### ISSUE TITLE
Switch to use Github actions

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#1007]
I think it would be interesting to use Github Actions now instead of travis.

**Comment by jtbayly** [comment]
Is this because of the $$ that Travis is charging to opensource projects now? What would the cost be to using Github actions?

**Comment by cderv** [comment]
It is more like an evolution in our workflow here following the community best practice I would say. 

IMO Github Actions has some advantages: 
* Integration right inside Github where the code live (I always like Gitlab CI for that when working with Gitlab on some project)
* All OS in the same service (no need of Appveyor + Travis)
* Less black box than travis / more flexible IMO
* New work for R ecosystem happens in GHA not travis (see https://github.com/r-lib/actions)
* Easy to setup (using `usethis` 📦 )

Choice of server is a matter of practice inside the development team and there is not a solution good for everyone.  I find that sharing common practices with others close to our work is also important, and it is an idea to remembered to make the switch.  

> What would the cost be to using Github actions?

Travis is free for OSS project with 10000 credit limits  vs Github all free without limit for OSS project I believe.

**Comment by jtbayly** [comment]
Here is a nice test case where somebody is attempting to switch to Github Actions and is having trouble:

https://stackoverflow.com/questions/64823120/bookdown-document-not-rendering-outputs-correctly

**Comment by cderv** [comment]
Thanks for sharing! 

I answered to him already on twitter this morning but it seems the user has not seen it.

**Comment by cderv** [comment]
I am not sure why this behaviour happens on GHA - I have seen this set as option for bookdown in some book, like mastering shiny: 
https://github.com/hadley/mastering-shiny/blob/de0620d3b1501f9f02a252f97e5a1b2c1ce0f15b/common.R#L21-L22

But yes I think we should update this example as the option can be passed directly in the setup-r action. 
Or at least do a PR so that we ask the question about this option. 

Good thinking ! thank you!
