### ISSUE TITLE
References in the Introduction

### ISSUE THREAD

**Issue by Nowosad** [rstudio/bookdown#102]
Some of the references are located in the introduction section in the newest version of `bookdown` package (for example here https://bookdown.org/yihui/bookdown/). Is there a way to disable this and have the references at the end of the book only?

**Comment by yihui** [comment]
I think this is more convenient for your readers because they don't need to jump to another page to see what a certain citation really is. Is there a reason that you don't want this feature? Or you simply don't like it?

**Comment by Nowosad** [comment]
I don't like it, mainly because it creates the same information in two places (only in the different order). Maybe you could add a new parameter in YAML, for example `references_in_chapters: true`?

**Comment by yihui** [comment]
Okay, I'll provide an option for that.

**Comment by yihui** [comment]
Done. Now you can use `split_bib = FALSE` for `gitbook()`.

**Comment by Nowosad** [comment]
Thanks!
