### ISSUE TITLE
add package installation instructions to ReadMe

### ISSUE THREAD

**Issue by kategorically** [rstudio/bookdown#103]
For people inexperienced in installing R packages from github, please add the appropriate command :)

**Comment by Nowosad** [comment]
#104 Pull request added

**Comment by yihui** [comment]
Installing the package is only a tiny step of using this package, and you have to read the doc https://bookdown.org/yihui/bookdown/ as I explained in #104. Anyway, I have updated README to make it more clear about how to get started. Thanks!
