### ISSUE TITLE
Ligature font doesn't render in Microsoft Edge

### ISSUE THREAD

**Issue by ntluong95** [rstudio/bookdown#1037]
Hi everyone,

I have a problem with ligature font. While I try to set a default font for the source code is JetBrains Mono, it worked well to render a book and preview in Rstudio. However, when I open it in Microsoft Edge, the ligature font doesn't display. Could you please help me fix this problem

Here is in R previewer:
![image](https://user-images.githubusercontent.com/63569637/100867688-d2224000-349a-11eb-9d1e-041f36a8a27f.png)

But when I open it in Microsoft Edge, it fail to display ligature font here:
![image](https://user-images.githubusercontent.com/63569637/100867802-f54cef80-349a-11eb-8773-5abc17cf469b.png)

**Comment by cderv** [comment]
Font support may depend on browser, so that is not so surprising to me. 

Several questions: 
* How do you use this font in your bookdown project ? Which format ? (EOT, WOFF, TTF, ... )
* Which is the version of Microsoft Edge you are using ? Is it the one based on Chrome or the previous version ? 

I don't think this is related to R or boodown package or RStudio. I believe it is working in RStudio because the browser engine used supports it, whereas your Edge version engine don't.

**Comment by ntluong95** [comment]
Thanks Christophe,

I used the newest version of Microsoft Edge. I also tried to download Google Chrome and set it as a default browser but nothing change. I noticed that when I knitted a normal Rmarkdown, it works precisely. But the case doesn't with bookdown.

I think i used TTF font. Which is the different between them and how I can you the others in my document.

Thank you.

**Comment by ntluong95** [comment]
I tried to download Firefox and render again. It can display well in Firefox. But when I try to open with Chrome, the same thing happened. Does that mean there is no way to render a ligature font to be displayed in different browsers?

**Comment by ntluong95** [comment]
I found the solution for that. Posted here for who want to figure out it:

@font-face{
    font-family: 'JetBrains Mono';
    src: url('https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/webfonts/JetBrainsMono-Regular.woff2') format('woff2'),
         url('https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/ttf/JetBrainsMono-Regular.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

* {
    -webkit-font-feature-settings: "liga" on, "calt" on;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
    font-family: 'JetBrains Mono';
}
