### ISSUE TITLE
pdf_document2 gives toc even if toc=FALSE

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#105]
I compiled a .Rmd file from on the command line as
`bookdown::render_book("myfile.Rmd", bookdown::pdf_document2(toc = FALSE))`

and also from the Rstudio knit button with the following in the YAML header:
```
output:
  bookdown::pdf_document2:
    toc: no
```
Either way, the table of contents  are still produced.

**Comment by yihui** [comment]
Thanks for the report! Fixed now.
