### ISSUE TITLE
Fix sharing images/meta tags generated by pandoc for bs4_book 

### ISSUE THREAD

**Issue by apreshill** [rstudio/bookdown#1050]
Hi- 

I'm noticing (thanks to @mine-cetinkaya-rundel) that `bs4_book` links are missing `<meta>` tags.

<img width="1259" alt="Screen Shot 2020-12-24 at 8 43 49 AM" src="https://user-images.githubusercontent.com/12160301/103092106-2ca74b80-45c4-11eb-8780-7b22bd3c4d44.png">

Same with tidytextmining, which I know used to work because I helped to fix the sharing images before 😉 

<img width="1259" alt="Screen Shot 2020-12-24 at 8 44 56 AM" src="https://user-images.githubusercontent.com/12160301/103092152-519bbe80-45c4-11eb-910f-5f087dd97951.png">

With `bookdown::gitbook` format, pandoc generated the `<meta>` tags correctly, provided the `cover_image` and `url` fields were filled in, like:

https://github.com/dgrtwo/tidy-text-mining/blob/dffbcc9d538f816cb8e545f039fa8f9ce6f5313a/index.Rmd#L16-L17

For example:
<img width="762" alt="Screen Shot 2020-12-24 at 8 38 00 AM" src="https://user-images.githubusercontent.com/12160301/103092213-8871d480-45c4-11eb-8501-bf8533f84de4.png">

When I search in the HTML of r4ds for example, I don't see the same `<meta>` tags for OpenGraph and twitter:
<img width="763" alt="Screen Shot 2020-12-24 at 8 47 05 AM" src="https://user-images.githubusercontent.com/12160301/103092267-b2c39200-45c4-11eb-97cd-2756cc80764e.png">

**Comment by maelle** [comment]
Related: #1034
