### ISSUE TITLE
kableExtra

### ISSUE THREAD

**Issue by wilson0106** [rstudio/bookdown#1063]
Hi,

I trying to use kableExtra in RMarkown for a text table as the following example:

```{r}
text_tbl <- data.frame(
  Items = c("Item 1", "Item 2", "Item 3"),
  Features = c(
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vehicula tempor ex. Morbi malesuada sagittis turpis, at venenatis nisl luctus a. ",
    "In eu urna at magna luctus rhoncus quis in nisl. Fusce in velit varius, posuere risus et, cursus augue. Duis eleifend aliquam ante, a aliquet ex tincidunt in. ", 
    "Vivamus venenatis egestas eros ut tempus. Vivamus id est nisi. Aliquam molestie erat et sollicitudin venenatis. In ac lacus at velit scelerisque mattis. "
  )
)
kbl(text_tbl, booktabs = T) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "red") %>%
  column_spec(2, width = "30em")
```

However I would to change the text of the table by inserting operators in one column and the example with some explanation in another, similar to this site: https://www.tutorialspoint.com/r/r_operators.htm. but I would like to see in output just the table with code inside, not the code that produce the table:

I produced this following code, with some variations, but not worked.

```{r}
text_tbl <- data.frame(
  Items = c(" <- ", " %in% "),
  Features = c(
    " Here it's an example: $x <- 3$",
    " Here it's an example: $c(1, 1, 1, 2, 5, 8, 10) %in% 1$ "
  )
)
kbl(text_tbl, booktabs = T) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "red") %>%
  column_spec(2, width = "30em")
```

Thank's

**Comment by cderv** [comment]
How familiar are you with **rmarkdown** ? 

Do you want to hide the source code chunk ? If so there is a chunk option for that (`echo = FALSE`) 
See https://bookdown.org/yihui/rmarkdown-cookbook/hide-one.html

To get more familiar with R Markdown you should consult the Definitive Guide: https://bookdown.org/yihui/rmarkdown/

If it is not what you seek, please can you share more details on your example ? 

Also for next time, if you have questions not issues, please consider asking on Q&A website following the issue guide (https://yihui.org/issue/) - thank you !

**Comment by wilson0106** [comment]
Hi cderv.

I'm understand a little of rmarkdown. But use kableExtra to do tables, in rmarkdown, is a little confusing yet to me.

Maybe my question was inadequately.

Trying to be more specific I would to know:
1) How can I add operators in a data frame that I will used in a table created by kable()?
2) How can I add a code in a data frame that I will run out inside a table created by kable()?

Hide source code isn't important a priori. But I know how to use echo.

OK, this and my other questions I will in https://yihui.org/issue/. But If you known how can I resolve this I appreciate.

Thank you

**Comment by cderv** [comment]
I am really not sure I understand what you want to achieve. The questions are unfortunately not clear for me.

From your example above, you can use HTML directly in the cells but you need to use `escape = FALSE` meaning you are doing the escaping yourself- we are talking about HTML escaping.

````markdown
---
title: "R Notebook"
output: html_document
---

```{r}
library(kableExtra)
text_tbl <- data.frame(
  Items = c(" &lt;- ", " %in% "),
  Features = c(
    " Here it's an example: <code>x &lt;- 3</code>",
    " Here it's an example: `c(1, 1, 1, 2, 5, 8, 10) %in% 1` "
  )
)
kbl(text_tbl, booktabs = T, escape = FALSE) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "red") %>%
  column_spec(2, width = "30em")
```
````

results in 
![image](https://user-images.githubusercontent.com/6791940/105318529-ee517c00-5bc3-11eb-8697-21ef3fdf05aa.png)


I may have misunderstood - in this case, please give some more details examples. Thank you.

**Comment by wilson0106** [comment]
Hi cderv,

Considering what I asked its it.
In my code I used this escape argument. But seeing your code I noted that my wrong was in not use: "code" or back accent " ` ".

Besides that, I would like PDF output so I noted that worked as I expected.

An implicit question is how can I execute the code and it show me the result? As the same example in the site that I added.
Because when I use print(x) or just x inner of " `  " the back accent or  "code", for example, the result wasn't appear.

For example, I trying insert in, Features column, this: "Here is result <code>print(x)</code> " waiting that it could show me the code and result, but it wasn't appear. The same thing I waited with this code `c(1, 1, 1, 2, 5, 8, 10) %in% 1` that result could appear.

```{r}
library(kableExtra)
text_tbl <- data.frame(
  Items = c(" &lt;- ", " %in% "),
  Features = c(
    " Here it's an example: <code>x &lt;- 3</code> Here is result <code>print(x)</code>",
    " Here it's an example: `c(1, 1, 1, 2, 5, 8, 10) %in% 1` Here is result ..."
  )
)
kbl(text_tbl, booktabs = T, escape = FALSE) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "red") %>%
  column_spec(2, width = "30em")
```

Thank you

**Comment by cderv** [comment]
Currently you can't include code chunks into a table. This is a limitation of how the **knitr** and **rmarkdown** works. This is tracked here: https://github.com/rstudio/rmarkdown/issues/1655

**Comment by wilson0106** [comment]
cderv. 

I will look for other ways to inform what I want.
I appreciate the time spent helping me.

Thanks a lot.

**Comment by cderv** [comment]
You're welcome ! 
Don't hesitate to share your concerns and ask for ideas in the RStudio community !
