### ISSUE TITLE
chapters in different folders

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#107]
https://github.com/rstudio/bookdown/blob/1e480ce6d069e1893d2c47b37f7f332093553def/R/render.R#L96 checks that all the chapters are in the current directory.

However, it is reasonable to sometimes use different folders for different chapters, especially if each of them have separate data files etc. and maybe different people are working on individual chapters. Separating the chapter filespaces would make working on them easier. Is this condition check really needed? Is there a workaround?

**Comment by yihui** [comment]
When the markdown output files of these chapters are merged, I will have to parse the markdown files, figure out the relative paths in them, and adjust these paths. For example, `dir1/chapter1.md` + `dir2/chapter2.md` -> `book.md`, then `![](figure/foo.png)` in `chapter1.md` has to be updated to `![](dir1/figure/foo.png)` in `book.md`.

I'd suggest all Rmd files in the root directory, and you can put data files anywhere you like, e.g. `chapter1.Rmd` can read `dir1/data/foo.csv`.

**Comment by yasirs** [comment]
Rmd files in the root directory and data elsewhere seems to be a reasonable approach for now.
