### ISSUE TITLE
Code output does not fully appear in PDF book output

### ISSUE THREAD

**Issue by MatthBogaert** [rstudio/bookdown#1076]
Dear all

When I tried to output my book as a pdf, I notice that a lot of the output code of R is removed (because it is longer than the page).  For example, when I take a `glimpse()` at my data part of the output is out of the limits of the page. 

I read that you can solve it in markdown with a preamble.tex file or with some knit options. 

Anyone else who has this issue and knows how to solve this?

<img width="810" alt="Schermafbeelding 2021-02-13 om 20 24 17" src="https://user-images.githubusercontent.com/50582137/107874812-86d5d600-6ebc-11eb-8fe3-2178f25c8662.png">

**Comment by cderv** [comment]
This is something that can happen with PDF outputs. We've documented some possible solutions in the R Markdown Cookbook. See https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html and https://bookdown.org/yihui/rmarkdown-cookbook/opts-tidy.html#opts-tidy

Unfortunately, there is no magic and you may need to find case by case solution. For example here in your source code, try to set the comments on more line. (So less characters per line in your source comments.

I'll close this as this is not an issue with **bookdown**. Please ask on Q&A sites like https://community.rstudio.com to have the community share their experience. 
The Bookdown Context that happens some times ago now could be a could source of examples to see how others deals with this. 

Thank you!
