### ISSUE TITLE
Workflow for nesting a bookdown within an existing project

### ISSUE THREAD

**Issue by jestarr** [rstudio/bookdown#1085]
Is there a "Best Practice" for how to create a bookdown within an existing project?  I'd be looking for best practice as far as directories I should create, and any other necessary files.  

I read this thread: https://github.com/rstudio/bookdown/issues/215, but the answer remains unclear to me.

**Comment by cderv** [comment]
**bookdown** will now have two functions for create a template if you don't want to use the IDE "New Project" feature
* `create_gitbook()`
* `create_bs4_book()`

Choose the one you want for the HTML book format which has your preference.

Help page: https://pkgs.rstudio.com/bookdown/reference/create_book.html

I think this will help for this. 

I'll close this issue now.
