### ISSUE TITLE
image size 

### ISSUE THREAD

**Issue by xiangzhu** [rstudio/bookdown#109]
Hi Yihui,

Does the default setting of image size change in `bookdown`?

In the past the width of image and text were well matched, but today I noticed that the image became smaller than the text. Is there any way to fix this problem? 

Here is one example.

![screenshot from 2016-05-07 10 53 10](https://cloud.githubusercontent.com/assets/5986023/15093100/659bedbe-1442-11e6-9c95-67c99e2672cd.png)

I use the following code to insert the image, and I do not use any chunk options of `knitr`.

```r
knitr::include_graphics("images/xxx.png")
``` 

Here is the repo of my `bookdown` example: https://github.com/xiangzhu/rss-gsea

Thanks for your time and help!

**Comment by yihui** [comment]
Good observation. There was a change in knitr that introduced the issue. If you want the previous output, you may add `dpi = NA` in `include_graphics()`. See knitr NEWS for v1.13: https://github.com/yihui/knitr/blob/master/NEWS.md

**Comment by xiangzhu** [comment]
Yes. Adding this option solves the problem. Thanks!

**Comment by xiangzhu** [comment]
Yes. Adding this option solves the problem. Thanks!
