### ISSUE TITLE
Bookdown is missing a LaTeX run with biblatex

### ISSUE THREAD

**Issue by adnion** [rstudio/bookdown#1104]
##### Checklist
- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [x] included a minimal, self-contained, and reproducible example?
- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?
- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github()` ?

##### Error
```
Warning message:
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please rerun LaTeX.
```

##### What I tried
First I asked @ biblatex https://github.com/plk/biblatex/issues/1109#issuecomment-802116941 
The issue is reproducible but not caused by biblatex.
Then I asked @ pandoc https://github.com/jgm/pandoc/issues/7158
Pandoc does not call biblatex (biber).

It must be a bookdown issue. 
Bookdown should run XeLaTeX the required number of times.

##### Steps to reproduce:
index.Rmd https://dpaste.org/tC0b
book.bib https://dpaste.org/GHKA
Save both files into an empty directory
start R and run `bookdown::render_book('index.Rmd', 'bookdown::pdf_book')`

**Comment by cderv** [comment]
I don't think this is a **bookdown** issue directly. Could be linked to **tinytex**. Using `rmarkdown::pdf_document` also throw the warning. 

Here is a self_contained example
````markdown
---
title: "A Chapman & Hall/CRC Book Example Using bookdown"
bibliography: packages.bib
graphics: yes
output:
  bookdown::pdf_book:
    keep_tex: true
    latex_engine: xelatex
    citation_package: biblatex
---

```{r, include = FALSE}
knitr::write_bib("knitr", "packages.bib")
```


I used the knitr package [@knitr2015]
````

Putting this in a new projec folder, I got warning with 

* `bookdown::render_book(".")`
* `rmarkdown::render("index.Rmd", rmarkdown::pdf_document(citation_package = "biblatex", latex_engine = "xelatex", keep_tex = TRUE))`

However, the result is ok. I see no issue with it. Is there anything wrong with the output ? 

I think we need to look at the **tinytex** level. 

If I use this tex file: 
````tex
\documentclass[]{article}

\usepackage[]{biblatex}
\addbibresource{packages.bib}

\title{A Chapman \& Hall/CRC Book Example Using bookdown}
\author{}

\begin{document}
\maketitle

I used the knitr package \autocite{knitr2015}

\printbibliography

\end{document}
````

I get this warning running: `tinytex::latexmk("index.tex", "xelatex", "bibtex")`
```
Warning message:
LaTeX Warning: Citation 'knitr2015' on page 1 undefined on input line 12.
LaTeX Warning: Empty bibliography on input line 14.
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                index
(biblatex)                and rerun LaTeX afterwards. 
````
So I see the same warning that the one return. and I see that with all 3 engines. 

I'll look closer on the tinytex side for this warning to see if a run is missing or if the warning is thrown but should be ignore.

**Comment by cderv** [comment]
Ssome notes: I tried to simplify with this tex file 
````tex
\documentclass[]{article}

\usepackage[]{biblatex}
\addbibresource{book.bib}

\title{A Chapman \& Hall/CRC Book Example Using bookdown}
\author{}

\begin{document}
\maketitle

I used the knitr package \autocite{knitr2015}

\printbibliography

\end{document}
````
using the `book.bib`
```bib
@Book{xie2015,
  title = {Dynamic Documents with {R} and knitr},
  author = {Yihui Xie},
  publisher = {Chapman and Hall/CRC},
  address = {Boca Raton, Florida},
  year = {2015},
  edition = {2nd},
  note = {ISBN 978-1498716963},
  url = {http://yihui.name/knitr/},
}
```

and running 
````r
latexmk("test.tex", "xelatex", "biber")
````

I got the same error (plus a little more)
```
> latexmk("test.tex", "xelatex", "biber")
[1] "test.pdf"
Warning message:
LaTeX Warning: Citation 'knitr2015' on page 1 undefined on input line 12.
LaTeX Warning: Empty bibliography on input line 14.
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                test
(biblatex)                and rerun LaTeX afterwards. 
```

**Comment by cderv** [comment]
Ok I think it is a tinytex issue where one run is missed because the log contains 
```
Package biblatex Warning: Please rerun LaTeX.
```
but `tinytex::needs_rerun()` does not catch it. 

I'll push a fix in **tinytex**
