### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sje30** [rstudio/bookdown#111]
Hi, trying to install from your instructions

    devtools::install_github("rstudio/bookdown")

I get the following error:

```
Downloading GitHub repo rstudio/bookdown@master
Installing bookdown
Error: Malformed remote specification 'yihui/knitr'
```

**Comment by yasirs** [comment]
Do you have the latest devtools? Try updating devtools and doing `library(devtools)`.

**Comment by sje30** [comment]
Thanks!  that did it.
