### ISSUE TITLE
[FR] internationalization - Customize figure names to set label after number 

### ISSUE THREAD

**Issue by tamas-ferenci** [rstudio/bookdown#1114]
(Already posted in Stackoverflow [here](https://stackoverflow.com/questions/54158401/customize-figure-name-just-as-chapter-name-in-bookdown) to no avail.)

Bookdown [allows the customization][1] of chapter names, which is handy when a Hungarian project is built, as `Chapter 1` is translated as `1. fejezet` (i.e. the renaming of `Chapter` is not enough).

However, the very same is true for figure (and table) names as well, because `Figure 1.1` should be translated as `1.1. ábra`, but I don't know how to achieve this (`_bookdown.yml` doesn't seem to support something like "`language/ui/figure_name`" just as it does with `chapter_name`).

There is no problem with the PDF (LaTeX) output, because including `\usepackage[magyar]{babel}` in the `preamble.tex` solves this problem, but I don't know what to do with the non-PDF formats, where my only idea was to use the `_bookdown.yml`.

  [1]: https://bookdown.org/yihui/bookdown/internationalization.html

**Comment by tamas-ferenci** [comment]
Because the translation of Figure should go _after_ the number, not before it (as I have written: "`Figure 1.1` should be translated as `1.1. ábra`") and this is not possible with the possibilities listed in that doc, where I can only change the text, but I can't put it after the number in my understanding.

**Comment by cderv** [comment]
That is right, this is currently not possible to do that. Thanks for explaining. 

It will always be `<fig_lab>: <number>` for now. 

Out of curiosity, in which language do you label figure this way ?

**Comment by tamas-ferenci** [comment]
It's Hungarian. The reason why I hope for a possible new feature to support this is that the exact same thing is already working for chapter name! The cited doc even gives an example for this. The very same solution would be perfect for figure (and table) names.

**Comment by cderv** [comment]
You mean the use of a function taking chapter number as argument ? Is that what you use for chapter name ?

**Comment by tamas-ferenci** [comment]
Yes, `Chapter 1` is translated as `1. fejezet`. The solution is therefore simply:

```
language:
  ui:
    chapter_name: !expr function(i) paste0(i, ". fejezet")
```

A similar solution would be perfect for figure and table naming.

**Comment by yihui** [comment]
That sounds like a reasonable feature request to me.

**Comment by tamas-ferenci** [comment]
Thanks @yihui ! Together with https://github.com/rstudio/bookdown/issues/671 it'd make bookdown very nicely working for Hungarian as well :)

**Comment by cderv** [comment]
@tamas-ferenci you may try #1120
```r
remotes::install_github("rstudio/bookdown#1120")
```

where this should work now 
```yaml
language:
  label:
    fig: !expr function(i) paste(i, 'ábra')
  ui:
    chapter_name: !expr function(i) paste0(i, '. fejezet')
```

**Comment by tamas-ferenci** [comment]
Thank you very much @cderv and @yihui ! I checked it, and it indeed seems to work fine! I only see two (very minor) problems:

- The documentation says `fig: !expr function(i) paste(i, 'ábra')` which is technically correct, but the Hungarian typography would imply `fig: !expr function(i) paste0(i, '. ábra.')`.
- There is no space between the end of the text inserted and the first letter of the figure caption:
![kép](https://user-images.githubusercontent.com/25476790/113472199-c0a96e80-9461-11eb-927e-5efb2dec1fd8.png)
That's not a huge problem as one could easily circumvent it with `fig: !expr function(i) paste(i, '. ábra. ')`, but this was not needed for `chapter_name` (where even `!expr function(i) paste0(i, '. fejezet')` results in a space after `fejezet` and before the chapter name), so the two are not perfectly consistent right now.
