### ISSUE TITLE
Subscripts within in-line math

### ISSUE THREAD

**Issue by ccolonescu** [rstudio/bookdown#112]
Is there any way I could write an in-line math symbol or equation that contains subscripts? I need, for instance, what in LaTeX is $\beta\\_1$ (if I am not mistaken).

**Comment by yihui** [comment]
Isn't it just `$\beta_1$`? I don't know why you need the backslash before the underscore.

**Comment by ccolonescu** [comment]
It works, thank you. I was confused because the underscore changes the color of the text after it, but the output is fine.

**Comment by yihui** [comment]
You probably need to upgrade RStudio if you are using it, otherwise it sounds like a syntax highlighting issue of your text editor.
