### ISSUE TITLE
preview_chapter() does not work with Rmd files in a sub-directory

### ISSUE THREAD

**Issue by mklienz** [rstudio/bookdown#1121]
preview_chapter works as intended for previewing Rmd files that are in the root directory. However, it does not render the same Rmd file that is within a subdirectory.

I'm not sure whether the inability to preview Rmds in subdirectories is intentional or not. For our purposes, we are putting Rmd content in a subdirectory within the root folder, so that the root folder doesn't become overwhelmed. It would be nice to be able to preview chapters without needing to render the whole book.

Here is a reprex using the [bookdown-demo](https://github.com/rstudio/bookdown-demo) as an example; note that I've used `render_book(preview = TRUE)` rather than `preview_chapter` but should be functionally equivalent. Hopefully it makes sense, I can clarify anything if needed.

```r
# Using https://github.com/rstudio/bookdown-demo as an example
# While all content in the root directory
bookdown::render_book("index.Rmd", "bookdown::gitbook") # works
bookdown::clean_book(TRUE)
bookdown::render_book("01-intro.Rmd", "bookdown::gitbook", preview = TRUE) # works
bookdown::clean_book(TRUE)

# Now move the book contents to a subdir = content
# Need to add rmd_subdir: ["content"] and rmd_files: ["index.Rmd"] to _bookdown.yml
bookdown::render_book("index.Rmd", "bookdown::gitbook") # works
bookdown::clean_book(TRUE)
bookdown::render_book("content/01-intro.Rmd", "bookdown::gitbook", preview = TRUE) # blank html pages
```

**Comment by cderv** [comment]
Thanks. I can reproduce. 

I don't know if this is on purpose or not. It seems like a bug to me. As **bookdown** allows to set Rmd in subdir, it should be able to preview one of this file too. 

> It would be nice to be able to preview chapters without needing to render the whole book.

Are you using RStudio to preview by clicking the Knit button or always the command line as in example ?

**Comment by cderv** [comment]
In fact using dev version of **bookdown** and running 
```r
bookdown::render_book("content/01-intro.Rmd", "bookdown::gitbook", preview = TRUE)
```
will correctly only build `_book/intro.html`

As you ran `bookdown::clean_book(TRUE)` not other HTML file exist. They are created but empty as you explicitly ask to preview only `intro.html`. If you open the resulting `_book/intro.html` you should get a correct file. 
For all other you will get blank page. 

The workflow with preview is mainly aimed at `bookdown::serve_book()`: 

1. Build the book once
2. Only build modified file after that 

However, there is an issue when clicking with the knit button that is not working as expected. 

Can you retry the above and confirm this is how it works for you ?

**Comment by cderv** [comment]
> However, there is an issue when clicking with the knit button that is not working as expected.

Oh in fact the Knit button does not work as expected when a file is in the sub folder. It calls `rmarkdown::render()` and not `rmarkdown::render_site()` - we may need to do something like for **blogdown**

Anyway, @mklienz for your issue, I think it is working as expected - previewing will only build one HTML file. If you did not have built the book once before, all the other HTML file will be blank.
