### ISSUE TITLE
Create `bs4_book` project template

### ISSUE THREAD

**Issue by apreshill** [rstudio/bookdown#1123]
Hi @yihui and @cderv,

In prep for next package release with `bs4_book` output format, we discussed creating a project template with:

1. A project accessible from RStudio project wizard to create  "A Bootstrap-4 HTML book using bookdown"
2. A checkbox for users using GitHub Pages to automatically add the `.nojekyll` file and change the output directory to `docs/` (same as Distill's website, see: https://github.com/rstudio/bookdown/issues/1092; https://github.com/rstudio/bookdown/issues/1087)
3. I'm happy to write some filler text into the book skeleton for this so that the example book gives some minimal instructions for users.
4. An exported function like `create_bs4_book()` to do the same as above from the command line (see: https://github.com/rstudio/bookdown/issues/225); also like Distill's `create_website()` function: https://pkgs.rstudio.com/distill/reference/create_website.html)

**Comment by cderv** [comment]
Thanks for opening so that we don't forget ! 

`bookdown::gitbook()` or `bookdown::bs4_book()` is only format you can change in `_output.yml` in the current existing template. I had in mind adapting and updating the current template.

Would that be worth maintaining two templates ? 

We need at least to add `bs4_book()` to the current template, and work on the `create_book()` function as we discussed (Which is tracked in #225)

What would be the main difference in content than the current gitbook format ? 
What specific content do you see for `bs4_book()` that would not be possible to add in the current template ?

**Comment by apreshill** [comment]
Ah ok- I was thinking of adding a new project template. One of the biggest differences is the one .Rmd per chapter in `bs4_book`, so I was thinking the template would be a great way to make sure that is clear right off the bat. The current skeleton includes a `preamble.tex` file that won't apply, and a CSS file that probably will not work with the bootstrap-based format.

**Comment by cderv** [comment]
> One of the biggest differences is the one .Rmd per chapter in bs4_book, so I was thinking the template would be a great way to make sure that is clear right off the bat. 

`split_by='chapter'` is the default for `gitbook()` too. You just can change it for `gitbook()` and not in `bs4_book()`. The template skeleton currently respect the default, so it would work for both. ([template is here](https://github.com/rstudio/bookdown/tree/master/inst/rstudio/templates/project/resources))

> The current skeleton includes a preamble.tex file that won't apply, and a CSS file that probably will not work with the bootstrap-based format.

The current template is several Rmd files and all the content needed to show how to build in several formats contained in [`_output.yml`](https://github.com/rstudio/bookdown/blob/master/inst/rstudio/templates/project/resources/_output.yml) - `bs4_book()` could be added with a custom css file different than the other. The [current css](https://github.com/rstudio/bookdown/blob/master/inst/rstudio/templates/project/resources/style.css) is very limited for now though, so I think it would work with `bs4_book()`. 

So either we consider than the template should show everything, and the user keeps what is needed. Or we create several book project demo like `bookdown-demo` showing `gitbook()` OR `bs4_book()` + other non HTML.  
`preamble.tex` would still be required if you want to build your book to `bs4_book()` and `pdf_book()`, so it also should be include in a `bs4_book()`.

In fact, I think I don't see anything specific to `bs4_book()` that would require a new template. Usually I test `bs4_book()` by just rendering bookdown-demo to this format without changing anything.  I'll try to look closely to the differences in configuration of this two HTML format. 

I am just trying to get a correct understanding before doing anything. I see that as either a `create_book() or * either a `create_bs4_book()` and `create_gitbook()`. but would that mean `create_pdf_book()` or `create_tufte_book()` - I don't think so. I always see the format as something you can modify keeping the same project. Maybe `create_book()` with parameters like `blogdown::new_site()` ? 🤔

**Comment by apreshill** [comment]
That sounds great to me! `create_book(output = gitbook)` or `create_book(output = bs4_book)` Glad to know this is easy :)

**Comment by cderv** [comment]
I'll make a first draft and we'll iterate. I am not sure yet of the full differences. 
It could also depend on how much we can adapt `bs4_book()` to some missing `gitbook()` configurations (like adding `description:` in the YAML for metadata)

**Comment by apreshill** [comment]
Decision based on conversation with @cderv: we'll have a single project in the repo (https://github.com/rstudio/bookdown/tree/master/inst/rstudio/templates/project), will edit these files to update with minimal additions:

+ add `url` and `cover-image` to `index.Rmd` YAML here: https://github.com/rstudio/bookdown/blob/3c4eca3122474229adbc6807c8203a286f2f963a/inst/rstudio/templates/project/resources/index.Rmd#L10

+ add `bookdown::bs4_book` here: https://github.com/rstudio/bookdown/blob/3c4eca3122474229adbc6807c8203a286f2f963a/inst/rstudio/templates/project/resources/_output.yml#L1

+ figure out: does `bs4_book` expect `new_session: TRUE`? https://github.com/rstudio/bookdown/blob/3c4eca3122474229adbc6807c8203a286f2f963a/inst/rstudio/templates/project/resources/_bookdown.yml#L1

+ figure out: does `style.css` work with `bs4_book` as is? https://github.com/rstudio/bookdown/blob/master/inst/rstudio/templates/project/resources/style.css

+ include how to add `before_chapter_script` since this was fixed semi-recently? https://pkgs.rstudio.com/bookdown/news/index.html#bug-fixes-4
