### ISSUE TITLE
Should local search with bs4_book work locally?

### ISSUE THREAD

**Issue by maelle** [rstudio/bookdown#1137]
Currently local search with bs4_book works online but not locally.

https://github.com/rstudio/bookdown/blob/674001be1e718856b1531980ab7ed1576a438a9f/inst/resources/bs4_book/bs4_book.js#L38

results in the error `Fetch API cannot load file:///bla/bla/_book/search.json. URL scheme must be "http" or "https" for CORS request`.

Is this expected @hadley?

**Comment by maelle** [comment]
Notes from some search.

https://www.edureka.co/community/83684/how-to-read-an-external-local-json-file-in-javascript looks interesting.

**Comment by hadley** [comment]
Yes; I don't think it's worth the effort to get working locally.

**Comment by maelle** [comment]
good to know when testing one's code locally :grin:

**Comment by cderv** [comment]
I believe if you serve the book using `bookdown::serve_book()` (or with **servr** 📦 directly) the search will work. It did when I tested, and this is how you are suppose to do testing one running locally. At least, the JSON file will be available through https and you won't get the CORS request issue.

**Comment by maelle** [comment]
Right, I should have been more precise, I was wondering whether it should work when not serving anything. I came here because of experimenting with this for pkgdown. 
Thank you!
