### ISSUE TITLE
Citation inside figure caption as verbatin in LaTeX PDF

### ISSUE THREAD

**Issue by rgaiacs** [rstudio/bookdown#1138]
Consider the following minimal working example:

``````
---
title: "Untitled"
author: "Raniere Silva"
date: "16/04/2021"
output:
  bookdown::html_document2:
  bookdown::pdf_document2:
bibliography: references-from-zotero.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r motor-neuron, fig.cap = "ggplot2 logo. Source: [@ggplot2].", out.width = "100%", fig.align = 'center'}
knitr::include_graphics("ggplot2-logo.png")
```
``````

Convert the document to HTML and PDF do not raise any error. The following image illustrate the output with the HTML output in the left and the PDF output in the right.

![Screenshot from 2021-04-16 14-23-10](https://user-images.githubusercontent.com/1506457/114980857-af2f8000-9ebf-11eb-8ae3-640013fb18cc.png)

The HTML document has `Figure 1: ggplot2 logo. Source: (Wickham 2016).` for the caption and the PDF document has `Figure 1: ggplot2 logo. Source: [@ggplot2].` for the caption. In the PDF document, the citation inside the caption is **not** translated properly.

# Supplementary documents

`references-from-zotero.bib`:

```
@book{ggplot2,
author = {Hadley Wickham},
title = {ggplot2: Elegant Graphics for Data Analysis},
publisher = {Springer-Verlag New York},
year = {2016},
isbn = {978-3-319-24277-4},
url = {https://ggplot2.tidyverse.org},
}
```

`ggplot2-logo.png`: https://github.com/tidyverse/ggplot2/blob/master/man/figures/logo.png

**Comment by cderv** [comment]
For this to work, the caption need to be processed as Markdown by Pandoc. 

You need to use the special Text Reference feature in **bookdown** design for this: 
https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references

> Then you can use (ref:foo) in your figure/table captions. The text can contain anything that Markdown supports, as long as it is one single paragraph.


I let you try

**Comment by rgaiacs** [comment]
Thanks for the reply. The text references worked.

**Comment by cderv** [comment]
Glad it works ! That is currently the way to do this.
