### ISSUE TITLE
KM mode not isolating R session variables in chapters

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#114]
I modified the bookdown-demo to build in the KM mode, and also added a check by defining a variable in Chap 2, and checking in Chap 4. The code is given in my branch https://github.com/yasirs/bookdown-demo/tree/KM-mode. Even when compiling with the KM mode (`new_session: yes` in `_bookdown.yml`), the variable is visible in a different chapter.

This behavior is different from the what the docs say at https://bookdown.org/yihui/bookdown/new-session.html.

The variable is defined as in https://github.com/yasirs/bookdown-demo/commit/93669f53d55bab5fda0de3ae51af38ee1d5ca1ec#diff-547c34c529c929ed3009c085b95fa811, and checked at https://github.com/yasirs/bookdown-demo/commit/93669f53d55bab5fda0de3ae51af38ee1d5ca1ec#diff-6ddc9ccae11241992ce38be8c4708ccf.

I am using the Preview version of RStudio (Version 0.99.1172) to build.

**Comment by yasirs** [comment]
Okay, so in the Rstudio build book menu, if I click Build Book > All Formats, the variables are visible (new_session: yes is ignored). However, if I click a single format like Build Book > bookdown::pdf_book then it builds correctly in KM mode and the sessions are separate. There is probably some bug in rstudio.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
