### ISSUE TITLE
Search ignores indented text

### ISSUE THREAD

**Issue by dmklotz** [rstudio/bookdown#1141]
I'm writing a book that features many quotations of poetry, so I have been relying heavily on the line blocks feature to force indentation in rmarkdown: [https://bookdown.org/yihui/rmarkdown-cookbook/indent-text.html](https://bookdown.org/yihui/rmarkdown-cookbook/indent-text.html)

However, now that I'm building a **bs4_book**, the Search tool apparently skips any lines of text that begin with "|", and won't come up with any results.  If the same word is used in regular text on the same page, the search tool will highlight that page, and the indented example will be highlighted correctly.

**Comment by cderv** [comment]
I can confirm that this works ok in the search for used by `gitbook()` format but it does not with `bs4_book()`.

**Comment by maelle** [comment]
For future reference here's what I added for this in the pkgdown local-search branch [`3f4623f` (#1629)](https://github.com/r-lib/pkgdown/pull/1629/commits/3f4623f88b7e2f4f2a4c1fae61c30ccc88563ec7)

**Comment by cderv** [comment]
@apreshill this is possible that we want to fix that for next release. 
@maelle you seem to have a solution, is that it ?

**Comment by maelle** [comment]
yes this was fixed for pkgdown so I can port the fix.
