### ISSUE TITLE
bad argument #1 to 'insert' (table expected, got nil)

### ISSUE THREAD

**Issue by config-i1** [rstudio/bookdown#1144]
Unfortunately, I cannot produce a minimal, self-contained, and reproducible example for this, but I'm eager to help if you can help me narrow it down to something. I get the following error when compiling a textbook on bookdown v0.21 and higher (including the github version) after the .Rmd file is created:

> /usr/bin/pandoc +RTS -K512m -RTS adam.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output adam.html --lua-filter /usr/local/lib/R/site-library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /tmp/RtmpAFsf8u/file113e16feb99fa --wrap preserve --standalone --section-divs --table-of-contents --toc-depth 3 --template /usr/local/lib/R/site-library/bookdown/templates/gitbook.html --highlight-style pygments --number-sections --css style.css --include-in-header /tmp/RtmpAFsf8u/rmarkdown-str113e14ef04379.html --mathjax --include-in-header hypothesis.html --include-in-header google_analytics.html --include-before-body open_review_block.html --include-after-body call_to_action_block.html --filter /usr/bin/pandoc-citeproc 
> Error running filter /usr/local/lib/R/site-library/bookdown/rmarkdown/lua/custom-environment.lua:
> ...te-library/bookdown/rmarkdown/lua/custom-environment.lua:182: bad argument #1 to 'insert' (table expected, got nil)
> stack traceback:
>         [C]: in function 'table.insert'
>         ...te-library/bookdown/rmarkdown/lua/custom-environment.lua:182: in function 'Div'
> Error: pandoc document conversion failed with error 83
> Execution halted

This works fine on v0.20 and earlier. I tried googling different parts of this error, but nothing relevant comes up.

This is the book I try to compile: https://github.com/config-i1/adam

Session info:
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Locale:
  LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
  LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
  LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
  LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

Package version:
  base64enc_0.1.3   digest_0.6.27     evaluate_0.14     glue_1.4.2       
  graphics_4.0.5    grDevices_4.0.5   highr_0.9         htmltools_0.5.1.1
  jsonlite_1.7.2    knitr_1.32        magrittr_2.0.1    markdown_1.1     
  methods_4.0.5     mime_0.10         rlang_0.4.10      rmarkdown_2.7    
  stats_4.0.5       stringi_1.5.3     stringr_1.4.0     tinytex_0.31     
  tools_4.0.5       utils_4.0.5       xfun_0.22         yaml_2.2.1       

Pandoc version: 2.5

**Comment by cderv** [comment]
Thanks for the report. Sharing your repo is already a good way for us to look into this. 

This is an error in one of the Lua Filter used. This should only trigger if you are using one of the support custom environment from https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems

One possible hint: You are using Pandoc 2.5. Is this possible for you to update ? 
https://bookdown.org/yihui/rmarkdown-cookbook/install-pandoc.html

I'll try on my side to with this version and newer to reproduce your issue.

**Comment by cderv** [comment]
Forget about Pandoc version - I can reproduce with your projet and Pandoc 2.11.4. 

You are indeed using block engine
````markdown
```{block, type="remark"}
...
```
````

This should be ignore by the Lua filter and it seems I don't handle correctly this case. I'll look into it. 

FYI, **bookdown** supports a new syntex now and you could write 
````markdown
::: remark
<content here>
:::
```
instead of the above.

**Comment by cderv** [comment]
Now I understand. 

When we develop support for this new syntax, 
````
::: remark
<content here>
:::
````

It was in replacement of this syntax
````
```{remark}
...
```
````

So currently we did not expect this usage using the `block` engine. This special usage is not catched by our filter. We are handling the currently documented way: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems

I can try fix it by adding another detection rule. However, I would like to know as your are the first to encounter this so not many user are using this syntax: how about changing to the new syntax for your blocks of Theorem and Proof Environment ? 

And by the way, you can use it with your special environment too
````
```{block, type='adamCitation'}
- Svetunkov, I. (2020) Time Series Analysis and Forecasting with ADAM: Lancaster, UK. openforecast.org/adam. Accessed on [current date].
```
````

should become 
````
::: {.adamCitation latex=true}
- Svetunkov, I. (2020) Time Series Analysis and Forecasting with ADAM: Lancaster, UK. openforecast.org/adam. Accessed on [current date].
:::

See https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

**Comment by config-i1** [comment]
Thanks for the rapid response! The new syntax sounds good. I'll experiment with it and probably will switch to it.

**Comment by cderv** [comment]
This new syntax is a lot better as you'll be able to use any R Markdown valid syntax inside the block. 
We still need to update the documentation and finish support for other format. 

I'll wait for your feedback, and if this is fine with you I may not add another special usecase for this `block` engine usage.

**Comment by config-i1** [comment]
Done. The new one works like a charm. Thanks a lot!
Just a thought: would it make sense to make a warning or something to those using the old style blocks?

**Comment by cderv** [comment]
> would it make sense to make a warning or something to those using the old style blocks?

Just to be clear - the old style block is 
````markdown
```{remark}
...
```
````
and still works. 

We decided for now to still supports it and maybe warn in the future when ready to be removed. 

What is not supported is using `block` engine with a type one of https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems

I don't know if a lot of users are doing this as this is not the documented way. Where did you find this syntax ? 

We could warn about that, but it that case it is like adding a specific handling for it and supports it.

**Comment by config-i1** [comment]
Okay, cool.
I don't remember, where. Probably here: https://bookdown.org/yihui/bookdown/custom-blocks.html

**Comment by cderv** [comment]
Oh sure. 

I should definitly update this part of the doc. Part of https://github.com/rstudio/bookdown/issues/939

**Comment by cderv** [comment]
I'll close this and we'll reopen if there are more problem like this one. Thank you !
