### ISSUE TITLE
[FR] Add `split_bib` to `bs4_book`

### ISSUE THREAD

**Issue by shirdekel** [rstudio/bookdown#1146]
At the moment the `bookdown::bs4_book` output does not use a `split_bib` argument, like `bookdown::gitbook`. However, I noticed that it seems to be [`FALSE` by default](https://github.com/rstudio/bookdown/blob/2d692ba4b61f1e466c92e78fd712b0ab08c11d31/R/bs4_book.R#L115). Is there a reason why the user can't be given control of this through an argument in `bookdown::bs4_book`? I tried this out in my fork and it seems to work fine, so happy to submit a PR.

**Comment by sstoeckl** [comment]
I would very much like that feature! Could you submit the PR?

**Comment by shirdekel** [comment]
Here it is: https://github.com/rstudio/bookdown/pull/1185
