### ISSUE TITLE
Extra space at beginning of first line of code chunk with bs4_book

### ISSUE THREAD

**Issue by pschloss** [rstudio/bookdown#1148]
When I build a site using `bs4_book` I'm noticing that the first line of each code block is indented relative to the subsequent lines in the code block. I was able to produce this with the default bookdown book and by adding the following to the top of `_output.yml`

```
bookdown::bs4_book:
  theme:
    primary: "#6D90F0"
    fg: "#2b2121"
    bg: "#ffffff"
```

Here's the first code block of Chapter 2 of the "Minimal Book Example" with a red line to highlight the indenting...

<img width="782" alt="Screen Shot 2021-04-28 at 16 49 43" src="https://user-images.githubusercontent.com/1264132/116470863-f3b50700-a841-11eb-95ed-30d9ef2e7a20.png">

My CSS skills aren't strong enough to track down what is causing this. I'm assuming that desired appearance is that the lines of a code block should be left justified. Looking at code blocks in [R4DS](https://r4ds.had.co.nz/workflow-scripts.html#running-code), which was generated with `bs4_book` shows those lines are all left justified. 

```R
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bookdown_0.22.2

loaded via a namespace (and not attached):
 [1] compiler_4.0.5    htmltools_0.5.1.1 tools_4.0.5      
 [4] yaml_2.2.1        rmarkdown_2.7     knitr_1.33       
 [7] xfun_0.22         digest_0.6.27     rlang_0.4.10     
[10] evaluate_0.14    
```

**Comment by cderv** [comment]
Hi, thanks for the report. 

Can you check your **bslib** version and use the last dev version ? it is not in your session info.
I think this issue has been fixed there.

Thanks.

**Comment by cderv** [comment]
I believe this is the issue that was fixed on **bslib** side: https://github.com/rstudio/bslib/issues/236

I let you check with last dev version before closing

**Comment by pschloss** [comment]
That did it - thanks! Shouldn't `bslib` get updated when I installed the dev version of `bookdown`?

**Comment by cderv** [comment]
No it won't because **bslib** is only a suggested dependency as it is only useful for `bs4_book()`. 
It is not a strong dependency with a specific requirement. So we did not add a Remote field for **bslib** so that we are not blocked for a new CRAN release of **bookdown** by this Suggested package. 

A new version of **bslib** will probably be on CRAN soon. If not, we'll add the field after next bookdown release. 

As it is solved, I'll close this one - thanks for asking !
