### ISSUE TITLE
! LaTeX Error: File `titling.sty' not found.

### ISSUE THREAD

**Issue by ccolonescu** [rstudio/bookdown#115]
I get an error message when I try to knit to word or pdf, but html works OK. How can I create this titling.sty file? I'm using windows.

"C:/Users/COLONE~1/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS RPoE.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output RPoE.pdf --template "C:\PROGRA~1\R\R-32~1.5\library\RMARKD~1\rmd\latex\DEFAUL~3.TEX" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --bibliography book.bib --bibliography packages.bib --filter pandoc-citeproc 
! LaTeX Error: File `titling.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.107 

pandoc.exe: Error producing PDF
Error: pandoc document conversion failed with error 43
In addition: Warning message:
running command '"C:/Users/COLONE~1/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS RPoE.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output RPoE.pdf --template "C:\PROGRA~1\R\R-32~1.5\library\RMARKD~1\rmd\latex\DEFAUL~3.TEX" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --bibliography book.bib --bibliography packages.bib --filter pandoc-citeproc' had status 43

**Comment by ccolonescu** [comment]
Here is the command I try to execute: 
 render_book("~\\RPoE", output_format="pdf_document", output_dir="C:\\Users\\colonescuc\\Desktop")

**Comment by yihui** [comment]
You need to install the `titling` package using the MikTeX package manager.
