### ISSUE TITLE
Starting a bookdown project

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#116]
The bookdown-demo Rstudio project seems to be the standard way to go about things according to the tutorial. However, how do you actually start a new bookdown project in Rstudio? Even with the Rstudio preview release version, new project options are only empty. shiny website, and package? If you open a new empty project, the Book Build tools don't show up. Screenshot attached.

![screen shot 2016-05-16 at 5 11 25 pm](https://cloud.githubusercontent.com/assets/400538/15304550/f9641f12-1b8b-11e6-8967-8312a9929229.png)

**Comment by jjallaire** [comment]
The bookdown-demo folder actually has an RStudio .Rproj file within it.
Just double-click that file or open it within RStudio.

**Comment by yasirs** [comment]
Yes, I understand that one can open the bookdown-demo project this way. My
concern is that one should be able to start a new bookdown Rstudio project
for their own work from Rstudio, just like one can for a package or a shiny
website. Right now the only way to do so is to first download the
bookdown-demo project and then start writing your own document in that
folder and delete the demo chapters.

**Comment by jjallaire** [comment]
Agree completely, we just haven't yet added this capability to RStudio (we
will!)

**Comment by yihui** [comment]
I have logged this issue and will report back once this feature is available in the IDE.
