### ISSUE TITLE
Should the `echo = FALSE` global option hide theorem chunks?

### ISSUE THREAD

**Issue by judgelord** [rstudio/bookdown#1164]
A documentation suggestion and question responding to a helpful discussion in closed issues #220 and #257: 

> Hmm, perhaps it is just a bad idea for me to use `echo=FALSE` to hide theorems. The documentation is kind of hidden here: https://bookdown.org/yihui/bookdown/custom-blocks.html Thanks @rtaph!

_Originally posted by @yihui in https://github.com/rstudio/bookdown/issues/257#issuecomment-264097294_

Like @Selbosh and @rtaph, I did not expect theorem chunks to obey `echo`. (It makes sense but sure had me confused for a while!)

As @yihui noted, `echo` behavior is noted in the docs on Custom blocks:

> For all custom blocks based on the block or block2 engine, there is one chunk option echo that you can use to show (echo = TRUE) or hide (echo = FALSE) the blocks.

However, `echo` is not yet mentioned in the docs on theorems: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems

As theorem chunks are most likely to be used in documents where knitr options are set globally to `echo = FALSE`, could theorem chunks just ignore default knitr options and only be hidden if `echo = FALSE` appears in the local chuck options? I know this would be unusual chunk behavior, but I honestly can't think of a use case for hiding all theorems since they have no output or side effects.

**Comment by cderv** [comment]
Hi @judgelord, 

Thanks for you suggestion. 

We have a new to write theorem & proof that will replace in the long term the current theorem engine based on block and block 2 engines. We are late on the documentation update but this is already working. 

This is powered by a new Custom Block syntax that are better for this kind of task : https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

This 
````markdown
```{theorem, foo, name="Pythagorean theorem"}
For a right triangle, if $c$ denotes the length of the hypotenuse
and $a$ and $b$ denote the lengths of the other two sides, we have
$$a^2 + b^2 = c^2$$
```
````

is replaced by

````markdown
::: {.theorem #foo name="Pythagorean theorem"}
For a right triangle, if $c$ denotes the length of the hypotenuse
and $a$ and $b$ denote the lengths of the other two sides, we have
$$a^2 + b^2 = c^2$$
:::
````

Among other advantages (you can write any markdown content inside the block), this new syntax won't be impacted by global knitr chunk options. 

We provide a `bookdown::fence_theorems()` helper to help convert existing source to this new syntax. 

Would that solve your issue ? 

This is still widely undocumented (only in NEWS and Github Issues mainly) so very new but it has been around for some versions now, and we plan to deprecate the old way to this new syntax. 

Would that work for you ?

**Comment by cderv** [comment]
Thanks for the great suggestion. We'll do it! 

I think I will also prioritize the documentation of this new syntax in chunk. Just a warning: This is support for HTML and PDF only for now. Saying just in case. (And this is why it is not yet documented fully in place of the old way).
