### ISSUE TITLE
No paragraph environments for new paragraphs in math components

### ISSUE THREAD

**Issue by AstrickHarren** [rstudio/bookdown#1169]
This is a screenshot from the _Authoring books with R markdown_: 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/33888523/121049255-1d226480-c7ea-11eb-981c-9cb0180a1eee.png">

There is an extra line break in front of each `<span>`, it seems a missing `<p>` for the paragraph causes this glitch.

**Comment by cderv** [comment]
How are you looking at this page ? 

I don't think I am seeing the same thing on Chrome at https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#theorems

![image](https://user-images.githubusercontent.com/6791940/121052712-ed0f9d00-c7ba-11eb-9530-5733d97934dd.png)

**Comment by AstrickHarren** [comment]
Should've checked the browsers. Chrome works for me as well, sorry for the troubles. I was using Safari.

**Comment by cderv** [comment]
That is interesting to know this is not working as expected in safari... I can't test that as I am on Windows but we should have a look. Firefox is also ok for me.

@yihui when you have time, can you check if you see the same thing as @AstrickHarren ? Thanks.

**Comment by yihui** [comment]
@cderv I just viewed this page on Safari, and I was able to see the same problem. @AstrickHarren's diagnosis was correct that a `<p>` tag was missing on the last paragraph: https://github.com/rstudio/bookdown/blob/76e3e24135f6292e801f0a8ef1cc41af0bc7bec6/markdown-extensions-by-bookdown.html#L462

We need to either add `<p>`, or update the documentation to use the new fenced Div syntax for theorems.

**Comment by cderv** [comment]
Thanks for checking! 

> update the documentation to use the new fenced Div syntax for theorems.

Oh right the new syntax should solve this ! 

It may be time I do #939 then.
