### ISSUE TITLE
Treat blocks as markdown

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown#117]
See https://github.com/jgm/pandoc/issues/2453

Instead of `\begin{block} \end{block}`, I can probably use other tokens so Pandoc can treat the block content as markdown, and I can restore the tokens to LaTeX environments in the end, e.g. translate this

    ```{block, type='foo'}
    a **block**
    ```

to

    \BookdownBegin{foo}

    a **block**

    \BookdownEnd{foo}

and Pandoc will convert it to

```latex
\BookdownBegin{foo}

a \textbf{block}

\BookdownEnd{foo}
```

then I restore it to

```latex
\begin{foo}

a \textbf{block}

\end{foo}
```

So all Pandoc's Markdown features can still be used in custom blocks.

Related #73.

**Comment by safferli** [comment]
This would be awesome -- I'm currently trying to build a custom block which should include R code to be parsed. Would this be possible this way?

**Comment by yihui** [comment]
I think the answer will be yes, if you mean you want R code chunks in custom blocks.
