### ISSUE TITLE
Add caption and label for htmlwidgets

### ISSUE THREAD

**Issue by byzheng** [rstudio/bookdown#118]
Is it possible to add legend and label for htmlwidgets chucks? I have added some DiagrammeR figures in my book. It will be really nice we can have a legend and cross reference it.

**Comment by yihui** [comment]
I guess you mean "caption" instead of legend. If that is the case, yes, figure captions and labels are supported, but only when the widgets are rendered as screenshots. You can see Section 2.8 of the PDF version of the bookdown book https://bookdown.org/yihui/bookdown/

**Comment by byzheng** [comment]
is it possible to support html output?

**Comment by yihui** [comment]
Currently it is not supported, but I can consider it in the near future.

**Comment by byzheng** [comment]
Thanks for your consideration.

**Comment by yihui** [comment]
Done. You can install the development versions of bookdown and knitr via

```r
devtools::install_github('rstudio/bookdown')
```

cc @cpsievert
