### ISSUE TITLE
Document `bs4_book` format in bookdown book

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#1191]
@apreshill I think we need to do that for next version too.

`bs4_book()` should have a section under chapter about HTML format : https://bookdown.org/yihui/bookdown/html.html

**Comment by apreshill** [comment]
fyi @hadley @maelle- lmk if you'd like to contribute, otherwise we will write and tag you both to review.

**Comment by apreshill** [comment]
new 3.1.2 in bookdown book: https://bookdown.org/yihui/bookdown/html.html#bootstrap-style

- add screenshots

Bootstrap style: https://bookdown.org/yihui/bookdown-demo2
Tufte: https://bookdown.org/yihui/bookdown-demo3/
