### ISSUE TITLE
"Error in setwd(book_proj) : character argument expected" when compiling to docs in parent folder with new_session: true

### ISSUE THREAD

**Issue by CrumpLab** [rstudio/bookdown#1205]
I have checked all of the items in the checklist (session info at bottom), thank you everyone for all your work on bookdown. This appears to be a minor bug involving a new error message.

I am receiving the "Error in setwd(book_proj) : character argument expected" after compiling to gitbook or bs4_book using build book from the build tab. This issue began appearing when I recently updated to the development version of bookdown. I have been able to reproduce the error using the [minimal bookdown example](https://github.com/rstudio/bookdown-demo).

This repo shows an example of the issue

<https://github.com/CrumpLab/bookdown-demo-setwd-problem>

I made a copy of the [minimal bookdown example](https://github.com/rstudio/bookdown-demo), and modified `_output.yml` to include `new_session: true` and `output_dir: "../docs"`.

```
book_filename: "bookdown-demo"
language:
  ui:
    chapter_name: "Chapter "
delete_merged_file: true
new_session: true
output_dir: "../docs"
```

The folder structure of the project is as follows, and the intention is to write the html files to a docs folder in a parent folder above the `_output.yml` file.

```
bookdown-demo-setwd-problem
│   README.md
│
└───bookdown-demo-master
│   │   bookdown files
│   
└───docs
```

On build (to gitbook or bs4_book), everything appears to work fine except "Error in setwd(book_proj) : character argument expected" is written to the console. The appearance of the error message appears to interact with `new_session`.

1. `new_session: true` seems to be required to make the error message appear.
2. deleting the `new_session: true` line from `_output.yml` does not make the error message go away, but if I also delete the contents of the `docs` folder, and the `bookdown-demo.rds` file, then the error message no longer appears.

## usage case

As I mentioned earlier, I didn't have this problem with an earlier version of bookdown (I can't remember which one I was running). My use case is to include a bookdown project as a folder inside an R package folder structure. In this case, I create a pkgdown website that renders to a docs folder in the root directory (for github pages). I would like the bookdown project (in its own subfolder) to compile the web files to same root docs folder.

## Session info

R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   bookdown_0.22.11  digest_0.6.27     evaluate_0.14    
  glue_1.4.2        graphics_4.1.0    grDevices_4.1.0   highr_0.9        
  htmltools_0.5.1.1 jsonlite_1.7.2    knitr_1.33        magrittr_2.0.1   
  markdown_1.1      methods_4.1.0     mime_0.11         rlang_0.4.11     
  rmarkdown_2.9     stats_4.1.0       stringi_1.6.2     stringr_1.4.0    
  tinytex_0.32      tools_4.1.0       utils_4.1.0       xfun_0.24        
  yaml_2.2.1

**Comment by cderv** [comment]
Hi, 

thanks for the issue report. I used the github project you made (thanks), and I can see the message. 

I'll look closer to where it comes from. I believe the usage of providing a `output_dir` that is not a child of the book project is not something we (I) expected for bookdown to support. It seems it work for you before though. I will check how this is supported or not. 

> the intention is to write the html files to a docs folder in a parent folder above the _output.yml file.

I don't think you need a bookdown internal support for this. You could render the book child directory and move this in the right place for your pkgdown website. 
````r
# render book
book <- bookdown::render_book("my_book")
# move in the right place when book is rendered
fs::file_move(fs::path_dir(res), "../docs")
```

IMO this is the safest way as you really control what happens in your workflow when building everything.

**Comment by cderv** [comment]
Also let's precise that I can only reproduce this with running `Build Book` from within the IDE button. 

The error message comes from : 
https://github.com/rstudio/bookdown/blob/2719e5fcf82ca6de3d2ae32d644fbc6e279cc1cb/R/site.R#L9-L16

I don't know why but this is run two times. One with the correct input file, (`<book_project_path>` which will correctly found the book project the index.Rmd file) but also another times by appending the output_dir to the path, and loosing the `../`. So we got an input of the type `<book_project_path>/docs` which does not exist. Hence `book_proj` is NULL and `setwd()` errors.

So it could come from the IDE itself calling the site function a second time with an argument we do not expect... 🤔 

I need to look deeper.

**Comment by CrumpLab** [comment]
> Hi,
> 
> thanks for the issue report. I used the github project you made (thanks), and I can see the message.
> 
> I'll look closer to where it comes from. I believe the usage of providing a `output_dir` that is not a child of the book project is not something we (I) expected for bookdown to support. It seems it work for you before though. I will check how this is supported or not.
> 
> > the intention is to write the html files to a docs folder in a parent folder above the _output.yml file.
> 
> I don't think you need a bookdown internal support for this. You could render the book child directory and move this in the right place for your pkgdown website.
> 
> ```r
> # render book
> book <- bookdown::render_book("my_book")
> # move in the right place when book is rendered
> fs::file_move(fs::path_dir(res), "../docs")
> ```
> 
> IMO this is the safest way as you really control what happens in your workflow when building everything.

**Comment by CrumpLab** [comment]
oops, I accidentally closed this. @cderv thanks for looking into this, and I'll follow your advice and use `file_move`, thanks again!
