### ISSUE TITLE
Document new 404 page feature 

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#1208]
See discussion in https://github.com/rstudio/bookdown/pull/1035

Options are: 
* we could add a section in Chapter 6: bookdown.org/yihui/bookdown/publishing.html This topic seems to be too small to fit a whole section, though.
* Chapter 4: bookdown.org/yihui/bookdown/customization.html because there will be a default and you can customize it using _404.Rmd. But it is not cross format.
* Chapter 3.1: bookdown.org/yihui/bookdown/html.html would be a good place too because this is a feature for HTML books only, which will apply on all HTML book format. It could be documented once in Gitbook, and mentioned again in a new bs4_book section with a link back to the Gitbook subsection ? Or a new "3.1.4 Common element" but it seems to short for that.

**Comment by apreshill** [comment]
Added a possibility in PR #1213:

* Chapter 2.1.12

Several other listed components like index and HTML widgets only work for some output formats, so it felt like it could fit there too.

**Comment by cderv** [comment]
I like this placement you are proposing !

**Comment by yihui** [comment]
Chapter 2 "Components" means the content components. An 404 page is a special page to a specific output format (HTML) served in a specific environment (web server). Most other components are format- and environment-agnostic, so I feel perhaps Chapter 6 is a more proper place, especially after we document other publishing platforms such as Netlify in Chapter 6. Does that make sense?

(Index only works for PDF but is likely to be improved in the future; HTML Widgets works for all formats, although they become screenshots in non-HTML formats. Both components can be inserted anywhere into the content of a book, and the nature of 404 page feels different to me.)
