### ISSUE TITLE
tables with kable, column width in HTML book

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/bookdown#122]
I created a table with kable, but I'm looking for a way to wrap the text differently. I'd like to set the column width in the HTML book. Is this possible?

```
{r chunk1, include=F}
text <- data.frame(v1=c("This is my long text. It is long. Just keeps going, and makes column one quite wide when the HTML book is compiled. What to do?",
"This is my long text. It is long. Just keeps going, and makes column one quite wide when the HTML book is compiled. What to do?"),
v2=c("This is a second column of long text. This gets squished when I compile the HTML book. Not sure how to fix it."))
names(text) <- c("Column 1", "Column 2")

knitr::kable(text, booktabs = TRUE,
caption = 'My caption.'
)
```

<img width="695" alt="screenshot 2016-05-23 16 18 50" src="https://cloud.githubusercontent.com/assets/546433/15483354/46579d8c-2102-11e6-98e6-e98f56ec8a30.png">

I also tried `xtable`:

```
{r chunk2, echo=F, comment=NA, results='asis'}
library(xtable)
print(xtable(sysrev, caption='My caption', align="lp{3cm}p{3cm}"), type="html", include.rownames=F, table.placement="ht", size=getOption("xtable.size", "tiny"))
```

<img width="692" alt="screenshot 2016-05-23 16 13 30" src="https://cloud.githubusercontent.com/assets/546433/15483369/5420f3d2-2102-11e6-8b9a-1ca54a7e4aa7.png">

**Comment by haozhu233** [comment]
Somehow I cannot reproduce the problem... hmm
<img width="776" alt="screenshot 2016-05-23 16 41 32" src="https://cloud.githubusercontent.com/assets/7014590/15483932/6b1c54d4-2105-11e6-9f91-54e1e101508d.png">


If you really want to modify the html table. You may want to try something like this. 

```
library(dplyr)

html_table_width <- function(kable_output, width){
  width_html <- paste0(paste0('<col width="', width, '">'), collapse = "\n")
  sub("<table>", paste0("<table>\n", width_html), kable_output)
}
text <- data.frame(v1=c("This is my long text. It is long. Just keeps going, and makes column one quite wide when the HTML book is compiled. What to do?",
"This is my long text. It is long. Just keeps going, and makes column one quite wide when the HTML book is compiled. What to do?"),
v2=c("This is a second column of long text. This gets squished when I compile the HTML book. Not sure how to fix it."))
names(text) <- c("Column 1", "Column 2")

knitr::kable(text, format = "html", 
caption = 'My caption.'
) %>%
  html_table_width(c(200,400))
```

So you can get
<img width="522" alt="screenshot 2016-05-23 17 23 49" src="https://cloud.githubusercontent.com/assets/7014590/15485116/72c34da4-210b-11e6-9fd0-550705090abb.png">

Be aware, I think it will destroy your Latex table.

**Comment by ericpgreen** [comment]
Thanks. If you look closely, the width of your column 1 (kable version) is slightly larger. If you add more text to [1,1], I think you'll see that the column 1 width gets even wider.

**Comment by yihui** [comment]
It is up to your web browser how to assign widths to columns when they have not been set manually. In your case, you have to manually set the width, and @haozhu233 has provided one approach. Note this approach only applies to HTML output, though. Since there is no syntax for Markdown tables to set column widths, it is not straightforward to set the width for all output formats (e.g. PDF/ePub).

Another way is to use JavaScript to set the widths.

**Comment by ericpgreen** [comment]
Thanks. @haozhu233's `html_table_width()` function will work for now since I'm focusing on HTML output.

**Comment by antaldaniel** [comment]
I'd like to ask a related question, not really an issue. My bookdown text has some images that are very small, and do not print well in the text. Is there any way to include small figures or images in a text that is wrapped, apart from placing it in a table, that has the disadvantages as shown above? 

I.e. in the above example, I would like to place a .jpg in Column1, or, if possible, avoid using the table anyway and just wrap the image.

**Comment by brooksambrose** [comment]
[kableExtra](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html) provides some nice functionality, including setting column widths and other modifications of the default kable html table output.

**Comment by ChrisWaloszek** [comment]
@haozhu233 is there a way to include images in kableExtra tables? Please see my SO question here: [R markdown: How to create a table with images and text which should be knitted as PDF?](https://stackoverflow.com/questions/58204272/r-markdown-how-to-create-a-table-with-images-and-text-which-should-be-knitted-a)
Many thanks in advance!

**Comment by jtr13** [comment]
Maybe there's a new way to do this now but going with the solution here, adding the table class to the `html_table_width` function produces output closer to the markdown version with horizontal lines between rows:

```
html_table_width <- function(kable_output, width){
  width_html <- paste0(paste0('<col width="', width, '">'), collapse = "\n")
  sub('<table>', paste0('<table class="table">\n', width_html), kable_output)
}

knitr::kable(head(iris), format="html") %>% 
  html_table_width(c(20, 40, 200, 400, 50))
```
