### ISSUE TITLE
latex macros not working in \equation{} environment

### ISSUE THREAD

**Issue by dahtah** [rstudio/bookdown#123]
pandoc supports directly defining Latex macros directly in the markdown, e.g.
\newcommand{\a}{\mathcal{alpha}}
This works fine in bookdown, as long as one uses the $$ syntax, but not when using the \equation syntax, meaning it's not possible to have a numbered equation with a macro in it. The reason as far as I can tell is that pandoc expands the macros directly when outputting html, but only when the math appears between $$. 
I guess a possible workaround is to also copy all the macros into an html preamble, but it is cumbersome. It would be great to have a unified mechanism.

**Comment by yihui** [comment]
I think it makes more sense to file a feature request to Pandoc: https://github.com/jgm/pandoc
