### ISSUE TITLE
Slow gitbook with self_contained = TRUE caused by inline images

### ISSUE THREAD

**Issue by king2bob** [rstudio/bookdown#1236]
I've been trying to diagnose a slow call in a self contained gitbook and come up with a minimal example that highlights where I think the issue is: largish inline-d images get scanned over slowing everything down a lot. 

The example book is just a title and two "noise" images (my real gitbook is much larger and has >50 images) 
![image](https://user-images.githubusercontent.com/5145738/130223209-ef216ae8-b938-4f89-90a0-57a1fa884b44.png)

If you stack up more and more copies of these images inside `index.Rmd` with something like this 
```
![png5](100-90-5.png)
![png25](100-90-25.png)
![png5](100-90-5.png)
![png25](100-90-25.png)
![png5](100-90-5.png)
![png25](100-90-25.png)
```

you can really start to feel how slow it is.

[A gist here](https://gist.github.com/king2bob/a5e6a4a7868b8c5ad6da883ea4dd9db8) with sample images to replicate the issue 
[as zip if you prefer](https://gist.github.com/king2bob/a5e6a4a7868b8c5ad6da883ea4dd9db8/archive/ecd682b9ce791b54ac9103e05ce9274ae9da3592.zip)

run (included in render.R) 
```r
bookdown::render_book("index.Rmd", output_format = bookdown::gitbook())
```
vs
```r
bookdown::render_book("index.Rmd", output_format = bookdown::gitbook(self_contained = TRUE))
```

the normal non-`self_contained = TRUE` run is always very fast but the other is very slow by comparison. 

The generated _main* files pre call to `move_files_html` in case they are useful but they can be ignored for reproducing.

Running the slow call through `profvis` 
```r
profvis::profvis({bookdown::render_book("index.Rmd", output_format = bookdown::gitbook(self_contained = TRUE))})
```

![image](https://user-images.githubusercontent.com/5145738/130221399-54533c35-95db-4df7-8f4e-f5d609fcd49c.png)

points to slow calls here inside `move_files_html`
https://github.com/rstudio/bookdown/blob/401dc53a7193761d08ef11c08f25fca539d3e39e/R/html.R#L1089
as the large inline-d images are being pushed through the call to `utils::URLdecode`

Any ideas on how to speed this up? Can inline src links that start `data:` be skipped by this process?

Thanks for taking the time to read through this. Much appreciated. If anything in the below is unclear do let me know. 

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('bookdown')` in your issue?

```r
xfun::session_info('bookdown')
```
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Locale:
  LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
  LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

Package version:
  bookdown_0.23.1 digest_0.6.25   evaluate_0.14   glue_1.4.0      graphics_3.5.1  grDevices_3.5.1 highr_0.9       htmltools_0.4.0
  jquerylib_0.1.4 jsonlite_1.6.1  knitr_1.33      magrittr_1.5    markdown_1.1    methods_3.5.1   mime_0.9        Rcpp_1.0.4.6   
  rlang_0.4.5     rmarkdown_2.10  stats_3.5.1     stringi_1.4.6   stringr_1.4.0   tinytex_0.33    tools_3.5.1     utils_3.5.1    
  xfun_0.25       yaml_2.2.1 
```
- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

Apologies, I'm tied to this version of R at the moment but can update to a later version if you'd rather. I imagine it affects all versions anyway. But I have made sure all the packages are as up to date as possible. 

- [x] installed and tested your bug with the development version of the bookdown package using `remotes::install_github("rstudio/bookdown")` ?
Yes, I pulled the github version with the command above

**Comment by yihui** [comment]
> Can inline src links that start `data:` be skipped by this process?

Yes, we should definitely do that. Are you able to submit a PR? This shouldn't be too hard (@cderv you can do it, too). Thanks a lot!

**Comment by king2bob** [comment]
Thanks. 
> Are you able to submit a PR?

Sorry, I've got some corporate hoops to jump through RE contribution to OSS projects. It is just paperwork that should be fine but I can't submit a PR until I have done it. If you'd rather not wait feel free to pick it up @cderv

**Comment by yihui** [comment]
I feel it is just one line of code (something like `if (grepl('^data:', x) x else URLdecode(x)`). So @cderv please feel free to do it when you have a chance.

**Comment by king2bob** [comment]
I've sorted out the paperwork and put the PR up (see above). Let me know if you need anything more to get it merged.

Thanks again!

**Comment by cderv** [comment]
Thanks !
