### ISSUE TITLE
Multiple citations of same reference fails

### ISSUE THREAD

**Issue by davidchall** [rstudio/bookdown#1237]
I've been experiencing issues with citing the same reference multiple times through my bookdown site. The first citation renders correctly, but all subsequent citations are incorrect. I've been using the new bs4_book output. 

## index.Rmd
I tried to follow the examples from [the docs](https://bookdown.org/yihui/bookdown/html.html#bs4-book) to keep it simple. The bibtex and CSL files are just taken from the docs.
```
---
title: "A Minimal Book Example"
author: "Jane Doe"
date: "2021-08-20"
site: bookdown::bookdown_site
output: bookdown::bs4_book
bibliography: biblio.bib
suppress-bibliography: true
csl: chicago-fullnote-bibliography.csl
---

# Welcome

Reference [@R-base]

Try again [@R-base]
```

## Rendered output
You can see that the first citation works as expected, but the second citation only mentions the author.

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1804856/130255909-ab7b7897-c2ff-4ead-bfff-57b8f862adc0.png">

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1804856/130255867-eab7558c-d7b4-4945-87aa-03f3258b68d7.png">

## Session info

```
> xfun::session_info('bookdown')
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.5.1, RStudio 1.4.1717

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   bookdown_0.23     digest_0.6.27     evaluate_0.14     glue_1.4.2       
  graphics_4.0.4    grDevices_4.0.4   highr_0.9         htmltools_0.5.1.1 jquerylib_0.1.4  
  jsonlite_1.7.2    knitr_1.33        magrittr_2.0.1    markdown_1.1      methods_4.0.4    
  mime_0.10         rlang_0.4.11      rmarkdown_2.10    stats_4.0.4       stringi_1.6.2    
  stringr_1.4.0     tinytex_0.32      tools_4.0.4       utils_4.0.4       xfun_0.24        
  yaml_2.2.1    
```

**Comment by davidchall** [comment]
The same problem occurs with `bookdown::html_book`.

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1804856/130257123-755cb8ce-5fd5-4b4f-a518-97f4e9b96df4.png">

**Comment by davidchall** [comment]
Gotcha - thanks so much for the tip! 👍

**Comment by davidchall** [comment]
In case others find themselves in this situation, I adjusted the CSL file so tooltips work for subsequent citations ([see here](https://gist.github.com/davidchall/7500ad9e965df5e274414b542669af42)).

**Comment by cderv** [comment]
Wow that's cool ! Thanks for sharing !
