### ISSUE TITLE
`search: yes` results in a misleading error message

### ISSUE THREAD

**Issue by GegznaV** [rstudio/bookdown#1238]
# Issue

I use the `gitbook` format with `bookdown`  v0.23.2. If option  `search: yes` is used in `_output.yml` (the option was totally valid in previous `bookdown` versions`), rendering results in error:
```
Error: $ operator is invalid for atomic vectors
```
The message is not informative and even misleading.

See also [this GitHub question](https://stackoverflow.com/questions/68806645/bookdown-0-23-0-24-error-operator-is-invalid-for-atomic-vectors/68877224#68877224).

# Steps to reproduce the error

1. Create "A Minimal Book Example"
2. Change the contents of  `_output.yml` file to:

    ```yml
    bookdown::gitbook:
      config:
        search: yes
    ```
3. Push "Build Book" in RStudio.

# Expected behavior

1.  Ether no error with `search: yes` (the default search engine should be used) **(preferred)**,
2. Or more user-friendly error message that allows easy and accurate identification of the problem must be issued.

<details>
<summary>Session info</summary>
```r
> xfun::session_info('bookdown')
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 1.4.1717

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    
system code page: 1257

Package version:
  base64enc_0.1.3   bookdown_0.23.2   digest_0.6.27     evaluate_0.14     glue_1.4.2       
  graphics_4.1.1    grDevices_4.1.1   highr_0.9         htmltools_0.5.1.1 jquerylib_0.1.4  
  jsonlite_1.7.2    knitr_1.33        magrittr_2.0.1    markdown_1.1      methods_4.1.1    
  mime_0.11         rlang_0.4.11      rmarkdown_2.10    stats_4.1.1       stringi_1.7.3    
  stringr_1.4.0     tinytex_0.33      tools_4.1.1       utils_4.1.1       xfun_0.25        
  yaml_2.2.1       
  ```
</details>

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report! You can install the development version via

```r
remotes::install_github('rstudio/bookdown')
```
