### ISSUE TITLE
Suggestion: use pandoc-crossref filter

### ISSUE THREAD

**Issue by dahtah** [rstudio/bookdown#124]
For referencing equations and figures, there's a pandoc filter called [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref), which has very nice syntax. For example, equations are labelled directly: 
$$ \pi = 3 $$ #{eq:pi}
That's less cumbersome than the current approach (for equations at least). 
Since pandoc-citeproc is already used, perhaps crossref could be included as well?

**Comment by yihui** [comment]
I think you can use `pandoc-crossref` through `pandoc_args` of all formats, e.g.

```
output:
    bookdown::pdf_book:
        pandoc_args: "--filter pandoc-crossref"
```

**Comment by dahtah** [comment]
Thanks for your reply! The correct syntax seems to be:
output:  
 bookdown::gitbook:
  pandoc_args: 
   - "--filter"
   - "pandoc-crossref"

Otherwise the string "--filter pandoc-crossred" appears quoted in the call to pandoc.

**Comment by yihui** [comment]
You are right. Or `pandoc_args: ["--filter", "pandoc-crossref"]`

**Comment by floswald** [comment]
hi @yihui ,
is there a way to get the pandoc-crossref installation from within Rstudio? It seems to me that i have to install it separately in my computer. I am worried about making this dependency available on travis. any ideas of how to do that? thanks!

**Comment by floswald** [comment]
forget about my comment, i just the relevant section in https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations. all good. thanks!
