### ISSUE TITLE
specify the placement of bibliography, rename, remove chapter number in bookdown `pdf_book()`

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/bookdown#1244]
I am trying to do the following with `pdf_book()`:

1. Specify the placement of the bibliography
2. Name it "References" instead of "Bibliography"
3. Remove chapter number

The way I read it, the RMarkdown cookbook suggests that this is possible for pdf output: https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html#include-appendix-after-bibliography

> By default, the bibliography appears at the very end of the document. However, there can be cases in which we want to place additional text after the references, most typically if we wish to include appendices in the document. We can force the position of the references by using `<div id="refs"></div>`, as shown below:

```
# References

<div id="refs"></div>

# Appendix
```

> **Although `<div>` is an HTML tag, this method also works for other output formats such as PDF.**

But this does not work for me. I get the error: 

> ! LaTeX Error: \begin{CSLReferences} on input line 275 ended by \end{document}.

"Authoring Books with RMarkdown" suggests what I want to do is not possible in Bookdown: https://bookdown.org/yihui/bookdown/citations.html

> When the output format is LaTeX, the list of references will be automatically put in a chapter or section at the end of the document. For non-LaTeX output, you can add an empty chapter as the last chapter of your book. For example, if your last chapter is the Rmd file 06-references.Rmd, its content can be an inline R expression:

```
`r if (knitr::is_html_output()) '# References {-}'`
```

Apologies if this is not a "bug". I just expected a different behavior given the note in the manual referenced above.

## Checklist

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('bookdown')` in your issue?

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.4.1103

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 bookdown_0.23.4 digest_0.6.27   evaluate_0.14  
  fastmap_1.1.0   glue_1.4.2      graphics_4.0.2  grDevices_4.0.2
  highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.2 
  knitr_1.33      magrittr_2.0.1  markdown_1.1    methods_4.0.2  
  mime_0.11       rlang_0.4.11    rmarkdown_2.10  stats_4.0.2    
  stringi_1.7.4   stringr_1.4.0   tinytex_0.33    tools_4.0.2    
  utils_4.0.2     xfun_0.25       yaml_2.2.1
```

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the bookdown package using `remotes::install_github("rstudio/bookdown")` ?

-->

**Comment by cderv** [comment]
> But this does not work for me. I get the error:
>    ! LaTeX Error: \begin{CSLReferences} on input line 275 ended by \end{document}.

This error usually happens when your are using pandoc citeproc for citation processing and the tex template used by Pandoc is missing some definition. Are you using `bookdown::pdf_book()` with default value ? Or another format based on it ? Do you use the default template ? 

Regarding what you could do, this depends on what citation processing you are using. Pandoc citeproc, natbib or biblatex ? The feature or ways to configure may differ.

FWIW 
* Pandoc has variable that can be used to change title of bibliography. https://pandoc.org/MANUAL.html#biblatex-bibliographies It should work with default template.
* Using a div to move bibliography will only work with Pandoc citeproc https://pandoc.org/MANUAL.html#placement-of-the-bibliography. Hence the R Markdown Cookbook details.
* For natbib or biblatex, I don't know how you do that in tex usually, but the call to create the bibliography are in the template I believe and you may need to modified that for it to work. Hence the bookdown book comment.

Can you share a reproducible example of what you are trying to do so that we can be more precise ?

**Comment by ericpgreen** [comment]
Thanks, @cderv. I wasn't sure about the best way to share a reproducible example for bookdown. This might be overkill, but I pushed my current setup to https://github.com/ericpgreen/ghr_book. 

I define two main output formats in `_output.yml` ([exploring bs4_book](https://community.rstudio.com/t/modify-bs4-book-to-enable-tufte-style-margin-notes/100747)): `bookdown::pdf_book` and `msmbstyle::msmb_html_book` (a variant of tufte).

```
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
  base_format: tufte::tufte_book
  highlight: tango
msmbstyle::msmb_html_book:
  tufte_variant: "envisioned"
  toc: TRUE
  toc_depth: 1
  split_by: chapter
  split_bib: yes
  margin_references: TRUE
  css: [stylemsmb.css, center.css, custom-msmbstyle.css]
  includes:
    in_header: google_analytics.html
    after_body: footer.html
```

In `index.Rmd`:

```
title: "Global Health Research"
author: "Eric P. Green"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib, ghr.bib]
csl: apa.csl
link-citations: true
url: 'http\://themethodsection.com/ebook/'
cover-image: images/cover.jpg
description: |
  Online textbook about global health research methods
geometry: paperheight=10in,paperwidth=8in,margin=1in
papersize: justified,twoside,symmetric
```

In `preamble.tex`:

```
\PassOptionsToPackage{round}{natbib}
\setcitestyle{super}
\renewcommand*{\citep}[1]{{\cite{#1}}}
\renewcommand*{\citet}[1]{{\cite{#1}}}
```

I inserted an example citation in `index.Rmd` in the Preface: 

> Something about global health. @white:2017 have ideas.

Here is the PDF output:

<img width="861" alt="Screen Shot 2021-08-31 at 11 15 27 AM" src="https://user-images.githubusercontent.com/546433/131529629-f3cf084b-d1a4-42dd-93cf-ac9fb9954e7e.png">
<img width="607" alt="Screen Shot 2021-08-31 at 11 17 29 AM" src="https://user-images.githubusercontent.com/546433/131529640-4e1ea011-b46f-4aca-a4e3-9d2130effd83.png">

Here is the html output:

<img width="1139" alt="Screen Shot 2021-08-31 at 11 21 02 AM" src="https://user-images.githubusercontent.com/546433/131530216-e2f8f502-50cc-489e-9dae-ce52514906f8.png">

<img width="812" alt="Screen Shot 2021-08-31 at 11 21 33 AM" src="https://user-images.githubusercontent.com/546433/131530320-5ee913d5-bd68-479a-8f79-e6897d48dfcf.png">

The file `91-references.Rmd` includes:

```
`r if (knitr::is_html_output()) '# References {-}'`
```


**Summary**

HTML

1. There is a "Reference" section, but it has no contents. Ideally I'm trying to get citations in margin notes AND a reference section. Even more ideal would be for the Reference section to be at the end of each chapter (plus in the margins).
2. The in-text citation and margin note citation are perfect!

PDF

1. Citation appears in the margin, but there are two issues: (a) Citation has footnote numbering (I'd prefer non-numbered as in html output); and (b) the author name does not appear in the in-text citation as it does in the html.
2. There is a "Bibliography" chapter at the end (I'd prefer it be called "References" and not be a numbered chapter...and as noted above, and extra bonus would be to have a reference section after each chapter). 

I've described more issues than the original post, but I figure it's better to be specific about the end goal. Multiple formats + tufte is giving me a run for my money!!

**Comment by cderv** [comment]
I will need time to look into this then. 

At first sight, this seems like specific features you want from format that don't support them in the first place. 

I don't know if it is issues in the tool or just some how-to for the specific needs.

I'll try to take not to long to look into this closely. 

If anyone wants to help, feel free to chime in ! 😄

**Comment by ericpgreen** [comment]
I appreciate your willingness to take a look. I agree with your assessment. I'm not sure which it is either. 

I'll post back with any progress.

**Comment by ericpgreen** [comment]
I'm going to close this for now because I've made some other decisions that make this question moot for now. I might re-open in the future with (hopefully) a clear ask.
