### ISSUE TITLE
allow for custom dependencies to take precedence

### ISSUE THREAD

**Issue by ThierryO** [rstudio/bookdown#1248]
Can we replace https://github.com/rstudio/bookdown/blob/23798df80f9ade52836f76c31ea701c576d707a2/R/gitbook.R#L34 with 

```
      ..., extra_dependencies = c(gitbook_dependency(table_css, gb_config), extra_dependencies)
```

In the current implementation, the gitbook css is loaded last. Hence it takes precedence over the css instructions defines in `extra_dependencies`.

**Comment by cderv** [comment]
Yes we should do that. It is a duplicated of https://github.com/rstudio/bookdown/issues/1101 and we discussed that there. 

I don't think it will break things in the wild. `extra_dependencies` is not really useful this ways, and may not be so used. I'll make change. 

Please read the discussion there also for other consideration regarding moved JS lib.

**Comment by ThierryO** [comment]
Closing this issue since it is a duplicate.
