### ISSUE TITLE
[FR] bs4_book: toc_depth specification in sidebar

### ISSUE THREAD

**Issue by meierluk** [rstudio/bookdown#1254]
It would be nice if the depth of the TOC appearing on the right-hand side of a bs4_book could be customized.

**Comment by cderv** [comment]
Yes currently I think the level is h3 max
https://github.com/rstudio/bookdown/blob/7ce6dc65b39ffe846e2ff88c160a69f2348a5a92/R/bs4_book.R#L138

Can you share more on your use case ? At which level would you want to specify ? 

I marked this as a feature request to consider for next time we'll add features into **bookdown**

**Comment by meierluk** [comment]
I see. Actually, due to a corrupt in_header file, my sidebar was never expanded to h3 items ... now it works (only the static h2 were visible). For me, that level is enough, so I leave it up to you whether you want to keep this as a feature request or not.

**Comment by cderv** [comment]
I'll close this then. If others are interested, we'll reconsider and reopen

Thanks;
