### ISSUE TITLE
中文问题

### ISSUE THREAD

**Issue by HeyangGong** [rstudio/bookdown#126]
我下载这个模板后，输入中文，然后并不能显示，能不能修改一下模板，使得它支持中文输入？我用的是windows. 尝试在intro中输入“为什么不能使用中文” 编译以后是乱码。

当然单个章节单独编译时能够显示中文，但是编译整本书就不能显示，或者乱码。

另外我尝试下载书籍 **R忍者秘籍** 后编译书籍，会出现错误，如下：

```
> bookdown::render_book("index.rmd")
Error in yaml::yaml.load(enc2utf8(string), ...) : 
  Reader error: control characters are not allowed: #8D at 25
```

请问，能不能修改您的模板， 使得它可以显示中文？

**Comment by yihui** [comment]
你的 `sessionInfo()` ？RStudio 是最新的预览版吗？https://www.rstudio.com/products/rstudio/download/preview/

**Comment by WLswert** [comment]
我也遇到了相同的问题，编译**R忍者秘籍** 后出现下面的报错
Error in yaml::yaml.load(enc2utf8(paste(readUTF8(x), collapse = "\n"))) : 
  invalid multibyte character in parser at line 1
 看了一下源码，跟踪了一下，我这边好像是_bookdown.yml中的chapter_name: !expr "function(i) paste0('第', i, '章')"有中文，提示多字节的问题，变更编码都无法解决。

**Comment by yihui** [comment]
你的 `sessionInfo()` ？

**Comment by yihui** [comment]
我发现了，这是 yaml 包的问题（ https://github.com/viking/r-yaml/issues/6 ），已经报告三年多了还没修复，看样子是作者已经带着什么人跑路了……我只好把 bookdown 设置稍微改了一下，你下载最新的忍者秘籍库应该可以编译了：https://github.com/yihui/r-ninja

**Comment by HeyangGong** [comment]
以为是windows操作系统问题，整了一个Ubuntu，看来我编程生涯刚到迷茫的绝望期！以后直接用你的那本书当成模板写文章！

**Comment by yihui** [comment]
当然部分原因确实是 Windows，因为它不用 UTF-8 编码，很讨厌。每年在字符编码问题问题上浪费的时间足够每个程序员休一周假了。

我那本书还没弄 PDF 模板，不过估计需要写书的人在半年内也不太可能真写完，所以我应该还有时间去研究中文的 PDF 模板。先玩着 HTML 输出吧。
