### ISSUE TITLE
How do I include a cross reference to an image that is not in a code chunk?

### ISSUE THREAD

**Issue by mdeea** [rstudio/bookdown#1267]
I was able to automatically cross-reference figures and tables in R code chunks using the information in the link below 

https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html.

But how to do this for an image in the text?

**Comment by mdeea** [comment]
Right, got it.

Don't include the figure in the text with 
![Figure 1 Experimental Design](../outs/design.png)

Include it inside a chunk like:

```{r design, fig.cap = "Experimental"}
knitr::include_graphics(path = "../outs/design.png")
```
and then reference it the normal way in the text with:

"as per the experimental design shown in **Figure \@ref(fig:design)**."

**Comment by llrs** [comment]
Note that it is also possible to use `(#fig:design)`: `![(#fig:design) Experimental Design](../outs/design.png)` and later reference with `\@ref(fig:design)` as per your answer on RStudio forum https://community.rstudio.com/t/cross-reference-images-in-rmarkdown/83402/2
