### ISSUE TITLE
Export into Word file as single document

### ISSUE THREAD

**Issue by byzheng** [rstudio/bookdown#127]
`html_document2()` and `pdf_document2()` can be used to export single Rmarkdown file into html and pdf file with cross referencing of figure and table. I love this features which is missing in the rmarkdown package. It will be much easier to write a journal article. 

However, our colleagues and publishers will use MS Word format. Is it possible to write a similar function `word_document2()` to export into Word format?

**Comment by benmarwick** [comment]
I'm also very interested in this option, and I think a great many others are too, and it probably would make bookdown attractive to a much wider user community. 

However, in a recent exchange on twitter, I found that it's not currently in the developer's plan: https://twitter.com/xieyihui/status/736928051427053568

**Comment by byzheng** [comment]
@benmarwick Thanks for your suggestion. 

I agree with @yihui about the word document is ugly and am more than happy to not use word. However, our colleagues and publishers use word as their standard format. We have to use word to collaborate with them. In most cases, we have no choices to convert Rmd file into word document. (To be honest, I try to give up MS Office for many years, but my working environment forces me convert everything back to Word) 

The auto number and cross reference is very useful feature to write a journal article and book. The word output may be not the major target of bookdown package. Could you we export this feature to rmarkdown package, then convert Rmd file into word?

**Comment by yihui** [comment]
I think the features of figure/table numbering and cross-references can be partially ported to Word output. I'll try that.

As I said on Twitter, it is okay to generate Word output, but everybody can be in trouble if anybody edits the Word output, because there is no way to apply the changes in Word back to Rmd documents. In other words, the Word output is supposed to be _read-only_.

**Comment by byzheng** [comment]
Thanks. I am happy to use the read-only word output.

**Comment by benmarwick** [comment]
Yes, I think this is how current users of Rmd -> MS Word are already thinking about it, with the Word doc output as read-only (just like the PDF and HTML output is also read-only).

Bookdown-style captioning and cross-referencing is a major feature addition for R markdown, and it would be great to have it available for MS Word output also.

**Comment by mienkoja** [comment]
@yihui, just curious if any work has been started on this. I need a solution like this in the next few weeks and would be interested in contributing to a `word_document2()` function if you have not already begun.

**Comment by yihui** [comment]
Done.

**Comment by benmarwick** [comment]
Thanks very much, this is a wonderful addition to the toolkit of literate data analysis. @adletaw, you might be interested to see this feature.
