### ISSUE TITLE
html_document2 - Multiple Kable output doesn't iterate table number in caption

### ISSUE THREAD

**Issue by brianperdomo** [rstudio/bookdown#1272]
I am trying to produce a list of tables as in the example below. This is the method for printing a list of kables as per [Section 10.1](https://bookdown.org/yihui/rmarkdown-cookbook/kable.html#generate-multiple-tables-from-a-for-loop) of the bookdown documentation. This works as intended except that all the table captions are numbered the same.

```
temp <- tempfile(fileext = '.rmd')

file.create(temp)
f <- file(temp, open = "w")

writeLines(con = f, text = '
---
title: "Title"
author: "Author"
date: "10/19/2021"
output: bookdown::html_document2
---          
            
```{r results="asis"}
library(magrittr)

tbl_list <- LETTERS[1:3] %>% 
  purrr::set_names(nm = LETTERS[1:3]) %>% 
  purrr::map(~ dplyr::sample_n(mtcars, 4)) %>% 
  purrr::imap(~ tibble::rownames_to_column(.x, var = .y)) %>% 
  purrr::imap(~ knitr::kable(.x,
                             caption = paste0("Frequency Distribution - ", .y))) %>% 
  purrr::walk(function(tbl){
    print(tbl)
    cat("\n\n<!-- -->\n\n")
  })
```')

close(f)

out_f <- rmarkdown::render(temp)
rstudioapi::viewer(out_f)

file.remove(temp)
file.remove(out_f)
```

My real usecase here has far more than 3 tables so I'd rather not create one chunk per table if I don't have to and in the future I intend to use this as a template that could have a variable number of tables at that point.

Am I overlooking a setting or is this simply a bug?

```
> xfun::session_info('bookdown')
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600), RStudio 1.4.1717

Locale: LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3 bookdown_0.24   digest_0.6.28   evaluate_0.14   fastmap_1.1.0   glue_1.4.2      graphics_4.0.5  grDevices_4.0.5 highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.2 
  knitr_1.36      magrittr_2.0.1  methods_4.0.5   rlang_0.4.11    rmarkdown_2.11  stats_4.0.5     stringi_1.7.5   stringr_1.4.0   tinytex_0.34    tools_4.0.5     utils_4.0.5     xfun_0.26      
  yaml_2.2.1   
```

**Comment by brianperdomo** [comment]
Yeah, that would work. I was just trying to make it work as shown in the documentation. Thank you for that response. I think it would be helpful to add that example in that section as a way to make the table numbering work with multiple tables.

**Comment by cderv** [comment]
> I was just trying to make it work as shown in the documentation.

This is part of the documentation already. **rmarkdown-cookbook** is a set of recipes and sometimes you need to combine several of them. 

> I  think it would be helpful to add that example in that section as a way to make the table numbering work with multiple tables

I'll open an issue in the book repo to remind us adding a reference between the recipes.

I'll close the issue here.
