### ISSUE TITLE
leaflet::addMarkers not working 

### ISSUE THREAD

**Issue by dyerlab** [rstudio/bookdown#128]
The following code produces a leaflet map on a page in a bookdown project.

```
require(leaflet)
pts <- data.frame( Longitude= c(-110,-109,-112), Latitude=c(28,26,27), Stratum=LETTERS[1:3])
leaflet(pts) %>% addTiles() %>% addCircleMarkers(~Longitude,~Latitude,popup=~Stratum)
```
but if I change the plot to use normal markers as

`
leaflet(pts) %>% addTiles() %>% addMarkers(~Longitude,~Latitude,popup=~Stratum)
`

it shows a missing image icon in the gitbook rendered html.  It does work properly in RStudio plots and does as well in a normal rmarkdown::html_document. Any ideas?

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
