### ISSUE TITLE
No spacing on reference section and how to numbered ? 

### ISSUE THREAD

**Issue by AimerGDiaz** [rstudio/bookdown#1280]
Hi, 

I'm quite happy with all the features of the bookdown code and the guide to write them, however the section for bibliography is too short, I've not found any instruction to increase the spacing between lines. 

![reference](https://user-images.githubusercontent.com/26363252/139697864-49eff2c0-be83-42ad-b12a-f56bac5b1338.PNG)

Is it also possible to numbered or itemized the references ? 

Thanks

**Comment by cderv** [comment]
I believe the spaces is something related to #1277 which should solve this. 

About the styling, if you want to change it, you need to use any style you want using a CSL file: 
https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html#changing-citation-style
