### ISSUE TITLE
OutDec = "," in base R graphs does not seem to work

### ISSUE THREAD

**Issue by kehldaniel** [rstudio/bookdown#1284]
Hello, first of all thank you for the **great package**!
I have written a book with both ggplot and base R graphs.
I am almost sure that `options(OutDec = ",")` used to work for both worlds.
However at the moment base R graphs do not seem to use , as the decimal separator.
I downloaded the bookdown-demo book of yihui and changed the first figure as follows
```{r nice-fig, fig.cap='Here is a nice figure!', out.width='50%', fig.asp=.75, fig.align='center', fig.show='hold'}
library(ggplot2)
options(OutDec = ",")
plot(runif(100), runif(100))
qplot(runif(100), runif(100))
options(OutDec = ".")
```
Result is the same: "," in the ggplot figure, "." in the base R figure. Running the code from console produces the expected result.

Is there a way to change the behaviour for base R?

I am on Windows and using latest 0.24 bookdown version. Let me know if you need more info or need any more testing.

Thank you, have a great day,
daniel

**Comment by cderv** [comment]
Hi @kehldaniel, 

Can you share your session information please ?   i.e `xfun::session_info("bookdown")`

> I am almost sure that options(OutDec = ",") used to work for both worlds.

Do you know which version of **knitr** you had before ?

if there is an issue, I don't think this is specific to **bookdown**. Can you try reproduce with `rmarkdown::html_document()` only ? 

From my tries, this is working expected if I remove the last `options(OutDec = ".")`. I am not sure why but setting the two options in the same chunk make the plot keep the `.` as separator.

@yihui do you happen to know why setting 
```r
options(OutDec = ",")
plot(runif(100), runif(100))
options(OutDec = ".")
```
would make the second option set take precedence whereas it is after the plot code ? 

I can reproduce in a simple md file using `knitr::knit()` and looking at the png file produced.


@kehldaniel also what is your use case ? This is very specific to do it at chunk level. 

1. Changing globally in setup chunk works
````markdown
---
title: "RStudio error en título"
author: "José Luis Olivares Vázquez"
date: "26/10/2021"
output: html_document
---

```{r setup, include=FALSE}
options(OutDec = ",")
```

```{r}
library(ggplot2)
plot(runif(100), runif(100))
qplot(runif(100), runif(100))
```
````

2. Changing option for a chunk only could be done using `R.options` chunk option. I would do it that way if you need to locally change an option. 
````markdown
---
title: "RStudio error en título"
author: "José Luis Olivares Vázquez"
date: "26/10/2021"
output: html_document
---

```{r, R.options = list(OutDec = ",")}
library(ggplot2)
plot(runif(100), runif(100))
qplot(runif(100), runif(100))
```
````

Both case above works for me.

**Comment by yihui** [comment]
> @yihui do you happen to know why setting would make the second option set take precedence whereas it is after the plot code ?

That's really odd. My finding is that you have to wait for at least 0.07 seconds before resetting `OutDec` to `.`:

```r
options(OutDec = ",")
plot(runif(100), runif(100))
Sys.sleep(.07)
options(OutDec = ".")
```

If you wait for less time (e.g., 0.06 seconds), the tick labels will use `.`. I don't know why. I was running the code in the R console instead of R Markdown.

**Comment by cderv** [comment]
That is odd ! 

> I was running the code in the R console instead of R Markdown.

Also, this is working for me without timeout in console 🤷‍♂️

**Comment by kehldaniel** [comment]
Dear cderv and yihui,
thank you for looking into this. I was really just playing around with this in a more complex case which ultimately boiled down to this simplest reproducible example. I don't really think this is an important issue I just thought that the root of the behaviour might be important. No matter what, I am surprised I could come up with something you have not seen before. :)

Thank you again,
daniel
