### ISSUE TITLE
gitignores and git workflow

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#129]
I have started a bookdown project by cloning this:

https://github.com/rstudio/bookdown-demo

And am also scrutinizing source vs. rendered for [hadley/r4ds](https://github.com/hadley/r4ds) and [csgillespie/efficientR](https://github.com/csgillespie/efficientR) to figure out what the heck I'm doing.

Is there advice on what we should gitignore? The `.gitignore` file in the demo bears little resemblance to what people seem to be doing in real life.

Any or all of this would be great: advice here, advice in [Bookdown: Authoring Books with R Markdown](https://bookdown.org/yihui/bookdown/), or different (more realistic) `.gitignore` in the demo project. I'm hoping for info on what's source vs output vs vendored, what I could safely delete + rebuild, etc. I can make good guesses but it's alot to take in...

**Comment by znmeb** [comment]
I'm actively developing a book in Bookdown. It's not quite live yet so you can't look at code yet, but it will be sometime the middle of the week. Meanwhile, here's the .gitgignore I'm currently using:

.Rproj.user
.Rhistory
.RData
.*.Rnb.cached
_publish.R
_book

IIRC everything except `_book` was copied from the template book <https://github.com/rstuido/bookdown-demo>

**Comment by jjallaire** [comment]
You don't actually need .*.Rnb.cached anymore (that was a notebook thing
that is no longer in play). I'll update the template.

**Comment by coatless** [comment]
@jennybc 

For a default build that is bare-n-bones see:

[https://github.com/coatless/statprogramming](https://github.com/coatless/statprogramming/tree/7dcfc3199a87c0b23946299da7935930341cce15)

GitHub ignore:

```
.Rproj.user
.Rhistory
.RData
.Ruserdata
_book
```

Slightly more content:

<https://github.com/coatless/timeseriesisgreat>

And even more content as it goes live in under a week:

<https://github.com/daviddalpiaz/appliedstats>

These are all setup to autodeploy to GitHub pages via Travis-CI, so we have:

<https://coatless.github.io/statprogramming>

<https://coatless.github.io/timeseriesisgreat>

<https://daviddalpiaz.github.io/appliedstats>

**Comment by jennybc** [comment]
Thanks for the examples @znmeb @coatless!

I am ambivalent about gitignoring `_book` but perhaps it is for the best. With something like this, it can be hard to figure out what changes about the rendered result, as a consequence of a specific changes to source. If `_book` is in the repo, the diff will show you. If `_book` is gitignored, you've just got your own eyeballs and patience to click around and explore the result. For generating plain text from plain text, I don't think the prohibition against putting downstream products under version control necessarily applies.

But I do want to gitignore stuff that is non-diff-friendly (so maybe `_book/_main.pdf` and `_book/_main.epub`?) and/or a dependency (`_book/libs`).

**Comment by csgillespie** [comment]
@jennybc As an aside, we started our book when bookdown was in it's infancy. So our gitignore and general structure is an example of evolution, instead of a grand plan.

**Comment by znmeb** [comment]
@jennybc How big is the book? Mine's still small and young and not in need of me losing sleep over continuous integration. My workflow typically is as many small changes / commits as I can keep in my head, "Clean all", "Build Book", open a shell, "cd _book; netlify deploy". I went "live" yesterday so people can watch it happen.

**Comment by jennybc** [comment]
@znmeb I'm trying this out on something small (a tutorial for useR). But I need to rethink the STAT 545 content, so this also serves as a pilot study for that. In that case I would want to deploy via continuous integration. In STAT 545 I also get a lot of nontrivial contributions from others (e.g. from TAs), hence my desire to make it easier to understand the implications of proposed changes to source.

**Comment by znmeb** [comment]
@jennybc I'll be opening up my book source repo in the next day or so. It's on GitLab now but I need to move it here because Netlify can't pull from GitLab. I probably should have put it here to begin with, since the "Edit" links were designed for GitHub fork / pull request workflows.

**Comment by znmeb** [comment]
OK - my repo is live: <https://github.com/znmeb/mastering-dfs-analytics-bookdown>.

**Comment by yihui** [comment]
What I do is similar to @coatless: Rmd source files in master, and HTML output in gh-pages, so I can see changes in both source and output if I want.

**Comment by jennybc** [comment]
@coatless and @yihui: thanks to you both for specific example repos above. That allowed me to successfully deploy to gh pages via travis.
