### ISSUE TITLE
[FR] Pretty URLs for gitbook output

### ISSUE THREAD

**Issue by thosgood** [rstudio/bookdown#1298]
At the moment, using the gitbook output, the html output does not have so-called "pretty URLs", e.g. the URL will be `https://qubit.guide/chapter7.html` instead of `https://qubit.guide/chapter7`. This could be fixed simply by moving `chapter7.html` to `chapter7/index.html`, but I can't do this after the build process, since the resulting html files use relative links throughout (e.g. `<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />`).

- Would it be possible to have some toggle to allow for pretty URLs?
- Is there some workaround that I can use in the meanwhile?

**Comment by yihui** [comment]
I feel this would be challenging to implement in **bookdown**. I'd recommend that you use services like Netlify to automatically generate pretty URLs:

![image](https://user-images.githubusercontent.com/163582/148710309-09f9bb13-0570-45ae-9095-989a5fe7dc66.png)

**Comment by thosgood** [comment]
I'm hosting using GitHub pages, but it turns out that this automatically solves the problem! All the links point to e.g. `/chapter7.html`, but if you manually delete the `.html` then the URL still resolves, so that's nice.

My only question now is how to change the name of the outputted files: e.g. if I'd like the generated page to be `/chapter-7.html`, or just `/7`, instead of `chapter7.html`.
