### ISSUE TITLE
The use of "..." in text produces errors.

### ISSUE THREAD

**Issue by quantmeth** [rstudio/bookdown#1299]
Hi,

I found that if a text contain "..." (three dots) in the parentheses, using `bookdown:::serve_book()` while produces this error during tweaking. See image.

```
Error in match.call(fn, expr) : 
  ... used in a situation where it does not exist
```
![image](https://user-images.githubusercontent.com/41082179/149568850-518dd864-04e6-4737-999a-4d316040fc0a.png)

It was at the end of a sentence in parentheses. Other instances did not produce error. Removing the three dots removed the error.

Thank you for your work, bookdown is great!

**Comment by cderv** [comment]
Hi, 

I assume you are using `bs4_book()` format. Unfortunately, you did not mentioned it.

Based on this assumption, I tried to reproduce by adding  this sentence in [bookdown-demo example book](https://github.com/rstudio/bookdown-demo) , file `intro.Rmd`
````
**R** fournit une grande  variété de techniques statistiques (modélisation linéaire et non-linéaire, analyses statistiques classiques, analyse de séries chronologiques, classification, ...) et graphiques, et est hautement extensibles.
````

No error was produced. The book is served correctly. 

Can you share an example repo where this happens ?  Without any example it will be hard to reproduce .

**Comment by quantmeth** [comment]
Hi, 

Yes it was with bs4, after doing

```
library(bookdown)
create_bs4_book(".")
# Change one file with the text screenshoted
serve_book()
```

I'll make a reproducible example to get the error.  I got it a several times three days ago; don't seem to happen today.

**Comment by cderv** [comment]
Can you copy past here the text from the screenshot ? I wrote it above but I don't get the error in that case.

I did 
````r
dir.create(tmp_dir <- tempfile())
owd <- setwd(tmp_dir)
library(bookdown)
create_bs4_book(".")
fs::dir_tree()
xfun::write_utf8(
  c(
    xfun::read_utf8("01-intro.Rmd"),"\n",
    "**R** fournit une grande  variété de techniques statistiques (modélisation linéaire et non-linéaire, analyses statistiques classiques, analyse de séries chronologiques, classification, ...) et graphiques, et est hautement extensibles."
  ),
  "01-intro.Rmd"
)

serve_book()
servr::daemon_stop()
setwd(owd)
unlink(tmp_dir)
````

Maybe I got the text wrong

**Comment by quantmeth** [comment]
[text.txt](https://github.com/rstudio/bookdown/files/7882934/text.txt)

Here is the text in the image.

**Comment by cderv** [comment]
The text in the file does get the `...` but I added them after `classification` and I can't reproduce either.

````r
dir.create(tmp_dir <- tempfile())
owd <- setwd(tmp_dir)
library(bookdown)
create_bs4_book(".")
fs::dir_tree()
textcon <- url("https://github.com/rstudio/bookdown/files/7882934/text.txt")
content <- xfun::read_utf8(textcon)
close(textcon)
content <- gsub("(classification)\\)", "\\1, ...)", content)
xfun::write_utf8(content, "044-newfile.Rmd")
serve_book()
servr::daemon_stop()
setwd(owd)
unlink(tmp_dir)
````

**Comment by quantmeth** [comment]
I don't seem to be able to replicate the error.  I'll investigate the problem and come back with a reproducible example. Sorry for the inconveniences,
