### ISSUE TITLE
TOC not floating in HTML, stuck at top

### ISSUE THREAD

**Issue by trestletech** [rstudio/bookdown#13]
See: https://www.dropbox.com/s/5ej0fvf6dwydiia/ch1.html?dl=0

on latest master

**Comment by trestletech** [comment]
Found that this looks to be intentional, but caught us off-guard. 1db06cfccca36d87ee813d33d29f53e197494c70

We'll just lock onto an old version until things have stabilized.

**Comment by yihui** [comment]
Yes, it was intentional. I guess most users will prefer `bookdown::gitbook` over `html_chapters` in the future. I'll let you know once it is mature enough.
