### ISSUE TITLE
pandoc 2.17.0.1 can't find labels for labeled heading, so break their references

### ISSUE THREAD

**Issue by N0rbert** [rstudio/bookdown#1301]
Below is the minimal reproducible example (`index.Rmd` file):

```
---
title: Test document
author: tested
date: "`r Sys.Date()`"

documentclass: book

site: bookdown::bookdown_site
output:
  bookdown::epub_book: default
  bookdown::word_document2: default
  bookdown::odt_document2: default

---

# Theory {#theory}

...

see \@ref(label1).

...

## Some other header {#label1}

...

### Third level header {#label2}

* list:

  1. see \@ref(label2) above.

```

I'm compiling it using command below:

```
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::word_document2')"
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::odt_document2')"
```

and get the following output:

```
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book')"


processing file: _main.Rmd
  |......................................................................| 100%
   inline R code fragments


output file: _main.knit.md

/usr/bin/pandoc +RTS -K512m -RTS _main.knit.md --to epub3 --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.epub --lua-filter /home/i/R/x86_64-pc-linux-gnu-library/4.0/bookdown/rmarkdown/lua/custom-environment.lua --number-sections 

Output created: _book/_main.epub
[1] "/tmp/_book/_main.epub"
Warning messages:
1: The label(s) label1 not found 
2: The label(s) label2 not found 
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::word_document2')"


processing file: _main.Rmd
  |......................................................................| 100%
   inline R code fragments


output file: _main.knit.md

/usr/bin/pandoc +RTS -K512m -RTS _main.knit.md --to docx --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.docx --lua-filter /home/i/R/x86_64-pc-linux-gnu-library/4.0/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/i/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmarkdown/lua/pagebreak.lua --number-sections --highlight-style tango 

Output created: _book/_main.docx
[1] "/tmp/_book/_main.docx"
Warning messages:
1: The label(s) label1 not found 
2: The label(s) label2 not found 
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::odt_document2')"


processing file: _main.Rmd
  |......................................................................| 100%
   inline R code fragments


output file: _main.knit.md

/usr/bin/pandoc +RTS -K512m -RTS _main.knit.md --to odt --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.odt --lua-filter /home/i/R/x86_64-pc-linux-gnu-library/4.0/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /home/i/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /home/i/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmarkdown/lua/number-sections.lua 

Output created: _book/_main.odt
[1] "/tmp/_book/_main.odt"
Warning messages:
1: The label(s) label1 not found 
2: The label(s) label2 not found 
```

Both `1: The label(s) label1 not found` and `2: The label(s) label2 not found` are critical for me.
Resulting odt-rendering is below:

![labels-in-odt](https://user-images.githubusercontent.com/309456/150697017-3f7768c3-b269-4f44-91d8-ec43a5fb802b.png)

---

It is Ubuntu 21.10. Other details:

```
$ pandoc --version
pandoc 2.17.0.1
Compiled with pandoc-types 1.22.1, texmath 0.12.4, skylighting 0.12.1,
citeproc 0.6.0.1, ipynb 0.2
User data directory: /home/i/.local/share/pandoc
Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

$ LC_ALL=C R -e "xfun::session_info('bookdown')"

R version 4.0.4 (2021-02-15) -- "Lost Library Book"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> xfun::session_info('bookdown')
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 21.10

Locale: C

Package version:
  base64enc_0.1.3 bookdown_0.24.4 digest_0.6.29   evaluate_0.14  
  fastmap_1.1.0   glue_1.6.1      grDevices_4.0.4 graphics_4.0.4 
  highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.3 
  knitr_1.37      magrittr_2.0.1  methods_4.0.4   rlang_0.4.12   
  rmarkdown_2.11  stats_4.0.4     stringi_1.7.6   stringr_1.4.0  
  tinytex_0.36    tools_4.0.4     utils_4.0.4     xfun_0.29      
  yaml_2.2.1     
> 

```

**Comment by N0rbert** [comment]
This is a regression. It first happened with pandoc 2.17 (from *pandoc-2.17.0.1-1-amd64.deb*). Below command

```
Rscript --verbose -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book', clean=FALSE)"
```

results with

```
$ Rscript --verbose -e "bookdown::render_book('index.Rmd', 'bookdown::epub_book', clean=FALSE)"
running
  '/usr/lib/R/bin/R --no-echo --no-restore -e bookdown::render_book('index.Rmd', 'bookdown::epub_book', clean=FALSE)'



processing file: _main.Rmd
  |......................................................................| 100%
   inline R code fragments


output file: _main.knit.md

/usr/bin/pandoc +RTS -K512m -RTS _main.knit.md --to epub3 --from markdown+autolink_bare_uris+tex_math_single_backslash --output _main.epub --lua-filter /home/i/R/x86_64-pc-linux-gnu-library/4.0/bookdown/rmarkdown/lua/custom-environment.lua --number-sections 

Output created: _book/_main.epub
[1] "/tmp/_book/_main.epub"
Warning messages:
1: The label(s) label1 not found 
2: The label(s) label2 not found 
```

and the following contents of `_main.knit.md`:

```
---
title: Test document
author: tested
date: "2022-01-24"
documentclass: book
site: bookdown::bookdown_site
output:
  bookdown::word_document2: default
  bookdown::epub_book: default
  bookdown::odt_document2: default
---

# Theory {#theory}

...

see <a href="#label1"><strong>??</strong></a>.

...

## Some other header {#label1}

...

### Third level header {#label2}

* list:

  1. see <a href="#label2"><strong>??</strong></a> above.



<!--chapter:end:index.Rmd-->
```

Reverting to Pandoc 2.16.2 (from *pandoc-2.16.2-1-amd64.deb*) solves the issue immediately, and `_main.knit.md` looks correct:

```
---
title: Test document
author: tested
date: "2022-01-24"
documentclass: book
site: bookdown::bookdown_site
output:
  bookdown::word_document2: default
  bookdown::epub_book: default
  bookdown::odt_document2: default
---

# Theory {#theory}

...

see <a href="#label1">1.1</a>.

...

## Some other header {#label1}

...

### Third level header {#label2}

* list:

  1. see <a href="#label2">1.1.1</a> above.



<!--chapter:end:index.Rmd-->
```

Please join your efforts with @jgm and solve this issue.

**Comment by cderv** [comment]
Thanks for the report. As answered https://github.com/jgm/pandoc/issues/7862#issuecomment-1020096118, this is due to new behavior added in Pandoc 2.17 where HTML content will be wrapped by default as with other content. 

We need to explicitly non wrap

**Comment by N0rbert** [comment]
Thanks, @cderv . I really appreciate your help. 

I can't determine the ways to debug this by myself. I tried both Profiling and Debuging in RStudio without any luck. For me it seems that rmarkdown calls pandoc beforeThanks, @cderv . I really appreciate your help. I can't determine the ways to debug this by myself. I tried both Profiling and Debuging in RStudio without any luck. For me it seems that rmarkdown calls pandoc before final *knit.md* → *epub* call.
Could you please tell me how to make first *_main.Rmd* → *_main.knit.md* conversion more verbose and traceable? 
I debug the second step (*_main.knit.md*  → *epub*) using `pandoc_args: [--verbose, --trace]`. But I do not know how to debug the first conversion when *_main.knit.md* is obtained. final *knit.md* → *epub* call.
Could you please tell me how to make first *_main.Rmd* → *_main.knit.md* conversion more verbose and traceable? 
I debug the second step (*_main.knit.md*  → *epub*) using `pandoc_args: [--verbose, --trace]`. But I do not know how to debug the first conversion when *_main.knit.md* is obtained.

**Comment by cderv** [comment]
Please try the PR it should solve it

```r
remotes::install_github("rstudio/bookdown#1305")
```

> For me it seems that rmarkdown calls pandoc before final knit.md → epub call.

Yes, pandoc is called during pre processing by **bookdown**. You can see that in the PR. 

> I can't determine the ways to debug this by myself.

I am a bit biased because I know maybe more of the internals. Here for example, I know which part of the process is supposed to handle the cross reference. So I am debugging specifically this part. 

However, usually I try to idenitfy which part of the process can have changed. 
* Is it during knitr processing ? 
* Is it during pre processing before Pandoc conversion ? (and sometimes it will call Pandoc also for a pre process)
* Is it during post processing after Pandoc conversion ? 

Setting breakpoint ins those part and comparing the resulting file could help. 

> I debug the second step (_main.knit.md → epub) using pandoc_args: [--verbose, --trace]

Interesting, I never have done that yet. I'll try. 

> But I do not know how to debug the first conversion when _main.knit.md is obtained.

I set breapoinks in `rmarkdown::render()` usually where I want to stop in the process, like before kniting or after knitting. 
**bookdown** will be a bit special because of heavy pre / post processing so I set breakpoints in there too. 

Also, for an issue with a Pandoc upgrade, I dig first in the release not  to have hint of what could be the issue.

**Comment by N0rbert** [comment]
Thanks for both explanation and PR! 
It now works as expected.

**Comment by cderv** [comment]
@N0rbert I have merged the change. Dev version should work for you now. 

Thanks a lot for the report!

**Comment by N0rbert** [comment]
I'm sorry, but I got the same bug again using latest versions, see

```
> rmarkdown::pandoc_version()
[1] ‘2.17.1.1’
> xfun::session_info('bookdown')
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS, RStudio 2022.2.0.443

Locale: C

Package version:
  base64enc_0.1.3 bookdown_0.24   digest_0.6.29   evaluate_0.15   fastmap_1.1.0   glue_1.6.2     
  graphics_3.4.4  grDevices_3.4.4 highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.8.0 
  knitr_1.37      magrittr_2.0.2  methods_3.4.4   rlang_1.0.1     rmarkdown_2.11  stats_3.4.4    
  stringi_1.7.6   stringr_1.4.0   tinytex_0.37    tools_3.4.4     utils_3.4.4     xfun_0.29      
  yaml_2.3.5  
```

Who is responsible in current situation?

**Comment by cderv** [comment]
Are you using the dev version of **bookdown** ? I see ` bookdown_0.24` in your session info.

The fix is not yet in a released version on CRAN, we are a bit out of schedule and we will make a release very soon.

**Comment by N0rbert** [comment]
The dev version works normally. Thanks!
