### ISSUE TITLE
Pandoc 2.17 will now auto wrap HTML content, which could break our process

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#1304]
In Pandoc 2.17, `--wrap` is now taken into account by HTML output. The default automatic wrapping applies. This will probably breaks some of our process (as **bookdown** not optimally uses regex matching / parsins on line by line basis)

I believe https://github.com/jgm/pandoc/issues/7862 is related to that as `process_markdown()` will run `pandoc_convert()` on HTML to parse the reference. 

It is possible this change affect other part of the process. We should probably set `--wrap = "none"` for all **bookdown** output format.

**Comment by yihui** [comment]
Currently we are using `--wrap=preserve` but I don't remember the specific reason now: https://github.com/rstudio/bookdown/blob/236e07b443deb7bfa049bbda206489e4e6816bb6/R/html.R#L78-L82

**Comment by cderv** [comment]
Maybe I should use `pandoc_args2()` as a fix in #1305 :think?  I'll try to see if that fixes it too.

**Comment by cderv** [comment]
I think the fact that we are setting `--wrap`  to `preserve` is preventing us another issue by this Pandoc 2.17 change. 

I'll close and reopen if we found something else later on.
