### ISSUE TITLE
[FR] References at the end of page in bs4_book

### ISSUE THREAD

**Issue by dietrichson** [rstudio/bookdown#1306]
In the original bookdown format references show up at the bottom of the page in which they appear. This seems to have disappeared in the bs4_book template.

**Comment by cderv** [comment]
`gitbook()` and `bs4_book()` does not work the same and have not the same default. You can find there documentation in the book, in the Output format chapter: https://bookdown.org/yihui/bookdown/output-formats.html

Specifically `bs4_book()` uses inline footnotes and it applies on reference too. This means that by default `split_bib = FALSE` for this format. You need to reactivate it if you prefer this output. 
See part about this in `bs4_book()` documentation: https://bookdown.org/yihui/bookdown/html.html#referencesbibliography

Is this what you are looking for ? 

Hope it helps

**Comment by dietrichson** [comment]
@cderv This is exactly what I was looking for. Thanks!
