### ISSUE TITLE
DT style changing in bookdown gitbook version

### ISSUE THREAD

**Issue by ugurdar** [rstudio/bookdown#1309]
Hi,

I try to create a custom DT in bookdown but style of table changing in bookdown. When I use bs4 there is no problem but gitbook style change the style.  How can I implement my customized table in bookdown gitbook style?
 
My code:

```
datatable(
fillContainer = FALSE,
width = '100%',
caption = htmltools::tags$caption(
style = 'caption-side: top; text-align: center; color:#2569a9;
font-size:180% ;','Caption'),
data.frame(a = 1:5,b=6:10),

class = 'table-bordered',
callback = JS(
  '$("button.buttons-excel").css("background","#2569a9");
   $("button.buttons-excel").css("color","#fff");
   $("button.buttons-excel").css("border","#fff");
   $("button.buttons-excel").css("font-size","10px");
   $("button.buttons-pdf").css("background","#2569a9");
   $("button.buttons-pdf").css("color","#fff");
   $("button.buttons-pdf").css("border","#fff");
   $("button.buttons-pdf").css("font-size","10px");
   return table;'
),
extensions ='Buttons',
options = list(
  dom='Bt',ordering=F,
  buttons = c('excel', 'pdf'),

  initComplete = JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#2569a9', 'color': '#fff'});",
     paste0("$(this.api().table().container()).css({'font-size': '", "10px", "'});"),
    "}"
  )

)

)
```

Output of table in Rmarkdown
![customizedtable](https://user-images.githubusercontent.com/37039994/154013495-a3e75144-7024-4365-aeee-9bc2a6f6e324.png)

Output of table in Bookdown
![image](https://user-images.githubusercontent.com/37039994/154013846-b2a51c2b-6dc2-4a23-8ecb-323dbe0b6250.png)

**Comment by cderv** [comment]
It is highly possible that there are some conflicts in CSS as Gitbook format loads its own CSS. There is an option `table_css` you can try set to FALSE to not load the CSS for table from Gitbook format. 
See arguments in the doc: https://pkgs.rstudio.com/bookdown/reference/gitbook.html

**Comment by ugurdar** [comment]
Thank you! It's working. 

I added ´table_css: false´ in output.yml 

´´´
bookdown::gitbook:
  table_css: false
´´´
