### ISSUE TITLE
Support unlisting sections in TOC in `bs4_book()` as other formats

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/bookdown#1317]
# Issue summary

Both [the cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/toc-unlisted.html) and [pandoc documentation](https://pandoc.org/MANUAL.html#extension-header_attributes) says that a section will not be included in the TOC if it has class `.unlisted` (and this feature is available for HTML). But this doesn't seem to work (anymore?) for `bookdown::bs4_book()` output.

I have created a minimial reprex bookdown project [here](https://github.com/IndrajeetPatil/minimalBookdown/), but posting the key details below.

# RMarkdown input

![image](https://user-images.githubusercontent.com/11330453/158032266-cd8ba917-2c30-4392-b872-fb7b5efcd7b8.png)

# Rendered output

Note that, as expected, `.unnumbered` class works as the corresponding section is not numbered in the TOC. 
But `.unlisted` class doesn't because the section is still included in the TOC.

![image](https://user-images.githubusercontent.com/11330453/158032363-9715be52-b324-47be-940f-f87ab2dfc3c3.png)

# Session info

I am using the latest `pandoc` (`2.17.1.1`) and GitHub/development version of _bookdown_, _rmarkdown_, and _knitr_.

<details>
<summary>Session info</summary>
<pre>

sessioninfo::session_info(include_base = TRUE)
#> - Session info -------------------------------------------
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Windows 10 x64 (build 22000)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United Kingdom.1252
#>  ctype    English_United Kingdom.1252
#>  tz       Europe/Berlin
#>  date     2022-03-12
#>  pandoc   2.17.1.1 @ C:/Program Files/RStudio/bin/quarto/bin/ (via rmarkdown)
#> 
#> - Packages -----------------------------------------------
#>  ! package     * version    date (UTC) lib source
#>    base        * 4.1.2      2021-11-01 [?] local
#>    bookdown      0.24.11    2022-03-12 [1] Github (rstudio/bookdown@7fd6224)
#>    bslib         0.3.1      2021-10-06 [1] CRAN (R 4.1.1)
#>    cachem        1.0.6      2021-08-19 [1] CRAN (R 4.1.1)
#>    cli           3.2.0      2022-02-14 [1] CRAN (R 4.1.2)
#>  P compiler      4.1.2      2021-11-01 [2] local
#>  P datasets    * 4.1.2      2021-11-01 [2] local
#>    digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
#>    downlit       0.4.0.9000 2022-03-12 [1] local
#>    evaluate      0.15       2022-02-18 [1] CRAN (R 4.1.2)
#>    fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.1)
#>    fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
#>  P graphics    * 4.1.2      2021-11-01 [2] local
#>  P grDevices   * 4.1.2      2021-11-01 [2] local
#>    htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
#>    jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.1.1)
#>    jsonlite      1.8.0      2022-02-22 [1] CRAN (R 4.1.2)
#>    knitr         1.37.6     2022-03-12 [1] Github (yihui/knitr@d919733)
#>    magrittr      2.0.2      2022-01-26 [1] CRAN (R 4.1.2)
#>    memoise       2.0.1      2021-11-26 [1] CRAN (R 4.1.2)
#>  P methods     * 4.1.2      2021-11-01 [2] local
#>    R6            2.5.1.9000 2022-03-02 [1] local
#>    rlang         1.0.2      2022-03-04 [1] CRAN (R 4.1.2)
#>    rmarkdown     2.13.1     2022-03-12 [1] Github (rstudio/rmarkdown@1ef2cf3)
#>    rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.1)
#>    sass          0.4.0      2021-05-12 [1] CRAN (R 4.1.1)
#>    sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
#>  P stats       * 4.1.2      2021-11-01 [2] local
#>    stringi       1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
#>    stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.2)
#>  P tools         4.1.2      2021-11-01 [2] local
#>  P utils       * 4.1.2      2021-11-01 [2] local
#>    xfun          0.30       2022-03-02 [1] CRAN (R 4.1.2)
#>    xml2          1.3.3      2021-11-30 [1] CRAN (R 4.1.2)
#>    yaml          2.3.5      2022-02-21 [1] CRAN (R 4.1.2)
#> 
#>  [1] C:/Users/IndrajeetPatil/Documents/R/win-library/4.1
#>  [2] C:/Program Files/R/R-4.1.2/library
#> 
#>  P -- Loaded and on-disk path mismatch.
#> 
#> ----------------------------------------------------------
</pre>
</details>

**Comment by cderv** [comment]
Thanks for the report. 

I don't think this is not working anymore, I think it is not supported by `bs4_book()` because the TOC is not build by Pandoc. The table of content is built directly by `bs4_book()`. 
https://github.com/rstudio/bookdown/blob/7fd62243cee01f8c19a65f73379e18b45f9f01b3/R/bs4_book.R#L53-L54

This means that Pandoc's feature for TOC won't work for `bs4_book()`. 

This would be a feature request for `bs4_book()` to support the same features as Pandoc's TOC. 

So for now, this is not supported by `bs4_book()`, and it is a feature as it is usually not as useful to ignore unnumbered and ignore a header in TOC for a book format, as it could for a single document format. 

Do you have a use case for this or just noticed the difference ? 

I don't know if it would be easy to add, but I am not a fan of porting Pandoc's own feature in R, especially in opinionated format as `bs4_book()`. If you want to try and send a PR for this, please do and I'll review it to consider the feature support.

**Comment by IndrajeetPatil** [comment]
Thanks for the detailed explanation for why I am seeing this difference!

The interesting thing is that this used to work. Well, more specifically, I was using `{-}` to avoid numbering sections, and somehow it also hid the sections from TOC. I _know_ that this used to work because I've been building a bs4 book in a private repo for the last six months. I noticed this change in behaviour only in the last couple of weeks; not sure what changed. 

That said, if this was never supposed to work, then what I was seeing might have been [off-label usage](https://www.tidyverse.org/blog/2021/06/off-label-uses-in-ggplot2/).

> Do you have a use case for this or just noticed the difference?

The latter; although, I can definitely see that some authors may wish to hide some sections, and it'd be nice to provide them with an option.

> I don't know if it would be easy to add, but I am not a fan of porting Pandoc's own feature in R

I can give this a try.

**Comment by cderv** [comment]
>  I know that this used to work because I've been building a bs4 book in a private repo for the last six months. I noticed this change in behaviour only in the last couple of weeks; not sure what changed.

If we found what changed, that could be a hint. I don't recall anything on **bookdown** side about that. I don't see any change in `build_toc()`: https://github.com/rstudio/bookdown/blame/233afc816df38bb69edcc3e0bc3a79dbde06881b/R/bs4_book.R#L142

Possibly related to an upgrade in Pandoc version maybe ? 

> I can definitely see that some authors may wish to hide some sections 

I am not sure to see when that would be useful to hide some section in the TOC for `bs4_book()`. However, if you want to look at how to support it then feel free to try. Thanks !

**Comment by IndrajeetPatil** [comment]
> I am not sure to see when that would be useful to hide some section in the TOC

Thinking more about this, I think I have come around to share your point of view 😅 

Even places where I desired to hide sections from the TOC, it made more sense actually to not create those sections in the first place, avoiding any need to hide them in the TOC. 

Thanks for providing a moment of clarity 🙃
