### ISSUE TITLE
Blank page header after unnumbered first chapter shows wrong chapter name

### ISSUE THREAD

**Issue by darylz** [rstudio/bookdown#1318]
```
$ R -v
radian version: 0.5.12
r executable: /usr/local/Cellar/r/4.1.3/lib/R/bin/R
r version: 4.1.3
python version: 3.9.7
```

```
r$> packageVersion("bookdown")                                                                                                                             
[1] ‘0.24.11’
```

In my project the first chapter is "Preface" which is unnumbered. It's found the blank page's header shows wrong chapter name like "CONTENTS" or "LIST OF FIGURES".

So I downloaded the demo book from https://github.com/rstudio/bookdown-demo and modified the first chapter to "nunumbered". It looks having the same issue.

![image](https://user-images.githubusercontent.com/746947/158053164-4115b2f8-5942-4451-8453-5a5c7c41ccb0.png)

**Comment by darylz** [comment]
update: 
I just fixed it by adding `\markboth{Preface}{}` after `# Preface {-}`.

I think this can be added by bookdown automatically.

**Comment by darylz** [comment]
UPDATE:

I correct it using `\markboth{PREFACE}{}`, but don't know if there is any more elegant solution?

**Comment by cderv** [comment]
I think this is something specific to `documentclass: book` sets for `pdf_book()`. Unnumbered chapters won't make it to page header. I believe this is confirmed by the doc https://www.latex-project.org/help/documentation/classes.pdf for book class p.21 - Only numbered chapter are put in left page header (`\ifnum` is used). 

So if you want to change that, using `\markboth` command seems a good solution. Thanks for sharing this back !
