### ISSUE TITLE
Book in pdf format with rmd_files: in _bookdown.yml fails to compile 

### ISSUE THREAD

**Issue by ellessenne** [rstudio/bookdown#1323]
Hi,
I developed a {bookdown} template for theses at a certain institution, and some user now reported the following error when trying to compile the book via the "Knit" button in RStudio:

```r
Error in files2[[format]] : 
  attempt to select less than one element in get1index
Calls: <Anonymous> ... <Anonymous> -> <Anonymous> -> render_book -> source_files
Execution halted
```

However, using the "Build Book" button from the "Build" tab in RStudio seemed to work fine.
Interestingly, I noticed that this is likely due to using `rmd_files: [...]` in the `_bookdown.yml` file, as if I removed that, it compiles without issue either way.

You can find the repository at that specific point in time [here](https://github.com/ellessenne/uol-thesis/tree/fa7b3913b95ce4fa69ea2c818e8d277fff016917), in the `bookdown` folder (I now removed the `rmd_files` part).

I tried installing the latest version from GitHub, but the issue still persists.

I hope this helps, and thanks for the fantastic work on {bookdown}!

Alessandro

**Comment by cderv** [comment]
Thanks for the report. I can confirm this happen when no format is passed to `render_book()`. This comes indeed from `rmd_files` config when using per-format selection where somehow `format` is NULL here where it should not be
https://github.com/rstudio/bookdown/blob/5c4332b441e372b40b8faf84a71c34b9874afd74/R/utils.R#L104

I'll look into that. Thanks for the report , and for the repo for reproducibility !  that helps a lot!

**Comment by cderv** [comment]
> some user now reported the following error when trying to compile the book via the "Knit" button in RStudio:

By the way, was it working before ? Because I don't think we handled correctly the case where no format is passed to `render_book()` and `rmd_files` config is using a per-format key. I don't think this as ever worked. 

If it did it would be helpful to know so that we check this regression, otherwise, I'll fix this as a new bug. thanks !

**Comment by ellessenne** [comment]
Thanks for looking into this @cderv!

I am pretty sure it did work at some point, at least it did when I first created that template (the repository had a compiled book with that setup) in February of 2020...

**Comment by cderv** [comment]
I asked because I can't find a previous **bookdown** version that worked for now. Maybe at the time you rendered using the Build button and it worked ok.

**Comment by ellessenne** [comment]
That might actually be the case, for this template – I know I used the `render_book()` function with a similar setup before (programmatically, in a Makefile), but there I actually passed the `pdf_book()` format (which, if I understood correctly, would have prevented this issue).

**Comment by cderv** [comment]
> which, if I understood correctly, would have prevented this issue

Yes this issue would still be hidden. Thank you for not doing that and letting us know that there is an issue 😄

**Comment by ellessenne** [comment]
No worries, glad to help - and thanks again for {bookdown}! 😄
