### ISSUE TITLE
Suggestion: add example book that shows how to publish with on GitHub

### ISSUE THREAD

**Issue by daattali** [rstudio/bookdown#133]
I'm playing around with bookdown and it's awesome. @jennybc and I want to use it and have it ready for the upcoming useR. 

I just read the section on [publishing with GitHub](https://bookdown.org/yihui/bookdown/github.html) and I'm a bit confused and not exactly sure how it works. It would be very helpful IMO if there was an example github repository that was set up to serve a bookdown book so that we can see how everything should look.

The part I'm mostly confused about is that currently the entire book project is a repository: [link](https://github.com/daattali/happy-git-with-r).  But the actual book HTML is inside the `_book`. folder, so in order to actually access the book, I need to go to daattali.github.io/happy-git-with-r/_book 

Can we have one repo that contains both the book metadata and source and HTML output?  I also wasn't sure if the `.nojekyll` file should go in the root dir or in the `_book` dir.

I hope these questions make sense!

**Comment by byzheng** [comment]
It seems this a bug of bookdown. The output has to be under _book folder. I just add an index.html to root folder to automatically redirec to _book folder. See my example here https://github.com/byzheng/APSIM-Wheat-Doc.BTW: This repo is complied and published by travis.

**Comment by byzheng** [comment]
Sorry link should be: https://github.com/byzheng/APSIM-Wheat-Doc

**Comment by yihui** [comment]
You copy everything under _book to the root directory of your gh-pages branch, and you will be able to view the website at daattali.github.io/happy-git-with-r/ instead of daattali.github.io/happy-git-with-r/_book That is what this line in the doc does:

```
cp -r ../_book/* ./
```

The master branch only contains the source files, and gh-pages only contains output files. _book is excluded in master, and copied to gh-pages. Is that more clear?

**Comment by daattali** [comment]
Thank you for chipping in @byzheng . It was helpful to see your repo as a working example (although the idea from the bookdown docs is a bit better because the URL doesn't include "_book" in it).  And thanks for clearing it up @yihui , it does make sense.

I do still think that having a repo set up where the travis file and bash scripts are set up would be helpful, especially because there are a few code chunks and it'd help to make it 100% clear which ones are what file (travis vs deploy.sh vs build.sh)

**Comment by jennybc** [comment]
OMG I got this working 🎉! A critical piece that I didn't see mentioned anywhere is the importance of a DESCRIPTION file, with `bookdown` in the Imports and in Remotes.

**Comment by daattali** [comment]
@jennybc RIGHT!  That's why I was struggling with travis for half an hour to get it to install devtools and bookdown.... I couldn't figure out why travis didn't have those packages available, so I had to manually `install.packages("devtools")` in my travis config.  Good call adding that to the DESCRIPTION, will probably safe many people a lot of time

**Comment by raghavendrajain** [comment]
Hello my gh-pages was already setup and I did exactly as yihui suggested. 

I can see the book on my github.io page however no images are seen. what change should I do?
