### ISSUE TITLE
[FR] Add `daemon` logical parameter to `bookdown::render_book`

### ISSUE THREAD

**Issue by mettekou** [rstudio/bookdown#1334]
A `daemon` or `watch` logical parameter to `bookdown::render_book` to watch the files in `rmd_subdir` or `rmd_files` for changes and rerender the book when a change happens would be useful.

# Workaround

Using `inotifywait` on UNIX systems.

**Comment by yihui** [comment]
Sounds like you were looking for `bookdown::serve_book()`: https://bookdown.org/yihui/bookdown/serve-the-book.html

**Comment by mettekou** [comment]
> Sounds like you were looking for `bookdown::serve_book()`: https://bookdown.org/yihui/bookdown/serve-the-book.html

No, because I want to render a PDF, not an HTML document.

**Comment by yihui** [comment]
I see. I assume that you know that rebuilding a PDF is potentially expensive and don't mind that. I'm not particularly interested in adding such a parameter to `render_book()`, but it's not too hard to do it by yourself. Below is an example:

```r
rerender = servr:::watch_dir(handler = function(...) bookdown::render_book())
later::later(rerender, 1)
```

`servr:::watch_dir()` returns a function to watch for changes in a dir, and execute the `handler` if changes are detected. `later::later()` runs a function periodically (e.g., every second in the above example).

You can pass `pattern = '[.]Rmd$'` to `watch_dir()` to only watch for changes in Rmd files.

**Comment by mettekou** [comment]
No, since I want to render the book as PDF, not as HTML.

Yihui Xie ***@***.***> schreef op 5 mei 2022 19:25:54 CEST:

**Comment by yihui** [comment]
Please see my second reply above.
