### ISSUE TITLE
Error in split_chapters due to "duplicated filenames"

### ISSUE THREAD

**Issue by jaum20** [rstudio/bookdown#1335]
I'm getting this erron at the end of the render, in the pandoc part. How these filenames are duplicated? Hown can I debug this?

```
Error in split_chapters(output = output, build = function(...) bs4_book_page(...,  : 
  Automatically generated filenames contain duplicated ones: cap1, cap2, cap3, cap4, cap5, cap6, cap7, cap8, cap9, cap10, cap11, cap12, cap13, cap14, cap15
```

```
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 20.3

Locale:
  LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
  LC_TIME=pt_BR.UTF-8        LC_COLLATE=pt_BR.UTF-8    
  LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=pt_BR.UTF-8   
  LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C            
  LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

Package version:
  base64enc_0.1.3  bookdown_0.26    bslib_0.3.1.9000 cachem_1.0.6    
  digest_0.6.29    evaluate_0.15    fastmap_1.1.0    fs_1.5.2        
  glue_1.6.2       graphics_4.2.0   grDevices_4.2.0  highr_0.9       
  htmltools_0.5.2  jquerylib_0.1.4  jsonlite_1.8.0   knitr_1.39      
  magrittr_2.0.3   memoise_2.0.1    methods_4.2.0    R6_2.5.1        
  rappdirs_0.3.3   rlang_1.0.2      rmarkdown_2.14   sass_0.4.1      
  stats_4.2.0      stringi_1.7.6    stringr_1.4.0    tinytex_0.38    
  tools_4.2.0      utils_4.2.0      xfun_0.30        yaml_2.3.5
```

**Comment by yihui** [comment]
The error message means all of these filenames are duplicated:

```
cap1, cap2, cap3, cap4, cap5, cap6, cap7, cap8, cap9, cap10, cap11, cap12, cap13, cap14, cap15
```

i.e., they appeared more than once as ID's of your section headers.

Without you providing a reproducible example (as requested by the issue guide), there is no way to tell how they were duplicated.

**Comment by jaum20** [comment]
Thank you for your response.
I checked my generated _main.Rmd and find that the whole code is duplicated in the file, so there are two of each chapter. Any idea of what can be causing this problem? [This](https://github.com/paternogbc/livro_aer) is the book

**Comment by yihui** [comment]
That sounds like a bug of **bookdown**. With a quick glance, I didn't see any obvious problems...

@cderv Could you take a look when you have a chance? Thanks!

**Comment by jaum20** [comment]
I was using the command `bookdown::render_book(output_format="bookdown::bs4_book", config_file='_output.yml')`. Removing the `config_file` part make it work fine

**Comment by yihui** [comment]
The `config_file` should point to `_bookdown.yml` (which is the default). You should not point it to `_output.yml`.

**Comment by jaum20** [comment]
> The `config_file` should point to `_bookdown.yml` (which is the default). You should not point it to `_output.yml`.

Thank you for the info!

**Comment by yihui** [comment]
If that fixes your problem, I guess this issue can be closed?

**Comment by jaum20** [comment]
Yes. Thank you
