### ISSUE TITLE
[FR] Generate `PAGE_URL` and `PAGE_IDENTIFIER` automatically for Disqus

### ISSUE THREAD

**Issue by isaactpetersen** [rstudio/bookdown#1336]
I'm trying to add Disqus to a bookdown site. The embedded Javascript code includes [Javascript configuration variables](https://help.disqus.com/en/articles/1717084-javascript-configuration-variables) that are [important for avoiding split threads and missing comments](https://help.disqus.com/en/articles/1717137-use-configuration-variables-to-avoid-split-threads-and-missing-comments). Thus "*[Disqus recommends] that you define the `PAGE_URL` and `PAGE_IDENTIFIER` configuration variables within the `disqus_config` section of your embed code.*" How can these be specified automatically?

Here's the relevant section of the embed code:

```
var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
```

For instance, the Disqus documentation notes that: "*These variables should be defined by using your CMS’ or platform’s dynamic values, if available. For example, the Disqus WordPress plugin defines these variables by default using the following PHP values:*"

```
this.page.url = '<?php echo get_permalink(); ?>';
this.page.identifier = '<?php echo dsq_identifier_for_post($post); ?>';
```

As noted [here](https://github.com/rstudio/bookdown/issues/81#issuecomment-356824941):
"*the embedded javascript code requires the url of the webpage (so the url of the page you're generating with bookdown). The domain can be indicated manually, since it is only known by the author, of course ; but what about the relative path of any given webpage? Is there any automatic way of generating it (i.e., something similar to a {{page.url}} liquid tag)?*"

This is a similar issue for adding Discourse: https://github.com/rstudio/bookdown/issues/81#issuecomment-356824941

**Comment by cderv** [comment]
This feature is not built-in. 

Currently, you would need to post process your resulting HTML files to add the necessary JS in HTML by processing the information you have. (like the filename and site url to create the page.url). 

We could maybe try to add this as a feature where we would insert the part when doing the splitting. If someone wants to have a go for it please feel free to jump in and we'll review happily. 

How I would try to do it: 

1. When converting to book format, a single markdown file is produced and passed to Pandoc to generate a single HTML file. 
2. As post processing, this HTML file is split in files according to the `split_by` options (like chapters)

I think we could try inserting the correct piece of code for discuss at this stage of the process using the file name and site url. That is why I think this could also be done by yourself after the book has been built. 

Hope it helps

**Comment by isaactpetersen** [comment]
Thanks very much for your helpful response. What you're saying makes sense, and I might need a little more guidance to figure out how to implement that in my case.

My GitHub repo is here: https://github.com/isaactpetersen/Principles-Psychological-Assessment. My book is here: https://isaactpetersen.github.io/Principles-Psychological-Assessment.

The book is built using GitHub Actions in two jobs. The first job, ["build-book"](https://github.com/isaactpetersen/Principles-Psychological-Assessment/actions/workflows/deploy_bookdown.yml) renders the book and creates an artifact called `_book.zip` that contains the `.html` files. The second job, ["pages-build-deployment"](https://github.com/isaactpetersen/Principles-Psychological-Assessment/actions/workflows/pages/pages-build-deployment) creates an artifact called `github-pages.zip` that contains `artifact.tar`, which gets deployed to GitHub pages.

Do you know what I should put for `PAGE_URL` and `PAGE_IDENTIFIER` in my case, or how I would post-process the information in GitHub Actions to achieve this?

Thanks very much for your help.

**Comment by yihui** [comment]
> I'm trying to add Disqus to a bookdown site. The embedded Javascript code includes [Javascript configuration variables](https://help.disqus.com/en/articles/1717084-javascript-configuration-variables) that are [important for avoiding split threads and missing comments](https://help.disqus.com/en/articles/1717137-use-configuration-variables-to-avoid-split-threads-and-missing-comments). Thus "_[Disqus recommends] that you define the `PAGE_URL` and `PAGE_IDENTIFIER` configuration variables within the `disqus_config` section of your embed code._" How can these be specified automatically?

I think you can ignore Disqus's recommendation here, i.e., it's not really necessary to configure these two variables. I've been using Disqus for several years, and have rarely configured these variables. The key point is that _you keep your URLs stable_. As long as you can do that, there is absolutely no need to configure anything for Disqus, just like the example at https://bookdown.org/yihui/bookdown/collaboration.html didn't configure anything.

How to keep **bookdown** page URLs stable? The answer is that you assign fixed identifiers to your (chapter/section) headings: https://bookdown.org/yihui/bookdown/cross-references.html That's because **bookdown** uses these IDs to generate `.html` filenames. If the IDs are fixed, the filenames are fixed, and you get stable (permanent) URLs, no matter how you change the text in the headings in the future.

**Comment by isaactpetersen** [comment]
That's helpful, yihui. That makes sense to use fixed identifiers for chapter and section headings. I'll plan to do that. I'm new to Disqus, so am not exactly sure how it works.

For clarification, if anyone writes a Disqus comment on a given page (e.g., [`/validity.html`](https://isaactpetersen.github.io/Principles-Psychological-Assessment/validity.html))—including on any subsections—I'd like the comment to be shown on that main chapter page. If someone leaves a Disqus comment after clicking on the cross-reference link to a subsection (e.g., [`validity.html#contentValidity`](https://isaactpetersen.github.io/Principles-Psychological-Assessment/validity.html#contentValidity)), my worry is that the Disqus comment wouldn't be shown on the main chapter page (`/validity.html`) because it has a different URL (`validity.html#contentValidity`). Would the Disqus comment on the "subsection page" be correctly shown on the main chapter page? Thanks for clarifying.

**Comment by yihui** [comment]
The hash in the URL `/validity.html#contentValidity` shouldn't matter. I'm reasonably sure if users open this URL and post a comment, the comment will be correctly loaded on `/validity.html`. If you are not sure, feel free to test it by yourself.
