### ISSUE TITLE
Ambiguous meaning of the "r <EXPRESSION>" syntax

### ISSUE THREAD

**Issue by AlbertLei** [rstudio/bookdown#1345]
## Problem description

The following error occurred when I tried to build my book in the gitbook format.

```
Quitting from lines 2-1674 (_main.Rmd) 

<simpleError in parse(text = code, keep.source = FALSE): <text>:1:1: unexpected '='
1: =
    ^>
```

It turns out that the error comes from the code text `` `r = 0.06` ``, where I was talking about the value of interest rate in my code, while bookdown thought I was executing a flawed R expression. Everything works after I remove the space, `` `r=0.06` ``.

## Final remarks

This is not a bug, but it may qualify as an unexpected behavior. I almost never use the `` `r <EXPRESSION>` `` syntax provided by bookdown (and it's standard to use `r` for interest rate).

As I googled "bookdown simpleError in parse ..." and did not find any relevant info, it may help others by documenting my experience here.

## My session info

```
> xfun::session_info('bookdown')
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 2022.2.1.461

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 bookdown_0.24   bslib_0.3.1     digest_0.6.25  
  evaluate_0.14   fastmap_1.1.0   fs_1.4.1        glue_1.6.0     
  graphics_4.0.5  grDevices_4.0.5 highr_0.8       htmltools_0.5.2
  jquerylib_0.1.4 jsonlite_1.7.2  knitr_1.37      magrittr_2.0.1 
  markdown_1.1    methods_4.0.5   mime_0.9        R6_2.5.1       
  rappdirs_0.3.1  Rcpp_1.0.4.6    rlang_0.4.12    rmarkdown_2.14 
  sass_0.4.0      stats_4.0.5     stringi_1.4.6   stringr_1.4.0  
  tinytex_0.36    tools_4.0.5     utils_4.0.5     xfun_0.30      
  yaml_2.2.1     
```

**Comment by yihui** [comment]
Yes, we can improve the error message, which is from here: https://github.com/yihui/knitr/blob/907184f82489488ab8fd3619aa15b9822bf96067/R/hooks.R#L14

An alternative solution for @AlbertLei is to add a space after the first backtick, i.e., write `` ` r  = 0.06` ``. This space is meaningless to Markdown, but will make **knitr** ignore the "inline expression".

**Comment by cderv** [comment]
> An alternative solution for @AlbertLei is to add a space after the first backtick, i.e., write ` r = 0.06`. This space is meaningless to Markdown, but will make knitr ignore the "inline expression".

Once again another nice trick ! 😄

**Comment by cderv** [comment]
@AlbertLei I opened an issue in **knitr** to track the improvment idea. 

I'll close this here. Thanks for the report!

**Comment by cderv** [comment]
@AlbertLei Next version of **knitr** will have an improved error message in this case. Thank you for your report and suggestion !

**Comment by AlbertLei** [comment]
Thanks!
