### ISSUE TITLE
[BS4_Book] Error if chapters have manually assigned duplicate ID 

### ISSUE THREAD

**Issue by shivam7898** [rstudio/bookdown#1348]
## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('bookdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the bookdown package using `remotes::install_github("rstudio/bookdown")` ?

## Steps

- Build a New BS4_book project from RStudio (File -> New Project -> New Directory -> Book project using bookdown -> HTML book format = bs4_book ->  Create Project)
- In the default files generated, manually assign any two first level chapter headers duplicate reference id. Example:
  - In "03-parts.Rmd", change `# Parts` -> `# Parts {#abcd}`
  - In "04-citations.Rmd", change `# Footnotes and citations` -> `# Footnotes and citations {#abcd}`
- Build will fail with a Warning and Error 

```r
#[WARNING] Duplicate identifier 'abcd' at testB.md line 153 column 1

#Error in split_chapters(output = output, build = function(...) bs4_book_page(...,  : 
#  Automatically generated filenames contain duplicated ones: abcd
#Calls: local ... <Anonymous> -> bs4_book_build -> split_chapters -> <Anonymous>
#Execution halted
#Error: bookdown::render_book() failed to render the output format 'bookdown::bs4_book'.
#Execution halted
```
 
## Disclaimers

- I know that manually assigning duplicate ID to different chapters, using `{#abcd}`, is NOT a good practice. However, during the build it only results in `[WARNING] Duplicate identifier ...`. So, I am assuming it is frowned upon but is allowed.
- I have only tested this in BS4_book. However, I suspect the issue might be present in other formats also.

## Thoughts
During the build the `md` files generated for each chapter have filenames same as the associated `Rmd` files. However, the resulting HTML files are generated with filenames based on their reference id i.e.  `# Parts` would result in "parts.html", but `# Parts {#abcd}` would produce "abcd.html". Similar pattern can also be observed when pandoc assigns  automatic reference names for chapter headers of same name, it generates `parts.html`, `parts-1.html` same as their auto generated reference id.

Because, the `md` filenames are same as `Rmd` filenames but html files have different names. It might not be a bug and part of design choice. In that case, I think, the manual duplicate reference id should itself result in ERROR. 

If it is a bug, the HTML filename pattern should be modified to not conflict if duplicate ids are present.

## Session Info

```r
xfun::session_info()
#R version 4.2.0 (2022-04-22 ucrt)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows 10 x64 (build 19044), RStudio 2022.2.3.492
#
#Locale:
#  LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8    LC_MONETARY=English_India.utf8
#  LC_NUMERIC=C                   LC_TIME=English_India.utf8    
#
#Package version:
#  base64enc_0.1.3 bookdown_0.27.1 bslib_0.3.1     cli_3.3.0       compiler_4.2.0  digest_0.6.29  
#  evaluate_0.15   fastmap_1.1.0   fs_1.5.2        glue_1.6.2      graphics_4.2.0  grDevices_4.2.0
#  highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.8.0  knitr_1.39      magrittr_2.0.3 
#  methods_4.2.0   R6_2.5.1        rappdirs_0.3.3  rlang_1.0.2     rmarkdown_2.14  sass_0.4.1     
#  stats_4.2.0     stringi_1.7.6   stringr_1.4.0   tinytex_0.40    tools_4.2.0     utils_4.2.0    
#  xfun_0.31       yaml_2.3.5     
```

**Comment by cderv** [comment]
The WARNING you see is from PANDOC conversion, but **bookdown** is doing other step after the conversion from md to HTML and this step does expect to have each identifier to be unique. 

It is an explicit error thrown here
https://github.com/rstudio/bookdown/blob/d4e71eb949c50aaec47f954f7dc50b19785c4843/R/html.R#L403-L406

You can't have duplicated ID on section that will be used to create the HTML files as they would have the same name in this case.
See about `split_by` in here: https://bookdown.org/yihui/bookdown/html.html#gitbook-style

Especially `bs4_book()` will split by chapters using the header level 1 - if you assign an ID it will be used from filename, so you can't put the same. 

If you place same ID on headers that are not used to create the HTML file name you won't get any error. (But you'll still get the Pandoc warning)

Hope it helps understand

**Comment by shivam7898** [comment]
From your link:

> The header identifier is automatically generated from the header text by default, and you can manually specify an identifier using the syntax {#your-custom-id} after the header text

Yes, thank you for the link & detailed clarification. Although, I assumed that this was not a bug, I could have done some more reading myself before posting. Sorry, for not looking it up properly! 

Please feel free to close this one (I am unsure about closing this by myself).

**Comment by cderv** [comment]
Glad we do not have an issue with that! The splitting code is quite complex. 

Thanks for opening an issue ! Always appreciated, do not hesitate again. No worries to miss something.
