### ISSUE TITLE
How to deploy without publicizing?

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#135]
I am embarrassed to see an experiment of ours (@daattali's version/fork) showing up on <https://bookdown.org>. This has no content. ~~BTW I've got him working to bring that down!~~ *at least it 404s now*

How can one develop a book, up to and including deployment, but NOT have it show up somewhere like that? I don't want to leave deployment to the end, because I've learned from, e.g., Shiny, that only leads to heartache. And I don't mind the development version being visible to someone who knows a URL or bothers to look on GitHub. But how can I keep it from appearing on  <https://bookdown.org> as if I want people to read it?

<img width="915" alt="screen shot 2016-06-16 at 1 16 08 pm" src="https://cloud.githubusercontent.com/assets/599454/16131822/2c20c0d0-33c5-11e6-995b-c32d598d9f02.png">

**Comment by daattali** [comment]
The book was deleted a few minutes before this issue was opened. But yes, it was a bit unexpected to see something that I just played around with in rstudio for 5 minutes appear on the front page.  Might be good to have a checkmark somewhere like "I agree to have this book appear in the gallery and be browse-able" to prevent these things?

**Comment by yihui** [comment]
Sorry about that. The homepage was generated semi-automatically. Ideally we should provide an option for authors to decide whether they want their books to be listed on the homepage. Anyway, I just added the link `https://bookdown.org/daattali/happy-git-with-r/` to our "blacklist" so it will not appear again until you explicitly ask us to list it.

**Comment by jennybc** [comment]
Thanks! Of course, one day I might want it there. But after we go through the awkward teenager phase. Yes, an "opt in" somewhere in the book setup or in RStudio Connect would be perfect.

**Comment by pssguy** [comment]
+1 for option to opt in or out. Otherwise who should be contacted re getting on blacklist and can this be done prior to deploying?

**Comment by yihui** [comment]
After you log in, you can set who can view your book:

<img width="329" alt="screen shot 2016-07-07 at 3 50 23 am" src="https://cloud.githubusercontent.com/assets/163582/16647673/ffaed032-43f5-11e6-923c-2a0e8c8a437e.png">

If you do not want other people to see your book yet, you may choose one of the three options below "Everyone".

@trestletech Is it possible for you not to list the book in _sitemap.xml if the book is set to be private?
