### ISSUE TITLE
Clipboard does not work

### ISSUE THREAD

**Issue by chadyuu** [rstudio/bookdown#1358]
I am facing an issue with the clipboard when reading a web book generated by bookdown.

## an example case

1. Open [2.2 Markdown extensions by bookdown](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html) in "bookdown: Authoring Books and Technical Documents with R Markdown" 
2. We can copy any chunks we want by hitting the clipboard icon like this.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/8579255/177493792-6f4f7736-b871-42bc-bdef-b10b47a4f0ab.png">

3. However, we cannot copy after clicking the internal link in the same chapter. E.g., click "2.2.2 Theorems and proofs" in the left index, as the following image shows.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/8579255/177493303-4e9f3605-8b66-4d66-a030-e62738f4cca5.png">

This issue might relate to the Javascript codes on the clipboard function, but I would appreciate any advice or solution.

**Comment by cderv** [comment]
Thanks for the report. 

I think we have indeed an issue in the clipboard plugin as we are wrongly removing the clipboard feature in this case. 
https://github.com/rstudio/bookdown/blob/4af5406de3f7ff6b69e5cfb251431994387437f1/inst/resources/gitbook/js/plugin-clipboard.js#L10-L17

I'll see if I can come with a quick fix

**Comment by chadyuu** [comment]
Thanks again! The necessity of `clipboard.destroy()`  still remains a mystery, though...
