### ISSUE TITLE
possible to preview README.md?

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#136]
If I am editing `README.md` and use the keyboard shortcut for "knit" or click "Preview", I am taken to a preview of my book, pointed at index.html. I was only able to preview my README via `rmarkdown::render("README.md")` + open the html in the browser. Am I missing something? Or could `README.md` be treated in a more conventional way in the bookdown context?

**Comment by yihui** [comment]
That is an RStudio IDE issue, and I think it makes sense not to treat README.md as a book chapter. As you know, most of us have been busy preparing for useR recently, so this issue is likely to be resolved after useR.

**Comment by yihui** [comment]
I have filed an issue to the RStudio IDE team.
