### ISSUE TITLE
[FR] How to embed custom css and HTML into bookdown

### ISSUE THREAD

**Issue by MonteShaffer** [rstudio/bookdown#1365]
Hello,

https://shhdharmen.medium.com/announcing-keyboard-css-show-off-your-keyboard-shortcuts-with-style-a83f488c6ecb

has a style guide to render "shortcut keys" as buttons:

HTML
```
<p>Press <kbd class="kbc-button">Ctrl</kbd> + <kbd class="kbc-button">Shift</kbd> + <kbd class="kbc-button">R</kbd> to re-render this page.</p>
```

How can I render the above html with the corresponding CSS from the website in the HTML knit of bookdown?

**Comment by yihui** [comment]
This is a question about CSS. Please follow the issue guide when you want to ask questions: https://github.com/rstudio/bookdown/issues/new/choose Thanks for your understanding!
