### ISSUE TITLE
Deletion of several .md chapters!

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#137]
I just decided to experiment with the `(PART)` token. When I first tried to save this file, I got an unexpected message. It was so weird I took a screenshot, just in case ...

<img width="1434" alt="screen shot 2016-06-17 at 2 00 29 pm" src="https://cloud.githubusercontent.com/assets/599454/16164659/479ff7e8-3494-11e6-951f-0a767fed6b6e.png">

I clicked No. File stayed open. Next attempt to save worked. BUT all my other chapters were deleted. Check out my Git pane:

<img width="522" alt="screen shot 2016-06-17 at 2 05 20 pm" src="https://cloud.githubusercontent.com/assets/599454/16164690/7a6c0cc0-3494-11e6-8c41-89ed431e1475.png">

Luckily I committed just prior to this experiment, so have lost nothing. But others might not be so lucky. I feel like I experienced intermittent single file disappearance earlier, but nothing I could really describe clearly enough to merit an issue. This is a big one though.

Any idea what just happened?

**Comment by jennybc** [comment]
I restored everything. Made more changes. COMMITTED. Then built the book. And again my md files are deleted.

<img width="522" alt="screen shot 2016-06-17 at 3 15 13 pm" src="https://cloud.githubusercontent.com/assets/599454/16166217/59af1234-349e-11e6-9161-435daa071ac0.png">

I started out with Rmd files because I forked the demo book. But eventually realized I had little/no R code and switched everything possible to md. I wonder if these are being deleted in some overzealous deletion on (allegedly) intermediate markdown?

**Comment by jjallaire** [comment]
Two issues here:

1. Bookdown only works with .Rmd not with plain .md

2. Even so there's no way those files should have been deleted! We'll
investigate.

**Comment by jennybc** [comment]
Duly noted that everything must be Rmd. I had already switched back to that! 

But here's what the manual says:

> Although we have been talking about R Markdown files, the chapter files do not actually have to be R Markdown. They can be plain Markdown files (.md), and do not have to contain R code chunks at all. You can certainly use bookdown to compose novels or poems!

https://github.com/rstudio/bookdown/blame/7198f944c73523e0afe5d4a0d5aa7c9fa1c8f0ee/inst/examples/index.Rmd#L142

**Comment by jjallaire** [comment]
Interesting! I know that R Markdown Websites require .Rmd so I was assuming
that bookdown did as well. @yihui ?

**Comment by yihui** [comment]
bookdown does not require .Rmd; if you use .md, you will have to specify `rmd_files` in `_bookdown.yml`.

**Comment by jjallaire** [comment]
Any idea why the .md files might have been deleted?

**Comment by yihui** [comment]
I just renamed all Rmd to md in the bookdown-demo repo, but could not reproduce the issue.

**Comment by jennybc** [comment]
I just did this: renamed a single chapter .Rmd --> .md. Edited its entry in `_bookdown.yml` to reflect that. Built book. Now the Rmd is gone (makes sense), but so is the md for that file. Makes no sense. The content is even present in the preview in front of my eyes. But if I close that and build again. I get this:

```
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... mapply -> <Anonymous> -> readUTF8 -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file '03_workshops.md': No such file or directory
Execution halted

Exited with status 1.
```

**Comment by jennybc** [comment]
@yihui 

I just successfully repeated this entire sequence three times with exact same result. Maybe someone else can.

Start with a book that has been successfully built, all chapters are Rmd, but are also listed in `_bookdown.yml`.

Rename a single chapter Rmd --> md and edit `_bookdown.yml`.

Build book. Preview looks fine, but chapter md is gone. Close preview and attempt to rebuild. Get error above.

Strange: Restore the chapter file and immediately rename Rmd --> md again. Build book. Works AND the md file survives.

**Comment by rdpeng** [comment]
FWIW this happened to me too, but I just converted everything to Rmd and everything was fine thereafter.

**Comment by yihui** [comment]
Ah! I see. You guys are using `new_session: yes` in `_bookdown.yml`. The .md files are actually not removed, but moved to the _book/ directory instead. Anyway, I just fixed this issue. Thanks!
