### ISSUE TITLE
Cross-reference with custom link text?

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#138]
I am successfully cross-referencing with `\@ref(label)` as described here:

https://bookdown.org/yihui/bookdown/cross-references.html

But this forces me to write "chapter `\@ref(label)`".

Is there a way to create links in a more conventional markdown style where I get to write the text?

In <http://r4ds.had.co.nz> @hadley uses simple square brackets to achieve this, e.g. `[functions]` to link to the functions chapter. But damn if I can figure out why this works. It does not work for me.

**Comment by yihui** [comment]
You may see #6 for how simple square brackets works.
