### ISSUE TITLE
PDF page headers don't work with unnumbered sections

### ISSUE THREAD

**Issue by jtbayly** [rstudio/bookdown#1382]
Use the demo book, and make the first two chapters unnumbered

`# Prerequisites {-}`

and

`# Introduction {- #intro}`

Now build the PDF. The header on page 8 still says you're in the "Contents" section.

**Comment by cderv** [comment]
I believe this is something related directly to LaTeX and what `{-}` creates. This is a duplicate of https://github.com/rstudio/bookdown/issues/309

It seems it is an old issue in Pandoc that does not add the `\markboth` command which seems to be needed (https://github.com/jgm/pandoc/issues/1632) 

So this is really a LaTeX thing, that could be solved maybe with a preamble, or at least a Pandoc issue when `.unnumbered` is used on header.

**Comment by jtbayly** [comment]
Sorry, I got in a hurry last night. I should have realized this would be connected to Pandoc and looked into it further before reporting it as a bug here. I asked for help over there and got what I needed for now.

**Comment by cderv** [comment]
No worries @jtbayly ! Your feedback and questions are always welcomed ! 

Thanks a lot for sharing your experience with us, that helps a lot.
