### ISSUE TITLE
Past 30 days usage shows nothing

### ISSUE THREAD

**Issue by datamonke1** [rstudio/bookdown#1389]
bookdwon: Past 30 days usage does show nothing.
API query does also not return any activity numbers:

activity:
https://bookdown.org/__docs__/cookbook/user-activity/

What is the CONNECT_SERVER for bookdown: https://bookdown.org/   ? 

The documentation is not clear

**Comment by cderv** [comment]
Thanks for additional information. I understand better now. 

`CONNECT_SERVER` is https://bookdown.org/ , same url as the CONNECT doc. You then need to follow the documentation by creating API KEY before doing request. 

I don't know which error you get, but it works on my side.

**Comment by datamonke1** [comment]
Thanks for the info, but does unfortunately not work.

bookdown page:
on https://bookdown.org/ the now past 30 day information is shown.

with api:
The api does not return any information
Response [https://bookdown.org/__api__/v1/instrumentation/shiny/usage?limit=25]
  Date: 2022-10-03 19:09
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 118 B

content(resp)
$results
list()

$paging
$paging$cursors
$paging$cursors$previous
NULL

$paging$cursors$`next`
NULL


$paging$first
NULL

$paging$previous
NULL

$paging$`next`
NULL

$paging$last
NULL

**Comment by cderv** [comment]
First, there shouldn't be any shiny app on bookdown.org, only books. Are you using the right endpoint ? You should probably not use the shiny one, but the other one.

Also, you need to be the publisher or the application to get some information I believe. 

I don't know the details of the API, you should look at the reference page for the endpoint to see which data is sent back.

**Comment by datamonke1** [comment]
**Also, you probably need to be the publisher or the application to get some information I believe.**
I agree the information seems not accessible by the user.

**Are you using the right endpoint ?** 
Changing the endpoint does not help either. No HTTP error, just no data.

Response [https://bookdown.org/__api__/v1/instrumentation/content/visits?limit=25]
  Date: 2022-10-03 19:39
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 118 B

```
# The CONNECT_SERVER URL must have a trailing slash.
connectServer <- "https://bookdown.org/"
connectAPIKey <- "..."

# Request a page of up to 25 visitation records.
resp <- GET(
  paste0(connectServer, "__api__/v1/instrumentation/content/visits?limit=25"),
  add_headers(Authorization = paste("Key", connectAPIKey))
)

print(content(resp))
$results
list()

$paging
$paging$cursors
$paging$cursors$previous
NULL

$paging$cursors$`next`
NULL


$paging$first
NULL

$paging$previous
NULL

$paging$`next`
NULL

$paging$last
NULL

```

**Comment by cderv** [comment]
Which is your publisher content ? 

From my understanding, you can retrieve data only from your own published content.

**Comment by datamonke1** [comment]
**Which is your publisher content ?**
I just sent you an invitation, and added you to our stats book.

**From my understanding, you can retrieve data only from your own published content.**
The colleague who uploaded the content had no luck. I am a collaborator and cant do it either.

At the end, activity its not even displayed on the bookdown site itself.

**Comment by datamonke1** [comment]
**According to the bookdown admin, the activity feature is most likely disabled by bookdown.org**
