### ISSUE TITLE
serve_book cannot identify modified html if not organized as chapter level

### ISSUE THREAD

**Issue by fecet** [rstudio/bookdown#1396]
I'm writing rmd in subdir(not sure if it's relevant per #1121 and #834), if they are all organized as first-level, i.e. without warning like
```
 You have 7 Rmd input file(s) but only 6 first-level heading(s). Did you forget first-level headings in certain Rmd files?
```
The `serve_book` works fine with `preview=TRUE`, but if I change one's first level into second, it will confused what chapter I'm modifying and re-compile `_book/index.html`.

A minimal exmaple can be found in my fork of bookdown_demo https://github.com/fecet/bookdown-demo/tree/bug, where I changed 
```
# Final Words

We have finished a nice book.

```
to 
```
## Final Words

We have finished a nice book.

```
and can be reproduced by `bash _server.sh`.

As the serve function rely on `preview_chapter`, is this expected and I have to organized my rmds as first-level, if so, is there any workaround? 

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('bookdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the bookdown package using `remotes::install_github("rstudio/bookdown")` ?

**Comment by fecet** [comment]
> Our doc says the following (https://bookdown.org/yihui/bookdown/usage.html#usage)
> 
> > A typical bookdown book contains multiple chapters, and **one chapter lives in one R Markdown file**, with the filename extension .Rmd. **Each R Markdown file must start immediately with the chapter title using the first-level heading**, e.g., # Chapter Title.
> 
> So I believe this is expected in our functions. 
> 
> It is possible that our new tooling called Quarto (https://quarto.org/docs/books/) offers more organization flexibility if **bookdown** is not suitable for your organization. You could have a look there - it is similar to **bookdown**, just more generic and with another layout and organization. 

Great！That is looks like another life-changing to me, do we have
 backward compatibility with bookdown or a guide about migration?

**Comment by cderv** [comment]
You have a good documentation on the main website. **bookdown** and Quarto are both using Markdown, Pandoc, and **knitr** for R execution, so you should be able to migrate quite easily by just changing the configuration. This is because format is different, so you need to tweak the `_quarto.yml` accordingly as the R Markdown format like `gitbook()` won't be recognize. Look at the Quarto website to gets the basics of Projects, and books features. Quarto will have a bit more feature than **bookdown** that you may be interested in. 

How easy the migration will be depend on your book content, and how standard R Markdown it is. 

Some resource online can help, made by users who did the switch. See https://www.openscapes.org/blog/2022/07/21/quarto-migrate/ and https://openscapes.github.io/quarto-website-tutorial/transition-from-rmarkdown.html

Also, `knitr::convert_chunk_header()` is a function to help you convert chunk in a Rmd file to new YAML in chunk syntax inside a qmd file. 

Hope it helps

**Comment by fecet** [comment]
> 

OK, I have migrated to quarto, the workflow seems much more clean and power, preview also works for second level `.qmd` file, I still have two small questions: 
- Is it true that we dont have a `qmd_subdir` option and have to explicitly list files in `chapters`
- I don't find similar things with `preview_chapters` in quarto, what's the scope preview re-render, the whole project or the file changed, or a "chapter" (like  `bookdown`)?

**Comment by cderv** [comment]
> Is it true that we dont have a qmd_subdir option and have to explicitly list files in chapters

Yes I believe this is currently the way to do it. `chapters` key needs to be used to specify the order in which the files should be organized. 

You can ask here https://github.com/quarto-dev/quarto-cli/discussions directly, for a potential feature request

> I don't find similar things with preview_chapters in quarto, what's the scope preview re-render, the whole project or the file changed, or a "chapter" (like bookdown)?

See https://quarto.org/docs/books/#book-preview:  "As you preview your book, chapters will be rendered and updated. "

What are you observing ? Something different ? 

[Quarto Discussion](https://github.com/quarto-dev/quarto-cli/discussions) would be a good place to ask more help if you keep using Quarto. 

I'll close this won't be changed in **bookdown**.
