### ISSUE TITLE
Theorem environment no longer works for slidy presentations.

### ISSUE THREAD

**Issue by urx449** [rstudio/bookdown#1398]
I'm using bookdown v0.31, and latest version of R and RStudio.

Knitting this

````
---
title: "test"
output: bookdown::slidy_presentation2
---

## Slide

::: {.theorem}
NEW
:::

```{theorem}
OLD
```
````

produces this.

![Untitled](https://user-images.githubusercontent.com/121920102/211109925-6f94b905-fbe9-450e-89cc-8582c1e8ad69.png)

The old theorem style used to work in v0.24.

**Comment by cderv** [comment]
Thanks for opening the issue. It should be fine now with dev version of **bookdown**.

Hopefully what we do for HTML output will work ok for slidy also. Please report anything not working as you expect.
