### ISSUE TITLE
Problem with knit and merge

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#14]
When I set `new_session:yes` in `bookdown.yml` I get:

```R
bookdown::render_book("index.rmd")
Error in (function (input, output_format = NULL, output_file = NULL, output_dir = NULL,  : 
  unused argument (run_pandoc = FALSE)
Calls: local ... eval -> eval -> eval -> eval -> do.call -> <Anonymous>
Execution halted
```

Does this suggest I have an out of date dependency?

**Comment by jjallaire** [comment]
Yes, that's a new argument to render introduced recently to rmarkdown (it's
still on github, hoping to submit to CRAN in a week or two)

**Comment by hadley** [comment]
Thanks! Is there a version number of rmarkdown that bookdown could depend on to make this problem more obvious?

**Comment by jjallaire** [comment]
Yes, version 0.9.5 would do the trick.
