### ISSUE TITLE
First chapter in a part comes and goes in preview

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#140]
I'm using the `(PART)` token as described here: https://bookdown.org/yihui/bookdown/markdown-syntax.html.

If I use RStudio's Build Book, the sidebar appears as I expect.

But if I edit then update a single chapter and update the preview by knitting just that chapter, via "Knit", the first chapter in each part disappears from the sidebar. This even affects chapter numbering. I can still navigate to those pages via arrows and, after various amounts of internal navigation, the first chapters reappear in the sidebar and the chapters get renumbered.

**Comment by yihui** [comment]
Previewing means only the current Rmd is rendered, and you should not expect other chapters to work well (including the chapter titles): https://bookdown.org/yihui/bookdown/preview-a-chapter.html

Anyway, for this specific issue, I guess I just fixed it. Thanks!
