### ISSUE TITLE
[FR] Specify encoding  for render_site via bookdown_site generator

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#141]
Hi, 

`rmarkdown::render` accept `encoding` argument. As `bookdown::render_book` calls `rmarkdown::render` and passes `encoding` arg, it also working. 

However, if we use `site: bookdown::bookdown_site` in `index.Rmd`, then when we call `rmarkdown::render_site` (or click and *Build Book* button in RStudio), it is not possible to specify encoding because the `encoding` arg is not pass through the functions and `render` element of `bookdown::bookdown_site` calls `bookdown::render_book` without the `encoding` arg.

see the code of `bookdown::bookdown_site` : 

```r
function (input, ...) 
{
  on.exit(opts$restore(), add = TRUE)
  oldwd = setwd(input)
  on.exit(setwd(oldwd), add = TRUE)
  config = load_config()
  name = find_book_name(config, basename(normalizePath(input)))
  book_dir = find_book_dir(config)
  render = function(input_file, output_format, envir, quiet, 
    encoding, ...) {
    if (is.null(input_file)) {
      in_dir(input, render_book_script(output_format, 
        envir, quiet))
    }
    else {
      render_book(input_file, output_format, envir = envir, 
        preview = TRUE)
    }
  }
  clean = function() {
    suppressMessages(clean_book(clean = FALSE))
  }
  list(name = name, output_dir = book_dir, render = render, 
    clean = clean)
}
```
Seems possible to pass it through thanks to unused `...`,  and then insure consistency between all rendering functions. 

It seems almost done as `render` element on the list above takes `encoding` arg but do not pass it to `render_book` - it is an unused arg.

```r
  render = function(input_file, output_format, envir, quiet, 
    encoding, ...) {
    if (is.null(input_file)) {
      in_dir(input, render_book_script(output_format, 
        envir, quiet))
    }
    else {
      render_book(input_file, output_format, envir = envir, 
        preview = TRUE)
    }
  }
```
 Is it planned for future version ?

**Comment by yihui** [comment]
This is intentional. The documentation: https://bookdown.org/yihui/bookdown/usage.html

> All R Markdown files must be encoded in UTF-8.

Having to think about the encoding all the time is painful, so I just made the decision to support UTF-8 only (like what Pandoc does).

**Comment by cderv** [comment]
Yes I agree with you, UTF-8 only is ok. And it is why I tried to do : render my Rmd book in UTF-8 only.
I followed the documentation, and all my files are in UTF-8.

However, because of the problem of the lack of `encoding` arg, `bookdown::render_book` dispatch by default on `rmarkdown::render` without giving any arg on encoding. It is why `rmarkdown::render` use default arg `encoding = getOption("encoding")`.

It is the problem, `getOption("encoding")` is not always equal to UTF-8. on my windows machine it is `native.enc`. So, if all my files are in `native.enc`, ok. But as they are all UTF-8, it is an issue.

So either I force by `options(encoding = "UTF-8")` but I think it is not a good idea, or I use encoding arg in the function to set manually to UTF-8. 

It is what I do with `bookdown::render_book` and `rmarkdown::render`, I set `encoding = "UTF-8"` manually. 

For the list `bookdown::bookdown_site`, `render` element dispatches on  

- `bookdown:::render_book_script` then `bookdown::render_book`, 
or
- `bookdown::render_book`

it is why I tweaked the function `bookdown::bookdown_site` to force UTF-8 encoding and bypass the default `getOption("encoding")`. Then, I put in my *index.Rmd*, `site: source("custom_site_generator.R")$value` in order for the Build Button to work. 

I am with your intention, but it is not flawless as always with encoding. Not sure what is the best option.

**Comment by yihui** [comment]
Oh yes, there seems to be an issue here. I'll take a look again later. Thanks!

**Comment by cderv** [comment]
I did not point it before but looking and trrying, I can say it is the same with `bookdown::serve_book`, it defines a function `rebuild` with default encoding option, so I cannot preview the book with my UTF-8 encoded Rmd, as my default encoding is `native.enc`.

**Comment by yihui** [comment]
I just passed `encoding = 'UTF-8'` to all `rmarkdown::render()` calls. Hopefully the problem is fixed now.
