### ISSUE TITLE
Quarto | indexing not properly pointing to correct pages

### ISSUE THREAD

**Issue by jkylearmstrong** [rstudio/bookdown#1411]
I understand this is perhaps not a bookdown issue however, I found [https://github.com/rstudio/bookdown/issues/1274#top](https://github.com/rstudio/bookdown/issues/1274#top) when I was looking for resources on how to address my Quarto book not properly indexing items. 

As in [https://github.com/rstudio/bookdown/issues/1274#top](https://github.com/rstudio/bookdown/issues/1274#top) I am indeed using the `krantz.cls`. The issue seems to be similar, but all the indexes are off by more than a few pages. 

The thread seems to indicate that an update was performed to `tinytex` but does Quarto run this in the same way? I suspect not. Does anyone understand how to implement a similar solution in Quarto?

**Comment by cderv** [comment]
Thanks for the report. Let's stay in Quarto as this is shared team working on Quarto and R Markdown ecosystem.
