### ISSUE TITLE
Shiny dependency

### ISSUE THREAD

**Issue by theowoo** [rstudio/bookdown#143]
Patch request: specify "shiny" dependency for the bookdown package

error:
```
* installing *source* package 'bookdown' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'shiny'
ERROR: lazy loading failed for package 'bookdown'
* removing 'C:/R/library/bookdown'
```

**Comment by yihui** [comment]
That is weird; shiny should be automatically installed unless you ran `R CMD INSTALL bookdown` instead of using the documented way to install bookdown: https://bookdown.org/yihui/bookdown/get-started.html
