### ISSUE TITLE
Image embeded in flextable lost in .docx output

### ISSUE THREAD

**Issue by jimewu** [rstudio/bookdown#1438]
I used the following yaml in my .Rmd file to output as .docx:

```
---
output:
    bookdown::word_document2:
        reference_docx: "conf_toolkit/template.docx"
        number_sections: TRUE
        global_numbering: TRUE
---
```

and under this yaml setting, the following code chunk that produce a flextable with an embeded image only generate a table with the image lost in the output .docx file:

```{r}
ft <- mtcars %>%
    flextable() %>%
    compose(
        part = "body",
        i = 1,
        j = 1,
        value = as_paragraph(
            as_image(
                src = "Steps.jpg",
                width = 1.2,
                height = 1.8
            )
        )
    )
    
ft
```

![Screenshot_20230920_091737](https://github.com/rstudio/bookdown/assets/7069687/827ac370-70c2-4a61-aa60-75eb923949d5)

However, I called the `ft` in VS Code and found that the image is there:

![Screenshot_20230920_091831](https://github.com/rstudio/bookdown/assets/7069687/e1d66225-9f45-42bf-b6bf-d81ce190b42e)

This issue is reproducible regardless of the image used. 

Thanks for your help.

**Comment by cderv** [comment]
This is what I am reading in `flextable::as_image()` doc: https://davidgohel.github.io/flextable/reference/as_image.html
In the [Note](https://davidgohel.github.io/flextable/reference/as_image.html#note) part:
> This chunk option **requires package officedown in a R Markdown context with Word output format**.

So it seems this is not compatible with `rmarkdown::word_document`, which `bookdown::word_document2` is based on. 

So you need to use **officedown** https://ardata-fr.github.io/officeverse/officedown-for-word.html

You can do it with bookdown feature like this 
`````yaml
output:
  bookdown::markdown_document2:
    base_format: officedown::rdocx_document
    reference_docx: "conf_toolkit/template.docx"
    number_sections: TRUE
    global_numbering: TRUE
`````

Though you should check how **officedown** is working, and how compatible it is with **bookdown** feature.

**Comment by jimewu** [comment]
Thanks for your reply and it worked for me. Actually, I was initially using `officedown`, and then I switched to `bookdown` because the `officedown` does not take content in the template.docx (*e.g.*, header and footer texts) to the output.docx. The yaml you described is so far the best one that meets my needs. Thanks for your support.
