### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by tleitch** [rstudio/bookdown#144]
Output from install:

Downloading GitHub repo rstudio/bookdown@master
Installing bookdown
Error: Malformed remote specification 'yihui/knitr'

**Comment by yihui** [comment]
Upgrade your R packages please, in particular, devtools.

**Comment by tleitch** [comment]
I'm already on 1.9.1

**Comment by tleitch** [comment]
Everything is up to date

**Comment by yihui** [comment]
1.9.1 is not the latest version: https://cran.rstudio.com/web/packages/devtools/
