### ISSUE TITLE
Equation in book is broken

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#1440]
https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations

![image](https://github.com/rstudio/bookdown/assets/6791940/0240d96d-4cd2-4072-aef9-98285de9546e)

**Comment by cderv** [comment]
Rebuilding for 1ffd96c seems to have fixed it

**Comment by yihui** [comment]
Hmm, that's interesting. I have no idea why it was broken, and no idea how it was fixed, either :)
