### ISSUE TITLE
IDE Knit not publishing to Bookdown

### ISSUE THREAD

**Issue by danielmcintosh1** [rstudio/bookdown#145]
I am able to create a local set of .Rmd files, knit them and navigate them locally through the IDE previewer. When I publish to bookdown, bookdown is listing the file as a document, does not have the navigation pane on the left hand side, and a 404 error populates for files not on the index.
Any idea what might cause this?

![image](https://cloud.githubusercontent.com/assets/8877657/16470772/02984e70-3e0d-11e6-9346-cbecb61869ef.png)

![image](https://cloud.githubusercontent.com/assets/8877657/16470843/834dd7a6-3e0d-11e6-8c35-b95203e4cf49.png)

**Comment by danielmcintosh1** [comment]
I was able to reproduce the error locally. If I open the .html file in the folder created by the IDE, the document displays correctly.
If I copy the .html file to a new location, open the file, I get the poorly displayed output and the 404 error for the subsequent chapters.

**Comment by yihui** [comment]
Which version of RStudio are you using? Is this an RStudio project?

You may try `bookdown::publish_book()` from the R console (assuming your working directory is the book directory).

**Comment by danielmcintosh1** [comment]
Version 0.99.1246 – © 2009-2016 RStudio, Inc.
It is *not* an RStudio project.

**Comment by yihui** [comment]
For now you cannot publish books to bookdown.org using a publish button in RStudio. You have to run `bookdown::publish_book()` manually.
