### ISSUE TITLE
Hyphenation only works in English

### ISSUE THREAD

**Issue by piiskop** [rstudio/bookdown#1451]
I use RStudio Server and when I create a _bookdown_ project it can only hyphenate in English in PDF output. If I set the language to be something else like Estonian then there is no hyphenation at all. The same code in _TexStudio_ makes hyphenation in Estonian work.

So in _index.Rmd_, I have:

`lang: et`

In _preamble.tex_, I have:

`\babelprovide[main,import]{Estonian}`

Inside somewhere I have the text:

`lepingu kehtivuse ajal ja pärast lepingu lõppemist hoidma konfidentsiaalsena ja ilma Tööandja kirjaliku nõusolekuta mitte avaldama kolmandatele isikutele asutusesiseseks kasutamiseks mõeldud teavet sellele kehtestatud juurdepääsupiirangu tähtaja jooksul või muude andmete hulka, millele juurdepääs või mille kasutamine on mistahes õigusaktiga piiratud.`

If I build "bookdown::pdf_book" then the result is that the given text is not hyphenated. If I change "lang" to "en" then the text English text will be hyphenated according to English rules.

`> xfun::session_info('bookdown')`

> R version 4.3.2 (2023-10-31)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 22.04.3 LTS, RStudio 2023.3.3.539
> 
> Locale:
>   LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
>   LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
>   LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> Package version:
>   base64enc_0.1.3   bookdown_0.35     bslib_0.6.1       cachem_1.0.8      cli_3.6.2         digest_0.6.33     ellipsis_0.3.2   
>   evaluate_0.23     fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3          glue_1.6.2        graphics_4.3.2    grDevices_4.3.2  
>   highr_0.10        htmltools_0.5.7   jquerylib_0.1.4   jsonlite_1.8.8    knitr_1.45        lifecycle_1.0.4   magrittr_2.0.3   
>   memoise_2.0.1     methods_4.3.2     mime_0.12         R6_2.5.1          rappdirs_0.3.3    rlang_1.1.2       rmarkdown_2.25   
>   sass_0.4.8        stats_4.3.2       stringi_1.8.3     stringr_1.5.1     tinytex_0.49      tools_4.3.2       utils_4.3.2      
>   vctrs_0.6.5       xfun_0.41         yaml_2.3.8

**Comment by cderv** [comment]
Can you try with `rmarkdown::pdf_document()` directly (so single document and not a book project)  ? 

And share a full reproducible example so that I can have a look. 

Hyphenation is not a **bookdown** feature or R Markdown feature; It is from latex language support. As Pandoc is creating the LaTeX and handling the `lang` value, there could be some configuration you are not expecting. 

* https://pandoc.org/MANUAL.html#language-variables

> This affects most formats, and controls hyphenation in PDF output when using LaTeX (through [babel](https://ctan.org/pkg/babel) and [polyglossia](https://ctan.org/pkg/polyglossia))

You can add `keep_tex: true` in YAML under the format to have access to the `.tex` produced if not already, and see what are the LaTeX tools used. 

Thanks

**Comment by piiskop** [comment]
`> rmarkdown::pdf_document()`

> $knitr
> $knitr$opts_knit
> NULL
> 
> $knitr$opts_chunk
> $knitr$opts_chunk$dev
> [1] "pdf"
> 
> $knitr$opts_chunk$fig.width
> [1] 6.5
> 
> $knitr$opts_chunk$fig.height
> [1] 4.5
> 
> $knitr$opts_chunk$dev.args
> $knitr$opts_chunk$dev.args$pdf
> $knitr$opts_chunk$dev.args$pdf$useDingbats
> [1] FALSE
> 
> 
> 
> 
> $knitr$knit_hooks
> NULL
> 
> $knitr$opts_hooks
> NULL
> 
> $knitr$opts_template
> NULL
> 
> 
> $pandoc
> $pandoc$to
> [1] "latex"
> 
> $pandoc$from
> [1] "markdown+autolink_bare_uris+tex_math_single_backslash"
> 
> $pandoc$args
> [1] "--embed-resources" "--standalone"      "--highlight-style" "tango"             "--pdf-engine"      "pdflatex"          "--variable"       
> [8] "graphics"         
> 
> $pandoc$keep_tex
> [1] FALSE
> 
> $pandoc$latex_engine
> [1] "pdflatex"
> 
> $pandoc$ext
> NULL
> 
> $pandoc$convert_fun
> NULL
> 
> $pandoc$lua_filters
> [1] "/usr/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua" "/usr/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua"
> 
> 
> $keep_md
> [1] FALSE
> 
> $clean_supporting
> [1] TRUE
> 
> $df_print
> [1] "default"
> 
> $pre_knit
> NULL
> 
> $post_knit
> NULL
> 
> $pre_processor
> function (metadata, input_file, runtime, knit_meta, files_dir, 
>     output_dir) 
> {
>     saved_files_dir <<- files_dir
>     pdf_pre_processor(metadata, input_file, runtime, knit_meta, 
>         files_dir, output_dir)
> }
> <bytecode: 0x55d2329e5548>
> <environment: 0x55d2329e7d60>
> 
> $intermediates_generator
> function (...) 
> {
>     general_intermediates_generator(saved_files_dir, ...)
> }
> <bytecode: 0x55d2329e4f28>
> <environment: 0x55d2329e7d60>
> 
> $post_processor
> NULL
> 
> $file_scope
> NULL
> 
> $on_exit
> NULL
> 
> attr(,"class")
> [1] "rmarkdown_output_format"

I detected that the same TEX-file produced by "bookdown" gives a different PDF-file in _TeXstudio_ - a correct one with hyphenation. As TEX-file generation seems to not cause the problem, I used _pdflatex_ in my server machine and in my desktop machine. The server machine generated a PDF-file that has no hyphenation and the desktop machine generated a PDF-file that has hyphenation.

In the server machine:

`pdflatex --version`

> pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)
> kpathsea version 6.3.4/dev
> Copyright 2021 Han The Thanh (pdfTeX) et al.
> There is NO warranty.  Redistribution of this software is
> covered by the terms of both the pdfTeX copyright and
> the Lesser GNU General Public License.
> For more information about these matters, see the file
> named COPYING and the pdfTeX source.
> Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
> Compiled with libpng 1.6.37; using libpng 1.6.37
> Compiled with zlib 1.2.11; using zlib 1.2.11
> Compiled with xpdf version 4.03

In the desktop machine:

`pdflatex --version`

> pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)
> kpathsea version 6.3.4
> Copyright 2022 Han The Thanh (pdfTeX) et al.
> There is NO warranty.  Redistribution of this software is
> covered by the terms of both the pdfTeX copyright and
> the Lesser GNU General Public License.
> For more information about these matters, see the file
> named COPYING and the pdfTeX source.
> Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
> Compiled with libpng 1.6.37; using libpng 1.6.37
> Compiled with zlib 1.2.11; using zlib 1.2.11
> Compiled with xpdf version 4.03

The only difference is the minor-minor version and it makes such a huge difference.

The full code of the _bookdown_ project:

`repo: https://github.com/piiskop/erialapraktika`

**Comment by cderv** [comment]
> I detected that the same TEX-file produced by "bookdown" gives a different PDF-file in TeXstudio - a correct one with hyphenation. As TEX-file generation seems to not cause the problem, I used pdflatex in my server machine and in my desktop machine. The server machine generated a PDF-file that has no hyphenation and the desktop machine generated a PDF-file that has hyphenation.

I understand you are saying that without **bookdown** or R being involved you get a difference using two different `pdflatex` version. Is that right ? 

One thing that could lead to big difference could be the package version. You could also check that both your environment are using the same version of the tools - especially those involved in hyphenation.

**Comment by piiskop** [comment]
`output: pdf_document` gives the same result - no hyphenation in Estonian.

Yes, without _bookdown_ or R being involved, I get a difference using two different _pdflatex_ versions.

I have the newest version on both machines which is possible. The server machine with RStudio Server is running with _Ubuntu 22.04 LTS_ and the desktop machine is running with _Ubuntu 23.10_.

**Comment by cderv** [comment]
> Yes, without bookdown or R being involved, I get a difference using two different pdflatex versions.

This is a bummer - I am not sure what we could do. If you find what changes in the tooling and there is some TeX adjustment to make in preamble included for example, we'll be happy to look at it 

> I have the newest version on both machines which is possible. The server machine with RStudio Server is running with Ubuntu 22.04 LTS and the desktop machine is running with Ubuntu 23.10.

I would really check the packages versions between both your environment 

Maybe by comparing output of `tlmgr info --list --only-installed --json` or just doing an update of everything on both environment to be at the same updated version. 

Hopefully you'll find the issue.

**Comment by piiskop** [comment]
In both machines:

`tlmgr info --list --only-installed --json `

> (running on Debian, switching to user mode!)
> (see /usr/share/doc/texlive-base/README.tlmgr-on-Debian.md)
> TLPDB: not a directory, not loading: /home/kalmer/texmf
> tlmgr: user mode not initialized, please read the documentation!

**Comment by cderv** [comment]
Your installation is different than what I am used to. I am using TinyTeX FWIW (https://yihui.org/tinytex/) 

You are probably using the system TeX Live 

So you can read `tlmgr` manual to understand how to export version of your installed package , or you can also install TinyTeX distribution that is portable and would be the same on both your environment. 

Overall, I don't think this is an issue with **bookdown**, R Markdown ecosystem or even R. This is related to how TeX Live works and has potentially changed. 

You can also read the documentation of `babel` or `polyglossia` to understand how it should be configured, or maybe which CTAN package with hyphenation you need could be missing 

Hope it helps

**Comment by norbusan** [comment]
@piiskop have you installed the respective Debian TeX Live packages for your language? That would be one of the `texlive-lang-XXXX`.
I can only imagine that the hyphenation pattern is not available because well, it wasn't installed.

Can you only create the LaTeX file and run pdflatex manually on it, and send the output? That would make it much easier to debug.

**Comment by u-fischer** [comment]
> The only difference is the minor-minor version and it makes such a huge difference.

It means that you are using two different tex systems which is a *huge* difference as tex systems can contain more or less packages.  

Compile this `test.tex` document with `pdflatex test` on both machines and then compare (or show) the log-files:

~~~~
\documentclass{article}
\usepackage{babel}
\babelprovide[main,import]{Estonian}
\begin{document}
lepingu kehtivuse ajal ja pärast lepingu lõppemist hoidma konfidentsiaalsena ja ilma Tööandja kirjaliku nõusolekuta mitte avaldama kolmandatele isikutele asutusesiseseks kasutamiseks mõeldud teavet sellele kehtestatud juurdepääsupiirangu tähtaja jooksul või muude andmete hulka, millele juurdepääs või mille kasutamine on mistahes õigusaktiga piiratud.
\end{document}
~~~~

If the language support is available the log should say something like this

~~~~
(c:/texlive/2022/texmf-dist/tex/generic/babel/locale/et/babel-estonian.tex)
Package babel Info: Importing data for Estonian
(babel)             from babel-et.ini. Reported on input line 119.
Package babel Info: Hyphen rules for 'Estonian' set to \l@estonian
(babel)             (\language24). Reported on input line 119.
~~~~

**Comment by piiskop** [comment]
It turns out that the cause for the difference was not the version difference of _pdflatex_. I followed the suggestion of @norbusan which was not straightforward at first as there is no replacement like `estonian` or `et_EE` for `XXXX`.

Before following the suggestion of @norbusan , I gave a try what @u-fischer suggested.

Here is the result on my desktop machine:

`pdflatex u-fischer.tex 

> `This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> (./u-fischer.tex
> LaTeX2e <2021-11-15> patch level 1
> L3 programming layer <2022-04-10>
> (/usr/local/texlive/2022/texmf-dist/tex/latex/base/article.cls
> Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
> (/usr/local/texlive/2022/texmf-dist/tex/latex/base/size10.clo))
> (/usr/local/texlive/2022/texmf-dist/tex/generic/babel/babel.sty
> (/usr/local/texlive/2022/texmf-dist/tex/generic/babel/txtbabel.def)
> (/usr/local/texlive/2022/texmf-dist/tex/generic/babel/nil.ldf))
> (/usr/local/texlive/2022/texmf-dist/tex/generic/babel/locale/et/babel-estonian.
> tex)
> (/usr/local/texlive/2022/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
> No file u-fischer.aux.
> [1{/usr/local/texlive/2022/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
> (./u-fischer.aux) )</usr/local/texlive/2022/texmf-dist/fonts/type1/public/amsfo
> nts/cm/cmr10.pfb>
> Output written on u-fischer.pdf (1 page, 16351 bytes).
> Transcript written on u-fischer.log.
> 

I see that _babel-estonian.tex_ is listed but no message like importing is displayed. The PDF output has hyphenated text.

This is the result on my server machine:
`pdflatex u-fischer.tex `

> This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> (./u-fischer.tex
> LaTeX2e <2021-11-15> patch level 1
> L3 programming layer <2022-01-21>
> (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
> Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
> (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
> (/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
> (/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def)
> (/usr/share/texlive/texmf-dist/tex/generic/babel/nil.ldf))
> (/usr/share/texlive/texmf-dist/tex/generic/babel/locale/et/babel-estonian.tex)
> (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
> No file u-fischer.aux.
> 
> Overfull \hbox (19.61177pt too wide) in paragraph at lines 5--6
> \OT1/cmr/m/n/10 asutusesiseseks kasutamiseks m~oeldud teavet sellele kehtestatu
> d juurdep^^?a^^?asupiirangu
> 
> Overfull \hbox (4.63966pt too wide) in paragraph at lines 5--6
> \OT1/cmr/m/n/10 t^^?ahtaja jooksul v~oi muude andmete hulka, millele juurdep^^?
> a^^?as v~oi mille kasutamine
> [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./u-fischer.aux) )
> (see the transcript file for additional information)</usr/share/texlive/texmf-d
> ist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
> Output written on u-fischer.pdf (1 page, 16258 bytes).
> Transcript written on u-fischer.log.

Also _babel_estonian.tex_ is listed but there are _Overfull_-messages for the strings containing letters not available in Latin. The text in the PDF output was not hyphenated.

Then I came back to the suggestion of @norbusan and tried to figure out what package is available for Estonian:
`sudo apt install texlive-la`

I followed the command by pressing _T_. The list of available language packages:

> texlive-lang-all               texlive-lang-czechslovak       texlive-lang-greek             texlive-lang-polish            texlive-latex-extra
> texlive-lang-arabic            texlive-lang-english           texlive-lang-italian           texlive-lang-portuguese        texlive-latex-extra-doc
> texlive-lang-chinese           texlive-lang-european          texlive-lang-japanese          texlive-lang-spanish           texlive-latex-recommended
> texlive-lang-cjk               texlive-lang-french            texlive-lang-korean            texlive-latex-base             texlive-latex-recommended-doc
> texlive-lang-cyrillic          texlive-lang-german            texlive-lang-other             texlive-latex-base-doc       

It has no direct package for Estonian as it has for Greek or Polish. However, there are some packages that might contain useful things for Estonian. One of them is _texlive-lang-all_. I did not want to install that because obviously, it would have installed all the possible languages in our visible universe known to TeX. I used an Internet search engine to find out what is in _texlive-lang-other_ because as you might know: in the series _Lost_, there were these mysterious others. It turned out that it did not contain Estonian-others. Next, I used the same latter approach for _texlive-lang-european_ although that name if consistent with my previous experiences on computer languages, should not contain Estonian things neither because in early days, they counted Estonian to Baltic languages although Estonian is not a Baltic language. [Estonian is listed for that package](https://packages.debian.org/sid/texlive-lang-european). So I installed the package:

`sudo apt install texlive-lang-european `

> [sudo] password for kalmer: 
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following NEW packages will be installed:
>   texlive-lang-european
> 0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
> Need to get 15.8 MB of archives.
> After this operation, 25.6 MB of additional disk space will be used.
> Get:1 http://ee.archive.ubuntu.com/ubuntu jammy/universe amd64 texlive-lang-european all 2021.20220204-1 [15.8 MB]
> Fetched 15.8 MB in 3s (5,788 kB/s)                
> Selecting previously unselected package texlive-lang-european.
> (Reading database ... 390256 files and directories currently installed.)
> Preparing to unpack .../texlive-lang-european_2021.20220204-1_all.deb ...
> Unpacking texlive-lang-european (2021.20220204-1) ...
> Setting up texlive-lang-european (2021.20220204-1) ...
> Processing triggers for tex-common (6.17) ...
> Running mktexlsr. This may take some time... done.
> Running updmap-sys. This may take some time... done.
> Running mktexlsr /var/lib/texmf ... done.
> Building latex-based formats --byhyphen language.dat.
>         This may take some time... done.
> Building e-tex based formats --byhyphen language.def.
>         This may take some time... done.
> Scanning processes...                                                                                                                                            
> Scanning candidates...                                                                                                                                           
> Scanning processor microcode...                                                                                                                                  
> Scanning linux images...                                                                                                                                         
> 
> Running kernel seems to be up-to-date.
> 
> The processor microcode seems to be up-to-date.
> 
> Restarting services...
>  /etc/needrestart/restart.d/systemd-manager
>  systemctl restart cron.service php8.1-fpm.service postgresql@13-main.service ssh.service systemd-journald.service systemd-networkd.service systemd-resolved.service systemd-timesyncd.service
> Service restarts being deferred:
>  systemctl restart systemd-logind.service
>  systemctl restart user@1000.service
> 
> No containers need to be restarted.
> 
> No user sessions are running outdated binaries.
> 
> No VM guests are running outdated hypervisor (qemu) binaries on this host. 

Giving the same command to my desktop computer resulted with:

> [sudo] password for kalmer: 
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> texlive-lang-european is already the newest version (2023.20230613-2).
> texlive-lang-european set to manually installed.
> 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

This difference of results gave me hope that as the package was missing on my server machine, I can now compile PDF-files with hyphenated text in Estonian on my server machine:
`pdflatex u-fischer.tex `

> This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> (./u-fischer.tex
> LaTeX2e <2021-11-15> patch level 1
> L3 programming layer <2022-01-21>
> (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
> Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
> (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
> (/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
> (/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def)
> (/usr/share/texlive/texmf-dist/tex/generic/babel/nil.ldf))
> (/usr/share/texlive/texmf-dist/tex/generic/babel/locale/et/babel-estonian.tex)
> (/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
> (./u-fischer.aux) [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
> (./u-fischer.aux) )</usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/c
> m/cmr10.pfb>
> Output written on u-fischer.pdf (1 page, 16345 bytes).
> Transcript written on u-fischer.log.

There was no complaining about something being overfilled and the resulting PDF file contains hyphenated text in Estonian.

Also _bookdown_ compiles the PDF file with hyphenated text in Estonian now. Before that, the text was not hyphenated and although, I am forcefully using aligning on both edges, some lines were longer than the rest. I do not know why TeX produces such a crap if hyphenation is not in use, however this is another topic for another discussion.

I thank you TeX-guys for your quick replies and hints that brought me to a better-working environment!

It is still confusing though that if so many different people and organizations are involved in software development of software pieces that must work together, there is no easy and fast way to figure out solutions for special cases like my cases pretty often are. In this case: R and its packages, _RStudio Server_, _bookdown_, _knitr_, _pandoc_,_ _TeX_ and several packages of the latter one. Each of them has their own sometimes not full documentation and there is no sufficient integration documentation. This is why I write down [solutions for my own problems](http://manual-for-rstudio.ons.ee/).

**Comment by u-fischer** [comment]
> I see that _babel-estonian.tex_ is listed but no message like importing is displayed. The PDF output has hyphenated text.

you are looking only at the (shortened) terminal output. The log-*file*  contains much more informations.

**Comment by piiskop** [comment]
I agree.

**Comment by norbusan** [comment]
Hi @piiskop 

You write a lot and complain a lot to volunteers who agreed to help you and who spend countless hundreds of hours ...


> It has no direct package for Estonian as it has for Greek or Polish. However, there are some packages that might contain useful things for Estonian. One of them is _texlive-lang-all_. I did not want to install that because obviously, it would have installed all the possible languages in our visible universe known to TeX

It would have been a **very** good idea to install all those, if you don't know which you need.

> I used an Internet search engine to find out what is in _texlive-lang-other_ because as you might know: in the series _Lost_, there were these mysterious others. It turned out that it did not contain Estonian-others. Next, I used the same latter approach for _texlive-lang-european_ 

Yes, a simple search on packages.debian.org would have showed you that.

> although that name if consistent with my previous experiences on computer languages, should not contain Estonian things neither because in early days, they counted Estonian to Baltic languages although Estonian is not a Baltic language. [Estonian is listed for that package](https://packages.debian.org/sid/texlive-lang-european). 

I have studied about 15 languages, including Sanskrit. I know what **indo-european languages** are, but we called it `european`. Do you want to say the Estonia is not part of Europe? Nobody discussed here language families from a linguistic point of view.

> Also _bookdown_ compiles the PDF file with hyphenated text in Estonian now. Before that, the text was not hyphenated and although, I am forcefully using aligning on both edges, some lines were longer than the rest. I do not know why TeX produces such a crap if hyphenation is not in use, however this is another topic for another discussion.

The log file tells you this. TeX tries to do the best even in such bad circumstances.

You call things out as "crap" without understanding even the basic functionality.

Go forth and write a program that does block alignment without hypenation that behaves better. Show me what you can do! And if you can't, don't call out things as crap.

> It is still confusing though that if so many different people and organizations are involved in software development of software pieces that must work together, there is no easy and fast way to figure out solutions for special cases like my cases pretty often are.

Because they are different software programs. Many people use R/Rserver without EVER touching TeX. Many people use pandoc without EVER touching R, or TeX. Many people use TeX without ever having heard of R or pandoc.

Why do you assume just because **you** feel that is "the way", everyone else needs to do that, too?

> Each of them has their own sometimes not full documentation and there is no sufficient integration documentation. 

The problem was that you did NOT followed the advise we *always* give: Install ALL of TeX Live, and not do partial installs. If you do that, you need to know what might go wrong.

Enjoy.

**Comment by piiskop** [comment]
I have got my solution from two of you already however as you wanted to debate this topic further, I respond.

I am also a volunteer occasionally; once I volunteer, I do my job diligently. In software development, too many volunteers miss testing or documenting, or following a common style.

Estonian is not an Indo-European language. Estonia is part of Europe and its location has nothing to do with the languages spoken on that territory. Estonian is therefore still a language spoken in Europe however its inclusion in European languages is not in correlation with ISO. Estonian belongs to the Uralic languages. At the same time, Czech and Slovakian belong to Indo-European languages but they have a separate package. How is this not confusing and not worth complaining?

You wrote that TeX does its best. How is that doing the best if some lines are longer than other lines while aligning according to both edges and while these lines contain at least two words? I think that TeX can do better, not to mention do well. If the current behavior is the best one then I am pretty disappointed in TeX as it has been around for so long. Why are you using demagogy by telling me to write a program for aligning? _LibreOffice Writer_ has no issue with that and it has not been around so long. Writing TeX core is not my job. This is the job of Tex-core writers. I am a physics and chemistry teacher. If you want me to do something better in teaching then please tell me so. Something is crap if it is crap no matter whether I can do better or not. It is not my responsibility. I am responsible for my thoughts, words, and actions.

I do not assume that everyone has to integrate pieces of software. I do assume that since it is possible to integrate two pieces of software there must be comprehensive and easy-to-read documentation on that.

Is installing all of TeX Live rational? I mean it allegedly takes a lot of space and probably most of the functionalities would not be in use.

**Comment by u-fischer** [comment]
> How is that doing the best if some lines are longer than other lines while aligning according to both edges and while these lines contain at least two words?
LibreOffice Writer has no issue with that 

That TeX  doesn't do that by default has something to do with *quality* not with *inability*
TeX tries to avoid too large word spaces and prefers to complain if that is not possible. If you don't care about that you can tell it to be sloppy and allow it to stretch word spaces more. Simply add `\sloppy` to your document.

> Is installing all of TeX Live rational?
> probably most of the functionalities would not be in use.

Sure. But the same is true for all your software, including your OS and R and whatever. I didn't the full texlive because I thought I need all of it, but because I didn't want to waste my time thinking which parts I will need.   As long as I have the disk space it is only a few more dead bytes.

**Comment by piiskop** [comment]
`sloppy` really works well in that case. For comparison, I give you an example:

```
\documentclass[
12pt]{report}
\usepackage{unicode-math}
\setmainfont[]{DejaVu Serif}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
	\IfFileExists{parskip.sty}{%
		\usepackage{parskip}
	}{% else
		\setlength{\parindent}{0pt}
		\setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
	\KOMAoptions{parskip=half}}
\makeatother

\setlength{\columnsep}{32pt}

\usepackage{multicol}
\setlength{\columnseprule}{1pt}
\usepackage[none]{hyphenat}

\begin{document}
	\begin{multicols}{2}
Asusin 2021. a Tallinna Ülikooli õppima integreeritud loodusteadusi, et saada piisav sisuline ettevalmistus edasiseks pedagoogikaõppeks samal suunal. Kuna eesmärk on õpetaja kutsetunnistus, siis oli mõistlik teostada erialapraktika õpetamisena. Olin juba märtsis 2023 asunud juhendama loodusteaduste klubi ja samas koolis pakuti mulle füüsika ja keemia õpetamist septembrist. (ref:intro-KoFy) Vastasin otsingule ja leppisime kokku tähtajalise töölepingu. Kuna Kohila Gümnaasiumis oli mu õpetamise koormus kõige suurem, otsustasin sõlmida selle kooli suhtes erialapraktika lepingu.

Erialapraktika toimus vähemalt tunni ulatuses ajavahemikus 2023-08-22 kuni 2023-10-24, misjärel jätkus õpetamine kuni 2023-12-23.
\end{multicols}
\begin{multicols}{2}
	\sloppy
Asusin 2021. a Tallinna Ülikooli õppima integreeritud loodusteadusi, et saada piisav sisuline ettevalmistus edasiseks pedagoogikaõppeks samal suunal. Kuna eesmärk on õpetaja kutsetunnistus, siis oli mõistlik teostada erialapraktika õpetamisena. Olin juba märtsis 2023 asunud juhendama loodusteaduste klubi ja samas koolis pakuti mulle füüsika ja keemia õpetamist septembrist. (ref:intro-KoFy) Vastasin otsingule ja leppisime kokku tähtajalise töölepingu. Kuna Kohila Gümnaasiumis oli mu õpetamise koormus kõige suurem, otsustasin sõlmida selle kooli suhtes erialapraktika lepingu.

Erialapraktika toimus vähemalt tunni ulatuses ajavahemikus 2023-08-22 kuni 2023-10-24, misjärel jätkus õpetamine kuni 2023-12-23.
	
	\end{multicols}
\end{document}
```
