### ISSUE TITLE
Search in gitbook doesn't work because of empty search_index.json

### ISSUE THREAD

**Issue by UlvHare** [rstudio/bookdown#1454]
In my bookdown gitbook [site](https://ulvhare.gitlab.io/rmdnotes) the search function works only in current page, not in all document. Google says that one of the reason of such malfunction can be empty file `search_index.json`. And yes, you can see it: [my search_index.json](https://gitlab.com/UlvHare/rmdnotes/-/blob/master/public/search_index.json?ref_type=heads).

I tried recompile the project locally by `render_book()` and `serve_book()` and see local copy, no changes.

All R packages are up-to-date, Rstudio is the last stable version (12/2023).

```{R}
> xfun::session_info('bookdown')
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Gentoo Linux, RStudio 2023.12.0.369

Locale:
  LC_CTYPE=ru_RU.UTF-8       LC_NUMERIC=C               LC_TIME=ru_RU.UTF-8        LC_COLLATE=C              
  LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=ru_RU.UTF-8    LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

Package version:
  R6_2.5.1          base64enc_0.1.3   bookdown_0.37   bslib_0.6.1       cachem_1.0.8      cli_3.6.2        
  digest_0.6.34     ellipsis_0.3.2    evaluate_0.23     fastmap_1.1.1     fontawesome_0.5.2 fs_1.6.3         
  glue_1.7.0        grDevices_4.3.2   graphics_4.3.2    highr_0.10        htmltools_0.5.7   jquerylib_0.1.4  
  jsonlite_1.8.8    knitr_1.45        lifecycle_1.0.4   magrittr_2.0.3    memoise_2.0.1     methods_4.3.2    
  mime_0.12         rappdirs_0.3.3    rlang_1.1.3       rmarkdown_2.25    sass_0.4.8        stats_4.3.2      
  stringi_1.8.3     stringr_1.5.1     tinytex_0.49      tools_4.3.2       utils_4.3.2       vctrs_0.6.5      
  xfun_0.42         yaml_2.3.8   
```

**Comment by UlvHare** [comment]
I've found the solution from https://community.rstudio.com/t/problem-with-empty-search-index-json/17368/6. Just change the string 266 in [utils.R](https://github.com/rstudio/bookdown/blob/main/R/utils.R):
```r
 gsub('\\s{2,}', ' ', xfun::strip_html(x))
```
 by
```r
 gsub('\\s{2,}', ' ', xfun::strip_html(x), useBytes = TRUE)
```
I've done this in a local copy of bookdown sources, installed that and now it's OK!

Please implement this in the next release of Bookdown!

**Comment by yihui** [comment]
Thanks for the report! Instead of `useBytes = TRUE`, does `perl = TRUE` work? I'd prefer not using the former because R core doesn't recommend it: https://blog.r-project.org/2022/07/12/speedups-in-operations-with-regular-expressions/

**Comment by UlvHare** [comment]
I'll try

**Comment by UlvHare** [comment]
Yes, it works with `perl = TRUE`. Everything is OK!
