### ISSUE TITLE
Single document with html output on Windows doesn't show cross-refs and fig caption

### ISSUE THREAD

**Issue by benmarwick** [rstudio/bookdown#146]
I've also posted this on [SO](http://stackoverflow.com/questions/38156279/cross-referencing-in-a-single-file-bookdown-document) (is this cross-posting ok? I'm not sure). A [commentator on SO](http://stackoverflow.com/questions/38156279/cross-referencing-in-a-single-file-bookdown-document#comment63747205_38156279) confirmed the problem and suggested I report it here also. 

Here's a simple example Rmd:

    ---
    output: bookdown::html_document2
    ---

    Here's the cross-ref: \@ref(fig:cars-fig) 

    Here's the figure:

    ```{r cars-fig, fig.cap = 'Here is a plot about cars'}
    plot(cars)
    ```

Here's the output I get when I click on the knit button in RStudio, the cross-references are not quite working as expected:

![bzbsi](https://cloud.githubusercontent.com/assets/1262179/16549890/37ab4102-41e7-11e6-8919-15684d37d286.png)

How can I get the cross-referencing to show figure numbers and be a live link to the figure? And how can I get the caption to be formatted as expected?

Here's my session info:

```
devtools::session_info()
Session info -------------------------------------------------------
 setting  value                       
 version  R version 3.3.0 (2016-05-03)
 system   x86_64, mingw32             
 ui       RStudio (0.99.846)          
 language (EN)                        
 collate  English_Australia.1252      
 tz       Australia/Sydney            
 date     2016-07-02                  

Packages -----------------------------------------------------------
 package   * version date       source                           
 bookdown    0.0.74  2016-07-01 Github (rstudio/bookdown@8333bbb)
 devtools    1.12.0  2016-06-24 CRAN (R 3.3.1)                   
 digest      0.6.9   2016-01-08 CRAN (R 3.3.0)                   
 htmltools   0.3.5   2016-03-21 CRAN (R 3.2.4)                   
 httpuv      1.3.3   2015-08-04 CRAN (R 3.2.3)                   
 memoise     1.0.0   2016-01-29 CRAN (R 3.2.5)                   
 mime        0.4     2015-09-03 CRAN (R 3.2.2)                   
 miniUI      0.1.1   2016-01-15 CRAN (R 3.2.4)                   
 R6          2.1.2   2016-01-26 CRAN (R 3.2.5)                   
 Rcpp        0.12.5  2016-05-14 CRAN (R 3.3.0)                   
 rmarkdown   0.9.6   2016-05-01 CRAN (R 3.3.0)                   
 rsconnect   0.4.3   2016-05-02 CRAN (R 3.3.0)                   
 shiny       0.13.2  2016-03-28 CRAN (R 3.2.4)                   
 withr       1.0.2   2016-06-20 CRAN (R 3.3.0)                   
 xtable      1.8-2   2016-02-05 CRAN (R 3.2.5)                   
 yaml        2.1.13  2014-06-12 CRAN (R 3.2.2)  
```

**Comment by yihui** [comment]
This is a bug and I just fixed it in the dev version. Thanks for the report!

**Comment by benmarwick** [comment]
Yes, thanks so much. I've installed the latest version from github and it now works as expected, wonderful!
