### ISSUE TITLE
Katex introduces errors in footnotes

### ISSUE THREAD

**Issue by pbreheny** [rstudio/bookdown#1470]
I recently switched my book over to using [Katex](https://katex.org/) as the math engine by adding the following to `_output.yml`:

```yaml
bookdown::gitbook:
  math_method: r-katex
```

The math looks wonderful, everything renders correctly, but it screws up the footnotes -- all footnotes now appear on the last page, as in this issue: #793.

You can reproduce this in any book (so far as I can tell), but here's an explicit example:

```bash
git clone git@github.com:rstudio/bookdown-demo.git
```

then add `math_method: r-katex` as in the above.

**Comment by cderv** [comment]
Thanks for the report! I can reproduce. 

We are probably not handling something correctly when detecting footnote to move when `r-katex` is used.

**Comment by cderv** [comment]
I think our regex in 
https://github.com/rstudio/bookdown/blob/f244cf12bf2c2d7106ac6322b2b2a5796d4ef0c8/R/html.R#L1027-L1037

does not take into account the SVG content resulting from r-katex or something else 🤔

**Comment by cderv** [comment]
I think the issue that with KaTeX processing we get 
````html
<a href=\"#fnref2\" class=\"footnote-back\">&#x21A9;&#xFE0E;</a></p></li>
````
where without we get 
```html
<a href=\"#fnref2\" class=\"footnote-back\">↩︎</a></p></li>
```

Not the difference between single unicode chars and several HTML sequence characters. 

So `<a href="#fnref\\1"[^>]*?>\\X</a></p></li>` is not adapated here. Maybe using `\\X+` is enough, or we need something more tailored to what we want to match. 

@yihui hope it helps do the right thing. Thanks!

**Comment by yihui** [comment]
@cderv Thanks for the investigation!

@pbreheny It should be fixed now, but I don't have time to verify it. Please let us know if the problem persists. Thanks!

**Comment by pbreheny** [comment]
Works for me! :tada:
