### ISSUE TITLE
Repetitive 'row. names' after merge_taxa("Genus")

### ISSUE THREAD

**Issue by gg-miro** [rstudio/bookdown#1475]
i want add arrow in pcoa, but when running code:
rownames(tmp$otu_table) <- tmp$tax_table[rownames(tmp$otu_table), "Genus"]
##Error in `.rowNamesDF<-`(x, value = value) : no allow Repetitive 'row.names'
此外: Warning message:
non-unique values when setting 'row.names': ‘g__Bacillus’, ‘g__Clostridium’
then i check the value use:
any(duplicated(tmp$tax_table$Genus))
##TURE
There are indeed duplicate values, why haven't the horizontal taxes been fully merged.

**Comment by cderv** [comment]
Hi!

This does not seem like a **bookdown** issue, for which this issue tracker is about. 

Please ask on Stackoverflow: https://stackoverflow.com/questions/tagged/r or on https://forum.posit.co

THanks !
