### ISSUE TITLE
[FR] Line spacing customisable 

### ISSUE THREAD

**Issue by hayden-MB** [rstudio/bookdown#1477]
Hello! 

Bookdown using the GitBook style via BookML is used in our institution as an accessibility solution. This works well in allowing students to apply their own accommodations or just preferences to the course notes without having to contact the course organiser. However, this menu does not allow the user to change the line spacing. 1.5 or 2 line spacing is a common accommodation for students, and as such it would a useful addition to this menu.

> *What I would want to happen*: that the user can edit the line spacing without outside help
> *Exactly what I would want*: an addition to the 'A' menu on the gitbook style which allows line spacing to be chosen. 

Thank you!!

**Comment by yihui** [comment]
This shouldn't be hard if one knows JavaScript and a little CSS (line spacing is controlled by the CSS property `line-height`), but I don't have time for this task. The place to implement this feature is https://github.com/rstudio/bookdown/blob/main/inst/resources/gitbook/js/plugin-fontsettings.js We will welcome a pull request. Thanks!

**Comment by hayden-MB** [comment]
I will look into doing that. 
Pardon my ignorance, but is there a simple way of checking changes? i.e. viewing an example document locally before pushing.

**Comment by hayden-MB** [comment]
I have written code which I hope would do the job, but without a way of checking I wouldn't want to push. Any advice is appreciated.
