### ISSUE TITLE
Custom cover image

### ISSUE THREAD

**Issue by rdpeng** [rstudio/bookdown#148]
First I appreciate having my book on the bookdown.org site. Thanks! But I'm trying to get a custom cover image to show up (as well as the description). I have the cover-image:, url:, and description: meta data set in my [index.Rmd](https://raw.githubusercontent.com/rdpeng/rprogdatascience/bookdown/index.Rmd) file but for some reason I can't get it to show up after rendering the book. I'm not sure if this is a bookdown package issue or a web site rendering issue, but it's difficult for me to tell.

**Comment by jjallaire** [comment]
It might be that the website needs to be re-rendered manually (we were
thinking of moving it to hourly automatic regeneration but I'm not sure if
that's in place yet). @yihui am I correct that we need to manually
regenerate to get covers to show up?

**Comment by yihui** [comment]
That is correct. I just regenerated the homepage, and the cover image is there now.
