### ISSUE TITLE
bookdown.org is down?

### ISSUE THREAD

**Issue by ndphillips** [rstudio/bookdown#1484]
https://bookdown.org/ appears to be down. Can we inform the people who should know?
Apologies if this issue does not belong here, happy to move elsewhere

<img width="555" alt="Image" src="https://github.com/user-attachments/assets/d4021b73-fef4-4b61-94b9-6c2d4146cb3a" />

**Comment by cderv** [comment]
Thanks for the report. We are investigating. https://bookdown.org free service is becoming harder to maintain unfortunately... 

I'll update here when this is fixed

**Comment by cderv** [comment]
It is now up again. Thanks

**Comment by ndphillips** [comment]
Thanks for fixing so quickly @cderv ! I'm curious, what' making https://bookdown.org harder to maintain? Is it still officially supported by Posit? Do we have reason to believe it will go down frequently in the future? If so, what mitigations or alternatives are there?

The reason I ask is that I know many people that rely on bookdown.org (myself included). If bookdown.org won't be reliably maintained, I want to explore options.

**Comment by cderv** [comment]
> I'm curious, what' making [bookdown.org](https://bookdown.org/) harder to maintain? Is it still officially supported by Posit? Do we have reason to believe it will go down frequently in the future? If so, what mitigations or alternatives are there?

It is a matter of evolving offers in the ecosystem, and engineering / maintenance ressources available for this free service build years ago.

bookdown.org is only meant for publishing **bookdown** project. For other type of content, there are now other solutions like usual Github Pages or Netlify environment with their free tier, quarto.pub for quarto content, new [posit connect cloud](https://posit.co/blog/introducing-posit-connect-cloud/) now in beta. And probably more.  

**bookdown.org** works well for what it has been designed for (publish bookdown books), but does not have the same SLA that other solutions, and same engineering resources for its evolution regarding usage - That is what I meant. 

> The reason I ask is that I know many people that rely on bookdown.org (myself included). If bookdown.org won't be reliably maintained, I want to explore options.

It will still be reliably maintained - we solved the problem quickly and we'll continue to do so. So if you rely on it to share you **bookdown** project, that is great and you can continue. For Quarto project, quarto.pub should be prefered. Rpubs is still valid for R Markdown documents. Ultimately, https://connect.posit.cloud/ could be the new place for all type of content when beta is successful. 

Hope it answered your questions.

**Comment by ndphillips** [comment]
Thank you @cderv , I'll follow your advice and continue using bookdown for now. I look forward to when connect.posit.cloud is the source of truth across Quarto and RMarkdown!
