### ISSUE TITLE
Create index entries

### ISSUE THREAD

**Issue by peircej** [rstudio/bookdown#149]
For writing a book I need to be able to insert index entries for a general index at back of the book. This isn't a cross-reference as such: a particular index entry might come up multiple times (on different pages) e.g. one being the main reference that handles that thing and another that simply discusses it in-passing. The locations that the indeices refer to don't need to be titles, figures etc, merely a location in the text.

Other issues are that an index should support sub-entries like:
```
Stimuli, *24*, 38
  updating, 26
  drawing, 25
```

This is the way that sphinx supports such a thing: 
  http://www.sphinx-doc.org/en/stable/markup/misc.html#directive-index

I can't see this currently in markdown/bookdown. I guess we could use the LaTeX makeidx package but then we'd need to hack our own compile script?

cheers
Jon

**Comment by yihui** [comment]
If you only want this to work for LaTeX/PDF output, you can simply use the `\index{}` command, and pandoc will preserve it when converting markdown to LaTeX, and ignores it when the output is not LaTeX.

**Comment by peircej** [comment]
Update: Using the standard LaTeX `\index{}` commands is working fine for me and adding
```
 - \usepackage{makeidx}
 - \makeindex
```
to the `header-includes:` section of the document was obviously easy. The wrinkle that took me a while to get correct was that I needed to break out of the RStudio `knitr pdf` button and create my own shell script for the build because I needed a call to `makeindex` there.

For others' info I ended up with the following build script (I use a source folder and a 'tex' folder for the build files which is why the various cd options):

```
basename=NameOfMyDocNoExtension

# make the first copy of the latex document using knitr from R
cd source
echo R -e "options(knitr.package.progress=FALSE); rmarkdown::render('"$basename".Rmd')"
R -e "options(knitr.package.progress=FALSE); rmarkdown::render('"$basename".Rmd')"
cd ..

#copy in the bibtex references and need to compile in that dir
rm -R tex #start with clean directory
mkdir tex
cd tex
cp "../source/"$basename".tex" .
cp ../references.bib .
cp ../index_style.ist .
cp -R ../source/images .

echo converting latex to pdf
# make latexpdf
# must run pdflatex twice before makeindex and twice after bibtex
echo pdflatex pass 1
pdflatex $basename
echo bibtex
bibtex $basename
echo pdflatex pass 2
pdflatex $basename > /dev/null 2>&1 #silent
makeindex -s index_style.ist $basename".idx"
echo pdflatex pass 3
pdflatex $basename > /dev/null 2>&1 #silent
echo pdflatex pass 4
pdflatex $basename > /dev/null 2>&1 #silent

# move the pdf file to the buld rather than build/latex
mv *.pdf ..
cd ../..
```

**Comment by yihui** [comment]
It should not be that complicated. If you have installed latexmk, you are all set, otherwise rmarkdown will simply do what you did: https://github.com/rstudio/rmarkdown/blob/f43f59ec/R/util.R#L306-L356 All you need is `\usepackage{makeidx} \makeindex` in the preamble, and `\printindex{}` at the end of your book.

**Comment by yihui** [comment]
Documented at https://bookdown.org/yihui/bookdown/latex-index.html
