### ISSUE TITLE
html_dependency problem

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#15]
```R
bookdown::render_book("index.rmd")
#> Error: path for html_dependency not found: /tmp/RtmpO4fv0m/widgetbindingcb3263a9aa9f 

traceback()
#> 10: stop("path for html_dependency not found: ", list$src$file, call. = FALSE) at html_dependencies.R#141
#> 9: FUN(X[[i]], ...) at html_dependencies.R#128
#> 8: lapply(dependencies, validate_html_dependency) at html_dependencies.R#93
#> 7: dependency_resolver(all_dependencies) at html_extras.R#13
#> 6: html_extras_for_document(knit_meta, runtime, dependency_resolver, 
#>   format_deps) at html_document_base.R#92
#> 5: base(...) at output_format.R#81
#> 4: output_format$pre_processor(yaml_front_matter, utf8_input, runtime, 
#>   knit_meta, files_dir, output_dir) at render.R#387
#> 3: rmarkdown::render(main, output_format, ..., clean = clean, envir = envir, 
#>   run_pandoc = TRUE, knit_meta = knit_meta) at render.R#129
#> 2: render_new_session(files, main, force_knit, output_format, clean, 
#>   envir, ...) at render.R#86
#> 1: bookdown::render_book("index.rmd")
```

Any ideas?

**Comment by jjallaire** [comment]
@yihui will know for sure, but I think this might be an artifact of running
the knit of each chapter in it's own session (so temp directories disappear
after the chapter is knit).

**Comment by yihui** [comment]
Right. That is also a problem I wanted to solve with https://github.com/ramnathv/htmlwidgets/pull/183 so please merge it before the next release of htmlwidgets.

**Comment by jjallaire** [comment]
Okay, I will definitely merge that before the next release of htmlwidgets

**Comment by hadley** [comment]
For now, I'll just install htmlwidgets from that branch.  

@yihui do you know about the remotes field that devtools now supports? You can use it to specify that bookdown should install from specified github repos/branches/pull requests.

**Comment by hadley** [comment]
Ok - I installed from the branch, deleted all the caches I could find (including `_main.rds`) but I'm still getting the same error

**Comment by yihui** [comment]
Hmm, that is weird. Were you testing it on the r4ds book? Could you email me `_main.rds`?

**Comment by hadley** [comment]
Yeah - if you check out http://github.com/hadley/r4ds and then `bookdown::render_book("index.rmd")` you should be able to recreate the problem. I'll email you the rds.

**Comment by yihui** [comment]
Sorry I should have mentioned that both my htmlwidgets branch and the development version of htmltools are required. I just added `Remotes` in DESCRIPTION.

**Comment by hadley** [comment]
Ah got it - thanks!

**Comment by jjallaire** [comment]
You just need to change the output format within your individual Rmds to
bookdown::preview_chapter, that will make it the default behavior for the
"Knit" button.

**Comment by jjallaire** [comment]
Wrong thread, sorry

**Comment by dongzhuoer** [comment]
The problem emerge again when I first build the book under Windows and then build the book under Ubuntu. I fixed it by deleting the `_bookdown_files` dir. I think there is something wrong with cache verification. Though most people would probably not do the similar thing, it's would be nice if you can add some check.

**Comment by dongzhuoer** [comment]
I think the problem would also occur when someone install a new version of R, thus change the location of installed R packages. 

the error message is

```
Error: path for html_dependency not found: W:/program/lib/R/htmlwidgets/ww
```

wherein `W:/program/lib/R` is where I put my R packages on Windows. And I get the error when I want to rebuild the book on Ubuntu (with `new_session=T`)

**Comment by wesleyburr** [comment]
Not to bump something that may be considered solved, but this issue just happened to me using R Markdown knitting when I had rsync'd a directory of work from one machine to another. Had to delete the _cache and _files directories, then it worked fine. Wasn't a terribly informative error, but Google led me here, so it's all good. :)

**Comment by ldfreight** [comment]
just bumped into this problem as well

> packageVersion("rmdformats")
[1] '0.3.4'
> packageVersion("rmarkdown")
[1] '1.9'
> packageVersion("htmlwidgets")
[1] '0.9'

I have tried to delete the cache folder but it did not help

**Comment by dongzhuoer** [comment]
You need to provide minimal information for reproducing the problem if you want others to help you.

Create a GitHub repo might be a good idea. GitHub issue also support uploading files now.

**Comment by Robinlovelace** [comment]
Heads-up @yihui I'm sorry to say that this issue has raised its head with vengeance for me. The previous solution of removing the cache no longer fixes the issue I'm afraid...

Reproducible example:

```
git clone git@github.com:robinlovelace/geocompr
cd geocompr
make html
```

Generates this (when all geo dependencies are installed):

```
output file: references.knit.md

List of 10
 $ name      : chr "leaflet-providers"
 $ version   : chr "1.9.0"
 $ src       :List of 1
  ..$ file: chr "/tmp/RtmprIInyg"
 $ meta      : NULL
 $ script    : chr "leaflet-providers_1.9.0.js"
 $ stylesheet: NULL
 $ head      : NULL
 $ attachment: NULL
 $ package   : NULL
 $ all_files : logi FALSE
 - attr(*, "class")= chr "html_dependency"
Error: path for html_dependency not found: /tmp/RtmprIInyg
Execution halted
makefile:2: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by yihui** [comment]
@Robinlovelace Do you have a _minimal_ reproducible example? I'm afraid it will be difficult to debug the issue if the example is a whole book project...

**Comment by ldfreight** [comment]
Where is installed the package on your environment?

Xavier Faure-Miller

________________________________

**Comment by Robinlovelace** [comment]
Agreed. this is the basis of a minimal reproducible example:

```bash
git clone git@github.com:rstudio/bookdown-demo
bookdown-demo
Rscript -e 'bookdown::render_book("index.Rmd")'
```

Then replace the contents of `02-literature.Rmd` with this:

```
# Test leaflet

```{r}
remotes::install_github("rstudio/leaflet")
remotes::install_github("rstudio/bookdown")
remotes::install_github("nowosad/spData")
remotes::install_github("mtennekes/tmap")
```

```{r}
library(leaflet)
leaflet() %>% 
  addPolygons(data = spData::lnd)
```

```{r}
library(tmap)
tmap_mode("view")
tm_shape(spData::lnd) + tm_polygons()
```

```

**Comment by Robinlovelace** [comment]
Unfortunately that doesn't reproduce the issue, but is a step towards a minimal reproducible example I think, guess it's a clash between leaflet JS versions needed by different mapping packages. Any ideas @nowosad? Many thanks for quick replies by the way!

**Comment by Robinlovelace** [comment]
But I can reproduce the example in the book. It seems a file needed for `htmltools` cannot be found from the error message. Any further ideas on debugging this welcome, other than replacing chapters section-by-section... 

https://github.com/rstudio/rmarkdown/blob/master/R/html_dependencies.R#L234

**Comment by Robinlovelace** [comment]
Heads-up @yihui, I've found a reproducible example, BINGO! It's when you build the book with `new_session` enabled.

Please try the following 

```bash
git clone git@github.com:rstudio/bookdown-demo
bookdown-demo
Rscript -e 'bookdown::render_book("index.Rmd")'
```

and add this to `02-literature.Rmd`:

```{r}
library(leaflet)
popup = c("Robin", "Jakub", "Jannes")
leaflet() %>%
  addProviderTiles("NASAGIBS.ViirsEarthAtNight2012") %>%
  addMarkers(lng = c(-3, 23, 11),
             lat = c(52, 53, 49), 
             popup = popup)
```

That should reproduce it.

Then run:

```
Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", clean = FALSE, new_session = TRUE)'
```

So it builds the 'M-K' way: https://bookdown.org/yihui/bookdown/new-session.html

**Comment by yihui** [comment]
@Robinlovelace After some investigation, I'm afraid that `leaflet::addProviderTiles()` cannot work with the K-M method of **bookdown**. The reason is that **leaflet** writes the HTML dependency to the `tempdir()`, which will be deleted after the R session quits. In the `new_session: true` mode, each Rmd is knitted in a separate R session; when that session quits, its `tempdir()` is deleted. Then **rmarkdown** can no longer find the HTML dependency. Relevant code here:

https://github.com/rstudio/leaflet/blob/c19b0fb9c60d5caf5f6116c9e30dba3f27a5288a/R/plugin-providers.R#L92

If the leaflet authors can stabilize this HTML dependency (like other dependencies, of which the paths are R package paths instead of temp paths), your problem will go away.

**Comment by Robinlovelace** [comment]
Many thanks for the investigations @yihui. I did also try the M-K method and, for some unknown reason to my surprise, aslo got the same error message. I think your solution, to stabilize the HTML dependency, sounds reasonable. Any ideas how I would start exploring options for implementing that in code?

Many thanks again.

**Comment by yihui** [comment]
@Robinlovelace The minimal example above works fine with the M-K method. The PR you mentioned failed with a different reason: https://travis-ci.org/Robinlovelace/geocompr/builds/636229884

You have to talk to **leaflet** authors on stabilizing the path of the `leaflet-providers` dependency. I don't really know if this is possible, or why it uses a temp path (there must be a reason for this unusual treatment).

**Comment by Robinlovelace** [comment]
Thanks Yihui. The fail with the M-K method I mentioned happened on my local computer, not Travis. In any case it sounds like this is not a problem in **bookdown**. Worth me raising this issue here?: https://github.com/rstudio/leaflet/issues

**Comment by yihui** [comment]
@Robinlovelace I'm unable to reproduce the issue locally with the M-K method.

**Comment by andrewmaclachlan** [comment]
@Robinlovelace i was having a similar issue with leaflet in our GIS practical book, the M-K method wasn't working as well. Not sure what happened but looks like htmltools and htmlwidgets weren't loaded. Seems to have solved my issue.

**Comment by Robinlovelace** [comment]
Great, thanks for sharing @andrewmaclachlan

**Comment by mgei** [comment]
@andrewmaclachlan @Robinlovelace 
Sorry I don't understand your solution. How did you solve? I am having the same problem with leaflet + blogdown.

I already installed the latest leaflet version from Github and also loaded htmlwidgets and htmltools.

**Comment by andrewmaclachlan** [comment]
I actually now think it's an issue with caching. For all the code chunks that used leaflet i turned caching to FALSE and now the book builds locally using the M-K method. @Robinlovelace has essentially saved his maps and then loaded them again to avoid the issue, you can see his fix here: https://github.com/Robinlovelace/geocompr/pull/465/files

**Comment by mgei** [comment]
@andrewmaclachlan THanks indeed I had `opts_chunk$set(cache = T)` at the beginning of my Rmd.

Solution was to set false

```
knitr::opts_chunk$set(cache = F)
```

**Comment by BennyWag** [comment]
Hi @mgei @andrewmaclachlan  I am coming up with the same issue building a bookdown book of multiple .rmds, one of which contains mapview functions. I've set cache = F at the beginning of the respective .rmd, but am still getting the same error. I have also tried setting cache = F in each seperate .rmd, or merging all chunks together into one .rmd file, but am getting the same error each time. So far I could only build the book, when removing the respective mapview code. If I knit the same .rmd with rmarkdown as a html document, it does work with or without cache =  F ... Any suggestions?

**Comment by cderv** [comment]
Hi @BennyWag ! 
As this issue is pretty old and the discussion pretty long, I think it would be benificial to ask the question from start with your issue; 
Can you open a new issue with a detail example of your use case, or a question in RStudio Community so that it is easier to help ? 
You can link to this one for context. Thanks !

**Comment by BennyWag** [comment]
Hi @cderv, sure I will do that. Will need to get together a reproducible example first.

**Comment by andrewmaclachlan** [comment]
Hi @BennyWag 

Have you tried:

- clearing the cache 
- reinstalling the package with dependencies (sorry if that's a bit obvious). 

Otherwise put a reproducible example up and i'll help if i can.

**Comment by alexyshr** [comment]
In my case it works leaving knitr::opts_chunk$set(cache = TRUE), but knitting from outside Rstudio in a fresh session of Rgui.exe: rmarkdown::render("MRI_700.Rmd", "html_document").
