### ISSUE TITLE
Issues with customization (koma-script)

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/bookdown#151]
Based on [this](https://bookdown.org/yihui/bookdown/theming.html) I am trying to make the bookdown output more European by using `scrbook`. A minimal example looks like so:

    ---
    knit: "bookdown::render_book"
    documentclass: scrbook
    geometry: margin=0.75in, a4paper
    
    output:
      bookdown::pdf_book:
        template: null
        pandoc_args: --chapters
    header-includes:
      - \usepackage{booktabs}
      - \usepackage{fontenc}
    
    link-citations: true
    ---
    
    # Test
    Test, tester, the testest.

When kniting this from within RStudio I get (independent of the `pandoc_args` statement):

    ...
    processing file: _main.Rmd
    output file: _main.knit.md
    
    
    Latexmk, John Collins, 1 January 2015. Version 4.41
    ! Undefined control sequence.
    l.1 \chapter
                {Test}\label{test} 

What am I doing wrong?

**Comment by yihui** [comment]
There should be a `--standalone` argument, and I just added it, so your example should work with the current version now.
