### ISSUE TITLE
Theorem/Lemma/Definition Custom Blocks

### ISSUE THREAD

**Issue by coatless** [rstudio/bookdown#152]
I'm trying to provide a way to use theorems/lemmas/definitions.

The main way I see about going about this is via the [custom block declaration](https://bookdown.org/yihui/bookdown/custom-blocks.html):

To enable this feature I'm running into a roadblock of not being able to:

1. supply non-body content like a header (e.g. theorem name)
2. autoincrement/number 

For 1. it seems as if `caption = "Fermat's Last Theorem"` could be passed through to the block more options would be possible.

For 2., I'm pretty sure this isn't possible due to the restriction on the `\ref` tag.

**Comment by yihui** [comment]
I did think about this when I started this project, but I didn't come up with a simple solution. I'm preparing the CRAN release of bookdown right now, and I'll reconsider this feature in the next version. Basically there are two possible ways on my mind: 1) As you described, use custom blocks (the major drawback is that it is not easy to use all Markdown features in these blocks at the moment; #117); 2) Hack the definition list or example list http://pandoc.org/README.html#definition-lists using some sort of special tokens and restore them to thereoms/lemmas/whatever.

**Comment by yihui** [comment]
All these environments have been implemented. Please see the documentation at https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html

**Comment by coatless** [comment]
Praise be @yihui .

**Comment by endri81** [comment]
Environment theorem not working for me. When I compile pdf I get:
In get_engine(options$engine) :
  Unknown language engine 'theorem' (must be registered via knit_engines$set()).
and theorem show just the typed text with different font but not at all as in the example book

**Comment by coatless** [comment]
After a bit of configuration, the theorem environments do work.

Questions:

1. Do you have the latest `bookdown` version?  `devtools::install_github("rstudio/bookdown")`
2. Are you building under `bookdown::pdf_book`?
3. Did you define theorem environments?
https://github.com/SMAC-Group/TTS/blob/cb0e8f4f46857b88d11bd429d7be4bc3f2944e7c/preamble.tex#L54-L78

**Comment by endri81** [comment]
Thank you @coatless very much.
I made the changes now everything works fine
Best Regards

**Comment by yihui** [comment]
2 and 3 are not necessary. Theorems work for HTML/EPUB output as well. You can also leave the preamble empty, and bookdown will define the environments for you.

**Comment by coatless** [comment]
@yihui 

---

I agree that 2 is unnecessary. This was primarily to make sure that the document was not being knitted (if open in a non-bookdown rstudio project). This is a known issue that a few of my collaborators have run into.

---

On 3, I disagree. I'm not sure that `theorem` has been defined for the `pdf_book`.

Without defining the `theorem` and other environments in the `premable.tex`, I received:

> ! LaTeX Error: Environment theorem undefined.

I came to this realization after observing the example text, which explicitly loads `amsthm`:

https://github.com/rstudio/bookdown/blob/1254a81864c7d0e1d165eda58d9fb08fe3a9bc71/inst/examples/latex/preamble.tex#L92-L98

**Comment by yihui** [comment]
@coatless I'm loading amsthm explicitly only because I wanted to increase the vertical space above the theorems in the bookdown book, which uses the LaTeX class from Chapman & Hall and the spacing above theorems was too tight. This is only for cosmetic purposes. If your book cannot compile without defining the theorem environments, it is either a bookdown bug or there was something wrong in your book, and I'll need a reproducible example. I didn't define the theorem environments in the bookdown book, and it generates the PDF without any problems.

**Comment by stevepowell99** [comment]
Is there any way to get a list of definitions / theorems etc at the end of the book?

**Comment by yihui** [comment]
@stevepowell99 Possible, but not very straightforward. Theorems are not different with normal R code chunks, so chunk references will still work: http://yihui.name/knitr/demo/reference/ Basically `echo=FALSE` to hide a theorem, and `echo=TRUE` with the same label to show it later. I'm curious why that could be possibly helpful to readers, though. Personally I very much hate figures/tables being placed at the end of a paper (per requirement of some old-fashioned journals), and I also feel it is inconvenient when theorems are not where they are actually used.

**Comment by stevepowell99** [comment]
sorry, I just meant to place an index of definitions at the end, but to leave the actual definitions where they belong, in the text.

**Comment by yihui** [comment]
@stevepowell99 If you mean a LaTeX index, please see the section `Index` in the docs: https://bookdown.org/yihui/bookdown/ If you mean something else, I think it will be better to explain it with an example.

**Comment by stevepowell99** [comment]
V sorry if I wasn't clear. The short version is this: presumably bookdown, by the end of the book, knows all the definition labels which have been created in the text? So one could just loop / lapply through them and print them all out, aka Index of Definitions. So the user can look to see, aha, where is "bar2" defined, here it is in the Index of Definitions, let's click on it to get to the definition of bar2 in the text.

Long version:
I just meant something like this, (in markdown, not latex)
in text:



```{definition, bar1, echo=T}
A bar1 is defined as a foo.
```
...


```{definition, bar2, echo=T}
A bar2 is similarly defined as a foobar.
```
and then, presumably at the end, I can already do this...

##Index of definitions
\@ref(def:bar1)
\@ref(def:bar2)

... but I have to know all the labels I created in the text and I have to type them. If bookdown knows about all the definition labels I have created, it could make such an index automatically.

**Comment by yihui** [comment]
@stevepowell99 By the end of the book, you can obtain all labels of definitions via `knitr::all_labels(engine == 'definition')`. You can certainly create cross-references automatically, but the problem is you only have the labels, so readers can only see definition numbers like X.Y, and there are no names/terms for the definitions. This issue is not impossible to solve. You may post a question on StackOverflow and I may answer it there, since I think other users may benefit from it, too.

**Comment by yihui** [comment]
@stevepowell99 FYI: finally found some time to type an answer on SO http://stackoverflow.com/q/40735727/559676

**Comment by stevepowell99** [comment]
Is there any way to change the names `Lemma`, `Theorem` etc which are actually printed at the start of each block, e.g. for another language?

**Comment by yihui** [comment]
@stevepowell99 https://bookdown.org/yihui/bookdown/internationalization.html

**Comment by stevepowell99** [comment]
thanks - now I can't see how to translate the token `(PART)` - is this not possible?

**Comment by yihui** [comment]
@stevepowell99 No. For HTML output, you only get part numbers like I, II, III, IV, ... For LaTeX output, you have to figure it out by yourself how to change the PART name (may be something like `\partname`).

**Comment by endri81** [comment]
For LateX output you have to put the code below before the chapter which begins your part:

# (PART) Name of part {-} 

For example if you have book organized:

Part 1

Chapter 1

Chapter 2

...

Part 2

Chapter 1

Chapter 2

...

So you begin Chapter 1 in Part 1 with 

# (PART) Name of part 1 {-}


and  Chapter 1 in Part 2 with 

# (PART) Name of part 2 {-}

Like this you get the organization you want

**Comment by stevepowell99** [comment]
Thanks @endri81 - I don't have chapter numbering so had left off the {-}, and that led to me seeing PART actually printed before the header, which I didn't want, which is why I wanted the translation ... In short: _when writing `(PART)`, leave the `{-}` in place, as instructed in the docs, even if you aren't using chapter numbering._

**Comment by fyemath** [comment]
> @stevepowell99 https://bookdown.org/yihui/bookdown/internationalization.html

In latex
`\begin{proof}[Sketch of proof]` will be printed as 

> _Sketch of proof._

In bookdown, it prints at 

> _Proof._(Sketch of proof) 

Is it possible the temporarily change the printed name of the proof environment?
