### ISSUE TITLE
Equations not numbered with html_document2

### ISSUE THREAD

**Issue by alanarnholt** [rstudio/bookdown#153]
When I try to use the single document mode - bookdown::html_document2 - I can label Figures and Tables but equations are not being numbered. Is this a known issue?

**Comment by yihui** [comment]
MathJax needs configuration. Here is a minimal example:

    ---
    title: "Math Equations"
    author: "John Smith"
    output: bookdown::html_document2
    ---
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      TeX: { equationNumbers: { autoNumber: "AMS" } }
    });
    </script>
    
    # Introduction
    
    \begin{equation}
    f\left(k\right)=\binom{n}{k}p^k\left(1-p\right)^{n-k} \label{eq:binom}
    \end{equation}
    
    See Equation \@ref(eq:binom).

**Comment by alanarnholt** [comment]
Thanks.  Very nice.
