### ISSUE TITLE
gitbook templating available?

### ISSUE THREAD

**Issue by safferli** [rstudio/bookdown#155]
Hi all, I was trying to use gitbook templating (http://toolchain.gitbook.com/templating/), which doesn't seem to be implemented(?). Are there plans to do this? Do I see this correctly that bookdown gitbook "only" applies the gitbook theme to the bookdown output, and doesn't "do" a full gitbook?

**Comment by yihui** [comment]
bookdown uses Pandoc, and gitbook's Markdown rendering engine is completely replaced by R + Pandoc: https://bookdown.org/yihui/bookdown/templates.html

**Comment by safferli** [comment]
I'm looking for a way to centrally set parameters (which works for R: http://rmarkdown.rstudio.com/developer_parameterized_reports.html), but specifically for the markdown part. 

So if I define a variable `param.colour = colour`, I could write `param.colour` in my markdown document, and it would output "colour" in the target output HTML. This way, I can centrally change the parameter to "color" if I send the file to an American. Is this possible?

**Comment by yihui** [comment]
Yes, just use `` `r params$colour` `` in the Rmd source document.

**Comment by safferli** [comment]
Ah, of course... silly me, my brain somehow tried to convince me that this would output it as a code block -- d'oh! 

Thanks a lot, it's a workaround for the sorely missed ease of `\newcommand{}` in LaTeX. Now I just need my `\xspace` back! :p
