### ISSUE TITLE
some links display incorrectly

### ISSUE THREAD

**Issue by etiennebr** [rstudio/bookdown#156]
While reading r4ds I realized that some links seem not to display correctly in bookdown html rendering. 

For instance comparing `([@hadleywickham](https://twitter.com/hadleywickham))` in r4ds http://r4ds.had.co.nz/introduction.html and in https://github.com/hadley/r4ds/blob/master/intro.Rmd. The github version seem to display in the intended way ([@hadleywickham](https://twitter.com/hadleywickham)), while the bookdown rendering displays ` ([@hadleywickham](https://twitter.com/hadleywickham)) `. I don't think I can link to specific line number here, but searching for `@hadleywickham` will bring you straight to it.

I also noticed in the same page that one of the double brackets (`[[ ]]`) were displayed, but maybe that's an issue with the way they used brackets in r4ds. Search for `model assessment` in the same page to find it.

**Comment by yihui** [comment]
Pandoc probably thinks `@` is for a citation. It works if you escape `@`, e.g. `[\@hadleywickham](https://twitter.com/hadleywickham)`. You can submit a pull request to them to fix this issue.

A single pair of brackets is for cross-references of section headers. The extra pair is just a literal pair of brackets. It is probably just the authors' preference.
