### ISSUE TITLE
Automatically figure number when chunk name has underscore

### ISSUE THREAD

**Issue by byzheng** [rstudio/bookdown#157]
When chunk name has underscore (see minimum example below), bookdown cannot automatically generate the figure number, but show `(#fig:test_figure)test figure`.  Is this desired feature or a bug in bookdown or pandoc?

    ---
    output: bookdown::html_document2
    ---
    
    ```{r test_figure, echo=FALSE, fig.cap='test figure'}
    plot(pressure)
    ```

**Comment by yihui** [comment]
This restriction is imposed by bookdown: https://bookdown.org/yihui/bookdown/figures.html (See the block with the note sign)

**Comment by byzheng** [comment]
Thanks. Missed that section when reading your book
