### ISSUE TITLE
Output format for single documents?

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#16]
Is there an output document tailored for individual chapters? It's nice to be able to use the same cache and visual appearance while iterating on a single chapter.

**Comment by yihui** [comment]
I'm working on that today.

**Comment by hadley** [comment]
:tada:

**Comment by jjallaire** [comment]
@hadley If you just use this front matter in your chapters you now get a
nice fast preview!

    knit: bookdown::preview_chapter

**Comment by hadley** [comment]
Hmmm, when I add that and knit, I get:

```
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... create_placeholder -> grep -> readUTF8 -> readLines -> file
In addition: Warning message:
In file(con, "r") : cannot open file 'NA': No such file or directory
Execution halted
```

**Comment by yihui** [comment]
The only possibility that I can think of is that bookdown didn't find any input files (I just added an error message for that). Or perhaps something screwed up in _main.rds, and you may try clean_book() and rebuild the book. If it still does not work (with the latest Github version), please send me a copy of the rds file by email.
