### ISSUE TITLE
Custom Cover Issues

### ISSUE THREAD

**Issue by pssguy** [rstudio/bookdown#162]
a) When trying to add cover image on YAML the url throws an error
url: "https\://bookdown.org/aclark/useR2016videos/"

```

Error in yaml::yaml.load(enc2utf8(string), ...) : 
  Scanner error: while parsing a quoted scalar at line 13, column 6found unknown escape character at line 13, column 12
Calls: <Anonymous> ... yaml_load_utf8 -> mark_utf8 -> <Anonymous> -> .Call
Execution halted

Exited with status 1.

```

b) Does the custom image have to be of specific dimensions

c) Is it viewable prior to publishing

**Comment by yihui** [comment]
1. I think you need to escape the colun `url: "https\://bookdown.org/aclark/useR2016videos/"`. See the example on the About page https://bookdown.org/;
2. No, currently there is no requirement, so just use whatever that makes it look fine on the bookdown.org homepage;
3. You can always embed the cover image in the book if you like `![]()` or `knitr::include_graphics()`. You may see my trick here: https://raw.githubusercontent.com/rstudio/bookdown/master/inst/examples/index.Rmd I don't want to show the cover image if the output is not HTML.

**Comment by pssguy** [comment]
Sorry my bad. 
It throws that error WITH the colon escaped as per your example

Without it, the book gets built with the image appearing in the Introduction as per your trick 3
but in top right hand corner the url,'https://bookdown.org/aclark/useR2016videos/' gets shown

**Comment by yihui** [comment]
Sorry the quotes should be single quotes (as in the bookdown book https://raw.githubusercontent.com/rstudio/bookdown/master/inst/examples/index.Rmd). I'll update the page shortly.

**Comment by pssguy** [comment]
So to clarifydescription - double quotesurl - single quotesgithub-repo and cover-image - no quotes 

    On Tuesday, July 19, 2016 3:04 PM, Yihui Xie <notifications@github.com> wrote:
 
 

 Sorry the quotes should be single quotes (as in the bookdown book https://raw.githubusercontent.com/rstudio/bookdown/master/inst/examples/index.Rmd). I'll update the page shortly.—

**Comment by yihui** [comment]
The url is an exception due to a missing feature in Pandoc. For all other options, just use normal YAML syntax (typically double quotes, but sometimes quotes are not necessary).
