### ISSUE TITLE
Is there any way to see usage hours or visits?

### ISSUE THREAD

**Issue by pssguy** [rstudio/bookdown#163]
to books on bookdown
Similar to how you can on shinyapps.io

**Comment by yihui** [comment]
Currently there is no restriction on the usage hours. We don't have a price plan at the moment, and I guess hosting static HTML books is likely to be always free. In the future, you may be able to build books on the bookdown server, in which case it will consume much more resources than just hosting the static files, and that is probably when you need to worry about usage. If you just build books locally and publish to bookdown.org, I don't think you need to worry about anything.

**Comment by pssguy** [comment]
It was more interest in seeing how many people are visiting the  book rather than concerns about cost!
I know you guys are pretty generous with new developments
I guess the same applies to rstudioconnect apps

**Comment by yihui** [comment]
I see. In that case, you can just embed Google Analytics code or whatever webmaster tools in your book using the `includes` option.

Just to clarify, bookdown.org is based on RStudio Connect, but this server is not intended for publishing content other than books. I noticed some users published things like shiny apps there, but there is no guarantee we will continue supporting these apps in the future.
