### ISSUE TITLE
Any thoughts of creating a bookdown cover brand?

### ISSUE THREAD

**Issue by pssguy** [rstudio/bookdown#167]
This might help publicity and also aid authors with minimal photo-editing abilities e.g. yours truly to create a passable cover image
  So based on something similar to this [cover generator](https://dev.to/rly) perhaps with more options for users to upload images. It would then be easy to create something similar, with the RStudio logo, to this

![cover2](https://cloud.githubusercontent.com/assets/2775918/17220952/74a65f52-54a6-11e6-9235-b2368b2d10d0.png)

**Comment by haozhu233** [comment]
What about a Rstudio addin?

**Comment by yihui** [comment]
Sorry, but we don't have plans to support this.
