### ISSUE TITLE
Conditional compilation of book chunks to ensure compatibility with both HTML and XeLaTeX

### ISSUE THREAD

**Issue by adamryczkowski** [rstudio/bookdown#168]
One can add custom LaTeX commands, there is a lot to gain over basic rendering capabilities of pure Pandoc. The problem is that when I use e.g. `\LaTeX` instead of `LaTeX` on the markdown, the pdf version includes the 'LaTeX', and the HTML version includes nothing. 

What I am missing is a either 

* some form of inline conditionals, like `This document was rendered in [bookdown:pdf_book: \LaTeX | bookdown:gitbook: HTML] by bookdown`. 

or 

* Support R *inline chunks* with `output='asis'`. (For R chunks, I know that I can always use an option `output='asis'`, and use the R output as a conditionally-rendered text. Unfortunately chunks force new paragraphs)

In the ideal world, `pandoc` should be able to understand all LaTeX formatting commands and handle it correctly. But I think it is safe to assume it would never happen. 

Is anything like this already exists? Do you have any plans to include it?

**Comment by yihui** [comment]
No, this does not exist for general users, but some (internal) output functions do take the output format into consideration, e.g. the plot output can be LaTeX or HTML depending on the format. If you want conditional output, the object you should inspect is `knitr::opts_knit$get('rmarkdown.pandoc.to')` (or `knitr:::pandoc_to()` for short). This value can be `latex`, `html`, `word`, `beamer`, ...

**Comment by sctyner** [comment]
Commenting to remind myself to try this when switching between HTML and PDF. My case: I have GIFs & 3D interactive plots which breaks the PDF compilation. Need to turn on static graphs & turn off web graphs when rendering to PDF.
