### ISSUE TITLE
Book down only produces html:  No .pdf, no word

### ISSUE THREAD

**Issue by sreejimalayil** [rstudio/bookdown#170]
Whatever I do, bookdown only produces the html version.  I have been trying with the basic example provided, but result is just the html version.

Should I change any configurations in the  "A Minimal Book Example" to  get a pdf generated?  Appreciate any help.

**Comment by yihui** [comment]
No, all you need to do is follow the steps here (use the preview version of RStudio) https://bookdown.org/yihui/bookdown/get-started.html For PDF output, you need to install LaTeX.
