### ISSUE TITLE
can a toc be generated in single documents generated from word_document2()?

### ISSUE THREAD

**Issue by mienkoja** [rstudio/bookdown#171]
I am trying to get a TOC on a single document generated from `output: bookdown::word_document`. 

I have added the following line to my YAML: 

```
output: bookdown::word_document
  toc: true
```

But am getting the following error: 

```
Error in yaml::yaml.load(enc2utf8(string), ...) : 
  Scanner error: mapping values are not allowed in this context at line 5, column 32
Calls: <Anonymous> ... yaml_load_utf8 -> mark_utf8 -> <Anonymous> -> .Call
Execution halted
```

Can I add a TOC to a single document bookdown rendering using `word_document2()`?

**Comment by yihui** [comment]
I think that is just wrong YAML syntax. This should be fine:

```
output:
  bookdown::word_document:
    toc: true
```

**Comment by mienkoja** [comment]
@yihui - you are correct. The revised YAML syntax works fine.
