### ISSUE TITLE
publish_book() gives "https:/" error

### ISSUE THREAD

**Issue by ccolonescu** [rstudio/bookdown#172]
I try to publish to bookdown.org and this is what I get:

```
> bookdown::publish_book(name="RPoE4", account="ccolonescu", render="none")
Error in parse(text = front_matter$site) : <text>:1:7: unexpected '/'
1: https:/
          ^
```

Here are the first lines in my index file:

```yaml
--- 
title: "My Title"
author: "Me"
date: "`r Sys.Date()`"
site: https://bookdown.org/ccolonescu/RPoE4/
output: latex_document
documentclass: book
```

I use RStudio Version 0.99.1281

Any help is appreciated.

**Comment by yihui** [comment]
The field `site` is supposed to be `url`, and the URL needs to be quoted in single quotes, with the colon being escaped like the example on the `About` page of https://bookdown.org/

BTW, I don't know what the `latex_document` output format is. There is not such a format in rmarkdown or bookdown. 

```
--- 
title: "My Title"
author: "Me"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
url: 'https\://bookdown.org/ccolonescu/RPoE4/'
output: bookdown::gitbook
documentclass: book
---
```

**Comment by ccolonescu** [comment]
Thanks! It works now.
