### ISSUE TITLE
stargazer with bookdown?

### ISSUE THREAD

**Issue by ccolonescu** [rstudio/bookdown#173]
I would like to use `stargazer` with bookdown, so that the table can be seen both in html and pdf. However, stargazer requires the argument `type`, which asks whether you want html output or latex. How can I have both output options at the same time?
Thank you.

**Comment by yihui** [comment]
You can use `knitr:::is_latex_output()` to check whether the output format is LaTeX.

**Comment by ccolonescu** [comment]
Thanks, it works fine.
