### ISSUE TITLE
GIFs not loading in PDF / link instead?

### ISSUE THREAD

**Issue by ismayc** [rstudio/bookdown#174]
LaTeX has issues by default with GIFs so any chunk in an Rmd that looks like 

```{r forgetcode, echo=FALSE, fig.cap="Forgetting to copy from Console to R chunk"}
knitr::include_graphics("gifs/forget_copy.gif")
```

will produce an error when building a `pdf_book` such as

`! LaTeX Error: File 'gifs/forget_copy' not found.`

Could a link be provided to the web location of the GIF instead so that the LaTeX file would compile with the link instead of attempting to do `\includegraphics`?  Something similar for ePub would be great.

**Comment by yihui** [comment]
Not very straightforward but possible:

```r
if (knitr:::is_latex_output()) {
  knitr::asis_output('\\url{....}')
} else {
  knitr::include_graphics("gifs/forget_copy.gif")
}
```

**Comment by ismayc** [comment]
Ah, yes!  Are there just `is_latex_output()` and `is_html_output()` functions currently?  It seems like this is the way to solve quite a few of the problems of going between formats that sometimes occur.  Epubs and Word documents seem to have their own sorts of issues.

**Comment by yihui** [comment]
These functions have existed for a while but not exported. `is_latex_output()` is simple, but `is_html_output()` is a little tricky, e.g. should word/epub be considered as HTML output?

My suggestion is try your very best to avoid this kind of output conditional on the output format. It is often possible to come up with a solution, but it is very unlikely to be perfect. Ask yourself three times "do I really have to use GIFs" :) It will be much easier to give up either GIF or PDF.

**Comment by ismayc** [comment]
No, I don't really have to use GIFs...but...but... :) Thanks, @yihui!
