### ISSUE TITLE
On rebuild of failed compile the combined Rmd is not being removed 

### ISSUE THREAD

**Issue by coatless** [rstudio/bookdown#176]
When previewing the textbook via Addins preview, the combined `.Rmd` that gets autogenerated containing the `XX-content.Rmd` does not get removed on failure. Once the issue is corrected and the preview is automatically generated, then one will run into:

> Error in parse_block(g[-1], g[1], params.src) : duplicate label 'intro_load'
> Calls: knit ... process_file -> split_file -> lapply -> FUN -> parse_block
> Execution halted

As the combined `.Rmd` still has left overs from the previous run. 

That is, the file is persistent, but lacks the ability to clear the previous problematic iteration when a new compile is done. 

This problem was introduced when a commit to leave the failed render fail was added: 

https://github.com/rstudio/bookdown/commit/2c97cd3879d6249020fb665821aef09d1f50e4f3

To replicate, run this once:

```md
--- 
title: "Fake"
date: "`r Sys.Date()`"
knit: "bookdown::render_book"
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
site: bookdown::bookdown_site
description: ""
---

Hello

\```{r some_chunk}
1+2
\```


\```{r bad_chunk}
a*2
\```

```

Then update `bad_chunk` to:

```
\```{r bad_chunk}
a = 1
a*2
\```
```

**Comment by yihui** [comment]
The combined Rmd will not be considered as the input Rmd because of `setdiff(source_files(format, config), main)` on line #99 in 2c97cd3879d6249020fb665821aef09d1f50e4f3

I cannot reproduce your issue. Could you upload a zip archive of your reproducible example?

**Comment by coatless** [comment]
I've attached a reproducible example.

[repo_combined.zip](https://github.com/rstudio/bookdown/files/423746/repo_combined.zip)

Let me know if I can provide anything else.

**Comment by yihui** [comment]
Perfect. Fixed. Thanks!

**Comment by coatless** [comment]
No no, thank you!
