### ISSUE TITLE
Cross-references as in https://bookdown.org/yihui/bookdown/latexpdf.html

### ISSUE THREAD

**Issue by tomjamesprior** [rstudio/bookdown#178]
How was the text "Sections 2.3, 2.4, and 2.5" with 2.3, 2.4, and 2.5 each being a link to a numbered section, achieved?

That is a page from the tutorial book, but that book itself does not describe any way to refer to sections by their section numbers.

**Comment by yihui** [comment]
Whenever you see anything that you want to know about its R Markdown source, you can just hit the Edit button on the toolbar, and it will take you to the source.

Cross-references are actually documented at https://bookdown.org/yihui/bookdown/cross-references.html
