### ISSUE TITLE
cannot clear search

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#179]
I recently searched within http://r4ds.had.co.nz.

And now I can't get back out of search. Clicking on the x does nothing. Which prevents me from seeing the sidebar. Safari 9.1.2 if that matters.

![screen shot 2016-08-19 at 12 05 03 pm](https://cloud.githubusercontent.com/assets/599454/17821201/36b3d5e2-6605-11e6-90e6-05bc8ee217cf.png)

**Comment by yihui** [comment]
Yes, that is a problem specific to Safari. The only way to clear it in Safari is to click the search button again. Or press F when the search box is not on focus.

**Comment by jennybc** [comment]
AHA! That worked (clicking search box again). If there's no hope of other remedy, feel free to close this then. I wonder if there's any way to deliver this info to people stuck where I was.
