### ISSUE TITLE
bookdown can deal with markdown in fig.cap in html, not in latex

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#180]
This chunk option works, when the output is HTML (such as `tufte_handout2()`), but not when the output is LaTeX, where the markdown syntax is not interpreted.

```
fig.cap=c("Participant considers all items.", "Participant chooses two *similar* items, names category."}
```

![doesntwork](https://cloud.githubusercontent.com/assets/5372770/17836959/1675458e-67a6-11e6-9bee-b85fa6f17bfc.png)

![screen shot 2016-08-21 at 13 49 04](https://cloud.githubusercontent.com/assets/5372770/17836960/1a95506e-67a6-11e6-9746-641abc69d20f.png)

I know that as per the docs, I shouldn't do complicated markup in the margins:

> For the sake of portability between LaTeX and HTML, you should keep the margin content as simple as possible (syntax-wise) in the marginefigure blocks. You may use simple Markdown syntax like **bold** and _italic_ text, but please refrain from using footnotes, citations, or block-level elements (e.g. blockquotes and lists) there.

But this was just simply italics :).

Ps.: this is obviously a very, very low priority thing, and probably my own fault for using something wrong / too complicated.

**Comment by yihui** [comment]
It is not your fault. It is a limitation of knitr/bookdown, and is a little difficult to explain :( Frankly I wish we could just use any Markdown syntax in figure/table captions, but it is not possible for now.

**Comment by yihui** [comment]
Please see one solution in #209.
