### ISSUE TITLE
several include_graphics calls behave differently than several qplot calls

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#181]
Consider these three examples:

**Chunk with margin.fig = TRUE and 4 qplots and vector of 4 fig.cap**

``` r q-pic, echo=FALSE, out.width="100%", fig.cap=c("Participant considers all items.", "Participant chooses two *similar* items, names category.", "Participant applies categories to all items.", "All items are categorized as TRUE or FALSE."), dpi = 72, fig.margin = TRUE, fig.show = "asis"
qplot(x = 1:10, y = 1:10)
qplot(x = 1:10, y = 1:10)
qplot(x = 1:10, y = 1:10)
qplot(x = 1:10, y = 1:10)
```

yields **as intended, with different captions**
![screen shot 2016-08-21 at 13 52 11](https://cloud.githubusercontent.com/assets/5372770/17836975/ab942e6e-67a6-11e6-95f9-1adccb017442.png)

---

**Chunk with margin.fig = TRUE and 4 include_graphics and vector of 4 fig.cap**

``` r q-pic, echo=FALSE, out.width="100%", fig.cap=c("Participant considers all items.", "Participant chooses two *similar* items, names category.", "Participant applies categories to all items.", "All items are categorized as TRUE or FALSE."), dpi = 72, fig.margin = TRUE, fig.show = "asis"
include_graphics(path = "img/q-cat-stage-0.png")
include_graphics(path = "img/q-cat-stage-1.png")
include_graphics(path = "img/q-cat-stage-2.png")
include_graphics(path = "img/q-cat-stage-3.png")
```

yields **incorrectly with all the same captions**
![screen shot 2016-08-21 at 13 52 55](https://cloud.githubusercontent.com/assets/5372770/17836980/cd2f26aa-67a6-11e6-89d0-79bf5f6e7e4d.png)

---

**Chunk with margin.fig = TRUE and include_graphics() with 4-long vector and vector of 4 fig.cap**

lastly, when passing a vector to `include_graphics()`, it **works fine again**

``` r q-pic, echo=FALSE, out.width="100%", fig.cap=c("Participant considers all items.", "Participant chooses two *similar* items, names category.", "Participant applies categories to all items.", "All items are categorized as TRUE or FALSE."), dpi = 72, fig.margin = TRUE, fig.show = "asis"
include_graphics(path = c("img/q-cat-stage-0.png", "img/q-cat-stage-1.png", "img/q-cat-stage-2.png", "img/q-cat-stage-3.png"))
```

![screen shot 2016-08-21 at 13 55 36](https://cloud.githubusercontent.com/assets/5372770/17837003/4d52203a-67a7-11e6-86a7-22bb56f41da6.png)

---

I expected that `include_graphics()` would behave basically like any other graphics-producing call, but that appears not to be the case; to set _separate_ `fig.cap` for each plot, the `include_graphics()` must called _only_ once, with a vector of files.
`qplot()` can be called several times, and uses the different `fig.cap` as intended.

Is this intended behavior, or did I miss something?

**Comment by yihui** [comment]
Looks like a bug of `include_graphics()`... At the moment I have no idea about how to fix it, though.

**Comment by cderv** [comment]
I think this was fixed by https://github.com/yihui/knitr/pull/1776

here is a reprex that works of with last version of **knitr**

````markdown
---
title: "Test"
date: "`r Sys.Date()`"
output: bookdown::tufte_html2
---

```{r}
library(ggplot2)
```


```{r qplots, fig.margin = TRUE, fig.cap = sprintf("cap%s", 1:4), echo = FALSE}
qplot(x = 1:10, y = 1:10)
qplot(x = 1:10, y = 1:10)
qplot(x = 1:10, y = 1:10)
qplot(x = 1:10, y = 1:10)
```

```{r, fig.margin = TRUE, fig.cap = sprintf("other%s", 1:4), echo = FALSE}
knitr::include_graphics(path = knitr::fig_chunk("qplots", "png", 1))
knitr::include_graphics(path = knitr::fig_chunk("qplots", "png", 2))
knitr::include_graphics(path = knitr::fig_chunk("qplots", "png", 3))
knitr::include_graphics(path = knitr::fig_chunk("qplots", "png", 4))
```
````
