### ISSUE TITLE
Code inside blocks 

### ISSUE THREAD

**Issue by lselzer** [rstudio/bookdown#183]
Hello, I'm having trouble getting this to render correctly.  Is it posible to do this? For what I read it is. Or should I just use a `div`?

```
# Title

Text.

```{block, type = 'rmdtip'}
## title

Some text

 ```{r, eval=FALSE}
code_fun()
\```

More Text in the block.

\```

Text outside the block
```

I added the backslash escape the the backticks to make it clear in this issue.

**Comment by yihui** [comment]
You can add a zero-width space in-between ```` ``` ````, e.g. ```` `​`` ```` (note there is an invisible zero-width space after the first backtick).

**Comment by yihui** [comment]
This has been documented at https://bookdown.org/yihui/bookdown/knitr.html

**Comment by egarpor** [comment]
So I am trying to do a

```
\```{block, type = 'rmdtip'}
## title

Some text

`​``{r, eval=FALSE}
code_fun()
`​``

More Text in the block.

\```

```

(with the zero-width space in-between the backticks delimiting the code chunk) and it does not render the code properly. Is that how it was supposed to be used?

**Comment by yihui** [comment]
Try this:

    ```{block2, type = 'rmdtip'}
    ## title
    
    Some text
    
        `​``{r, eval=FALSE}
        code_fun()
        `​``
    
    More Text in the block.
    ```

**Comment by egarpor** [comment]
Thanks for the reply yihui! I added your code to my file:

![image](https://cloud.githubusercontent.com/assets/1271286/19626142/d9ccfddc-992a-11e6-8810-17f7e22ac4c2.png)

and then I get this:

![image](https://cloud.githubusercontent.com/assets/1271286/19626123/4f69e970-992a-11e6-956c-d150915fc6a2.png)

So the code chunk is rendered inside the block but still is not interpreted as `R` code. I am using the 0.1.16 package version.

**Comment by yihui** [comment]
Okay I see what you want. Unfortunately that is not possible.

**Comment by ijlyttle** [comment]
Just to add my vote as this capability being nice to have (at some point).

**Comment by yihui** [comment]
Unfortunately this is pretty much by design: code chunks cannot be nested, i.e. we cannot have an `r` chunk inside a `block2` chunk.

**Comment by ijlyttle** [comment]
Thanks for thinking about this - I was worried that this was where you used the Willy Wonka "Good Day Sir" gif :)

**Comment by yihui** [comment]
No, that would be rude 😉 I'd use this one instead:

![](https://slides.yihui.name/gif/give-up.gif)
