### ISSUE TITLE
Chunk Labels with Slashes in Them for Cross Referencing

### ISSUE THREAD

**Issue by tinyheero** [rstudio/bookdown#185]
I know that based on https://bookdown.org/yihui/bookdown/figures.html it says that:

> If you want to cross-reference figures or tables generated from a code chunk, please make sure the chunk label only contains alphanumeric characters (a-z, A-Z, 0-9) and dashes (-). Other characters do not qualify.

Would there be a possibility to consider slashes though? 

The reason I ask is that I've been using the chunk names as a convenient way to specify an output path for the figure when using bookdown in Rmarkdown websites. While I recognize that it's possible to use the `fig.path` option, this makes it harder to create distinct chunk name. For example,

* \`\`\``r training_cohort/heatmap-score-barplot`\`\`\`
* \`\`\``r validation_cohort/heatmap-score-barplot`\`\`\`

Provides a convenient way to both have a distinct chunk name and output path for the figure in the chunk. But cross-reference won't work with the slash. The alternative is:

* \`\`\``r heatmap-score-barplot, fig.path = 'training_cohort'`\`\`\`
* \`\`\``r heatmap-score-barplot, fig.path = 'validation_cohort'`\`\`\`

This works for cross-referencing, but this means that the fig.path cannot be used to generate a distinct chunk names.

**Comment by yihui** [comment]
Done.

**Comment by tinyheero** [comment]
Fantastic! Thanks so much!
