### ISSUE TITLE
How to suppress chapter reference 

### ISSUE THREAD

**Issue by junchenfeng** [rstudio/bookdown#186]
I want to aggregate chapter reference into a reference in the end of the book.

Is it possible in the current version of bookdown? If so, how?

**Comment by junchenfeng** [comment]
It turns out that the reference is under chapter in the html preview but at the end of the book in pdf.
Thus closed.

**Comment by yihui** [comment]
Same as #102. Basically you set the option `split_bib` to FALSE, e.g.

```yaml
bookdown::gitbook:
  split_bib: no
```
