### ISSUE TITLE
First-level header necessary for building HTML (trouble building index.html)

### ISSUE THREAD

**Issue by juliasilge** [rstudio/bookdown#187]
As @dgrtwo and I have been working on our [bookdown project on tidy text mining](https://github.com/dgrtwo/tidy-text-mining), we had a LOT of trouble getting the project to build an `index.html` file. We had an `index.Rmd` and kept trying to figure out why the corresponding HTML file was not getting built. Eventually Dave discovered that it was because we did not have a first-level header (`#`) in our `index.Rmd`, and once we added that, all was well. We, more naturally, had first-level headers in all our chapters so of course they all got built just fine.

What do you think about this behavior? Do you think it should be like this? At a minimum, could it be more clearly documented that the .Rmd files will not get built to HTML unless there is a first-level header?

**Comment by yihui** [comment]
That was documented: https://bookdown.org/yihui/bookdown/usage.html

**Comment by juliasilge** [comment]
What would you think about adding an `index.Rmd` to that list there, showing examples of how to get started? Or, when `index.Rmd` is mentioned in the paragraph after the list, there is a short note about the first-level header?

```
If there exists an Rmd file named index.Rmd (which also must start immediately with a first-level heading), it will always be treated ...
```

I did go over that section several times and it took quite a while to realize that was our problem with the index file.

**Comment by yihui** [comment]
That is a good suggestion. Thanks!

**Comment by juliasilge** [comment]
Thank YOU so much for all your work on this amazing tool for communicating with people. :sparkles::sparkles::sparkles:
