### ISSUE TITLE
Pairs of $ inside code blocks inside custom blocks

### ISSUE THREAD

**Issue by cjgb** [rstudio/bookdown#188]
I think I found a bug concerning how `$` is rendered inside inlined code blocks inside custom blocks. When there are two of them, the HTML renderer considers everything between them as a LaTeX formula.

I have attached a small sample file, [index.zip](https://github.com/rstudio/bookdown/files/440707/index.zip) that reproduces the problem. The intermediate `.md` files seem correct, but the final `.html` file is not.

**Comment by yihui** [comment]
I think you can escape the dollar sign with `\$`.
