### ISSUE TITLE
pdf icon at bookdown.org page too small

### ISSUE THREAD

**Issue by ccolonescu** [rstudio/bookdown#189]
I've published a book on bookdown.org in both html and pdf formats. I have been told by users that the pdf icon is hard to notice. Is it possible to make it more conspicuous? (The pdf icon alone shows up only when there is no epub version of the book.)

**Comment by yihui** [comment]
I agree it is subtle to notice, but I don't want to increase its default size in bookdown. If you want to increase the button size, you can add a css file to your book, e.g.

```css
.book .book-header .btn {
  font-size: 20px;
}
```
