### ISSUE TITLE
Cross-referencing equations

### ISSUE THREAD

**Issue by crsh** [rstudio/bookdown#190]
Hi, thanks for the great package. After reading the documentation I was wondering if there is---or ever will be---a syntax to cross-reference equations?

**Comment by yihui** [comment]
Yes, please see the end of this page https://bookdown.org/yihui/bookdown/markdown-syntax.html

**Comment by crsh** [comment]
Indeed, sorry I missed that. I can get this to work in the example `gitbook` and in a `pdf_document2`. When I try to use it in `html_document2` the equation is not numbered and consequently the corss-referencing doesn't work; in `word_document2` the equation doesn't render at all. I assume the latter is a pandoc issue rather than having to do with bookdown?

~~~{markdown}
---
title: "Untitled"
output: bookdown::html_document2
---

\begin{equation}
f\left(k\right)=\binom{n}{k}p^k\left(1-p\right)^{n-k} \label{eq:binom}
\end{equation}

You may refer to it using `\@ref(eq:binom)`, e.g., see Equation \@ref(eq:binom).
~~~

**Comment by yihui** [comment]
For Word, yes I think it is a pandoc issue. For `html_document2`, you need to enable equation numbering by adding this to your document (preferably in the `<head>` but it does not really matter):

```html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
```

**Comment by yihui** [comment]
The MathJax configuration is no longer necessary with the current development version of bookdown. Equations will be numbered as long as they are labeled: https://bookdown.org/yihui/bookdown/markdown-syntax.html

**Comment by stla** [comment]
@crsh 
The equation is rendered in Word if you enclose between "$$":
```
$$
\begin{equation}
f\left(k\right)=\binom{n}{k}p^k\left(1-p\right)^{n-k} (\#eq:binom)
\end{equation}
$$
```
But there are other bugs...

**Comment by yihui** [comment]
@stla That is not necessary. `$$` is automatically added when the output format is EPUB or Word: https://github.com/rstudio/bookdown/blob/b9f0e400d5d9e75b0e7871dea8ad00822b27b007/R/ebook.R#L178-L193

**Comment by stla** [comment]
@yihui I have tried today, with the latest bookdown, and the equation is not rendered without `$$`.

**Comment by yihui** [comment]
I cannot reproduce it using [bookdown-demo](/rstudio/bookdown-demo). I don't have Word installed but I can see the equation when my docx is imported in Google Docs.

It is very weird that your equation wouldn't work without `$$` because bookdown will add `$$` automatically.

Do you have a minimal reproducible example?

**Comment by stla** [comment]
Yes I will post my example. That explains why an additional `$$` is printed in the docx, below the equation. There's no way to keep the `md`?

**Comment by stla** [comment]
Ok, `keep_md` works. 
My `Rmd` is 
```
\begin{equation} (\#eq:binom)
f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k} 
\end{equation}

$$
\begin{equation} (\#eq:binom)
f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k} 
\end{equation}
$$
```

Then the `md` is exactly the same.

```
---
title: "Untitled"
author: "John Doe"
date: "November 10, 2016"
output:
  bookdown::word_document2:
    fig_caption: yes
    keep_md: yes
    toc: yes
documentclass: article
link-citations: yes
linkcolor: blue
---

```{r setup, include=FALSE}
library(bookdown)
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter One

\begin{equation} (\#eq:binom)
f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k} 
\end{equation}


$$
\begin{equation} (\#eq:binom)
f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k} 
\end{equation}
$$

Equation \@ref(eq:binom) is the probability mass function of the binomial distribution with size parameter $n$ and success probability $p$. 
```

**Comment by stla** [comment]
Oh you're right. My label is at a wrong place. This works like this:
```
\begin{equation}
(\#eq:binom)
f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k} 
\end{equation}

```

**Comment by yihui** [comment]
Right. For `\begin{equation}` and `\end{equation}`, there should not be anything before or after them on the same lines when the output is Word or EPUB.

**Comment by Keniajin** [comment]
I tried rendering the equation on Word without `$$` but it wasn't working.  The issue is with the `$$` the equation won't render on pdf.  How can I work around this?

**Comment by efayolle** [comment]
Is there a way to assign a label to the equation for cross-referencing  with `$$` ?
Indeed the equation preview does not work with `\begin{equation}` and `\end{equation}` in Rstudio or Typora.

**Comment by jannikbuhr** [comment]
The following currently works for me and previews in RStudio:
```
$$D=\frac{1}{2d}
(\#eq:eq)$$

see \@ref(eq:diffusivity)
```
as well as
```
$$
D=\frac{1}{2d}
(\#eq:eq)
$$
```
I assume the double dollar signs get translated to `begin{equation}` and `\end{equation}`, so you get the best of both worlds.

Note: without the newline before `(\#eq...)`, it does not knit correctly.
```
$$D=\frac{1}{2d}(\#eq:eq)$$
```

Hope it helps you @efayolle :)

**Comment by efayolle** [comment]
Thank you @jannikbuhr ! 🙂

**Comment by efayolle** [comment]
Hi @jannikbuhr
It seems there is a difference between `$$`and `begin{equation}`. 
When I render with `bookdown::pdf_book:`, if I use `$$` the reference numbers of the equations do not appear to the right of them, but the cross-referencing still work in the text.
The `begin{equation}` renders an equation and its associated reference number at the end of the line.

**Comment by sumanstats** [comment]
I have this multiline equation which I want to reference and tried this way:

```
\begin{equation} 
(\#eq:six_first)
  \begin{split}
  \text{Slope of tangent is,}\\
   &= -\frac{x_1^2}{y_1^2}\\
  \frac{y_2-y_1}{x_2-x_1} &= -\frac{x_1^2}{y_1^2}\\
  \end{split}
\end{equation}
```

See `\@ref(eq:six_first)`, but it does not work. What can I do to reference such multiline equations?
