### ISSUE TITLE
Figure captions not rendering correctly if chunk name contains underscore "_"

### ISSUE THREAD

**Issue by janvydra** [rstudio/bookdown#194]
Not really a bug, but still spent around 3 hours figuring this one out:

this renders as Figure 1: (#fig:os_fig)Aha
{r os_fig, fig.cap="Aha"}
  survplot(s, n.risk = T, time.inc = 1)

while this renders correctly:
{r os-fig, fig.cap="Aha"}
  survplot(s, n.risk = T, time.inc = 1)

Best regards
Jan

**Comment by yihui** [comment]
This has been documented: https://bookdown.org/yihui/bookdown/figures.html
