### ISSUE TITLE
Changing size of horizontal rule for LaTeX via ***

### ISSUE THREAD

**Issue by ismayc** [rstudio/bookdown#197]
Is there a way to change the default `\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}` to `\begin{center}\rule{\linewidth}{\linethickness}\end{center}` when a `***` is encountered in an Rmd?  The horizontal line goes all the way across the webpage version but is reduced to only half the page by default for a PDF book using `tufte_book`.

**Comment by yihui** [comment]
This is not specific to `tufte_book`. It is hard-coded by Pandoc. A quick google search for "pandoc horizontal rule width":

- http://stackoverflow.com/q/25657471/559676
- https://groups.google.com/forum/#!msg/pandoc-discuss/LzV15A8dyDs/viJRp6nW8v0J
- https://github.com/jgm/pandoc/issues/2544

**Comment by ismayc** [comment]
Thanks for this.  I was just trying to keep things looking the same for all document types as much as possible and this seems to be an extra thing that requires hard-coding for each specific document type that could be avoided.  

I should have been more clear that I added in a change to the tufte_handout file and used that as a template.tex and it worked, but I would doubt many folks are comfortable enough with LaTeX to be able to make this change as well.  I was hoping there was a nicer way to bypass Pandoc, but my question wasn't clear.

**Comment by yihui** [comment]
You don't need to define a whole template. You just need to redefine `\rule{}`, and include it via the `includes` option (`in_header`): 

- http://rmarkdown.rstudio.com/pdf_document_format.html#includes
- https://bookdown.org/yihui/bookdown/yaml-options.html
