### ISSUE TITLE
Enable amsthm in preamble

### ISSUE THREAD

**Issue by junchenfeng** [rstudio/bookdown#200]
I want to use the amsthm's newtherom function in my book.

If I put it in the preamble

```
\usepackage{amsthm}
\newtheorem{mydef}{Definition}
```

and later used it in the main article

```
$$
\begin{mydef}
This is a definition
\end{mydef}
$$
```

It gives the following error

```
! Missing $ inserted.
<inserted text> 
                $
l.207 \begin{mydef}
```

**Comment by yihui** [comment]
If the only type of output you want is PDF, you can simply remove `$$`, otherwise I don't have a perfect solution at the moment. This is a partial solution:

    ```{block, type="mydef"}
    This is a definition
    ```

**Comment by yihui** [comment]
Theorem and proof environments have been implemented. Please see the documentation at https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html In your case, you don't need anything in the preamble, and just type

    ```{definition}
    Your definition.
    ```

Of course, you need to install the development version via

```r
devtools::install_github('rstudio/bookdown')
```
