### ISSUE TITLE
Bookdown uses pdflatex instead of xelatex when using base_format

### ISSUE THREAD

**Issue by ThierryO** [rstudio/bookdown#201]
I've created a reproducible example at https://github.com/ThierryO/bookdowntest

The vignette compiles with xelatex when rendering `bookdowntest::bookdown_test()`. When using `bookdown::pdf_book()` with `base_format = base_format: bookdowntest::bookdown_test` the pdf is rendered using pdflatex. How can I make sure that `bookdown::pdf_book()` also uses xelatex to render the pdf?

The xelatex and pdflatex versions of this example differ only in the fonts. The otf version of the font are available from http://www.tug.dk/FontCatalogue/

pandoc command from `bookdowntest::bookdown_test()`

    /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /tmp/RtmpSJM01n/preview-263e6368243c.dir/test.tex --template /home/thierry_onkelinx/R/x86_64-pc-linux-gnu-library/3.2/bookdowntest/pandoc/bookdown_test.tex --latex-engine xelatex 
    /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /tmp/RtmpSJM01n/preview-263e6368243c.dir/test.pdf --template /home/thierry_onkelinx/R/x86_64-pc-linux-gnu-library/3.2/bookdowntest/pandoc/bookdown_test.tex --latex-engine xelatex 

pandoc command from `bookdown::pdf_book()`

    /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /tmp/RtmpSJM01n/preview-263e22db9183.dir/test.tex --template /home/thierry_onkelinx/R/x86_64-pc-linux-gnu-library/3.2/bookdowntest/pandoc/bookdown_test.tex --latex-engine xelatex --variable tables=yes --standalone 
    /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /tmp/RtmpSJM01n/preview-263e22db9183.dir/test.tex --template /home/thierry_onkelinx/R/x86_64-pc-linux-gnu-library/3.2/bookdowntest/pandoc/bookdown_test.tex --latex-engine xelatex --variable tables=yes --standalone

**Comment by ThierryO** [comment]
I was able to track down the problem myself. It turns out I had to use `pandoc_options(latex_engine = "xelatex")` instead of `pandoc_options(args = c("--latex-engine", "xelatex"))`

**Comment by gsaray101** [comment]
where do you changed  pandoc_options(args = c("--latex-engine", "xelatex")) ?
