### ISSUE TITLE
Use left-right arrows for second level navigation.

### ISSUE THREAD

**Issue by paulcbauer** [rstudio/bookdown#202]
Hi! I am using bookdown to prepare slides for a class. Is it possible to modify the left-right arrows so that they jump through the second toc level (1.1, 1.2, 2.1,2.2) and not only through chapters (1,2,3)? Thanks!

**Comment by yihui** [comment]
That is an interesting idea. Actually do you know that you can split the output into sections instead of chapters by setting `split_by = "section"`? https://bookdown.org/yihui/bookdown/html.html That way, each section is an individual page, so left-right navigates through sections.

**Comment by paulcbauer** [comment]
Didn't know that. Sounds great. Thanks!
