### ISSUE TITLE
MathJax doesn't render in toc sidebar of gitbook output

### ISSUE THREAD

**Issue by philomonk** [rstudio/bookdown#204]
Thank you for this great package! I've used it to publish a university course book for a statistics class!

While it works fantastic, I've come across this bug that MathJax does not render properly in the table of contents sidebar of the gitbook. For me, MathJax renders everywhere else in the html output including the header that the faulty toc entry refers to (see screenshot below).

I reproduced this behavior by inserting a heading that includes MathJax to the bookdowm-demo's index.Rmd like so:

```markdown
# Prerequisites

## The $P$-value

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$.
````

Both in the RStudio viewer and my Chrome browser that displays like this:

![bildschirmfoto 2016-09-17 um 15 21 36](https://cloud.githubusercontent.com/assets/12614453/18608892/37d0754e-7ced-11e6-887d-7ef42abe354a.png)

All the best,
-T

**Comment by yihui** [comment]
This is a known issue #56. Since two people have reported it, I took a closer look and the fix should be in the current development version now. Thanks!
