### ISSUE TITLE
Bookdown `\@ref()` inside caption produces messy caption in html output

### ISSUE THREAD

**Issue by philomonk** [rstudio/bookdown#206]
I've come across what I think is a bug. If a (figure) caption contains a `\@ref()` call in the source, part of the caption text is inserted between image and actual caption text in the html output (the pdf is without error). I've been able to reproduce that behaviour with the bookdown-demo repo. There, I added to the index.Rmd the following:

```markdown
# Prerequisites

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$.

One   Two
---- ----
1       2
3       4

: (\#tab:one)Caption text.

This table can be referenced as Table \@ref(tab:one).

![(\#fig:two)A figure caption which references Table \@ref(tab:one)](two.png)

For now, you have to install the development versions of **bookdown** from Github:
```

That produces the following in the html output:

![bildschirmfoto 2016-09-20 um 17 05 10](https://cloud.githubusercontent.com/assets/12614453/18678640/90aa4f6e-7f54-11e6-94b9-3ab03ba239b8.png)

**Comment by philomonk** [comment]
I can say from other occurrences of this bug in my project that the faulty text that's being added is the caption text that follows the `\@ref()` including the automatically generated numbering. See below:

![bildschirmfoto 2016-09-21 um 15 46 39](https://cloud.githubusercontent.com/assets/12614453/18715905/ccc94fa4-8012-11e6-94e7-878af179520c.png)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
