### ISSUE TITLE
Code color palette not color-blind safe

### ISSUE THREAD

**Issue by behrman** [rstudio/bookdown#207]
bookdown colors R code using green and red. Those with red-green color-blindness, the most common form, may not be able to distinguish these.

/cc @hadley

**Comment by yihui** [comment]
They are not pure red or green, and I tested a code chunk through the color blindness simulator:
http://www.color-blindness.com/coblis-color-blindness-simulator/

Normal vision:

![image](https://cloud.githubusercontent.com/assets/163582/18769528/1d91d2e8-80eb-11e6-8f2d-57120e4dd1fd.png)

Red-green color blind vision:

![image](https://cloud.githubusercontent.com/assets/163582/18769521/07862936-80eb-11e6-982c-6c1c5b14562b.png)

Seems to be okay.

**Comment by behrman** [comment]
In your example, 4, pressure, and “b” have three different colors, but it is very difficult to distinguish their colors in the color-blind simulation. I can’t.

What helps to set off the function names is the boldness, not the color.

**Comment by yihui** [comment]
I think colors in syntax highlighting are much less important than colors in data visualization. I'm not sure how much they affect your understanding of the code. I'm not color blind (well actually I do have some slight color blindness), and I rarely consciously notice the colors of tokens in program code when I read them. To me, the colors are more for decorative purposes than really distinguishing different types of tokens.

That said, I'll be happy to change the color theme if any color blind person feels uncomfortable about it.
