### ISSUE TITLE
Possible travis issue

### ISSUE THREAD

**Issue by csgillespie** [rstudio/bookdown#208]
Yesterday I spent a very unproductive day tracking down a travis build issue. The book build fine on two separate computers, but on travis it bombed. The offending chunk was:

```
  cppFunction(
         'int fibonacci(const int x) {
             if (x == 0) return(0); 
             if (x == 1) return(1);
             return (fibonacci(x - 1)) + fibonacci(x - 2);
         }')
```

which is taken from the Rcpp docs. However, deleting sections above this line (or this chunk) just shifted the error to other places. Travis unhelpful didn't provide any useful info.

What did solve the issue was adding

```{r}
rm(list=ls())
```
to the top of the page. What I'm thinking is that travis was running into memory issues; in previous chapters we generated fairly large objects. 

-----
I realise this isn't a bookdown issue, but bookdown does encourage users to create large documents and use travis. Perhaps in a good  practice section somewhere, suggest adding a clean-up line to avoid odd bugs.

**Comment by yihui** [comment]
Are there any Travis logs that I can see? If I cannot figure out the reason for the failure, I do not feel confident enough to call it "best practice", although I did accidentally mentioned `rm(list=ls())` in the docs: https://bookdown.org/yihui/bookdown/configuration.html

**Comment by csgillespie** [comment]
I created a new branch when testing: https://travis-ci.org/csgillespie/efficientR/builds/161979303

**Comment by yihui** [comment]
That is indeed weird. In `make html`, can you use `try()` so that Travis won't fail, and `clean=FALSE` so that the .md output is preserved? I want to know what happened in .md. You can either cache the .md output on Travis and download the cache later, or perhaps send it by email (not sure if it is supported).

**Comment by csgillespie** [comment]
I now can't reproduce the error (all branches have been deleted). 

Not sure what was going on.
