### ISSUE TITLE
underscores in fig.cap

### ISSUE THREAD

**Issue by csgillespie** [rstudio/bookdown#209]
Not sure if this is a bookdown issue.

I want to have an underscore in the fig.cap, e.g. `fig.cap="The function read_csv is handy"`

This works fine in HTML but not pdf. I've tried various escaping tricks, e.g. `read\\_csv`, which work for pdfs but break the HTML version.

**Comment by yihui** [comment]
Thanks for the report! @geanders discovered the same issue yesterday, and I'll try to provide a solution in the next few days.

**Comment by yihui** [comment]
I just provided an alternative way to write figure/table captions. You can write them in a separate paragraph, e.g.

```
(ref:my-caption) The function read_csv is handy.
```

Then use `fig.cap = "(ref:my-cap)"` in the chunk options. Full documentation here: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html (Section 2.2.3)
