### ISSUE TITLE
Update default html table styling

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/bookdown#211]
Can we get an update on the default html table styling so that the output of `knitr::kable(mtcars)` in a gitbook visually matches the output in an html document?

![screen shot 2016-09-23 at 4 22 46 pm](https://cloud.githubusercontent.com/assets/8197328/18803953/045d3d02-81aa-11e6-89a2-b5f382748b9d.png)
**vs**
![screen shot 2016-09-23 at 4 23 47 pm](https://cloud.githubusercontent.com/assets/8197328/18803972/2aa91350-81aa-11e6-925c-9111c6be085a.png)

**Comment by yihui** [comment]
I think that is a good idea. I hate too many vertical lines in a table. You can certainly tweak the CSS through the `css` option under `bookdown::gitbook`, but I'll take a look to see if I can change the default style anyway.

**Comment by tiernanmartin** [comment]
Agreed  – it's much cleaner looking without the vertical lines. I'll make use of the `css` option for now. Thanks for the heads up.
