### ISSUE TITLE
\@ref(...) requires parentheses

### ISSUE THREAD

**Issue by krlmlr** [rstudio/bookdown#213]
...not `{}` braces. Took me too much time to learn this as a first-time bookdown and long-time LaTeX user. The documentation links to the book, this information might be a good fit for the footnote:

> Do not forget the leading backslash!

**Comment by krlmlr** [comment]
Thanks!

**Comment by yihui** [comment]
The only reason for choosing parentheses is they are not special characters in LaTeX or HTML, so they won't be escaped in the output, and it is slightly easier for me to post-process the output. I know this is a selfish reason, and probably not worth it compared to the possible confusion to LaTeX users :)
