### ISSUE TITLE
Can I nest a bookdown project within another project?

### ISSUE THREAD

**Issue by tiernanmartin** [rstudio/bookdown#215]
I would like to nest a `bookdown` document/project (and all its files) within another project. Is it possible to include it in a folder _other_ than the main project's root directory? It seems like no matter what I try the book fails to render.

Here's an example of the folder hierarchy I'd like to achieve:

```
├── example-project.Rproj
│
├── data
│   ├── external
│   ├── interim 
│   ├── processed
│   └── raw      
│
├── communication
│   ├── notebooks
│   ├── bookdown       <- would contain all necessary bookdown files except those in `data/`
│
├── etc
│
```

Are there certain files (say, from the `bookdown-demo` repo) that could be edited to make this work? For what it's worth, I'm currently making use of @krlmlr's [rprojroot package](https://github.com/krlmlr/rprojroot) to make it easier to use consistent paths within projects and that has worked well so far in other rmarkdown docs and rnotebooks. 

Thanks!

**Comment by znmeb** [comment]
Interesting ... I'm trying to do this the other way around. The "master" project is a Bookdown book and a sub-project is an R package.

So far I've had RStudio projects inside other RStudio projects with no issues other than the fact that the highest-level project is where the Git control directory .git lives. That is, when you create a sub-project, *don't* enable Git - use the main project's Git repository. Git submodules are tricky.

**Comment by yihui** [comment]
No, you cannot. An RStudio project can only be of one type: a package, Makefile, or website. I mean you won't be able to click the Build button to build the book, but you can certainly write an R script to compile your book. For example, the bookdown book is in a subdirectory of this repo, which is an R package, and I use this script to build the book: https://github.com/rstudio/bookdown/blob/master/inst/examples/_render.R

Another option you can consider (which is also what I use) is https://bookdown.org/yihui/bookdown/serve-the-book.html and there is an RStudio addin for it https://bookdown.org/yihui/bookdown/rstudio-ide.html
