### ISSUE TITLE
How is search supposed to work?

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#216]
I can't tell if the search capability is rather basic or if I am doing it wrong.

I'm recommending lots of students read [R for Data Science](http://r4ds.had.co.nz) and they are having some difficulty searching for terms in the book.

If I enter, e.g., "join", in the search box, the set of chapters in the sidebar is reduced, presumably to those that contain the word "join". But then what? I see that if I scroll through the entire chapter ~~the word is highlighted~~. Is that the best I can do? Right now I am resorting to browser-based search, so I can navigate to next match, next match, etc.

**Comment by yihui** [comment]
You can search for `search` in the bookdown documentation, go to the Gitbook style page, and while you are in the search box, press Up/Down: https://bookdown.org/yihui/bookdown/html.html

**Comment by jennybc** [comment]
OK. That's great -- I will spread the word!

If I enter `search` in the search box, the sidebar chapters are narrowed to those harbouring matches.

Then if I click on "3.1 HTML", the up/down arrows take me through the matches. ✔️

But if, instead, I click on "3.1.1 GitBook style", the up/down arrows don't work for me. This seems to persist, even if I try to rescue things by clicking on "3.1 HTML" at this point. I can get the arrows to function again by clicking on "3 Output Formats" and then "3.1 HTML".

**Comment by yihui** [comment]
The cursor has to be in the search box for Up/Down arrows to function.

**Comment by jennybc** [comment]
Aaaah.
