### ISSUE TITLE
Manual numbering of chapters

### ISSUE THREAD

**Issue by junchenfeng** [rstudio/bookdown#218]
I write the abstract in the index.rmd, which I really don't want to be chapter 1.

How can I remove the index.rmd from chapter numbering? Or is there a way to insert an abstract without chapter numbering?

**Comment by yihui** [comment]
Use an unnumbered header by appending `{-}` to it: https://bookdown.org/yihui/bookdown/markdown-syntax.html

**Comment by junchenfeng** [comment]
My bad.

**Comment by martinamorris** [comment]
Is it possible to have the chapter numbering start at 0 instead of 1?

thx!

**Comment by yu-soong** [comment]
or
```
output:
  bookdown::pdf_document2:
    number_sections: false
```
Is that what you want?
