### ISSUE TITLE
index.html not created when using the _bookdown.yml rmd_files command

### ISSUE THREAD

**Issue by zachcp** [rstudio/bookdown#219]
Team Bookdown,

Thanks for your great software. 

I've run into an issue when changing the RMD directories. If I move the RMD files somewhere outside of the primary directory and specify the new location in the `_bookdown.yml`, the file is processed to HTML but an index.html file is not longer created.  Then, when you serve the book, you then serve a directory of HTML files instead of the gitbook: see the bottom right panel below - normally this is the gitbook html. 

![screen shot 2016-10-05 at 12 17 42 pm](https://cloud.githubusercontent.com/assets/1260667/19121797/c6ff1b92-8af5-11e6-8294-61c6dbc338a1.png)

Im not sure if this is a feature (fine-grained control) or a bug but I would appreciate any suggestions on how to work around it. My basic use case is that I would like to place related RMD files in subdirectories and then specify how to combine them in the _bookdown.yml. 

Reproducible minimal example here: https://github.com/zachcp/bookdown-demo/tree/bookdownRMDtroubleshoot

Thanks,
zachcp

**Comment by yihui** [comment]
index.Rmd must be in the root directory of the book. Other Rmd files can go to subdirectories.

**Comment by zachcp** [comment]
thank you @yihui.
