### ISSUE TITLE
Echo=FALSE and Theorems

### ISSUE THREAD

**Issue by rtaph** [rstudio/bookdown#220]
Hi Yihui,

Love the new ability to add theorems. However, I have run into the issue that if I have `opts_chunk$set(echo = FALSE)` set, I can no longer get theorems to render.

Trying to override the chunk locally via

```r
```{theorem, echo = FALSE}
A theorem.
'```
```
does not work.

Is there a way around this?

**Comment by rtaph** [comment]
Nevermind-- I typed too quickly. It work if  `echo = TRUE`.

**Comment by yihui** [comment]
I should have documented this. Thanks for the feedback!
