### ISSUE TITLE
References inside blocks

### ISSUE THREAD

**Issue by egarpor** [rstudio/bookdown#223]
It seems like references inside blocks don't work as expected?

For example, for the 'rmdtip' block
```
    ```{r, foo}
    plot(1:5)
    ```
    ```{block, type = 'rmdtip'}
    Figure \@ref(fig:foo)
    ```
```

results in `Figure (???)(fig:foo)`.

**Comment by yihui** [comment]
Try `block2`: https://bookdown.org/yihui/bookdown/custom-blocks.html

**Comment by egarpor** [comment]
Thanks Yihui! That works perfectly. I missed the part on `block2` in the guide.

**Comment by yihui** [comment]
Glad to know it works.
