### ISSUE TITLE
collapse both section and subsection

### ISSUE THREAD

**Issue by mRcSchwering** [rstudio/bookdown#224]
It seems currently if you set `collapse = "section"`, sections are collapsed but subsections are omitted form the TOC.

**Comment by yihui** [comment]
Do you mean when `collapse = 'section'`, the subsections should also be hidden initially?

**Comment by mRcSchwering** [comment]
If I set `collapse = "section"` initially only chapters are shown in the TOC (intended). If I click a chapter, its sections are shown (intended). But, if the section again has subsections, they are not shown in the TOC.

**Comment by yihui** [comment]
I cannot reproduce it. Do you have a reproducible example anywhere?

![untitled](https://cloud.githubusercontent.com/assets/163582/19287159/36ceb25a-8fc6-11e6-9e0b-219a193ab6f1.gif)

**Comment by mRcSchwering** [comment]
Now that I clicked around so much I noticed it worked by double clicking. Before I only clicked once and was surprised that there was no reaction.
![bsp1](https://cloud.githubusercontent.com/assets/21263062/19288159/01b1602e-9005-11e6-9a57-f1a34d788551.gif)

**Comment by yihui** [comment]
Oh really? Double clicking is not required. Single clicking should just work.

**Comment by mRcSchwering** [comment]
I just tried it in firefox and konqueror... It only opens on the second click. Anyway it works, thanks a lot:)

**Comment by yihui** [comment]
That is weird. Do you have a link to the problematic page? Does this page work if you click on Section 1.2? http://docs.rstudio.com/ide/server-pro/index.html

**Comment by mRcSchwering** [comment]
Interesting. There it works.
