### ISSUE TITLE
html page output control

### ISSUE THREAD

**Issue by henrywoo** [rstudio/bookdown#226]
For html output, now it is one chapter one html page. But sometimes one chapter is too long. Can we make one section one page? (one chapter has many sections) If we can, the html page will not be very long for some chapter. Thanks.

**Comment by henrywoo** [comment]
i found `Tufte` works for this. Thanks anyway.

**Comment by yihui** [comment]
This is documented: https://bookdown.org/yihui/bookdown/html.html See the `split_by` option.
