### ISSUE TITLE
custom footers for pdf

### ISSUE THREAD

**Issue by AdamMJenks** [rstudio/bookdown#227]
Is there a proper way to create custom footers that will render on all bookdown pdf pages? The following code in the `index.Rmd` file doesn't show any type of header.

```
--- 
title: "Title"
author: "Authors"
date: "October 2016"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
header-includes: 
   \usepackage{graphicx}
   \usepackage{fancyhdr}
   \pagestyle{fancy}
   \fancyfoot[L]{\includegraphics[width=5cm]{images/Logo_Long.png}}
---
```

**Comment by yihui** [comment]
Don't use the top-level option `header-includes`. Use `includes` under `bookdown::pdf_book` instead: https://bookdown.org/yihui/bookdown/yaml-options.html
