### ISSUE TITLE
Citations bug in developing version

### ISSUE THREAD

**Issue by mingsnu** [rstudio/bookdown#228]
I'm using the latest developing version of bookdown and I found something unusual when using citations.
As shown in the following example, the references occur twice at the bottom of the page.
The code: https://github.com/mingsnu/bookdown-minimal
The html page: http://dreamhunter.me/bookdown-minimal/

**Comment by yihui** [comment]
Set `split_bib: no` under `bookdown::gitbook`: https://bookdown.org/yihui/bookdown/html.html

**Comment by mingsnu** [comment]
OK, I see. I think we should also mention the `split_bib` option in the Citations section. Thank you!

**Comment by yihui** [comment]
That is a good suggestion.
