### ISSUE TITLE
Button 'Hide menu/title bar' or reading/presentation mode

### ISSUE THREAD

**Issue by paulcbauer** [rstudio/bookdown#233]
Hi! 

I am currently (still) developing my course slides with bookdown. 

I wonder if one could add a button to hide/show the top bar that includes the menu button etc. Then there would be more space to show things on the slide. Maybe there could be a presentation/reading mode that only shows the content in the main frame.

Best,

Paul

**Comment by yihui** [comment]
This is not possible for now. You can have a static toolbar instead of a fixed one: https://bookdown.org/yihui/bookdown/html.html (search for `toolbar`).

The height of the toolbar is only 50px. I guess it does not really occupy too much space on the screen after the sidebar is collapsed.

**Comment by paulcbauer** [comment]
Thanks! That worked. Toggle on/off would certainly be a cool feature for the future.

Somewhat related. Is there a way to hack the font size of the chapter titles and relatedly the space/distance between chapter title and toolbar. I use the big letter size to present and the titles/space become so big that it takes too much space on my slides. No answer on [Stackoverflow ](http://stackoverflow.com/questions/40215141/bookdown-how-can-i-change-the-size-of-the-chapter-titles) so far.

**Comment by yihui** [comment]
Since I don't have the time to answer your question, I offered a bounty there, which is the best I can do for you at the moment.

**Comment by paulcbauer** [comment]
Thank you.
