### ISSUE TITLE
Lost the long footnote in gitbook format

### ISSUE THREAD

**Issue by axitdn** [rstudio/bookdown#234]
PDF and EPUB book format work fine.
But the Gitbook format cannot render the "long footnote":
<img width="1269" alt="screen shot 2016-10-25 at 8 39 58 pm" src="https://cloud.githubusercontent.com/assets/1311197/19684781/26d7493c-9af4-11e6-979b-f0524f917b3f.png">

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
