### ISSUE TITLE
Math on e-ink devices

### ISSUE THREAD

**Issue by JVAQUEROM** [rstudio/bookdown#236]
Hello, I recently discovered bookdown and liked a lot the idea of being able to create books to read anywhere: pdf, html, epub...

However, i just discovered that math is just ignored in my kindle device, although calibre reads it properly...is there a workaround to this? I cannot help feeling a bit disappointed about that...what is the point of using epub format if you cannot use it on an eink device?

Thank you for your efforts to do this software, and your help.

EDIT: digging a bit, it turns out that kindle cannot render any math or almost any math...the only way is to use svg image files for formulas... I guess there is no easy way to do this on bookdown, right?

**Comment by yihui** [comment]
Calibre supports MathJax, but it seems Kindle does not support it. I guess math formulas have to be converted to images. Pandoc supports other math rendering methods: http://pandoc.org/MANUAL.html#math-rendering-in-html I don't have a Kindle to test, but `--webtex` is one way to convert math expressions to images. If Kindle supports web pages, you can just read the HTML version.

**Comment by znmeb** [comment]
I have an eInk Kindle - second generation Paperwhite, about a year old. Equations are problematic on it. And the eInk Kindles will *not* work with the fancy new PDF-to-enhanced textbook features at all. For those eBooks you need a PC or Mac Kindle app, an iOS or Android app, or the Kindle Fire.

PDFs read fairly well on the newer eInk Kindles ... you rotate the screen, pinch to zoom when you need to, etc. But this eInk Kindle will be my last.

Amazon has a utility for turning a PDF into one of those fancy eTextbooks. It's free to use but you can only sell the resulting eBook at Amazon! I supposed if you're "selling" the book for a price of 0$US that'll make their lawyers happy, but I don't see the point.

I do plan to experiment with the PDF enhancement tool on a Bookdown book sometime this week - I'll report back.

**Comment by JVAQUEROM** [comment]
Thank your for your answers. I was not aware that pandoc could do the math to image conversion... digging a bit more I just found [this](https://gist.github.com/lierdakil/6a95278d02256a74a0fc) github project, which converts to svg images instead of png, so the image gets zoomed if you change the size of the font. 

Regarding PDF, is there a way to tell bookdown which page size to use? It would be great to be able to set it to the kindles dimensions so that the page fits perfectly without having to zoom (my kindle is non-touch, so zooming is quite restricted).

Thank you very much

**Comment by yihui** [comment]
Yes, you can set the paper size in the YAML metadata of index.Rmd. All possible variables for LaTeX output are listed in the Pandoc documentation: http://pandoc.org/MANUAL.html#variables-for-latex You need to know a bit about LaTeX to understand what these variables exactly mean and what the possible values are, though.

**Comment by JVAQUEROM** [comment]
I could get the pagesize worked out, more or less, i have to adjust a few things. However, webtex option does not seem work...acording to pandoc manual:

>--webtex[=URL]

>    Render TeX formulas using an external script that converts TeX formulas to images. The formula will be concatenated with the URL provided. If URL is not specified, the CodeCogs will be used. **Note: the --webtex option will affect Markdown output as well as HTML, which is useful if you’re targeting a version of Markdown without native math support.**

It looks like it would only work if a tex file is the input, maybe? I just does not work, using --webtex and not using it produces the same reult

**Comment by yihui** [comment]
`--webtex` is irrelevant to LaTeX/PDF output. It is only for Markdown and HTML output. If PDF works, I'd suggest you bear with PDF. I don't think any output format can beat PDF on ebook readers. The disadvantage is that it may require more work to make the output look elegant.
