### ISSUE TITLE
Cross-references don't works in HTML outputs (after 0.1.11 version)

### ISSUE THREAD

**Issue by JrEduardo** [rstudio/bookdown#240]
The syntax `(\#eq:binom)` for labels in math environments don't works. See the example:

_Consider in index.Rmd file_
```markdown
---
title: "A Book"
author: "Frida Gomam"
output: bookdown::html_document2
---

# Hello World {#section}

It renders the equation below:

\begin{equation}
f\left(k\right)=\binom{n}{k}p^k\left(1-p\right)^{n-k} (\#eq:binom)
\end{equation}

You may refer to it using `\@ref(eq:binom)`, e.g., see Equation
\@ref(eq:binom).

The others cross-references works, see section \@ref(section).
```

When compiling the document, with `rmarkdown::render("index.Rmd")`, he following warning message is displayed 
```r
Warning message:
The label(s) eq:binom not found 
```
and the label in equation isn't correct process. See the screenshot below:

![](http://200.17.213.89/~eduardo/foo/equation-error)

This messages also occurs in Travis CI build process of bookdown package after version 0.1.11, see <https://travis-ci.org/rstudio/bookdown/builds/163789423#L585-L589>

---
My R session information is
```r
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pt_BR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_1.1   bookdown_0.1.19

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     digest_0.6.10   assertthat_0.1  mime_0.5       
 [5] R6_2.2.0        xtable_1.8-2    magrittr_1.5    evaluate_0.10  
 [9] stringi_1.1.2   miniUI_0.1.1    tools_3.3.2     stringr_1.1.0  
[13] shiny_0.14.1    httpuv_1.3.3    compiler_3.3.2  htmltools_0.3.5
[17] knitr_1.15      tibble_1.2    
```

**Comment by yihui** [comment]
It failed on Travis because I don't know when they switched to pandoc 1.15.2 by default (maybe it has always been 1.15.2 and I just didn't notice it before). I changed the pandoc version to 1.17.2, and it works fine now: https://travis-ci.org/rstudio/bookdown/builds/174847505#L764-L765 If your pandoc version is older than 1.17.2, please upgrade it. If you are using the latest version of RStudio, you should be fine.

**Comment by JrEduardo** [comment]
Thanks Yihui, I update the pandoc to 1.17.2 version (it was at 1.15.2 version) and math labels are correctly renderized now.

I think the warning message in `ref_to_number` function could to warn user for verify his pandoc version
(https://github.com/rstudio/bookdown/blob/master/R/html.R#L434-L435).

Awesome work in bookdown package :)

**Comment by yihui** [comment]
Thanks for bringing this to my attention. I'll add a warning message.

**Comment by highlando** [comment]
Had the same issue with the current travis pandoc version (2.2). If I set it to 1.17.2 (as suggested here) or 1.19.2.4 (as it is on my machine) everything is fine.

**Comment by highlando** [comment]
2.3.1 works fine, too.

Here is my [repo](https://github.com/highlando/script-daes/commit/7dbab1f541d0247082f64ccf42e630b3b8d3d54a) at this very commit
