### ISSUE TITLE
ASCIIMath support for Math expressions

### ISSUE THREAD

**Issue by ziyadsaeed** [rstudio/bookdown#241]
Please add asciimath support in addition to latex for math expressions. Latex is very cumbersome and asciimath is more natural. It's very similar to an actual math expression, making it very easy to learn and very fast to type.
 http://asciimath.org/

**Comment by yihui** [comment]
Sorry, but we can only support whatever Pandoc supports: http://pandoc.org/MANUAL.html If Pandoc does not support AsciiMath, we cannot, either. It might be possible to get the HTML output format working, but I doubt if it will work for PDF output, too.

**Comment by ziyadsaeed** [comment]
That link mentions ASCIIDoc is supported by pandoc. ASCIIDoc uses ASCIIMathml which is the older version of ASCIIMath. So it is supported by pandoc. Just need an example of how to use it.

**Comment by yihui** [comment]
I don't have time to write a complete solution for you, and I recommend you to ask this question on StackOverflow just like #233. If it is simply a matter of loading a JavaScript library, you can do it via the `in_header` option (see Chapter 4: https://bookdown.org/yihui/bookdown/). However, I don't think you will be able to generate PDF correctly if Pandoc does not support translating AsciiMath to LaTeX.
