### ISSUE TITLE
Some things that go wrong with parts in pdf_document2

### ISSUE THREAD

**Issue by florisvdh** [rstudio/bookdown#243]
I experience issues with _parts_ in pdf output formats (pdf_document2, and the same holds for pdf_book), similar to those in issue #221. I have attached a copy ([zipfile](https://github.com/rstudio/bookdown/files/595478/issue_parts_pdf.zip)) of this small RStudio project so that you can reproduce it, and the resulting [pdf-document](https://github.com/rstudio/bookdown/files/595477/_main.pdf) as well. I attached the TeX-file in another [zipfile](https://github.com/rstudio/bookdown/files/595483/texfile.zip).

Also, see the screenshot below.

Note that I have made a cross-reference in the last chapter to _'my first part'_, using [pandoc markdown's auto-identifiers](http://pandoc.org/MANUAL.html#header-identifiers) as I couldn't get this to work with bookdown's cross-referencing style.

What goes wrong is this:

- **'(PART) ...'** appears in the table of contents for both parts. This happens irrespective of cross-referencing to parts or not.
- for parts which are **cross-referenced** in markdown:
    - the page with the numbered part title disappears, and an unnumbered chapter '(PART) ...' is added on a separate page.
    - the numbered part title disappears from the table of contents, while the '(PART) ...' line does not.
    - the numbering of parts does not take into account these parts.
- the **hierarchy** of parts and chapters in the pdf-file is broken when making cross-references to parts (_left side of the screenshot_). The following can happen (only partly visible in the attached case): when a part is inserted that is not cross-referenced (and therefore correctly distinguished), all subsequent _chapters plus cross-referenced parts_ are at the same level, below the level of the not-cross-referenced part.

In the meantime I manage to fix these things in TeX, but of course that is a manual step that does not survive new runs (and I also maintain HTML output from the same Rmd project).

BTW, thanks a lot for the bookdown package, it makes rmarkdown much more convenient for writing longer reports!

This is the output of `sessionInfo()`:
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04 LTS

locale:
 [1] LC_CTYPE=nl_BE.UTF-8       LC_NUMERIC=C               LC_TIME=nl_BE.UTF-8       
 [4] LC_COLLATE=nl_BE.UTF-8     LC_MONETARY=nl_BE.UTF-8    LC_MESSAGES=nl_BE.UTF-8   
 [7] LC_PAPER=nl_BE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=nl_BE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     bookdown_0.2    digest_0.6.10   assertthat_0.1  mime_0.5       
 [6] R6_2.2.0        xtable_1.8-2    magrittr_1.5    evaluate_0.10   stringi_1.1.2  
[11] miniUI_0.1.1    fortunes_1.5-3  rmarkdown_1.1   tools_3.3.2     stringr_1.1.0  
[16] shiny_0.14.2    rsconnect_0.5   httpuv_1.3.3    yaml_2.1.14     htmltools_0.3.5
[21] knitr_1.15.1    tibble_1.2     
```

![screenshot](https://cloud.githubusercontent.com/assets/19164640/20359523/8eadc6a6-ac30-11e6-90dc-58751d8f1b9d.png)

**Comment by yihui** [comment]
Thanks for the report! I have pushed a fix, but it still requires you to make a change in Rmd from

    See [first part](#part-my-first-part)!

to

    See Part \@ref(part-my-first-part)!

If you don't like this, I can reconsider a deeper fix.

**Comment by florisvdh** [comment]
This works! Indeed, self-made hyperlinks to parts are not allowed at the moment, or all the above problems will return. But it's OK for me; thanks a lot for the fix!
