### ISSUE TITLE
Arrow navigation stops working after switching input method

### ISSUE THREAD

**Issue by junchenfeng** [rstudio/bookdown#244]
The arrow navigation stops working for the edit area of Rstudio when in bookdown project after I switch the input methods using the keyboard shortcut "win+blank", which I assume is the default on win10.

**Comment by yihui** [comment]
What are your versions of RStudio and bookdown? Do you mean pressing Left/Right keys on your keyboard does not work, or clicking the left/right buttons on the page?

**Comment by junchenfeng** [comment]
I mean left/right keys on my keyboard.

Rstudio 1.0.44
bookdown 0.1.16

**Comment by yihui** [comment]
Does the addin `Preview Book` work?

**Comment by junchenfeng** [comment]
Yes, it works. And the bug goes away when in the preview mode.

**Comment by yihui** [comment]
Personally I think this addin is more convenient than the Build button. If it works for you, I'd just recommend you to use it.
