### ISSUE TITLE
Cross-referencing appendices in HTML gives a next chapter number instead of A-B-C-...

### ISSUE THREAD

**Issue by florisvdh** [rstudio/bookdown#245]
E.g. `see appendix \@ref(my-unique-appendix-label)` results in:
see appendix 12
(if there are 11 chapters/appendices before it).

At least I have this with html_document2.

The problem is not present in PDF (where you get "see appendix A" for example).

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by florisvdh** [comment]
Works wonderful, thank you!
