### ISSUE TITLE
Part titles of more than 20 characters are problematic in PDF

### ISSUE THREAD

**Issue by florisvdh** [rstudio/bookdown#246]
Some of the problems of issue #243 arise in PDF output when a part title has more than 20 characters. See the screenshot below of the TOC (second and third part). I attached an [RStudio project](https://github.com/rstudio/bookdown/files/604103/bookdowntest.zip) to reproduce this, including the `_book` folder with PDF and TEX file.

- part title with > 20 characters and at least one space:
    - TOC: a numbered part title and a (PART) title appear separately.
- part title is one word of >20 characters (so: no spaces):
    - TOC: no numbered part title, but a (PART) title instead.
    - pdf structure (left side of screenshot): the 3rd part has become part of part 2.
    - the separate numbered part title page in the document is replaced by a separate page with the (PART) title instead.

In HTML output, everything works fine!

![Screenshot:](https://cloud.githubusercontent.com/assets/19164640/20489939/9e9c679a-b00c-11e6-980f-2805ce4ae9c0.png)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by florisvdh** [comment]
Thank you very much, this works fine now!
