### ISSUE TITLE
"bookdown.sty not found" error when trying to make pdf

### ISSUE THREAD

**Issue by ccolonescu** [rstudio/bookdown#247]
I have updated R, RStudio and bookdown and now I get this error when trying to make pdf. Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/10256096/20491755/9ebe499c-afcf-11e6-9b72-c22a8d1af568.png)
I would appreciate any suggestions.
Constantin

**Comment by yihui** [comment]
Search in your project for `\usepackage{bookdown}` and delete it. It is probably in `preamble.tex`. I don't know how it ended up there, but bookdown is not a LaTeX package.

**Comment by ccolonescu** [comment]
Thanks! It works now.
