### ISSUE TITLE
how to add example caption

### ISSUE THREAD

**Issue by snowhyzhang** [rstudio/bookdown#252]
Hello @yihui 

I read "Authoring Books with R Markdown", but I just find adding caption to figures and tables. Is there a way to add caption to an example just like figures and tables something like ex.cap?

For example, I am writing an R code block
```{r, echo = TRUE, eval = FALSE}
x <- 1
y <- 1
x + y
```
I'd like to add a caption like "Example 1.1 An example code" so that it will be put under the code.

**Comment by yihui** [comment]
Why not use the example environment? Section 2.2.2: https://bookdown.org/yihui/bookdown/

**Comment by snowhyzhang** [comment]
OK, I got it. 
thank you!
