### ISSUE TITLE
Only number section headers until a certain level

### ISSUE THREAD

**Issue by aryamanarora** [rstudio/bookdown#253]
Is their any way I can number only up to third-level headers (without manually adding `{-}`)?

This would be numbered:

```markdown
# A
Lorem ipsum.
## B
### C
Some text.
```

but this wouldn't:

```markdown
#### D
##### E
Too many numbers are bad.
```

Thanks in advance.

**Comment by yihui** [comment]
Sorry, I'm not aware of a way. Normally we can only support what Pandoc supports, and this feature does not seem to be present in Pandoc: http://pandoc.org/MANUAL.html So you have to either use `{-}`, or write a certain pre-processing function to add `{-}` automatically to these headers.
