### ISSUE TITLE
search dialog UI is a bit too minimal

### ISSUE THREAD

**Issue by kevinushey** [rstudio/bookdown#254]
I'm not sure how much control `bookdown` has over the Git pages styling, but wanted to file just in case. To reproduce:

1. Open a Git book (e.g. https://bookdown.org/yihui/bookdown),
2. Initiate a search (click the magnifying glass),
3. Press the spacebar (e.g. as though you were searching for a single space),
4. Click the main page (unfocus the search dialog).

The left sidebar is now empty without any real indication of why.

<img width="1440" alt="screen shot 2016-11-28 at 10 55 34 am" src="https://cloud.githubusercontent.com/assets/1976582/20681630/45a47270-b559-11e6-830f-6e843e2b0cba.png">

Note that since Gitbooks seems to remember the last search term used, if you refresh the page you should then see the same UI, making it a bit more confusing in that case.

It seems like the search dialog here should get a bit of minimal styling (e.g. an magnifying glass on the right + a background)?

**Comment by yihui** [comment]
Good point. Thanks! I'll add some styling.
