### ISSUE TITLE
Figure numbers in PDF-output with parts can be wrong

### ISSUE THREAD

**Issue by florisvdh** [rstudio/bookdown#256]
Sometimes it is convenient to put some text after a (PART) title, and before the chapter title:

```
(PART) Title of second part

Here comes a little bit explanation on the part itself. And sometimes, with a figure.

![Figure caption](filename.png)

# Title of my fourth chapter in the book
```

When a figure is inserted in that piece of text, HTML output will reference it as figure **II.1** in the above example, which is convenient. However, PDF output uses the number of the _previous_ chapter as the prefix; **3.x** in this example (x being the xth figure from chapter 3). This would better be avoided; the HTML approach seems most logical.

I attached an [RStudio project](https://github.com/rstudio/bookdown/files/621299/bookdowntest.zip) to reproduce this (zip file, also containing pdf and tex in the _book folder).

**Comment by yihui** [comment]
I'm afraid you will have to look for a LaTeX solution, since figure numbers are generated by LaTeX. All bookdown does is to replace `\@ref(label)` with `\ref{label}`. Bookdown only renders the actual numbers for non-LaTeX output.

**Comment by florisvdh** [comment]
Just for the record. A workaround for this case is not to use chapter prefixes for figure numbers in LaTeX. This can be [accomplished](https://tex.stackexchange.com/questions/28333/continuous-v-per-chapter-section-numbering-of-figures-tables-and-other-docume#28334) by putting the following in the preamble:

```
\usepackage{chngcntr}
\counterwithout{figure}{chapter}
```
