### ISSUE TITLE
Provide an RStudio add-in to help manage cross-references

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown#26]
just like the LyX panel that allows you to choose a reference key interactively

<img width="1019" alt="screen shot 2016-02-19 at 11 59 45 am" src="https://cloud.githubusercontent.com/assets/163582/13184243/520ab840-d700-11e5-84ab-fe0fd6ed42d1.png">

Similar thing for citations.

**Comment by crsh** [comment]
Yes! This would be a really nice feature. There is also an [open feature request](https://support.rstudio.com/hc/en-us/community/posts/202160258-Tab-autocompletion-of-bibtex-references) at RStudio for an auto-complete variant of this.

**Comment by ismayc** [comment]
Does this solve this issue?  https://cran.r-project.org/web/packages/citr/index.html

**Comment by yihui** [comment]
@ismayc Almost. I just filed an issue https://github.com/crsh/citr/issues/7 When that is done, I think it will be perfect. Thanks!

**Comment by crsh** [comment]
FYI: The new version of `citr` was just released on CRAN; binaries should be available soon.

**Comment by yihui** [comment]
Perfect. Thanks!
