### ISSUE TITLE
Error in figure chunk with plotly object

### ISSUE THREAD

**Issue by augustoamerico** [rstudio/bookdown#264]
First of all, I'm not sure if I should post this here or in webshot repo.

When I compile the bookdown project, the gitbook site is OK with no errors. But when the compile is to LaTex there is a error from the webshoot screenshot.

The error is:
`PHANTOM ERROR: CasperError: No element matching selector found: .plot-container.plotly`

As is states, it can't find the selector that I've had defined.

In the gitbook site, the widget has a wrapper div with those classes.

Maybe an issue of delay? I setted the webshoot delay to 20 seconds and still had the same error. In the gitbook site it takes like 4/5 seconds for the widget to load.

Maybe the image doesn't have those classes at knitr-to-latex compile time? Well, i've setted the selector to NULL and there is no error, but the screenshot is just a blank screen.

I know that I can use `screenshot.alt`, but for the next month it would be better if I used the screenshot of the widget (less maintenance needed).

What are the images? The images are plotly objects. Actually there are two kind of images that raises this behaviours:

- Plotly object with the plot type = "box"
- Plotly object with the plot type = "scatter" and marker colors with continuous values

A minimal example where I can find the stated behaviour:

    ---
    title: "Untitled"
    author: "Tiago dos Santos"
    date: "12/10/2016"
    output: bookdown::pdf_document2
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = T)
    ```
    
    ```{r data-setup, include=T, echo=F}
    
    dfs <- data.frame(
      x = rnorm(10),
      y = rnorm(10),
      z = rnorm(10)
    )
    
    case1 <- plotly::plot_ly(dfs, y = ~y, type="box")
    case2 <- plotly::plot_ly(dfs, x = ~x, y = ~y, type="scatter", mode="markers", marker=list(color = ~z)) 
    
    ```
    ## R Markdown
    
    ```{r fig-1, fig.cap = "This is an example", screenshot.opts = list(delay = 30)}
    case1
    ```
    
    ```{r fig-2, fig.cap = "This is another example", screenshot.opts = list(delay = 30)}
    case2
    ```

How can I understand what's happening? Any way to look for the phatonJS logs? Maybe a bookdown/webshot/plotly bug or incompatibility?

**Comment by yihui** [comment]
I don't know what the error message means. I wonder if @cpsievert has any ideas here.

**Comment by cpsievert** [comment]
Yea, I ran into this problem quite a bit, and resorted to manual screenshots via `screenshot.alt`.

If @etpinard would like, I could produce minimal example(s) for the plotly.js repo, but only if he sees it as worthwhile to support phantomjs

**Comment by yihui** [comment]
@cpsievert Is it possible to convert a plotly plot to PNG with command line instead of clicking the button on the plotly toolbar in a web browser?

**Comment by augustoamerico** [comment]
That command line plot to PNG approach would be pretty useful @yihui ! I think the plotly::export does exactly that! Gonna try this!

**Comment by yihui** [comment]
@augustoamerico If that works, I think it makes sense for the plotly package to extend its `knit_print` method for cases when the output format is not HTML.

**Comment by cpsievert** [comment]
`plotly::export()` actually uses **webshot**, just like **bookdown** does, so that probably solve anything.

I have a feeling the best approach is to use `htmlwidgets::onRender()` to call the `Plotly.downloadImage` plotly.js function on the widget after it renders in a real browser. I'll transfer this issue to plotly so I don't forget.

**Comment by cpsievert** [comment]
For posterity, I think the problem here is a missing TypedArray polyfill...it should work now.
