### ISSUE TITLE
bookdown::render_book warning msg

### ISSUE THREAD

**Issue by landge** [rstudio/bookdown#268]
Hi,

when I run bookdown::render_book("index.Rmd", "bookdown::gitbook") I get the following warning

```
processing file: 

Output created: _book/_main.html
[1] "/home/landge/Nor-coast-scoringer/_book/_main.html"
Warning messages:
1: In normalizePath(f1, ...) :
  path[1]="_main.html": No such file or directory
2: In file.remove(output) :
  cannot remove file '_main.html', reason 'No such file or directory'
```

I have set the output_dir in the index.Rmd to _book.
This warning doesn't seem to effect the rendering so maybe it should just be ignored?

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
