### ISSUE TITLE
Equation labeling requires pandoc >= 1.17.2

### ISSUE THREAD

**Issue by aoles** [rstudio/bookdown#269]
According to my testing, equation labeling as [described in the bookdown book](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations) requires pandoc >= 1.17.2. With version 1.17.1 I get the following.

```
---
output: bookdown::html_document2
---

\begin{equation}
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}
```
<img width="264" alt="Equation" src="https://cloud.githubusercontent.com/assets/6545356/21147755/5acdfeb0-c156-11e6-994f-6b8d67ce8a04.png">

----
Therefore, you might consider adding to **DESCRIPTION**
```
SystemRequirements: pandoc (>= 1.17.2)
```

Cheers,
Andrzej

**Comment by yihui** [comment]
Added. Thanks!
