### ISSUE TITLE
Malformed remote specification when installing

### ISSUE THREAD

**Issue by ekstroem** [rstudio/bookdown#27]
I'm quite exited about the bookdown project and want to try it out and provide feedback. However, if I try to install bookdown either by cloning and installing the repository and or by running 

```{r}
devtools::install_github("rstudio/bookdown")
```
I get the error message
```
Installing bookdown
Error: Malformed remote specification 'rstudio/rmarkdown'
```

Installing the github version of `rstudio/rmarkdown` doesn't really fix it. Is there anything I can do to get it up and running?

**Comment by jjallaire** [comment]
I think if you install the latest version of devtools from CRAN then
re-install bookdown from GitHub things will work

**Comment by ekstroem** [comment]
Yup. Works with devtools 1.10.0. Thank you

**Comment by whizzalan** [comment]
> packageVersion("devtools")
[1] ‘1.9.1’ 
It works on devtools 1.10.0. Thanks.
