### ISSUE TITLE
epub output and \begin{align} \end{align} adds $$...$$ resulting in incorrect output

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#270]
Greetings,

Latest version of all packages, R, RStudio etc. 

Very impressed with the state of the project. Generating perfect PDF and HTML output, but noticed that the conversion to epub barfs when using \begin{align} \end{align} though PDF and HTML work as expected. Here is the result... it appears to introduce $$...$$ that throws things off.

“A consequence of stationarity is that the means, variances, and covariances of the series are time invariant i.e. do not depend on 
t
. $$\begin{align} E[y_t]&=\mu_y\cr V[y_t]&=E[(y_t-\mu_y)^2]=\sigma^2_y\cr C[y_t,y_{t+k}]&=E[(y_t-\mu_y)(y_{t+k}-\mu_y)]=\gamma_k \end{align}$$

”
Excerpt From: Jeffrey S. Racine. “ECON 762 - Winter 2017.” iBooks. 

Thanks!

**Comment by yihui** [comment]
Short answer: none of the math environments except the `equation` environment currently work for EPUB output if you use iBooks. If you want to see them, you have to use a different reader with better math support, such as Calibre: https://calibre-ebook.com

Longer story: https://github.com/jgm/pandoc/issues/2758#issuecomment-215628804

**Comment by JeffreyRacine** [comment]
Many thanks, this is most helpful
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Thursday, January 5, 2017 at 00:32
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [rstudio/bookdown] epub output and begin{align} end{align} adds $$...$$ resulting in incorrect output (#270)


 

Short answer: none of the math environments except the equation environment currently work for EPUB output if you use iBooks. If you want to see them, you have to use a different reader with better math
 support, such as Calibre: https://calibre-ebook.com
Longer story: 
jgm/pandoc#2758 (comment)
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
