### ISSUE TITLE
Extra files generated from within knitr::knit_print

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/bookdown#271]
I'm developing a pacakge 'widgetframe' https://github.com/bhaskarvk/widgetframe, which allows you to wrap a widget inside an iframe. This could come really handy for bookdown to make sure that the book's CSS/JS don't interfere with the widget's CSS/JS. 

The basic idea is very simple, If you have something like below in your R markdown say 'example01.Rmd'...
<pre>
```{r w01}
widgetframe::frameWidget(leaflet::leaflet()))
```
</pre>

Then when you knit this markdown it will result in two files, example01.html and widgets_w01.html. The example01.html will contain an iframe whose src attribute is 'widget_w01.html' and widgets_w01.html will contain the leaflet widget. This way the widget is displayed inside an iFrame and thus unaffected by the style used by the Rmd.

This works very well for a stand alone Rmd file, but in case of bookdown, the `widgets_w01.html` is not moved to the book dir (_book by default). Is is possible to move all generated HTML artifacts from a knitting operation?

Or alternatively is there a way to somehow override bookdown's behavior in my package so that I can move the widget HTML files when the book is rendered?

**Comment by yihui** [comment]
From the Pym.js doc:

> Starting on v1.1.0 you can pass configuration parameters as HTML data attributes by just prefixing the parent configuration parameter with data-pym-. 

Perhaps you can define a function `widgetframe_html` in your package to generate a custom div like

```html
<div data-pym-src="child.html" data-pym-allowfullscreen></div>
```

instead of using the default container of htmlwidgets: https://github.com/ramnathv/htmlwidgets/blob/master/R/htmlwidgets.R#L219

Then bookdown will look for `src="..."` and recognize the external file to be copied.

**Comment by bhaskarvk** [comment]
Thanks @yihui . Unfortunately that might not be possible because the child HTML name is dynamically generated based on the chunk label, so not known in advance, and there is no way to pass that name to the custom `<widgetname>_html` function. But I might just use a make file that'll copy over the widget HTMLs.

**Comment by yihui** [comment]
Okay, then please see if you are able to get the text `src="???.html"` into the output. It can be in an HTML comment. That will be a hint for bookdown to know this .html file needs to be copied.

If that turns out be too hard (e.g. takes you more than an hour), I can consider solving this problem in a different way.

**Comment by bhaskarvk** [comment]
Hi Yihui,

I was able to insert an HTML comment in the parent HTML with `widget-href='childwidget.html'` which results in successful copy over of the childwidget.html file into the book directory. But there are two issues.

a) The files are copied over and not moved. So I end up with two copies of the childWidget.html files one in the parent directory along with the `*.Rmd` files, and the second in the `_book` directory. The ideal solution is for the files to be moved.

b) As per your suggestion at RsutdioConf I now determine whether to self_contain the childWidget.html using a new chunk option `self_contained_widgetframes`, which works very well, but when this is `FALSE` (the default), the resulting `widgets_lib` folder which contains the JS/CSS libs for the child widgets is not copied/moved over. So even after having the `widget-href='childwidget.html'` it only works if the child widgets are self_contained, which is not really ideal. I also added `libs-href='widget_libs'` as a hack to trigger copying over of this folder but the 'widget_libs' folder is not copied over. I think the check is only for files and not directories.

so a) The local files should be moved and not copied to avoid duplicates, and it should also move any directories and not just files.

**Comment by yihui** [comment]
I don't have a good solution at the moment, and I don't have time, either. I'll reopen this issue and think about it again when I have a chance. Thanks!

**Comment by bhaskarvk** [comment]
Hi Yihui, 
Any chance you could revisit this issue & the related rstudio/blogdown#28 ? I would like to push widgetframe to CRAN, but w/o proper support for bookdown and blogdown, it kind of is limited to RMarkdown docs/slides.

**Comment by yihui** [comment]
This is an important issue to solve but unfortunately I don't have enough time to come up with a proper solution. If you really want to push to CRAN, you can state the limitation in the documentation, and ask users to wait for the next version. Sorry.

**Comment by bhaskarvk** [comment]
I have more or less solved this issue. It does require a manual step of copying the child widgets directory to the final folder, but it's easily solvable using a Makefile.

So see widgetframe + bookdown in action 
See https://rawgit.com/bhaskarvk/widgetframe/master/inst/examples/bookdown/book/index.html

And the code
https://github.com/bhaskarvk/widgetframe/tree/master/inst/examples/bookdown

I am happy with this solution, but if possible, it would also be nice to have pre and post book scripts just like pre and post chapter scripts. Then I won't even need a Makefile.
