### ISSUE TITLE
bookdown::word_document2 --> Error: pandoc document conversion failed with error 139

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/bookdown#273]
I have an issue with a document that is processed fine when using (from within RStudio preview on Debian Linux)  `bookdown::pdf_document2`, yet when using `bookdown::word_document2`, I get:

    /usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS manuscript.utf8.md --to docx --from 
    markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output manuscript.docx 
    --highlight-style tango --bibliography flippant.bib --filter /usr/lib/rstudio/bin/pandoc/pandoc-citeproc 
    Segmentation fault
    Error: pandoc document conversion failed with error 139
    In addition: There were 50 or more warnings (use warnings() to see the first 50)
    Execution halted

I'm at a loss as to where to start debugging this. Where to start?

Sincerely, Joh

**Comment by yihui** [comment]
segfault from Pandoc is probably not easy to debug. In the R console, `rmarkdown::render('manuscript.Rmd', 'bookdown::word_document2')`, and see if you find anything meaningful from `warnings()`.

**Comment by r-cheologist** [comment]
Hmm ... the segfault persists, but 'warnings' doesn't give anything of interest (all R related).

Is there a way to get rmarkdown/bookdown to spit out the `manuscript.utf8.md` referred to in the error, so I can fall back to the command line?

**Comment by r-cheologist** [comment]
Thank you that helped indeed ... when I use above pandoc call on the CLI it fails with a segfault. HOWEVER, if I fall back to my system's pandoc (debian, pandoc, version both 1.17.2), everything works. What's wrong with rstudio's version?

**Comment by yihui** [comment]
I have no idea... Currently the only ways to avoid RStudio's pandocs are: 1) install a higher version of Pandoc (https://github.com/jgm/pandoc/releases), or 2) render the book outside RStudio.

**Comment by kevinushey** [comment]
You might be able to force RStudio to ignore its own bundled pandoc by setting the environment variable `RSTUDIO_PANDOC` to an empty value; you might need to do this in e.g. `~/.Rprofile` or `~/.Renviron` or a similar startup file. (haven't tested but in theory should work?)
