### ISSUE TITLE
Using `\@ref(fig:XXX)` within R code blocks?

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/bookdown#274]
In a situation like so:

    ```{r fake-call eval=FALSE}
    # A plot looks like this (Figure 1)
    plot(1,1)
    ```
    
    ```{r actual-call fig.cap="Something", echo = FALSE}
    # Here the actual (formatted plotting is done)
    plot(1,1)
    ```

where the first block shows basic usage of a function and the second block enables an elaborated on output, I would like to be able to replace `Figure 1` with `Figure \@ref(fig:actual-call)` ... is that possible somehow yet?

Sincerely, Joh

**Comment by yihui** [comment]
No, it is not possible. Sorry. The reference has to be outside of code chunks. I don't think it is a bad idea in your case to move the comment to a paragraph outside like this:

    A plot looks like this (Figure \@ref(fig:actual-call)).
    
    ```{r fake-call eval=FALSE}
    plot(1,1)
    ```
    
    ```{r actual-call fig.cap="Something", echo = FALSE}
    # Here the actual (formatted plotting is done)
    plot(1,1)
    ```
