### ISSUE TITLE
gitbook and tikzDevice... firefox, chrome don't display images, safari does...

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#275]
Greetings,

Some perplexing issues... take the minimal book example, compile gitbook, view in browser on Mac 10.12.2, latest versions of all packages, browsers etc. The issue lies with generating figures (Introduction "Figure 2.1: Here is a nice figure! "). 

The default image format (png) is viewable in all browsers on my system. Ditto for adding dev: pdf (works with all). But add dev: tikz and the image displays when viewed in safari but not firefox, chrome etc. I checked the pdf produced and dev: pdf produces a PDF-1.4 pdf while dev: tikz produces a PDF-1.5 pdf, but that is the only difference I can see.

Hopefully you can reproduce... I scoured the web for issues with firefox and chrome and didn't find anything that resolved the issue...

[minimal.zip](https://github.com/rstudio/bookdown/files/659447/minimal.zip)

And, of course, thanks for your incredible contributions!

Thanks!

**Comment by yihui** [comment]
I won't be surprised if PDF images do not work for certain web browsers. I'd suggest you convert PDF to PNG (or SVG/JPEG) when the output format is not LaTeX. There are two tools you can use: the [chunk option](http://yihui.name/knitr/options/) `fig.process` and ImageMagick or the R package **magick** (or other image processing tools).

Not tested:

```r
knitr::opts_hooks$set(dev = function(options) {
  if (identical(options$dev, 'tikz') && !knitr:::is_latex_output()) {
    options$fig.process = function(x) {
      if (!grepl('[.]pdf$', x)) return(x) 
      x2 = sub('pdf$', 'png', x)
      magick::image_write(magick::image_read(x), x2, format = 'png')
      x2
    }
  }
  options
})
```

**Comment by JeffreyRacine** [comment]
Many thanks, will give it a try.
 
Jeff
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Saturday, December 31, 2016 at 01:14
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [rstudio/bookdown] gitbook and tikzDevice... firefox, chrome don't display images, safari does... (#275)


 

I won't be surprised if PDF images do not work for certain web browsers. I'd suggest you convert PDF to PNG (or SVG/JPEG) when the output format is not LaTeX. There are two tools you can use: the
chunk option fig.process and ImageMagick or the R package
magick (or other image processing tools).
Not tested:

knitr::opts_hooks$set(dev = function(options) {
  if (identical(options$dev, 'tikz') && !knitr:::is_latex_output()) {
    options$fig.process = function(x) {
      if (!grepl('[.]pdf$', x)) return(x) 
      x2 = sub('pdf$', 'png', x)
      magick::image_write(magick::image_read(x), x2, format = 'png')
      x2
    }
  }
  options
})

—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by JeffreyRacine** [comment]
Works like a charm, thanks!
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Saturday, December 31, 2016 at 01:14
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [rstudio/bookdown] gitbook and tikzDevice... firefox, chrome don't display images, safari does... (#275)


 

I won't be surprised if PDF images do not work for certain web browsers. I'd suggest you convert PDF to PNG (or SVG/JPEG) when the output format is not LaTeX. There are two tools you can use: the
chunk option fig.process and ImageMagick or the R package
magick (or other image processing tools).
Not tested:

knitr::opts_hooks$set(dev = function(options) {
  if (identical(options$dev, 'tikz') && !knitr:::is_latex_output()) {
    options$fig.process = function(x) {
      if (!grepl('[.]pdf$', x)) return(x) 
      x2 = sub('pdf$', 'png', x)
      magick::image_write(magick::image_read(x), x2, format = 'png')
      x2
    }
  }
  options
})

—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by JeffreyRacine** [comment]
Greetings Yihui,

It appears that even with cache=TRUE set globally, when compiling for gitbook using this workaround, caching is bypassed which adds a painful amount of time when compiling my project. By chance can you think of an option that might re-enable caching?

Thanks!

**Comment by JeffreyRacine** [comment]
Followup on this (no need to reply, but perhaps of help to others).

I had included this chunk in  `{r global_options, cache=FALSE}` and when I placed it in a separate chunk with `cache=TRUE` all is well.

So thanks again and perhaps someone using this can benefit from this tip.
