### ISSUE TITLE
gitbook's split_by Error

### ISSUE THREAD

**Issue by shadowwalker2718** [rstudio/bookdown#276]
I tried to assign the split_by in bookdown::gitbook function with value `c('section+number', 'section', 'chapter+number', 'chapter', 'rmd', 'none')`, but always got error as follows:

Error in match.arg(split_by) : 'arg' must be of length 1

How can I fix this to make gitbook generate multiple pages for one Rmd and at the same time use everything provided by gitbook(highlight/search...)?

**Comment by shadowwalker2718** [comment]
最近很冷清，rstudio更新也慢了好多，是不是公司发生什么事情了啊

**Comment by shrektan** [comment]
有吗？在做新的事情啊，包括r-pkgs这些~ 有种要把R做为Programming Language的基础工作彻底清理一遍的感脚。

**Comment by shadowwalker2718** [comment]
@shrektan 这么牛逼啊。
![image](https://cloud.githubusercontent.com/assets/16947948/21419365/2a27932a-c7f5-11e6-871f-028ac91049c9.png)
帮我看看上面那问题咋整?

**Comment by yihui** [comment]
给个具体的例子看看你到底做了什么。split_by 只能是长度为1的单值，不能是一个长度大于1的向量。
