### ISSUE TITLE
bookdown PDF table renders incorrectly

### ISSUE THREAD

**Issue by dietrichson** [rstudio/bookdown#281]
Compare:
![screen shot 2016-12-23 at 6 08 00 pm](https://cloud.githubusercontent.com/assets/2222669/21462409/ce718b98-c93a-11e6-817a-88af848ac91c.png)

to
![screen shot 2016-12-23 at 6 09 02 pm](https://cloud.githubusercontent.com/assets/2222669/21462420/f3fc3de0-c93a-11e6-84f1-60f9f1ed8595.png)

The first rendered with 
    ---
    title: "Test document"
    output:
         rmarkdown::pdf_document
    ---

The second with 
    ---
    title: "Test document"
    output:
         bookdown::pdf_document2
    ---

**Comment by dietrichson** [comment]
calling knitr with 
booktabs = TRUE
resolved the issue.

**Comment by dietrichson** [comment]
calling knitr::kable with 
booktabs = TRUE
resolved the problem

**Comment by mikey-harper** [comment]
Is there a reason that `booktabs = TRUE` is not automatically included? I feel it would be best if the output of `pdf_document` and `pdf_document2` are the same, as this seems to be an unintended side-effect.

[The book](https://bookdown.org/yihui/bookdown/tables.html) does say "some internal tricks in knitr to make it work with bookdown and users do not have to know anything about these implementation details", so I imagine this change is default formatting has something to do with this.
