### ISSUE TITLE
How to compile the book more efficiently

### ISSUE THREAD

**Issue by shadowwalker2718** [rstudio/bookdown#282]
Now my book grows larger and larger. But whenever i change a tiny part, i have to recompile the whole book. How can i just render one file?

**Comment by shadowwalker2718** [comment]
anybody here?

**Comment by znmeb** [comment]
If you're in RStudio, open the chapter in the editor and press the "Knit" button. It will render just that chapter.

**Comment by shadowwalker2718** [comment]
I always got the following errors:
```
) (/usr/share/texlive/texmf-dist/tex/latex/breakurl/breakurl.sty
Package: breakurl 2013/04/10 v1.40 Breakable hyperref URLs
\burl@toks=\toks30
! Undefined control sequence.
<argument> \headerps@out 
                         {/burl@stx null def /BU.S { /burl@stx null def } de...
l.311 }```

If I run `bookdown::render_book('index.Rmd', 'bookdown::gitbook')`, it works well. But it will render the whole book.

**Comment by shadowwalker2718** [comment]
i have Chinese characters in my Rmd files. It looks that is the root cause. But it is very frustrating.

**Comment by znmeb** [comment]
@shadowwalker2718 do you have TeXLive XeLaTeX installed? Does your RStudio project point to XeLaTeX for PDF generation?

**Comment by shadowwalker2718** [comment]
yes, i have them all. but the question at the first place is why does it generate pdf? I just want to generate HTML pages. Even if I just click `knit html`, i will get this pdf related error. Why?

**Comment by yihui** [comment]
Please provide a minimal, self-contained, and reproducible example. If I were to guess, the first output format in your index.Rmd or _output.yml may be a PDF format.

Personally I don't click any buttons myself when I write a book. I always use the addin Preview Book: https://bookdown.org/yihui/bookdown/rstudio-ide.html I only click the Build buttons only when I need PDF.

Chinese characters are slightly trickier to deal with. I have a separate example here: https://github.com/yihui/bookdown-chinese
