### ISSUE TITLE
Maths in tables

### ISSUE THREAD

**Issue by robjhyndman** [rstudio/bookdown#285]
LaTeX syntax within `knitr::kable` tables is not being processed using `bookdown::pdf_book`. It works fine with `rmarkdown::pdf_book`. A minimal reproducible example is here: 
[test.txt](https://github.com/rstudio/bookdown/files/681818/test.txt)

(Named `test.txt` to satisfy github attachment rules. Rename to `test.Rmd`)

**Comment by yihui** [comment]
The short answer is `kable(..., format = 'pandoc')`, but here is a longer story about the caveat: http://tex.stackexchange.com/q/276699/9128 `kable()` produces LaTeX tables by default for the LaTeX output of bookdown because of this issue.
