### ISSUE TITLE
add space between R code blocks and text in html output

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/bookdown#286]
Question:

I am trying to add some space between text and code blocks in the HTML output. I added the following to `p.caption` in the `style.css` file, and it adds space after figure captions.

```
p.caption {
  color: #777;
  margin-top: 10px;
  padding: 0px 0px 40px 0px;
}
```
Now I'd like to add space before figures included via:

`knitr::include_graphics(rep("images/knit-logo.png",` 3))`

and before/after all code blocks.

ps. [posted to SO](http://stackoverflow.com/questions/41432013/add-space-between-r-code-blocks-and-text-in-bookdown-for-html-output) first, but did not generate much interest.

**Comment by yihui** [comment]
Always include the tag `r` if it is an R-related question. That will gain more attention. `r` is a much bigger world than `bookdown`.
