### ISSUE TITLE
Error: Failed to compile *.tex

### ISSUE THREAD

**Issue by meefen** [rstudio/bookdown#287]
I was running `bookdown::publish_book(name = "foo", account = "bar", render = "server")` to publish a draft book and ran into the following error. Execution halted at the pandoc line and there was a warning about latexmk. Any suggestions?

> 2017/01/03 21:21:48.353203906 /opt/rstudio-connect/ext/pandoc/pandoc +RTS -K512m -RTS snaEd.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output snaEd.tex --table-of-contents --toc-depth 2 --template /opt/rstudio-connect/mnt/packrat/3.2.4/v2/library/rmarkdown/d8f0cf248116dbdfc23f35991d0ed3f7/rmarkdown/rmd/latex/default-1.17.0.2.tex --number-sections --highlight-style tango --latex-engine xelatex --natbib --include-in-header preamble.tex --variable graphics=yes --variable 'geometry:margin=1in' --variable tables=yes --standalone --bibliography biblio.bib --bibliography packages.bib
2017/01/03 21:21:49.356402664 Error: Failed to compile snaEd.tex.
2017/01/03 21:21:49.356480568 In addition: Warning message:
2017/01/03 21:21:49.356510190 Your latexmk version seems to be too low. You may need to update the latexmk package or your LaTeX distribution.
2017/01/03 21:21:49.358394521 Execution halted
2017/01/03 21:21:49.352719665
2017/01/03 21:21:49.352731335 Latexmk, John Collins, 7 May 2011. Version 4.24
Site deployment failed with error: exit status 1

Tex Live version is current (i.e., 2016).

> $ latexmk -v
Latexmk, John Collins, 22 April 2016. Version 4.45

Session Info:

> \> devtools::session_info('bookdown')
Session info --------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       America/Chicago             
 date     2017-01-03                  
Packages ------------------------------------------------------------------------------
 package     * version  date       source                           
 backports     1.0.4    2016-10-24 CRAN (R 3.2.2)                   
 base64enc     0.1-3    2015-07-28 CRAN (R 3.2.0)                   
 bitops        1.0-6    2013-08-17 CRAN (R 3.2.0)                   
 bookdown      0.1.16   2016-10-15 Github (rstudio/bookdown@867a774)
 caTools       1.17.1   2014-09-10 CRAN (R 3.2.0)                   
 digest        0.6.10   2016-08-02 CRAN (R 3.2.5)                   
 evaluate      0.10     2016-10-11 CRAN (R 3.2.5)                   
 highr         0.6      2016-05-09 CRAN (R 3.2.5)                   
 htmltools     0.3.5    2016-03-21 CRAN (R 3.2.4)                   
 httpuv        1.3.3    2015-08-04 CRAN (R 3.2.0)                   
 jsonlite      1.1      2016-09-14 CRAN (R 3.2.5)                   
 knitr         1.14.11  2016-10-15 Github (yihui/knitr@9aa7c9b)     
 magrittr      1.5      2014-11-22 CRAN (R 3.2.0)                   
 markdown      0.7.7    2015-04-22 CRAN (R 3.2.0)                   
 mime          0.5      2016-07-07 CRAN (R 3.2.5)                   
 miniUI        0.1.1    2016-01-15 CRAN (R 3.2.3)                   
 packrat       0.4.8-1  2016-09-07 CRAN (R 3.2.5)                   
 PKI           0.1-3    2015-07-28 CRAN (R 3.2.0)                   
 R6            2.1.2    2016-01-26 CRAN (R 3.2.3)                   
 Rcpp          0.12.7   2016-09-05 CRAN (R 3.2.5)                   
 RCurl         1.95-4.8 2016-03-01 CRAN (R 3.2.4)                   
 RJSONIO       1.3-0    2014-07-28 CRAN (R 3.2.0)                   
 rmarkdown     1.3      2016-12-21 CRAN (R 3.2.2)                   
 rprojroot     1.1      2016-10-29 CRAN (R 3.2.2)                   
 rsconnect     0.4.3    2016-05-02 CRAN (R 3.2.5)                   
 rstudioapi    0.6      2016-06-27 CRAN (R 3.2.5)                   
 shiny         0.14.1   2016-10-05 CRAN (R 3.2.5)                   
 sourcetools   0.1.5    2016-09-15 CRAN (R 3.2.5)                   
 stringi       1.1.2    2016-10-01 CRAN (R 3.2.5)                   
 stringr       1.1.0    2016-08-19 CRAN (R 3.2.5)                   
 xtable        1.8-2    2016-02-05 CRAN (R 3.2.3)                   
 yaml          2.1.13   2014-06-12 CRAN (R 3.2.0)

**Comment by meefen** [comment]
I should have set the `render` parameter to `local`. It fixed the issue. Thanks.

`bookdown::publish_book(name = "foo", account = "bar", render = "local")`

**Comment by yihui** [comment]
You are right. The LaTeX support on bookdown.org is still not good enough. You cannot really build the book on the server side when the output format is PDF. Other output formats should be fine.
