### ISSUE TITLE
Link and preview on bookdown.org?

### ISSUE THREAD

**Issue by Rmadillo** [rstudio/bookdown#289]
Is there a way to have a book included (and linked) in the list under *Books* on the bookdown.org site? I have mine published to RStudio connect and it is open to everyone (https://bookdown.org/Rmadillo/likert/), but it doesn't show up on the Books list.

**Comment by yihui** [comment]
The book list is updated manually (currently by me), and I'll put your book there once I have got time. Thanks!

**Comment by Rmadillo** [comment]
OK, great to know (and sorry you have to do it manually!!!). 

The `bookdown` package has got to be the coolest thing in R land in a long time. Love it! Thanks so much for all your work on it.

**Comment by yihui** [comment]
No worries. It is mostly our problem (the main reason is currently I don't have the data to tell the type of content published to bookdown.org; some users are (ab)using bookdown.org to publish Shiny apps, for example; the other reason is that there are many books that are really skeletons, so I don't want to display them).

**Comment by Rmadillo** [comment]
Thank you!
