### ISSUE TITLE
Include version dep for servr package

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#29]
To make sure you get a version with `httw`

**Comment by yihui** [comment]
Actually I did specify the version in Suggests. I'll release a new version of servr to CRAN soon anyway.

**Comment by hadley** [comment]
Hmmm, weird, I wonder why I didn't get an error message :/

**Comment by yihui** [comment]
I have uploaded a new version of servr to CRAN. Hopefully this will be less confusing to future users.
