### ISSUE TITLE
search button does not bring up search

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/bookdown#290]
Nothing happens when I click the search tool or use F. I believe `search: yes` is the default. Any troubleshooting tips? 

```
bookdown::gitbook:
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">Title</a></li>
      after: |
        <li><a href="http://www.example.com" target="blank">Title</a></li>
bookdown::tufte_html_book:
  css: [style.css, toc.css]
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
bookdown::html_book:
  css: [style.css, toc.css, font-awesome.min.css]
```

**Comment by yihui** [comment]
Anything in the JavaScript console of your web browser? If I can take a look at the book, perhaps I can figure it out by myself.

**Comment by ericpgreen** [comment]
No, I don't see anything.

Thanks for the offer. http://www.designsandmethods.com/ebook/ and
https://github.com/ericpgreen/GHRbook

**Comment by yihui** [comment]
That is really weird. I haven't figured out the reason yet, but I'll take a look next week (sorry I'm very busy this week). In the meantime, could you also test bookdown.org? I'm not sure if it is a server-related issue.

**Comment by ericpgreen** [comment]
Thanks for taking a look. I'll keep trying on bookdown.org. I'm not doing
something right because only the index file is appearing.

**Comment by yihui** [comment]
Not sure how you published your book to bookdown.org. Did you use `bookdown::publish_book()`?

**Comment by ericpgreen** [comment]
I needed to add [`site: bookdown::bookdown_site` to `index.Rmd`](https://github.com/rstudio/bookdown/issues/68) to publish.

I can confirm that I see the same issue when the book is on bookdown. I shared it with you for when you have time to take a peek. Thanks again.

**Comment by yihui** [comment]
It seems this issue has been resolved somehow. I can search in the book now.

**Comment by ericpgreen** [comment]
Thanks. I confirmed it's true. I'm not sure why it's working now and was not before, but this is good news.

**Comment by gitzhuoer** [comment]
I download the zip and build the book in inst/examples folder. However, the search button works fine in Firefox, while doesn't work in chrome. As for Edge, the entire toobar disappears.
