### ISSUE TITLE
```{example} fails unless ```{theorem} exists in document

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#291]
Greetings,

Using the minimal example (index.Rmd below), the following demonstrates the problem. If the environment e.g. ```` ```{theorem}```` does not exist somewhere (it can precede or proceed ```` ```{example}````) in the document then the following error is thrown:

> output file: bookdown-demo.knit.md

> ! LaTeX Error: Environment example undefined.

> Error: Failed to compile bookdown-demo.tex. See bookdown-demo.log for more info.
> Execution halted

> Exited with status 1.

If you compile the code below all is well, remove ```` ```{theorem}  ```` and it fails. Thanks!

    --- 
    title: "A Minimal Book Example"
    author: "Yihui Xie"
    date: "`r Sys.Date()`"
    site: bookdown::bookdown_site
    output: bookdown::gitbook
    documentclass: book
    bibliography: [book.bib, packages.bib]
    biblio-style: apalike
    link-citations: yes
    github-repo: rstudio/bookdown-demo
    description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
    ---
    
    ```{theorem}
    Test
    ```
    
    ```{example}
    Test
    ```

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by JeffreyRacine** [comment]
Thank you!
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Monday, January 9, 2017 at 17:10
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [rstudio/bookdown] ```{example} fails unless ```{theorem} exists in document (#291)


 

Should be fixed now. Thanks for the report!
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by JeffreyRacine** [comment]
Greetings,
 
One thing arises – typically there is paragraph space before the example, but none occurs here… see attached… if space is expected it would be great to have this patch…
 
Jeff
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Monday, January 9, 2017 at 17:10
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [rstudio/bookdown] ```{example} fails unless ```{theorem} exists in document (#291)


 

Should be fixed now. Thanks for the report!
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by yihui** [comment]
Could you reply the issue on Github? The email attachment won't be sent here automatically.

**Comment by JeffreyRacine** [comment]
Certainly... 

![screen shot 2017-01-09 at 17 50 34 jan 9 2017](https://cloud.githubusercontent.com/assets/868531/21786863/26e46528-d694-11e6-8191-d9ac2b6cc90e.png)

**Comment by JeffreyRacine** [comment]
Following up with code... there is a space in the code...

For example, to test the hypothesis that $\rho_1=0$ and $\rho_2=0$, we could use the $\mathcal{Q}_{lb}$ statistic given by $T(T+2)(\hat\rho_1^2/(T-1)+\hat\rho_2^2/(T-2))$ and test the hypothesis by comparing this statistic with a critical value taken from a $\chi^2_{(2)}$ distribution (i.e. a $\chi^2$ random variable having two degrees of freedom such as the 5% level critical value `r format(qchisq(0.95,df=2),digits=3)` obtained via `qchisq(0.95,df=2)`).

```{example}

Let's consider a simple example where you are given $\hat\rho_1$ and $\hat\rho_2$ and $T$ (the length of the series) and then manually conduct individual and joint tests for white noise and report the outcome of the test.

Supposed that we wished to test $H_0\colon\rho_1=0$ based on $T=100$ realizations of a time series, and we computed $\hat\rho_1=0.15121$, $Var[\hat\rho_1]=1/100=.01$, hence $Z=\hat\rho_1/\sqrt{Var[\hat\rho_1]}=0.15121/.1=1.5121$. We would fail to reject the null at all conventional levels. You might ask yourself exactly what this failure to reject the null means in the current context.

If we wished to test $H_0\colon\rho_2=0$ and we computed $\hat\rho_2=0.069739$, $Var[\hat\rho_2]=(1+2\times 0.15121^2)/100=  0.0104573$, hence $Z=\hat\rho_2/\sqrt{Var[\hat\rho_2]}=0.069739/ 0.102260=0.68197$. Again, we would fail to reject the null at all conventional levels.

If we wished to test $H_0\colon\rho_1=0\cap\rho_2=0$, then $\mathcal{Q}_{lb}=100(100+2)[0.15121^2/(100-1)+0.069739^2/(100-2)]$ which equals $10200[0.022865/99+ 0.0048635/98]$ which equals $2.86194$. For $\alpha=0.05$, $\chi^2_{2,1-\alpha}=5.99147$ so again we would fail to reject the null.

```

**Comment by yihui** [comment]
That is a separate issue. You can add these lines of LaTeX code to your preamble to increase the spacing: https://github.com/rstudio/bookdown/blob/4e94c8d499/inst/examples/latex/preamble.tex#L92-L98 If you don't know how, here is the documentation: https://bookdown.org/yihui/bookdown/yaml-options.html (use the `in_header` option).

Source of the solution: http://tex.stackexchange.com/q/85400/9128

**Comment by JeffreyRacine** [comment]
Thanks!
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Tuesday, January 10, 2017 at 12:09
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [rstudio/bookdown] ```{example} fails unless ```{theorem} exists in document (#291)


 

That is a separate issue. You can add these lines of LaTeX code to your preamble to increase the spacing:

https://github.com/rstudio/bookdown/blob/4e94c8d499/inst/examples/latex/preamble.tex#L92-L98 If you don't know how, here is the documentation:
https://bookdown.org/yihui/bookdown/yaml-options.html (use the
in_header option).
Source of the solution: http://tex.stackexchange.com/q/85400/9128
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
