### ISSUE TITLE
Build book cannot find rmarkdown

### ISSUE THREAD

**Issue by michielvandijk** [rstudio/bookdown#293]
Hi I just installed bookdown and I am trying to run the bookdown demo but am not able to make it work. I seem to have two (probably related) problems: (1) when I press build book (for all formats) I got the warning:

Error in loadNamespace(name) : there is no package called 'rmarkdown'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Exited with status 1.

(2) when I press knit I seem to have the same problems as in this post: [https://github.com/rstudio/bookdown-demo/issues/3](url) but I am not able to solve it. I am able to generate the pdf but the figure is missing in the Introduction Chapter Although I can find the nice-fig_1.pdf in the folder. What is also strange is that when I am setting 'output: bookdown::html_book' (or knit to html) it still generates the pdf document (without the figure).

This is the information about my system.

`MiKTeX-XeTeX 2.9.6100 (0.99996) (MiKTeX 2.9.6100 64-bit)
(C) 1994-2008 by SIL International, (C) 2009-2012 by Jonathan Kew, (C) 2010-2012 by Han Han The Thanh, (C) 2012-2013 by Khaled Hosny
TeX is a trademark of the American Mathematical Society.
compiled with zlib version 1.2.8; using 1.2.8
compiled with libpng version 1.6.24; using 1.6.24
compiled with poppler version 0.46.0
compiled with jpeg version 8.4
compiled with fontconfig version 2.12; using 2.12
compiled with FreeType2 version 2.6.5; using 2.6.5
compiled with Graphite2 version 1.3.8; using 1.3.8
compiled with ICU version 57.1; using 57.1
compiled with HarfBuzz version 1.3.0; using 1.3.0
using TECkit version 2.4`

`R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] backports_1.0.4 bookdown_0.3.6  magrittr_1.5    rprojroot_1.1   htmltools_0.3.5 tools_3.3.2    
 [7] yaml_2.1.14     Rcpp_0.12.8.2   stringi_1.1.2   rmarkdown_1.3   knitr_1.15.1    stringr_1.1.0  
[13] digest_0.6.10   evaluate_0.10  `

Thanks!

**Comment by yihui** [comment]
Perhaps certain R packages were broken in your system, and you can find them out and reinstall with:

```r
broken = names(which(
  sapply(rownames(installed.packages()), function(i) {
    system2('Rscript', c('-e', shQuote(sprintf('library(%s)', i))))
  }) != 0
))
if (length(broken)) install.packages(broken)
```

**Comment by michielvandijk** [comment]
Hi Yihui,
Thanks for your quick response! I ran your script and it appeared there was a problem with the package 'Translations' which seem to be a base package (on which I can find very little information on the web). Reinstall gave an error so I decided to do a fresh R install to make sure everything is in order. After the re-installation I installed bookdown and no it seems to work (both the build book and the figure) . Nonetheless, when I ran your script again, the problem with the translations package remains so that was apparently not the problem. No clue what it was. Perhaps a conflict with some other package that is not there (yet)... I will add other packages now that I had installed previously and see if the same problem pops up again. I still keep having the error with latexmk.exe but I understood from previous comments that this is not per se a problem.

**Comment by yihui** [comment]
You can ignore the Translations package. I don't think it is a valid R package. You can also ignore the message about latexmk.exe as long as you are able to generate the PDF correctly.

**Comment by michielvandijk** [comment]
Hi Yihui, some final comments on a new discovery relating the problem. When I was trying bookdown on my home laptop i discovered I had the same problem, that is R could not find rmarkdown when I pressed the build book option. I also reinstalled R and found the following. First, there is a latex problem when latex is not in C:\miktex. Before it was in C:\program files and then it cannot find the right components for bookdown. I assume this has something to do with the PATH settings in window. Second, even after the reinstall of R I had the problem with the rmarkdown package. It seems to be related with a statement in my Rprofile.site that refers to non-standard the location of my library (.libPaths("C:/Users/vandijkm/R/library/3.3.2"). When I removed it things went fine. Could this be the explanation?

**Comment by yihui** [comment]
I think it certainly has something to do with `.libPaths()`, but I don't know how that could be a problem. Anyway, we have received a similar report as yours, and we will investigate the root reason. I may need your help sometime next week if possible.

**Comment by michielvandijk** [comment]
Sure. Just contact me and I will try to help.

**Comment by bbritten** [comment]
For what it's worth, when I try to build a simple book, I get the same issue. I have an .Rprofile file that adds another folder to `.libPaths()`, which is where I install all of my libraries. If I copy `rmarkdown` from this folder into `C:\Program Files\R\R-3.3.2\library` it moves past this error and tells me that it cannot find `htmltools`. So it does appear as though it's not looking in the folder where I've saved my files.

Session Info:

```
Session info -------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-02-24                  

Packages -----------------------------------------------------------------------------------------------
 package   * version date       source        
 backports   1.0.5   2017-01-18 CRAN (R 3.3.2)
 devtools    1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest      0.6.12  2017-01-27 CRAN (R 3.3.2)
 evaluate    0.10    2016-10-11 CRAN (R 3.3.2)
 htmltools   0.3.5   2016-03-21 CRAN (R 3.3.2)
 knitr       1.15.1  2016-11-22 CRAN (R 3.3.2)
 magrittr    1.5     2014-11-22 CRAN (R 3.3.2)
 memoise     1.0.0   2016-01-29 CRAN (R 3.3.2)
 Rcpp        0.12.9  2017-01-14 CRAN (R 3.3.2)
 rmarkdown * 1.3     2016-12-21 CRAN (R 3.3.2)
 rprojroot   1.2     2017-01-16 CRAN (R 3.3.2)
 stringi     1.1.2   2016-10-01 CRAN (R 3.3.2)
 stringr     1.1.0   2016-08-19 CRAN (R 3.3.2)
 withr       1.0.2   2016-06-20 CRAN (R 3.3.2)
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)
```

**Comment by yihui** [comment]
Could you try the daily build of RStudio and see if the problem has been fixed there? https://dailies.rstudio.com Thanks!

**Comment by bbritten** [comment]
This issue exists on my work computer, so I will try that first thing Monday morning.

**Comment by yihui** [comment]
@bateyt How about using `R_LIBS_USER` in `.Renviron` instead of `.libPaths()` in `.Rprofile`? I always use the former.

**Comment by michielvandijk** [comment]
I just encountered the same problem again when I tried to build my blogdown site. Then I discovered that I still had my old .libPaths() in the .Rprofile file. When I removed it and added the R_LIBS_USER statement in the .Renviron file it seems to work. Apparently .libPaths() and R_LIBS_USER are treated differently... So, at first sight this seems to solve the issue.

**Comment by dcomtois** [comment]
I concur. After switching from the `.libPaths` method to the `R_LIBS_USER`, I no longer have the error message ` there is no package called 'rmarkdown'`.

**Comment by ldfreight** [comment]
Hello, I have same issue as my packages are not in the default lib.loc.
My libPath() is correct and shows first the folder where my packages are.
So I really think it is a bug in RStudio which does not fetch the packages from the right place.
Could we fix that in RStudio?

**Comment by cderv** [comment]
This is issue is old with no more comment since more than 2 years. 
RStudio IDE has also moved up in version too during this time.

Please reopen a new issue if you still encounter issues. Thank you.
