### ISSUE TITLE
Change line spacing within the book

### ISSUE THREAD

**Issue by junchenfeng** [rstudio/bookdown#298]
I use the preamble to set double spacing for the whole book but I need the appendix and reference to be single spaced. Is there anyway to do it within bookdown?

**Comment by junchenfeng** [comment]
My current hack is to output .tex and manually change it

**Comment by yihui** [comment]
No, you should never manually touch the .tex output. You will have bad days.

![bad-days](https://cloud.githubusercontent.com/assets/163582/22095627/08ae683e-dddc-11e6-88e1-fa1564576157.gif)

Instead, you can add raw LaTeX commands before your appendix, such as `\setstretch{1.0}`: http://tex.stackexchange.com/q/83855/9128 In index.Rmd, you can set the global YAML option `linestretch` to something like 2.0 (maybe 1.5; I'm not sure).

**Comment by yihui** [comment]
If you take a look at the Rmd source of the bookdown book, you will see raw LaTeX commands like https://github.com/rstudio/bookdown/blob/master/inst/examples/07-tools.Rmd
