### ISSUE TITLE
Next button has confusing click target

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#30]
On safari (at least), if I hover over anywhere over the next button, my mouse pointer turns into the "clicky hand", but clicking does nothing. It's only if I'm over the text that clicking works to take me to the next page

**Comment by yihui** [comment]
I cannot reproduce that on Safari. I can click anywhere to go to the next page whenever the cursor is a "clicky hand".

**Comment by hadley** [comment]
(This is with the default output, not gitbook)
