### ISSUE TITLE
Build book fails regularly after a few iterations

### ISSUE THREAD

**Issue by abedd74** [rstudio/bookdown#301]
Hi 
I have recently installed bookdown. The bookdown demo works fine, so I started editing the file. Typically after compiling the example successfully for a few times I receive the error message below and I found no way to get the file to work again. However after downloading a fresh bookdown demo and editing the text to the same point in which I started receiving the error the file compiles correctly until it fails with the same error message some times later.

```
==> rmarkdown::render_site(encoding = 'UTF-8')

Error in check_special_chars(files) : 
  Filenames must not contain special characters
Calls: <Anonymous> ... setdiff -> as.vector -> source_files -> check_special_chars
In addition: Warning message:
In check_special_chars(files) :
  The filename "Test - test.Rmd" contains special characters. You may rename it to, e.g., "Test---a-test.Rmd".
Execution halted

Exited with status 1.
```

Any help on how to avoid this issue would be greatly appreciated. Thanks for the nice work.

**Comment by CaperKen** [comment]
I had exactly the same error occur today.

**Comment by CaperKen** [comment]
I had exactly the same error today.

**Comment by BenjamS** [comment]
So, was this resolved? I'm having the same problem in 2020.

**Comment by yihui** [comment]
> I guess blogdown doesn't like posts being inside their own special folder.

@BenjamS That's not true. In fact, I even encourage using page bundles so that posts are in their own folders: https://bookdown.org/yihui/blogdown/more-global-options.html BTW, for **blogdown** issues, please file them to the **blogdown** repo. Thanks!
