### ISSUE TITLE
Invalid HTML generated

### ISSUE THREAD

**Issue by lmullen** [rstudio/bookdown#302]
Bookdown generates invalid HTML, perhaps because of the underlying GitBook template. For example, here is the [validation report](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fbookdown.org%2Fyihui%2Fbookdown%2F) for the bookdown book. There's probably no need to be a stickler for every detail of that report. But the unclosed elements seem important. I think they cause some problems with the CSS for footnotes, for example.

**Comment by yihui** [comment]
The main issue was due to an extra double quote. Should be fixed now. Thanks for the report!

**Comment by yihui** [comment]
Well, after a closer inspection, there were indeed two `<div>`'s that were not closed.
