### ISSUE TITLE
custom css with {.myclass} for code and quote blocks too?

### ISSUE THREAD

**Issue by stevepowell99** [rstudio/bookdown#303]
At the moment I can do this

`## my heading {.mystyle}`

to style a heading, which is great.

If I want just a div I have to manually type the html and add `<div class=mystyle>` etc, remembering to close the div, which is not quite so great. I was thinking of hijacking code blocks or quote blocks for this purpose, e.g.:

`>asdf {.mystyle}`

or code block with four spaces, or the ``` syntax. But it doesn't work. Wondering if there is a workaround?

To clarify: I only want to piggyback on one of the quick ways to get a div in markdown (codeblocks, quote blocks) in order to be able to quickly apply a custom style to a paragraph, I don't want to change the default appearance of those blocks.

**Comment by yihui** [comment]
If you cannot find the syntax you want from http://pandoc.org/MANUAL.html or https://bookdown.org/yihui/bookdown/custom-blocks.html, I'm afraid it will not be supported.
