### ISSUE TITLE
Recompile from latex output failed

### ISSUE THREAD

**Issue by junchenfeng** [rstudio/bookdown#304]
The tex file is produced in "_book" folder but the figure assets are still in "_bookdown/thesis_files". 

After manually migrate it. The pdf is successfully compiled. I think it is an bug.

**Comment by yihui** [comment]
It is not a bug but I see your point. The .tex output is not supposed to be compiled manually. It is only for debugging purposes, and you will have to move it to the `_bookdown_files` directory before you can compile it. This is not documented, and I was hoping most users would not really need to open the .tex file or compile it.
