### ISSUE TITLE
warn users: weird stuff happens when you forget level 1 headings in index.rmd

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#305]
so, I just spent 2 hours or so chasing the stupid-est bug I have inflicted upon myself in a long time:

I had an `index.Rmd` *with no* heading whatsoever (no particular reason, I just forgot about it).

Bookdown still worked, threw some uninformative warnings, but *did not create an actual* `index.html`.

I have some vague idea what must caused this problem, and I *understand* that I need to have a toplevel heading in each file, particularly in `index.Rmd`.

Perhaps `bookdown` could warn (better: shout and scream at) users in some informative way if they are stupid enough to forget this?

**Comment by yihui** [comment]
That makes perfect sense. Sorry for wasting your time, and I'll try my best to scream in such cases in the future.

![you-get-nothing](https://cloud.githubusercontent.com/assets/163582/22095777/1e578d18-dddd-11e6-9b48-7327e670ca85.gif)

**Comment by maxheld83** [comment]
hehe, fun gif – just hope my issue wasn't too stupid.

Just wanted to add: even without a heading in `index.Rmd` `bookdown::gitbook` actually produced output (named `_main.html`, etc.) just not `index.html`, that's what confused me.

Anyway, thanks so much for your work!

**Comment by yihui** [comment]
No, it is not stupid. It just my failure and I really should have given a more clear warning message.
