### ISSUE TITLE
xelatex, bibtex, bookdown-demo.tex - status 127

### ISSUE THREAD

**Issue by drkamarul** [rstudio/bookdown#306]
Hi,

I downloaded the bookdown-demo-master and built the book. I also knitted the index.Rmd. They produced the books in  html and pdf (which is a good news! thanks). 

But these warning messages (see below) that I got after every time building and knitting bug me and so I would like to know what have I done wrong?

#####

Output created: _book/index.html
Warning messages:
1: running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 127 
2: running command '"bibtex" "bookdown-demo.aux"' had status 127 
3: running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 127 
4: running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 127

**Comment by yihui** [comment]
If you can get the PDF output correctly, you can ignore these warnings.
