### ISSUE TITLE
bookdown install failed with Microsoft R Client

### ISSUE THREAD

**Issue by milesxu** [rstudio/bookdown#308]
I encountered the following error when I try to run `devtools::install_github("rstudio/bookdown")`:
```
Installing bookdown
"G:/Microsoft/R Client/R_SERVER/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  "C:/Users/alone/AppData/Local/Temp/Rtmp8KLhZS/devtools1840330b5bb8/rstudio-bookdown-90118ff"  \
  --library="G:/Microsoft/R Client/R_SERVER/library" --install-tests

'G:\Microsoft\R' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed (1)
```
I found that when I call `R.exe` in Windows command line, the same error will appear.
My operating system is Windows 10 64bit, R version is Microsoft R client 64bit 3.3.2, I tried to install bookdown in Rstudio and RGui, both will complain the error above.

Can anyone help me?

**Comment by qinwf** [comment]
Hi, I think this may be a Microsoft R client issue. If you post it to Microsoft R client repo, you would get more relevant respond.

**Comment by milesxu** [comment]
Thanks! I will try it.

**Comment by yihui** [comment]
I have seen this error message several times and it could be an issue with devtools, too. Do you have a reason to install the Github version of bookdown? In other words, why not `install.packages('bookdown')`?

**Comment by milesxu** [comment]
Oh, I'm a newbie of R.
I use devtools just because I found these steps from the "getting started" section in bookdown.org.
Now I successfully installed in by Rstudio, thank you!

**Comment by milesxu** [comment]
However, the version I installed by `install.packages()` is 0.1, so I look forward to an update to cran library.

**Comment by yihui** [comment]
Not sure which CRAN mirror you used, but you are supposed to get 0.3: https://cran.rstudio.com/web/packages/bookdown/ I heard that Microsoft R used a strategy to lock versions of R packages to specific versions of R, and I'm not sure if you are able to install from a custom repo like

```r
install.packages('bookdown', repos = 'https://cran.rstudio.com')
```

**Comment by milesxu** [comment]
@yihui Thank you very much!
I get all problems solved.
Thanks again!
I installed the version 0.1 by Rstudio dialog, which shows "Repository (CRAN, CRANextra)"
when I use terminal and the command you given, I got the 0.3 version.

**Comment by yihui** [comment]
Great. If you can set the CRAN repository to any but MRAN (the repo provided by Microsoft), for example, cran.rstudio.com, I guess this kind of problems should not happen in the future. I have never tried Microsoft R Open myself, so I'm not sure.
