### ISSUE TITLE
For PDF output, TOC + leading unnumbered chapters cause error in running headers

### ISSUE THREAD

**Issue by WilDoane** [rstudio/bookdown#309]
A minimal change to the demo bookdown document, "A Minimal Book Example", shows the issue:

* add toc: yes to the YAML
* change the #Prerequisites and #Introductions headers to be unnumbered {-}
* build the book

Note that the running headers on pages 6 and 8 of the generated PDF are incorrect (read: "Contents"; should read: "Prerequisites" and "Introduction", respectively).

[header_error.zip](https://github.com/rstudio/bookdown/files/721405/header_error.zip)

**Comment by yihui** [comment]
That is purely a LaTeX issue. I don't have time to investigate it, but my guess is you need to declare `\frontmatter` and `\mainmatter` in appropriate places. If you are serious about writing a book but not a LaTeX expert, this should be a better example: https://github.com/yihui/bookdown-crc

**Comment by WilDoane** [comment]
It appears to be the interaction of two bits of guidance from your book. If one both uses

    # Preface {-}

as described in the *Special Headings* section AND follows the suggestion to add 

    \frontmatter

given in the *Publishing > Publishers* section, then you get misbehaving running headers.

The solution appears to be to use `\frontmatter` (which already makes `\chapter` and `\section` unnumbered and adds them to the TOC) without the `{-}` marker on the frontmatter chapter headings (so that `\chapter` and not `\chapter*` is generated within `\frontmatter`). The `{-}` marker is still needed for subsections within the `\frontmatter`, apparently.
