### ISSUE TITLE
support abstract in gitbook output

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#311]
happily, when `documentclass: article`, `bookdown::pdf_book` supports whatever is inside the YAML toplevel `abstract:` field, and puts it into the appropriate LaTeX environment.

Unfortunately, there is no equivalent output in `bookdown::gitbook` (and other HTML outputs), so the `abstract:` YAML field is ignored.

I don't think this would require/warrant any extra HTML/CSS.

It'd just be nice if the abstract from that field showed up perhaps as

```
# Abstract {-}

blah blah abstract from the field `abstract:` in the toplevel YAML.
```

Is this possible?
Or is there a simple way to access the toplevel YAML *from inside* the document, so I could "paste" it myself?

**Comment by maxheld83** [comment]
Just in case someone else stumbles into this, I've come up with a sort-of solution, but it's quite clumsy/hacky.

```
# Abstract {-}

```{r, abstract-begin, results="asis"}
if (knitr::opts_knit$get("rmarkdown.pandoc.to") == "latex") {
  # we first need to remove duplicate abstract title, hack-fix from http://tex.stackexchange.com/questions/42482/remove-abstract-title-from-abstract
  cat("\\renewcommand{\\abstractname}{\\vspace{-\\baselineskip}}") # clear the title
  cat("\\begin{abstract}")
}
```
Abstract text ... Lorem ipsum ...

```{r, abstract-end, results="asis"}
if (knitr::opts_knit$get("rmarkdown.pandoc.to") == "latex") {cat("\\end{abstract}")}
```
```

**Comment by yihui** [comment]
Should be fixed now. Just use `abstract` in YAML. Thanks for the report!

**Comment by jmagan01** [comment]
> Should be fixed now. Just use `abstract` in YAML. Thanks for the report!

Does not work for PDF output. I get this error message:
! LaTeX Error: Environment abstract undefined.

**Comment by micahwiesner67** [comment]
I am also having the same error ...
! LaTeX Error: Environment abstract undefined.

**Comment by cderv** [comment]
When using `pdf_book` with bookdown, I think most of the time you work with book format. That means you tell latex to work with `\documentclass{book}` - usually you have this in the `index.Rmd`:
```yaml
documentclass: book
```

Using `abstract` field in Yaml will activated this part of the pandoc latex template
```latex
$if(abstract)$
\begin{abstract}
$abstract$
\end{abstract}
$endif$
```
so it will asked for abstract environment. However, I believe the environment `abstract` is not define for such document class. See https://en.wikibooks.org/wiki/LaTeX/Document_Structure#Abstract
> As most research papers have an abstract, there are predefined commands for telling LaTeX which part of the content makes up the abstract. This should appear in its logical order, therefore, after the top matter, but before the main sections of the body. This command is available for the document classes article and report, **but not book.** 

You either need to create the abstract environment yourself (or maybe use the abstract Tex package), or work with another documentclass like `documentclass: report`. But it will change the way it looks. So this is not a bookdown issue, this is Latex stuff you need to look into. You'll find plenty of resource on the web looking for "abstract environment in latex book document"

Hope it helps.
