### ISSUE TITLE
Configure the edit button

### ISSUE THREAD

**Issue by csgillespie** [rstudio/bookdown#315]
The raw page  https://jumpingrivers.github.io/meetingsR/r-user-groups.html#asia is located at https://github.com/jumpingrivers/meetingsR/blob/master/02_useR_groups_asia.Rmd however this page only contains level 2 and 3 headings. So when I click on the edit button at 

https://jumpingrivers.github.io/meetingsR/r-user-groups.html#asia

It takes me to the top level page at https://github.com/jumpingrivers/meetingsR/blob/master/02_useR_groups_aaa.Rmd

Is there any way around this?

**Comment by yihui** [comment]
From [the documentation](https://bookdown.org/yihui/bookdown/usage.html):

> Each R Markdown file must start immediately with the chapter title using the first-level heading, e.g., `# Chapter Title`.
