### ISSUE TITLE
`keep_md: true` option with output?

### ISSUE THREAD

**Issue by akzaidi** [rstudio/bookdown#317]
Is there a way to render bookdown with keep_md option so I can get the _book files as mds in addition to the html? 

When adding this I see the following files are created
```
output file: bookdown-demo.knit.md
```
but they aren't in the `_book` directory.

**Comment by yihui** [comment]
If you want to keep the intermediate .md file, you have to run `bookdown::render_book('index.Rmd', clean = FALSE)`.

**Comment by akzaidi** [comment]
Oooh, nice. Thanks !
