### ISSUE TITLE
retain original .Rmd filenames for html output

### ISSUE THREAD

**Issue by stevepowell99** [rstudio/bookdown#318]
At the moment, the html files produced are named after the first heading in each file (overriden by `{#myid}` as well). Is there a setting to retain the original .Rmd filenames instead? 

My motivation: I would like to do some post-processing on the html files and I need this to be in the original alphabetical order of the source .Rmd files - unfortunately that order can not be deduced from the new .html filenames (nor from the creation dates as bookdown is too fast).

**Comment by yihui** [comment]
Search for `split_by`: https://bookdown.org/yihui/bookdown/html.html
