### ISSUE TITLE
Query about adding further docx compatibility to bookdown/pandoc

### ISSUE THREAD

**Issue by peircej** [rstudio/bookdown#319]
Hi there, 

I'm interested in the following features, mostly to improving compatibility with the docx outputs (I know, don't ask!). I think for all of these the question is whether this is something that needs changing in bookdown or pandoc?

1. I'd love for custom `block2` environments to relate to a new style in the word document so that I could adjust that style in a template (like I can adjust the custom environment in the latex output). 
2. Is there any cross-target way to provide in-line images (in the text) rather than as a Figure. I was using `\include_graphics()` for the LaTeX outputs but that only works in LaTeX obviously. I've now switched to using the R `include_graphics()` but I can't work out with that how to add inline images
3. I guess the cross-target equivalent of `\index{}` won't be coming anytime soon?

Other than these things I'm quite impressed at how good the docx output is. Much better-looking than if I converted the pdf after creating it. bookdown is quite a help in allowing me to output both formats from a single source

many thanks

**Comment by yihui** [comment]
1. I don't know if it is possible. At least I'm not aware of a way to mark certain elements with a specific style name for Word output. If you can figure out how it could possibly work in Pandoc, I can do the work on knitr's side.

2. I think you can just use the Markdown syntax `![]()` if the image size is appropriate for all output formats.

3. You are correct that `\index{}` won't come soon, but I agree it is useful.
