### ISSUE TITLE
Support for algorithms and nomenclature with numbering and list of algorithms/nomenclature

### ISSUE THREAD

**Issue by mjmg** [rstudio/bookdown#320]
I'm evaluating whether to write my thesis in latex or bookdown. My latex template has incorporated support for numbered algorithms <https://en.wikibooks.org/wiki/LaTeX/Algorithms>, code listings <https://www.sharelatex.com/learn/Code_listing> and nomenclature <https://www.sharelatex.com/learn/Nomenclatures> with corresponding lists of nomenclature/algorithms/code listings in the preamble.

Is support for these environments already possible with current versions of bookdown or they still have yet to be implemented?

**Comment by yihui** [comment]
None of these environments are currently supported. Sorry.

**Comment by yihui** [comment]
Closing as "duplicate" of #238.
