### ISSUE TITLE
International symbols in capter names cause encoding issues in an HTML table (DT::datatable())

### ISSUE THREAD

**Issue by GegznaV** [rstudio/bookdown#321]
I use an *R* *Bookdown* package to create an HTML-based Git-book. The book contains an interactive HTML table created with function `DT::datatable()`.
I noticed, that if any chapter name in a book contains an international letter (say, "ą", "ž", etc.), the interactive table becomes encoded incorrectly.

**Is there a way to have international letters in chapter names and correctly encoded interactive table (DataTable)?**

Structure of my *Bookdown* folder:

    dir()
    [1] "_bookdown.yml"   
    [2] "_output.yml"  
    [3]  "bookdown_tmp.Rproj"
    [4] "index.Rmd" 

**_bookdown.yml:**

    documentclass: book
    output_dir: "_book"
    encoding: utf-8

**_output.yml:**

    bookdown::gitbook: default

**index.Rmd** (that gives correct result)**:**

    --- 
    site: bookdown::bookdown_site
    ---
    
    # Ch1
    
    ```{r, include=FALSE}
    library(DT)
    Sys.setlocale(locale = "Lithuanian")
    ```
    
    ```{r, echo = FALSE}
    x <- c("ą č ę ė į š ų ū 9 0 ž", "3254")
    DF <- data.frame(x = x)
    datatable(DF)
    ```

Result:  
[![enter image description here][1]][1]

If in file **index.Rmd** the line with the title `# Ch 1` is changed into chapter name that contain international symbols, say, `# Ch 1 ž`, the encoding issues arise:

[![enter image description here][2]][2]

Nothing else is changed except from one additional letter in a chapter's name.

I render the book by pressing "Build book" button in *RStudio*: [![enter image description here][3]][3]

***
Session information `devtools::session_info()`:

    Session info --------------------------------------------------------------------
     setting  value                       
     version  R version 3.3.2 (2016-10-31)
     system   x86_64, mingw32             
     ui       RStudio (1.0.136)           
     language (EN)                        
     collate  English_United States.1252  
     tz       Europe/Helsinki             
     date     2017-02-01                  
    
    Packages ------------------------------------------------------------------------
     package   * version  date       source                            
     backports   1.0.5    2017-01-18 CRAN (R 3.3.2)                    
     bookdown    0.3.9    2017-01-31 Github (rstudio/bookdown@b73daa1) 
     devtools    1.12.0   2016-06-24 CRAN (R 3.3.2)                    
     digest      0.6.12   2017-01-27 CRAN (R 3.3.2)                    
     evaluate    0.10     2016-12-27 Github (hadley/evaluate@742da2d)  
     htmltools   0.3.5    2016-03-21 CRAN (R 3.3.2)                    
     knitr       1.15.8   2017-01-31 Github (yihui/knitr@b936c1e)      
     magrittr    1.5      2014-11-22 CRAN (R 3.3.2)                    
     memoise     1.0.0    2016-01-29 CRAN (R 3.3.2)                    
     Rcpp        0.12.9   2017-01-14 CRAN (R 3.3.2)                    
     rmarkdown   1.3.9002 2017-01-31 Github (rstudio/rmarkdown@c4908dc)
     rprojroot   1.2      2017-01-16 CRAN (R 3.3.2)                    
     rsconnect   0.7      2016-12-21 CRAN (R 3.3.2)                    
     stringi     1.1.2    2016-10-01 CRAN (R 3.3.2)                    
     stringr     1.1.0    2016-08-19 CRAN (R 3.3.2)                    
     withr       1.0.2    2016-06-20 CRAN (R 3.3.2)                    
     yaml        2.1.14   2016-11-12 CRAN (R 3.3.2) 

  [1]: https://i.stack.imgur.com/3msgn.jpg
  [2]: https://i.stack.imgur.com/OlLH5.jpg
  [3]: https://i.stack.imgur.com/TffYj.jpg

**Comment by GegznaV** [comment]
I noticed, that inclusion of `print(x)`, which results in `[1] "ą č ę ė į š ų ū 9 0 ž" "3254"`, also distorts encoding of table produced with `DT::datatable`.

Is it possible, that during the rendering process  some intermediate file has incorrect encoding?

**Comment by yihui** [comment]
That is weird. I cannot think of a reason why this could happen. Does `devtools::install_github('rstudio/htmltools')` help?

Another thing you may try is to set the locale globally in `~/.Rprofile`:

```r
Sys.setlocale(locale = "Lithuanian")
```

**Comment by GegznaV** [comment]
Your suggestions helped.
