### ISSUE TITLE
Caching behavior

### ISSUE THREAD

**Issue by basille** [rstudio/bookdown#323]
I've been using `bookdown` for a while now, and I have to say I'm really impressed by the work done! It provides me the perfect tools for my work. I am just slightly puzzled by how cache is handled. In my case, I like to turn `cache = TRUE` in `knitr::opts_chunk$set`, so that it makes work-in-progress easier: all you have to do is to `render` the book and you have the session ready for use with every objects at hand.

Except that what works with vanilla `knitr` does not seem to work with `bookdown::render`. If I `render` a book, all objects are indeed created (as a call to `ls()`) indicates, but they are only pointers to the last cache version computed (for instance, epub), and the way `bookdown::render` reorganizes folders when it's done makes it unable to recover objects. For instance, if I create an object `x` in a RMarkdown file, render the book, and try to call `x` in the R console, I get error messages such as:

    Error: cannot open file '<working directory>/bookdown_cache/epub3/unnamed-chunk-
    1_53b327261f8a149223b65aef1557669f.rdb': No such file or directory

Which makes sense given that the actual cached object is now in `_bookdown_files/bookdown_cache/epub3/`, i.e. now in the `_bookdown_files` subfolder.

So my question is: Is this intended behavior? Is the cache mechanism just intended for the book, and not for users? (if yes, may I suggest that it would be a great idea that users can use it too, as is available through `knitr`)

Bonus question: What is the purpose of having different cache folders for different book formats? Shouldn't it be a single cache for all outputs? I'm not sure I see the benefits of having three (this is a huge computing + size overhead, plus the possibility that the different caches are not synced… which would lead to different outputs for different book formats…)

**Comment by yihui** [comment]
It is intended. The only way to render a book is `render_book()`. You should not call `knitr::knit()` or `rmarkdown::render()` to compile a single Rmd file.

The reason for different cache folders for different output formats is that the output of a code chunk may be dependent on the output format. For example, PDF figures are generated by default when the output format is LaTeX, and PNG is used when the output format is HTML. 

If you are sure your output is not dependent on output formats, you can use the chunk option `cache.path` to specify a cache directory that is not dependent on output formats, e.g.

    ```{r very-important, cache.path='cache/'}
    ```

**Comment by basille** [comment]
Hey Yihui, thanks for your answer, and sorry to be so slow to respond…

I have to apologize for the confusion, and actually mixing different points in my initial query. I'll try to be clearer here, and break the question down to 3 points:

## Render

First of all, let me clarify this, I do use `bookdown::render_book()` to render a book, I understand why `knitr::knit()` or `rmarkdown::render()` are not cut for this job.


## Caching and interactive sessions

Second, however, I still think there is a problem to the caching behavior, and the way cache folders move around. Let me try to illustrate this with a simple example, elaborating after the [bookdown-demo](https://github.com/rstudio/bookdown-demo) minimal example.

So let's just start by cloning the repository, edit `01-intro.Rmd`, and simply add the following chunk at the end of it:

    ```{r test, cache = TRUE}
    bla <- 2
    ```

Let's now render the bookdown using `bookdown::render_book('index.Rmd', 'bookdown::gitbook')`. Everything works fine, the bookdown is correctly rendered with the additional chunk. I can type `bla` in the R console, and get `2` as expected. The cache is created in `_bookdown_files/bookdown-demo_cache`. 

Now let's end the R session. Later on, I want to come back to this work, so I re-run `bookdown::render_book('index.Rmd', 'bookdown::gitbook')`, and the cached chunk is read from cache, just as expected.

However, now, I'm unable to read `bla` from the R console, as R complains about the file being absent:

    > bla
    Error: cannot open file '<snip>/bookdown-demo/bookdown-demo_cache/html/test_16ca564ea9f13e368de31a5c477cbf3b.rdb': No such file or directory

And rightfully so, since the cache is now in `_bookdown_files/bookdown-demo_cache`, not directly in `bookdown-demo_cache`. As a result, I cannot dynamically work on my project (i.e. with an interactive session) anymore. I hope this makes things clearer.


## Cache folders

Although it is really not the point of my initial query, I still have a hard time understanding the reason for cache folders being different depending on the output format. I understand that figures are different, but they are stored in `bookdown-demo_files`, independently of the cache. Isn't the cache a saved version of R objects, which are independent of the output format?

(At the same time, I have noticed slight differences in the cache files from html to pdf for instance, so it seems I'm missing something.)

Thanks a lot or any light you may shed on this.

**Comment by yihui** [comment]
The cache stores all text output from code chunks. For example, a code chunk may generate the text output `![](figure-html/foo.png)` when the output is HTML, and the output can be `![](figure-tex/foo.pdf)` when the output format is LaTeX/PDF. If caching is independent of the output formats, **knitr** will output `![](figure-tex/foo.pdf)` even if the format has been changed to HTML, which will become problematic.

In short, yes, the figure files themselves are independent of the cache, but how we use the figure files and which figure files to use are not independent of output formats.

As I said, you can make the cache independent with output formats if you want and understand the consequences -- just bring your own caching path that is independent with output formats. It is just the default cache path that is dependent on output formats.

**Comment by basille** [comment]
Oh, I see, thanks for the explanation (which is why html vs pdf cache size can sometimes be only a few bytes different). Although in the end that duplicates all R objects (cache size) and all computation (time), that are independent of output, I can live with that.

So that's for my third point (i.e. Cache folders). What about my second point (Caching and interactive sessions), which is really the "annoying" part of a bookdown process with cache enabled?

**Comment by yihui** [comment]
The second point can also be (partially) addressed by a custom cache path that is independent of output formats, because **bookdown** only moves the `*_cache/` folder. If your cache path does not end with `_cache`, it will not be moved.

**Comment by basille** [comment]
Indeed. But, arguably, the "partially" really defeats the purpose of caching: I cannot work on a bookdown iteratively with multiple outputs in mind. The solution might be to 1) develop with HTML only and a specific `cache.path`, and 2) remove the `cache.path` and switch to full compilation with multiple formats when I'm done (and hoping that I'm done for good). But this seems rather clunky to me.

**Comment by yihui** [comment]
Then you have to actually use `bla` at least once in your book, so that the promise is evaluated before the cache directory is moved away. Or set the chunk option `cache.lazy = FALSE` to avoid lazy loading.

**Comment by basille** [comment]
I see. Using `bla` does the trick, but requires to do it for every object, which may not always be convenient in iterative development. On the other hand, using `cache.lazy = FALSE` seems to work in all cases (although I wonder how `load` finds the right cache files while `lazyLoad` doesn't). Rendering the bookdown (initial render or following render) seems to be slower for big objects — are there any other drawbacks in using `cache.lazy = FALSE`?

Thanks for guiding me through… I actually learned a lot on caching with knitr.

**Comment by yihui** [comment]
These have been explained in the knitr book (no, I don't mean you should buy a copy). Basically, lazy loading means the object is not loaded from disk (the cache database) until it is actually used. This can save you some time and memory when the cached objects are not immediately used. However, this delayed loading means the object has to be associated with a file path to the cache database. The problem in bookdown is that the cache database will be moved. That is why lazy loading won't work. When `cache.lazy = FALSE`, objects are immediately loaded into memory, so it does not matter where the cache database is moved to.

**Comment by basille** [comment]
Oh, I understand now! Both `load` and `lazyLoad` find the actual cache files in `_bookdown_files/<whatever>_cache`, but the promise for `lazyLoad` points to a file that has moved since caching. Which is why rerunning `bookdown::render_book` does not fail (`lazyLoad` finds the cache files) but using the objects does fail (the promise is pointing to the wrong target).

This said, couldn't it be solved by asking knitr (in the call from `bookdown::render_book`) to put the cache directly in the right folders, instead of moving them afterwards?

And in the end (knowing that would probably require a major refactoring), wouldn't it be also easier to have R invariants (i.e. R objects) stored separately in cache than text output? That would allow to keep a single copy of cache when it's not necessary to have three copies of it, and only have specific files for figures and text output.

**Comment by yihui** [comment]
I think it should be rare for someone to create an object but not actually use it until after the book has been compiled. You are the first bookdown user who has run into this issue. It may make more sense for bookdown not to move the cache directory, but since you have enough workarounds, I'm hesitant to change the behavior. To repeat what my usual response: if this is something that make you sleepless at 3am, let me know and I can change it, otherwise let's move on :)

If you seriously care about the efficiency of caching, I recommend you to use your own caching mechanism, e.g. the good old trick `if (file.exists('foo.rds')) readRDS('foo.rds')`. You will have full control of what you want to cache and how you want to load objects.

**Comment by basille** [comment]
I agree with you: at least, I have some workarounds (I can leave with `cache.lazy = FALSE` when I need it). Admittedly, it took me a while to figure out what was going on, because sometimes it would work and sometimes not. You found it: it was exactly because of an object created but not used immediately. And in my case, it was the result of a fairly long and computer-intensive call, which just added to the frustration (and the joy of debugging).

So no, it's definitely not a big issue that prevents me from sleeping! I guess most of it comes from computation time and efficiency (but I'm not to the point that my computer is really the limiting factor, as compared to me…).
