### ISSUE TITLE
prerun script before build

### ISSUE THREAD

**Issue by yonicd** [rstudio/bookdown#324]
apart from writing my own makefile is there a way to have current build run code before it queries what rmd files are in the working directory?

**Comment by yihui** [comment]
If you mean a way in an RStudio project, no, the only way is Makefile or a custom shell script. 

![image](https://cloud.githubusercontent.com/assets/163582/23642845/85ebeba8-02c3-11e7-868a-d98ffde57b36.png)

**Comment by yonicd** [comment]
thanks for the info. you may like this [example](https://metrumresearchgroup.github.io/slickR/index.html) that uses [slickR](https://github.com/metrumresearchgroup/slickR)+Bookdown
