### ISSUE TITLE
Possible mathjax process cache size issue?

### ISSUE THREAD

**Issue by drexell0680** [rstudio/bookdown#325]
I'm using bookdown_0.3, rmarkdown_1.3 on OS/X Yosemite with Rstudio 1.0.136.  I'm  running into a strange error in which it seems the mathjax process just can not render one more latex chunk to a gitbook output.

The output knit.md file is created, pandoc is run, and then I get this error:

> /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS cren-paper.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output cren-paper.html --smart --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --template /Users/danp/co/svn-proj-GEN100101/deliv/paper/modeling-paper/lib/bookdown/templates/gitbook.html --highlight-style pygments --number-sections --include-in-header /var/folders/p9/2b_bsphj329bh74fq4fnwfxc0000gp/T//RtmpJ2QHsu/rmarkdown-str328a5542153e.html --mathjax --bibliography alpha.bib --bibliography packages.bib --filter /Applications/RStudio.app/Contents/MacOS/pandoc/pandoc-citeproc 
> Error in seq.default(dots[[1L]][[3L]], dots[[2L]][[3L]]) : 
>   'to' cannot be NA, NaN or infinite

If I remove a decent amount of my latex (which is wrapped in double dollar signs), I can get to a point at which it builds correctly.  From there, if I simply add:

$$
test
$$

It fails with the same error as above.  (See the gifs).  
This is only if I use the double dollar signs, however... If I use inline mathjax it again makes it through the pandoc process.    

Where do I even start debugging on debugging this?

Thanks for the help, you're doing great things here 👍 

![this_works](https://cloud.githubusercontent.com/assets/707490/22610868/a0db60e8-ea35-11e6-9f5a-7e6d53282e47.gif)
![this_doesnt](https://cloud.githubusercontent.com/assets/707490/22610875/a7d5b812-ea35-11e6-9842-f7a93eb0b57b.gif)

**Comment by drexell0680** [comment]
A little more info on this, if I switch my output tag in the yaml header in index.Rmd from:
output: 
  bookdown::gitbook: default

to 
ouput:
  html_document:
    toc: true

The problem goes away.  Also, I am rendering via:
bookdown:::render_book("index.Rmd")

**Comment by yihui** [comment]
I guess I have fixed it in the development version. You can try:

```r
devtools::install_github('')
```

Basically this error message indicates that your `$$ $$` expression is not in its own paragraph. You can add blank lines before/after such math expressions.
