### ISSUE TITLE
bookdown::word_document2 does not produce numbered section headers... can this be added?

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#327]
Greetings, 

bookdown is improving and becoming incredibly good thanks to your efforts. However one feature I am unable to get working is numbered headers for word_document2. This works in HTML and PDF (pdf_document2 and html_document2) but fails in word and number_sections also does not appear to be supported.

If this could be added it would be a wonderful enhancement and one that I think would be welcome by all... thanks for giving this your consideration. Code to demonstrate follows...

```
---
booktabs: yes
output:
  bookdown::word_document2: null
  bookdown::pdf_document2: null
  bookdown::html_document2: null
---

# Header 1

## Header 2
```

> devtools::session_info('bookdown')
Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin16.1.0        
 ui       RStudio (1.1.66)            
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       America/Toronto             
 date     2017-02-06                  

Packages -------------------------------------------------------------------------------------------------------------
 package   * version  date       source                            
 backports   1.0.5    2017-01-18 CRAN (R 3.3.2)                    
 base64enc   0.1-3    2015-07-28 CRAN (R 3.3.0)                    
 bitops      1.0-6    2013-08-17 CRAN (R 3.3.0)                    
 bookdown    0.3.9    2017-02-01 Github (rstudio/bookdown@b73daa1) 
 caTools     1.17.1   2014-09-10 CRAN (R 3.3.0)                    
 digest      0.6.12   2017-01-27 CRAN (R 3.3.2)                    
 evaluate    0.10     2016-10-11 CRAN (R 3.3.1)                    
 highr       0.6      2016-05-09 CRAN (R 3.3.0)                    
 htmltools   0.3.5    2016-03-21 CRAN (R 3.3.0)                    
 jsonlite    1.2      2016-12-31 CRAN (R 3.3.2)                    
 knitr       1.15.8   2017-02-01 Github (yihui/knitr@b936c1e)      
 magrittr    1.5      2014-11-22 CRAN (R 3.3.0)                    
 markdown    0.7.10   2016-12-16 Github (rstudio/markdown@1e1b061) 
 mime        0.5      2016-07-07 CRAN (R 3.3.1)                    
 Rcpp        0.12.9   2017-01-14 CRAN (R 3.3.2)                    
 rmarkdown   1.3.9002 2017-02-04 Github (rstudio/rmarkdown@c4908dc)
 rprojroot   1.2      2017-01-16 CRAN (R 3.3.2)                    
 stringi     1.1.2    2016-10-01 CRAN (R 3.3.1)                    
 stringr     1.1.0    2016-08-19 CRAN (R 3.3.1)                    
 yaml        2.1.14   2016-11-12 CRAN (R 3.3.2)                    
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
>

**Comment by peircej** [comment]
In word you can edit the style of the heading and provide this as a template document.
```
output:
  bookdown::word_document2:
    toc: yes
    reference_docx: "template.docx" 
```

To create a file that will be a valid template just build your document once, then edit the styles in the word document so it looks how you want then use *that* document as the template. works fine for me and you can customize your headings however you like (not limited to numbering)

**Comment by yihui** [comment]
From the [Pandoc manual](http://pandoc.org/MANUAL.html):

> `-N, --number-sections`  
> Number section headings in LaTeX, ConTeXt, HTML, or EPUB output.

Word is not supported. So I cannot support it, either. You have to use other approaches.
