### ISSUE TITLE
Cross referencing not resolved for pdf

### ISSUE THREAD

**Issue by johnros** [rstudio/bookdown#333]
I have a funny phenomenon which I can't figure out. 
My book compiles perfectly to HTML and docx.
For pdf, it cannot resolve the references. 
I identified the particular chapter that cannot be resolved. 
If I compile twice manually with xelatex, the problem is solved. 
This occurs with latexmk 4.52c, and 4.24-1 (I am running Ubuntu).
Does this make any sense?

[This](https://github.com/johnros/Rcourse/blob/master/03-eda.Rmd) is the problematic chapter.

**Comment by yihui** [comment]
You have one reference `Section \@ref(dim-reduce)` in the EDA chapter. By "not resolved", what do you exactly mean? Question marks? Like `Section ??` instead of `Section 10.1`?

Do other references work well?

**Comment by johnros** [comment]
Thank you Yihui for looking into the problem. Since I opened the issue, I discovered that it was all due to duplicate entries in the .bib file. That is why HTML compiled properly, but Xelatex broke. Removing the duplicate entries in the .bib file fixed the issue.

**Comment by yihui** [comment]
Okay, good to know.
