### ISSUE TITLE
New book written with bookdown

### ISSUE THREAD

**Issue by yijutseng** [rstudio/bookdown#337]
Thanks for the amazing bookdown package! 

I am writing a book with bookdown in **Traditional Chinese**. This book covers basic R programming and how to use R to import, manipulate, analyze, and visualize your data. However, this book is not published to bookdown.org. That will be great if this book can be list on bookdown.org.

The book is published here: http://yijutseng.github.io/DataScienceRBook/

Thanks!

YiJu

**Comment by yihui** [comment]
Thanks! The book looks great! I'll add it the next time I update the bookdown homepage.

**Comment by yihui** [comment]
Done.

**Comment by yijutseng** [comment]
Hello,
I found that the book http://yijutseng.github.io/DataScienceRBook/ is not on the bookdown homepage now. Could you please re-add the link? Thanks!

**Comment by yihui** [comment]
Sure. I will (in a couple of weeks, though).

**Comment by yihui** [comment]
Done: https://bookdown.org/home/archive/ Thanks!
