### ISSUE TITLE
with packrat, rmarkdown::render_site() fails on RStudio button, but not in console

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#338]
This is a weird one, and it's quite frustrating (as I find some things `packrat`...).

To make sure this isn't a problem with my setup, the problem can be reproduced from the `bookdown-demo` boilerplate thus (see [my fork](https://github.com/maxheld83/bookdown-demo)):

1. `packrat::init()`
2. for example, `install.packages("DT")` (must be commented out)
3. `library("DT")` somewhere in the code
4. `packrat::snapshot()`
5. Try and compile.

Oddly, when I click the RStudio `build book` button, the invoked `rmarkdown::render_site(encoding = 'UTF-8')` fails with:

```
==> rmarkdown::render_site(encoding = 'UTF-8')

  |......                                                           |   9%
   inline R code fragments

  |............                                                     |  18%
label: setup


processing file: bookdown-demo.Rmd

Quitting from lines 20-26 (bookdown-demo.Rmd) 
Error in library(DT) : there is no package called 'DT'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted

Exited with status 1.
```

This is evidently false, because there *is* a `DT`, and it loads just fine on the console, it's also in the `packrat.lock`, and in `packrat/src` and `packrat/lib`.
The problem isn't specific to `DT`, happens with all sorts of packages.

**Invoking the *very same command* (`rmarkdown::render_site(encoding = 'UTF-8')`) via the RStudio console, baffingly, works just fine and compiles the book without incident.**

Let me know if you need gifs.

This is driving me a little crazy.

----

This is me:

- macOS Sierra 10.12.3 (16D32)
- RStudio Version 1.0.136

`sessionInfo()`:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DT_0.2        bookdown_0.3  rmarkdown_1.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9.2   packrat_0.4.8-1 digest_0.6.12   rprojroot_1.2   backports_1.0.5 magrittr_1.5    evaluate_0.10   highr_0.6       stringi_1.1.2   tools_3.3.2    
[11] stringr_1.1.0   htmlwidgets_0.8 yaml_2.1.14     htmltools_0.3.5 knitr_1.15.1
```

`brew list --versions`:

```
boost 1.63.0
cairo 1.14.8
fftw 3.3.6-pl1
fontconfig 2.12.1_2
freetype 2.7.1
gdk-pixbuf 2.36.2
gettext 0.19.8.1
git 2.11.1
glib 2.50.2
gobject-introspection 1.50.0
harfbuzz 1.4.2
highlight 3.34
hugo 0.18.1
icu4c 58.2
imagemagick 7.0.4-6 7.0.4-7
jpeg 8d
libcroco 0.6.11
libffi 3.0.13
libpng 1.6.28
librsvg 2.40.16_1
libtiff 4.0.7_2
libtool 2.4.6_1
libyaml 0.1.7
lua 5.2.4_4
openssl 1.0.2k
pandoc 1.19.2.1
pandoc-citeproc 0.10.3 0.10.4
pango 1.40.3
pcre 8.39
pixman 0.34.0
pkg-config 0.29.1_2
readline 7.0.1
ruby 2.4.0
shared-mime-info 1.8
xz 5.2.3
```

----

Ps.: apologies if this is the wrong repo; I am never quite sure which part of the build stack (`bookdown`, `rmarkdown`, `RStudio` is responsible).

**Comment by kevinushey** [comment]
The problem here is likely that RStudio is running that RMarkdown command in a new R process that doesn't inherit the library paths of the original process (so that process doesn't know about / have access to the packrat private library)

I believe this is an issue that is fixed on the RStudio side in the latest daily build, if you want to give that a shot (just for testing):

http://dailies.rstudio.com/

**Comment by maxheld83** [comment]
yes, thanks @kevinushey I can confirm that the problem does not occur with RStudio `1.1.71`. 
Guess this can be closed then.

Hope this'll make it to a (preview) release soon!

Sorry for reporting this in the wrong place (since this apparently has nothing to do with `bookdown`.)

**Comment by kevinushey** [comment]
No worries at all -- it's often not obvious where the actual issue lies for things like this (especially re: R package + RStudio interactions), so regardless of where the issue is posted we're happy to re-route it to wherever it's most appropriately tracked.
