### ISSUE TITLE
make bookdown clean up merged `bookdown.rmd`s on failed builds

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#339]
I'm using the merge-then-compile strategy for `bookdown`, so the first thing it does is create some merged `bookdown.Rmd` (or `project-name.Rmd`).

When the build succeeds, this temp file is deleted.

However, if it fails (early) as in #338, that `project-name.Rmd` remains at root.

I understand that this might be helpful for debugging, but it can also be very confusing, when tired me thinks it is the *actual* source and starts editing it, or, worse, when the *next* build actually thinks it's just another chapter.
Also makes it easy to pollute the commit history.

Any chance to

1. delete this on failed builds, too?
2. mark this as `_project-name.Rmd`?
3. move this to the temp folders `_bookdown_files/` on fail? (I know that's bad, because in debugging, the relative paths then no longer make sense ...)
4. automatically gitignore this?

Again, I understand that it's crucial for debugging, just wondering whether other people are also shooting themselves in the foot with this.
I am, frequently.

Will probably add a physical post-it note to my laptop to that effect 😸

**Comment by yihui** [comment]
If you install the devel version of bookdown, this merged Rmd file will be marked as read-only, so you cannot really edit it.

When building a book fails, I think the natural thing to do is to fix the error and build again, in which case the merged Rmd will be deleted as you mentioned.

In any case, this Rmd will never be treated as a chapter by bookdown. I do have an internal check to make sure it is excluded when all Rmd files are merged.

When I work with GIT, I always make sure I understand the newly appeared files before I commit them. Anyway, sorry for the trouble!
