### ISSUE TITLE
In gitbook, is there an equivalent of the latex \part?

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#34]
Many books are big enough that they need some organisation of chapters (e.g http://adv-r.had.co.nz). Does gitbook/bookdown offer any tools for this?

**Comment by yihui** [comment]
Not yet. I guess it is simple to support LaTeX output. For HTML, it might be a little tricky, but I guess all you want is the part titles in the TOC, right?

**Comment by hadley** [comment]
Yeah - they're like an additional level above the current h1's.

**Comment by lmullen** [comment]
I would be glad for this feature too.

**Comment by yihui** [comment]
Implemented and documented at https://bookdown.org/yihui/bookdown/markdown-syntax.html

**Comment by hadley** [comment]
In the sidebar, part headings appear to be links, but don't do anything when clicked. (Should be able to see in ~5 minutes on http://r4ds.had.co.nz)

**Comment by yihui** [comment]
Yeah I noticed this yesterday and just replaced the links `<a>` with `<span>` so they are not clickable. The default color might be a little light, but it should be easy to customize, e.g.

```css
li.part span {
  opacity: 1;
}
```

**Comment by hadley** [comment]
Great, thanks!

**Comment by ericpgreen** [comment]
@yihui nice addition. Is `li.part.span` intended to go in the `style.css` file? I tried it there with no luck. I thought it might go in the `toc.css` file, but all of these entries begin with `#TOC`.

**Comment by yihui** [comment]
@ericpgreen It does not matter. It can be in any .css file, as long as it is included via the `css` option. 

```yaml
---
output:
  bookdown::gitbook:
    css: anyfile.css
---
```
