### ISSUE TITLE
Bookdown not building book due to "xelatex" issue

### ISSUE THREAD

**Issue by heardca** [rstudio/bookdown#340]
Hi,

I've tried downloading the basic package of Latex using the MiKTeX installer however, it won't download because of the following issue:

FATAL mpmcli - Info: path="C:\Users\heardca\AppData\Local\Programs\MiKTeX 2.9\miktex/bin\MiKTeX209-core.dll", hr="Access is denied.

Has anyone encountered this problem before? I have tried googling for some answers, but am yet to find one. I know that Latex is required only if you want to convert your book to PDF, but I am also having an issue when trying to build a book in R. 

I followed the [instructions](https://bookdown.org/yihui/bookdown/get-started.html) of how to get started and have pulled up the R project file and the index.rmd in R Studio, however I am getting an error when I try to build the book:

output file: bookdown-demo.knit.md
Error: Failed to compile bookdown-demo.tex.
In addition: Warning message:
running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 127 
Execution halted
Exited with status 1.

I do not have great experience with debugging code, so I was hoping that someone could possibly explain what this means and how I can resolve the issue. 

Thanks!

**Comment by yihui** [comment]
Sorry, I have no idea about what that error message means. Windows always has all kinds of weird permission problems...

**Comment by vaclajon** [comment]
I had the same problem using MiKTex. After uninstalling and installing TidyTex via RStudio everything works as expected.
