### ISSUE TITLE
Modify css for example block

### ISSUE THREAD

**Issue by ekstroem** [rstudio/bookdown#341]
I've been trying to find out how to modify the gitbook output using css for an example block. If I have the following code:

    yada yada yada

    ```{example, mylabel, name="Exposure to smoking among children"}
    In an experiment we have 5 variables: `Gender`, `Smoke`, age in years (`Age`), and height
    (`Ht`). The first eight observations are shown in Table \@ref(tab:fevtable).                                                                                                                 
    ```
This renders nicely: I get the "Example" prefix with the proper numbering and the name in parentheses. All is well. I'd like to modify the background through css but when I look at the output the example is not wrapped in a `span` or a `div` but is just a regular paragraph.

Alternatively I tried to define my own block

    ```{block2, type="myex", name="Exposure to smoking among children"}                                                       
    same stuff as above
    ```

Here I can modify the css using the code below but there is no prefix and I also cannot figure out how to pass the `name` argument along. Also it would be better to have the same block work directly with all types of output. 

Is it possible to wrap the example block in a span/div?

Example css

```
div.myex {
    padding-left: 20px;
    padding-top: 18px;
    padding-bottom: 18px;
    padding-right: 10px;
    background-color: #dadada;
    border-top: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
    border-radius: 15px;    
    margin: 5px;
    text-indent: 23px;    
}
```

**Comment by yihui** [comment]
The example block is wrapped in `<div class="example"> </div>`. You can take a look at the HTML source of the example block at https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html

**Comment by ekstroem** [comment]
It isn't with the most recent version of bookdown (v 0.3.10) I just downloaded. Here the following code

    ---
    title: "Test McTest"
    date: "`r Sys.Date()`"
    site: bookdown::bookdown_site
    output: bookdown::gitbook
    ---

    Testy

    ```{example, mylabel, name="Smoking"}
    Example block                            
    ```


    ```{block2, type="eksempel", name="Smoking"}
    Example block2                               
    ```

will result in this html-output (partly clipped):


```
<section class="normal" id="section-">
<div id="header">
<h1 class="title">Test McTest</h1>
<h4 class="date"><em>2017-03-08</em></h4>
</div>
<p>Testy</p>
Example 1  (Smoking) Example block
</div>
<p></p>

<div class="eksempel">
Example block2
</div>
<p></p>
</section> 

```   

The default example is not wrapped in an example div but formats the example title, numbering and label correctly. The `block2` does wrap it in the class specified but the label is lost.

**Comment by yihui** [comment]
Is your `rmarkdown::pandoc_version()` 1.17.2? Currently we only support this version, and there some [known bookdown issues](./300) with higher versions of Pandoc.

**Comment by ekstroem** [comment]
Yup. That did it. Was running 1.19.1. Sorry for the noise

**Comment by yihui** [comment]
Great. I'll definitely think about workarounds for Pandoc 1.19 in the future. You are not the only one who ran into this issue.

**Comment by yihui** [comment]
Pandoc 1.19.x should work with the development version of bookdown now:

```r
devtools::install_github('rstudio/bookdown')
```

**Comment by ekstroem** [comment]
Wonderful. Will give it a go

**Comment by suknat** [comment]
I've been trying to modify the example block to make it look like the examples given in the book. 

I added the following to `style.css`
```
.example {
    padding: 1em 1em 1em 4em;
    background: #dadada 5px center/3em no-repeat;
    border-radius: 15px;    
    margin-bottom: 10px; 
    text-indent: 40px;
    background-image: url("./icons/example-small.png");
}
```

Unfortunately it results in a duplication of the icon, screenshot below.
![Screenshot 2020-05-12 at 15 03 21](https://user-images.githubusercontent.com/16538950/81701302-ba815c80-9461-11ea-9bee-c95931046f65.png)

Any help on how to fix this is much appreciated!

**Comment by suknat** [comment]
Help! 

I removed the icons (after posting the above response) and built the book (gitbook) to find everything was working fine. 

I then built the PDF to find that all exercise and example blocks had disappeared and now they do not appear even in gitbook output!

How do I go about restoring the blocks? All other elements such as figures and tables are appearing properly - only the example and exercise blocks have vanished!

**Comment by cderv** [comment]
You may have better chance of getting help if you ask your question on QA site like https://community.rstudio.com 

Commenting on an old closed issue is not the best place. It does not help to see clearly what is going on in your case. 

I'll be happy to look into it there if you explain the step to reproduce your issue. There is a broad community ready to help there too. 

Thank you !

**Comment by suknat** [comment]
Hi - many thanks for reaching out and apologies for posting here! I've now created a new post [here](https://community.rstudio.com/t/bookdown-blocks-not-rendering-correctly-now-not-rendering-at-all/65790) as you suggested, that hopefully explains things better!
