### ISSUE TITLE
figure-latex/ directory missing

### ISSUE THREAD

**Issue by antaldaniel** [rstudio/bookdown#342]
I am trying to add a custom cover image into the bookdown pdf output by saving the tex file and adding manually the cover.  Unfortunately, the intermediary file that I get refers to pdf versions of plots, and the tex refers to a non-existing or not-kept directory 

>bookdown-demo_files/figure-latex/

After compilation obviously the compiler does not find these files.   Is there a way to keep this auxiliary directory?

I have tried to specifically pass to render(...) 
>intermediates_dir = "tmp"

I have two motivations for more access to the .tex file.  First ,to be able to use a custom cover in pdf.  

This is the change I am trying to make, currently quickly capturing and copying` bookdown-demo_files/figure-latex/` to a different folder before it gets cleaned up. I think it should optionally stay, as well as the epub files. 

`\begin{document}`
`\begin{center}`
`\includegraphics{_images/cover.pdf}`
`\end{center}`
` %  \maketitle    removed and replaced with cover.pdf`

It would be very logical to include this in the `before_body` optional .tex but currently it is placed the `\maketitle `which thus cannot be by-passed. Logically, the whole titling should go to the **before_body** invoked from  `_output.yml` where more (or less!) elaborate titling, or just the insertion of pre-created pdf file could take the place of the cover.  If the current titling would go explicitly into a `before_body.tex` it could be replaced or amended easily.  Generally, I think it is easier to create a nice front and back cover, even in Rmarkdown, and paste it to the bookdown document, similarly to the epub `cover-image` option than do it via the .yaml parts. 

The other issues to have more access to the tex file is some [internalization complications](https://github.com/rstudio/bookdown/issues/344) with non-English/non-Chinese texts.

**Comment by yihui** [comment]
I think editing the .tex output manually is a bad idea in general. You will lose changes the next time you compile the book. That said, the way to preserve the figure-latex/ directory is to set `keep_tex: true` under `bookdown::pdf_book`, but please note the .tex file is generated to `_book/` and `figure-latex/` is generated to `_bookdown_files/`, so you have to move .tex to `_bookdown_files/` before you can compile it.

I don't which publisher you are working with, but I have worked with Chapman & Hall, and I don't need to worry about cover images. They will design the covers and print them. I only need to submit the manuscript generated from bookdown.

It might be easier for you to use PDF processing tools (such as `pdftk`) to insert your cover image instead of hacking at the LaTeX level.

**Comment by antaldaniel** [comment]
Hi Yihui, 

When I wrote this remark, even though the settings were as you said, for some reason with `keep_tex: true` I kept getting a .tex file and a deleted `figure-latex/` folder. I updated my Latex compiler, the plugins, and currently I have no problem, the figure-latex folder is in place, so I cannot reproduce that problem, and it may had been some bad configurations that I cannot think of.  

On the more general idea, I agree with you than manually tinkering with the cover is a very bad idea. However, the "books" I am making are just very long technical documents without a book publisher that need a cover. It is indeed a pain to manually edit the .tex file, they are research reports that are 80-120 pages long. So bookdown is a superb improvement compared to RMarkdown, but more control on the cover and pagination would be great.  Apart from the simple cover insertion I use the `\documentclass [openany] {book}`  setting manually, which is also a very natural demand in book-length but not book documents, where empty chapter divisions are not required. 

So, all in all, I am not making books with bookdowns, but many repeating (and multi-language) reporting. 

On the end of this lengthy comment I just want to say a very big thank you for bookdown in general. It is an extremely useful tool.

**Comment by yihui** [comment]
Okay, I see. Thanks for the explanation!

**Comment by wuffi** [comment]
I'm afraid that, despite using the `keep_tex` option, I am experiencing the same problem.  
I can see the directory and figures being niceley generated, but in the end, they all get deleted.  
Keeping the directory would potentially be helpful for including figures in a presentation, for example.
