### ISSUE TITLE
[Question] how to cross-reference panels of figure?

### ISSUE THREAD

**Issue by qifei9** [rstudio/bookdown#343]
For exmaple, I have code:
```
```{r nice-fig, echo = F, fig.cap = 'Nice figure. (a) Left part. (b) Right part.', fig.align = 'center', fig.pos = 'htbp', out.width = '50%'}
knitr::include_graphics(c("a.eps", "b.eps"))
\```
```
How could I reference the panels separately as `Figure 1a` and `Figure 1b`? I am using `bookdown::pdf_document2` output format.

**Comment by qifei9** [comment]
I found it is `Figure \@ref(fig:nice-fig1)` for `Figure 1a` and `Figure \@ref(fig:nice-fig2)` for `Figure 1b`.

**Comment by qifei9** [comment]
Just one question: if I have 11 figures in 11 chunks, and each figure has 2 panels. Then if the 11 chunks are named as `f1`, `f2` ... and `f11` respectively. Then the code `Figure \@ref(fig:f11)` will ref the `Figure 1a` or `Figure 11`? I tested it...

---

`fig:f11` is `figure 4`, with

    ```{r f1, fig.cap = '1'}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
  
    ```{r f11, fig.cap = '11'}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
in `.tex` file, 2 figures with label `f1`, 2 figures with label `f11`. It looks weird as `\caption{\label{fig:f1}1}`

---

`fig:f11` is `figure 1`, with

    ```{r f1, fig.cap = '1', out.width="100%"}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
  
    ```{r f11, fig.cap = '11', out.width="100%"}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
in `.tex`, 4 figures, `f11`, `f12`, `f111`, `f112`.

---

`fig:f11` is `figure 2`, with

    ```{r f1, fig.cap = '1', out.width = "50%", fig.show = 'hold'}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
    
    ```{r f11, fig.cap = '11', out.width = "50%", fig.show = 'hold'}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
in `.tex`, 2 figures, `f1` and `f11`.

---

`fig:f11` is `figure 2`, with

    ```{r f1, fig.cap = '1', out.width = "50%", fig.show = 'hold', fig.subcap=''}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
    
    ```{r f11, fig.cap = '11', out.width = "50%", fig.show = 'hold', fig.subcap=''}
    plot(1:10, cex = 10)
    plot(1:20)
    ```
in `.tex`, 2 main figures labelled `f1` and `f11`; 4 sub figures labelled `f11`, `f12`, `f111` and `f112`.

**Comment by yihui** [comment]
When you have multiple plots per chunk, I recommend you to use `fig.show="hold"` as in your third example, in which case your figure label is more predictable. If you do not want to hold two plots in the same figure environment, I recommend you to use two separate code chunks.

It is hard to generate consistent figure labels in all cases, so I'd ask you to do me a favor and try to generate one figure environment per code chunk :)
