### ISSUE TITLE
Internalization: changing word ordering

### ISSUE THREAD

**Issue by antaldaniel** [rstudio/bookdown#344]
There are two questions related to the Internalization chapter.  I am working on a series of research reports, or rather books on an international research project that has to be produced in four or five Latin-character languages. Producing the English version is easy following the excellent authoring documentation. However, internalization appears to be painful, because there are virtually no examples (apart from non-Latin, Chinese) books, and the examples are not clear to me in the book. 

In a language where Chapter 1 would be like 1. fejezet, you would need to use this recommended approach:

>  R function that takes the chapter number as the input and returns a string as the new chapter number 
 >(e.g.,` !expr function(i) paste('Chapter', i)`). If it is a character vector of length 2, the chapter title prefix 
> will be `paste0(chapter_name[1], i, chapter_name[2])`, where i is the chapter number.

I assume that something like 
>` r paste0(i, ". fejezet")`  

should work (among the ' `...` ') code quotes, but I wonder how I can retrieve the chapter number and passed it to [`i`], and how can have the expression evaluated from the` _bookdown.yml `file.  It is unclear to me in the example how can I get
>` !expr function(i) paste('Chapter', i)`

executed (and why` !expr `? )

Furthermore, I wonder if this approach can be taken to other possible label elements, such as
> `tab: 'Table "`

if it should become 1.1. táblázat? 

A workaround to internalization would be relying on the .tex output created for `pdf_book()` but as I [reported earlier](https://github.com/rstudio/bookdown/issues/342), the .tex file cannot be compiled because it refers to temporary directory that I cannot retrieve.  I generally believe that with more and more languages tried in bookdown, there will be other issues unexpected from an English/Chinese background, and a first step could be tinkering the .tex file, and then possibly adding a bit more internalization features to bookdown.

**Comment by yihui** [comment]
I believe you can use either `!expr function(i) paste0(i, '. fejezet'))` or `["", ". fejezet"]`.

`!expr` is a special token defined by the R package [yaml](https://cran.rstudio.com/package=yaml) to treat the value as an R expression to be evaluated.

For other labels, there are no ways to customize the order of the labels and numbers. Sorry.
