### ISSUE TITLE
Parameterised books

### ISSUE THREAD

**Issue by psychemedia** [rstudio/bookdown#346]
`rmarkdown` provides a straightforward way of generating multiple, parameterised reports from a single, base "master report", configured by passing in parameter values from the `rmarkdown:render` function ([*RStudio/RMarkdown* Parameterized Reports](http://rmarkdown.rstudio.com/developer_parameterized_reports.html)):

````
rmarkdown::render("MyDocument.Rmd", params = list(
  region = "west"
))
````

How can a book be generated as compilation of a set of reports? eg something like:

````
bookdown::render("ParameterisedDocument.Rmd", params = list(
  list(region = "west", otherparameter=1),
  list(region = "east", otherparameter=2)
))
````

concatenating separate sections of the report from a `ParameterisedDocument.Rmd` with parameter values  `list(region = "west", otherparameter=1)`, for the first part, `list(region = "east", otherparameter=2)` for the second etc?

What about if I also wanted to top and tail the book with a `openingPart.Rmd` and a `closingPart.Rmd`?

i.e. how would I construct something with the sense of:

`rmd_files: ["openingPart.Rmd", list(base ="ParameterisedDocument.Rmd", params = list(
  list(region = "west", otherparameter=1), list(region = "east", otherparameter=2) ) ),  "closingPart.Rmd"]`

**Comment by yihui** [comment]
`bookdown::render_book()` has a `...` argument that is passed to `rmarkdown::render()`, which means you can certainly pass the `params` argument there.

For the second question, no, there is not possible (well, it is, but not straightforward).

BTW, I don't know where you got the idea

```r
params = list(
  list(region = "west", otherparameter=1),
  list(region = "east", otherparameter=2)
)
```

but even with `rmarkdown::render()`, you cannot pass a list of lists of params. You have to do the explicit loop by youself, and pass one set of params each time.

**Comment by psychemedia** [comment]
Re: the idea:

    params = list(
      list(region = "west", otherparameter=1),
      list(region = "east", otherparameter=2)
    )

it was just pseudo-code. My use case is I want a report in book form with an intro, a summary, and then N intermediate chapters which are all generated from the same template but with different parameters.

**Comment by quantitative-technologies** [comment]
@psychemedia this is exactly what I want to achieve. 

It's the obvious way to report on multiple experiments that only differ in parameters.

**Comment by zachary-waller** [comment]
Not sure if anyone is still playnig around with this, but I've made a repository that does this:
https://github.com/zachary-waller/parameterised_bookdown
It's very bare bones, but basically takes the same approach as what bookdown does. I hope it helps someone out!

**Comment by psychemedia** [comment]
@zachary-waller This is back in scope for me atm... will check your repo out.

One thing that occurred to me is incrementally adding to a report. Eg you are producing a set of monthly reports as part of an annual report, and want to run the script to add each month to the current report. I guess setting caches up properly may help with that.
