### ISSUE TITLE
Remark chunk with name given does not show "Remark" in word_document2 and html_document2

### ISSUE THREAD

**Issue by ugroempi** [rstudio/bookdown#347]
Hi Yihui,

first, thank you very much for providing bookdown. 

I think that I may have found a small bug for the remark engine: if I specify a name (like in 
```` ```{remark, relconceven, relation between concentrated and even case}````
), word_document2 and html_document2 only display the name and omit the "Remark" portion in front of that name. 

By the way, I only decided to give names because remarks apparently cannot be numbered (I wanted to avoid redefining anything); being able to number them would also be quite nice.

Thanks and regards,
Ulrike

**Comment by yihui** [comment]
I don't remember what I was thinking when implementing this feature, but I think you are right that the "Remark" portion should not have been omitted. It should be fixed now. Thanks for the report!
