### ISSUE TITLE
Question / Feature request: author affiliation in pdf?

### ISSUE THREAD

**Issue by ugroempi** [rstudio/bookdown#348]
Hi Yihui,

I notice that I can use YAML
author:
  name="Ulrike Grömping"
  affiliation="Beuth"
for html-output with html_document2, while the pdf will then show the author as "true" (and a word document will not show any author information). It would be great if the affiliation YAML would work for all output types.

Is there any simple way for me with the current status of Rmarkdown / bookdown for automatically giving an author affiliation in PDF output? 

Best, Ulrike

**Comment by ugroempi** [comment]
Just answered the question myself: If I can do without a date, I can simply add the affiliation in the YAML date field, i.e.
author: "Ulrike Grömping"
date: "Beuth"

Best, Ulrike

**Comment by yihui** [comment]
I'm afraid that abusing the `date` field is the best solution, considering the support for all output formats. Otherwise you will have to define custom templates.

**Comment by znmeb** [comment]
I think you can also pass this information to Pandoc via the custom Pandoc hooks in R Markdown. I did that once for some LaTeX thing and it worked.

**Comment by yihui** [comment]
It is not Pandoc hooks but Pandoc variables. You can certainly do that, and you have to define your templates. It is easy to support one specific output format (except Word and EPUB), e.g. https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/jss_article/resources/template.tex, but considering all output formats, I'd rather use the `date` field instead (it even works for Word and EPUB).
