### ISSUE TITLE
Missing title?

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#35]
On http://www.frontendhandbook.com, when you hover over the top navbar, the name of the book comes up. That doesn't happen with bookdown, and when I look at the source the `<h1>` in the navbar is empty.

**Comment by hadley** [comment]
Ah, that's what I'm missing. Maybe it should be a parameter to gitbook?

**Comment by yihui** [comment]
Probably not. This `title` field in YAML works for all output formats. It is not specific to gitbook.

**Comment by hadley** [comment]
Normally the title applies per document. Here it affects multiple `.md` files - to me that feels like it should be a parameter of the output format.
