### ISSUE TITLE
Percentages in fig.cap for pdf output

### ISSUE THREAD

**Issue by ekstroem** [rstudio/bookdown#350]
I'm slightly puzzled as to why this is giving problems: When I produce pdf-output and have a figure caption that contains a `%` then the caption is rendered incorrectly in the pdf output. 

    --- 
    title: "A Minimal Example"
    site: bookdown::bookdown_site
    output: bookdown::pdf_book
    documentclass: book
    ---

    # Prerequisites

    ```{r boxplots2, echo=FALSE, fig.show = 'hold', out.width='50%', fig.cap='This is 50%.'}

    plot(1, 1)
     ```

I'm guessing that the `%` is parsed as a comment when the TeX file is rendered. Can it be escaped? `\%` doesn't appear to work.

**Comment by zeehio** [comment]
LaTeX requires `%` to be escaped. Thus LaTeX wants `\%`. But the thing you write inside `fig.cap=''` is parsed by R before, and R requires `\` to be escaped.

Therefore if you use `fig.cap = "Percentage \\%"` R will parse it into `\%`, and LaTeX will change it into `%` showing what you want to see.

**Comment by zeehio** [comment]
Final tip: In a similar way, LaTeX code is possible in the caption if `\` is escaped:

`fig.cap='Frequency \\%. See \\href{https://github.com/rstudio/bookdown/issues/350}{Issue 350} to understand why we are escaping the backslash'`

**Comment by yihui** [comment]
Do not wrestle with backslashes. You can never stop it once you start it :) Use text references instead: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references

**Comment by ekstroem** [comment]
Thanks
