### ISSUE TITLE
bookdown tufte table of contents and list of figures/tables not working

### ISSUE THREAD

**Issue by njtierney** [rstudio/bookdown#351]
Hi there!

Thanks again for making such a great package!

I'm using the bookdown tufte format, specifically for the format of a thesis. I'm trying to add a table of contents, but it is blank when I do so. You can see an example of this here: https://github.com/njtierney/thesisdown-tufte

I am also trying to work out how to add sections prior to the chapters that do not have numbered sections, but I can't work out how to do this, do you have any suggestions?

Apologies if this would be more appropriate in the [tufte](https://github.com/rstudio/tufte) repo, I just felt like it was more related to using bookdown - but please let me know if you would prefer it in bookdown.

**Comment by yasirs** [comment]
Were you able to find out why it is not generating the TOC?

**Comment by njtierney** [comment]
Unfortunately not yet! Have you had any luck with this?

**Comment by yasirs** [comment]
Ok, so I don't have the answer yet, but I am investigating. Do you have `  keep_tex: yes' in the output section of your yml? 

In the generated tex file, I had
```tex
{
\setcounter{tocdepth}{1}
\tableofcontents
}

```

When I compile this .tex file on the command line (after putting the picture files in the path needed), the TOC doesn't show up. But when I comment out the line `\setcounter{tocdepth}{1}` and compile, the TOC shows up. Is it the same in your case?

**Comment by yihui** [comment]
@yasirs is correct that the .tex file needs to be compiled one more time. This is probably a bug of `latexmk`, though (rmarkdown calls `latexmk` to compile .tex to PDF by default if it is installed).

If you use macOS, you can remove `latexmk` via:

```r
sudo tlmgr remove latexmk
```

If you use Windows, I think `latexmk` can also be removed through the MiKTeX package manager. For Linux users who use the Debian `texlive-*` packages, I don't know how to remove `latexmk`.

Once `latexmk` is removed, rmarkdown will use the fallback method to compile .tex, i.e. run pdflatex (or xelatex) once, then bibtex/makeidx, then pdflatex twice. This will generate the TOC/LOF/LOT successfully for Tufte book PDF output.

**Comment by yasirs** [comment]
On OSX. I was nervous about removing it lest something breaks, but trying to remove latexmk gives:
```
tlmgr: not removing latexmk.universal-darwin, needed by latexmk
tlmgr: not removing latexmk, needed by collection-binextra
tlmgr: not removing latexmk.x86_64-darwin, needed by latexmk
tlmgr: no packages removed.
tlmgr: action remove returned a warning.
```
Also, on Windows, does pdflatex exist if you remove latexmk? Or do you have to install it?

**Comment by yihui** [comment]
I'm able to remove latexmk probably because I installed the basic/minimal MacTeX package.

`latexmk` is only a wrapper utility to execute pdflatex/xelatex/bibtex/makeidx for the correct number of times. None of these executives will be removed if you remove latexmk. Unfortunately latexmk is not really able to compile tufte book output for the correct number of times.

It should be fairly safe to remove it. If you are not sure, find out where it is installed (`which latexmk`), rename it temporarily (`sudo` required for `mv`), and see if anything breaks.

**Comment by njtierney** [comment]
This worked for me!

I just renamed latexmk to something else, then it created the ToC no problems.

**Comment by njtierney** [comment]
Hi @yihui !

I can't seem to get the List of Figures and List of Tables to generate, when I put them where the toc is placed [here](https://raw.githubusercontent.com/njtierney/thesisdown-tufte/master/index.Rmd)

See the [PDF here](https://github.com/njtierney/thesisdown-tufte/blob/master/docs/Thesisdown-tufte.pdf)

Is there perhaps something that I am missing for adding the list of figures/tables correctly?

Thank you once again!
