### ISSUE TITLE
knitr::write_bib() gives different bib entries from citation() 

### ISSUE THREAD

**Issue by dapengde** [rstudio/bookdown#352]
This is what I have found funny. If you run:
```
knitr::write_bib(c(
  .packages(), 'lattice', 'ggplot2'
), 'packages.bib')
```
you will get bib entries like:
```
@Manual{R-lattice,
  title = {lattice: Trellis Graphics for R},
  author = {Deepayan Sarkar},
  year = {2016},
  note = {R package version 0.20-34},
  url = {https://CRAN.R-project.org/package=lattice},
}
```
which is different from `citation('lattice')` 
```
@Book{R-lattice,
    title = {Lattice: Multivariate Data Visualization with R},
    author = {Deepayan Sarkar},
    publisher = {Springer},
    address = {New York},
    year = {2008},
    note = {ISBN 978-0-387-75968-5},
    url = {http://lmdvr.r-forge.r-project.org},
  }
```
So is ggplot2.

I have checked the source code of write_bib(), but have not got any idea of it.

**Comment by r-cheologist** [comment]
Write_bib appears to generate a generic citation for any R package based in its version. 
Citation returns wgat the package author wants it to ...

On Wed Mar 1 01:35:30 2017 GMT+0100, Peng Zhao wrote:
> This is what I have found funny. If you run:
> ```
> knitr::write_bib(c(
>   .packages(), 'lattice', 'ggplot2'
> ), 'packages.bib')
> ```
> you will get bib entries like:
> ```
> @Manual{R-lattice,
>   title = {lattice: Trellis Graphics for R},
>   author = {Deepayan Sarkar},
>   year = {2016},
>   note = {R package version 0.20-34},
>   url = {https://CRAN.R-project.org/package=lattice},
> }
> ```
> which is different from `citation('lattice')` 
> ```
> @Book{R-lattice,
>     title = {Lattice: Multivariate Data Visualization with R},
>     author = {Deepayan Sarkar},
>     publisher = {Springer},
>     address = {New York},
>     year = {2008},
>     note = {ISBN 978-0-387-75968-5},
>     url = {http://lmdvr.r-forge.r-project.org},
>   }
> ```
> So is ggplot2.
> 
> I have checked the source code of write_bib(), but have not got any idea of it.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/rstudio/bookdown/issues/35

-- 
Sent from my Jolla

**Comment by dapengde** [comment]
It seems so. 

Well, I am wondering what the experience really is, when a package author sees people show the respect to his/her work by citing in a biblio style which the author does not  recommend......

**Comment by dapengde** [comment]
This issue has been described in the [bookdown book](https://bookdown.org/yihui/bookdown/citations.html#):

>  write_bib() ... only generates one BibTeX entry for the package itself at the moment, whereas a package may contain multiple entries in the CITATION file, and some entries are about the publications related to the package. These entries are ignored by write_bib().

I prefer the way that the package authors suggest, since citations are to show respect or acknowledgement to the authors. Thus, I have written a function, which generates all the Bibtex entries suggested by the package authors:

```
mf_bib <- function(pkg = c('base'), bibfile = 'packages.bib'){
  pkg <- unique(pkg[order(pkg)])
  for (i in pkg){
    # if (class(try(citation(i))) == 'try-error') install.packages(i)
    cti <- toBibtex(citation(i))
    entryloc <- grep(pattern = '^@', cti)
    cti[entryloc] <- gsub(',', paste('R-',i, ',', sep =''), cti[entryloc])
    if (length(entryloc) > 1)  cti[entryloc] <- paste(substr(cti[entryloc], 1, nchar(cti[entryloc])-1), 1:length(entryloc), ',', sep ='')
    cat(cti, sep = '\n', file = mybib, append = TRUE)
  }
}
```

**Comment by yihui** [comment]
The only reason I didn't use the CITATION file was that I was not sure how to properly generate the keywords after `@type{`for bib entries, especially when there are multiple entries per package. I can probably use `R-lattice-1`, `R-lattice-2`, ... but what if the number of entries changes in the future... The only entry that I'm sure I can generate is the package itself.

That said, I do use CITATION occasionally, and I just cut-and-paste the entries provided by the authors.

**Comment by dapengde** [comment]
@yihui I agree with you. I have tested some bib entries suggested by package authors. Some authors provides too many entries, making my reference list very lengthy. Some entries are incomplete and have to be revised manually. I would follow your way. Thanks a lot!
