### ISSUE TITLE
citation addin fails if Chinese characters in yaml

### ISSUE THREAD

**Issue by dapengde** [rstudio/bookdown#355]
I am writing something in Chinese with bookdown.  When there is a Chinese character at the beginning of the index.Rmd like: 
```
title: "an R book"
author: "冏 Smith"
site: bookdown::bookdown_site
date: "`r Sys.Date()`"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: ieeetr
link-citations: yes
description: "This is an R book."
```
there appears an error in RStudio console panel when starting RSudio by double clicking the .Rproj file:
```
Error in yaml::yaml.load(string, ...) : 
  Reader error: control characters are not allowed: #8F at 34
```

`34` is exactly the location of 冏 counted from the first letter of index.Rmd.

Despite this error, the file can be compiled successfully. However, the citation addin fails if I click Addins - Insert Citations. The error massage is the same.

The solutions are:
1. Do not use the citation addin when editing, or 
2. leave the title and author fields blank or in English, feel free to use the citation addin. When the citation is finished, change the title and author to Chinese.

**Comment by crsh** [comment]
Hi, I'm the author of the [`citr`](https://github.com/crsh/citr) package that provides the "Insert citations" addin. I cannot reproduce the error. I don't know about the error related to `.Rproj` but I think think the problem with the addin may be related to the encoding of `index.Rmd`. Could you upload an `index.Rmd` file containing only the YAML header above after confirming that it produces the error?

**Comment by dapengde** [comment]
Hi. Thanks for the response. The YAML header in `index.Rmd` is just what I posted:

```
--- 
title: "an R book"
author: "冏 Smith"
site: bookdown::bookdown_site
date: "`r Sys.Date()`"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: ieeetr
link-citations: yes
description: "This is an R book."
--- 

# Preface

blablabla
```

Nothing else.

The error I mentioned appears when RStudio is loading the .Rproj file even if `citr` package is disabled.  My .Rproj file was the original one from the demo folder. Thus I think this error has nothing to do with  `citr` package (that was why I commented here rather than on the homepage of `citr`).

I guess the only thing related to `citr` is that `citr` dislikes the yaml loading error......

**Comment by yihui** [comment]
@dapengde Can you provide your `devtools::session_info('bookdown')`? The version of the yaml package has to be at least 2.1.14. If you have that version, I think **citr** might have some character encoding issues.

@crsh All bookdown Rmd files are assumed to be encoded in UTF8. If you scan them, you have to be explicit about the encoding, e.g. `readLines(encoding = 'UTF-8')`. Without the explicit encoding, things can get wrong on Windows (the default system encoding is not UTF-8 there).

**Comment by dapengde** [comment]
@yihui @crsh Days ago I reinstalled R and all the packages, and I did not use citr until today, and now the error is gone. Both yaml.load() and citr are fine. I don't know why ,but sorry for the noise.

The version of the yaml package in my PC is currently 2.1.14. Please see the session info as follows.
```
> devtools::session_info(('bookdown'))
Session info --------------------------------------------------------------------------------------------------------
 setting  value                                              
 version  R version 3.3.2 (2016-10-31)                       
 system   x86_64, mingw32                                    
 ui       RStudio (1.0.136)                                  
 language ZH                                                 
 collate  Chinese (Simplified)_People's Republic of China.936
 tz       Europe/Berlin                                      
 date     2017-03-10                                         

Packages ------------------------------------------------------------------------------------------------------------
 package   * version date       source                           
 backports   1.0.5   2017-01-18 CRAN (R 3.3.2)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.3.2)                   
 bitops      1.0-6   2013-08-17 CRAN (R 3.3.2)                   
 bookdown    0.3.10  2017-03-08 Github (rstudio/bookdown@536eb80)
 caTools     1.17.1  2014-09-10 CRAN (R 3.3.2)                   
 digest      0.6.12  2017-01-27 CRAN (R 3.3.2)                   
 evaluate    0.10    2016-10-11 CRAN (R 3.3.2)                   
 highr       0.6     2016-05-09 CRAN (R 3.3.2)                   
 htmltools   0.3.5   2016-03-21 CRAN (R 3.3.2)                   
 jsonlite    1.3     2017-02-28 CRAN (R 3.3.2)                   
 knitr       1.15.1  2016-11-22 CRAN (R 3.3.2)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.3.2)                   
 markdown    0.7.7   2015-04-22 CRAN (R 3.3.2)                   
 mime        0.5     2016-07-07 CRAN (R 3.3.2)                   
 Rcpp        0.12.9  2017-01-14 CRAN (R 3.3.2)                   
 rmarkdown   1.3     2016-12-21 CRAN (R 3.3.2)                   
 rprojroot   1.2     2017-01-16 CRAN (R 3.3.2)                   
 stringi     1.1.2   2016-10-01 CRAN (R 3.3.2)                   
 stringr     1.2.0   2017-02-18 CRAN (R 3.3.2)                   
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)               
```
