### ISSUE TITLE
Numbered parts and subnumbered chapters?

### ISSUE THREAD

**Issue by ratnip** [rstudio/bookdown#356]
Hi.

I'm trying to figure out a way to set up numbered parts (Part I - Basic Concepts, Part II - Introduction to functions etc.) and chapters with subnumbering (Chapter 1.1 - Basic elements etc.).

Is this possible or do I need to convert existing chapters to sections, which would be infeasible because Chapters are currently pretty big and I wouldn't want to merge them all in a huge RMD "chapter" just because of numbering issues?

**Comment by yihui** [comment]
Sorry. This is not possible in bookdown, and I have never seen such a numbering style for chapters by myself...

**Comment by brooksambrose** [comment]
I started a [question](http://stackoverflow.com/questions/43688902/how-do-i-control-part-numbering-in-gitbook-toc) on SO that is related to this.
