### ISSUE TITLE
Question: Support for inline comments when producing a gitbook

### ISSUE THREAD

**Issue by kikofernandez** [rstudio/bookdown#357]
Hi,

I was wondering if it would be possible to add inline comments via disqus when generating gitbooks. I have seen it [here](https://www.gitbook.com/blog/features/discussions) and I think it's great for authors looking for reviews before the book is published.
Thanks!

**Comment by yihui** [comment]
Disqus integration was introduced at https://bookdown.org/yihui/bookdown/collaboration.html

If you really mean _inline_ comments like comments on specific lines of a page, you may consider https://hypothes.is.

**Comment by kikofernandez** [comment]
ok, thanks for the alternative
