### ISSUE TITLE
Impossible to add numbered equations within a paragraph because Pandoc adds unwanted line breaks

### ISSUE THREAD

**Issue by Selbosh** [rstudio/bookdown#358]
Pandoc adds extra line breaks around LaTeX environments such as `equation`, `align` and friends. In regular R Markdown this doesn't crop up too often as a problem, because we tend to use `\[ \]` or `$$ $$` instead. But in `pdf_book` and `pdf_document2` we can't use bookdown's equation numbering extension within paragraphs without vertical spacing and indentation issues.

For example, a single paragraph sequence like
```latex
Lorem ipsum dolor sit amet,
\begin{equation}
E = mc^2,
\end{equation}
consectetur adipiscing elit.
```
is converted by pandoc into three paragraphs
```latex
Lorem ipsum dolor sit amet,

\begin{equation}
E = mc^2,
\end{equation}

consectetur adipiscing elit.
```
which is not the same thing in LaTeX at all. It changes the vertical spacing completely (especially egregiously for `align` and `align*`) and, if `indent: true` is set, then indents the following sequence of text. Adding `\noindent` everywhere is not a solution, especially as it does nothing about the vertical spacing.

There is a [related issue](https://github.com/jgm/pandoc/issues/2171) on the pandoc repository.  Does anybody know any tricks to stop Pandoc from doing this, or else a way to remove the line breaks just before converting to PDF?

**Comment by yihui** [comment]
It seems this has been fixed upstream https://github.com/jgm/pandoc/commit/8c55b7b5640e41feaae658e95e659bdd2101a340 and I cannot provide a workaround in bookdown.

**Comment by eslewis** [comment]
unsubscribe
