### ISSUE TITLE
example environment does not work on its own

### ISSUE THREAD

**Issue by dietrichson** [rstudio/bookdown#359]
Debug1.Rmd

This throws an error "! LaTeX Error: Environment example undefined."

However is I add a theorem like in debug2.Rmd it compiles without issue.
[debug.zip](https://github.com/rstudio/bookdown/files/827888/debug.zip)

**Comment by yihui** [comment]
Duplicate of #291. Please

```r
devtools::install_github('rstudio/bookdown')
```
