### ISSUE TITLE
Before_chapter_script doesn't work?

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#36]
In `_bookdown.yaml` I have:

```yaml
before_chapter_script: "_common.R"
```

and in `_common.R` I have:

```R
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  cache = TRUE
)
```

but the chunk options don't seem to have any affect.  What am I missing?

**Comment by yihui** [comment]
You didn't miss anything. I just didn't implement it for the case `new_session = TRUE`. Done now.

**Comment by hadley** [comment]
After this change I'm getting:

```
Error in insert_chapter_script(config, "before") : 
  object 'config' not found
Calls: <Anonymous> -> render_new_session -> insert_chapter_script
Execution halted
```

**Comment by yihui** [comment]
Ah, fixed now

**Comment by dereckdemezquita** [comment]
I know this is an old post; but I'm having this same issue. My before chapter script is not executing. I have the following set up:

- bookdown.yml

```
new_session: yes
language:
  ui:
    chapter_name: "Chapter "
delete_merged_file: true
before_chapter_script: "_common.R"
```

- _common.R

```
knitr::opts_chunk$set(echo = TRUE, fig.width = 7, fig.height = 7, fig.align = "center")
```

I've tried everything to fix it to no avail. I would appreciate any help you may extend. 

Might it possibly be the fact that I am using a "new_session: yes" for a K-M build mode? I saw that it was an issue when "new_session = TRUE"? I tried setting to TRUE/true in the yml and nothing.

**Comment by cderv** [comment]
Hi @dereckdemezquita, 

I can't reproduced. This is working fine for me using the [demo book](https://github.com/rstudio/bookdown-demo). 
I added a `_common.R` file with 
```r
knitr::opts_chunk$set(echo = FALSE)
```
and after building the book, all chunk source are correctly not shown. 

Can you try that too ? 

Also can you ask on [the RStudio community](https://community.rstudio.com/c/R-Markdown/10) or in a new issue, instead of an old issue ?  It will be easier to continue discussion. Thank you.

**Comment by hadley** [comment]
@dereckdemezquita I don't recommend using `before_chapter_script` — because it literally inserts that code into your .Rmd file, it messes up line numbers making debugging very painful. It's easier to just copy and paste a standard block at the front of every chapter.

**Comment by cderv** [comment]
> it literally inserts that code into your .Rmd file

I think this will only do that if `new_session: no`, i.e Merge and Knit approach. For `new_session: yes`, i.e Knit and Merge approach, it will the source the script before calling `render()` on each file. 

> It's easier to just copy and paste a standard block at the front of every chapter.

If one wants to follow this way, I would advice to use a child document, or import the `_common.R` file as chunk content to avoid copy pasting the same pieces of code and keep it all in the same place. Example: 
```md
```{r, include=FALSE, echo=FALSE, code = xfun::read_utf8('_common.R')}
```
````
or 
````md
```{r, child="_common.Rmd"}
```
````

> it messes up line numbers making debugging very painful.

Easier debug of Rmarkdown project seems a topic to invest in.

**Comment by hadley** [comment]
@yihui I didn't know that because you don't blog about it 😄 Regardless, I've now been burned by that behaviour, so I'm unlikely to use `before_chapter_script` again in the future.

**Comment by yihui** [comment]
@hadley Sorry, but I didn't know you were burned. Claus and Bob reported that this issue bothered them, so I made the change for them, but I had no idea how many more users were burned...
