### ISSUE TITLE
Long chapter names in the header

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#360]
When compiling to pdf, the chapter names show up in the header, which is nice.

But sometimes the name is too long and the header overflows. One can provide a shorter name for header purposes in Latex as discussed here: http://tex.stackexchange.com/questions/26234/chapter-title-in-header-too-long

How do we provide this alternative short name in .Rmd files? Or, as a second option, turn off the chapter names in the header?

**Comment by yihui** [comment]
I guess there is no way to provide short titles in the Markdown syntax. The LaTeX syntax is like `\chapter[short title]{long title}`. See more info at #295.

To turn off chapter names in header, you can use a certain `\pagestyle{}` in the LaTeX preamble (`plain`, or `empty`, or something else; you need to look it up in the LaTeX references).

**Comment by rdinter** [comment]
I recently ran into this problem. The workaround I found was to insert  `\usepackage{fancyhdr}` into my preamble and then for the `.Rmd` files I had problematic names for I would add the `\chaptermark{shorter-title}` right below the new Chapter. It would look something like this:

```
# A really long chapter title which would span the entire header and look awful
\chaptermark{My shorter version}

This is my content ...
```

So far so good, my pdfs render with the shorter version in the header but the table of contents contains the longer one.

**Comment by maxheld83** [comment]
Another way to go about this might be to do it the *other way around*, that is, to use *short* headings in markdown, and then to add un-`toc`ed latex headers for the long stuff, like so:

```
# My shorter version
\chapter*{A really long chapter title which would span the entire header and look awful}
<h1>A really long chapter title which would span the entire header and look awful</h1>
```

@VerenaKasztantowicz can you check whether this works for you?

Should works without any extra packages and get passable results.

of course, it remains a hack-fix, barring better pandoc support as mentioned in #295.

**Comment by maxheld83** [comment]
I've also raised this [at pandoc](https://github.com/jgm/pandoc/issues/3682)
