### ISSUE TITLE
Where to put custom templates for pandoc?

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#362]
I am trying to compile a bookdown book with a custom pandoc template that I created as `mytemplate.tex`.  In the _output.yml I have:
```
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
  template: mytemplate.tex
```

When I run Build Book from Rstudio, the build panel, it shows me:
```
/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS outfile.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output outfile.tex --table-of-contents --toc-depth 2 --template mytemplate.tex --number-sections --highlight-style tango --latex-engine /Library/TeX/texbin/xelatex --natbib --include-in-header preamble.tex --variable tables=yes --standalone --bibliography collection.bib 
pandoc: Could not find data file templates/mytemplate.tex
Error: pandoc document conversion failed with error 97
Execution halted

Exited with status 1.
```

I have `templates/mytemplate.tex ` in the project directory (where _output.yml, index.Rmd, and _bookdown.yml live). And I also copied it in the pandoc folder so `/Applications/RStudio.app/Contents/MacOS/pandoc/templates/mytemplate.tex` exists.

**Comment by yasirs** [comment]
Ok, I found the answer but it will be nice if this explained somewhere in the docs. Since the Rstudio build panel shows the location of the pandoc used, I was able to do
```
/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc --version
```
which spat out some version information along with the statement that the pandoc user directory is `~/.pandoc`. Now, if I put my templates in `~/.pandoc/templates/`, I can use it with bookdown by specifying in_output.yml as `  template: mytemplate.tex`.

**Comment by yihui** [comment]
It does not have to be that complicated. The template can be put under the root directory of your book, just like `preamble.tex`.

**Comment by dapengde** [comment]
I saw such a template file tailored for books in Chinese:
https://github.com/yihui/bookdown-chinese/blob/master/template.tex
wondering what the internal template looks like. Is there a built-in template.tex hidden somewhere? It would be helpful to get start from the default one and customize it. For example, I would like to forbid `maketitle` sometimes.

**Comment by yihui** [comment]
@dapengde https://github.com/rstudio/rmarkdown/tree/master/inst/rmd/latex

**Comment by dapengde** [comment]
Great! Now I can do anything to bookdown. Thanks!

**Comment by daijiang** [comment]
Is it possible to put the url of a template file as value of `includes` @yihui @pzhaonet ? For example:

```yaml
output:
  bookdown::pdf_document2:
    includes:
      in_header: https://raw.githubusercontent.com/.../x.tex
```

I can put the path of the template file in every Rmd file without duplicate it. But if I am collaborating with others, I need to copy the template file into all project root directories. Otherwise, my collaborators cannot render the file. Thus, it would be great if I can put the template online and just add the url in the yaml. This url way works for CSL files, but not for template files.

Thanks!

**Comment by yihui** [comment]
@daijiang No, unfortunately you cannot use a URL, but you can always use `download.file()`, e.g., https://stackoverflow.com/a/46333724/559676

**Comment by pzhaonet** [comment]
@daijiang @yihui 
I think you can.

@daijiang's question is how to share with colleagues some online resources in an .Rmd file, or more generally, in bookdown. It is a good idea to do so. You only have to maintain the online files and all your colleagues' work will be synced. Fortunately, it is possible if you use @yihui's suggestion of download.file() . I have two methods as follows.

1. You can use `download()` function in your .Rmd file. The target file will be downloaded to your local path. Then it can be specified in YAML. It looks like this:

```
--- 
title: "ttt"
author: "ddd"
output:
  bookdown::pdf_book:
    template: my_shared.tex
---

`r download.file('https://raw.githubusercontent.com/pzhaonet/bookdownplus/master/inst/tex/template_thesis_classic.tex', 'myshared.tex', mode = 'wb')` `` 

This is the beginning of my book. blahblahblah....


```

2. You could upload all your files onto a server, and share only an .R script file to your colleagues. Thus your colleagues only have to run the .R script and bingo! The compiled book is there. The .R script should look like this:

```
setwd()
download()
bookdown::render_book()
```

**Comment by daijiang** [comment]
Thanks @pzhaonet ! I ended with putting the rcode to download files in a set up chunk.
