### ISSUE TITLE
(ref:label) does not work in HTML and Word?

### ISSUE THREAD

**Issue by ugroempi** [rstudio/bookdown#363]
Hello everybody,

I am trying to use (ref:label) in order to make the row labels in my table appear in the desired formatting (italics and subscripts, mostly). After I managed to make things work in Latex, I had to realize that this apparently does not work correctly in Word and HTML ....

For two simple cases, I gave e.g. 

`(ref:PFT) *PFT*`

`(ref:a3) *a*~3~`

early on in the text. Later, I have a character matrix that contains a value '(ref:PFT)' or '(ref:a3)'. In PDF, I do get the desired result, but in HTML and Word (latest version as well as Word 2007) I run into problems: in HTML, I get the non-italic text "(ref:PFT)"; in Word, I do get the desired italic *PFT* (for example), but the column alignment of the table is messed up, with the next column being merged together with the column containing the "(ref:label)" entry for some rows. 

Am I doing something wrong, do the (ref:label) definitions work in PDF only, or is this a bug?

Best wishes, Ulrike

**Comment by yihui** [comment]
I don't know what you did exactly. Could you provide a reproducible example based on https://github.com/rstudio/bookdown-demo/?

**Comment by ugroempi** [comment]
I am working on an article, not a book, and I attach a (hopefully) reproducible example below - I can't make this one work in Latex (using Miktex pdflatex), but the behavior under Word and HTML is the same behavior I tried to describe above, and the same strategy (I can't find the difference ...) produced the desired table in a 20 page PDF document with several tables of this or a similar nature.

Best, Ulrike

[refdemo.zip](https://github.com/rstudio/bookdown/files/842848/refdemo.zip)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report and reproducible example!
