### ISSUE TITLE
Option to force top-level chapters

### ISSUE THREAD

**Issue by yasirs** [rstudio/bookdown#365]
If you use a custom class file, pandoc does funky stuff with the top level division. For example if your index.Rmd has the YAML saying `documentclass: custom`, it will make all the chapters in the .Rmd files to become sections. Please provide a way to specify this through bookdown. Pandoc has the command line option `--top-level-division=[default|section|chapter|part]`.

See view-source:http://pandoc.org/MANUAL.html and https://github.com/jgm/pandoc/issues/3197 for more information. If I do `top_level_division: chapter` in the index.Rmd YAML, bookdown spits an error. When I specified it in _output.yml, it didn't pass on the argument when calling the pandoc command.

**Comment by yihui** [comment]
`--top-level-division` is an argument of a newer Pandoc version than 1.17.2. We only support 1.17.2 at the moment, and the argument name is `--chapter` (deprecated in Pandoc 1.19.x), e.g. https://github.com/rstudio/bookdown/blob/c72a783a3/inst/examples/_output.yml#L29

**Comment by yihui** [comment]
You can use this argument with the development version of bookdown and Pandoc 1.19.x now, but you are recommended to use `--top-level-division=chapter`.
