### ISSUE TITLE
fontsize in documentclass

### ISSUE THREAD

**Issue by GuangchuangYu** [rstudio/bookdown#366]
I try to write `documentclass`, `hku.cls`, for `pdf_book`:

At the very beginning, the file just contains:

```
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{HKU}[2017/03/02 HKU thesis class]
\LoadClass{book}
```

and I specify `documentclass: hku` in `index.Rmd`, and then I find `fontsize: 12pt` wont work.

Even if I specify `fontsize` using `\LoadClass[fontsize=12pt]{book}`, the setting was also omitted.

If it was changed to `documentclass: book`, `fontsize` variable works.

This is quite weird.

**Comment by yihui** [comment]
I guess there is nothing I can do on my side; `hku.cls` has to support fontsize declarations. Basically bookdown generates

```tex
\documentclass[12pt]{hku}
```

in the .tex output, and it is totally up to the document class how the font size should respected.

Here is a SO post after a quick google search: http://tex.stackexchange.com/q/9908/9128

**Comment by GuangchuangYu** [comment]
my head is spinning and thanks for the link.
