### ISSUE TITLE
appendix numbering easily confused with titles

### ISSUE THREAD

**Issue by aronatkins** [rstudio/bookdown#367]
The HTML output renders appendix section "number"/title in a way that might be confusing to some readers. See this example from the bookdown book:
<img width="333" alt="screen shot 2017-03-14 at 9 27 14 am" src="https://cloud.githubusercontent.com/assets/362187/23902740/87c088fa-0898-11e7-88c5-dfdcd669bd28.png">

The default PDF rendering of the same content introduces enough padding. Here's an example from a different book (the bookdown book uses custom latex layout):
<img width="361" alt="screen shot 2017-03-14 at 9 30 11 am" src="https://cloud.githubusercontent.com/assets/362187/23902843/e09404e8-0898-11e7-86c9-5feb544bde85.png">

**Comment by aronatkins** [comment]
Playing around with the following as a workaround:
```css
.header-section-number {
    padding-right: 1em;
}
```

**Comment by yihui** [comment]
Thanks! I added `.5em` as the default right padding, but you can easily override it with your own CSS file.
