### ISSUE TITLE
Table caption not displaying in Word, if list of objects given to kable

### ISSUE THREAD

**Issue by ugroempi** [rstudio/bookdown#368]
Thanks for fixing things really fast!
I have one further possible bug: My Word version only shows (and counts) table captions for tables of a single object, not for lists of objects (not even for a list of a single object). 
For example, the code below produces tables without a caption in Word (using bookdown::word_document2), while the caption works fine in pdf and html.

```{r tab, echo=FALSE}
tab1 <- swiss[1:10,1:3]
tab2 <- swiss[1:10,4:6]
knitr::kable(list(tab1, tab2), caption="A table caption that is not shown in Word")
```

Best, Ulrike

**Comment by yihui** [comment]
Word is not supported and will not be supported in this case. Sorry.

**Comment by ugroempi** [comment]
I understand and respect the wish to keep things simple. However, wouldn't it (perhaps) be a simple hack with great benefit to treat lists of tables for Word such that the chunk is executed for the first element as if it were a single element and for the list of remaining elements exactly as it is now? That would fix the Caption and numbering / reference problem and leave the arrangement of tables to the user.

Best, Ulrike

**Comment by yihui** [comment]
I'll reconsider it. Thanks!

**Comment by yihui** [comment]
Fixed in the dev version of knitr. Thanks!
