### ISSUE TITLE
The parameter 'output_dir' in render_book function does not work with the Single Document Format

### ISSUE THREAD

**Issue by axitdn** [rstudio/bookdown#369]
The parameter 'output_dir' in render_book function does not work with the Single Document Format. 

When I run this script 
```
Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::tufte_html2',output_dir='_book')"
```
I expected that all document will be placed in the _book directory. But nothing that has happened.

**Comment by yihui** [comment]
That is by design. Please see the Note section in the help `?bookdown::tufte_html2`.
