### ISSUE TITLE
Weird styling of headings with code

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#37]
<img width="263" alt="screen shot 2016-03-04 at 9 22 47 am" src="https://cloud.githubusercontent.com/assets/4196/13531161/b8bc700c-e1ea-11e5-9f61-aeeac31bd3e3.png">

**Comment by hadley** [comment]
The problem seems to be that the section number is wrapped in `<span class="toc-section-number"></span>`, rather than `<b></b>` like the others.

**Comment by yihui** [comment]
Could you paste the HTML source of these two `<li>` items?

**Comment by yihui** [comment]
Fixed now. Thanks!
