### ISSUE TITLE
Extra white space around LaTeX environments

### ISSUE THREAD

**Issue by nicksolomon** [rstudio/bookdown#373]
Pandoc automatically inserts blank lines on each end of a LaTeX environment, so
```
\begin{equation*}
\end{equation*}
```
results in
```

\begin{equation*}
\end{equation*}

```
in the .tex file that is compiled. This makes unwanted paragraph breaks in the final document. An  example of this can be seen in nicksolomon/thesisdown_example@a2dfda57b80f62011387d1b00899851188c2bf49

**Comment by yihui** [comment]
Instead of incorporating the changes you proposed into bookdown, I provided an option so that you can add your custom post-processor, e.g.

```r
options(bookdown.post.latex = fix_envs)
```

where `fix_envs` is the function you defined in #374.
