### ISSUE TITLE
Forbidden control sequence found when knitting the minimal example

### ISSUE THREAD

**Issue by pinusm** [rstudio/bookdown#375]
I've been getting the following error when knitting the minimal working example.
```
! Forbidden control sequence found while scanning use of \__cs_generate_from_si
gnature:nnNNNn.
<inserted text> 
                \par 
l.1767       \int_case:nnn
                           #2 
Here is how much of TeX's memory you used:
 13468 strings out of 428408
 237377 string characters out of 3160621
 238889 words of memory out of 3000000
 16852 multiletter control sequences out of 15000+200000
 3680 words of font info for 19 fonts, out of 3000000 for 9000
 1328 hyphenation exceptions out of 8191
 52i,0n,31p,10413b,233s stack positions out of 5000i,500n,10000p,200000b,50000s

Error: Failed to compile bookdown-demo.tex. See bookdown-demo.log for more info.
In addition: Warning messages:
1: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\latexmk.exe" -v' had status 1 
2: The LaTeX package latexmk was not correctly installed. 
3: running command '"C:\PROGRA~1\MIKTEX~1.9\miktex\bin\x64\latexmk.exe" -v' had status 1 
4: running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 1 
Execution halted
```

I suspect this is the culprit `The LaTeX package latexmk was not correctly installed` but am unable to get latexmk to install correctly, or understand how to fix the existing installation. I've used MikTex's package installer, but to no avail. What am I missing here?

Below I'm attaching my sessionInfo(). If any additional info is needed I'll gladly provide.
```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Hebrew_Israel.1255  LC_CTYPE=Hebrew_Israel.1255   
[3] LC_MONETARY=Hebrew_Israel.1255 LC_NUMERIC=C                  
[5] LC_TIME=Hebrew_Israel.1255    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bookdown_0.3.14

loaded via a namespace (and not attached):
[1] tools_3.3.3   knitr_1.15.1  digest_0.6.12
```

**Comment by yihui** [comment]
It is okay if latexmk is not installed. That is unlikely to be the issue. `xetex` definitely has to be installed.

**Comment by pinusm** [comment]
As far as I can understand, I do have `xetex` installed..
[here's ](http://pastebin.com/iyN3einB) a paste of my `mpm --list` command (following [this ](http://tex.stackexchange.com/a/294271) procedure, in an elevated commandline).

**Comment by yihui** [comment]
Could you move `_book/bookdown-demo.tex` to `_bookdown_files`, open a command window (RStudio menu `Tools -> Shell`), `cd _bookdown_files`, and run `xelatex bookdown-demo.tex`? If the error message is the same, I'm afraid I cannot help, since I don't understand this error message. BTW, are you using the latest version of MikTeX? You can check `xelatex --version`

**Comment by pinusm** [comment]
I've deleted the entire bookdown-demo-master folder, downloaded a fresh copy, and now it seems to be working.
I guess something got corrupted in a previous attempt to build/knit the project, although I don't remember ever editing the folder, besides trying to knit, and failing every time.
Thank you for you patience and attentiveness! I look forward to using bookdown!

**Comment by yihui** [comment]
Well, if you want to build the book to PDF, I think you will run into this issue again. The problem is gone now probably because I changed the default output format to be `bookdown::gitbook` instead of `bookdown::pdf_book` yesterday. If you run into the issue again, you still have to follow the steps above to diagnose the problem.

**Comment by pinusm** [comment]
very strange. now I can't seem to get either the knit or the build command to work.
even when I rm the folder and re-extract the zip.
I don't see a `_book` folder, but I do see a `bookdown-demo.tex` in the root of the project. is that the one you'd like me to move into `_bookdown_files`? (btw, the only thing inside `_bookdown_files` is a folder called `bookdown-demo_files`, inside it is a folder called `figure-latex`, inside it a pdf file `nice-fig-1`).

**Comment by yihui** [comment]
Yes, please try to move `bookdown-demo.tex` to `_bookdown-demo_files` and compile using `xelatex`.

You can choose a specific output format from the Build Book menu. I think gitbook should be fine. Only LaTeX/PDF output can be problematic. 

![image](https://cloud.githubusercontent.com/assets/163582/24162147/9ae3dbd4-0e34-11e7-89bb-6c8edb20defd.png)

**Comment by pinusm** [comment]
[Here's ](http://pastebin.com/Xp063dPM )the output I get after running `xelatex bookdown-demo.tex`.
Whenever I got to a blinking prompt, I tried pressing `RETURN`. 
That worked (i.e., I was able to continue with the process), until I got to the last bit:
```
! I can't write on file `bookdown-demo.pdf'.
Please type another file name for output:
! I can't write on file `.pdf'.
Please type another file name for output: sdfsdf.pdf
! I can't write on file `sdfsdf.pdf'.
Please type another file name for output: "C:\Users\MP\Desktop\bookdown.pdf"
! I can't write on file `"C:\Users\MP\Desktop\bookdown.pdf"'.
Please type another file name for output:
```
I tried several options, but ended up simply closing the shell window because I couldn't figure out how to continue.

**Comment by yihui** [comment]
Your LaTeX log said `"LaTeX2e <2016/03/31> patch level 3"`, which means it is probably a little old now.

You may try to update all your packages first: https://docs.miktex.org/manual/updating.html Then refresh FNDB and update formats: https://docs.miktex.org/manual/configuring.html

**Comment by pinusm** [comment]
updating the packages and FNDB worked! 
I'm now able to build the book in all three formats, although I still get the latexmk warning when building to PDF (doesn't seem to have an effect on the output PDF).
Again, thank you for you patience and attentiveness!

**Comment by yihui** [comment]
Glad to hear that. You can safely ignore the latexmk warning.
