### ISSUE TITLE
internationalization not working for pdf_book or pdf_document2

### ISSUE THREAD

**Issue by piotx** [rstudio/bookdown#377]
Hi,

if I use 
output:
    bookdown::gitbook 
Figures and Tables are translated according to _bookdown.yml

However if I use
output:
   bookdown::pdf_document2 or bookdown::pdf_book 

default names for figures / tables etc are used. _bookdown.yml has no effect on the output.

Is there any workaround, as I need pdf documents?

Cheers
Piotr

**Comment by yihui** [comment]
This is a documented behavior: https://bookdown.org/yihui/bookdown/internationalization.html

To customize figure / table names, you can google for LaTeX solutions, then use them in the LaTeX preamble: https://bookdown.org/yihui/bookdown/yaml-options.html

**Comment by piotx** [comment]
thanks!
