### ISSUE TITLE
table moved unnecessarily to bottom of page with bookdown::pdf_document2 or bookdown::pdf_book

### ISSUE THREAD

**Issue by piotx** [rstudio/bookdown#378]
Hi,

I just took the standard code from rstudio here http://rmarkdown.rstudio.com/lesson-7.html and replaced output: pdf_document with bookdown::pdf_book. The table is moved to the bottom of the page as can be seen here:
![table1](https://cloud.githubusercontent.com/assets/13752742/24214159/03f01d58-0f35-11e7-9b6c-cc1f818e522f.png)

I get the same results with the stable and dev version of bookdown. Any ideas? I'm running debian unstable, rstudio 1.0.135, R 3.3.3, bookdown_0.3 / bookdown_0.3.14

Cheers
Piotr

**Comment by yihui** [comment]
This also has been explained in the documentation: https://bookdown.org/yihui/bookdown/figures.html Tables and figures float by default.

**Comment by piotx** [comment]
thanks yihui; I've read the documentation and from my point of view it is not explicit. It explains about the difference between latex and html in general. output: pdf_document is not html however and it doesn't float the same way as bookdown::pdf_book. I would expect bookdown::pdf_book to behave similarly as output: pdf_document

for me personally, as an not so experienced knitr / rmarkdown user, this is confusing; as the documentation is written also for not so proficient users in mind, (https://bookdown.org/yihui/bookdown/software-tools.html) I don't find it easy to grasp

thanks for the packages!

**Comment by yihui** [comment]
Then please read the section on tables if you really do not want tables to float: https://bookdown.org/yihui/bookdown/tables.html

Tables do not float in `pdf_document` because Pandoc uses the longtable package. The reason I disabled longtable by default in **bookdown** is here: http://tex.stackexchange.com/q/276699/9128 If you understand the consequences, please feel free to use longtable.

**Comment by piotx** [comment]
Thanks. I had some issues with longtable a few years ago, so now I
understand it...

Am Donnerstag, 23. März 2017 schrieb Yihui Xie :
> Then please read the section on tables if you really do not want tables
to float: https://bookdown.org/yihui/bookdown/tables.html
>
> Tables do not float in pdf_document because Pandoc uses the longtable
package. The reason I disabled longtable by default in bookdown is here:
http://tex.stackexchange.com/q/276699/9128 If you understand the
consequences, please feel free to use longtable.
