### ISSUE TITLE
A small question about `fig.cap`

### ISSUE THREAD

**Issue by sammo3182** [rstudio/bookdown#379]
Hi Yihui, 

How could I force the caption of a plot at the top of the figure? In Latex, it always depends on where to put the `\caption{}`, but I didn't find an option to do that in bookdown. I tried to force the caption position to the top with `\usepackage[position=top]{caption}` in the template, but it doesn't work. 

Thank you,

**Comment by yihui** [comment]
Honestly I don't know. Why do you need to do that? The convention is usually "figure captions below figures, and table captions above tables". It does not sound worthwhile to me to break the convention.

**Comment by sammo3182** [comment]
Ok. In quite a few core journals in my area, the figure titles are at the top. That's why I am looking for the way to adjust it. I will turn back to Latex then. Thank you again for the great work of `bookdown`.

**Comment by yihui** [comment]
This is what I got from a quick google search: http://tex.stackexchange.com/q/22751/9128 Presumably either the float package or floatrow could be your solution, and this may be a pure LaTeX problem orthogonal to bookdown.

**Comment by sammo3182** [comment]
Thank you for the information, Yihui!

**Comment by markbneal** [comment]
I think a more general solution would be useful that applies to html and Latex output if possible, though html is personally of higher interest for me. There has been some action at this [stackoverflow question](https://stackoverflow.com/questions/56979022/caption-above-figure-in-html-rmarkdown/60480459#60480459) on this. Would it be fair to reopen this issue and widen scope to html, or submit another issue?

**Comment by yihui** [comment]
@markbneal I just posted a solution: https://stackoverflow.com/a/60516108/559676

**Comment by markbneal** [comment]
Thanks @yihui - solution is easy to implement, and works with my ggplot figures! 
I'm still having trouble with the plotly figures though - numbering is retained, but image reverts to the bottom: https://stackoverflow.com/a/60480459/4927395
Is this a **bookdown** or **plotly** package issue?
