### ISSUE TITLE
Equivalent of oldbookdown::screenshot()

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#38]
I don't think we have anything that's quite equivalent yet. There are two important differences from `knitr::include_graphics()`:

* you can use it inside `` `r ` `` for inline graphics

* it preserves the original size of the image (using optional dpi argument to scale) (i.e. it ignores `fig.width` and `fig.height`)

This is most useful for diagrams (so the `screenshot()` name isn't great), where you have carefully sized the image.

**Comment by yihui** [comment]
`knitr::include_graphics()` works for `` `r ` `` although I didn't think very carefully about it.

For the image size, `include_graphics()` basically uses `out.width`/`out.height`, and if they are not set, there should not be any restrictions on the size, i.e. it should show the original size, unless the size is has been restricted by CSS (like `max-width: 100%`) or LaTeX.

**Comment by hadley** [comment]
`knitr::include_graphics()` still doesn't work quite the way I want. Let me provide more details. 

Take <http://r4ds.had.co.nz/introduction.html#rstudio>. That section contains two screens, one of the R console and one of the options pane.  They are currently displayed as the same width - but "rstudio-layout.png" is 2466 pixels wide and "rstudio-workspace.png" is 1350 pixels wide. Rather than inspecting  `out.width` at all, I'd rather have those images sized "naturally", i.e. 2466 / 220 = 11.2". and 1350 / 220 = 6.13" (the dpi is 220 because I made them on my retina macbook)

(You might wonder if 11" is too wide - and indeed I think it is. I probably need to redo the screenshot at a more reasonable size, but I didn't realise until now because `include_graphics()` resizes it for me.)

Another use case is <http://r4ds.had.co.nz/relation-data.html#understanding-joins>. Here I have hand drawn diagrams that have different widths, but with a consistent font size. Unless I manually adjust the `out.width` (which I've done here) the diagrams are displayed with the same width, distorting the font size across the diagrams.

Does that make sense? I'm fairly confident that this is different enough from the current behaviour of `include_graphics()` that it requires it's own function.

(I could've sworn that `include_graphics()` didn't work for me inline, but it does now, so either you've fixed the bug or I was wrong in the first place)

**Comment by yihui** [comment]
On closer inspection, I realized this was a bug of `knitr::include_graphics()`. It should not have added the width constraint on images. I just fixed it in knitr, and now it should just show images of their original sizes.

**Comment by hadley** [comment]
Ok, that's much better 👍 But setting the dpi chunk option doesn't seem to affect the output size?

**Comment by yihui** [comment]
Right. `dpi` currently only works for R plots.

**Comment by hadley** [comment]
@yihui could you make it work for this too? I think it is moderately important.

**Comment by yihui** [comment]
Done in the dev version of knitr.
