### ISSUE TITLE
travis script: delete all version history in `gh-pages` on each deploy

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#381]
(This is in addition to #380 – would've added it myself, but I'm not git pro enough to deal with these rewrite-version-history commands).

I noticed that the `gh-pages` branch, and with it, the entire repo become quite huge over time.

It occurs to me this is because all the old *deploys* linger around on `gh-pages`, which seems unnecessary (because the *source* is versioned).

Could you perhaps amend the Travis script so that `gh-pages` is rewritten from scratch on every deploy?

**Comment by yihui** [comment]
One approach that you can use is to add the `--ammend` option to `git commit`, and then `git push --force`

But I think you really do not need to use GIT at all if you do not want to use version control. There are much better services than Github pages. You can consider @Netlify + Travis CI if you have a little bit experience with using REST API: https://www.netlify.com/docs/api/ (DEPLOYING VIA ZIP FILE)

**Comment by maxheld83** [comment]
Thanks @yihui that makes a lot of sense, I've been thinking about migrating to a proper Webspace host for some time. Thanks for the pointer!
