### ISSUE TITLE
Render document by sections

### ISSUE THREAD

**Issue by endri81** [rstudio/bookdown#383]
In this moment I have a book organized with every chapter inside one .Rmd file. I render it as pdf and everything is fine. Due to very long chapters I would like to have one section per file. Is it possible this schema?

**Comment by yihui** [comment]
You can write one section per Rmd file. There will not be any problems if you only care about PDF output. HTML/EPUB/Word output should also be fine in most cases. You may run into problems when you use the `edit` feature in HTML output: https://bookdown.org/yihui/bookdown/configuration.html

That said, even if you have a very long chapter, you can easily collapse sections in the RStudio IDE, e.g.

![image](https://cloud.githubusercontent.com/assets/163582/24374437/7ed11482-12fa-11e7-9a5b-04bad535ca0f.png)
