### ISSUE TITLE
Ensure block and block2 icons show up when sending html_book output to a printer

### ISSUE THREAD

**Issue by franknarf1** [rstudio/bookdown#384]
Looking at [the Bookdown book](https://bookdown.org/yihui/bookdown/custom-blocks.html), when I send it to my printer, I see none of the icons on the left side of the blocks (the "!", "note", etc.). I'm assuming this applies generally, but I'm seeing it with Chrome, Win 10, printing to a virtual printer (cute PDF). 

For my doc, I have [two block types](http://franknarf1.github.io/r-tutorial/_book/index.html#reading-this-book), differentiated by color and icon, but they will be indistinguishable in any black-and-white printout.

**Comment by yihui** [comment]
In the bookdown book, icons were implemented via background images, so you have to check the box "Background graphics" when printing from Chrome:

![image](https://cloud.githubusercontent.com/assets/163582/24640077/bc2bdf82-18b9-11e7-8df1-4cb3ebc42935.png)

I don't know why it does not work for your book. It might be a CSS issue.

**Comment by franknarf1** [comment]
@yihui Okay, thanks. I looked into it some more and think it is to do with the rendering (html_book vs gitbook). Please see the branch I made to illustrate when you have time: https://github.com/franknarf1/r-tutorial/tree/blockdemo 

When I render with html_book, the images are invisible (even when using your CSS); and when I switch to gitbook, they are visible so long as background images is checked, like you said.  In the linked branch, I put each result in its own folder manually (/_book -- html_book and /_book -- gitbook)**

** Side  note: I did this since I do not understand [the documentation for rendering multiple output formats](https://bookdown.org/yihui/bookdown/output-formats.html) at once. The best I could figure out was that the item at the top of _output.yml got priority for populating the /_book folder.

**Comment by yihui** [comment]
`html_book` uses Bootstrap styles, and `gitbook` uses completely different CSS styles. I don't have time to investigate why those background images won't show up when using Bootstrap.

In terms of HTML output formats, the bookdown project is almost exclusively devoted to the gitbook format. Other formats like `html_book` and `tufte_html_book` are not well tested and their priority is fairly low.

For your side note, I can see why you are confused. You can choose only one HTML output format by default. If you want to render different HTML output formats to different folders, you have to use the argument `output_dir` explicitly, e.g.

```r
bookdown::render_book('index.Rmd', 'bookdown::gitbook', output_dir = '_gitbook')
bookdown::render_book('index.Rmd', 'bookdown::html_book', output_dir = '_html_book')
```

**Comment by franknarf1** [comment]
Thanks for the pointer re Bootstrap. A google search [landed me at](http://stackoverflow.com/a/36742058/) an explanation for its behavior along with a crude css workaround (adding `!important`). I'm closing since that workaround should be sufficient for anyone in a similar situation, I think.

Point taken re using PDF for printing and thanks for pointing out output_dir.
