### ISSUE TITLE
Code block problem in Tufte format

### ISSUE THREAD

**Issue by axitdn** [rstudio/bookdown#385]
I've try to use this block in the Tufte style document:

\```{ .java .numberLines startFrom="1"}
import java.util.LinkedList;
...
\````

But it seems to be not rendered as I expected.

**Comment by yihui** [comment]
If something is not what you expected, please describe your expectation and show what you actually see.

**Comment by axitdn** [comment]
As you see the line { .java .numberLines startFrom="1"} means that the listing block is display java code with syntax highlight and the line number. It works when I use the gitbook document.

**Comment by yihui** [comment]
I don't have time to investigate the reason at the moment, but it seems you need to use a non-default `highlight` option for the Tufte style (e.g. `highlight: tango`). You didn't provide a minimal reproducible example, so I have no idea which output format you were actually using.
