### ISSUE TITLE
before_chapter_script also needs to be run by preview_chapter

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#39]
So local previews look the same as building the complete book.

**Comment by hadley** [comment]
This still isn't working for me - I have

```R
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  cache = TRUE
)
```

but the chunks aren't getting the style I want (or cached)

**Comment by hadley** [comment]
Also this now seems to be running in the main directory (instead of `_book`) so the chapter number is incorrect, and I get intermediate outputs in the root dir

**Comment by yihui** [comment]
Hmm, I cannot reproduce it with your r4ds repo. The _common.R script is inserted before chapters as expected. Intermediate outputs are also moved to `_book`. `*_files/` and `*_cache/` are not moved, though, but that is intentional (I guess I could move them if you want).

**Comment by hadley** [comment]
Hmmm, now it looks ok for me too. Maybe I was looking at a cached version?

I did expect the `_files/` and `_cache/` to go in `_book` too. Can you explain why they're not moved automatically?

**Comment by yihui** [comment]
I was simply waiting for you to complain about it :)

For the merge-and-knit approach, these are only two directories, so this does not bother me too much. I know it will be messy for the knit-and-merge approach, and apparently you do not like it, so I'll move them. The Rmd's are compiled in the root directory, and the outputs are moved to _book later. If I move _cache to _book, I'll have to move it back to the root directory the next time I compile an Rmd (then move it to _book again).

**Comment by mbojan** [comment]
Is this resolved? I believe I ran into the same problem. I have `new_session: true` in `_bookdown.yml` and the `before_chapter_script` is not executed when previewing a chapter in RStudio (with the "Knit" button).

**Comment by cderv** [comment]
Hi @mbojan , 

This is an old issue and not suitable to ask for something like that 4 years later. Moreover, yes this is supposed to work. 
Please open a new issue and provide some more information (a reproducible example would be great) so that we can look into it. 

Thank you !

**Comment by mbojan** [comment]
You are right @cderv , apologies. New issue incoming.
