### ISSUE TITLE
multiple footnotes without blank cannot be handled correctly

### ISSUE THREAD

**Issue by kohske** [rstudio/bookdown#390]
Here is an example Rmd: 

```
---
output: html_document
---

aiuie^[aiuie], kakikuke^[kakiku]sashi # OK

aiuie^[aiuie],kakikuke^[kakiku]sashi # NG

aiuie^[aiuie],kaki
kuke^[kakiku]sashi # NG

aiuie^[aiuie]kak ikuke^[kakiku]sashi #OK
```

I think it fails to parse multiple footnotes in one block (of what?).
In most English writing, this is not problematic because there are many white-spaces in texts.
However, in CJK we do not use white-spaces as a text separator, resulting in difficulty to use multiple footnotes in one sentence.

kohske

**Comment by yihui** [comment]
Unfortunately `^text^` is the syntax for superscripts in Pandoc's Markdown: http://pandoc.org/MANUAL.html#superscripts-and-subscripts I cannot think of a solution in this case. You have to file an issue to https://github.com/jgm/pandoc/issues. I think it makes more sense to parse footnotes before superscripts, but I don't know what the Pandoc author thinks.

**Comment by kohske** [comment]
Okay, I see. Thanks.
