### ISSUE TITLE
cannot build pdf using output: bookdown::pdf_book

### ISSUE THREAD

**Issue by suredream** [rstudio/bookdown#392]
I am a user of rticle package and it works well right now.

I want to dig more on bookdown. But when 

I followed instruction:

[here](https://bookdown.org/yihui/bookdown/get-started.html)

and 

[here](https://bookdown.org/yihui/bookdown/a-single-document.html)

I didn't find the button Build Book on the Build tab of RStudio. So far I can't build the [demo book](https://github.com/rstudio/bookdown-demo) to pdf format but only gitbook and html. And even for these two, only the first page was display correctly.

I use mac osx el capitan. 

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin11.4.2 (64-bit)
Running under: OS X El Capitan 10.11.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] backports_1.0.4 bookdown_0.3    magrittr_1.5    rsconnect_0.7  
 [5] rprojroot_1.1   htmltools_0.3.5 tools_3.3.2     yaml_2.1.14    
 [9] Rcpp_0.12.8     stringi_1.1.2   rmarkdown_1.3   knitr_1.15.1   
[13] stringr_1.1.0   digest_0.6.10   evaluate_0.10  
```

**Comment by yihui** [comment]
The Build button is only available when you are in an RStudio project, e.g. the bookdown-demo project. And you have to use a relatively recent version of RStudio.

**Comment by suredream** [comment]
Rstudio Version 1.0.136.
I can see the Knit button.

**Comment by yihui** [comment]
The Build Book button is in the Build pane: https://bookdown.org/home/getting-started.html

**Comment by suredream** [comment]
Thanks. But why even I set
> output: bookdown::pdf_book
In the frontmatter. But still only epub was created?

**Comment by yihui** [comment]
It seems you didn't realize that the Build Book button was also a dropdown menu:

![image](https://cloud.githubusercontent.com/assets/163582/25466595/4f0f201c-2acf-11e7-97a4-9d938d5374e2.png)

You can choose which format you want to build. By default, it builds all formats, and shows you the last format, which is epub in this case.

**Comment by suredream** [comment]
Perfect! Now I can dive into.

Thank you for your patience.
