### ISSUE TITLE
Protect users from their own stupidity?

### ISSUE THREAD

**Issue by nicholaelaw** [rstudio/bookdown#397]
Alright I've done something very stupid. I'll spare you the confusion and panic, and get straight to the point.

In the YML matter, setting `book_filename` to `index` would lead to the undesirable side-effect of __overwriting__ your `index.Rmd` with the knitted output `index.Rmd`. After this, the project and the day would probably be ruined. 

Oh and what I'm suggesting is to ban using `index` as the output file name.

**Comment by yihui** [comment]
Sorry about that. I just added a check so that bookdown will signal an error if the file exists. Thanks for the report!
