### ISSUE TITLE
Do not copy external CSS/Fonts when rendering?

### ISSUE THREAD

**Issue by nicholaelaw** [rstudio/bookdown#398]
Another blunder by me, I suppose. 

If I set `output_dir` to `../_book`, and use a custom CSS with `css: ../styles/style.css`, then upon `render_site`, any and all files referenced by the custom CSS, along with the CSS itself, would be overwritten, and corrupt.

Before:
![image](https://cloud.githubusercontent.com/assets/10719482/26229215/ca425c36-3c72-11e7-8bf1-a081251cf2ca.png)

After:
![image](https://cloud.githubusercontent.com/assets/10719482/26229229/f134ca90-3c72-11e7-902a-222ba5d2cf97.png)

Those two `NotoSerifCJK` fonts that weren't changed were not referenced in the CSS. As you could imagine, custom CSS won't work anymore.

I'd like to know if there is any way to disable this copying behaviour, and prefereably leave the stylesheet reference unchanged.

**Comment by yihui** [comment]
Thanks for providing another edge case! It is my fault, not yours. Should be fixed now.

**Comment by nicholaelaw** [comment]
No need to apologize. I back up often, and I back up the back up as well. So no harm done. However, I do want to know your opinion on something I've been working on:

A website built with `rmarkdown`, and then subdirectories each a report written in `bookdown`. What's the best way to manage such project(s)?

**Comment by yihui** [comment]
I don't have a recommendation. I have not worked in this way before. For me, a website is a pure website, and a book project is purely a book. I have never tried to mix them up, but I think it is totally fine to have different types of projects under subdirectories. When I work on a book, I mostly use `bookdown::serve_book('path/to/your/book')` to live preview it.
