### ISSUE TITLE
`render_book()` should not touch the source `.Rmd` files

### ISSUE THREAD

**Issue by clauswilke** [rstudio/bookdown#405]
First thanks a lot for the fantastic work you're doing with **knitr** and **bookdown**!

I have the following concern: I have noticed that `bookdown::render_book()` touches the `.Rmd` source files. I'm using the knit-then-merge approach and I'm using a before-chapter script, just like Hadley does in his r4ds book. What appears to be happening is that the before-chapter script is actually inserted into the source `.Rmd` file, then the file is knitted, and then the original source file is restored. This problematic for at least two reasons:

1. Most importantly, I've had several instances when the before-chapter script was not properly removed from the source file. I'm not sure exactly when this happens, but it could be a race condition between `render_book()` and my editor, i.e., `render_book()` changes the file, my editor picks it up, then I modify the file in my editor before `render_book()` restores it, and I end up with a source file that contains the before-chapter script.

2. More generally, though, I don't think any compilation process should touch source files at all. It messes up time stamps, and it risks corruption of the original source if anything goes wrong, e.g. the compile crashes, the power goes out, whatever.

The correct approach would be to copy the source file into a temporary file, modify the temporary file, knit that, and then delete.

**Comment by clauswilke** [comment]
To provide some additional information: The problem of corrupted `.Rmd` files arises when I knit `index.Rmd` while having several chapter `.Rmd` files open in RStudio. After knitting, a random selection of the opened chapters have the before-chapter script inserted into them in the RStudio editor. The files on disk are fine, though, so it indeed looks like a race condition between RStudio and `render_book()`.

**Comment by clauswilke** [comment]
An additional piece of insight: The race condition seems to occur for very short `.Rmd` files that knit very rapidly. RStudio notices the first change in the file but not the reversion, and thus the inserted R code remains. For longer files, RStudio notices two changes, the first that inserts R code and the second that removes it.

For all files, though, it is weird to see the source file change in RStudio as the knitting progresses.

**Comment by yihui** [comment]
I guess currently the best way to solve this problem is that you manually `source()` your R scripts in each Rmd. I might be able to figure out a better solution, but I have no time at the moment.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by clauswilke** [comment]
Super, thanks!
