### ISSUE TITLE
"block type" is working in bookdown under RStudio?

### ISSUE THREAD

**Issue by Efsilvaa** [rstudio/bookdown#408]
I have tried the same command used in your  bookdown book:

````
```{block2, type='rmdimportant'}
If you want to cross-reference figure ...
```
````

Is the sintax correct?

**Comment by yihui** [comment]
Correct. Please take a look at the Rmd source of the bookdown book when in doubt: https://github.com/rstudio/bookdown/tree/master/inst/examples

The relevant lines to this issue are: https://github.com/rstudio/bookdown/blame/fdd68e44eb7f0e8d74ba5c6f3ba1d957f94e7332/inst/examples/02-components.Rmd#L626-L645
