### ISSUE TITLE
speed up build a book

### ISSUE THREAD

**Issue by shadowwalker2718** [rstudio/bookdown#411]
Now my book has more than 40 chapters and it is very slow. I changed a powerful server which should be two times faster than the previous machine, but the speed is still as slow as before. Any idea to improve the speed? Now it takes 30+ mins to build a book. As an alternative, i tried to use preview book addin, but the cross references URLs are all gone awry. any idea to maintain the cross reference in preview book? Thanks.

**Comment by dataopt** [comment]
Are you outputting as PDF?  If so, how many pages?

Let's say you are outputting to PDF.  Bookdown first does some work to resolve cross-references and creates a single pandoc Markdown file and then calls pandoc for the actual conversion to the target format.  So it would be useful to know how much of that 30+ minutes was spent on the R processing and how much was spent on pandoc.  If it is the latter, then it is a pandoc issue.

**Comment by yihui** [comment]
Unfortunately you have to choose between speed and cross-references. You can only have one. Please see Section 1.5 https://bookdown.org/yihui/bookdown/some-tips.html and also Section 5.2.

That said, 30+ mins sounds way too long to me. We have to figure out why it is so slow before we know how to speed it up.
