### ISSUE TITLE
bookdown doesn't support pandoc 2.0

### ISSUE THREAD

**Issue by shadowwalker2718** [rstudio/bookdown#412]
```
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
Please delete sde.Rmd after you finish debugging the error.
Execution halted
```

Can you add a logic to support pandoc 2.0+? just change `--smart` to `+smart`

**Comment by yihui** [comment]
Thanks for the early heads-up! Could you do me a favor to report this to the [rmarkdown repo](https://github.com/rstudio/rmarkdown) instead? This issue should be fixed there.

**Comment by yihui** [comment]
Moved to https://github.com/rstudio/rmarkdown/issues/1120

**Comment by yihui** [comment]
I just submitted a fix and please test `devtools::install_github('rstudio/rmarkdown#1168')` if you want. Thanks!
