### ISSUE TITLE
More examples for tufte_html_book

### ISSUE THREAD

**Issue by reyman** [rstudio/bookdown#415]
Hi,

Is it possible to push little more information/examples about option for `bookdown::tufte_html_book:` template ? 

For example, is there a way to create a normal hyperlink from citation origin in the text [@key] to corresponding position in references at the end of document when using `link-citations: no` ?

**Comment by yihui** [comment]
For you first question, it is intentional since I'm not very satisfied with the [**tufte**](https://github.com/rstudio/tufte) package. I think I'll revamp it later this year.

For the second question, no, currently there is no way, but it may be a good idea and I'll add an option in the **tufte** package in the future.

**Comment by lf-araujo** [comment]
Dear @yihui , could you please point to where you are keeping ideas for the tufte revamp? I managed to mimic its behaviour using memoir [here](https://github.com/lf-araujo/tuftish-pandoc). Willing to help out too.

Merry Christmas

**Comment by yihui** [comment]
@lf-araujo I just feel the design of [tufte-css](https://github.com/edwardtufte/tufte-css) is not good enough (the CSS looks a little awkward to me), which prevents me from implementing features like https://github.com/rstudio/tufte/issues/13. I'd take a serious look at @nstrayer and @LucyMcGowan's awesome site http://livefreeordichotomize.com before I do anything.

**Comment by yihui** [comment]
Now you may try @grimbough's **msmbstyle** package: https://community.rstudio.com/t/16394 It may be worth looking at @jweisber's book "Odds & Ends", too (which was mentioned in the same post).
