### ISSUE TITLE
new_session is incompatible with RMDs in a subdirectory

### ISSUE THREAD

**Issue by steveharoz** [rstudio/bookdown#418]
When `new_session` is set to `no` (by default), you can put RMD files in a subdirectory and include their relative path in `_bookdown.yml`. For example:

    new_session: no
    rmd_files: ["index.Rmd", "chapters/01-intro.Rmd", "chapters/02-literature.Rmd"]

However, if `new_session` is set to `yes`, the build will throw the following error:

    ==> rmarkdown::render_site(encoding = 'UTF-8')
    
    Error in render_book("index.Rmd", output_format = output_format, envir = envir) : 
      All input files must be under the current working directory
    Calls: <Anonymous> ... <Anonymous> -> in_dir -> render_book_script -> render_book
    Execution halted
    
    Exited with status 1.

Either putting the RMDs in the root directory or setting `new_session` to `no` makes the error go away.

Here is a fork of bookdown-demo with files in a subdirectory that you can test - https://github.com/steveharoz/bookdown-demo

**Comment by yihui** [comment]
That is by design, as both the error message and the documentation have indicated: https://bookdown.org/yihui/bookdown/new-session.html

**Comment by steveharoz** [comment]
Got an idea of what prevents it from working? I commented out the stop command [here](https://github.com/rstudio/bookdown/blob/master/R/render.R#L109), but then `merge_chapters()` looked for `folder/myfile.md` instead of `folder/myfile.knit.md` or `folder/myfile.utf8.md`. I had a tough time digging up why that was happening.

**Comment by yihui** [comment]
Sorry, but I don't have time to explain it in detail. As I said, this is by design, so you should not simply comment out `stop()`. The main problem with `new_session: yes` + Rmd under subdirectories is that dependencies won't work (R graphics output, HTML widgets, etc). This problem is not easy to solve (at least not straightforward). You must make a decision here: give up `new_session: yes`, or give up subdirectories. You cannot have both at the moment.

**Comment by steveharoz** [comment]
No worries. I understand the time constraints. I find a workaround that seems to work. Instead of fully restarting the session, clearing the workspace and detaching packages should solve most people's needs.

1. In `_bookdown.yml`, set `new_session: no` (or just don't specify)
2. In `_bookdown.yml`, set `after_chapter_script: clear_vars_and_pkgs.R'
3. Create `clear_vars_and_pkgs.R` in the working directory with the following content:

```{r}
# detach packages
packages = sapply(sessionInfo()$otherPkgs, function(x) x$Package)
packages = packages[packages != "bookdown"]
packages = sapply(packages, function(p) paste0("package:", p))
lapply(packages, detach, character.only = TRUE, unload = TRUE)
# clear environment
rm(list = ls())
```

**Comment by yihui** [comment]
That is a reasonable approach.

I have mentioned in [Section 1.4](https://bookdown.org/yihui/bookdown/new-session.html):

> It can be very tricky and difficult to restore a running R session to a completely clean state if you use the M-K approach. For example, even you detach/unload packages loaded in a previous chapter, R will not clean up the S3 methods registered by these packages.

If all you want is to unload all packages, and remove all objects, I don't have a better approach than yours.

**Comment by ratnanil** [comment]
I frequently organize rmd's in subdirs and would like to use `new_session: yes`. So if this feature is implemented at some point, that would be great!

**Comment by steveharoz** [comment]
@ratnanil, see my workaround above.

**Comment by ratnanil** [comment]
I'm using the workaround, but I still think this would be a great feature!
