### ISSUE TITLE
Think about gitbook performance

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#42]
e.g. https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fr4ds.had.co.nz&tab=desktop

I think the main problem is that the gitbook `app.js` is 760 kb!! This seems ridiculously large.

**Comment by yihui** [comment]
Yeah, I'm aware of that. It will be minified eventually: https://github.com/rstudio/bookdown/blob/master/tools/uglifyjs.R And I could just take the embedded jQuery out.
