### ISSUE TITLE
rmdnote in pdf version

### ISSUE THREAD

**Issue by shadowwalker2718** [rstudio/bookdown#420]
Hi Yihui, I followed your book's example to use `rmdnote`, `rmdtip` block in my rmarkdown and found it looks beautiful in html output, but after I switched to PDF format, it just gave me errors. Do you know how to make them work in PDF format? I tried to search in SO but could not find any answer related. Thanks.

**Comment by jemus42** [comment]
The PDF output uses custom LaTeX environments für custom blocks, so you'll need to define these in your LaTeX includes, see the bookdown book itself as a reference: https://github.com/rstudio/bookdown/blob/master/inst/examples/latex/preamble.tex#L71-L85

If that doesn't to it for you, I got decent results by using epub output with bookdown and then using Calibre via `bookdown::calibre()` to convert the epub to PDF, which renders the custom blocks accurately (among other things).

**Comment by yihui** [comment]
Yes, @jemus42 was correct.
