### ISSUE TITLE
gitbook html lang attribute

### ISSUE THREAD

**Issue by joelwross** [rstudio/bookdown#421]
The HTML generated for the `gitbook` format doesn't include a `lang` attribute in the `<html>` tag (e.g., `<html lang="en">`. This causes problems with some validation/accessibility tools. Is it possible to include a `yaml` argument whereby we can specify the language for our generated book?

**Comment by yihui** [comment]
You can set `lang: en` in the YAML metadata of index.Rmd: http://pandoc.org/MANUAL.html#language-variables

Next time you may try StackOverflow, where you may get quicker answers. Here you basically have to wait for a single person (i.e. me) to process all issues and questions.
