### ISSUE TITLE
let render_book default to envir = new_env(), not parent.frame() to avoid side-effect-trap

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#424]
I recently spent a couple of hours figuratively shooting myself in the foot with `bookdown::render_book()` scoping shenanigans.
It was stupid, painful and unnecessary, and I'm wondering whether others might fall into the same trap and/or whether a different default could protect users like myself *from* themselves.

----

**Problem**

I was building a custom render function with some internal control logic. (I used some logical flags as arguments, say `docs = TRUE`, which would indicate whether I *also* wanted to, say, run `pkgdown::build_site()`).

So I had something like this:

```
render_book2 <- function(docs = TRUE) {
  bookdown::render_book(
    input = "index.Rmd",
    output_format = 'bookdown::gitbook',
    output_dir = '../../_site/book'
  )
  if (docs) {
    # `pkgdown::build_site()`. # my actual use case
    cat("docs is currently set to", docs)  # just for reprex purposes
  }
}
```

This function worked fine from the R console, but failed when run via `Rscript e ...` with an ominous `Object docs cannot be found` (not verbatim), which baffled me.

The reason, I realised after *way* too many more rounds is because `envir = parent.frame()` *and* `clean_envir = !interactive()` by default.
(The `clean_envir = !interactive()` bit explains the different behavior between R console and `Rscript e ...`.).

Once I had figured this out, the problem is clear: `bookdown::render_book()`, via `clean_envir = TRUE` removes all objects from the *parent* (?) environment, which here is the custom `render_book2()` function, so logical flags (such as `docs`) are gone by the time they're used in the control flow.

So, it's a **side effect** of `bookdown::render_book()` if used *with defaults*.

----

**Solution**

Once I figured this out, I fixed the problem by setting `envir = new.env()` as advised in the `rmarkdown::render_site()` docs.

----

**Comment**

I think I understand the `clean_envir = !(interactive)` default.
Actually I always want `clean_envir = TRUE` because it is a good idea to avoid potentially lingering objects from past builds to different formats.

But together with `envir = parent.frame()` this leads to an easy trap if used programmatically.

I wonder whether others might fall into this with the defaults too.

----

**Solution**

**Might `envir = new_env()` be a safer default for `render_book()`?**

Scoping and environments generally give me the shivers, so I might be missing something obvious here.

**Comment by maxheld83** [comment]
a sorry, I see this is similar to / duplicate of https://github.com/rstudio/rmarkdown/issues/934, and I should've opened the issue over at `rmarkdown`, where the default stems from.

Still, since my trap only arises in combination with the bookdown default `clean_envir = !(interactive)`, I'll leave this open here.

**Comment by yihui** [comment]
I don't want to make `clean_envir = TRUE` the default, since cleaning up an environment is intrusive: those who do not read the documentation may end up losing certain objects in an interactive R session. `clean_envir = TRUE` in a non-interactive R session is safer, because in that case, I believe most objects should be created from R scripts in an automatic fashion. Even they are accidentally deleted, it should not be hard to regenerate them. For an interactive R session, I need to be more conservative.
