### ISSUE TITLE
allow directory in input (much like rmarkdown::render_site())

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#425]
(I am aware that the whole working directory and path issue is quite complicated, so I understand if this won't be possible or is a bad idea.)

I'd like to be able to render some bookdown project *from some parent directory* as the working directory, where, say,

- my current `getwd()` would be `foo/`
- all my `*.rmd`s, including `index.rmd` live inside `foo/book/`.

I can of course `setwd()` my way to `/book` in my script, but I understand that to be evil.

`rmarkdown::render_site()` *does* seem to accept an entire *directory* for an input as per the docs:

> The render_site function enables you to render a collection of markdown documents within a directory as a website.

`bookdown::render_book()` does not accept a directory, and will not find the *other* `*.Rmd` when given `input = 'root/book/index.rmd'`.

Would it be possible / wise for `bookdown::render_book()` to *also* just accept a directory, and abstract away any possible `setwd()` actions or would that just open a whole different can of worms?

----

Ps.: My use cases is: I have a book *inside* a package (`/docs/book/`), and would like to render it from the project root.

**Comment by yihui** [comment]
`setwd()` is not evil at all as long as you restore the working directory when you are done.

You could use `xfun::in_dir('book', bookdown::render_book('index.rmd'))`.
