### ISSUE TITLE
gitbook: allow user scaling

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#43]
Currently have:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
```

I think

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

Is more appropriate, because it's often useful to zoom into pictures etc.

**Comment by hadley** [comment]
I think you can also drop the `handheldfriendly` since it's only used by [very old browser](https://github.com/h5bp/mobile-boilerplate/wiki/The-Markup)

**Comment by yihui** [comment]
Done. Thanks!
