### ISSUE TITLE
remove `bookname.rds` file after `render_book(new_session = T)` 

### ISSUE THREAD

**Issue by gitzhuoer** [rstudio/bookdown#430]
After you run `render_book(new_session = T)`, there will be a `bookname.rds` file in the output directory. I think this file is useless after the book is build, so it should be removed to leave a tidy output directory.

**Comment by yihui** [comment]
It should not be deleted. It is used to store some intermediate metadata (mainly HTML dependencies of HTML widgets).

**Comment by gitzhuoer** [comment]
But I still don't think it should stay in the project's directory. If it's needed for the book to be read (open by browser), it should be moved to the `_book` folder. If it's needed for rebuilding the book=, it should be moved to the `_bookdown_files` folder.

**Comment by yihui** [comment]
Yes, it can be moved back and forth. I can take a look if you can send a pull request, otherwise I won't have time for this in the foreseeable future. It is a single file after all, and I don't feel the pressure about how it seriously messes up the whole directory. Thanks!
