### ISSUE TITLE
enumerate or itemize within an example block does not compile with pdf_book

### ISSUE THREAD

**Issue by merliseclyde** [rstudio/bookdown#433]
Including an itemized or enumerated list within an example block using Rmarkdown does not compile with pdf_book

The latex error indicates that the end  of the example block occurs before the end of the list (should be reversed)

Minimal example:

````
---
title: "A Book"
author: "M Clyde"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  bookdown::pdf_book: default
---

# Test {-}

This is a minimal example block that compiles with gitbook

```{example}
Here is a  minimal example that builds with gitbook, but not pdf_book

1. first item

2.  second item
```

but does not compile with `pdf_book`.
````

LaTex Code showing switched order: 

``
\BeginKnitrBlock{example}
\protect\hypertarget{ex:unnamed-chunk-1}{}{\label{ex:unnamed-chunk-1}}Here
is a minimal example that builds with gitbook, but not pdf\_book

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  first item
\item
  second item

  \EndKnitrBlock{example}
\end{enumerate}
``

Tested with the bookdown_minimal environment  and the dev version of book down.

Session info:
##  date     2017-08-06

Packages:
##  yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)

rmarkdown::pandoc version()

## [1] '1.19.2.1' 

Latex TexLive2017  from mac ports

**Comment by merliseclyde** [comment]
Adding a blank line at the end before the check ends as suggested with `block2` seems to resolve the problem in the pdf_book

**Comment by yihui** [comment]
This is exactly what I reminded you in the bookdown book: https://bookdown.org/yihui/bookdown/custom-blocks.html
