### ISSUE TITLE
Markdown superscript notation problem in kable caption for `pdf_document2`

### ISSUE THREAD

**Issue by walmes** [rstudio/bookdown#435]
Hi bookdown developers,

Today I observed a possible bug behavior regarding to the markdown notation in table captions. I tried to isolate the problem I found that `pdf_document` and `bookdown::pdf_document2` have different behavior for the caption argument in the `knitr::kable()` function. The code below uses the markdown notation `^.^` and `~.~` to write super and subscripts.

    ---
    title: "Testing kable"
    output: bookdown::pdf_document2
    ---

    The gravity on earth is 9.8 m s^-2^. The water molecule is H~2~O.

    ```{r, echo = FALSE}
    library(knitr)
    cap <- "A caption with markdown notation for superscript 10 m s^-1^."
    kable(head(iris), caption = cap)
    ```

But, when `bookdown::pdf_document2` is used (default for `pdf_book` that I'm authoring), something coerces the output beeing interpreted as is. With the `pdf_document`, there is no problem. Below is the produced LaTeX code when using the `keep_tex: true` option in the YAML.

```
\textbackslash{}begin\{table\}
\textbackslash{}caption\{\label{tab:unnamed-chunk-1}A caption with markdown
notation for superscript 10 m s\textsuperscript{-1}.\} \centering
... code omited ...
\textbackslash{}end\{table\}
```

The `^-1^` notation is interpreted correctly to LaTeX producing `\textsuperscript{-1}`. But the `\textbackslash{}` isn't expected to happen. This messed up the things below this table, mostly because the `\centering` command.

In advance, I appreciate your attention.
Thank you.

**Comment by yihui** [comment]
In general, you are not recommended to use any Markdown syntax in captions (figures or tables). If you have to format the text, the only portable approach is https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references.

**Comment by TonyLadson** [comment]
At present it seems possible to use subscripts in figure captions where these are specified in the chunk header e.g. ` fig.cap='Nitrate (NO~3~)', `
but its not possible for tables where the caption is specified as an argument to kable e.g.
`knitr::kable(... caption = 'Nitrate (NO~3~)')`

Is there a workaround for this?

Thanks for all your work on bookdown and knitr etc.

**Comment by TonyLadson** [comment]
Thank you, using text references solved my problem.
