### ISSUE TITLE
output directory for tufte_html2

### ISSUE THREAD

**Issue by strongway** [rstudio/bookdown#437]
I tried several options for html output directory. It seems it is not working with tufte_html2. The output file is at root folder with name '_main.html'

Here is what I put in the _output.yaml

     bookdown::tufte_html2: 
              output_dir: "_book"

I appreciate any suggestions. Thanks.

**Comment by yihui** [comment]
`output_dir` is not a valid option for the output format `bookdown::tufte_html2()`.
