### ISSUE TITLE
Gitbook header toolbar not displaying in iPad

### ISSUE THREAD

**Issue by jemus42** [rstudio/bookdown#438]
This is a visual issue and probably only relevant for bookdown's modified gitbook template.  

The following screenshots were taken on an iPad Air 2 in Safari:

![](https://dump.jemu.name/IMG_0051.PNG)
and
![](https://dump.jemu.name/IMG_0052.PNG)

(It looks the same in Chrome)

I tried to reproduce the issue using Chrome's developer tools on macOS, yet I can't find any screen size at which the issue occurs:

![](https://dump.jemu.name/2017-08-wme60l6ucahijwe.png)

It doesn't only affect the current version of the bookdown book, but also my current bookdown project [over here](https://github.com/tadaadata/r-intro-book), which is how I noticed the issue, but I thought it would be best to use the bookdown site as an example make sure it's not due to any changes I made to the CSS.

**Comment by yihui** [comment]
I think this is the same issue as #60, to which I don't have a solution. Sorry.
