### ISSUE TITLE
serve_book on Windowns: cannot change working directory

### ISSUE THREAD

**Issue by dmenne** [rstudio/bookdown#439]
Bookdown 0.4.2, RStudio 1.1.331, Windows 10 Desktop version

When I run  `bookdown:::serve_book()` on Windows, I get

```
Output created: yyy_2017.html
Serving the directory C:\Users\Dieter\Documents\xxx\report1 at http://127.0.0.1:4321
Error in setwd(site.dir) : cannot change working directory
```
No problem on Linux

**Comment by yihui** [comment]
What is `output_dir` in your `_bookdown.yml`?

**Comment by dmenne** [comment]
There is none in _bookdown.yml. I tried

- Output dir in _bookdown.yml
- output dir relative path in bookdown::serve_book in a separate R session
- output dir absolute path in bookdown::serve_book in a separate R session

With these settings, after the build completed, I get the "cannot change working directory" twice in a row, the browser opens and displays the bare text "cannot change working directory" (all in German)

**Comment by yihui** [comment]
I cannot reproduce the issue. Please ensure [all packages are up-to-date](https://yihui.name/en/2017/05/when-in-doubt-upgrade/), e.g. `update.packages(ask = FALSE, checkBuilt = TRUE)`

If the problem persists, please provide a minimal reproducible example with `devtools::session_info('bookdown')`.

**Comment by dmenne** [comment]
See comments in attached file serve_book.cmd

[bookdown_test.zip](https://github.com/rstudio/bookdown/files/1234928/bookdown_test.zip)

```
Session info ---------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.331)           
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/Berlin               
 date     2017-08-18                  

Packages -------------------------------------------------------------------------------------------
 package   * version date       source                           
 backports   1.1.0   2017-05-22 CRAN (R 3.4.0)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                   
 bitops      1.0-6   2013-08-17 CRAN (R 3.4.0)                   
 bookdown    0.4.5   2017-08-18 Github (rstudio/bookdown@ffec58e)
 caTools     1.17.1  2014-09-10 CRAN (R 3.4.0)                   
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                   
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.0)                   
 graphics  * 3.4.1   2017-06-30 local                            
 grDevices * 3.4.1   2017-06-30 local                            
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                   
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                   
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)                   
 knitr       1.17    2017-08-10 CRAN (R 3.4.1)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                   
 markdown    0.8     2017-04-20 CRAN (R 3.4.0)                   
 methods   * 3.4.1   2017-06-30 local                            
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                   
 Rcpp        0.12.12 2017-07-15 CRAN (R 3.4.1)                   
 rmarkdown   1.6     2017-06-15 CRAN (R 3.4.0)                   
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)                   
 stats     * 3.4.1   2017-06-30 local                            
 stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)                   
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)                   
 tools       3.4.1   2017-06-30 local                            
 utils     * 3.4.1   2017-06-30 local                            
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)                   
 
 ```

**Comment by yihui** [comment]
Your output format is `bookdown::html_document2`, which is not for books but single documents. You should use `rmarkdown::render()` instead of `bookdown::render_book()` or `serve_book()`.

**Comment by dmenne** [comment]
This is by design, because I want one file to give to my customer as a report. Well, never mind, you can close this, the server is a nice gimmick, not essential, and I am happy with the bookdown/html_document2 combination.

**Comment by yihui** [comment]
You can use something similar to `serve_book()`:

1. Install the **xaringan** package;

2. Do not use multiple Rmds. You should only have a single Rmd document with `output: bookdown::html_document2` in YAML. Then you can use `xaringan::inf_mr("foo.Rmd")` to live preview it.

**Comment by dmenne** [comment]
... Do not use multiple RMD ....

No way. I need to run parts, otherwise I would have to wait much too long, debugging needs long, and the documents get huge. I know we had this discussion 5 year ago in context with child documents... Looks like the report you and me generate are of different type.

To be able to work with an almost clean slate in all child documents, I found new_session interesting, but it removes all globals. To remove all newly created once and make documents independent, I do:

`BeforeObjects = ls()`

at the top of each child RMD, and 

```
```{r }
rm(list = setdiff(ls(), BeforeObjects))
```
```
at the end. This has worked well with child documents up to now, and also works with bookdown.
