### ISSUE TITLE
Delete generated rmd file

### ISSUE THREAD

**Issue by dmenne** [rstudio/bookdown#442]
Automatically delete the generated RMD, don' t generated  error message.

`The file xxxx.Rmd exists. Please delete it if it was automatically generated, or set a different book_filename option in _bookdown.yml.`

It is a temporary file that can easily be reconstructed, and it's just to easy to delete the wrong file when you see this message.

**Comment by yihui** [comment]
Basically it boils down to this question: should I bug you with an annoying error message or silently wipe out a file? The reason I chose to annoy you is #397. It may be obvious to you that it is automatically generated, but I have no knowledge whether an existing file was automatically generated.

**Comment by dmenne** [comment]
Suggestion: 

delete_rmd: true/false
It's up to the user to decide.

**Comment by yihui** [comment]
That is a good suggestion. I'll do it.

**Comment by yihui** [comment]
Okay, now you can set `delete_merged_file: true` in `_bookdown.yml`.

**Comment by dmenne** [comment]
Great. Tested and works. 

If you want to be fancy, you could suppress the "please delete the ...." when this is true.

**Comment by yihui** [comment]
Sure. I'll do that.
