### ISSUE TITLE
Some EPUB sections can't be seen on iBooks

### ISSUE THREAD

**Issue by mamaciasq** [rstudio/bookdown#443]
Unfortunately, I can't read some sections of bookdown example by @yihui
If I want to move to HTML widgets section, the next message appears:

![captura de pantalla 2017-08-17 a las 3 13 17 p m](https://user-images.githubusercontent.com/7801159/29431879-2e1dbae2-835f-11e7-9ea4-88e01853d8bf.png)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
