### ISSUE TITLE
可否切换 bookdown.org 的账号不跟 google 挂钩

### ISSUE THREAD

**Issue by bubifengyun** [rstudio/bookdown#445]
作为一名中国人，生活在国内，很无奈，根本用不了那个谷歌账号。能不能增加一个 github 或者其他注册账户，谢谢。

Can add github's user as login user in bookdown.org? Thank you.

**Comment by yihui** [comment]
@trestletech Is it possible to log in Connect using other types of accounts such as Github? All Google services are blocked in China, so they have difficulties in logging into bookdown.org.

**Comment by trestletech** [comment]
Sure. We could run with any of these auth systems: http://docs.rstudio.com/connect/admin/authentication.html Unfortunately we don't support any other OAuth providers like GitHub.

We had assumed that OAuth would be the most universally accessible but if we could do password auth or something else if that would be easier. Unfortunately we don't support migrations so we'd have to either blow away the existing deployments and/or setup a separate server running as the different auth provider.
