### ISSUE TITLE
Cross reference issue when the figure name using underline

### ISSUE THREAD

**Issue by yaaaang** [rstudio/bookdown#446]
I was struggling with the cross reference. And I found this strange issue:
The name of the figure cannot use underline symbol, otherwise the crossrefence failed.

Here is a example: If you name the figure cars_fig, it failed. And if you change it to cars-fig, then it is fine.

Here's the cross-ref: \@ref(fig:cars_fig)

Here's the figure:

```{r cars_fig, fig.cap = 'Here is a plot about cars'}
plot(cars)
```

<img width="1157" alt="screenshot 2017-08-20 07 06 58" src="https://user-images.githubusercontent.com/22521093/29490706-5db0b296-8576-11e7-99a3-a5789a9f0b3e.png">
<img width="1155" alt="screenshot 2017-08-20 07 07 16" src="https://user-images.githubusercontent.com/22521093/29490715-bbb3c3ce-8576-11e7-8185-da6faac905bd.png">

**Comment by yihui** [comment]
Please read https://bookdown.org/yihui/bookdown/figures.html
