### ISSUE TITLE
Feature request: arbitrary fonts and font sizes for the verbatim environment

### ISSUE THREAD

**Issue by dusadrian** [rstudio/bookdown#447]
There are situations when a different monospaced font is used, in my situation I use Menlo because it has a more visually appealing tilde sign ~ compared to the default font, in a setup that produces a PDF file using xelatex.

But changing the font brought a host of new issues, some already solved, such as the font size (the default is too big, the \small is too small). There is also the issue of the space between the lines of the verbatim environment, depending on particular setups it might be too much space for the default font size.

Having described the situation, this is the fix I came across:

````
\usepackage{fancyvrb}
\usepackage{anyfontsize}
\DefineVerbatimEnvironment{verbatim}{Verbatim}{formatcom=%
{\linespread{0.9}\normalfont\ttfamily\fontsize{10}{12}\selectfont}}

\setmonofont{Menlo}
````

I can put this in the preamble but it would only affect the R output, while the R commands in the Highlighting environment would still be different. I thought it would be nice to have this feature globally offered with parameters in the .yml file: name of the font, the percentage (in this example 0.9) to shrink or enlarge the space between the lines, and perhaps the font size (only one parameter is needed, since 12 is simply obtained by multiplying 10 with 1.2).

One other thing which I had to solve, was related to the double quotes in the verbatim environment. As it turns out, this line:
````
\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
````
caused the double quotes to appear like smart quotes (slightly inclined), apparently having something to do with the `Ligatures=TeX` part. Removing that (have no idea if it breaks something) seems to solve the double quotes issue as well.

Thanks,
Adrian

**Comment by yihui** [comment]
These are pure LaTeX problems, and I'm not a LaTeX expert, so I cannot offer any help. Sorry. You have to ask other LaTeX experts like on TeX.SE.
