### ISSUE TITLE
gitbook feature request: arbitrarily exclude heading from TOC

### ISSUE THREAD

**Issue by brooksambrose** [rstudio/bookdown#448]
First I absolutely love the package and thanks so much for your hard work! My feature request is similar to how we can use `# H1 {-}` to prevent heading numbering. I would find it useful to have a syntax option within `{}` to arbitrarily exclude a particular header from the TOC. I have found myself choosing heading levels merely to get the TOC to display the way I want rather than reflecting the logical structure of the contents or how I want separate html pages to be built out. Consider the case where chapters have different levels of granularity. For instance, a "low resolution" vs "high resolution" set of chapters might look like:

```
# 1 Introduction (low res)
## 1.1 Section
## 1.2 Section
# 2 Chapter (high res)
## 2.1 Section
### 2.1.1 Subsection
### 2.1.2 Subsection
```
If I want my TOC to read:

- 1 Introduction
- 2 Chapter
  - 2.1 Section

Currently I could set `bookdown::gitbook:toc_depth: 2` in `_output.yml`. And rewrite my headings like this:

```
# 1 Introduction (low res)
### 1.1 Section
### 1.2 Section
# 2 Chapter (high res)
## 2.1 Section
### 2.1.1 Subsection
### 2.1.2 Subsection
```

But this is illogical and prevents 1.1 and 1.2 from being built as separate html pages. I imagined the solution could be something like this...

```
# 1 Introduction (low res)
## 1.1 Section {+}
## 1.2 Section {+}
# 2 Chapter (high res)
## 2.1 Section
### 2.1.1 Subsection
### 2.1.2 Subsection
```
...which could be a flag for ignoring those headings when building the TOC. In general, for long projects the TOC can get unwieldy fairly quickly, so manually paring it down is a feature I would really appreciate!

**Comment by yihui** [comment]
Thanks for the suggestion, but this has to be implemented on Pandoc's side. See https://github.com/jgm/pandoc/issues/1762 for more discussions.

**Comment by rnuske** [comment]
In the discussion over at [[jgm/pandoc#1762](https://github.com/jgm/pandoc/issues/1762)](https://github.com/jgm/pandoc/issues/1762) there is a [pandoc filter](https://github.com/jgm/pandoc/issues/1762#issuecomment-355545627) mentioned which seems to work.

I tried to use it with [bookdown-demo](https://github.com/rstudio/bookdown-demo). The line `\let\oldaddcontentsline\addcontentsline` is not added automagically to the preamble as it is the case with simple stand-alone markdown documents.

It worked for me after adding that line manually to `preamble.tex`.

**Comment by yihui** [comment]
jgm/pandoc#1762 has been fixed; more info at https://github.com/rstudio/rmarkdown/issues/1625#issuecomment-558854773
