### ISSUE TITLE
Line numbers in code block do not align

### ISSUE THREAD

**Issue by bitbacchus** [rstudio/bookdown#449]
# Issue

The line numbers and the lines of code do not align properly when rendering to html (using ` ``` {.numberLines} `):

![screenshot](https://user-images.githubusercontent.com/19432439/29707120-75c315ce-8984-11e7-9f51-0c621c658113.png)

I had a l look into the html file: in the `<style type="text/css">`-section is a line `table.sourceCode { width: 100%; line-height: 100%; }`. When I remove `line-height: 100%; ` everything aligns nicely.

My css-knowledge is quite limited, so I couldn't figure out a workaround, yet. Any ideas there would be appreciated, too :-) 

Thanks a lot for your effort with bookdown!

Best,
Sebastian

# Minimal example
My .Rmd file:

[listings.Rmd.txt](https://github.com/rstudio/bookdown/files/1251412/listings.Rmd.txt)

(I had to rename it to be able to upload it)

# System info

## Pandoc version 
1.19.2.1

## Session info
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.153)           
 language de_DE                       
 collate  de_DE.UTF-8                 
 tz       Europe/Berlin               
 date     2017-08-25                  

## Packages
 package   * version date       source                           
 backports   1.1.0   2017-05-22 CRAN (R 3.4.1)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.1)                   
 bitops      1.0-6   2013-08-17 CRAN (R 3.4.1)                   
 bookdown    0.5     2017-08-25 Github (rstudio/bookdown@d40592d)
 caTools     1.17.1  2014-09-10 CRAN (R 3.4.1)                   
 digest      0.6.9   2016-01-08 CRAN (R 3.2.3)                   
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                   
 graphics  * 3.4.1   2017-07-08 local                            
 grDevices * 3.4.1   2017-07-08 local                            
 highr       0.6     2016-05-09 CRAN (R 3.4.1)                   
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.1)                   
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)                   
 knitr       1.17    2017-08-10 CRAN (R 3.4.1)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.2.1)                   
 markdown    0.8     2017-04-20 CRAN (R 3.4.1)                   
 methods   * 3.4.1   2017-07-08 local                            
 mime        0.5     2016-07-07 CRAN (R 3.4.1)                   
 Rcpp        0.12.11 2017-05-22 CRAN (R 3.4.0)                   
 rmarkdown   1.6     2017-06-15 CRAN (R 3.4.1)                   
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.1)                   
 stats     * 3.4.1   2017-07-08 local                            
 stringi     1.0-1   2015-10-22 CRAN (R 3.2.2)                   
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.1)                   
 tools       3.4.1   2017-07-08 local                            
 utils     * 3.4.1   2017-07-08 local                            
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.1)

**Comment by yihui** [comment]
The easiest way to override this CSS rule is to add this to your Rmd document:

```html
<style>
table.sourceCode {
  line-height: inherit;
}
</style>
```

You can also customize the `css` option of `gitbook`, e.g.

```yaml
output:
  bookdown::gitbook:
    css: custom.css
```

where custom.css contains the CSS below:

```css
table.sourceCode {
  line-height: inherit;
}
```

BTW, this issue is only reproducible in Firefox. Chrome and Safari are okay.

**Comment by bitbacchus** [comment]
Thanks for the css-code, you just saved my day :-)

> BTW, this issue is only reproducible in Firefox. Chrome and Safari are okay.

Hm, I checked Chrome (58.0.3029.96 (64-bit), Linux) and Chromium (Version 60.0.3112.78) and have the same issue like on Firefox.

Just let me know if I can do some more testing.

Best,
Sebastian

**Comment by yihui** [comment]
I'm using Google Chrome Version 60.0.3112.113 on macOS. Not sure if that makes a difference.
