### ISSUE TITLE
Changing chapter titles causes problems with serve_book

### ISSUE THREAD

**Issue by pdhoff** [rstudio/bookdown#451]
Many thanks for this very useful resource. 

I encountered what seems to be a bug when using "serve_book". 

Suppose I have an Rmd file, say "an.Rmd", like the following 

```{r}
# Introsuction

Bloop.
```
When I serve the book, a file "introsuction.html" gets created in "_book".

If I edit "an.Rmd" in a way that changes the chapter title, such as 

```{r}
# Introduction

Bloop.

Bleep.
```
then a file "introduction.html" is created, but  "introsuction.html" is not deleted. 

This wouldn't be so bad, except the "index.html" file doesn't get rebuilt, and 
so  "introsuction.html" is served instead of "introduction.html."
Even when making further changes to "an.Rmd",  "introduction.html"  doesn't get 
served until index.html is rebuilt (e.g. if index.html gets changed).

**Comment by yihui** [comment]
That is by design. Previewing a book means only the chapter that you edited will be regenerated. Other files won't change. If you need to update everything, you have to build the full book.

https://bookdown.org/yihui/bookdown/preview-a-chapter.html

**Comment by pdhoff** [comment]
> Previewing a book means only the chapter that you edited will be regenerated. 

Sort of: I think of one chapter as being one Rmd file. If you edit the first level heading, it 
doesn't regenerate the html file, it generates a new html file that doesn't get served. 
If you edit the heading multiple times, you will have multiple html files all derived from one 
Rmd file, with only the original being served. The issue here seems to be that html file 
names correspond to the first level heading, instead of the name of the Rmd file that 
they are created from. 

Anyway, thanks for providing this useful software.
