### ISSUE TITLE
Update cover-image, URL, & description for ModernDive on bookdown.org

### ISSUE THREAD

**Issue by rudeboybert** [rstudio/bookdown#452]
Hi, could you update the following fields for the ModernDive listing on [https://bookdown.org/](https://bookdown.org/):

1. `url`: <http://moderndive.com/>
1. `cover-image`: replace with this [one](https://github.com/ismayc/moderndiver-book/blob/master/images/logos/book_cover.png)
1. `description`: "An Introduction to Statistical and Data Sciences in R: An open-source and fully-reproducible electronic textbook bridging the gap between traditional introductory statistics and data science courses."

thank you
Albert and @ismayc

**Comment by yihui** [comment]
Sure. I will. Thanks for letting me know!

**Comment by yihui** [comment]
Could you enable HTTPS for your website? If you are not familiar with HTTPS, the most convenient way to go is probably to publish your content via Netlify.com.

**Comment by yihui** [comment]
Note `cover-image` and `description` are automatically scraped from your book, so you have to set them properly in YAML: https://bookdown.org/home/about.html

**Comment by ismayc** [comment]
We have added them to our [`index.Rmd`](https://raw.githubusercontent.com/ismayc/moderndiver-book/master/index.Rmd).  

We currently go through HostGator and it isn't initially apparent how to enable HTTPS there and we likely won't have a chance to get netlify set up for a couple weeks.
