### ISSUE TITLE
provided fontawesome.ttf missing "Installable" permission

### ISSUE THREAD

**Issue by bernd-steinert-itc** [rstudio/bookdown#454]
We are using gitbook output and try to render an icon from the provided fontawesome lib inside a custom block (```{block, type='warning'} ... ```).

The fontawesome icons don't show up in IE11 while FireFox and Chrome works fine.

In IE11 console we get an error CSS3114, complaining about missing "Installable" permission flag for TTF file fontawesome-webfont.ttf. 

_Tested solution:_
Upgrading fontawesome-webfont.ttf to current version (4.7.0) avoids the error in IE11 console and icons are displayed on FireFox, Chrome and IE11.

**Comment by yihui** [comment]
Thanks for the report. I'll try to upgrade it in the future.
