### ISSUE TITLE
Deploy book down directly to the browser

### ISSUE THREAD

**Issue by Flavjack** [rstudio/bookdown#455]
How can I deploy the render book directly to the browser.

In the current option we have:
1. Preview in windows
2. Preview in Viewer pane
3. (No Preview) 

Is there the possibility to add "browser"?

**Comment by yihui** [comment]
You can pop out the window to your browser from RStudio:

![image](https://user-images.githubusercontent.com/163582/30008179-57b56130-90e2-11e7-8a06-3d196759faed.png)
