### ISSUE TITLE
Emojis are not displayed in PDF generated

### ISSUE THREAD

**Issue by pablo14** [rstudio/bookdown#457]
Hi there!
Before all, let me tell you this is a great package, **thanks for the hard work!**

Now the question which is in StackOverflow:

https://stackoverflow.com/questions/46027757/emojis-are-not-displayed-in-pdf-generated-by-bookdown

Basically, the .tex generated contains the emojies (i can see them with a text editor), and also they are well displayed in the website version. But it doesn't show in the pdf version.

Thanks!

**Comment by yihui** [comment]
This is a LaTeX question, and I'm afraid that I cannot help. If the .tex file contains the emoji characters, that means bookdown has fulfilled its mission. I have no idea how to compile a .tex file with emoji to PDF via pdflatex. You have to ask LaTeX experts.
