### ISSUE TITLE
Add "Advanced R" to index please

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#459]
Since the in-progress 2nd edition uses bookdown: http://adv-r.hadley.nz/

**Comment by yihui** [comment]
Done. It will be great if you could enable HTTPS. Currently bookdown.org is marked as "not fully secure" by Chrome because of the three images (two from you and one from @dgrtwo + @ juliasilge):

> Mixed Content: The page at 'https://bookdown.org/home/' was loaded over HTTPS, but requested an insecure image 'http://r4ds.had.co.nz/cover.png'. This content should also be served over HTTPS.

> /home/:1 Mixed Content: The page at 'https://bookdown.org/home/' was loaded over HTTPS, but requested an insecure image 'http://adv-r.hadley.nz/cover.png'. This content should also be served over HTTPS.

> /home/:1 Mixed Content: The page at 'https://bookdown.org/home/' was loaded over HTTPS, but requested an insecure image 'http://tidytextmining.com/images/cover.png'. This content should also be served over HTTPS.

**Comment by hadley** [comment]
Do you have any thoughts on whether it's easier to publish to netlify from travis or set up cloudflare in front of my AWS S3 site?

**Comment by hadley** [comment]
(Maybe it's time for an update to https://bookdown.org/yihui/bookdown/github.html ?)

**Comment by hadley** [comment]
I'm trying the netlify route:

1. Run `netlify deploy` once locally, to set up `.netlify`
1. Create new personal access token at https://app.netlify.com/account/applications
1. Save as "NETLIFY_PAT" env var in travis config
1. Modify travis to install netlify, cache npm directory, and deploy after success: https://github.com/hadley/adv-r/blob/master/.travis.yml

**Comment by hadley** [comment]
Ok, done! 

This is much simpler to set up than AWS, supports https (now redirecting automatically), and should be faster too. Thanks for the prompt!

**Comment by yihui** [comment]
Yes, that is what I'd do.

**Comment by juliasilge** [comment]
We have moved over [tidytextmining.com](https://www.tidytextmining.com/) to Netlify and turned on https, FYI.

**Comment by yihui** [comment]
@juliasilge Perfect! Thanks a lot!
