### ISSUE TITLE
Look into Calibre for converting EPUB to MOBI

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown#46]
Calibre is free and open-source: https://calibre-ebook.com/

Because Amazon's kindlegen has some restrictions https://www.amazon.com/gp/feature.html?docId=1000599251 It seems we are not allowed to use kindlegen on a server:

> You may make one copy of the Software for back-up purposes. You may not use the Software over a network. All rights not expressly granted to you are reserved by Amazon.

**Comment by muschellij2** [comment]
Kindlegen no longer available: https://www.amazon.com/gp/feature.html?docId=1000765211, so may want to look into this again...

**Comment by muschellij2** [comment]
Maybe use `bookdown::calibre` as the recommendation at https://bookdown.org/yihui/bookdown/e-books.html#mobi

**Comment by cderv** [comment]
Thanks for the info @muschellij2. I opened another issue to track this.

**Comment by yihui** [comment]
You are right. I was aware of that. Someone reported it by email to me a while ago but I haven't updated the book or the `kindlegen()` function yet. Thank you!
