### ISSUE TITLE
chapter_name entry in _bookdown.yml does nothing for PDF output

### ISSUE THREAD

**Issue by ntguardian** [rstudio/bookdown#462]
In my _bookdown.yml file I have the setting `chapter_name: "Entry "` and this does change the naming of chapters for HTML output so that numbering is "Entry 1", "Entry 2", etc., but for PDF output, the numbering is still "Chapter 1", "Chapter 2", etc.

**Comment by yihui** [comment]
This is documented: https://bookdown.org/yihui/bookdown/internationalization.html

For LaTeX output, you have to use LaTeX solutions, such as redefining `\chaptername`.

**Comment by olugovoy** [comment]
Could you please provide an example with the `\chaptername`? Thx

**Comment by Adrianzo** [comment]
Try:

```
header-includes:
  - \AtBeginDocument{\renewcommand{\chaptername}{Entry}}
```

source: https://stackoverflow.com/questions/54676107/changing-chapter-x-name-in-bookdown-pdf
