### ISSUE TITLE
Host bookdown on Sharepoint: "_main_files" issue

### ISSUE THREAD

**Issue by DRManager** [rstudio/bookdown#468]
Hi Yihui,

I am trying to establish a workflow to host bookdown on Sharepoint (main publishing platform within corporate). It is not straigthforward. But we have work around to host the gitbook on the sharepoint. 
However, all the figures could not be displayed. It turns out that SharePoint **added "_"** to the "_main_files" automatically as "files" was reserved for system. 

Is there a place that we can configure within bookdown package where to put the figures? Can the folder be changed to "_main_images"? It would not conflict with sharepoint naming convention.

Thanks,
Rick

**Comment by yihui** [comment]
Yes, set `book_filename` (defaults to `_main.Rmd`) in `_bookdown.yml`: https://bookdown.org/yihui/bookdown/configuration.html

**Comment by DRManager** [comment]
Yihui,

Your rules on the questions order (SO -> Github issue -> email) make sense!  I have transferred the issue to  [SO ](https://stackoverflow.com/questions/46459185/issue-with-host-r-bookdown-generated-gitbook-on-sharepoint).

book_filename can change the book output folder. However, the subfolder that saves images still ends with *_files by default, which has issue with Sharepoint. If you can change it to end with _images, it would resolve the issue for Sharepoint hosting the content. I am trying to see if there is work around so far from SO and internal development team.

Thanks!

**Comment by yihui** [comment]
Oh I thought the leading `_` in `_main_files` was the problem. I just read you question again, and realized `_files` was the problem. 

To thank you for your understanding, I answered your SO question.
