### ISSUE TITLE
Crossreference syntax

### ISSUE THREAD

**Issue by aetiologicCanada** [rstudio/bookdown#469]
I have a comment on table cross-referencing. 
 I kept puzzling over the meaning of the last paragraph of Section 2.5 (Tables) of the bookdown ebook. 

I have worked up a functioning skeleton here that does captions and cross-references for tables and figures. It tests both inline rchunks as well as testing a separate rchunk file. Both are now working fine. 

See: https://github.com/aetiologicCanada/matthew_default_bookdown

Tables captions appear to require syntax such as:
------ begin here
# Tables with R chunks

 ```{r foo4, tidy=TRUE, echo=FALSE, cache=FALSE}```
 Table: (\#tab:foo4) Caption TableRchunk Goes Here 

Here we reference the  table: \@ref(tab:foo4)
---- end here -----
Lines such as:

**Table: (\#tab:foo4) Caption TableRchunk Goes Here** 

are needed to generate table captions and referencing but these lines are neither "text" in the usual sense, nor are the lines traditional "R code."   It seems to be that they violate the clear distinction needed between R code and text in an Rmd file, and some reconsideration is needed. Perhaps it would be clearly if these lines could be placed within code chunks or were transformed into classical R functions that could be called from the Rmd file. 

Some rationalization of how the code works for this problem, and a rewrite of Section 2.5 would be most helpful.

**Comment by yihui** [comment]
Could you please correctly format your issue first (in particular, please check out [the four-backtick rule](https://yihui.name/en/2017/05/four-backticks-github/))?

**Comment by moui72** [comment]
I was struggling to get crossref to work and found that I had to use `/@ref{label}` instead of `/@ref(label)` -- do I have something out of date?

settings:

```yaml
output: 
  bookdown::tufte_handout2: 
    toc: True
    latex_engine: xelatex
```
