### ISSUE TITLE
Navigation is not working in the preview of a book

### ISSUE THREAD

**Issue by FvD** [rstudio/bookdown#47]
When I preview the a book using the preview addin, or serve_book() the navigation doesn't work in the RStudio Viewer. When opened from the viewer into an external browser links are downloaded as html files, and not opened in the browser. If I open index.html for the same book directly in an external browser navigation works correctly.

When I open index.html of the book directly withservr::httw and servr::httd they show the same behaviour: links in the TOC are downloaded and not opened in the browser. The same index.html TOC works correctly when opened directly in an external browser.

**Comment by yihui** [comment]
That is odd. What is your version of RStudio and operating system?

**Comment by FvD** [comment]
Ubuntu 14.04 with RStudio 0.99.878.

**Comment by yihui** [comment]
I cannot reproduce it with the current release of RStudio 0.99.892 on Ubuntu 15.04: https://www.rstudio.com/products/rstudio/download/

**Comment by FvD** [comment]
The issue persists after updating to RSTudio 0.99.892. I installed knitr from you github repo so that the version is 1.12.21 to solve some initial issues I had rendering the bookdown example in the inst folder. servr is at version 0.3.

To try to narrow the issue down I reduced the example in the inst folder to a [minimal template](https://github.com/FvD/bdtemplate) and I can reproduce the issue with that smaller file-set. Perhaps I should update all your packages to the yihui-XRAN repo.

**Comment by yihui** [comment]
I don't think this is relevant to knitr, because you said even `servr::httd()` for static HTML files had the same problem.

The possible reason is that your Ubuntu system does not recognize the MIME type of .html files. You may run the system command `mimetype` on any HTML file to see the output, or [`servr:::guess_type()`](https://github.com/yihui/servr/blob/master/R/utils.R#L102-L110) on an HTML file. The expected output is `text/html`, and you system might give `application/octet-stream`.

**Comment by FvD** [comment]
Yes, that is probably it!

     > servr:::guess_type("index.html")
     [1] "application/x-extension-html"

**Comment by yihui** [comment]
Do you know how to modify MIME types? If not, you may look at this article: https://help.ubuntu.com/community/AddingMimeTypes It is odd anyway; `application/x-extension-html` should not be the default MIME type on Ubuntu.

**Comment by FvD** [comment]
Yes, it was in fact the mime type that was causing the issue. I am not sure which application made the change, but suspect it was Firefox at some point.

To change the mime type for html files back to the text/html default these were the steps I had to take. Remove the x-extension-html.xml and user-extension-html.xml files from the ~./local/share/mime folder and then rebuild the mime type database. In the steps below I do not delete the files, but copy them to the desktop.

```
mv ./local/share/mime/application/x-extension-html.xml ~/Desktop
mv ./local/share/mime/packages/user-extension-html.xml ~/Desktop

update-mime-database ~/.local/share/mime
```

Then log-out and log in again. The mimetype is now correct and the bookdown preview works as expected.
