### ISSUE TITLE
Bookdown iPad Pro bug

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [rstudio/bookdown#470]
Are there any plans in place for optimizing the Bookdown reading experience for iPad Pro users?  I noticed that the toolbar does not appear at all (e.g., for adjusting font size, white/sepia/night reading mode, etc.).  Is this a known issue?  Thank you for your time and hope this helps.

**Comment by yihui** [comment]
Yes, it is a known issue (you can search for "iPad" in existing issues). Duplicate of #60 and #438.
