### ISSUE TITLE
Too little space after subheader enumeration in table of contents

### ISSUE THREAD

**Issue by eeenilsson** [rstudio/bookdown#472]
When using 10+ headers with 10+ subheaders, the blankspace after enumeration in table of contents will be too short and the enumeration appear adjacent to the subheader text. Suggest increasing default blankspace after enumeration in table of contents.

Ie, put in .rmd and run bookdown:
```

---
title: Test enumeration
---

# Header1
# Header2
# Header3
# Header4
# Header5
# Header6
# Header7
# Header8
# Header9
# Header10
## Sub A
## Sub B
## Sub C
## Sub D
## Sub E
## Sub F
## Sub G
## Sub H
## Sub I
## Sub J
## Sub K

```

**Comment by yihui** [comment]
Could you post a screenshot when talking about styles?

**Comment by eeenilsson** [comment]
![image](https://user-images.githubusercontent.com/20885220/31876682-d35cbc94-b7d3-11e7-9127-d07af4d14730.png)

**Comment by yihui** [comment]
So you were talking about PDF output. This is essentially a LaTeX question instead of a bug report or feature request of bookdown per se, so please consider [asking it on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) or StackExchange instead (with a reproducible example). Thanks!
