### ISSUE TITLE
bookdown fails using the most recent pandoc version

### ISSUE THREAD

**Issue by theGreatWhiteShark** [rstudio/bookdown#475]
Yesterday (12.10.2017) I installed the latest version of **pandoc** from its master brach on Github, since **bookdown** asked me to use a more recent version.

But unfortunately **bookdown** doesn't work with the newest version. 

I'm using

> pandoc --version
> pandoc 2.0
> Compiled with pandoc-types 1.17.2, texmath 0.9.4.4, skylighting 0.4.1
> Copyright (C) 2006-2017 John MacFarlane

The actual version number is

> $ git describe --tags
> 1.19.2-1914-gc3dca09

and the SHA of my current head is

> $  cat .git/refs/heads/master
> c3dca0923c12cbaf48ec9f637a4329e9ca8df597

For *gitbook* and *html_book* the error message is

> /home/X/bin/pandoc +RTS -K512m -RTS _main.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output _main.html --smart --email-obfuscation none --standalone --section-divs --table-of-contents --toc-depth 3 --template /home/X/R/R-3.4.0/library/bookdown/templates/gitbook.html --highlight-style pygments --number-sections --include-in-header /tmp/Rtmpk9ukj1/rmarkdown-strcc45c5c1a9.html --mathjax 
> --smart/-S has been removed.  Use +smart or -smart extension instead.
> For example: pandoc -f markdown+smart -t markdown-smart.
> Try pandoc --help for more information.

and for *pdf_book* it's

> /home/X/bin/pandoc +RTS -K512m -RTS _main.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output _main.tex --table-of-contents --toc-depth 2 --template /home/X/R/R-3.4.0/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --number-sections --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' --variable tables=yes --standalone 
> --latex-engine has been removed.  Use --pdf-engine instead.
> Try pandoc --help for more information.
> Error: pandoc document conversion failed with error 2

**Comment by yihui** [comment]
Thanks for being brave to test the development version of Pandoc. We are aware of these issues (https://github.com/rstudio/rmarkdown/issues/1120) and will consider backward-compatible fixes in the upstream rmarkdown package.

**Comment by yihui** [comment]
I just submitted a fix and please test `devtools::install_github('rstudio/rmarkdown#1168')` if you want. Thanks!

**Comment by theGreatWhiteShark** [comment]
Nice. Everything looks fine.

Thanks a lot!
