### ISSUE TITLE
"Feature request". Support conda environments for chapters/parts.

### ISSUE THREAD

**Issue by Adrianzo** [rstudio/bookdown#476]
I'm using conda environments for administering the applications and libraries through my work. I'm not able to use bookdown to write my report since the whole build needs to be done in one environment. I understand this is by design, and I don't know if it can be changed. So I need to ask:

Wouldn't be possible to have chapters assigned to different conda environments?

Cheers!

**Comment by yihui** [comment]
I know nothing about Conda, so I cannot offer any help here (bookdown is an R package after all). I recommend you to [try StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead. Thanks!
