### ISSUE TITLE
Publishing instructions for Gitlab

### ISSUE THREAD

**Issue by jsta** [rstudio/bookdown#477]
I wonder if a PR to include publishing information for Gitlab would be welcome. Except for the fact that the Gitlab documentation is terrible (overly complex Gitlab admin instructions are mixed with user facing docs), I found the process to be easier than Github.

The process is Docker based and you don't have to deal with `.nojekyll` or tokens (build outputs are moved within Gitlab to Gitlab pages) as "artifacts".

I worked off of the example here by @ConorIA: https://github.com/ConorIA/dockerfiles/tree/master/alpine-r-bookdown

**Comment by ConorIA** [comment]
@jtsa, thanks for the ping. Here is a live example if it is any help. To be honest, I stopped using my own Docker image because of locale issues with Alpine. 

https://gitlab.com/ConorIA/r4cs/blob/master/.gitlab-ci.yml

**Comment by jsta** [comment]
In my case, any image that has pandoc + devtools prereqs will work.

**Comment by yihui** [comment]
I added a section on publishing from GitLab in the **blogdown** book, but I think you can easily replace **blogdown** with **bookdown**: https://bookdown.org/yihui/blogdown/gitlab-pages.html The idea is the same.
