### ISSUE TITLE
pandoc 2.0.x makes bookdown render empty htmls

### ISSUE THREAD

**Issue by maxheld83** [rstudio/bookdown#479]
I think this might be another `pandoc 2.0.x` snafu.

### Steps to reproduce

1. `brew switch pandoc 2.0.0.1` **or** `brew switch pandoc 1.19.2.4` (I think this is the offender)
2. open new boilerplate bookdown
3. `rmarkdown::render_site(encoding = 'UTF-8')`

### Observed behavior

Everything works fine with pandoc < 2.

With pandoc > 2, PDF looks fine, **but html is empty, except for the TOC and title**:

<img width="584" alt="emptybook" src="https://user-images.githubusercontent.com/5372770/32343907-6bcba90c-c005-11e7-940a-c8fe4f15bac8.png">

The HTML still includes the requisite text snippets, so perhaps this is a CSS problem?

I also tried to reproduce the issue with a plain `rmarkdown` file (no bookdown), but couldn't reproduce is, so I am guessing this is on `bookdown`s end.

### Colophon

I tried this using the latest `rmarkdown` and `bookdown` versions off of github.

`sessionInfo()`:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_1.6.0.9009 bookdown_0.5.4      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13    withr_2.1.0     digest_0.6.12   rprojroot_1.2   R6_2.2.2        backports_1.1.1 git2r_0.19.0    magrittr_1.5    evaluate_0.10.1 httr_1.3.1      stringi_1.1.5   curl_3.0        devtools_1.13.3
[14] tools_3.4.2     stringr_1.2.0   yaml_2.1.14     rsconnect_0.8.5 compiler_3.4.2  memoise_1.1.0   htmltools_0.3.6 knitr_1.17   
```

`brew list --versions`:

```
pkg-config 0.29.2 0.29.1_2
libtiff 4.0.7_2 4.0.7_3 4.0.8 4.0.8_1 4.0.8_4 4.0.8_3 4.0.8_2 4.0.8_5
libtool 2.4.6_1
netlifyctl 0.1.4 0.1.5
imagemagick@6 6.9.9-20 6.9.9-21 6.9.9-19 6.9.9-17 6.9.9-12 6.9.9-15 6.9.9-14
pandoc 2.0.1 1.19.2.1 1.19.2.2 2.0.0.1 1.19.2.4
little-cms2 2.8 2.8_1
```

**Comment by yihui** [comment]
Thanks for the report! bookdown is not ready for Pandoc 2.0 yet; if you use RStudio, there is no need to install pandoc unless you absolutely want the newer version of Pandoc: https://github.com/rstudio/rmarkdown/issues/1184

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
