### ISSUE TITLE
Custom LaTeX commands: scene break

### ISSUE THREAD

**Issue by theramiyer** [rstudio/bookdown#484]
Hi!

I'm trying to write a novel using bookdown: HTML, EPUB, as well as PDF (pdfLaTeX). I'm using the indent mode, so paragraphs begin with an indent. I have the following custom LaTeX command, called `\scenebreak`, which:

 1. Leaves an empty line between paragraphs when the scene changes within a chapter.
 2. Introduces a ding, if the scene break is at the end of a page, or the beginning of a page.
 3. Resets indent for the paragraph that follows the break (the paragraph that follows the break starts flush left).

Here's the LaTeX:
````latex
% scene breaks
\renewcommand{\pfbreakdisplay}{%
\scriptsize\ding{86}}
\newcommand{\scenebreak}{\pfbreak*\noindent}
\newcommand{\forceindent}{\leavevmode{\indent}}
````
In HTML, this is how I've done it:
````html
<div style='text-align:center;'>&#8226;</div>
````
I'm aware that a `block` in bookdown is like a LaTeX environment.

Is a similar setup possible with commands/macros?

The original [question was posted on StackExchange](https://stackoverflow.com/questions/47253228/how-to-a-scenebreak-in-bookdown), but got no response. Hence the highlight here.

**Comment by yihui** [comment]
Let's continue on SO. Thanks!
