### ISSUE TITLE
Wish: html blockquote and latex quote environment to work in the respective other format

### ISSUE THREAD

**Issue by ugroempi** [rstudio/bookdown#487]
In html, if I use 
`\begin{quote}`
`some quotation`
`\end{quote}`
the text in `some quotation` is simply ignored.
In pdf, if I use 
`<blockquote>`
`some quotation`
`</blockquote>`
the text in `some quotation` is printed but not treated as a quotation.

It would be nice if both would respect each other.

Best, Ulrike

**Comment by yihui** [comment]
What is wrong with `>`? https://bookdown.org/yihui/bookdown/markdown-syntax.html

**Comment by ugroempi** [comment]
Thanks for the pointer, I overlooked this, and nothing is wrong with it - it still would be nice (but by no means necessary) if bookdown would also understand the html and latex markup for block quotes.

Best, Ulrike
