### ISSUE TITLE
lemma labels not being processed...

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#488]
Greetings,

lemma environment (and perhaps others though proof works) is not processing labels...

Minimal example follows.

Thanks!

---
output: bookdown::pdf_document2
---

```{lemma,label="lemA.00"}
  Blah
```

```{proof}
Proof of \@ref(lem:lemA.00).
```

```{proof,label="proofA.00"}
  Blah
```

> devtools::session_info('bookdown')
Session info -----------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin17.0.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       <NA>                        
 date     2017-11-21                  

Packages ---------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.1.1   2017-09-25 CRAN (R 3.4.2)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                    
 bookdown    0.5.10  2017-11-15 Github (rstudio/bookdown@0d3e67c) 
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                    
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.0)                    
 graphics  * 3.4.2   2017-10-08 local                             
 grDevices * 3.4.2   2017-10-08 local                             
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)                    
 knitr       1.17.15 2017-11-19 Github (yihui/knitr@39567eb)      
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                    
 markdown    0.8     2017-04-20 CRAN (R 3.4.1)                    
 methods   * 3.4.2   2017-10-08 local                             
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                    
 Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)                    
 rmarkdown   1.8.2   2017-11-21 Github (rstudio/rmarkdown@b84f706)
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)                    
 stats     * 3.4.2   2017-10-08 local                             
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                    
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)                    
 tools       3.4.2   2017-10-08 local                             
 utils     * 3.4.2   2017-10-08 local                             
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)                    
> rmarkdown::pandoc_version()
[1] ‘2.0.2’
> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/MacPorts 2017_2)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.32; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.57.0

**Comment by yihui** [comment]
Please read the documentation: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html

> All labels in bookdown must only contain alphanumeric characters, `:`, `-`, and/or `/`.
