### ISSUE TITLE
FR: Breadcrumb Support?

### ISSUE THREAD

**Issue by pgensler** [rstudio/bookdown#489]
Is it possible to get the ability to have a breadcrumb for navigation? I can't tell you how many times I would love to have that for easier navigation of R4DS. Thanks.

**Comment by yihui** [comment]
By default, bookdown's `gitbook` format will highlight the current subsection that you are reading in the sidebar, e.g.,

![image](https://user-images.githubusercontent.com/163582/33134911-95029e96-cf66-11e7-8d4a-36f9a6bbdcb1.png)

That should be similar to breadcrumb navigation. R4DS didn't seem to have customized the collapsing of section titles in the left sidebar. See the documentation of the `config` option: https://bookdown.org/yihui/bookdown/html.html It is up to the book authors which collapsing style they want. For R4DS, the current section will be highlighted in the sidebar, but not subsections.

**Comment by pgensler** [comment]
Yeah, I see your point, it's not always the easiest to search for items inside the book, and click, view an item, go back to results, etc...

Does Blogdown intend to have this feature, or does Hugo not support it? I've been wanting to create a simple website for R Code I use regularly(similar to Cookbook for R site), but I have not seen this feature. 

Related:
https://stackoverflow.com/questions/45943871/how-to-create-working-breadcrumbs-for-hugo

![image](https://user-images.githubusercontent.com/7308115/33135708-c7145a80-cf68-11e7-8a17-ccc24c6db150.png)


http://www.cookbook-r.com/Data_input_and_output/Writing_text_and_output_from_analyses_to_a_file/

**Comment by yihui** [comment]
blogdown is a better way to go if you really care about breadcrumb navigation, but... you have to either find an existing theme that supports it, or add it by yourself: https://gohugo.io/content-management/sections/

Note that you won't be able to cross-reference elements on different pages, or build a PDF out of multiple Rmd's (https://community.rstudio.com/t/2767). All you can build at the moment from blogdown is a website.
