### ISSUE TITLE
PDF Output & Appendix: Missing hypereref braces

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/bookdown#490]
Consider an `Rmd` like so:

    ---
    title: Appendix Bug?
    date: '`r format(Sys.time(), "%d %B, %Y")`'
    output:
      bookdown::pdf_document2:
        template: ~
        toc: yes
        toc_depth: 2
    colorlinks: yes
    fontsize: 11pt
    documentclass: scrartcl
    geometry: margin=1in, a4paper
    ---
    
    # Title 1
    
    ## Title 1.1
    
    # Title 2
    
    # (APPENDIX) Appendix {-}
    
    # ATitle 1
    
    ## ATitle 1.1
    
    # ATitle 2
    
Knitting that to pdf fails with this error:

    ...
    ! Paragraph ended before \hypertarget was complete.
    <to be read again> 
                       \par 
    l.87
    ... 

 Exploring log and tex files indeed leads to the observation, that the `Appendix` hypertarget is not closed:

    ...
    \hypertarget{title-2}{%
    \section{Title 2}\label{title-2}}
    
    \hypertarget{appendix-appendix}{%
    \appendix
    
    
    \hypertarget{atitle-1}{%
    \section{ATitle 1}\label{atitle-1}}
    ...

This is on 

> devtools::session_info('bookdown')
Session info --------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       RStudio (99.9.9)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2017-11-22                  

> Packages ------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 backports   1.1.1   2017-09-25 CRAN (R 3.4.2)
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.2)
 bitops      1.0-6   2013-08-17 CRAN (R 3.4.2)
 bookdown    0.5     2017-08-20 CRAN (R 3.4.2)
 caTools     1.17.1  2014-09-10 CRAN (R 3.4.2)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.1)
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.2)
 graphics  * 3.4.2   2017-11-13 local         
 grDevices * 3.4.2   2017-11-13 local         
 highr       0.6     2016-05-09 CRAN (R 3.4.2)
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.2)
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)
 knitr       1.17    2017-08-10 CRAN (R 3.4.2)
 magrittr    1.5     2014-11-22 CRAN (R 3.4.2)
 markdown    0.8     2017-04-20 CRAN (R 3.4.2)
 methods   * 3.4.2   2017-11-13 local         
 mime        0.5     2016-07-07 CRAN (R 3.4.1)
 Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)
 rmarkdown   1.7     2017-11-10 CRAN (R 3.4.2)
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.2)
 stats     * 3.4.2   2017-11-13 local         
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.2)
 tools       3.4.2   2017-11-13 local         
 utils     * 3.4.2   2017-11-13 local         
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.2)

> rmarkdown::pandoc_version()
[1] ‘2.0.3’

> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Arch Linux)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.61.0

**Comment by r-cheologist** [comment]
Actually - after `devtools::install_github('rstudio/bookdown') this seems fixed, BUT: while the title numbering switches after the `APPENDIX` call, there is no part title 'Appendix', which I woudl expect in the above ...

**Comment by yihui** [comment]
Yes, the issue has been fixed two weeks ago in 923b6db61c28169fe7f794597e1e72d319b0dbc5. BTW, you don't need Pandoc 2.0: https://yihui.name/en/2017/11/pandoc-2/

>  there is no part title 'Appendix', which I would expect in the above ...

It is up to the LaTeX document class. `\appendix` in LaTeX _does not necessarily_ generate the title "Appendix". This is a LaTeX question. Please google it by yourself for a solution or ask on TeX StackExchange.
