### ISSUE TITLE
tikzDevice and plot legends... $\\operatorname{E}$ - TeX was unable to calculate metrics...

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#492]
Greetings, 

Using tikzDevice, "$\\\\operatorname{E}(Y|x)$" is properly processed in fig.cap however it fails in legend... the following minimal example illustrates... if you use "$E(Y|x)$" in the legend the figure compiles properly... I presume it ought to work both for figure captions and figure legends?

Thanks!

The error is

Quitting from lines 11-16 (debug.Rmd) 
Error in getMetricsFromLatex(TeXMetrics, verbose = verbose) : 
TeX was unable to calculate metrics for the following string
or character:

	$\operatorname{E}(Y|x)$

Common reasons for failure include:
  * The string contains a character which is special to LaTeX unless
    escaped properly, such as % or $.
  * The string makes use of LaTeX commands provided by a package and
    the tikzDevice was not told to load the package.

````markdown
---
title: "Test"
output: bookdown::gitbook
---

```{r global_options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(dev='tikz')
```

```{r,echo=FALSE,fig.cap="$\\operatorname{E}(Y|x)$."}
x <- rnorm(100)
y <- 1 + x + rnorm(100)
plot(x,y,ylab="$Y$",xlab="$X$")
abline(lm(y~x))
legend("topleft","$\\operatorname{E}(Y|x)$",col=1,lty=1,bty="n")
```
````

```r
> devtools::session_info('bookdown')
Session info --------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin17.0.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       <NA>                        
 date     2017-11-25                  

Packages ------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.1.1   2017-09-25 CRAN (R 3.4.2)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                    
 bookdown    0.5.10  2017-11-21 Github (rstudio/bookdown@d78c661) 
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                    
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.0)                    
 graphics  * 3.4.2   2017-10-08 local                             
 grDevices * 3.4.2   2017-10-08 local                             
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)                    
 knitr       1.17.20 2017-11-23 Github (yihui/knitr@33a3ba6)      
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                    
 markdown    0.8     2017-04-20 CRAN (R 3.4.1)                    
 methods   * 3.4.2   2017-10-08 local                             
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                    
 Rcpp        0.12.14 2017-11-23 CRAN (R 3.4.2)                    
 rmarkdown   1.8.3   2017-11-21 Github (rstudio/rmarkdown@07f7d8e)
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)                    
 stats     * 3.4.2   2017-10-08 local                             
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                    
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)                    
 tools       3.4.2   2017-10-08 local                             
 utils     * 3.4.2   2017-10-08 local                             
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)                    
> rmarkdown::pandoc_version()
[1] ‘2.0.2’
> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/MacPorts 2017_2)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.32; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.57.0
```

**Comment by yihui** [comment]
I have to say that `dev = 'tikz'` is for very advanced users only. I might know the solution, but I don't have time. `\operatorname` is from **amsmath**, and you have to let `tikzDevice::tikz()` load this package. How? That is the key part of the solution, and you have to do your own homework.

BTW, please do not ignore [the issue template](https://github.com/rstudio/bookdown/issues/new) the next time you open a new issue. Specifically:

1. Please consider [asking questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) first.

2. Please format your issue correctly (use four backticks).

**Comment by JeffreyRacine** [comment]
Many thanks for the kind response, and apologies for mangling the issue template.

I have used tikzDevice with bookdown for a year now and was simply trying to report that captions work flawlessly but legends do not which strikes me as a bug. Of course it could be my lack of digging around as well as you suggest, which I will do.

I am currently editing a manuscript that is 600+ pages with over 100 figures that all use tikz and just encountered this issue so thought it best to report it. 

I will do more homework as you suggest, and many thanks for your contributions!  Truly great work.
