### ISSUE TITLE
Level 5 headings with {-} have numbering

### ISSUE THREAD

**Issue by zeehio** [rstudio/bookdown#493]
This small project [test_project.zip](https://github.com/rstudio/bookdown/files/1511590/test_project.zip) has an index.rmd like:

    --- 
    title: "Level 5 without numbers in front?"
    author: "Sergio Oller"
    date: "`r Sys.Date()`"
    output: pdf_document
    documentclass: book
    site: bookdown::bookdown_site
    description: This is a minimal example
    ---
    
    #### Level4
    
    Hello world
    
    #### Level4minus {-}
    
    Hello world
    
    ##### Level5
    
    Hello world
    
    ##### Level5minus {-}
    
    This one does not respect the minus!
    
This is the result after building the PDF:
![imatge](https://user-images.githubusercontent.com/75441/33343660-73277416-d486-11e7-81f6-f13d6a50da8e.png)

The level 5 minus is always numbered, no matter the `{-}`. Is there a way to remove the numbering? 

For now I will just use `**Level5minus**` instead of a header, but I would rather use a header to avoid page breaks right after it.

Thanks for your work in bookdown, I am about to finish writing my PhD thesis using it! 😃

**Comment by zeehio** [comment]
I was able to trace this back to pandoc https://github.com/jgm/pandoc/issues/3058

All we can do from bookdown would be to use this workaround described in their issue:

    \edef\foo{\arabic{secnumdepth}}
    \setcounter{secnumdepth}{0}
     \paragraph{AAAA}\label{aaaa}
     \addcontentsline{toc}{paragraph}{AAAA}
     \setcounter{secnumdepth}{\foo}

If there is interest I can try to write the patch, but given that it was never merged in pandoc I am not sure it is a good idea to merge it in bookdown.

**Comment by yihui** [comment]
Thanks for the great detective work! I'm not interested in supporting this. I rarely go beyond level 3 myself. If you need to patch the .tex output, you may use the R global option `bookdown.post.latex`: https://github.com/rstudio/bookdown/releases/tag/v0.4

**Comment by zeehio** [comment]
Thanks! And thanks as well for the post.latex tip!
