### ISSUE TITLE
Option to limit the depth of numbered headings

### ISSUE THREAD

**Issue by acarl005** [rstudio/bookdown#495]
I really like the `number_sections: TRUE` option in my `_output.yml`. It would be convenient if there was also a way to limit the numbering depth, like only number headings of level 1, 2, or 3. This would be analogous to the `toc_depth` option, which limits the depth of headings visible in the table of contents.

For now I'm adding `{-}` manually to my smaller headings, but it's a bit cumbersome.

**Comment by yihui** [comment]
If Pandoc's Markdown has such a feature (I don't think it does), I'd be happy to support it. [I'm not interested](https://yihui.name/en/2017/11/on-saying-no/) in implementing this feature by myself. Thanks for the bring it up!
