### ISSUE TITLE
Section References when Section Number is chosen as FALSE

### ISSUE THREAD

**Issue by JedStephens** [rstudio/bookdown#496]
Thanks for the great package!

I have created a MWE to demonstrate the oddity I have found.
When  number_sections: FALSE in the _output.yml the LaTeX file generated by the bookdown build process does not display the section. 

To demonstrate I have uploaded my MWE. In this, you will find two identical examples except in the one I have number_sections: FALSE and the sectioned is not referenced and in the other number_sections: TRUE the section is referenced with the section number. 

[bookdown MWP - Ref.zip](https://github.com/rstudio/bookdown/files/1555755/bookdown.MWP.-.Ref.zip)

I know this problem could exist in the way that the LaTeX referencing works (when bookdown has set the section levels = 0.) Nonetheless, just because one does not want section numbers, should not limit one's ability to reference sections.

I propose a solution like this:
If Section Numbers are FALSE, then authors would most likely want to reference on the section title. 
One could use the LaTeX package:
\usepackage{nameref}
%Which would do the following:
 \section{Evolution of Bookdown}\label{sec:Chpt1}

Where when LaTeX processes 
`This package allows the title associated with the anchor to be used \nameref{sec:Chpt1}
`
The output is:
This package allows the title associated with the anchor to be used Evolution of Bookdown.

This could be resolved by:
1. adding the nameref package to the LaTeX preamble
2. By changing \ref{} to \nameref{} for those who chose number_sections: FALSE

Let me know if I can help.

**Comment by cderv** [comment]
This issue is related to #6 to use a short syntax like `\@ref{}` instead of the [header reference](http://pandoc.org/README.html#extension-implicit_header_references) using the syntax described in https://bookdown.org/yihui/bookdown/cross-references.html

- `[link text][Section header text]`
- `[link text](#ID)`

I'll close to track into #6 and one can use the above syntax to make it work currently.
