### ISSUE TITLE
Chapter and section numbering with preview_chapter (and related functions)

### ISSUE THREAD

**Issue by rundel** [rstudio/bookdown#497]
I've attached a sample bookdown folder where the Rmds have been separated by section instead of chapter. [preview_bug.zip](https://github.com/rstudio/bookdown/files/1557745/preview_bug.zip)

This book renders correctly when using 
```r
render_book("index.Rmd", output_format = html_book(split_by="chapter"))
```
but I get misnumbering / mangling of the non-previewed sections when I attempt to use `preview_chapter`, `render_book` with `preview=TRUE` and `serve_book`.

For example, running the following with provide book
```r
preview_chapter("01-chap-02.Rmd", output_format = html_chapters())
```
gives me something that looks like

**Welcome**
**1 Chapter 1**
**2 Placeholder**
**2.1 Part 1**
**2.2 Part 2**
This is chapter one section two.
**3 Placeholder**
**3.1 Part 3**
**4 Chapter 2**
**5 Placeholder**
**5.1 Part 1**
`preview_chapter` (and hence `render_book`) is partially examining at least the first line of the other Rmds to come up with some of the placeholder text but it is not currently paying attention to the section level of that content. At least for the preceding sections it seems like it gets it partially right but there is still an additional unnecessary placeholder.

**Comment by yihui** [comment]
Thanks for the report!

1. The documentation says (https://bookdown.org/yihui/bookdown/usage.html):

> [...] Each R Markdown file must start immediately with the chapter title using the first-level heading.

2. Preview is for, preview, only. https://bookdown.org/yihui/bookdown/preview-a-chapter.html You should only expect a single Rmd to be correctly previewed, and should not be surprised if funny things happen in the output of other Rmds.

**Comment by rundel** [comment]
I appreciate that the documentation states that each Rmd should correspond to a single chapter but that is not always a reasonable workflow. There is no reason that the workflow described shouldn't work and it has been fine thus far when compiling the complete book, it is just the current preview related bits that are broken.

With regard to point 2. the existing code for preview is broken, hence the bug report. I've just submitted a pull request (#498) which attempts to address this. I haven't tested it extensively but it addresses the issues described above as well as an additional issue with code chunk output being interpreted as sections.

**Comment by yihui** [comment]
Excellent! I'll review your PR tomorrow.
