### ISSUE TITLE
Set output directory

### ISSUE THREAD

**Issue by trestletech** [rstudio/bookdown#5]
We run the following to compile HTML and PDF outputs

```bash
R -e "setwd('/data');" \
   -e "bookdown::render_book('', bookdown::html_chapters(lib_dir='out/assets'), output_dir='out');"
   -e "bookdown::render_book('', 'bookdown::pdf_book', output_file='out/_main.pdf', output_dir='out')"
```

the hope is that all output files would be rendered in `./out`. It took some finagling to get that to work for both HTML and PDF, but it seems like the above set of options successfully executes. The issue is that the chapters HTML is still in the current directory, along with a slew of _main* files. 

It would be great to have a way to avoid polluting the source tree and instead keep all rendered docs in a separate dir.

**Comment by yihui** [comment]
Thanks! That makes sense. I'll think about it. The output directory issue is pretty tricky.
