### ISSUE TITLE
Figure captions don't seem to work with current development version of bookdown

### ISSUE THREAD

**Issue by clauswilke** [rstudio/bookdown#500]
Hello,

I just upgraded pandoc to v2.0.5, rmarkdown to v1.8, and bookdown to github master (v0.5.11), and now I cannot generate figure captions.

For example, if I render the bookdown-demo book, I see:
```
Warning messages:
1: In split_chapters(output, gitbook_page, number_sections, split_by,  :
  You have 7 Rmd input file(s) but only 6 first-level heading(s). Did you forget first-level headings in certain Rmd files?
2: The label(s) fig:nice-fig not found 
```
(The second warning is the one that matters.)

The rendered document looks like this:
<img width="842" alt="screen shot 2017-12-22 at 7 20 39 pm" src="https://user-images.githubusercontent.com/4210929/34315874-4705831c-e74d-11e7-9cdb-5463f82b4f4e.png">

Apparently table captions work.

Session info:
```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14    bookdown_0.5.11 withr_2.1.0     digest_0.6.12   rprojroot_1.2   R6_2.2.2        backports_1.1.1
 [8] git2r_0.19.0    magrittr_1.5    evaluate_0.10.1 httr_1.3.1      stringi_1.1.5   curl_3.0        rstudioapi_0.7 
[15] rmarkdown_1.8   devtools_1.13.4 tools_3.4.2     stringr_1.2.0   yaml_2.1.16     compiler_3.4.2  memoise_1.1.0  
[22] htmltools_0.3.6 knitr_1.17     
```

**Comment by dataopt** [comment]
I have the following minimal example for `index.Rmd`.  If I add `out.width` or `fig.align`, the caption will disappear and the label shows up as `??`  But as is, both caption and the label show up.

````
---
title: "A Book"
author: "Frida Gomam"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    split_by: section
  bookdown::pdf_book: default
---

# Preface {-}

```{r svgtest, echo = FALSE, fig.align='right', fig.cap="Test"}
knitr::include_graphics("images/lemon.svg")
```

See Figure \@ref(fig:svgtest).
````

**Comment by clauswilke** [comment]
Would you mind testing with a separate caption as well, like so:

    (ref:svgtest) Test.
    
    ```{r svgtest, echo = FALSE, fig.cap="(ref:svgtest)"}
    knitr::include_graphics("images/lemon.svg")
    ```

This didn't work for me either when I tried the latest version of bookdown.

After my adventures with pandoc 2.X and the development version of bookdown I successfully downgraded my system and have things working again. Since I'm in the middle of writing a book I don't want to touch my setup right now.

**Comment by dataopt** [comment]
I installed the latest version of `knitr` from GitHub using
```
devtools::install_github("yihui/knitr")
```
and the figure captions and labels are now working.  See if that also works for you.

**Comment by clauswilke** [comment]
I'm glad to hear it's working with the `knitr` development branch. As I wrote in my other post, I'm in the middle of writing a book and can't risk messing up my setup right now, even for a few hours. But I'll try again in a few weeks if this issue is still open then.

**Comment by yihui** [comment]
@dataopt was correct. The issue was fixed in https://github.com/yihui/knitr/commit/f7bb683f8c0045910b0f51dd5a47e231e6f579c3.

@clauswilke Yes, that is a good strategy. I recommend that you stay with Pandoc 1.19 until we officially announce the support of Pandoc 2.0: https://yihui.name/en/2017/11/pandoc-2/ The next version of knitr was submitted to CRAN more than a month ago, but for some reason, it still has not been processed by CRAN maintainers (probably due to the large number of reverse dependencies, which is always huge pain to me). Once knitr 1.18 is published (I don't know when), you should be all set. Feel free to reopen this issue if that is not the case.

**Comment by clauswilke** [comment]
@yihui Thanks a lot for your help, and for your fantastic packages! Your blog post is helpful. I'm one of those people who upgraded pandoc unconsciously.

**Comment by yihui** [comment]
FYI **knitr** 1.18 is on CRAN now. You may test it only if you want. Thanks!

**Comment by clauswilke** [comment]
I can confirm that things work for me with pandoc 2.0.6, knitr 1.18, rmarkdown 1.8, and bookdown 0.5.14. Thanks!
