### ISSUE TITLE
`out.height` seems not working

### ISSUE THREAD

**Issue by sammo3182** [rstudio/bookdown#501]
I am using the developed version of `bookdown` and RStudio 1.2.209. Whenever I tried to modify the plot height with `out.height`, I got the following error:

```
! Paragraph ended before \Gin@ii was complete.
<to be read again> 
                   \par 
l.204 

Error: Failed to compile miniSample.tex. See miniSample.log for more info.
In addition: Warning messages:
1: running command '"pdflatex" -halt-on-error -interaction=batchmode "miniSample.tex"' had status 1 
2: running command '"pdflatex" -halt-on-error -interaction=batchmode "miniSample.tex"' had status 1 
Execution halted
```

I tried to change the compiling engine to `xelatex`, and it still produced the error. `out.width` works pretty well, though.

A minimal sample is attached:
[miniSample.zip](https://github.com/rstudio/bookdown/files/1584698/miniSample.zip)

**Comment by dataopt** [comment]
Looks like the percent sign was parsed literally and caused LaTex to think that it is the beginning of a comment.  The knitted file has the following:
```
\includegraphics[height=80%]{_main_files/figure-latex/pressure-1}
```
Changing `out.height` to `out.width` gives instead the following in the knitted file:
```
\includegraphics[width=0.8\linewidth]{_main_files/figure-latex/pressure-1}
```

So, in the case when `out.height` is specified, the percent sign should be replaced with `\textheight`.

**Comment by dataopt** [comment]
Until the bug is fixed, you can do this:

```{r pressure, out.height='0.8\\textheight'}
plot(pressure)
```

**Comment by yihui** [comment]
Fixed in the dev version of **knitr**. Thanks!
