### ISSUE TITLE
Something is broken with `split_chapters` in `html.R`

### ISSUE THREAD

**Issue by dataopt** [rstudio/bookdown#502]
Using bookdown version 0.5.11 directly from Github with  `split_by: section` when rendering as `gitbook` a minimal book with the following `index.Rmd`

```
---
title: "A Book"
author: "Frida Gomam"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    split_by: section
  bookdown::pdf_book: default
---

# Section 1 

Some content

## subsection 1

Hello.
```

gives the following warning:

```
Warning message:
In split_chapters(output, gitbook_page, number_sections, split_by,  :
  Something wrong with the HTML output. The line </html> is supposed to be </div>
```

Upon a closer looking at the generated html files, something definitely does not look right.  In particularly, the closing `</html>` tag is still commented out and the opening and closing `div` tags don't match properly.

I have yet able to figure out what is wrong with the code in `html.R`.   I hope someone could figure out a fix to the problem.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
