### ISSUE TITLE
Equation labels not properly handled when pandoc 2.0 is used with gitbook output

### ISSUE THREAD

**Issue by dataopt** [rstudio/bookdown#504]
Here is a minimal example for a minimal book with the following `index.Rmd`

```
---
title: "A Book"
author: "Frida Gomam"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    split_by: section
  bookdown::pdf_book: default
---

# Test labels {-}

Second equation label is not replaced with proper tag when using pandoc 2.0

\begin{equation}
x \in \mathbb{R} (\#eq:real)
\end{equation}
Hello
\begin{equation}
y \in \mathbb{Z} (\#eq:integer)
\end{equation}
```

Screenshot of the generated gitbook:
<img width="794" alt="screen shot 2017-12-26 at 4 55 46 am" src="https://user-images.githubusercontent.com/28999218/34353962-154624a4-e9f9-11e7-8b5b-7cfa60c22a45.png">

**Comment by yihui** [comment]
Could you add empty lines before and after `Hello` so that the equation can be in its own paragraph?

**Comment by dataopt** [comment]
Unfortunately, making the equation a paragraph results in too much space in the latex output.  Below are screenshots of before and after putting empty lines around `Hello`.
<img width="657" alt="screen shot 2017-12-28 at 6 44 47 pm" src="https://user-images.githubusercontent.com/28999218/34425946-71cc7c16-ebff-11e7-866a-4164e4287509.png">
<img width="652" alt="screen shot 2017-12-28 at 6 45 23 pm" src="https://user-images.githubusercontent.com/28999218/34425948-74f8d4f2-ebff-11e7-8041-c9d10bfa5d31.png">

**Comment by yihui** [comment]
The spacing issue is easier to solve. A quick google search: https://tex.stackexchange.com/q/224987/9128

**Comment by dataopt** [comment]
Thanks for the suggestion. Unfortunately, using setlength is more a hack than a solution to the problem since to get the desired spacing, I have to specify a negative value for abovedisplayskip.  As the Rmd file contains perfectly valid syntax, the problem is probably a bug in bookdown.

**Comment by yihui** [comment]
I know exactly what the problem is in this case, and I also know to fix it. I just hope I don't have to touch it, for three reasons: (1) I often have too many other things to do; (2) there is a workaround (i.e. this issue does not really block you); (3) [fixing bugs](https://twitter.com/RichRogersIoT/status/946207872269946880) can introduce new problems.

**Comment by dataopt** [comment]
I now also know exactly what the problem is.  I'm making a pull request to pandoc to add newlines around inlined display math.  This should solve the problem.  I hope the PR gets accepted.

**Comment by yihui** [comment]
It is great to know `--wrap=preserve` fixed the issue. It is probably a reasonable default.

**Comment by yihui** [comment]
I just made `--wrap=preserve` the default for Pandoc 2.0. Thanks a lot!
