### ISSUE TITLE
'"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 1

### ISSUE THREAD

**Issue by b1azk0** [rstudio/bookdown#507]
Hello,
each time I try to compile a pdf with `bookdown::render_book("index.Rmd", "bookdown::pdf_book")` I get :

```
Error: Failed to compile bookdown-demo.tex.
In addition: Warning message:
running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 1 
```

This happens with every document - bookdown_demo_master (untouched) included.

When knitting to pdf from a regular mardown file, with default yaml:

```
---
title: "Untitled"
author: ""
date: ""
output: pdf_document
---
```

Pdf renders properly.
Is there anything I can do to fix this?

I'm rnning:
```
> devtools::session_info('bookdown')
Session info ---------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  Polish_Poland.1250          
 tz       Europe/Warsaw               
 date     2017-12-28                  

Packages -------------------------------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.1.2   2017-12-13 CRAN (R 3.4.3)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.3.2)                    
 bookdown    0.5.13  2017-12-28 Github (rstudio/bookdown@c602ebc) 
 digest      0.6.13  2017-12-14 CRAN (R 3.4.3)                    
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                    
 graphics  * 3.4.3   2017-12-06 local                             
 grDevices * 3.4.3   2017-12-06 local                             
 highr       0.6     2016-05-09 CRAN (R 3.3.3)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.1)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)                    
 knitr       1.18.2  2017-12-23 Github (yihui/knitr@2c2acf9)      
 magrittr    1.5     2014-11-22 CRAN (R 3.3.3)                    
 markdown    0.8     2017-04-20 CRAN (R 3.4.3)                    
 methods   * 3.4.3   2017-12-06 local                             
 mime        0.5     2016-07-07 CRAN (R 3.3.2)                    
 Rcpp        0.12.14 2017-11-23 CRAN (R 3.4.2)                    
 rmarkdown   1.8.5   2017-12-19 Github (rstudio/rmarkdown@9f45f00)
 rprojroot   1.3-1   2017-12-18 CRAN (R 3.4.3)                    
 stats     * 3.4.3   2017-12-06 local                             
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                    
 stringr     1.2.0   2017-02-18 CRAN (R 3.3.3)                    
 tools       3.4.3   2017-12-06 local                             
 utils     * 3.4.3   2017-12-06 local                             
 yaml        2.1.16  2017-12-12 CRAN (R 3.4.3)                    
> system2('xelatex', '--version')
MiKTeX-XeTeX 2.9.6501 (0.99998) (MiKTeX 2.9.6500 64-bit)
(C) 1994-2008 by SIL International, (C) 2009-2012 by Jonathan Kew, (C) 2010-2012 by Han The Thanh, (C) 2012-2013 by Khaled Hosny
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.56.1; using libcurl/7.56.1 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with fontconfig version 2.12.6; using 2.12.6
compiled with freetype2 version 2.8.1; using 2.8.1
compiled with graphite2 version 1.3.10; using 1.3.10
compiled with harfbuzz version 1.6.3; using 1.6.3
compiled with icu version 60.1; using 60.1
compiled with jpeg version 9.2
compiled with liblzma version 50020032; using 50020032
compiled with libpng version 1.6.34; using 1.6.34
compiled with libressl version LibreSSL 2.5.3; using LibreSSL 2.5.3
compiled with MiKTeX Application Framework version 2.6416; using 2.6416
compiled with MiKTeX Core version 3.6505; using 3.6531
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 1.6488; using 1.6488
compiled with poppler version 0.60.1
using teckit version 2.4
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.11; using 1.2.11
```

**Comment by yihui** [comment]
I have no idea why that happens, but if you don't mind, could you remove MiKTeX and try TinyTeX instead? https://yihui.name/tinytex/

```
devtools::install_github(c('yihui/tinytex', 'rstudio/rmarkdown'))
tinytex::install_tinytex()
```

Restart RStudio, and rebuild the book to PDF.

**Comment by b1azk0** [comment]
Yes, that works like a charm - at least with the bookdown demo master and an other short bookdown I did.
Fails to compile an 8 chapter, 400 pages long, heavy in R code book - but I'll inspect it as it must be related with something else, since short ones are OK.
Thanks!

**Comment by yihui** [comment]
Great! If it is a LaTeX issue, I'll be happy to help when you feel you are stuck, since TinyTeX is a new project of mine, and not many people have tested it (I'm especially interested in how well it works on Windows).

**Comment by b1azk0** [comment]
If you need to test anything specifc let me know - i can do it.

For the time being ill stick with html for the long bookdown project, but keep in mind that issues I'm facing there are not latex (probably) related.
One thing is sure: on miktex pdf conversion did not work at all. With TinyTex it does out of the box - at least with simple / untouched demo / cases.

I do have an other problem - with[ polish coding being lost](https://stackoverflow.com/questions/47820217/r-encoding-of-labelled-data-and-knit-to-html-problems/47831332#47831332) when kniting an html document, but that's an other issue, not latex related.

**Comment by yihui** [comment]
Sounds good. I'll take a look at your SO post when I have a chance.

**Comment by yihui** [comment]
I have reasonably rich experience on encoding issues on Windows (although I don't use Windows myself), and I'm pretty sure I can figure out a solution to your SO problem, but... sjPlot is not my package, and I probably cannot afford the time to debug it (which may turn out to be as short as 10 minutes or as long as an hour). Daniel should be the best person to help you, and I think his answer is close to a real solution.

**Comment by melindahiggins2000** [comment]
Thank you for this post. I just ran into this issue myself this past week (I'm running Windows 10). Uninstalling MiKTeX and installing `tinytex` did fix the problem. But I'd be curious to know what is breaking using MiKTeX since (in the past) that has been what I've been recommending to other Windows-based RStudio users. I'm also curious if Mac users running MacTeX have also had these issues. I'll stay tuned to this issue and look for future posts and discussion. Thank you Yihui for `tinytex`!!

**Comment by yihui** [comment]
@melindahiggins2000 I have no idea why MiKTeX won't work. So far I haven't heard serious issues with tinytex, so I'm relatively confident to recommend it to future users. Personally I'm very excited about this package, and I think it can solve some long-lasting headache in LaTeX (especially for R Markdown users).

**Comment by 00-BonnieB** [comment]
Like, @melindahiggins2000 , I am also running Windows 10.  (I am on R 3.3.2 if this helps.)
MiKTex is not on my machine and adding `**tinytex**` still keeps the issue:

`running command '"xelatex" -halt-on-error -interaction=batchmode "bookdown-demo.tex"' had status 127`

Am I missing something? 


PS. Good call with bookdown - am really looking forward to seeing it pick up!

**Comment by yihui** [comment]
@00-BonnieB `tinytex::install_tinytex()`

**Comment by 00-BonnieB** [comment]
@yihui, Not sure what happened there, but it works like a charm!

Guess there is a difference in installation:
`install.packages("tinytex")` and then `tinytex::install_tinytex()`

**Comment by yihui** [comment]
@00-BonnieB Yes, the former installs the R package **tinytex**, and the latter installs a LaTeX distribution TinyTeX. I know it is kind of confusing :)
