### ISSUE TITLE
render before publish?

### ISSUE THREAD

**Issue by jjallaire** [rstudio/bookdown#51]
In the docs for publish_book I say "be sure to render all your formats before publishing". Should we just automatically render before publishing? (perhaps with a `render` argument to override this behavior). I guess if books are computationally expensive it would be annoying to have them auto-rendered but in that case perhaps caching is in use. 

Don't have a strong opinion here, just wanted to raise the issue for discussion.

**Comment by yihui** [comment]
I think we can add an argument `render = FALSE` to `publish_book()`, and provide a checkbox in the GUI so authors can decide by themselves whether to render the book before publishing. I'm wondering if the RStudio IDE should provide this button, or I just write a simple addin for it. The latter sounds easier, but the former may be more consistent with other types of documents, since we have already got a publish button in the IDE.

**Comment by jjallaire** [comment]
The IDE might have to be smarter about the workflow / requirements of
bookdown that it easily can be so the addin might be better. I'll take a
closer look tomorrow then we can discuss further.

**Comment by jjallaire** [comment]
Spent some time digging into this today:

1. For right now I think we should encourage all bookdown users to just
call the publish_book function for publishing. I'm not at all sure that it
even requires an addin as the function is setup to "do the right thing"
with no arguments. If you did want to do an addin it could take advantage
of the rsconnect::deployments function to show where the book is currently
deployed to (if anywhere), ask if they want to render first, etc. That said
I really think just the function is perfectly fine for now.

2. I was thinking about having the IDE hide the Publish button but then
realized that eventually the IDE is going to have to get smart about
bookdown (and other "aggregate" Rmd publishing formats) so that users can
publish source code to the server for dynamic/scheduled re-rendering. I
think aggregate Rmd formats will need some way to communicate to the IDE
that:

a. They should be published as an entire directory;

b. How they should be rendered on the server by RSC;

c. For a static publish which directory should be published; and

d. What the default name of the published asset should be.

Once we get all that working then RStudio should be able to do the
equivalent of publish_book should the user decide to work that way.
Hopefully we can get that done over the next couple of months.
