### ISSUE TITLE
No cover image generated when convert the "bookdown" book to `mobi`

### ISSUE THREAD

**Issue by psychelzh** [rstudio/bookdown#510]
This issue is about [the instruction book](https://bookdown.org/yihui/bookdown/).

I download the book as `.mobi` format for my kindle, but one exception happened: there is no cover image. See the following screenshot:

![screenshot_20180102-102353](https://user-images.githubusercontent.com/13306020/34472946-3b0af904-efa7-11e7-8931-c0f1d4c44d1e.png)

**Comment by yihui** [comment]
There is no native support for MOBI in bookdown. The MOBI version is converted from EPUB by Calibre, and personally I don't recommend that you read the MOBI version. In terms of quality, HTML and PDF > EPUB > MOBI.

**Comment by psychelzh** [comment]
Emmm, so I should stick to the html version now.

Thank you! In fact, I am trying to compose a `.mobi` book using `bookdown`. Hope it will work!

**Comment by yihui** [comment]
If you are able to figure out a solution, I'll be happy to take your pull request.

**Comment by psychelzh** [comment]
That will be nice. I would like to have a try.
