### ISSUE TITLE
Please add 'Field Guide to the R Ecosystem' to the homepage

### ISSUE THREAD

**Issue by sellorm** [rstudio/bookdown#511]
http://fg2re.sellorm.com

Many thanks,
Mark

**Comment by yihui** [comment]
You need to enable HTTPS before I can add it to the homepage. Thanks!

**Comment by yihui** [comment]
Hi @sellorm, I just want to make sure you saw my reply.

**Comment by yihui** [comment]
Added (but I still recommend HTTPS): https://bookdown.org/home/archive/

**Comment by sellorm** [comment]
So sorry, I did see it -- both your original note and the one from yesterday -- but the first time I got sidetracked and forgot and this time I'm on holiday!!!

Anyway, thanks for adding it - I've set up https as well now, and http gets bounced over to https too.

Apologies again and thanks for everything you do!

**Comment by yihui** [comment]
No worries. Thanks!
