### ISSUE TITLE
using `code` at end of title invalidates {-}

### ISSUE THREAD

**Issue by ajdamico** [rstudio/bookdown#513]
![subheading ending with backtick issue](https://user-images.githubusercontent.com/216807/34742401-153f325a-f554-11e7-878d-b83b23e027d9.png)

hi, i forked https://github.com/rstudio/bookdown-demo and added this text to 03-method.Rmd

	## no code in title {-}

	## `with` code at start of title {-}

	## with code at end of `title` {-}

	## with code in `middle` of title {-}

	
i think all four of those subheadings should _not_ be numbered, but (see screenshot) the 3rd one does get a number.  i think the behavior occurs when the line concludes with a backtick?

i checked in rmarkdown and didn't reproduce the behavior in a single sheet.  i checked with dev bookdown and got the same issue.

thanks for the fantastic software!

**Comment by yihui** [comment]
Duplicated of #96

**Comment by yihui** [comment]
Oh BTW, thanks for the report you mailed to me. I just received it last Friday, and I'm very proud of it!

**Comment by ajdamico** [comment]
it's so awesome what you have done with this software.  thanks again
