### ISSUE TITLE
Temporary .md files are not deleted

### ISSUE THREAD

**Issue by aoles** [rstudio/bookdown#519]
When rendering `bookdown::pdf_document2` to a non-default `output_dir` the intermediate `.knit.md` and `utf8.md` files are not cleaned up.

```r
writeLines(c(
  "---",
  "output: bookdown::pdf_document2",
  "---"
), "testfile.Rmd")

list.files(pattern="testfile.*")

## [1] "testfile.Rmd"

rmarkdown::render("testfile.Rmd", output_dir = tempdir())
list.files(pattern="testfile.*")

## [1] "testfile.knit.md" "testfile.Rmd"     "testfile.utf8.md"
```

**Comment by yihui** [comment]
Usually I don't recommend using `output_dir` or `output_file`. They are known to be (very) problematic, e.g. https://github.com/rstudio/rmarkdown/issues/587#issuecomment-168437646 https://github.com/rstudio/rmarkdown/issues/238 https://github.com/rstudio/rmarkdown/issues/348 https://github.com/rstudio/rmarkdown/issues/574 https://github.com/rstudio/rmarkdown/issues/1033 https://github.com/rstudio/rmarkdown/issues/861 etc. I believe the only reliable strategy is to render everything in the default output directory, and move the output files later.

**Comment by aoles** [comment]
Thanks @yihui for your prompt reply!

This issue is not limited to explicitly setting `output_dir` to `render`. In fact, I've run into it when knitting documents from the `vignettes` package source dir by using the "Knit" button in RStudio. For some reason the output file is then rendered to a temporary location leaving the `.knit.md` and `.utf8.md` files behind. Do you happen to know more about this feature? Just renaming the directory to anything else that doesn't match `^vignettes` restores the default behavior, i.e. creates `testfile.pdf` next to `testfile.Rmd` in the same dir (without any intermediate `.md` files).

```
processing file: testfile.Rmd
  |.................................................................| 100%
  ordinary text without R code

/usr/lib/rstudio/bin/pandoc/pandoc +RTS -K512m -RTS testfile.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output /tmp/RtmpMOUvdi/preview-c3f4afd5f9a.dir/testfile.tex --table-of-contents --toc-depth 2 --template /home/oles/R/R-devel/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --number-sections --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' --variable tables=yes --standalone 
output file: testfile.knit.md

Output created: /tmp/RtmpMOUvdi/preview-c3f4afd5f9a.dir/testfile.pdf
```

**Comment by yihui** [comment]
Sorry, but I don't have time to investigate this problem, but I acknowledge that we should at least fix the vignette issue, although I rarely knit vignettes this way.

**Comment by cderv** [comment]
Using the code in https://github.com/rstudio/bookdown/issues/519#issue-289988223 I can't reproduce. 

It seems the issue has been fixed since 2018. 

Please open a new issue if there is still problem with that.
