### ISSUE TITLE
Issues with bookdown gitbook Travis build

### ISSUE THREAD

**Issue by nate-d-olson** [rstudio/bookdown#52]
I recently setup a gh-pages hosted bookdown gitbook (https://github.com/nate-d-olson/mgmgnotes) and ran into a few issues, which I expected since the package is under active development. I was able to find work arounds for the issues and the Travis-CI build is working. Here is a list of the issues I ran into along with my work arounds.

* Documentation related
    * File numbering- section/ subsection and role of _bookdown.yml, it is unclear from the documentation how the file numbering and rmd list in _bookdown.yml determine chapters.   
    * The Travis build required a DESCRIPTION file, also needed to state devtools was a dependency for installing packages on github e.g. bookdown.  Travis build log with error https://travis-ci.org/nate-d-olson/mgmgnotes/builds/116715029

* Running scripts build and deploy scripts - needed to add the following to the .travis.yml due to a permissions issue. Not sure if it is better to define this in the `.travis.yml` or change permissions locally. Travis build log https://travis-ci.org/nate-d-olson/mgmgnotes/builds/116736240
```
before_script:
 - chmod +x ./_build.sh
 - chmod +x ./_deploy.sh
```
  
* Issues with `_deploy.sh` pushing to github (see build error message below ).  I fix the issue I added `git config --global user.email` and `git config --global user.name` to the deploy script.  I might have not set the GH_TOKEN up correctly though. Travis build log https://travis-ci.org/nate-d-olson/mgmgnotes/builds/116739556
```
$ ./_deploy.sh
Cloning into 'book-output'...
remote: Counting objects: 175, done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 175 (delta 62), reused 152 (delta 44), pack-reused 0
Receiving objects: 100% (175/175), 457.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (62/62), done.
Checking connectivity... done.
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <travis@testing-worker-linux-docker-18f5f0e1-3374-linux-14.prod.travis-ci.org>) not allowed
```

**Comment by yihui** [comment]
Thanks for the feedback! I'll update the documentation. Actually a much easier publishing service will be made available in the near future. You can take a look at the publish_book() function, and I'll document it once the service is mature.
