### ISSUE TITLE
Text references don't work with word_document2()

### ISSUE THREAD

**Issue by brunogrande** [rstudio/bookdown#521]
The issue has changed as I prepared to write this with a reproducible example. As of now, it seems like text reference altogether do not word with `word_document2()`. At first, it just seemed like it was multi-line text references, but I can't get them to work anymore. I also tried using the latest GitHub version (38efc824b23a53c792a68a7e410cd3975faca47d), but to no avail. 

### RMarkdown Document

````r
---
output: 
  bookdown::word_document2:
    toc: no
  bookdown::gitbook:
    split_by: "none"
    self_contained: yes
---

# Example 1

This is a test text (Figure \@ref(fig:test-figure)).


(ref:caption-test-figure) This is a test caption. 

```{r test-figure, fig.cap="(ref:caption-test-figure)", fig.height=2}
plot(rnorm(100))
```



# Example 2

This is a test text (Figure \@ref(fig:test-figure-two)).


(ref:caption-test-figure-two)
This is a test caption. 

```{r test-figure-two, fig.cap="(ref:caption-test-figure-two)", fig.height=2}
plot(rnorm(100))
```



# Example 3

This is a test text (Figure \@ref(fig:test-figure-three)).


(ref:caption-test-figure-three) This is a test caption. 
This is a second sentence for the caption.

```{r test-figure-three, fig.cap="(ref:caption-test-figure-three)", fig.height=2}
plot(rnorm(100))
```
````

### Output Word Document

None of the captions in Word are formatted properly. 

[test.docx](https://github.com/rstudio/bookdown/files/1654244/test.docx)

<img width="1147" alt="test docx" src="https://user-images.githubusercontent.com/740725/35254694-330a543a-ffa0-11e7-8093-ab04fe7a5bc5.png">

### Output GitBook HTML Document

In the GitBook HTML document, all three captions are formatted properly. The HTML document is gzipped so I can upload it to GitHub. 

[test.html.gz](https://github.com/rstudio/bookdown/files/1654245/test.html.gz)

<img width="679" alt="test html" src="https://user-images.githubusercontent.com/740725/35254697-3b9fcaa8-ffa0-11e7-92eb-8a7f3845e150.png">

## Additional Information

```r
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
```

```r
> devtools::session_info("bookdown")
Session info ------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       <NA>                        
 date     2018-01-23                  

Packages ----------------------------------------------------------------------------------------
 package   * version date       source         
 backports   1.1.2   2017-12-13 cran (@1.1.2)  
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0) 
 bookdown    0.5     2017-08-20 CRAN (R 3.4.1) 
 digest      0.6.13  2017-12-14 cran (@0.6.13) 
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1) 
 graphics  * 3.4.2   2017-10-04 local          
 grDevices * 3.4.2   2017-10-04 local          
 highr       0.6     2016-05-09 CRAN (R 3.4.0) 
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0) 
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0) 
 knitr       1.18    2017-12-27 CRAN (R 3.4.3) 
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0) 
 markdown    0.8     2017-04-20 CRAN (R 3.4.0) 
 methods   * 3.4.2   2017-10-04 local          
 mime        0.5     2016-07-07 CRAN (R 3.4.0) 
 Rcpp        0.12.13 2017-09-28 cran (@0.12.13)
 rmarkdown   1.8     2017-11-17 CRAN (R 3.4.2) 
 rprojroot   1.3-2   2018-01-03 cran (@1.3-2)  
 stats     * 3.4.2   2017-10-04 local          
 stringi     1.1.6   2017-11-17 cran (@1.1.6)  
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0) 
 tools       3.4.2   2017-10-04 local          
 utils     * 3.4.2   2017-10-04 local          
 yaml        2.1.16  2017-12-12 cran (@2.1.16) 
Warning message:
In as.POSIXlt.POSIXct(Sys.time()) :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/America/Vancouver'
```

**Comment by yihui** [comment]
For text references, you should not end the paragraph with spaces, or wrap the paragraph. I just clarified it in the doc (2.2.4): https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html Thanks for the report!

**Comment by clopezmorales** [comment]
Many thanks Yihui for your great work and the dedication to respond to questions. I am learning a lot from your books and comments. I intend to use bookdown for an academic book I will write in months to come. However, I need a Word output to collaborate with my publisher. 

I am having the same issue brunogrande exposed here. I understand your response and the reference made to 2.2.4 in the book. 

Lets reference to the example in 2.2.4. 

Lets say you want to reference the figure "foo" elsewhere in the text. Then you would need \@ref(fig:foo). This works perfectly with gitbook, but when producing a word output then none of it works. 

This is my case (as I'm learning and testing, I am using your book demo Rmds to make these testsl and taking screenshots. Sorry if it is not as straightforward... I'm kind of new to this):

Screenshot of code in R: 
![image](https://user-images.githubusercontent.com/25908935/44188585-f5672c80-a0e3-11e8-8711-bfea29c82f3f.png)

Screenshot of beautiful and nice result in html. All works here:
![image](https://user-images.githubusercontent.com/25908935/44188653-5abb1d80-a0e4-11e8-8a5d-e0262afdb07a.png)

Screenshot of result in MS Word. Note the labels are not carried on, nor the caption to the Figure nor its ordered numbering.
![image](https://user-images.githubusercontent.com/25908935/44188666-6b6b9380-a0e4-11e8-9dc1-6ee57bef405a.png)

I assure I have no extra spaces nor wrapping of paragraphs in the code.

I wonder if you can provide advice and guidance as to how to fix this for MS Word to include the references to the labels. I understand MS Word features are not supported from pandoc. Is this one of them?

**Comment by mschilli87** [comment]
@clopezmorales: I would suggest you post questions like this at stackoverflow where you have many more potential readers (and answerers) than here. If you do, please link the question here.
