### ISSUE TITLE
Overflowing text in PDF

### ISSUE THREAD

**Issue by aetiologicCanada** [rstudio/bookdown#527]
In Section 1.5 of the book you offer guidance that for PDF documents "... text may overflow into the page margin,... Do not try to make things look right immediately". 

OK, so I am now at the end of the writing of a long document using pdf_book and the text is still overflowing the margin. I am now using tinytex, Windows, and github current rmarkdown, and up to date R and libraries. 

What is unclear to me is what I should do now that I really need to finish up, to stop the text overflow.  The content has lots of in-line code, but is otherwise unremarkable.

Thank you for a lovely package.

**Comment by yihui** [comment]
Is it possible to show a screenshot?

**Comment by aetiologicCanada** [comment]
By email.. Stand by. About 1 page of text and graphics are missing.

**Comment by yihui** [comment]
Email attachments won't work for Github issues.

**Comment by aetiologicCanada** [comment]
I no longer have access to the recalcitrant code. As I recall, bookdown
had strong preferences for  having a blank line after an Rchunk.

**Comment by yihui** [comment]
Okay. Please let me know when you have a reproducible example and a screenshot.
