### ISSUE TITLE
unnamed.chunk.set not used

### ISSUE THREAD

**Issue by dmenne** [rstudio/bookdown#529]
Version: 0.6.2, from github as of today. Windows 10, Rstudio

- Use your standard bookdown-demo-master
- in 01-intro, add opts_knit$set, and remove chunk name from the next figure

``` 
   ```{r, cache = FALSE}
    knitr::opts_knit$set(unnamed.chunk.label = "fig")
    ```

    ```{r, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center'}
    par(mar = c(4, 4, .1, .1))
    plot(pressure, type = 'b', pch = 19)
    ```
```
- Build. Image is `unnamed-chunk-4-1.png`

**Comment by cderv** [comment]
This is not an issue with **bookdown**. This type of option ([Package option](https://yihui.org/knitr/options/#package-options) must be set before any knitting happen I believe and not inside a document. 

Example: `test.Rmd` 
````r
---
title: "A Book"
author: "Frida Gomam"
output: 
  html_document:
    self_contained: false
---

```{r, cache = FALSE}
knitr::opts_knit$set(unnamed.chunk.label = "fig")
```

```{r, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center'}
par(mar = c(4, 4, .1, .1))
plot(pressure, type = 'b', pch = 19)
```
````

* `rmarkdown::render("test.Rmd")` will not do what you expect
* but setting this option before rendering will work `knitr::opts_knit$set(unnamed.chunk.label = "fig"); rmarkdown::render("test.Rmd")`.

This kind of knitr option can also be set using R options. See `?knitr::opts_knit`

Hope it helps for your use case, and thank you for your patience with this opened issue.

**Comment by cderv** [comment]
See also about this and why in https://github.com/yihui/knitr/issues/1926#issuecomment-776299026
