### ISSUE TITLE
Please update Broadening Your Statistical Horizons in the list of books on the homepage

### ISSUE THREAD

**Issue by proback** [rstudio/bookdown#532]
Currently there is a listing for "Broadening Your Statistical Horizons" by Legler and Roback which links to the account of a student who had been working on this project: https://bookdown.org/wall1/bookdown-bysh/.  She is no longer working on the project and has tried to de-activate this link but could not figure out how.  The updated version should be called "Broadening Your Statistical Horizons: Generalized Linear Models and Multilevel Models" by Legler and Roback; it's located at https://bookdown.org/roback/bookdown-bysh/.  If this is something we can do ourselves, please just let me know - we're new to the bookdown world (but loving it)

**Comment by yihui** [comment]
Sorry about the delay. I'll definitely update it the next time I update the homepage. Unfortunately it is quite painful to update it at the moment, and I have been thinking of revamping the homepage: https://community.rstudio.com/t/4744 When the new website is done, this book will be automatically updated.

**Comment by yihui** [comment]
It has been updated: https://bookdown.org/home/archive/ Thanks!
