### ISSUE TITLE
sitemap.xml parsing for homepage breaks with new xml2 version

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#533]
@yihui  I began looking on how the homepage work in order to see how to revamp it. 

While testing, I saw that new xml2 version has a [breaking change](https://github.com/r-lib/xml2/blob/master/NEWS.md#breaking-changes) that impacts `sitemap.R`

* it needs now `xmldoc = as_list(read_xml(xml))[[1]]`. 

I open this issue to track  this kind of discovery and what to do.  If you prefer I do not use bookdown issue, please tell me. A gist as todo could also work.

**Comment by yihui** [comment]
Thanks @cderv! Please feel free to use bookdown issues to track problems you discover.

**Comment by cderv** [comment]
Dealt in new bookdown.org repo.
