### ISSUE TITLE
bookdown and png image fails

### ISSUE THREAD

**Issue by FelixErnst** [rstudio/bookdown#534]
Hi have a look here: https://github.com/Bioconductor/BiocStyle/issues/42

There seems to be an issue with bookdown and referenced images. The debugging output is contained in this issue already.

**Comment by yihui** [comment]
Could you provide such an example that I can just open and compile it? I downloaded your zip examples but didn't find the image or Rmd.

**Comment by FelixErnst** [comment]
Sure. it is mentioned in the comments of the linked issue, but for clarity:
```
---
title: "test"
author: "xyz"
output: 
  bookdown::pdf_document2
---
![](image.png)
```

This does not work on Windows 10 64 bit 16299.214 / RStudio 1.1.423 / R 3.4.3, but works on Ubuntu 17.10 / RStudio 1.1.423 / R-devel. Error message: `! Package pdftex.def Error: File `image.png' not found: using draft setting.`

```
---
title: "test"
author: "xyz"
output: 
  pdf_document
---
![](image.png)
```
This works in both cases.

**Comment by yihui** [comment]
Okay, let me show you what I meant by "an example that I can just open and compile": [test.zip](https://github.com/rstudio/bookdown/files/1721151/test.zip) (you didn't provide `image.png`, which means I'll have to spend time on finding an image for testing).

Anyway, I cannot reproduce the issue on macOS with the example I provided above. I suspect there is something wrong with your LaTeX distribution. I recommend you to remove MiKTeX (is that what you installed on Windows?) and try TinyTeX: https://yihui.name/tinytex/

BTW, looking at your testing environments:

doesn't work: Windows 10 64 bit 16299.214 / RStudio 1.1.423 / R 3.4.3
works: Ubuntu 17.10 / RStudio 1.1.423 / R-devel

it is hard to tell who is the culprit, because you are comparing Windows with Ubuntu, and R 3.4.3 with R-devel at the same time. There is no way to tell if the failure was due to Windows or R 3.4.3.

**Comment by FelixErnst** [comment]
[bookdown.zip](https://github.com/rstudio/bookdown/files/1721211/bookdown.zip)

Regarding the Latex distro not being ok: I can rule that out, since pdf_document works, can't I? That means MiKTeX works. The problem does not occur with R 3.4.3 under Ubuntu 17.10, so I guess it is Windows specific problem of bookdown, isn't it?

Since you suggested it, I tested it with TinyTex. The result is as follows:
- pdf is created
- BiocStyle does not result in a pdf with expected format. It is rather the same pdf, which is also produced by bookdown::pdf_document2. The "Contents" part is displayed. This is independent of the image being included or not.

Using bookdown::pdf_document2 or BiocStyle::pdf_document the following error is reported in the rmarkdown output every time I try to create the pdf:
```
tlmgr search --file --global "/ecrm1000[.](tfm|afm|mf|otf)"
Trying to automatically install missing LaTeX packages...
tlmgr install ec
tlmgr.pl: package repository http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl install: package already present: ec
tlmgr search --file --global "/ecrm1000[.](tfm|afm|mf|otf)"

Output created: test.pdf
Warning messages:
1: running command '"pdflatex" -halt-on-error -interaction=batchmode "test.tex"' had status 1 
2: running command '"pdflatex" -halt-on-error -interaction=batchmode "test.tex"' had status 1 
```

So I have the options of using 
1. MiKTeX and no png pictures. The output is correct and well formated. 
2. Switch to Linux
3. Use TinyTeX and png pictures, but not having the option of BiocStyle formating. In addition when using bookdown or BiocStyle warnings are generated and run time is long due to trying to download some files.
4. Not using bookdown/BiocStyle

So my threshold of discomfort is somewhere between 2. and 3. 

Nonetheless, it does mean, that there is at least a windows specific bookdown issue, am I wrong? (Or a TinyTeX issue about some missing files?)

**Comment by aoles** [comment]
My 2 cents:

Ad.1: Even though the following is not a solution to the observed problem, it might still be useful as a workaround: try including the picture through a code chunk calling `knitr::include_graphics`.

Ad. 3: In case there is something funky going on with file paths, you might want experiment with setting the argument `relative_path = TRUE` to `BiocStyle::pdf_document`.

**Comment by FelixErnst** [comment]
So as @aoles suggested in the BiocStyle issue, I was tripped up by the pdf generated once and any additional run not failing due to cache files being present. 

I am sorry for that.

Using TinyTeX and bookdown it works as intended without any error or warning. Using TinyTeX and BiocStyle it fails, with a similiar error as given above independent on the image being present or not in the Rmd file on Windows only.
