### ISSUE TITLE
Splitting by subsubsection

### ISSUE THREAD

**Issue by opencuny** [rstudio/bookdown#535]
Hi Rstudio team! 

I have a book hosted at https://bookdown.org/open/qcstats whose GitHub repo is https://GitHub.com/opencuny/qc-stats which I am attempting to split by subsection rather than section or section+number, as for example [this section](https://bookdown.org/open/qcstats/4-4-lecture-4-namespaces-and-libraries.html) is very long to scroll through, so I would like each third level heading to be on a separate page. I looked around about how to use gitbooks like this on StackExchange but didn't have much luck. Is there a way to do this?

Thank you!

**Comment by yihui** [comment]
Sorry, but no.

**Comment by opencuny** [comment]
Ah I see. This will work out for now! Though I figure there is a way to sort of split up the workflow into different Rmd files using a script?
