### ISSUE TITLE
Fail to compile pdf (Rstudio server)

### ISSUE THREAD

**Issue by snsansom** [rstudio/bookdown#536]
with
Rstudio server 1.1.383
devtools latest rmarkdown, bookdown
uptodate texlive
(running on a centos server)

1. Start new project, new directory, new book project, directory name "test"
2. Build pdf (build book -> bookdown::pdf_book)

#########

==> rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8')

processing file: test.Rmd
  |.......                                                          |  11%
   inline R code fragments

  |..............                                                   |  22%
label: unnamed-chunk-1 (with options) 
List of 1
 $ eval: logi FALSE

  |......................                                           |  33%
  ordinary text without R code

  |.............................                                    |  44%
label: unnamed-chunk-2 (with options) 
List of 1
 $ include: logi FALSE

  |....................................                             |  56%
  ordinary text without R code

  |...........................................                      |  67%
label: nice-fig (with options) 
List of 4
 $ fig.cap  : chr "Here is a nice figure!"
 $ out.width: chr "80%"
 $ fig.asp  : num 0.75
 $ fig.align: chr "center"

  |...................................................              |  78%
  ordinary text without R code

  |..........................................................       |  89%
label: nice-tab (with options) 
List of 1
 $ tidy: logi FALSE

  |.................................................................| 100%
   inline R code fragments

output file: test.knit.md

/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS test.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.tex --table-of-contents --toc-depth 2 --template /gfs/apps/apps/R-3.4.2/lib64/R/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --number-sections --highlight-style tango --latex-engine xelatex --natbib --include-in-header preamble.tex --variable graphics=yes --variable 'geometry:margin=1in' --variable tables=yes --standalone 
**Error: Failed to compile test.tex.**
Execution halted

Exited with status 1.

####################

**But if the test.tex file is copied to the _bookdown_files, and xelatex test.tex is run on the command line, compile is successful...**

**Comment by yihui** [comment]
Could you `devtools::install_github('yihui/tinytex')`, set `options(tinytex.verbose = TRUE)` in any code chunk in your index.Rmd, and rebuild the book? It should show the full error message, without which it will be hard to diagnose the problem.

**Comment by snsansom** [comment]
Brilliant, many thanks - revealed that xelatex is simply not on PATH within rstudio-server. 

As we have texlive installed as a bash environment module I can successfully work around with https://github.com/larsgr/RLinuxModules for now. 

Would be interested to know if there is a recommended way to evaluate environment modules site-wide when rstudio-server is launched.

**Comment by yihui** [comment]
Great. I'm not really familiar with Linux modules, so I cannot answer your last question.

BTW, if you use TinyTeX, it won't require PATH if you follow the default installation: https://yihui.name/tinytex/

**Comment by judytlewis** [comment]
I have updated packages and installed tinytex following the "For R Users" instructions and am no longer able to generate pdf reports from Shiny/Rmarkdown. The error I receive is: 

output file: reportPDF.knit.md

"C:/Users/xxxx/AppData/Local/Pandoc/pandoc" +RTS -K512m -RTS reportPDF.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output pandoc14c4607f6f65.tex --template "C:\Users\xxxx\Documents\R\win-library\3.4\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" 
Warning: running command '"pdflatex" -halt-on-error -interaction=batchmode "file14c46f9370ef.tex"' had status 1
Warning: Error in : Failed to compile file14c46f9370ef.tex.
Stack trace (innermost first):
    58: show_latex_error
    57: on_error
    56: system2_quiet
    55: run_engine
    54: latexmk_emu
    53: tinytex::latexmk
    52: latexmk
    51: rmarkdown::render
    50: download$func [C:\Users\xxxx\Documents\testRMD\TestRMD/app.R#29]
     1: runApp
Error : Failed to compile file14c46f9370ef.tex.

**Comment by yihui** [comment]
@judytlewis Did you set the option `options(tinytex.verbose = TRUE)` in your R Markdown document? If you did, there should be more error messages in your console. And did you restart RStudio after installing TinyTeX? What does `Sys.which('pdflatex')` return?

**Comment by judytlewis** [comment]
Thank you so much, Yihui. I added options(tinytex.verbose = TRUE) in my Rmarkdown document and then it did successfully knit and download the document, although with warnings:

Warning: running command '"pdflatex" -halt-on-error -interaction=batchmode "file14c4992311c.tex"' had status 1
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6350 64-bit)
entering extended mode
Warning: running command '"pdflatex" -halt-on-error -interaction=batchmode "file14c4992311c.tex"' had status 1
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6350 64-bit)
entering extended mode

And Sys.which("pdflatex") returned: 
                                                  pdflatex 
"C:\\PROGRA~1\\MIKTEX~1.9\\miktex\\bin\\x64\\pdflatex.exe"

**Comment by yihui** [comment]
So you didn't uninstall MiKTeX, and TinyTeX was not actually used in this case. You don't have to remove MiKTeX -- you can temporarily rename the folder and it should fall back on TinyTeX.

**Comment by judytlewis** [comment]
Thank you SO much for your help! Thank you also for the book recommendations at Rstudio::conf!

**Comment by yihui** [comment]
My great pleasure!

**Comment by mainakerbrat** [comment]
Thank you so much ! I had exactly the same issue this week ! And it works now :+1:

**Comment by liweitang** [comment]
I encounter the same problem,and I cannot deal with it after all those ways provided; it cannot generate pdf  file. In addition, I have another problem:
Error in yaml::yaml.load(string, ...) : 
  Scanner error: mapping values are not allowed in this context at line 2, column 7
Error in yaml::yaml.load(string, ...) : 
  Scanner error: while scanning a simple key at line 4, column 3 could not find expected ':' at line 5, column 1

**Comment by Gurashish** [comment]
I also have same error although I have successfully installed Miketex on my linux server.Also I have installed tinytex

**Comment by CriscelyLP** [comment]
I deal a lot with this problem!
For Fedora users, installing the` latexextra` package solved my the problem.
`sudo dnf install texlive-collection-latexextra`

Good luck!

**Comment by yvestch** [comment]
I had a similar issue as I wasn't able to knit pdf files & solved it by installing & running tinitex packages using those commands in the console -- not the terminal

> install.packages("tinytex")
> tinytex::install_tinytex()
