### ISSUE TITLE
Generating PDFs during a Shiny Server session

### ISSUE THREAD

**Issue by BK365** [rstudio/bookdown#540]
I have a dashboard app on a shiny server where the user can select an individual and then generate a PDF containing their fiscal year information via bookdown.  This works perfectly fine locally, but on the server it fails.

Can anyone diagnose why it wouldn't work, or suggest a different way that would work?

>Session info 
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-02-26                  

>Packages 
 package   * version date       source        
 backports   1.1.1   2017-09-25 CRAN (R 3.4.2)
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)
 bitops      1.0-6   2013-08-17 CRAN (R 3.4.0)
 bookdown  * 0.5     2017-08-20 CRAN (R 3.4.1)
 caTools     1.17.1  2014-09-10 CRAN (R 3.4.0)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)
 graphics  * 3.4.2   2017-10-04 local         
 grDevices * 3.4.2   2017-10-04 local         
 highr       0.6     2016-05-09 CRAN (R 3.4.0)
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)
 knitr     * 1.17    2017-08-10 CRAN (R 3.4.1)
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)
 markdown    0.8     2017-04-20 CRAN (R 3.4.0)
 methods   * 3.4.2   2017-10-04 local         
 mime        0.5     2016-07-07 CRAN (R 3.4.0)
 Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)
 rmarkdown   1.6     2017-06-15 CRAN (R 3.4.0)
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)
 stats     * 3.4.2   2017-10-04 local         
 stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)
 tools       3.4.2   2017-10-04 local         
 utils     * 3.4.2   2017-10-04 local         
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)

> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’

> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.29; using libpng 1.6.29
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 3.04

```{r}
output$downloadreport <- downloadHandler(

      filename = function() {
     paste(toString(input$PI), " Report", ".pdf", sep="")
   },
      content = function(file) {
        fname <- paste(file,"pdf",sep=".")
       
        bookdownreport <- "index.Rmd"
          
        # Set up parameters to pass to Rmd document
        params <- list(CurrentAwards  = selectedDataAwards(), MPIAwards = selectedDataAwardsMPI(), PPGAwards = selectedDataAwardsPPG(), UnpaidAwards = selectedDataAwardsUnpaid(), PI=toString(input$PI), CoiAwards = selectedDataAwardsCoi(), SalRec = selectedDataSal(), Teaching = selectedDataTeach(), ProposalsPI = selectedDataProp(), ProposalsCoi= selectedDataPropCoi(), PI.demographics = selectedDemographics())
        
 bookdown::render_book(bookdownreport,output_format="pdf_document",output_file=fname,params=params,envir = new.env(parent = globalenv()))
     
        file.copy(fname,file)
        if (file.exists(file.path("_main.Rmd"))) file.remove(file.path("_main.Rmd"))
      }
      
    )
downloadLink("downloadreport", label="Generate PI Report (PDF)")
```

**Comment by yihui** [comment]
It is hard to tell without the log.

**Comment by BK365** [comment]
GNU nano 2.5.3                            File: /var/log/shiny-server/Faculty-App-shiny-20180227-131110-35599.log                                                                

  Expecting logical in BI8024 / R8024C61: got 'ADV-EXT'
Warning in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  :
  Expecting logical in BH8586 / R8586C60: got 'FEE WAIVER: YES'
Warning in read_fun(path = path, sheet = sheet, limits = limits, shim = shim,  :
  Expecting logical in BI9532 / R9532C61: got 'ADV-EXT'
Warning: replacing previous import by 'shiny::validateCssUnit' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::br' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tags' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::div' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h1' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h2' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h3' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h4' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h5' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h6' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::knit_print.html' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagSetChildren' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeScript' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::em' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagAppendChild' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::is.singleton' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeHTML' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeMarkdown' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::code' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagList' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::a' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagAppendAttributes' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::singleton' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::hr' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::p' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::suppressDependencies' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagAppendChildren' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeText' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::pre' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::span' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::withTags' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::htmlTemplate' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::img' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tag' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeCSS' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::knit_print.shiny.tag' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::knit_print.shiny.tag.list' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::strong' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::HTML' when loading 'crosstalk'
output file: /tmp/RtmpTlJXTO/FacultyDashboardApp.knit.md


Output created: /tmp/RtmpTlJXTO/file13ba4b3b1ecb.html
Warning in dir.create(path, recursive = TRUE) :
  cannot create dir '_book', reason 'Permission denied'
Warning in file(con, "w") :
  cannot open file '_main.Rmd': Permission denied
Warning: Error in file: cannot open the connection
Stack trace (innermost first):
    58: file
    57: writeLines
    56: write_utf8
    55: merge_chapters
    54: render_cur_session
    53: bookdown::render_book
    52: download$func [<text>#32]
     3: <Anonymous>
     2: do.call
     1: rmarkdown::run
Error : cannot open the connection

**Comment by yihui** [comment]
So it is a user permission issue:

> cannot create dir '_book', reason 'Permission denied'

The R process cannot create dirs or files under the directory of the Shiny app.

I'm not very familiar with Shiny Server, but one thing you could do is to copy the whole book project to the `tempdir()`, render the book there, and let users download the PDF from there.

**Comment by BK365** [comment]
Warning: replacing previous import by 'shiny::HTML' when loading 'crosstalk'
output file: /tmp/RtmpitCzDk/FacultyDashboardApp.knit.md


Output created: /tmp/RtmpitCzDk/file5ad42a6e1b53.html



processing file: FacultyDashboardApp.Rmd
output file: /tmp/RtmpitCzDk/FacultyDashboardApp.knit.md


Output created: /tmp/RtmpitCzDk/file5ad465aaee69.html



processing file: FacultyDashboardApp.Rmd
output file: /tmp/RtmpitCzDk/FacultyDashboardApp.knit.md


Output created: /tmp/RtmpitCzDk/file5ad44e81c370.html
Warning in dir.create(path, recursive = TRUE) :
  cannot create dir '_book', reason 'Permission denied'
Warning in file(con, "w") :
  cannot open file '_main.Rmd': Permission denied
Warning: Error in file: cannot open the connection
Stack trace (innermost first):
    58: file
    57: writeLines
    56: write_utf8
    55: merge_chapters
    54: render_cur_session
    53: bookdown::render_book
    52: download$func [<text>#32]
     3: <Anonymous>
     2: do.call
     1: rmarkdown::run
Error : cannot open the connection

Execution halted
Warning message:
In rm(list = as.character(handle), pos = .wsconns) :
  object '108268480' not found

**Comment by BK365** [comment]
It looks like despite the fact my server administrator has given total permission to shiny, it still cannot create a folder within the app directory.  We are attempting to rebuild the server so that the client is the user instead of Shiny being the user to see if that will make a difference. 

Also, it seems like `render_book()` will always create a _book folder in the main directory even if I set every option to be `tempdir()`.

```
out <- bookdown::render_book(bookdownreport,output_format="pdf_document",output_file=fname,knit_root_dir=tempdir(),intermediates_dir=tempdir(),output_dir = tempdir(),params=params,envir = new.env(parent = globalenv()))
        file.copy(out,fname)
        file.copy(fname,file)
```

That is the code my app uses, and yet from the callstack you can see it still attempts to create _book.

**Comment by yihui** [comment]
`knit_root_dir` does not work with `render_book()`. 

The only way at the moment is as I said above: copy all source documents to the `tempdir()` and render the book there.

In theory, if you have write permission to the app directory, it should be fine. I don't know why `render_book()` fails to create the `_book` directory.
