### ISSUE TITLE
Markdown syntax figures not appearing in list of figures

### ISSUE THREAD

**Issue by wuffi** [rstudio/bookdown#542]
Figures included with `knitr::include_graphics()` inside an R code chunk appear in the list of figures, but
figures included with the markdown syntax `![caption](images/img1.png)` to my experience don't.
Since one can always use the call to knitr, this is actually not a very urgent issue. If others can replicate this for me unexpected behaviour, it might be worth mentioning it in the documentation.

**Comment by mikey-harper** [comment]
I haven't been able to reproduce your error. Here is a minimal example which makes a graphic then tries to load it in with the two techniques:

    ---
    output: 
    pdf_document
    lof: true
    ---

    ```{r include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)

    jpeg("test.jpg")
    plot(pressure)
    dev.off()
    ```

    ![alt text](test.jpg)

    ```{r pressure, fig.cap = "caption", out.width = "60%"}
    knitr::include_graphics("test.jpg")
    ```

![image](https://user-images.githubusercontent.com/20046224/36970906-035303e4-2062-11e8-87d3-d11c4adf320f.png)

However, I would always use `include_graphics()` as it adds more functionality to allow control of the figure dimensions, improved cross-referencing etc. As far as I can tell this is explained in the bookdown documentation here: https://bookdown.org/yihui/bookdown/figures.html

> "Sometimes you may have certain images that are not generated from R code, and you can include them in R Markdown via the function knitr::include_graphics()."

It goes on to list many of the benefits, one of which being that you can set chunk options.

**Comment by wuffi** [comment]
Wow, thanks a lot for the quick reply. The minimal example also works well for me.
I think the problem is rather due to a mistake of mine.
Therefore, I would close the issue. Thanks a lot for your help!

**Comment by yihui** [comment]
Thanks a lot for the help, @mikey-harper!
