### ISSUE TITLE
R markdown does not create pdf file

### ISSUE THREAD

**Issue by bdeepthi** [rstudio/bookdown#546]
Hi,

When I try to knit the vanilla example Rmd file to "pdf" I get the below error. I tried re-installing the packages and restarting the R session several time but it dint help.

Output created: test.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'test.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning messages:
1: running command '"pdflatex" -halt-on-error -interaction=batchmode "test.tex"' had status 1 
2: In readLines(logfile) : incomplete final line found on 'test.log'
Execution halted

**Comment by caggtaagtat** [comment]
Where?
