### ISSUE TITLE
chapters are sections in pdf document

### ISSUE THREAD

**Issue by topepo** [rstudio/bookdown#547]
[originally on SO](https://stackoverflow.com/questions/49198680/bookdown-converting-chapters-to-sections)

I have a book that compiles fine to html but the pdf version has no chapters. For example, the command

    # Introduction {#intro-intro}

is translated to 

    \hypertarget{intro-intro}{%
    \section{Introduction}\label{intro-intro}}

(No such issues with the gitbook format)

Test repo is [here](https://github.com/topepo/bookdown-section-issue)

```> session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 os       macOS High Sierra 10.13.3   
 system   x86_64, darwin15.6.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-03-11                  

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version date       source                            
 backports     1.1.2   2017-12-13 CRAN (R 3.4.3)                    
 bookdown    * 0.7.1   2018-03-12 Github (rstudio/bookdown@06bd619) 
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.4.0)                    
 digest        0.6.15  2018-01-28 cran (@0.6.15)                    
 evaluate      0.10.1  2017-06-24 CRAN (R 3.4.1)                    
 htmltools     0.3.6   2017-04-28 CRAN (R 3.4.0)                    
 knitr         1.20    2018-02-20 CRAN (R 3.4.3)                    
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)                    
 Rcpp          0.12.15 2018-01-20 cran (@0.12.15)                   
 rmarkdown     1.9.3   2018-03-12 Github (rstudio/rmarkdown@e67c789)
 rprojroot     1.3-2   2018-01-03 cran (@1.3-2)                     
 rstudioapi    0.7     2017-09-07 CRAN (R 3.4.1)                    
 sessioninfo * 1.0.0   2017-06-21 CRAN (R 3.4.1)                    
 stringi       1.1.6   2017-11-17 CRAN (R 3.4.2)                    
 stringr       1.3.0   2018-02-19 CRAN (R 3.4.3)                    
 tinytex       0.4     2018-03-08 cran (@0.4)                       
 withr         2.1.1   2017-12-19 CRAN (R 3.4.3)                    
 xfun          0.1     2018-01-22 cran (@0.1)                       
 yaml          2.1.18  2018-03-08 cran (@2.1.18)
```

     > system('pdflatex --version')
     pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
     kpathsea version 6.2.3
     Copyright 2017 Han The Thanh (pdfTeX) et al.
     There is NO warranty.  Redistribution of this software is
     covered by the terms of both the pdfTeX copyright and
     the Lesser GNU General Public License.
     For more information about these matters, see the file
     named COPYING and the pdfTeX source.
     Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
     Compiled with libpng 1.6.29; using libpng 1.6.29
     Compiled with zlib 1.2.11; using zlib 1.2.11
     Compiled with xpdf version 3.04     

     pandoc  2.0.5

**Comment by topepo** [comment]
@hadley suggested that the problem was related to using the `krantz` document class (as oppsed to `book`). I [updated that](https://github.com/topepo/bookdown-section-issue/commit/198745cdc27b99ddd2fda16af04c50d20cc0d499) but now it seems that the chapter header

```
# Seven Nation Army {#intro-intro}
```
is causing an error
```
Runaway argument?
{Seven Nation Army}]{Seven Nation Army}\label {intro-intro}\fi  
! Paragraph ended before \NR@chapter was complete.
<to be read again> 
```

[(log file)](https://github.com/topepo/bookdown-section-issue/blob/198745cdc27b99ddd2fda16af04c50d20cc0d499/feature_art.log)

**Comment by yihui** [comment]
I saw your question last night (still open in my browser), but I had been sick, so I didn't answer it. Just typed a quick answer there.

**Comment by topepo** [comment]
Thanks and I hope that you are feeling better. 

Any idea about the error above (after adding `--top-level-division=chapter`)?

**Comment by yihui** [comment]
Not quite sure, but you may try to add one more pandoc argument `--wrap=none` to `pandoc_args`.

**Comment by topepo** [comment]
No, that didn't help (plus I detest forced wrapping). 

I'll try to figure it out and post here if/when I do. 

Thanks

**Comment by yihui** [comment]
I'll look into it tomorrow.

**Comment by yihui** [comment]
After trial and error, I found out the culprit:

```tex
\usepackage{algorithm2e}
```

This package seems to be incompatible with the krantz class. You have to reach out to the help desk of CRC (or give up this package). Here is the minimal repro:

```tex
\documentclass{krantz}
\usepackage{algorithm2e}
\begin{document}
\chapter{a}
\end{document}
```

`pdflatex` fails on it (and succeeds without `algorithm2e`).

**Comment by topepo** [comment]
Thanks! I'll send them a note.
