### ISSUE TITLE
Feature to use gitbook plugins

### ISSUE THREAD

**Issue by therimalaya** [rstudio/bookdown#549]
Is there any chance that we can use gitbook plugins in bookdown gitbook output?  It will give a way to implement some interaction such as making quiz and exercises or adding a comment feature on the content. I don't know how difficult is it to implement, it will be a useful addition to bookdown.

**Comment by psychelzh** [comment]
It would really be helpful if plugins are supported. Here I am writing books with Chinese, but the default search engine for `gitbook` does not support Chinese. So I need a plugin to do this job. Hopefully plugins will be supported.

**Comment by cderv** [comment]
Unfortunatly, I don't think plugins still exist for gitbook format. Gitbook has become a platform, with cloud based solution only and old documentation has a dead link for plugins page: https://gitbookio.gitbooks.io/documentation/content/format/plugins.html

The new V2 format is not an open format as the one before, and plugins has been replaced by implemented feature: https://docs.gitbook.com/resources/gitbook-legacy/v2-differences#plugins)

This means that new features you need in **bookdown** needs to be added directly in the R package and its format.

Considering this, I'll close this issue. Please reopen if I missed something, and also open new feature request for what is missing for you in **bookdown**. Thank you. 

> but the default search engine for gitbook does not support Chinese. So I need a plugin to do this job. Hopefully plugins will be supported.

@psychelzh Follow https://github.com/rstudio/bookdown/issues/1031 which could improve the search feature for your use case.
