### ISSUE TITLE
What is equivalent of &nbsp; and other hard spaces in bookdown?

### ISSUE THREAD

**Issue by N0rbert** [rstudio/bookdown#558]
In LaTeX we have many types of spaces `~`, `\,` `\;` and `\/`.

Is it possible to use them in bookdown directly?

Writing `&nbsp;` or `&#160;` seems to be not user-friendly.

**Comment by yihui** [comment]
bookdown stands on the shoulders of Pandoc, so it supports whatever Pandoc supports. The only thing I know is that if you escape a space by `\`, it will be `&nbsp;`.

Other than that, the only thing I can say is FAQ 1: https://bookdown.org/yihui/bookdown/faq.html
