### ISSUE TITLE
chapter titles with math in them, e.g. subscripts, mess up the contents panel

### ISSUE THREAD

**Issue by dicook** [rstudio/bookdown#56]
If you do CO$_2$ as a chapter or section heading, the subscript will not show and the contents panel will have a big white space under it.

**Comment by yihui** [comment]
It seems math expression won't work in the contents panel. Can you write `CO~2~` instead?

**Comment by dicook** [comment]
Yes, that is fixed already by spelling out the full word.

> On Mar 21, 2016, at 3:02 PM, Yihui Xie <notifications@github.com> wrote:
> 
> It seems math expression won't work in the contents panel. Can you write CO~2~ instead?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

---------------------------
Di Cook
visnut@gmail.com
