### ISSUE TITLE
HTML code for theorem/proof environments includes the same CSS class twice

### ISSUE THREAD

**Issue by GegznaV** [rstudio/bookdown#560]
HTML code created for theorem/proof environments contains the same CSS class two times (a class inside the same class), and this results in formatting applied two times. And this does not look nice. Find the illustration is below.

My example is based on the minimal `bookdown` example. In `01-intro.Rmd` I wrote this code (correct backticks for chunk as necessary):

```md
# Links

Link to exercise \@ref(exr:exr-1).

# Data

`` `{exercise, exr-1, out.extra = 'style="border: 3px;"'}

     Text of the first exercise. 
`` `
```

In `style.css` I added lines to add border and background:

```css
.exercise {
    border: 1px solid;
    border-radius:10px;
    background-color: #eeccff;
}
```
 And this resulted in formatting (the border) unnecessarily appied two times:

![image](https://user-images.githubusercontent.com/12725868/38176850-278d49ec-35ff-11e8-8c35-f6592d946215.png)

In HTLM code, these lines appear:

```html
<div class="exercise">
<span id="exr:exr-1" class="exercise"><strong>Exercise 3.1  </strong></span>
Text of the first exercise.
</div>
```

The class for `div` and for `span` is the same and causes the formatting issue. Is it possible to have two different CSS classes, e.g., `exercise` and `exercise-id` to avoid the issue?

Session informaction is the same as in #559

**Comment by yihui** [comment]
Can you use `div.exercise`?

**Comment by GegznaV** [comment]
Oh, it's an issue knowledge in using CSS and not an issue of `bookdown`. Formatting with `div.exercise` works as expected. Thank you @yihui
