### ISSUE TITLE
pandoc2+gitbook give excessive margin after code blocks

### ISSUE THREAD

**Issue by aronatkins** [rstudio/bookdown#562]
Using yihui/knitr@v1.20, rstudio/rmarkdown@v1.9, and rstudio/bookdown@v0.7.

Given a code block with leading and trailing text like the following:

````
It is also possible to specify the list of email attachments from R code.
For example:

```r
attachments <- list("attachment_1.csv", "attachment_2.csv")
rmarkdown::output_metadata$set(rsc_email_attachments = attachments)
```

An email attachment will be accessible via HTTP just like an output file, and
you can make a link to it in your report in the same way.
````

When using pandoc-1.19.2.1, it renders like:
![screen shot 2018-04-06 at 2 43 32 pm](https://user-images.githubusercontent.com/362187/38438645-175fa076-39a9-11e8-9100-67a83028edda.png)

Switching to pandoc-2.1.3, we get:
![screen shot 2018-04-06 at 2 43 47 pm](https://user-images.githubusercontent.com/362187/38438661-236c3942-39a9-11e8-8db6-c41b28a42189.png)

This is because pandoc is injecting `sourceCode` margins:

```
div.sourceCode { margin: 1em 0; }
```

and gitbook is also doing something similar:

```
.book .book-body .page-wrapper .page-inner section.normal pre{overflow:auto;word-wrap:normal;margin:0 0 1.275em;padding:.85em 1em;background:#f7f7f7}
```

**Comment by yihui** [comment]
I had fixed it last week, so please

```r
devtools::install_github('rstudio/bookdown')
```

**Comment by yihui** [comment]
If you really need it, I can make a CRAN release after this weekend.

**Comment by aronatkins** [comment]
Nah. We're good.
