### ISSUE TITLE
<br> html tag -> \newline in LaTeX output

### ISSUE THREAD

**Issue by el-mazarol** [rstudio/bookdown#567]
Hi,
I think it could be usefull if bookdown would be able to convert the `<br>` html tag to the `\newline` LaTeX command when the pdf output is generated.

Thankyou.

**Comment by yihui** [comment]
bookdown is at the mercy of Pandoc in terms of rendering Markdown.

**Comment by dataopt** [comment]
There are two ways to do it.  One is to add in `\newline` right after every `<br>` tag.  Pandoc should remove `\newline` when outputting to HTML but include it when outputting to PDF/LaTex.  The other is to process `<br>` tags via a lua filter which you can read more about at https://pandoc.org/lua-filters.html.  Using a lua filter within bookdown will require setting up some pandoc args.

**Comment by yihui** [comment]
That is exactly right.

And I forgot to mention http://pandoc.org/MANUAL.html#paragraphs
