### ISSUE TITLE
Failing to find str_view again

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#57]
https://travis-ci.org/hadley/r4ds#L2802

This is something in the intersection between dev stringr, htmlwidgets, and r4ds :/

**Comment by yihui** [comment]
The last time I tried to render r4ds, I found you cached `library(stringr)`. In theory, that should not be a problem, since knitr will reload cached packages, but I don't know what went wrong there. This should be fixed if you put `library(stringr)` in an uncached chunk.

**Comment by hadley** [comment]
Fixed it - thanks!
