### ISSUE TITLE
If name of chunk has an space, figures do not show

### ISSUE THREAD

**Issue by gorkang** [rstudio/bookdown#576]
If the name of a chunk where we create an image (e.g. `plot(1)`) includes an space, as in "global plot", the resulting image path will be "_main_files/figure-html/global%20plot-1.png" and the image won't be displayed. 

Changing the name of the chunk to "global_plot", makes the resulting image path  "_main_files/figure-html/global_plot-1.png" and it will be shown. 

It would be nice if figures would show regardless :)

**Comment by yihui** [comment]
See the first NOTE block on this page https://bookdown.org/yihui/bookdown/figures.html I recommend you to only use those characters in your chunk labels.

Also see https://yihui.name/en/2018/03/space-pain/

**Comment by yihui** [comment]
Fixed via #631.
