### ISSUE TITLE
bookdown/rmarkdown/knitr: links from PDF to local files and windows/OSX

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/bookdown#580]
Hi. I asked over at [Stackoverflow](https://stackoverflow.com/q/50253417/2103880), but had no takers, so I try here again:

My bookdown report knitted to PDF tries to link to the underlying results like so

    [This](./somedir/.) directory contains some data.

or so

    [This file](./somedir/specific_data.txt) contains something more specific.

On (Arch)Linux using okular (my devel environment) all of this just works fine (file manager opens for the first, MIME type defined application for the second link), but on MS Windows and OSX Acrobat Reader asks whether to follow that link and after allowing to do so, the only thing that happens is that the dialog window disappears ...

Is what I want generally impossible on those platforms or am I doing something wrong?

Thanks, Joh

**Comment by yihui** [comment]
Thanks for mentioning cross-posting, but I don't have an answer. From your description, it seems to be up to the specific OS and PDF reader, so I guess there isn't anything I can do on bookdown's side.

**Comment by r-cheologist** [comment]
See [here](https://stackoverflow.com/a/50508984/2103880) for the solution I finally became aware off ...

**Comment by yihui** [comment]
Actually I blogged about it (`run:`) ten years ago: https://yihui.name/en/2008/10/how-to-open-a-file-from-a-hyperlink/ but I'm not sure if it is a portable solution.

**Comment by r-cheologist** [comment]
Works for me from within okular and acrobat reader at least ...
