### ISSUE TITLE
Resize not triggering for htmlwidgets

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/bookdown#581]
Resize it not triggering for htmlwidgets which makes them really hard to consume in mobile devices.

Repro:

Create a new bookdown project in RStudio and add the following chunks:

``````
```{r}
library(leaflet)

leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
```


```{r}
plot(iris)
```
``````

Notice that the plot resizes correctly but the htmlwidget is hardcoded in size:

<img width="842" alt="screen shot 2018-05-21 at 7 52 57 am" src="https://user-images.githubusercontent.com/3478847/40314116-678c9aea-5ccc-11e8-96be-0ab63e92d0fe.png">

<img width="843" alt="screen shot 2018-05-21 at 7 53 10 am" src="https://user-images.githubusercontent.com/3478847/40314117-67a3f046-5ccc-11e8-92c6-a0cdadfaa521.png">

I would expect instead for the htmlwidget to respond to resize events and change is size correctly.

@yihui, I would like to fix this one at some point, if anything, let me know what you think to send a proper PR. Thanks!

**Comment by yihui** [comment]
Does the chunk option `out.width='100%'` work?

**Comment by javierluraschi** [comment]
It does!

<img width="708" alt="screen shot 2018-05-21 at 8 02 12 am" src="https://user-images.githubusercontent.com/3478847/40314418-4a3811d0-5ccd-11e8-915b-9bb929a50ae9.png">

**Comment by yihui** [comment]
Great!
