### ISSUE TITLE
Java script bug?

### ISSUE THREAD

**Issue by nikolaussucher** [rstudio/bookdown#584]
Hi, I noticed a weird bug: on my iPhone and MacBook Pro (using any browser) I see the toolbar with the icons for the toc, search, edit and download. On my iPad it doesn’t show (again any browser). When I touch the area where it should be and move my finger up, the icons appear but disappear when I let go. If I touch the blank screen, where the icons should be, I get the expected response.

**Comment by dataopt** [comment]
This is a known issue.  The root problem is in the gitbook template.  See #60.

**Comment by yihui** [comment]
Duplicate of #60
