### ISSUE TITLE
`render_book(output_format = "pdf_book")` fails for bookdown-demo when `new_session: yes`

### ISSUE THREAD

**Issue by martinjhnhadley** [rstudio/bookdown#585]
The discussion of M-K vs K-M rendering options (https://bookdown.org/yihui/bookdown/new-session.html) does not appear to argue against using K-M for generating PDF.

However, the workflow described below yields this error

```r
> render_book(input = c("01-intro.Rmd", "02-literature.Rmd"),
+             output_format = "pdf_book")
Error in eval(parse(text = name)) : object 'pdf_book' not found
Calls: local ... <Anonymous> -> create_output_format -> eval -> eval
Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile index.Rmd
```

If this workflow is not recommended then I'll happily make a PR to suggest explanatory text to this extent.

# Workflow

1. Download https://github.com/rstudio/bookdown-demo
1. Open bookdown-demo.Rproj in RStudio
1. Add the following to `_bookdown.yml`
`new_session: yes`
1. Run:
```r
bookdown::render_book(input = c("01-intro.Rmd", "02-literature.Rmd"),
            output_format = "pdf_book")
# Error in eval(parse(text = name)) : object 'pdf_book' not found
# Calls: local ... <Anonymous> -> create_output_format -> eval -> eval
# Execution halted
# Error in Rscript_render(f, render_args, render_meta) : 
#  Failed to compile index.Rmd
```

**Comment by yihui** [comment]
It is `bookdown::pdf_book`.

Reference: https://bookdown.org/yihui/rmarkdown/output-formats.html

**Comment by martinjhnhadley** [comment]
Ahh, thanks! I'm not sure how exactly I missed this information.

I added a PR to the demo book here https://github.com/rstudio/bookdown-demo/pull/31
