### ISSUE TITLE
bookdown citation: no chicago-author-date references working

### ISSUE THREAD

**Issue by reikoch** [rstudio/bookdown#586]
Running on RHEL 7.4 with R 3.4.4 using bookdown 0.7 or 0.7.12 from github we cannot produce nice citation references in Word, see attached example ["BIBLIOGRAPHY (S. P et al. (2004); C, JJ, and LL. (2009); B, M, and T. (2008))." authors are abbreviated instead of full name].
Trying to exactly specify cls with
> csl: chicago-author-date.csl 

gives us errors like

> pandoc-citeproc: Error parsing XML file chicago-author-date.csl: chicago-author-date.csl: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc
Filter returned error status 1
Error: pandoc document conversion failed with error 83
Execution halted

We are using RStudio server pro v1.1.442. Not sure what exactly goes wrong.
[TEST_BIBLIO (2).docx](https://github.com/rstudio/bookdown/files/2058003/TEST_BIBLIO.2.docx)
[TEST_BIBLIO.Rmd.txt](https://github.com/rstudio/bookdown/files/2058011/TEST_BIBLIO.Rmd.txt)

**Comment by cderv** [comment]
Thanks for your patience. I hope you found a solution since then but just in case for others too here is an answer.

> pandoc-citeproc: Error parsing XML file chicago-author-date.csl: chicago-author-date.csl: openBinaryFile: does not exist (No such file or directory)

Did you have the `.csl` file in your project ? As you did not specified a URL you need the file locally. 
You can specify a URL directly if you can use online. 

```yaml
csl: https://www.zotero.org/styles/chicago-author-date
```

See https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html for documentation on changing CSL.

Example
````markdown
---
title: "mCRM EWOC for PD1-TIM3"
author: "Francesca Michielin"
date: "Last compiled `r Sys.Date()` by `r Sys.info()[['user']]` on `r Sys.info()['nodename']`"
output:
  bookdown::word_document2:
    fig_width: 6
    fig_height: 4
    fig_caption: true
header-includes:
- \usepackage{float}
- \floatplacement{figure}{H}
link-citations: yes
biblio-style: apalike
bibliography: references.bib
csl: https://www.zotero.org/styles/chicago-author-date
params:
  runAll: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::write_bib("knitr", "references.bib")
```

## R Markdown

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <http://rmarkdown.rstudio.com>.

THIS IS HOW TO INSERT BIBLIOGRAPHY: @knitr2015

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Reference
````
