### ISSUE TITLE
[bug] Invalid arguments when building PDF output with Pandoc2

### ISSUE THREAD

**Issue by gaocegege** [rstudio/bookdown#587]
Thank you for the awesome tool, which makes writing a book so simple. While when I am using pandoc 2.2.1 to generate PDF output, there is an error:

```
Rscript --quiet _render.R "bookdown::pdf_book"
--latex-engine has been removed.  Use --pdf-engine instead.
Try pandoc --help for more information.
Error: pandoc document conversion failed with error 2
Execution halted
Error: Failed to compile the book to bookdown::pdf_book
Execution halted
Makefile:2: recipe for target 'pdf' failed
```

I tried to read the code but I do not find where the logic is. I found that [here](https://github.com/rstudio/bookdown/blob/master/R/latex.R#L65) runs latexmk with the `latex_engine`. But I think it is not the cause of the error.

Then I tried pandoc 1.9 then it works well. Thus I think we have a hardcoded arguments somewhere in the code, then pandoc 2 changed it to `pdf-engine` then failed to build the book successfully.

I'd appreciate if you could take a look :smile:

**Comment by yihui** [comment]
[Is everything up-to-date?](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) e.g. try `update.packages(ask = FALSE, checkBuilt = TRUE)`

**Comment by gaocegege** [comment]
Thanks, it works. It is just like a magic :smile:
