### ISSUE TITLE
suggestion: code block to latex could be configured

### ISSUE THREAD

**Issue by bubifengyun** [rstudio/bookdown#588]
I find that in bookdown no matter whatever you write like,

<pre>
```bash
$ make
```
</pre> 

or

<pre>
```c
$ make
```
</pre>

will always produce like 

```
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{$ }\FunctionTok{make}
\end{Highlighting}
\end{Shaded}
```

All grammar related color highlight was removed.
if using `lstlisting` instead of `Shaded`, such as,

```
\begin{lstlisting}[language={C}, caption={一段C源代码}]
#include <stdio.h>
\end{lstlisting}
```

it will be much more beautiful. Could bookdown change it?Thank you.

**Comment by yihui** [comment]
Please read the Pandoc manual at least once (cf https://yihui.name/en/2017/11/thanks-tj-mahr/). In particular, take a look at `--listings`. Then use the `pandoc_args` option: https://bookdown.org/yihui/rmarkdown/output-formats.html

**Comment by yihui** [comment]
When you [cross-post issues](https://yihui.name/en/2017/10/cross-posting/), please mention it. Let's keep everyone in the same thread. Thanks!

https://stackoverflow.com/q/50773489/559676

**Comment by bubifengyun** [comment]
Thanks @YihuiXie I had solved this problem as you said. by set *_outputyml*

```
  pandoc_args: ["--listings", "--top-level-division=chapter"]
```
add `--listings` for pandoc.

Then you cannot input `$` and `#` in code, so you can try
`$\$$`,`$\#$`,`#`, for non-root and root user. 

that problem in https://stackoverflow.com/questions/50773489/how-to-knitr-rmarkdown-code-block-to-special-latex-format was solved. Thank you.
