### ISSUE TITLE
Feature request: about ````

### ISSUE THREAD

**Issue by bubifengyun** [rstudio/bookdown#591]
in *./inst/example/02-component.Rmd* file,

<pre>
````markdown
A normal paragraph.

(ref:foo) A scatterplot of the data `cars` using **base** R graphics. 

`r ''````{r foo, fig.cap='(ref:foo)'}
plot(cars)  # a scatterplot
```
````
</pre>

this code, when set in pandoc

```yaml
# _output.yml
pandoc_args: ["--listings", "--top-level-division=chapter"]
```
using `listings` insteal of `Shade and Highlight`, it will pops error
such as, 

```
Rscript --quiet _render.R "bookdown::pdf_book"
! Undefined control sequence.
\lstlisting ->\def \lstenv@name 
                                {lstlisting}\begingroup \lst@setcatcodes \ca...
l.1603 \end{lstlisting}
                       '} 
Here is how much of TeX's memory you used:
 25476 strings out of 493005
 450868 string characters out of 6134596
 606163 words of memory out of 5000000
 29161 multiletter control sequences out of 15000+600000
 46124 words of font info for 75 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 53i,18n,117p,10406b,1664s stack positions out of 5000i,500n,10000p,200000b,80000s

错误: Failed to compile bookdown.tex. See bookdown.log for more info.
此外: Warning message:
In parse_ref_links(x, "^%s (.+)$") :
  Possibly duplicated text reference labels: (ref:foo)
```

Hope can support listings code block. Thank you.

**Comment by bubifengyun** [comment]
Sorry, It is my fault.

**Comment by bubifengyun** [comment]
I find that 
<pre>
Then you can use `(ref:foo)` in your figure/table captions. The text can contain anything that Markdown supports, as long as it is one single paragraph. Here is a complete example:

````markdown
A normal paragraph.

(ref:foo) A scatterplot of the data `cars` using **base** R graphics. 

`r ''````{r foo, fig.cap='(ref:foo)'}
plot(cars)  # a scatterplot
```
````
</pre>

in markdown, it will translate.
![_ _20180614140621](https://user-images.githubusercontent.com/4437214/41394386-51b12394-6fdc-11e8-9720-fb1ee8a01813.png)

**Comment by bubifengyun** [comment]
I think the reason may be,

When code chunk is translated into `lstlisting`, `(ref:foo)` is changed to other string not itself, but it is translated into 'shade`, it will not be translated to other string.

**Comment by bubifengyun** [comment]
https://github.com/openframeworks/ofBook/issues/69
That is problem. It is lstlisting's bug. Maybe it cannot work well for lstlisting

**Comment by bubifengyun** [comment]
I find that it may be because of pandoc version is too low, so i update to recently version 2.2.1, it pops error, 
```
! Undefined control sequence.
<recently read> \passthrough
```
I will try continue.

**Comment by bubifengyun** [comment]
我的是 texlive 2017, 发现这个添加 \passthrough 的日期 为 2017.04.29

https://github.com/dotlambda/pandoc/commit/730796ee314d42477fab216621b8e44539c94656

我且安装个 2018 试试，再看看这个问题能不能解决。

**Comment by bubifengyun** [comment]
https://stackoverflow.com/questions/50854429/bookdown-undefined-control-sequence-recently-read-passthrough as promotion

**Comment by yihui** [comment]
不必捣腾 LaTeX，这问题与 LaTeX 没什么关系。我在 SO 上回答你了。

**Comment by bubifengyun** [comment]
太感谢啦，明天我试试，真是每走一步都得各种找资料，还好，都解决啦，太激动了。

**Comment by yihui** [comment]
要求越多，付出就会越多，这没办法：https://bookdown.org/yihui/bookdown/faq.html

我自己没用过 listings，所以没有提前意识到这个问题。

**Comment by bubifengyun** [comment]
嗯嗯，昨天遇到的问题是定理 theorem 环境的问题，实在找不到办法，只得去下载latex相关包的说明文档。幸好，只有六页，多翻了几遍，给解决了。今天已经安装好texlive2018仍旧有问题，试着找资料自定义 passthrough，那些代码被还是被转译，就把 listings 的说明书下载了，想找找怎么才可以不转译，六十多页，才翻个概况，就收到短信，看到你的回复了。不过还是有些收获。代码中那个\`老是被变成单引号，如图片所示。在那个说明书上就有解决方案，争取明天一并解决。

**Comment by bubifengyun** [comment]
我试了一下，你说的那个定制 `\passthrough` 的方法，我下午已经参照，https://github.com/dotlambda/pandoc/commit/730796ee314d42477fab216621b8e44539c94656 试过了，依旧有问题。对于行内代码，确实有效。但是对于代码块，依旧被转译，我看一下生成的中间 tex 文件，对于 lstinline 都处置了，但是对 lstlisting 均未处理。我再去看看怎么解决这个 lstlisting 转译的问题

**Comment by bubifengyun** [comment]
看了一下 pandoc，也只是对 lstinline 处理了，没有过问 lstlisting ，https://github.com/dotlambda/pandoc/commit/730796ee314d42477fab216621b8e44539c94656 还没有看 pandoc 源码，应该是 pandoc 的问题。如果是，就去提交一个

**Comment by bubifengyun** [comment]
重新理解了rmarkdown，看了一下生成的 rmd,md文件都是对的，就是pandoc 从 md 到 tex 用 listings 出问题了。看了pandoc 源码也是不好下手改，我再看看 listings 说明书吧，看看有没有突破。

**Comment by bubifengyun** [comment]
今天重新阅读了 listings.pdf 还有 pandoc ，感觉没有啥问题。把 `_render.R` 文件，的 `--quiet` 去掉，会弹出很多字符，如下

```
output file: sjtu-thesis-rmd.knit.md

/usr/bin/pandoc +RTS -K512m -RTS sjtu-thesis-rmd.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output sjtu-thesis-rmd.tex --table-of-contents --toc-depth 2 --template tex/template.tex --number-sections --highlight-style tango --pdf-engine xelatex --biblatex --listings --top-level-division=chapter --variable tables=yes --standalone 
! File ended while scanning use of \@newl@bel.
<inserted text> 
                \par 
l.104 \begin{document}

错误: Failed to compile sjtu-thesis-rmd.tex. See sjtu-thesis-rmd.log for more info.
此外: Warning message:
In parse_ref_links(x, "^%s (.+)$") :
  Possibly duplicated text reference labels: (ref:foo)
停止执行
错误: Failed to compile the book to bookdown::pdf_book
停止执行

```

I backup 

- sjtu-thesis-rmd.knit.md -> knit.md
- sjtu-thesis-rmd.utf8.md ->utf8.md

then, I use the command in output, like this

```
/usr/bin/pandoc +RTS -K512m -RTS utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output utf8.tex --table-of-contents --toc-depth 2 --template tex/template.tex --number-sections --highlight-style tango --pdf-engine xelatex --biblatex --listings --top-level-division=chapter --variable tables=yes --standalone 
```

I find that utf8.tex was not the same with `sjtu-thesis-rmd.tex`, I find utf8.tex was correct. 

<pre>
# in utf8.tex
\begin{lstlisting}
(ref:foo) Define a text reference **here**. 
\end{lstlisting}

Then you can use \passthrough{\lstinline!(ref:foo)!} in your
figure/table captions. The text can contain anything that Markdown
supports, as long as it is one single paragraph. Here is a complete
example:

\begin{lstlisting}
A normal paragraph.

(ref:foo) A scatterplot of the data `cars` using **base** R graphics. 

```{r foo, fig.cap='(ref:foo)'}
plot(cars)  # a scatterplot
```
\end{lstlisting}
</pre>

but `sjtu-thesis-rmd.tex`

<pre>
# `sjtu-thesis-rmd.tex`
\begin{lstlisting}



Then you can use \passthrough{\lstinline!Define a text reference **here**. 
\end{lstlisting}!} in your
figure/table captions. The text can contain anything that Markdown
supports, as long as it is one single paragraph. Here is a complete
example:

\begin{lstlisting}
A normal paragraph.

Define a text reference **here**. 
\end{lstlisting} A scatterplot of the data `cars` using **base** R graphics. 

```{r foo, fig.cap='Define a text reference **here**. 
\end{lstlisting}'}
plot(cars)  # a scatterplot
```
\end{lstlisting}
</pre>

So I think the reason was in `_render.R` file, I will try reread your bookdown.pdf, then try modify `_render.R`, Thank you.

**Comment by yihui** [comment]
我建议你不要在你的源文件中用这个例子（即：删掉这一段）：

````
A normal paragraph.

(ref:foo) A scatterplot of the data `cars` using **base** R graphics. 

```{r foo, fig.cap='(ref:foo)'}
plot(cars)  # a scatterplot
```
````

这一段对你真正的论文应该没有任何用处。

**Comment by bubifengyun** [comment]
嗯嗯，已经足够用了，不再继续折腾这个问题，有些内容不能追求完美

**Comment by bubifengyun** [comment]
我觉得问题可能在 render_book 这个函数，使用 pandoc 已经处理出来的 tex 文件暂时没有发现问题，还会被再次处理一次，比如 `@ref` 变为 `\ref{}` ，貌似这个过程出问题了。

**Comment by bubifengyun** [comment]
https://github.com/rstudio/bookdown/blob/master/R/latex.R?#L108#L138 原因基本查明，对于使用 Shade 高亮的代码，因为是对每个关键字都处理了，所以对全文处理时，不会有问题，但是使用 listings ，则整个不动，使用上述的搜索替换，就会出现 `lstlisting` 或者其他不应当替换的部位也被替换了。如果可以增加一个排除某部分代码，不替换，就可以了。比如 pandoc 就做到了不是对全文所有的 ref 或者其他内容一股脑的全部替换。

**Comment by bubifengyun** [comment]
https://github.com/rstudio/bookdown/blob/master/R/latex.R?#L137 这一行是对行内代码的复原。对于 listings 则没有涉及，我找找，能否对 lstinline lstlisting 括号内的都不替换。

**Comment by bubifengyun** [comment]
我错了，貌似这个不能这么解决，不说了。
