### ISSUE TITLE
New books to be added to the list on bookdown.org

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown#595]
- [x] https://serialmentor.com/dataviz/
- [x] https://socviz.co
- [x] https://otexts.org/fpp2/ (contact Rob)
- [x] https://www.datascienceatthecommandline.com/ (contact Jeroen Janssens)
- [x] https://www.gastonsanchez.com/r4strings/
- [ ] https://m-clark.github.io/documents/
- [x] https://bookdown.org/sestelo/sa_financial/
- [x] #541 
- [x] #532 
- [x] #511
- [x] #337

**Comment by m-clark** [comment]
Hi Yihui,  I actually had been meaning to get in touch with you a couple months ago to send you a list, so sorry for the delay.  Here is the list I was going send with the ones you've already put up crossed out.  I've gone ahead and added a blurb in case that saves you some effort.

~~[Graphical and Latent Variable Modeling](https://m-clark.github.io/sem/)~~
~~[Bayesian Basics](https://m-clark.github.io/bayesian-basics/)~~
~~[Generalized Additive Models](https://m-clark.github.io/generalized-additive-models/)~~
~~[Mixed Models with R](https://m-clark.github.io/mixed-models-with-R/)~~


[Machine Learning: an Introduction](http://m-clark.github.io/introduction-to-machine-learning/)

This is a gentle introduction to machine learning concepts with some application in R. Coverage includes the distinction between machine learning and standard statistical practice; key concepts such as regularization and cross-validation, and bias-variance tradeoff; demonstration of specific techniques; interpretability of results, and more.


[Text Analysis with R](https://m-clark.github.io/text-analysis-with-R/)

This document covers a wide range of topics, including how to process text generally, and demonstrations of sentiment analysis, parts-of-speech tagging, word embeddings, and topic modeling. Exercises are provided for some topics.


[Data Processing and Visualization in R](https://m-clark.github.io/data-processing-and-visualization/) 

The focus of this document is on common data processing and exploration techniques, especially as a prelude to visualization, as well as more advanced programming for applied users of R. Part of the focus will be on dplyr and tidyverse, which enhance and facilitate the sorts of operations that typically arise when dealing with data, including faster I/O and grouped operations. For visualization, the focus will be on using ggplot2 and other packages that allow for interactivity. Programming basics are also covered. Exercises are provided as well, and Jupyter notebooks of the same demonstrations in Python. 


[Introduction to R Markdown](https://m-clark.github.io/Introduction-to-Rmarkdown/) 

This documents will introduce readers to the basics of R Markdown. After an introduction to concepts related to reproducible programming and research, demonstrations of standard markdown as well as overviews of different formats will be provided, including exercises. 


[Clustered Data](https://m-clark.github.io/clustered-data/) 

This is a handbook reference for a variety of approaches one might use for data that is explicitly clustered in some fashion (e.g. longitudinal, hierarchical etc.). Includes a comparison of standard models, cluster robust standard errors, fixed effect models, mixed models (random effects models), generalized estimating equations (GEE), and latent growth curve models for dealing with clustered data.

**Comment by yihui** [comment]
@m-clark I'll add them in a few minutes. Thank you!

**Comment by yihui** [comment]
@m-clark Actually I don't need the descriptions, since they are automatically generated by scraping your book pages. These five books have been listed at https://bookdown.org/home/archive. If you see any information that is not accurate, that is probably because you used something nonstandard, e.g., the book title for "Text Analysis with R" was actually "In the beginning was the word ..." because that was the title you specified in index.Rmd: https://github.com/m-clark/text-analysis-with-R/blame/master/index.Rmd (while I was there, I discovered that you used HTML tags very often, e.g., `<span style="...">`, and I'd strongly recommend not using HTML tags, but CSS instead. The author field could be cleaner, too. If you have other meta information, it can probably go to the body of the book).

**Comment by yihui** [comment]
BTW, next you may help yourself by submitting pull requests if you have more books to share: https://bookdown.org/home/about/

**Comment by m-clark** [comment]
Thanks for the info and suggestions, some of that is legacy from trying things out for the first time long ago, and could definitely use some updating, but otherwise I'll update my template going forward. I knew you planned on providing that functionality for us to do pull requests, so I'll certainly do so to add documents in the future!  

And thanks for the great tool, I've enjoyed using it quite a bit, and a lot of clients have found these documents useful!
