### ISSUE TITLE
Bug: cannot modify _bookdown.yml book_filename

### ISSUE THREAD

**Issue by bubifengyun** [rstudio/bookdown#597]
<pre>
> devtools::session_info('bookdown')
Session info ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.447)           
 language zh_CN                       
 collate  zh_CN.UTF-8                 
 tz       PRC                         
 date     2018-07-02                  

Packages ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                           
 backports   1.1.2   2017-12-13 CRAN (R 3.4.1)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.1)                   
 bookdown    0.7.13  2018-06-17 Github (rstudio/bookdown@dda5f5a)
 digest      0.6.15  2018-01-28 CRAN (R 3.4.1)                   
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)                   
 glue        1.2.0   2017-10-29 CRAN (R 3.4.1)                   
 graphics  * 3.4.1   2017-07-07 local                            
 grDevices * 3.4.1   2017-07-07 local                            
 highr       0.6     2016-05-09 CRAN (R 3.4.1)                   
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.1)                   
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.1)                   
 knitr       1.20    2018-02-20 CRAN (R 3.4.1)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.4.1)                   
 markdown    0.8     2017-04-20 CRAN (R 3.4.1)                   
 methods   * 3.4.1   2017-07-07 local                            
 mime        0.5     2016-07-07 CRAN (R 3.4.1)                   
 Rcpp        0.12.16 2018-03-13 CRAN (R 3.4.1)                   
 rmarkdown   1.10    2018-06-11 CRAN (R 3.4.1)                   
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.1)                   
 stats     * 3.4.1   2017-07-07 local                            
 stringi     1.2.2   2018-05-02 CRAN (R 3.4.1)                   
 stringr     1.3.1   2018-05-10 CRAN (R 3.4.1)                   
 tinytex     0.5     2018-04-16 CRAN (R 3.4.1)                   
 tools       3.4.1   2017-07-07 local                            
 utils     * 3.4.1   2017-07-07 local                            
 xfun        0.2     2018-06-16 cran (@0.2)                      
 yaml        2.1.19  2018-05-01 CRAN (R 3.4.1)                   
> rmarkdown::pandoc_version()
[1] ‘2.2.1’
> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018)
kpathsea version 6.3.0
Copyright 2018 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.00
</pre>

I download example, when I modify https://github.com/rstudio/bookdown/blob/master/inst/examples/_bookdown.yml 

```
book_filename: deepin-bible
```
the others keep the same, it will pops error,

```
$ make all
Rscript --quiet _render.R
[1] "/home/litianci/bookdown/inst/examples/_book/deepin-bible.pdf"
pandoc-citeproc: reference R-tufte not found
pandoc-citeproc: reference R-rticles not found
pandoc-citeproc: reference R-servr not found
pandoc-citeproc: reference R-tufte not found
pandoc-citeproc: reference R-rticles not found
pandoc-citeproc: reference R-servr not found
[WARNING] Could not convert TeX math '\begin{align}
  g(X_{n}) &= g(\theta)+g'({\tilde{\theta}})(X_{n}-\theta) \notag \\
  \sqrt{n}[g(X_{n})-g(\theta)] &= g'\left({\tilde{\theta}}\right)
    \sqrt{n}[X_{n}-\theta ] \qquad(2.2)
  \end{align}', rendering as TeX:
  a}})(X_{n}-\theta) \notag \\
                     ^
  unexpected "\\"
  expecting "&", "\\\\", white space or "\\end"
[1] "/home/litianci/bookdown/inst/examples/_book/deepin-bible.epub"
Warning messages:
1: In xfun::prose_index(content) : Code fences are not balanced
2: The label(s) fig:does-not-exist not found 
Cannot read from /home/litianci/bookdown/inst/examples/_book/bookdown.epub
Error in bookdown::calibre("_book/bookdown.epub", "mobi") : 
  Failed to convert _book/bookdown.epub to _book/bookdown.mobi
停止执行
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1
```

I know the bookdown.epub should be instead of deepin-bible.pdf. How to configure? Thank you.

**Comment by yihui** [comment]
Here:

https://github.com/rstudio/bookdown/blob/dda5f5a220058271a43ba8b81c6e6859ae3b9815/inst/examples/_render.R#L21

BTW, did I mention that you'd better not start from bookdown's book as your first example? This book's configurations are relatively complicated. There are other much simpler examples like

- https://github.com/yihui/bookdown-minimal
- https://github.com/rstudio/bookdown-demo
- https://github.com/yihui/bookdown-chinese
- https://github.com/yihui/bookdown-crc

**Comment by bubifengyun** [comment]
Thank you, I had read this example two months, I think I can understand something.
