### ISSUE TITLE
default HTML output on iPad

### ISSUE THREAD

**Issue by kylelundstedt** [rstudio/bookdown#60]
Hi @yihui 
When browsing the standard HTML output from bookdown on an iPad, there doesn't seem to be a way to collapse the sidebar containing the table of contents.  So, when reading the bookdown or r4ds websites, the sidebar always takes up over 1/3 of the reading space on the iPad.  It would be great if the default HTML output allowed one to collapse/expand the TOC, or to see TOC in a menu.

Thanks
Kyle

**Comment by yihui** [comment]
You can tap the first button to toggle the sidebar:

<img width="222" alt="screen shot 2016-03-23 at 5 03 30 pm" src="https://cloud.githubusercontent.com/assets/163582/14002349/7089efce-f119-11e5-8ccc-0c2ba971bcc7.png">

**Comment by kylelundstedt** [comment]
Hmm.  I'm probably a complete knucklehead, but the toolbar does not appear in Safari on the iPad when viewing the HTML output.  I went to both of the following sites to confirm:

http://rstudio.github.io/bookdown/
http://r4ds.had.co.nz

No amount of tapping, double-tapping, etc causes the toolbar to appear.  What am I missing?

**Comment by yihui** [comment]
Okay, I just looked at it on iPad and indeed the toolbar buttons were invisible. This is similar to #44. The buttons are actually there but I don't know why they are not displayed. You can scroll down the page, and you can see a blank toolbar at the top. You can actually tap at the left of the toolbar.

**Comment by jjallaire** [comment]
@jmcphers If you could spend 15 minutes looking at this we'd be eternally grateful (realize you have plenty of other things cooking this week so please just spend 15 minutes in hopes this is a really simple thing to resolve). The issue does repro on the XCode iPad simulator but I couldn't figure out how to do the equivalent of Inspect Element there.

**Comment by dataopt** [comment]
It looks like the `book-header.fixed` class is causing problems on the iPad.  It is not clear why that is the case.  So there is a way to bring back the toolbar by simply removing this class entirely from the css definitions.  But doing so will make the toolbar scroll with the body content. HOWEVER, this latter behaviour is what is found in the current gitbooks. See [this](https://gitbookio.gitbooks.io/progit/content/en/bf647454e36069fd16f1a7a35cf6a865/65a73881ffd9f9c7fc7cbc61080c2ce2.html) for example.

**Comment by luispuerto** [comment]
Hey!! 

Is this going to be fixed? 

There is a workaround that is to pull with your finger in the top part of the screen so buttons of the menu will show up for a second —so you know where you need to push— but a solution would be really appreciated. :)

**Comment by dullhunk** [comment]
As far as I can see, as of September 2019, this is still a bug. I've tested by viewing e.g. [r4ds.had.co.nz](https://r4ds.had.co.nz/) on a reasonably up to date iPad Pro and the menu icon (and whole menu bar) does not appear. @yihui

Not a problem on safari and macbook, but haven't tried an iPhone which will probably have the same problem and an ipad. @luispuerto 

If you tap on the _blank space_ where the menu items **should** be, the menus work, but that's not much use unless you're familiar with bookdown.

**Comment by luispuerto** [comment]
I've tried in the iPhone and the problem is the same. It a problem with Safari from iOS I guess. But it also happens on Firefox for iOS at least in the iPad, so I guess it's a iOS problem in general. I believe that all of them use webkit.

**Comment by dullhunk** [comment]
If it is is webkit that's the problem, it doesn't affect webkit & safari on a laptop / desktop - they work fine.

It seems to be specific issue with webkit/safari on an iPad/iPhone @luispuerto

**Comment by chipbrock** [comment]
This is a real problem if one is trying to show off work. Please fix it! Thanks.

**Comment by luispuerto** [comment]
@chipbrock this is only still a problem if you haven't update to the last version of iPadOS or iOS.

**Comment by chipbrock** [comment]
Thanks for a quick reply.

I’m running iPadOS 13.1.3 on a new iPad mini and it is not functioning as it should - no sandwich icon (or any icon) at the top of an otherwise respectable page of a document. 

On a computer, the icons are all proudly displayed as per normal. 

So I don’t think the new update fixes this. What am I missing? See attachments.

<img width="595" alt="screenshot_1114" src="https://user-images.githubusercontent.com/4515277/67622068-63c57580-f7e4-11e9-815a-10a184f310b5.png">

<img width="726" alt="screenshot_1113" src="https://user-images.githubusercontent.com/4515277/67622069-63c57580-f7e4-11e9-91d8-3d90f295f960.png">

**Comment by luispuerto** [comment]
Can you check this one? 

https://geocompr.robinlovelace.net/

In my iPad works just fine

**Comment by luispuerto** [comment]
It's working also fine on my iPhone 5S with iOS12 

![IMG_EAF3F57EF28E-1](https://user-images.githubusercontent.com/22882880/67622464-08ff3e80-f823-11e9-9d70-f7afba20868b.jpeg)

**Comment by chipbrock** [comment]
Thanks. 

I think I get it now. Your page does _not_ render with the sandwich visible on my ipad mini, but it _does_ on my phone _and_ on my ipad pro. So I suspect there's an issue with the adaptive width assignments in the css that governs the framework.

BTW. My page also renders fine in my larger ipad confirming for me that this is the problem. There must be an in-between size under which the sidebar collapses - which it does on the phone that's not in sync with the instructions to the header.

What I REALLY wish could be instituted is the switch to collapse the sidebar by default. From browsing other discussions, this seems to be a feature and not a ...lack of implementation.

**Comment by jtbayly** [comment]
This is also an issue on an iPhone XS in landscape mode.

**Comment by luispuerto** [comment]
I can confirm!

**Comment by louisaslett** [comment]
Also confirmed on iPhone 12 with iOS 14.4.2 -- portrait is fine, but landscape the menu bar disappears.  If you tap roughly where the three line collapse icon should be, it does indeed expand/collapse the contents but is not visible.

**Comment by apreshill** [comment]
FWIW - I am not able to reproduce by simulating with Firefox Responsive Design Mode:


https://user-images.githubusercontent.com/12160301/120014203-a211b080-bf96-11eb-96b3-6aaf20e4e7db.mov

**Comment by jtbayly** [comment]
Still an issue, though. From my iPhone XS:

**Comment by cderv** [comment]
@apreshill this is indeed difficult to reproduce because it seems related to mobile browser and emulation on desktop browser does not show the issue. It is quite the same with all mobile issue. This is some iPhone, iPad stuff also. Not even sure the issue arise on another mobile device (I need to check this). 

Anyway, this makes it hard to diagnose and to fix (also because I don't web mobile specific stuff 🤷‍♂️ )

**Comment by jtbayly** [comment]
No, the issue is open.

**Comment by cderv** [comment]
Hi @dullhunk 

This issue is not closed and is still open. No need to open a new one. 

As a workaround, Possible that the new `bs4_book()` behave better on apple device. 

If anyone can help with web CSS for mobile on iPad, this would be much appreciated, feel free open a PR !

**Comment by dullhunk** [comment]
Thanks @cderv yes `bookdown::bs4_book` behaves much better on Apple devices, has lots of nice features and doesn't have this hamburger bug. 

Unfortunately `bookdown::bs4_book` doesn't have _all_ the features of `bookdown::gitbook` though ... 

I'm not enough of an expert on `gitbook` or CSS to submit a pull request on this one.

**Comment by dullhunk** [comment]
As far as I can tell, this bug looks like a problem with Google Chrome on an iPad (not a specific bug with Apple Safari, iOS or iPadOS). I've done some testing on the following devices:

* iPhone XR
* iPad 2nd generation
* iPad air 4th generation

...by viewing [bookdown.org/yihui/bookdown](https://bookdown.org/yihui/bookdown/) using Chrome and Safari. The top ("hamburger") menu appears fine on Safari on all three devices, but isn't displayed when using Google Chrome on an iPad. The menu appears fine using an iPhone with Chrome. See screenshot below @cderv @kylelundstedt @yihui 

![thumbnail](https://user-images.githubusercontent.com/46497/121190082-9a89bb80-c862-11eb-9206-ae46e4af8c86.jpeg)

**Comment by jtbayly** [comment]
I just posted a video demonstrating the problem is Safari on iOS. It's not limited to Chrome. Chrome uses the same rendering engine as Safari on iOS. Every browser does, because Apple requires that. Thus, the problem likely afflicts all browsers on iOS, and just depends on the width of the viewport, and zoom level. (I've even confirmed it on a Tor browser on iOS.) Just put an iPhone in landscape mode and you will see this problem. In fact, the bug goes back to gitbook (the original project that this template was taken from), and you can find lots of old gitbooks online that have the same problem. 

I'm very poor at front-end stuff (even worse than I am at backend stuff), but I'll try to at least track down more specifically what the problem is. 

For now, I'll note that on my iPhone, if I zoom out to 50%, the bar comes back. And if I zoom in to 125%, it also comes back. Everything in between it is missing. 🤷

**Comment by mpereira-dev** [comment]
This worked for me on iOS + Safari | Firefox | Chrome:

```css
* {
  -webkit-overflow-scrolling: auto
}
```

Changing from `touch` to `auto` didn't seem to affect the momentum based scrolling.

There is now quite a bit of discussion on this issue on the web once you know what to search for:

- https://stackoverflow.com/questions/9807620/ipad-safari-scrolling-causes-html-elements-to-disappear-and-reappear-with-a-dela
- https://stackoverflow.com/questions/4889601/position-fixed-doesnt-work-on-ipad-and-iphone


I did get the toolbar to render by forcing hardware acceleration as suggested with:
`-webkit-transform: translate3d(0, 0, 0);`

But for me, the toolbar was then no longer fixed to the top of the page.

So I ended up overriding gitbook-2.6.7/css/style.css as mentioned above.

```css
* {
  -webkit-box-sizing:border-box;
  -moz-box-sizing:border-box;
  box-sizing:border-box;
  -webkit-overflow-scrolling:touch;               /* This is the problem. */
  -webkit-tap-highlight-color:transparent;
  -webkit-text-size-adjust:none;
  -webkit-touch-callout:none
}
```

References:

- https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling

**Comment by jtbayly** [comment]
Wow. Thank you. I can't wait to try this. Is this fully fixing the problem in your experience? Will a simple pull request fix this whole issue?

**Comment by yihui** [comment]
@mpereira-dev That's really awesome! Thank you so much for solving this long-lasting mystery!

@jtbayly I just applied the fix so you can try the dev version:

```r
remotes::install_github('rstudio/bookdown')
```

**Comment by mpereira-dev** [comment]
Thank you @yihui for all the hard work, the community has greatly benefited from your efforts.

@jtbayly my flavor of Gitbook is a bit customized for a client (lots more CSS). Please do test the fix on the vanilla version before promoting.

🥂 Miguel

**Comment by jtbayly** [comment]
Can confirm this fixes it on the iPad, but unfortunately not on the iPhone. Not sure why.
