### ISSUE TITLE
LaTeX error when using both a reference and the out.height option in pdf_book

### ISSUE THREAD

**Issue by theGreatWhiteShark** [rstudio/bookdown#606]
When using both a reference  and the `out.height` chunk option like in the following example script

```` r
# test {#chpt:test}

```{r 'fig1',fig.cap='test \\@ref(chpt:test)'}
plot( rnorm( 10 ) )
```

```{r 'fig2',fig.cap='test \\@ref(chpt:test)',fig.height=2,out.height='4in'}
plot( rnorm( 10 ) )
```
````

and rendering the file using `bookdown::pdf_book()` a LaTeX error will be thrown. 

Other output formats like `bookdown::gitbook()` do still work.

`devtools::session_info("bookdown")`
> Session info ------------------------------------------------------------------
>  setting  value                       
>  version  R version 3.5.0 (2018-04-23)
>  system   x86_64, linux-gnu           
>  ui       X11                         
>  language (EN)                        
>  collate  en_US.UTF-8                 
>  tz       XXX               
>  date     2018-07-26                  
> 
> Packages ----------------------------------------------------------------------
>  package   * version date       source                            
>  base64enc   0.1-3   2015-07-28 CRAN (R 3.5.0)                    
>  bookdown    0.7.15  2018-07-26 local (rstudio/bookdown@NA)       
>  digest      0.6.15  2018-01-28 CRAN (R 3.5.0)                    
>  evaluate    0.11    2018-07-17 cran (@0.11)                      
>  glue        1.2.0   2017-10-29 CRAN (R 3.5.0)                    
>  graphics  * 3.5.0   2018-05-26 local                             
>  grDevices * 3.5.0   2018-05-26 local                             
>  highr       0.6     2016-05-09 CRAN (R 3.5.0)                    
>  htmldeps    0.1.1   2018-07-26 Github (rstudio/htmldeps@c1023e0) 
>  htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)                    
>  jsonlite    1.5     2017-06-01 CRAN (R 3.5.0)                    
>  knitr       1.20    2018-02-20 CRAN (R 3.5.0)                    
>  magrittr    1.5     2014-11-22 CRAN (R 3.5.0)                    
>  markdown    0.8     2017-04-20 CRAN (R 3.5.0)                    
>  methods   * 3.5.0   2018-05-26 local                             
>  mime        0.5     2016-07-07 CRAN (R 3.5.0)                    
>  Rcpp        0.12.17 2018-05-18 CRAN (R 3.5.0)                    
>  rmarkdown   1.10.8  2018-07-26 Github (rstudio/rmarkdown@6879605)
>  stats     * 3.5.0   2018-05-26 local                             
>  stringi     1.2.2   2018-05-02 CRAN (R 3.5.0)                    
>  stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)                    
>  tinytex     0.6.4   2018-07-26 Github (yihui/tinytex@f9d1246)    
>  tools       3.5.0   2018-05-26 local                             
>  utils     * 3.5.0   2018-05-26 local                             
>  xfun        0.3.5   2018-07-26 Github (yihui/xfun@e99cf9e)       
>  yaml        2.2.0   2018-07-25 cran (@2.2.0) 

`rmarkdown::pandoc_version()`
> [1] ‘1.19.2.1’

`system('pdflatex --version')`
> pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)
> kpathsea version 6.2.2
> Copyright 2016 Han The Thanh (pdfTeX) et al.
> There is NO warranty.  Redistribution of this software is
> covered by the terms of both the pdfTeX copyright and
> the Lesser GNU General Public License.
> For more information about these matters, see the file
> named COPYING and the pdfTeX source.
> Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
> Compiled with libpng 1.6.28; using libpng 1.6.28
> Compiled with zlib 1.2.8; using zlib 1.2.8
> Compiled with poppler version 0.48.0

**Comment by yihui** [comment]
I recommend that you use text references when you need even slightly advanced figure captions: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references e.g.

````
# test {#chpt:test}

(ref:fig-cap) test \@ref(chpt:test)

```{r 'fig1', fig.cap='(ref:fig-cap)'}
plot( rnorm( 10 ) )
```

```{r 'fig2', fig.cap='(ref:fig-cap)', fig.height=2, out.height='4in'}
plot( rnorm( 10 ) )
```
````

**Comment by theGreatWhiteShark** [comment]
Oh, I wasn't aware of this. 

But with both references and mathematical expressions available one can already build some useful captions. 

Thanks.
