### ISSUE TITLE
Internationalization: figure caption

### ISSUE THREAD

**Issue by sammo3182** [rstudio/bookdown#608]
I am using `bookdown::word_document2` to write an academic paper in Chinese and trying to show  figures with captions also in Chinese. I applied the method introduced by https://bookdown.org/yihui/bookdown/internationalization.html to change the figure to "图" with a `_bookdown.yml`. However, the output showed the caption like this:

![image](https://user-images.githubusercontent.com/6463211/43646496-a7902cc6-9767-11e8-9ab0-b8423f7c079e.png)

I know `bookdown` mainly aims to Latex and html outputs and I can't appreciate that more. Nevertheless, many Chinese journals (if not all in liberal arts) accept manuscript only in Word. So, `bookdown::word_document2` is the best choice I know I can use. Hope there's a way to deal with this issue. I attached a minimal example and system information as following.

Example: 
[miniEG.zip](https://github.com/rstudio/bookdown/files/2257591/miniEG.zip)

Information: 

```r
> devtools::session_info('bookdown')
Session info -------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, mingw32             
 ui       RStudio (1.2.862)           
 language (EN)                        
 collate  English_United States.1252  
 tz       Asia/Taipei                 
 date     2018-08-03                  

Packages -----------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 base64enc   0.1-3   2015-07-28 CRAN (R 3.5.0)                    
 bookdown    0.7.15  2018-08-03 Github (rstudio/bookdown@c470a52) 
 digest      0.6.15  2018-01-28 CRAN (R 3.5.0)                    
 evaluate    0.11    2018-07-17 CRAN (R 3.5.1)                    
 glue        1.3.0   2018-07-17 CRAN (R 3.5.1)                    
 graphics  * 3.5.1   2018-07-02 local                             
 grDevices * 3.5.1   2018-07-02 local                             
 highr       0.7     2018-06-09 CRAN (R 3.5.0)                    
 htmldeps    0.1.1   2018-08-03 Github (rstudio/htmldeps@c1023e0) 
 htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.5.0)                    
 knitr       1.20.3  2018-05-22 local                             
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)                    
 markdown    0.8     2017-04-20 CRAN (R 3.5.0)                    
 methods   * 3.5.1   2018-07-02 local                             
 mime        0.5     2016-07-07 CRAN (R 3.5.0)                    
 Rcpp        0.12.18 2018-07-23 CRAN (R 3.5.1)                    
 rmarkdown   1.10.10 2018-08-03 Github (rstudio/rmarkdown@fc6e05e)
 stats     * 3.5.1   2018-07-02 local                             
 stringi     1.2.4   2018-07-20 CRAN (R 3.5.1)                    
 stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)                    
 tinytex     0.6     2018-07-07 CRAN (R 3.5.0)                    
 tools       3.5.1   2018-07-02 local                             
 utils     * 3.5.1   2018-07-02 local                             
 xfun        0.3     2018-07-06 CRAN (R 3.5.0)                    
 yaml        2.2.0   2018-07-25 CRAN (R 3.5.1)                    
> 
> rmarkdown::pandoc_version()
[1] ‘2.2.1’
```

Thanks.

**Comment by yihui** [comment]
My experience is that if you want to work with CJK languages (or other types of multibyte characters), the most reliable way is to change the locale of your computer (e.g., to Chinese in your case). You may also try `Sys.setlocale(, "Chinese")` in your `.Rprofile`. Using Chinese under an English locale can often cause problems.

The character encoding issue in R is an extremely deep rabbit hole. Personally I have spent countless hours on it (so [have others](https://shrektan.com/post/2018/03/18/strings-encodings-in-r/)). Honestly speaking, when I receive bug reports related to character encodings, I feel I'd rather buy you a Windows machine with the correct language/locale support instead.

**Comment by sammo3182** [comment]
Thank you very much for the solution! I once set the `Sys.setlocate` within the rmarkdown file. It did not work. Setting in `.Rprofile` solved the problem. Thank you again for the help and sharing the experiences on the encoding issue.
