### ISSUE TITLE
Table highlighting with kable not working

### ISSUE THREAD

**Issue by davibicudo** [rstudio/bookdown#609]
Tested with and without bookdown, and in the latter the highlighting is not working. Using pander it is though.

Here the code for testing:

````
---
title: "bookdown pdf table highlight issue"
site: bookdown::bookdown_site
documentclass: book
output: bookdown::pdf_document2
--- 

```{r, kable, echo=T}
knitr::kable(data.frame(to_highlight=c("**bold**", "*italic*")), 
             caption = 'non-highlighted table using kable')
```

```{r, pander, echo=T}
pander::pander(data.frame(to_highlight=c("bold", "italic")), 
                     emphasize.strong.cells = matrix(c(1,1), ncol=2),
                     emphasize.italics.cells = matrix(c(2,1), ncol=2),
               caption = "correctly highlighted table with pander")
```

Finally, using markdown:

|to_highlight|
|------------|
|  **bold**  |
|  *italic*  |
````

**Comment by mschilli87** [comment]
@davibicudo 
> again, it seems almost impossible to correctly render markdown code chunks within markdown so here is the code as txt file

Have a look [here](https://yihui.name/en/2017/05/four-backticks-github/)! :wink:

**Comment by davibicudo** [comment]
Amazing, thanks @mschilli87 !

**Comment by yihui** [comment]
In **bookdown**, `kable()` produces LaTeX tables by default when the output format is LaTeX because of this weird issue: http://tex.stackexchange.com/q/276699/9128

If you want Markdown tables, there are two ways to go:

1. Use `kable(..., format = 'pandoc')` or `format = 'markdown'`, or

2. Set `knitr::opts_knit$set(kable.force.latex = FALSE)` in a previous code chunk.

**Comment by davibicudo** [comment]
Thanks for clarifying. That issue actually happened to me and I had to add a 
````
```{r, results='asis'}
cat('\n\\newpage\n')
```
````
block right after my table to fix it.
