### ISSUE TITLE
Self-contained format

### ISSUE THREAD

**Issue by dmenne** [rstudio/bookdown#61]
When I create a self-contained HTML and remove the _book folder or move it to another directory, the content is ok, but the layout is strange with two scrollbars:

![2016-03-24 08_24_40-rstudio](https://cloud.githubusercontent.com/assets/506275/14011023/349ba9f8-f19b-11e5-8307-4f67c4b7c75b.png)

```
--- 
title: "Authoring A Book with R Markdown"
date: "`r Sys.Date()`"
author: "Dieter Menne"
knit: "bookdown::render_book"
output:
  bookdown::gitbook: 
    self_contained: true

---

# Index

```

yml:

```
book_filename: "dieter-bookdown.Rmd"
chapter_name: "Chapter "
rmd_files: [ "index.Rmd", "c.Rmd", "b.Rmd", "a.Rmd" ]

```

**Comment by yihui** [comment]
You were looking at the wrong output, and the actual output files are in the `_book` directory. `dieter-bookdown.html` was only the intermediate HTML file that I forgot to delete (now it will be deleted).

Please see http://rstudio.github.io/bookdown/a-single-document.html and typically you are not recommended to use `self_contained = TRUE` for gitbook output for reasons explained at http://rstudio.github.io/bookdown/html.html (search for `self_contained`). Also note MathJax may not work when `self_contained = TRUE`.
