### ISSUE TITLE
rmd_files not respected

### ISSUE THREAD

**Issue by robjhyndman** [rstudio/bookdown#610]
If you have `rmd_files` specified in your `_bookdown.yml` config, but a few other Rmd files in the folder that are not listed, they now all get used due to https://github.com/rstudio/bookdown/commit/38338ba085b9d15383fe1bc71c86732e129d1742. In other words, `rmd_files` is no longer respected. I think this can be easily fixed by the change proposed at 
https://github.com/rstudio/bookdown/commit/38338ba085b9d15383fe1bc71c86732e129d1742#r30012237

But perhaps that would break something else, so I am just pointing it out rather than doing a PR. I can give you the PR if you prefer.

**Comment by mschilli87** [comment]
[correct comment link](https://github.com/rstudio/bookdown/commit/38338ba085b9d15383fe1bc71c86732e129d1742#r30012237)

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!
