### ISSUE TITLE
Declaration of a (ref:textreference) sometimes mistakenly detected inside a paragraph

### ISSUE THREAD

**Issue by brendanf** [rstudio/bookdown#616]
The specification says that definitions of text references should start their own paragraph.  However, this is not checked during parsing (at least for LaTeX output), so a reference which occurs within a paragraph (even in the middle of a line of the source file) is sometimes detected as a definition.  Apparently this is because the text of paragraphs is reflowed at some earlier part of the rendering process.  In cases where the actual definition occurs later in the file than the reference (I love that this is possible!) then the definition and reference are switched.

```Rmarkdown
---
title: "MWD"
output: bookdown::pdf_document2
---

Here is an example of a paragraph which includes some spacer text,
then (ref:test) and some additional text which follows it.

(ref:test) _the test text_
```

Gives the warning:
```
Warning message:
In parse_ref_links(x, "^%s (.+)$") :
  Possibly duplicated text reference labels: (ref:test)
```

and renders as:

>Here is an example of  a paragraph which includes some spacer text, then
>
> and some additional text which follows it. _the test text_

instead of the desired:

>Here is an example of a paragraph which includes some spacer text, then _the test text_ and some additional text which follows it.

**Comment by brendanf** [comment]
In contrast:
```Rmarkdown
---
title: "MWD"
output: bookdown::pdf_document2
---

Here is an example of a paragraph which includes (ref:test) and some additional text which follows it.

(ref:test) _the test text_
```
renders without warning and produces the desired result.

**Comment by yihui** [comment]
Thanks! This should work:

````
---
title: "MWD"
output:
  bookdown::pdf_document2:
    pandoc_args: --wrap=preserve
---

Here is an example of a paragraph which includes some spacer text,
then (ref:test) and some additional text which follows it.

(ref:test) _the test text_
````

Perhaps `--wrap=preserve` should be the default in `bookdown::pdf_document2`.

**Comment by beanumber** [comment]
What if you want to start a new paragraph with a text reference? For example,

```
(ref:R) **R**

(ref:R) is a free, open-source software environment for statistical computing and graphics.
```

Is there a way to do this without generating the warning?
