### ISSUE TITLE
Can not get the colon separator between Figure and number in bookdown::word_document2

### ISSUE THREAD

**Issue by upton9265** [rstudio/bookdown#618]
https://stackoverflow.com/q/51970625/559676

**Comment by upton9265** [comment]
Sorry mistakenly hit the enter button before I finished.

I have this chunk for a figure:
```{r blah-blah, echo=FALSE, fig.cap='blah blah'}
knitr::include_graphics('blah-blah.jpg')
```

and this in my _bookdown.yml
delete_merged_file: true
language:
  label:
    fig: 'Figuee '
    tab: 'TABLE '
  ui:
    chapter_name: "Chapter "

but it shows up in the word document as: 
Figuee 1 blah-blah

with no colon between the figure number and the caption. For the life of me, I don't see where that is specified nor where I can change it. I'm sure I'm missing something simple somewhere.

> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bookdown_0.7

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    knitr_1.20     xfun_0.3

**Comment by N0rbert** [comment]
This problem is still actual. I have the [same problem](https://stackoverflow.com/q/54915204/937095).

@yihui , could please make available and configurable? 

Some users with some locales may need a dot:
> Figure 1`.` blah blah
instead of colon:
> Figure 1`:` blah blah

**Comment by yihui** [comment]
@upton9265 Sorry, the colon was left out by accident. I just added it back. Thanks for the report!
