### ISSUE TITLE
Cross-referencing syntax

### ISSUE THREAD

**Issue by dmenne** [rstudio/bookdown#62]
I just converted a large report from rmarkdown with css figure/caption numbering (rstudio/rmarkdown#522) to bookdown::html_document2. This worked nicely; great feature.

I am not so happy about the latex-lookalike syntax for cross-referencing. Since more than 3 year, there has been an inofficial standard in pandoc which needs some clumsy postprocessing, but worked once you got the setup done:

https://github.com/lierdakil/pandoc-crossref

**Comment by yihui** [comment]
So you mean you prefer the syntax `[@fig:label]`? I intentionally chose the "weird" syntax `\@ref(fig:label)` to make sure it is rare enough for users to type this accidentally, and avoid possible clashes with the citation syntax.

**Comment by dmenne** [comment]
I remember a discussion with you long ago that you wanted to get rid of \Sweave - like expression. At that time, my preference was to keep the old eggshells, but in the long run you were right to remove it.

Probably I still do not understand how I can get 
See _Fig. 1_  Italics should be marked as link

or 

As was noted in the _Introduction_  (gives me "As was noted in 1.1")
The suggested 
`
![Caption](file.ext){#fig:label}
`
has all that, and it could be pandoc compatible

**Comment by yihui** [comment]
You don't need the explicit `{#fig:label}` after `![]()`. Figure labels are generated automatically from chunk labels, and you only need to reference them: http://rstudio.github.io/bookdown/figures.html

If you have a figure that is not generated from R, use `knitr::include_graphics()` in a code chunk instead of writing `![]()`.

**Comment by dmenne** [comment]
I know... knitr user since 20 feeled years! Check the pandoc thread for details.

This was about generalized cross-references, and the suggested syntax allows to separate the link text, e.g. _Introduction_ instead of 1.1. Same concept as in url links.

**Comment by yihui** [comment]
For now the link is only added to the reference number.

For section references, you can just use the native Pandoc syntax `[Introduction]` (see #6). For figures/tables, `\@ref(label)` does not automatically generate the prefix Figure/Fig./Table/..., and you have to type them by hand, e.g. `Figure \@ref(label)`. I think this is trivially easy, and personally I don't see the significant value of generating these prefixes automatically. You may argue that sometimes you want to switch from `Figure` to `Fig.`, and that is a valid argument, but I'd just say sorry for now -- I don't have a plan to support that yet. It is likely that we will add this feature in the future, as more users request for it.

**Comment by dmenne** [comment]
Ok, I see I was still not clear. When you generate the Fig. by hand, only the number is the link.

**Comment by schzcas** [comment]
@yihui 

Relating to this issue. I am trying to add a PNG image with a caption and have a reference label.

My first try was:
```
![Figure 1. Lorem ipsum dolor sit amet, est lorem verear te, graeco meliore suavitate sea ne. 
](figures/Figure1.png)
````

But I want to use a reference like this one:
```
\@ref(fig:Figure1).
```

My idea is to have a link-reference when I am refereing to this image
Where I can add the "fig:Figure1" reference?


Me second try was:

```{r Figure1, fig.cap= "Lorem ipsum dolor sit amet, est lorem verear te, graeco meliore suavitate sea ne. ", fig.retina = NULL}
knitr::include_graphics("figures/Figura1.png")
```

But when I use this code function the following chunk is shown  with the image. 

```
knitr::include_graphics("figures/Figura2.png")
```

1. How can I display a simple Image, add a caption and have a reference  in that caption. 
2. Can you detail more deeply section "2.2.4 Text references"?

**Comment by yihui** [comment]
@schzcas 

1. Use `echo=FALSE` to hide the R code, and only show the image;
2. I don't know what is unclear in 2.2.4. Basically you define a label followed by some text, e.g.

```
(ref:lorem) Lorem ipsum dolor sit amet, est lorem verear te, graeco meliore suavitate sea ne. 
```

Then you can use

    ```{r fig.cap="(ref:lorem)"}

instead of writing the full caption

    ```{r fig.cap="Lorem ipsum dolor sit amet, est lorem verear te, graeco meliore suavitate sea ne. "}

Does that make sense now?

**Comment by yimingli** [comment]
@yihui In the [text reference](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references) section of the bookdown book, I found "Then you can use `(ref:foo)` in your figure/table captions". So I used `fig.cap=(ref:foo)` without the double quotes, it didn't work, and I can't find an example in the book. I found an example here in your comment. It may be helpful to include an example for text referencing in the book for newbies like me. Thanks Yihui!

**Comment by yihui** [comment]
@yimingli Good suggestion. I'll add an example. Thanks!

**Comment by schzcas** [comment]
Thanks @yihui !
Excellent suggestion @yimingli !

**Comment by yasirs** [comment]
@schzcas You can add the label in the figure caption as

```
![Figure 1. Lorem ipsum dolor sit amet, est lorem verear te, graeco meliore suavitate sea ne.(\#fig:your-label)](figures/Figure1.png)
```
and then refer to it as `\@ref(fig:your-label)`.
