### ISSUE TITLE
Improperly centered equations from tufte_html_book

### ISSUE THREAD

**Issue by tchufnagel** [rstudio/bookdown#623]
Using bookdown with the Tufte format, HTML output (using tufte_html_book) does not properly center equations — they span the entire page, rather than the main text column. Similarly, the equation number is set all the way to the right of the page, instead of to the right of the main text column. The same problem does not appear in PDF output from the same source (using tufte_book2). A minimal example is attached as a zip file.

[fred.zip](https://github.com/rstudio/bookdown/files/2332580/fred.zip)

Session information appears below:

> devtools::session_info('bookdown')
Session info ----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.456)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-08-29                  

Packages --------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                           
 backports   1.1.2   2017-12-13 CRAN (R 3.5.0)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.5.0)                   
 bookdown    0.7.17  2018-08-29 Github (rstudio/bookdown@4f9d73d)
 digest      0.6.16  2018-08-22 CRAN (R 3.5.1)                   
 evaluate    0.11    2018-07-17 CRAN (R 3.5.0)                   
 glue        1.3.0   2018-07-17 CRAN (R 3.5.0)                   
 graphics  * 3.5.1   2018-07-05 local                            
 grDevices * 3.5.1   2018-07-05 local                            
 highr       0.7     2018-06-09 CRAN (R 3.5.0)                   
 htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)                   
 jsonlite    1.5     2017-06-01 CRAN (R 3.5.0)                   
 knitr       1.20    2018-02-20 CRAN (R 3.5.0)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)                   
 markdown    0.8     2017-04-20 CRAN (R 3.5.0)                   
 methods   * 3.5.1   2018-07-05 local                            
 mime        0.5     2016-07-07 CRAN (R 3.5.0)                   
 Rcpp        0.12.18 2018-07-23 CRAN (R 3.5.0)                   
 rmarkdown   1.10    2018-06-11 CRAN (R 3.5.0)                   
 rprojroot   1.3-2   2018-01-03 CRAN (R 3.5.0)                   
 stats     * 3.5.1   2018-07-05 local                            
 stringi     1.2.4   2018-07-20 CRAN (R 3.5.0)                   
 stringr     1.3.1   2018-05-10 CRAN (R 3.5.0)                   
 tinytex     0.7     2018-08-22 CRAN (R 3.5.1)                   
 tools       3.5.1   2018-07-05 local                            
 utils     * 3.5.1   2018-07-05 local                            
 xfun        0.3     2018-07-06 CRAN (R 3.5.0)                   
 yaml        2.2.0   2018-07-25 CRAN (R 3.5.0)                   
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.29; using libpng 1.6.29
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 3.04

**Comment by cderv** [comment]
Hi, 

thanks for your patience and for the reprex. It seems this has been fixed already as running your code with last versions of packages does not show the issue.
