### ISSUE TITLE
bookdown doesn't apply YAML parameters in browser, but does in RStudio preview

### ISSUE THREAD

**Issue by DanielReedOcean** [rstudio/bookdown#624]
This question has sat for a week at [Stackoverflow](https://stackoverflow.com/questions) without a single comment, so I will also post it here. The original question can be found [here]( https://stackoverflow.com/questions/52044706/bookdown-doesnt-apply-yaml-parameters-in-browser-but-does-in-rstudio-preview). I have also tried updating to the development version of `bookdown`, but that hasn't solved the problem either. Below, I have included a minimal, self-contained, and reproducible example of the problem with screenshots. I have also uploaded a zip file containing the files I used in this example [here](https://github.com/rstudio/bookdown/files/2348364/Book_test.zip).

I have a `bookdown` book that comprises of two files: `index.Rmd` and `01-intro.Rmd`. These files contain the following, respectively:

> index.Rmd

    --- 
    title: "Book"
    author: "User"
    date: ""
    site: bookdown::bookdown_site
    documentclass: book
    output:
      bookdown::gitbook:
        config:
          toc:
            collapse: section
          fontsettings:
            theme: white
            family: serif
            size: 2
    ---
    
    # First
    This is a book.

> 01-intro.Rmd

    # Second
    
    ## Second point one
    Stuff.
    
    ## Second point two
    
    Things.

I build my book to produce the following in RStudio preview:

[![enter image description here][1]][1]

There are two things worth noting: 1) collapsed table of contents and 2) serif font. Now, I click `Open in Browser` and I get the following in my default browser (Chrome):

[![enter image description here][2]][2]

Note: sans serif font and an expanded table of contents. Hmmm. I wondered if this is browser specific, so opened the book in Internet Explorer and got exactly the same results. Why are my YAML parameters discarded when viewed with a browser? Is this issue unique to my setup or can others replicate the problem?

----

> \> devtools::session_info('bookdown')
> Session info ----------------------------------------------------------------------------------------------------------------------------------------
>  setting  value                       
>  version  R version 3.5.1 (2018-07-02)
>  system   x86_64, mingw32             
>  ui       RStudio (1.1.442)           
>  language (EN)                        
>  collate  English_Canada.1252         
>  tz       America/Curacao             
>  date     2018-09-04                  
> 
> Packages --------------------------------------------------------------------------------------------------------------------------------------------
>  package   * version date       source                           
>  backports   1.1.2   2017-12-13 CRAN (R 3.5.0)                   
>  base64enc   0.1-3   2015-07-28 CRAN (R 3.5.0)                   
>  bookdown    0.7.17  2018-08-28 Github (rstudio/bookdown@4f9d73d)
>  digest      0.6.16  2018-08-22 CRAN (R 3.5.1)                   
>  evaluate    0.11    2018-07-17 CRAN (R 3.5.1)                   
>  glue        1.3.0   2018-07-17 CRAN (R 3.5.1)                   
>  graphics  * 3.5.1   2018-07-02 local                            
>  grDevices * 3.5.1   2018-07-02 local                            
>  highr       0.7     2018-06-09 CRAN (R 3.5.1)                   
>  htmltools   0.3.6   2017-04-28 CRAN (R 3.5.1)                   
>  jsonlite    1.5     2017-06-01 CRAN (R 3.5.1)                   
>  knitr       1.20    2018-02-20 CRAN (R 3.5.1)                   
>  magrittr    1.5     2014-11-22 CRAN (R 3.5.1)                   
>  markdown    0.8     2017-04-20 CRAN (R 3.5.1)                   
>  methods   * 3.5.1   2018-07-02 local                            
>  mime        0.5     2016-07-07 CRAN (R 3.5.0)                   
>  Rcpp        0.12.18 2018-07-23 CRAN (R 3.5.1)                   
>  rmarkdown   1.10    2018-06-11 CRAN (R 3.5.1)                   
>  rprojroot   1.3-2   2018-01-03 CRAN (R 3.5.1)                   
>  stats     * 3.5.1   2018-07-02 local                            
>  stringi     1.1.7   2018-03-12 CRAN (R 3.5.0)                   
>  stringr     1.3.1   2018-05-10 CRAN (R 3.5.1)                   
>  tinytex     0.7     2018-08-22 CRAN (R 3.5.1)                   
>  tools       3.5.1   2018-07-02 local                            
>  utils     * 3.5.1   2018-07-02 local                            
>  xfun        0.3     2018-07-06 CRAN (R 3.5.1)                   
>  yaml        2.2.0   2018-07-25 CRAN (R 3.5.1)                   
> \> rmarkdown::pandoc_version()
> [1] ‘1.19.2.1’
> \> system('pdflatex --version')
> \> 

I am not able to update RStudio or R, as my employer manages my versions.

  [1]: https://i.stack.imgur.com/NBPu0.png
  [2]: https://i.stack.imgur.com/XVQOA.png

**Comment by notZaki** [comment]
I tried to replicate the problem and the YAML configuration appeared correctly in both RStudio and Chrome.

My guess is that your system has Javascript disabled for the web browsers, and that is preventing the YAML configuration from being applied. That would also explain why the web browsers did not show the top menu--the one with the text options and social media icons.  
The steps to enable/disable Javascript in Chrome are [mentioned in this post](https://productforums.google.com/forum/#!msg/chrome/BYOQskiuGU0/5PRO2P-1WWwJ)

**Comment by DanielReedOcean** [comment]
Thanks for the reply. Checking my settings in Chrome, Javascript is enabled:
![javascript](https://user-images.githubusercontent.com/11167566/45089538-dbb57580-b0e2-11e8-9f89-09278d6364cf.PNG)

**Comment by notZaki** [comment]
In that case, try `bookdown::serve_book()` in R/RStudio and then enter the url in the web browser--something like `http://127.0.0.1:####`. 

I tried to reproduce the problem in other web browsers and was able to replicate it with Internet Explorer and Microsoft Edge--opening a local HTML did not show the top menu but online books did. Safari [probably has this issue too.](https://github.com/rstudio/bookdown-demo/issues/33) 
Chrome, Firefox and Opera seem to show the local HTML correctly. 
Firefox even has the strange advantage that the search function works on local files (#353), so it might be worth a shot to try Firefox if you don't want to use `serve_book()`.

**Comment by DanielReedOcean** [comment]
That's interesting: when I use `bookdown::serve_book()` and copy-and-paste the URL into a browser, like you suggest, then it renders correctly in both Internet Explorer and Chrome – tool bar, serif font, and collapsed table of contents. Do you know why local files would render incorrectly, but server files would look fine?
