### ISSUE TITLE
Allow `stdout` and `stderr` to be redirected when serve_book renders the book in a new session

### ISSUE THREAD

**Issue by hammer** [rstudio/bookdown#633]
I would like to pass the `stdout` and `stderr` arguments to the call to `Rscript` within `serve_book` (when `in_session` is set to `FALSE`) so that I don't get console spew every time I make a change to my book.

**Comment by yihui** [comment]
Done. Thanks for the suggestion!

```r
bookdown::serve_book(quiet = TRUE)
```
