### ISSUE TITLE
Maybe clean_book() should not delete .nojekyll?

### ISSUE THREAD

**Issue by jennybc** [rstudio/bookdown#636]

**Comment by yihui** [comment]
I cannot reproduce it. I used the demo project https://github.com/rstudio/bookdown-demo.

```r
> file.create('.nojekyll')
[1] TRUE
> bookdown::clean_book(T)
> file.exists('.nojekyll')
[1] TRUE
```

If `.nojekyll` is deleted, the only possibility I can think of is that you explicitly configured **bookdown** to delete it: https://bookdown.org/yihui/bookdown/configuration.html (the `clean` option).

**Comment by jennybc** [comment]
In my case, I'm rendering the book into `docs/`. So that's where the `.nojekyll` file is and it is deleted every time I run `clean_book()`.

**Comment by yihui** [comment]
In that case, you can call `dir.create('docs', F); file.create('docs/.nojekyll')` in any code chunk to make sure this file is always created. `clean_book()` is agnostic about the particular website backend such as Jekyll or Github, and basically just cleans up the whole output directory.

**Comment by jennybc** [comment]
OK. I have auto-build and deploy setup now, so this is less of an issue for me.
