### ISSUE TITLE
Is `\@ref` syntax only exclusive to `bookdown` at the moment?

### ISSUE THREAD

**Issue by ultinomics** [rstudio/bookdown#64]
I've enjoyed the `\@ref` feature for referencing tables and figures. I noticed, however, that this seems exclusive to `bookdown`. Is that the case?

Is there anyway to have this same referencing syntax across *any* .Rmd? I would love to use it in a .Rmd I'm currently writing with `output: html_document`!

Apologies as I know that this is not exactly an issue with `bookdown` but more of a request to have this feature extended to any `rmarkdown` document.

**Comment by yihui** [comment]
Yes it is exclusive to bookdown for now, because it is more or less a hack, although I believe it should work reasonably well.

However, I do have good news for you: simply change `html_document` to `bookdown::html_document2`, and enjoy the magic :)

**Comment by ultinomics** [comment]
Haha I wish I saw this hours ago. I made my own hack using `pandoc-tablenos`! But glad to switch to your hack. Thanks Yihui!

```
## Print Table
printTable <- function(tbl, label=NULL, new=FALSE) {
    stopifnot(!is.null(label))
    if(!is.null(label)) stopifnot(inherits(label, 'character'))
    assignCount(tbl, kind='table', new=new)
    num <- length(tableCount)
    tableCount[num] <- label
    cap <- paste0(attr(tbl, "caption"), " {#tbl:", label,"}")
    kable(tbl, caption=cap)
}

## reference Table
refTable <- function(label) {
    I(paste0("@tbl:", label))
}
```
