### ISSUE TITLE
comment colours inconsistent

### ISSUE THREAD

**Issue by AJABADI** [rstudio/bookdown#643]
Hi,
Thank you for the great work.

The comments in my book are coloured inconsistently.

[Here's the code](https://github.com/AJABADI/MINT_sPLSDA/blob/master/01-Data-Integration.Rmd), and [here is the bookdown page](https://ajabadi.github.io/MINT_sPLSDA/data-integration-with-mint.html#pca-on-the-combined-dataset). Sometimes, the code is back and sometimes blue while I have used a consistent code comment format. It happens both with RStudio preview and GitHub pages.

Thanks

**Comment by r-cheologist** [comment]
On Thu, 2018-10-04 at 23:58 -0700, Al J Abadi wrote:
> Hi,
> Thank you for the great work.
> The comments in my book are coloured inconsistently.
> Here's the code, and here is the bookdown page. Sometimes, the code
> is back and sometimes blue while I have used a consistent code
> comment format. It happens both with RStudio preview and GitHub
> pages.
> Thanks

Just a quick note without checking compilation myself: all the black
comments appear to have leading double hashes ('##') and all the blue
ones a single one ('#') - have you checked whether that may be the
source of the apparent inconsistency?

Joh

**Comment by yihui** [comment]
This seems to be a bug in Pandoc 2.2.1, which has been fixed in 2.3.1. I have requested RStudio to upgrade the bundled version of Pandoc: https://github.com/rstudio/rstudio/issues/3601 Before that happens, you may either use a single hash `#` for comments, or upgrade Pandoc by yourself: https://pandoc.org/installing.html Thanks!

**Comment by yihui** [comment]
RStudio will bundle Pandoc 2.3.1 in the future. You may test the daily build later today or tomorrow: https://dailies.rstudio.com

**Comment by AJABADI** [comment]
Thanks for the tip. I updated pandoc and now it works fine. Is there a way to change the default comment color in pandoc?
