### ISSUE TITLE
Conditional compilation of chunks breaks on Travis

### ISSUE THREAD

**Issue by hammer** [rstudio/bookdown#649]
I tried to add a cover image to the bookdown demo over at https://github.com/hammer/test-book/issues/2 and was surprised to see that the image worked in a local build but not on Travis.

After a bit of debugging, it turns out Travis doesn't like the use of `knitr:::pandoc_to()` as recommended in [issues](https://github.com/rstudio/bookdown/issues/168#issuecomment-238001368) and [examples](https://github.com/rstudio/bookdown/blob/master/inst/examples/index.Rmd#L43).

I haven't gotten around to debugging just why this triple colon operator behaves differently on my local machine versus on Travis, but I thought it might be worth noting this issue for future users.

I also think a non-private interface to allow for conditional compilation would be a good idea. Is there a reason some of the functions like `is_html_output` are in `utils.R` and not exported by `knitr`?

**Comment by yihui** [comment]
`is_html_output()` and `is_latex_output()` have been exported in **knitr** in 2017: https://github.com/yihui/knitr/releases/tag/v1.18

Examples: https://bookdown.org/yihui/rmarkdown-cookbook/latex-html.html

Thanks!
