### ISSUE TITLE
\@ref(xxx) is not recognized within parenthesis

### ISSUE THREAD

**Issue by aronatkins** [rstudio/bookdown#65]
I was building a checklist and including some section references. Something like:

```
1. Do this thing (\@ref(thing-section))
1. More complicated (\@ref(complicated-section), \@ref(complicated-details))
```

The `\@ref` is not recognized when adjacent to a left-paren. Workaround is to avoid this combination of characters.

One note: I was using b14f9edf907d9b5af8f82cbcae294b6859eda632 at the time.

**Comment by yihui** [comment]
Should be fixed now. Thanks!
