### ISSUE TITLE
HTML search only works by section?

### ISSUE THREAD

**Issue by dsblank** [rstudio/bookdown#657]
When I search in an HTML book created by bookdown, I can only move (up/down arrows) through matches  in that section. Is that by design? I have to click on each section to search them? 

Example book:
https://jupyter4edu.github.io/jupyter-edu-book/#

Description of problem:
https://github.com/jupyter4edu/jupyter-edu-book/issues/102

**Comment by yihui** [comment]
Yes, it is by design: https://bookdown.org/yihui/bookdown/html.html (with an emphasis added to the last phrase)

> The second button on the toolbar is the search button. Its keyboard shortcut is F (Find). When the button is clicked, you will see a search box at the top of the sidebar. As you type in the box, the TOC will be filtered to display the sections that match the search keyword. Now you can use the arrow keys Up/Down to highlight the next keyword _on the current page_.

**Comment by dsblank** [comment]
Ok, thanks for the quick feedback!

This creates some confusion, even with me, when there is only one match on that page. The highlighted word changes a bit, but nothing happens. The UI is pretty non-standard.

How difficult would it be to make it automatically move to the next match, even if it is on another page?

**Comment by yihui** [comment]
Probably not super difficult (I guess it would be one hour's work to me):
https://github.com/rstudio/bookdown/blob/7a0364b7ffd16b360b7abde36a29a8801675906c/inst/resources/gitbook/js/plugin-search.js#L183-L191

Basically when you reach the last word, you redirect to the next page (you can find its href from the TOC) via `location.href = ...`. Please free free to hack at it and submit a PR :) Thanks!

**Comment by dsblank** [comment]
Thanks for the hints! Perhaps someone who has some time soon could get inspired. I don't speak JS too well.

**Comment by yihui** [comment]
Okay, I've marked this issue with `help wanted`, and hope someone else could help.

**Comment by pyltime** [comment]
+1 for this request - we use bookdown for our RStudio admin guides (docs.rstudio.com) and not being able to easily move through the search the entire document at once makes it much more difficult to find a specific section, especially if you're not sure what section it might be in.

**Comment by aronatkins** [comment]
Related: #696 would show only the matching TOC sections (only chapters today).
Related: #660 would make UI for prev/next actions and not require users to "know" that up/down is a thing.

**Comment by yihui** [comment]
Should be fixed now. You can keep pressing Up/Down/Enter in the search box, and it will jump to the previous/next page that contains the match when necessary. These keybindings are no longer restricted to the current page. Thanks for the feedback!

**Comment by dsblank** [comment]
Great! Thank you for all of your work! Much appreciated!

**Comment by sriramab** [comment]
I was wondering if I can limit the search to a certain section level ? eg... limit search to # or ## or ###. Because I am writing a manual (600pages) for a software and i would like to limit the search to a certain section level, so that reader can search keywords, methods and not really all available text.

**Comment by yihui** [comment]
@sriramab Sorry, but there is no way to limit the search to a certain part of the book. Do you mean searching the whole book is too slow in your case?

**Comment by jedbrown** [comment]
I just tested this (Firefox 66.0.3) and when the search advances to the next page, focus leaves the search box so that keybindings stop working until I click or otherwise get back to the search box. How hard would that be to fix?

**Comment by sriramab** [comment]
@yihui , may be i was not clear. I state a simple example here. 
When I search for Yihui, I want results only from the pages that find Yihui text found in (upto) ### depth and not from all the pages that contain Yihui word in normal paragraphs.  So in the example below, i would like 3 results (## and ### depth) and not 6 results (that includes 3 more yihui in the normal paragraphs)

So my question is:

it is currently possible to search whole document (entire text , all words) with no search restriction. I was thinking if only # or ## or ## (sub section headings ) can be searched? So search for the queried string only in the headings, with a user specified depth of headings.

My meaning of depth is : depth 1 (#) depth 2 (##) depth 3(###) etc.
 
Rmd document 


```
# Chapter of Algorithms

## CRAN-R algorithms

## Yihui related algorithms

### Yihui Algorithm
--one page with no yihui--
--second page with no yihui --
Yihui Algorithm can efficiently calculate 
--fourth page with no yihui--

### sriramab algorithm
This uses _Yihui_ algorithm to generate..........

### Markdown algorithm
blah blah... blah... It combines _Yihui_ algorithm with rstudio algorithm 

## Microsoft R algorithms

### Azure-Yihui algorithm
```


Output html


# Algorithms

## CRAN-R algorithms

### Yihui Algorithm
--one page with no yihui--
--second page with no yihui --
Yihui Algorithm can efficiently calculate 
--fourth page with no yihui--

### sriramab algorithm
This uses _Yihui_ algorithm to generate..........

### Markdown algorithm
blah blah... blah... It combines _Yihui_ algorithm with rstudio algorithm 

## Microsoft R algorithms

### Azure-Yihui algorithms

**Comment by yihui** [comment]
@jedbrown I cannot reproduce your issue with Firefox 66.0.3 or Google Chrome on macOS. I rebuilt the **bookdown** book with the current dev version of **bookdown**: https://bookdown.org/yihui/bookdown/ I can keep on pressing Down; when it goes to the next page, the search box will be automatically on focus.

**Comment by yihui** [comment]
@sriramab Okay, now I see what you meant. That is currently not possible. However, if you only want to search within headers, you may just use the `Find` menu of your browser (the keyboard shortcut is often <kbd>Ctrl/Cmd + F</kbd>), because all headers are available in the sidebar by default.

**Comment by jedbrown** [comment]
@yihui Ah, it works once I deploy, but not for a `file://` on my system. Thanks.

**Comment by yihui** [comment]
@jedbrown Searching requires a web server serving the book. One way to start a local book server is `bookdown::serve_book()`: https://bookdown.org/yihui/bookdown/serve-the-book.html
