### ISSUE TITLE
How do I reference a static value that is defined after it is used?

### ISSUE THREAD

**Issue by MCM-Math** [rstudio/bookdown#659]
I noticed that there are references to sections and footnotes, but I am wondering how I do the reference in general.  For example:

I want to reference a flextable, but the typical captioning doesn't seem compatible with it, so I would like to have a separate counter be entered into something like ``[ `r nextTable()` ][tableLabel] ``, where the value returned by nextTable() (say, "Table 2.4"), would be referenced by tableLabel, so something like `` \@ref(tableLabel) `` would return "Table 2.4".  I can do this in R, but not for references made before the creation of the table.  Since Markdown does allow for similar references for sections and footnotes, is there something more general and open-ended that could be done for the flextable example I mentioned?

**Comment by atusy** [comment]
Hi, for the flextable, this feature is implemented in davidgohel/flextable#205 and is merged to the master branch.
See davidgohel/flextable#205 for the reproducible example.
Is this what you need?
