### ISSUE TITLE
Formatting of the last element before a new section gets distorted in a GitBook.

### ISSUE THREAD

**Issue by GegznaV** [rstudio/bookdown#662]
Formatting of the last element in the chapter before a new section gets distorted in a GitBook. I used the same project as in #661, thus session information is the same. To reproduce the problem: 

1. Open minimal bookdown example in RStudio.
2. Create file `01.Rmd` with contents: `# (PART\*) Section {-}`.

![image](https://user-images.githubusercontent.com/12725868/49829009-02481400-fd96-11e8-9ebb-3c0f837a5b7a.png)

3. Build a GitBook.
4. Scroll to the end of Chapter 2, whis is before the new section:

![image](https://user-images.githubusercontent.com/12725868/49828762-56062d80-fd95-11e8-962c-5341a182a15e.png)

If the section (`01.Rmd`) is removed, the formatting of the element is correct:
![image](https://user-images.githubusercontent.com/12725868/49829186-6e2a7c80-fd96-11e8-9470-f8fe64c77ba5.png)

**Comment by yihui** [comment]
Since you have already got the reproducible example in your hands, why not upload it as a zip file here? That way, I don't have to repeat the work that you have already done by following your steps: https://yihui.name/en/2018/06/copy-and-run/ Thanks!

**Comment by GegznaV** [comment]
The project: [bookdown-issue-661--section-distortions.zip](https://github.com/rstudio/bookdown/files/2671226/bookdown-issue-661--section-distortions.zip)
At first, please, investigate contents of folder "_book" and compare the lists of references in Chapter 1 and Chapter 2.

**Comment by GegznaV** [comment]
Any news on solving this issue? @RLesur Maybe you have time to look into this?

**Comment by RLesur** [comment]
@GegznaV I had a quick look. My problem is that I do not understand your use case and your goal.

> 2\. Create file `01.Rmd` with contents: `# (PART\*) Section {-}`.

Why do you need this file with such a content?  
If I do not create this file and insert `# (PART\*) Section {-}` as the first line of `02-literature.Rmd`, the gitbook seems to be correct.

**Comment by cderv** [comment]
Thank you all for your patience! 

This is indeed a current limitation of **bookdown** design that we have now documented better: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers

> A part title should be written right before the first chapter title in this part, **both title in the same document**.

So the advice is to do as said in https://github.com/rstudio/bookdown/issues/662#issuecomment-537375899 : the special header must be set in the same document as the first chapter. 

We know that this would be a limitation when writing a book and the chapter order will change. In that case you would like to have your part section on their own. It happened sometimes and it is a special case so it is why we will track this issue in https://github.com/rstudio/bookdown/issues/974 
but that is not an easy thing to change I think and it feels like adding the special header in the chapter file is a easy to do. Please give a 👍  to the other issue if it matters for you. 

Thank you.
