### ISSUE TITLE
Provide easier way to access latex log file

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#663]
The only way I could find to capture the log file was this hack:

```R
options("bookdown.post.latex" = function(x) {
  xfun::write_utf8(parent.frame()$x, parent.frame()$f)
  tinytex::latexmk(f, "xelatex", clean = FALSE)
  file.copy("_main.log", "latex.log")
  x
})
```

I wanted needed this to find broken references, so I'd also be happy to accept any solution that made it easier to check that I hadn't cross-referenced a section that didn't exist.

**Comment by yihui** [comment]
I'll work on this in the tinytex package. When there are broken cross-references, I guess I shouldn't delete the log file, and perhaps should also parse the log to warn against these references in R. Thanks for the suggestion!

**Comment by hadley** [comment]
I think it might be reasonable to never delete the log file?

**Comment by yihui** [comment]
Yeah, that sounds like a good idea, too.

**Comment by yihui** [comment]
Should be fixed now via

```r
devtools::install_github('yihui/tinytex')
```
