### ISSUE TITLE
Figure numbering with knitr::include_url()

### ISSUE THREAD

**Issue by cpsievert** [rstudio/bookdown#664]
Currently if I do the following:

````
Figure \@ref(fig:vimeo) has nice things.

```{r vimeo, fig.cap="A figure caption"}
knitr::include_url("https://player.vimeo.com/video/257149623")
```
````

The Figure numbering doesn't appear to work:

<img width="785" alt="screen shot 2018-12-20 at 12 17 43 pm" src="https://user-images.githubusercontent.com/1365941/50304640-1951ca80-0456-11e9-8182-5c8e182b5650.png">

I suppose this is something that needs to be implemented at the **knitr** level? I'd be happy to work on a PR if you can point me in the right direction!

**Comment by yihui** [comment]
Yes, the implementation is in **knitr**. See the source code of `include_url()` there, and perhaps there is a certain S3 method for `wrap()`. I won't have time before rstudio::conf. If you can figure it out, a PR is welcome; otherwise I could take a look after the conference.

**Comment by cpsievert** [comment]
Ohhh, it looks like it is already has support! 

When I was testing this out, I added the example above to the bottom of https://github.com/yihui/bookdown-crc/blob/master/index.Rmd, but it appears as though figure numbering generally isn't supported in the `index.Rmd` file -- when I put it in an actual chapter file it works.

Sorry for the noise.
