### ISSUE TITLE
suggestions for a publishing process with two target formats

### ISSUE THREAD

**Issue by topepo** [rstudio/bookdown#667]
We are in the final stages of writing our book using `bookdown`. We'll have both [HTML](https://bookdown.org/max/FES)  and LaTeX versions. 

Do you have any input on the sequence of events at the end of the cycle? The process that I see happening is:

 * Finalize `Rmd` files of main content
 * Build a "raw" pdf/LaTeX version to send for copyediting
 * Update the `Rmd` with copyediting changes.
 * Make a branch for the final LaTeX files. In that branch
   * Add `\index` commands
   * "Optimize" the LaTeX (e.g. figure positions, aesthetics, etc). 
   * Build the publisher's final version here

Is this the best sequence of events? 

My only thought about this is for a potential 2nd edition. We would have to re-do the indexing commands for a new version. Maybe a GH merge would make that happen cleanly but I doubt it. Keeping the custom LaTeX parts sequestered in a different branch is  probably a better approach than contaminating the `Rmd` files with LaTeX indexing bits and other nuances.

**Comment by yihui** [comment]
I just add `\index{}` to the master branch. There is no need to make a separate branch for that because `\index{}` will be ignored in HTML output.

Everything else sounds good to me.

**Comment by topepo** [comment]
Thanks! 

I was aware that it would ignore the commands. I'm not sure if the tradeoff between having extra tex crud in the Rmd was better than having those confined to a different branch.
