### ISSUE TITLE
Feature request: new gitbook format

### ISSUE THREAD

**Issue by sbihorel** [rstudio/bookdown#670]
Hi,

The nice people at Gitbook have release a new format (with an improved TOC sidebar in particular): https://docs.gitbook.com/

This is probably a big endeavor, but I was wondering if this new format could be implemented in a future version of gitbook.

Thanks

**Comment by olafghanizadeh** [comment]
Unless one can get the source CSS and HTML (JS)  templates from GitBook, it would have to be recreated from scratch

**Comment by cderv** [comment]
Hi, 

Thanks for your patience and your suggestion.

We won't be able to provide the new gitbook V2 as this is another product than the V1 we used; and it is only cloud based and closed source I believe. 

However, if you need new features, please open individual features request with what is missing in **bookdown** formats. 

Also, we are providing new book format like recently `bookdown::bs4_book()` that you can find in dev version of **bookdown**. See example of books using it: https://mastering-shiny.org/
This new format is the one to use if you want new TOC sidebars for example.

Thank you for your suggestion.
