### ISSUE TITLE
Cross referencing in fig.cap

### ISSUE THREAD

**Issue by sw2000** [rstudio/bookdown#678]
Not sure if an issue, but it is something I couldnt find a solution mentioned elsewhere, and I couldnt see it mentioned in the bookdown manual. When using \\@ref in a fig.cap, knitting fails due to 'it is likely that you forgot to quote "character" options' and 'Error: '\\@' is an unrecognized escape in character string starting.......'. If you use \\\@ref, it renders fine with no error. 

````
---
title: "Minimal example"
output:
  bookdown::word_document2
---

```{r fig1, fig.cap="minimal example. see also Figure \@ref(fig:fig2)"}
# this chunk will render if you use \\@ref in the figure caption instead
plot(1,1)
```

```{r fig2, fig.cap="minimal example"}
plot(1,2)
```
````

**Comment by yihui** [comment]
You should take advantage of text references in this case: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references
