### ISSUE TITLE
Format of formattable::as.datatable breaks when compiled as gitbook with bookdown

### ISSUE THREAD

**Issue by chrisdane** [rstudio/bookdown#684]
Hi

This is copy paste from my [unanswered SO post](https://stackoverflow.com/questions/54597176/format-of-formattableas-datatable-breaks-when-compiled-as-gitbook-with-bookdow). I just updated the package versions at the end.

I want to include a `ft <- formattable::formattable(...)` into a `gitbook` via `formattable::as.datatable(ft)`. However, `bookdown::render_book()` somehow breaks the format of that table.

I need the table as an `datatable` object since this enables the user to sort the table according to the values in the columns in the final html document. Furthermore, I would like to use the `formattable` features to visualize the values as bars in the background of the table elements from left to right. 

Please see this minimal example `index.Rmd`:

````
---
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
---

# Hello World

```{r echo=F}
df <- data.frame(type=letters[1:3], val=c(1, 0.007, 0.001))
library(formattable)
ft <- formattable::formattable(df, list(
            val=formattable::formatter("span",
                  style=function(x) {
                      formattable::style(display="inline-block",
                                direction="ltr",
                                "border-radius"="4px",
                                "background-color"="#b8dff3",
                                width=formattable::percent(x))
                                     })))
formattable::as.datatable(ft, options=list(dom='t'))
```
````

When I run the last line of this code, `formattable::as.datatable(ft, options=list(dom='t'))`, in the R terminal, the table looks exactly as I want it:
![correct table](https://i.imgur.com/Qt5bnSr.png)
Note the very small blue background bars from left to right in the 2nd and 3rd rows which is perfect since 0.007 and 0.001 are much smaller than 1.0.

In the gitbook, which I compile via `bookdown::render_book("index.Rmd", "bookdown::gitbook")`, the table looks like this:
![wrong table](https://i.imgur.com/u1tOW5n.png)

Somehow `render_book()` tries to fit the long character string `0.001` into the very short background bar of `formattable::formattable()`.

Thanks for any help!  
Chris

```{r}
R version 3.5.2 (2018-12-20)
bookdown    * 0.9.2   2019-03-02 [1] Github (rstudio/bookdown@cf3d5b2) 
formattable * 0.2.0.2 2019-02-08 [1] Github (renkun-ken/formattable@39e1e01)
rmarkdown::pandoc_version()
2.6
system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018/Arch Linux)
```

**Comment by yihui** [comment]
Sounds like a CSS issue, but I have no idea how to fix it. Sorry.

If all you want is the background bars, you may just try the **DT** package instead of converting **formattable** to **DT** because **DT** also supports background bars: https://rstudio.github.io/DT/functions.html
