### ISSUE TITLE
bookdown-demo Build Book fails unless tinytex is installed

### ISSUE THREAD

**Issue by ras44** [rstudio/bookdown#685]
Not sure if this would save someone else time, but it might be helpful to have something similar to the following in the getting started notes:
```
install.packages("tinytex")
library(tinytex)
tinytex::install_tinytex(force=TRUE)
```
In my case, building the book initially failed, but the discussion at https://github.com/yihui/tinytex/issues/102 hinted at the solution

**Comment by yihui** [comment]
The **tinytex** package is a required dependency of **bookdown**, so it should be automatically installed when you install **bookdown**.

https://github.com/rstudio/bookdown/blob/master/DESCRIPTION#L60

**Comment by ras44** [comment]
Thanks for your quick response.  Although the dependency means that the package is installed, I'm not sure if that ensures that the `tinytex::install_tinytex(force=TRUE)` command is run.  Running this command is what got things to work for me at least.

**Comment by yihui** [comment]
As I said at https://github.com/yihui/tinytex/issues/102#issuecomment-470132144, TinyTeX is recommended but not required. You can use other LaTeX distributions.

It is also mentioned in the bookdown-demo project: https://github.com/rstudio/bookdown-demo/blob/master/index.Rmd#L29

**Comment by ras44** [comment]
ok- thanks for your feedback!
