### ISSUE TITLE
Provide `latex_extension` option when compling PDF

### ISSUE THREAD

**Issue by hongyuanjia** [rstudio/bookdown#687]
In bookdown, basically, I want to preserve Chinese quotation marks in the PDF output. This is related to https://stackoverflow.com/questions/52052231/how-to-write-chinese-quotes-in-bookdown

The reason why adding `md_extensions: -smart` did not work is that in pandoc, `smart` extension is enabled for latex by default, no matter latex is the input or output.

```bash
pandoc --version
# pandoc 2.6
# Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.6
# Default user data directory: /home/hongyuanjia/.pandoc
# Copyright (C) 2006-2019 John MacFarlane
# Web:  http://pandoc.org
# This is free software; see the source for copying conditions.
# There is no warranty, not even for merchantability or fitness
# for a particular purpose.

pandoc --list-extensions=latex | grep "smart"
# +smart
```

So the only way to achieve this is to disable the `smart` extension both for markdown and latex.

```bash
echo "“”" | pandoc -f markdown-smart -t latex
# ``''

echo "“”" | pandoc -f markdown-smart -t latex-smart
# “”
```

However, in bookdown, the PDF is compiled using pandoc with only "-t latex", and there is no such `latex_extension` option to modify latex extension in pandoc.

**Comment by yihui** [comment]
Please try the dev version of **rmarkdown** (`remotes::install_github('rstudio/rmarkdown')`), in which I have added an argument `output_extensions`. Example usage:

```yaml
output:
  bookdown::pdf_book:
    md_extensions: -smart
    output_extensions: -smart
```

**Comment by hongyuanjia** [comment]
Thanks, @yihui. I can confirm that this has been fixed using the development version of rmarkdown.

**Comment by yihui** [comment]
Perfect. Thanks for letting me know!
