### ISSUE TITLE
bookdown0.9 in centos7.6 render the html files abnormal

### ISSUE THREAD

**Issue by wikithink** [rstudio/bookdown#688]
I use the bookdown:render_book function，the same rmd and yml files，the same R(3.5.1),the same rstudio server(1.1.463),the same lang is zh_CN.UTF-8,and the same rmarkdown:pandoc_version(1.19.2.1),the same knitr(1.21),with the centos 6.1 or 6.5,the output html files's head content(meta,og:title,content) is normal,but with the centos 7.6, the head content is abnormal: adding a | character before the content (specially the content is unicode like chinese,but english is normal.)
I copy the sessioninfo below,thanks.
The yaml info in index.Rmd is following:
```
title: "数据集质量探查与描述推断分析报告"
author: "DAAS"
date: "`r Sys.Date()`"
bibliography:
- book.bib
- packages.bib
description: 该分析报告基于岭束©DAAS平台的分析结果汇总而成
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
```

### centOS 6.5

sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
[1] LC_CTYPE=zh_CN.UTF-8 LC_NUMERIC=C
[3] LC_TIME=zh_CN.UTF-8 LC_COLLATE=zh_CN.UTF-8
[5] LC_MONETARY=zh_CN.UTF-8 LC_MESSAGES=zh_CN.UTF-8
[7] LC_PAPER=zh_CN.UTF-8 LC_NAME=C
[9] LC_ADDRESS=C LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats graphics grDevices utils datasets
[6] methods base

other attached packages:
[1] rprojroot_1.3-2 rmarkdown_1.11.9 knitr_1.21 bookdown_0.9.1
[5] RSQLite_2.1.1 gsubfn_0.6-6 proto_1.0.0 FSA_0.8.17
[9] TH.data_1.0-8 MASS_7.3-50 ggplot2_3.0.0 Formula_1.2-2
[13] survival_2.42-3 lattice_0.20-35 car_3.0-2 carData_3.0-1
[17] DT_0.2 RMySQL_0.10.15 DBI_1.0.0

loaded via a namespace (and not attached):
[1] Rcpp_0.12.18 rstudioapi_0.6
[3] magrittr_1.5
[5] splines_3.4.1 MASS_7.3-47
[7] lattice_0.20-35 minqa_1.2.4
[9] highr_0.6 stringr_1.4.0
[11] tools_3.4.1 parallel_3.4.1
[13] grid_3.4.1 nnet_7.3-12
[15] pbkrtest_0.4-6 nlme_3.1-131
[17] mgcv_1.8-17 xfun_0.4
[19] quantreg_5.34 MatrixModels_0.4-1
[21] htmltools_0.3.6 yaml_2.2.0
[23] lme4_1.1-12 digest_0.6.12
[25] Matrix_1.2-10 nloptr_1.0.4
[27] htmlwidgets_1.3 evaluate_0.10
[29] rmarkdown_1.11 stringi_1.3.1
[31] compiler_3.4.1 backports_1.0.4
[33] SparseM_1.77 jsonlite_1.5

the index.html's head:
```
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>数据集质量探查与描述推断分析报告</title>
<meta name="description" content="该分析报告基于岭束©DAAS平台的分析结果汇总而成">
<meta name="generator" content="bookdown and GitBook 2.6.7">
<meta property="og:title" content="数据集质量探查与描述推断分析报告" />
<meta property="og:type" content="book" />
<meta property="og:description" content="该分析报告基于岭束©DAAS平台的分析结果汇总而成" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content="数据集质量探查与描述推断分析报告" />
<meta name="twitter:description" content="该分析报告基于岭束©DAAS平台的分析结果汇总而成" />
<meta name="author" content="DAAS">
<meta name="date" content="2019-02-28">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="next" href="interpretation-and-suggestion.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />

<link rel="stylesheet" href="style.css" type="text/css" />
</head>
```
### centOS 7.6

sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
[1] LC_CTYPE=zh_CN.UTF-8 LC_NUMERIC=C
[3] LC_TIME=zh_CN.UTF-8 LC_COLLATE=zh_CN.UTF-8
[5] LC_MONETARY=zh_CN.UTF-8 LC_MESSAGES=zh_CN.UTF-8
[7] LC_PAPER=zh_CN.UTF-8 LC_NAME=C
[9] LC_ADDRESS=C LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] datasets grid graphics grDevices stats utils
[7] methods base

other attached packages:
[1] rprojroot_1.3-2 rmarkdown_1.11.9 knitr_1.21 bookdown_0.9.1
[5] RSQLite_2.1.1 gsubfn_0.6-6 proto_1.0.0 FSA_0.8.17
[9] TH.data_1.0-8 MASS_7.3-50 ggplot2_3.0.0 Formula_1.2-2
[13] survival_2.42-3 lattice_0.20-35 car_3.0-2 carData_3.0-1
[17] DT_0.2 RMySQL_0.10.15 DBI_1.0.0

loaded via a namespace (and not attached):
[1] tidyselect_0.2.5 lme4_1.1-18-1
[3] htmlwidgets_1.3 munsell_0.5.0
[5] CATT_2.0 codetools_0.2-15
[7] chron_2.3-53 miniUI_0.1.1
[9] withr_2.1.2 colorspace_1.3-2
[11] rstudioapi_0.8 CoinMinD_1.1
[13] DescTools_0.99.25 robustbase_0.93-3
[15] pastecs_1.3.21 trend_1.1.1
[17] vcd_1.4-3 VIM_4.7.0
[19] multiCA_1.1 TTR_0.23-4
[21] TeachingDemos_2.10 gvlma_1.0.0.2
[23] mnormt_1.5-5 ordinal_2018.8-25
[25] MCMCpack_1.4-4 bit64_0.9-7
[27] gee_4.13-19 coda_0.19-1
[29] xfun_0.5 R6_2.3.0

the index.html's head:
```
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title> | 数据集质量探查与描述推断分析报告</title>
<meta name="description" content="该分析报告基于岭束©DAAS平台的分析结果汇总而成">
<meta name="generator" content="bookdown and GitBook 2.6.7">
<meta property="og:title" content=" | 数据集质量探查与描述推断分析报告" />
<meta property="og:type" content="book" />
<meta property="og:description" content="该分析报告基于岭束©DAAS平台的分析结果汇总而成" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:title" content=" | 数据集质量探查与描述推断分析报告" />
<meta name="twitter:description" content="该分析报告基于岭束©DAAS平台的分析结果汇总而成" />
<meta name="author" content="DAAS">
<meta name="date" content="2019-03-01">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="prev" href="index.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
```
### 2019-03-12
install the development version of knitr,rmarkdown,bookdown，but has no effect.

please help me !!!

**Comment by wikithink** [comment]
> I use the bookdown:render_book function，the same rmd and yml files，the same rstudio server(1.1.463),the same lang is zh_CN.UTF-8,and the same rmarkdown:pandoc_version(1.19.2.1),the same knitr(1.21),with the centos 6.1 or 6.5,the output html files's head content(meta,og:title,content) is normal,but with the centos 7.6, the head content is abnormal: adding a | character before the content (specially the content is unicode like chinese,but english is normal.)
> I copy the sessioninfo below,thanks.
> 
> ### centOS 6.5
> sessionInfo()
> R version 3.4.1 (2017-06-30)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: CentOS release 6.5 (Final)
> 
> Matrix products: default
> BLAS: /usr/lib64/R/lib/libRblas.so
> LAPACK: /usr/lib64/R/lib/libRlapack.so
> 
> locale:
> [1] LC_CTYPE=zh_CN.UTF-8 LC_NUMERIC=C
> [3] LC_TIME=zh_CN.UTF-8 LC_COLLATE=zh_CN.UTF-8
> [5] LC_MONETARY=zh_CN.UTF-8 LC_MESSAGES=zh_CN.UTF-8
> [7] LC_PAPER=zh_CN.UTF-8 LC_NAME=C
> [9] LC_ADDRESS=C LC_TELEPHONE=C
> [11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats graphics grDevices utils datasets
> [6] methods base
> 
> other attached packages:
> [1] rprojroot_1.3-2 rmarkdown_1.11.9 knitr_1.21 bookdown_0.9.1
> [5] RSQLite_2.1.1 gsubfn_0.6-6 proto_1.0.0 FSA_0.8.17
> [9] TH.data_1.0-8 MASS_7.3-50 ggplot2_3.0.0 Formula_1.2-2
> [13] survival_2.42-3 lattice_0.20-35 car_3.0-2 carData_3.0-1
> [17] DT_0.2 RMySQL_0.10.15 DBI_1.0.0
> 
> loaded via a namespace (and not attached):
> [1] Rcpp_0.12.18 rstudioapi_0.6
> [3] magrittr_1.5
> [5] splines_3.4.1 MASS_7.3-47
> [7] lattice_0.20-35 minqa_1.2.4
> [9] highr_0.6 stringr_1.4.0
> [11] tools_3.4.1 parallel_3.4.1
> [13] grid_3.4.1 nnet_7.3-12
> [15] pbkrtest_0.4-6 nlme_3.1-131
> [17] mgcv_1.8-17 xfun_0.4
> [19] quantreg_5.34 MatrixModels_0.4-1
> [21] htmltools_0.3.6 yaml_2.2.0
> [23] lme4_1.1-12 digest_0.6.12
> [25] Matrix_1.2-10 nloptr_1.0.4
> [27] htmlwidgets_1.3 evaluate_0.10
> [29] rmarkdown_1.11 stringi_1.3.1
> [31] compiler_3.4.1 backports_1.0.4
> [33] SparseM_1.77 jsonlite_1.5
> 
> the index.html's head:
> `
> 
> <title>数据集质量探查与描述推断分析报告</title> <script src="libs/jquery-2.2.3/jquery.min.js"></script> `
> ###centOS 7.6
> 
> sessionInfo()
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
> 
> locale:
> [1] LC_CTYPE=zh_CN.UTF-8 LC_NUMERIC=C
> [3] LC_TIME=zh_CN.UTF-8 LC_COLLATE=zh_CN.UTF-8
> [5] LC_MONETARY=zh_CN.UTF-8 LC_MESSAGES=zh_CN.UTF-8
> [7] LC_PAPER=zh_CN.UTF-8 LC_NAME=C
> [9] LC_ADDRESS=C LC_TELEPHONE=C
> [11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] datasets grid graphics grDevices stats utils
> [7] methods base
> 
> other attached packages:
> [1] rprojroot_1.3-2 rmarkdown_1.11.9 knitr_1.21 bookdown_0.9.1
> [5] RSQLite_2.1.1 gsubfn_0.6-6 proto_1.0.0 FSA_0.8.17
> [9] TH.data_1.0-8 MASS_7.3-50 ggplot2_3.0.0 Formula_1.2-2
> [13] survival_2.42-3 lattice_0.20-35 car_3.0-2 carData_3.0-1
> [17] DT_0.2 RMySQL_0.10.15 DBI_1.0.0
> 
> loaded via a namespace (and not attached):
> [1] tidyselect_0.2.5 lme4_1.1-18-1
> [3] htmlwidgets_1.3 munsell_0.5.0
> [5] CATT_2.0 codetools_0.2-15
> [7] chron_2.3-53 miniUI_0.1.1
> [9] withr_2.1.2 colorspace_1.3-2
> [11] rstudioapi_0.8 CoinMinD_1.1
> [13] DescTools_0.99.25 robustbase_0.93-3
> [15] pastecs_1.3.21 trend_1.1.1
> [17] vcd_1.4-3 VIM_4.7.0
> [19] multiCA_1.1 TTR_0.23-4
> [21] TeachingDemos_2.10 gvlma_1.0.0.2
> [23] mnormt_1.5-5 ordinal_2018.8-25
> [25] MCMCpack_1.4-4 bit64_0.9-7
> [27] gee_4.13-19 coda_0.19-1
> [29] xfun_0.5 R6_2.3.0
> 
> the index.html's head:
> `
> 
> <title> | 数据集质量探查与描述推断分析报告</title> <script src="libs/jquery-2.2.3/jquery.min.js"></script> `
> ##2019-03-12
> install the development version of knitr,rmarkdown,bookdown，but has no effect.
> 
> please help me !!!

**Comment by wikithink** [comment]
I have use xpath to replace this content.but not best ideal.

**Comment by yihui** [comment]
I cannot think of a reason how the OS version could possibly affect the output, given the same versions of **bookdown**. You'd better follow the issue guide and provide a full reproducible example next time.

I just pushed a possible fix anyway. Please try the dev version of **bookdown**. Thanks!
