### ISSUE TITLE
Title Documents

### ISSUE THREAD

**Issue by trestletech** [rstudio/bookdown#7]
I'm guessing there's a way to do this with custom templates somehow, but it would be nice if there were a simple way to add a title to a document. This would be prepended on PDFs and perhaps integrated into the `<title>` of HTML?

**Comment by yihui** [comment]
Isn't that the `title` field in the YAML metadata of the first Rmd file?

```yaml
---
title: The Book Title
---
```

**Comment by trestletech** [comment]
That did the trick. Thanks!

**Comment by benwhalley** [comment]
I was going to open a separate issue, but think this is related. Is there a way of having a per-page title in the html output? Perhaps with the overall book title as a prefix, and the title attr of the individual page specified in the Rmd (or by section title)?
At present google results for individual pages are indistinguishable, even when there are nice chapter or section titles which could be used...

**Comment by yihui** [comment]
@benwhalley Please file a new issue. Thanks!
