### ISSUE TITLE
adding Font Awesome icons to custom blocks

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/bookdown#70]
I experimented a bit with using Font Awesome icons in custom code blocks. [Here's what I came up with](http://stackoverflow.com/questions/36293511/creating-custom-blocks-in-rstudios-bookdown) in case you have any desire to bake something like this into the package. I followed other examples to piece this together, so apologies for any really bad CSS.

**Comment by yihui** [comment]
Icons are easy for HTML output. The challenge is how to make them also work for LaTeX output.
