### ISSUE TITLE
suggestions for an errata/changelog? 

### ISSUE THREAD

**Issue by topepo** [rstudio/bookdown#709]
I wanted to have an unnumbered chapter at the end of the html output that would log changes and corrections. I have a chapter for references and then I added one after that with the content: 

```r
# Errata and Version History {-}

***2019-04-xx***

 * blah blah 

 * yada yada 
```

This works except it places the references after this content. 

Any suggestions on how to do this (outside of switching the order of the last two chapters)?

**Comment by yihui** [comment]
You can put references at a custom place via `<div id="refs"></div>` in the Markdown source: https://stackoverflow.com/a/44294306/559676

Something like this (not tested):

```
# References {-}

<div id="refs"></div>

# Errata and Version History {-}

***2019-04-xx***

 * blah blah 

 * yada yada 
```

I doubt if this will work for LaTeX/PDF output. I guess the more reliable method is to use the `includes: after_body` option (based on https://stackoverflow.com/a/16428699/559676). However, you'll have to convert Markdown (the errata file) to the desired output format for every output format, e.g. (again, not tested)

```yaml
---
bookdown::pdf_book:
  includes:
    after_body: _errata.html
bookdown::gitbook:
  includes:
    after_body: _errata.tex
---
```

````md
```{r include=FALSE}
rmarkdown::pandoc_convert('_errata.md', to = knitr:::pandoc_to())
```
````

**Comment by topepo** [comment]
`<div id="refs"></div>` worked perfectly; I only needed it for HTML. Thanks
