### ISSUE TITLE
adding a glossary

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/bookdown#71]
Is it possible to use the [glossaries](https://en.wikibooks.org/wiki/LaTeX/Glossary) LaTeX package with `bookdown`? I think it should be, but I might not be going about it correctly. If it's not possible, then I'll suggest it as a possible enhancement.

If it is possible to implement, here's my approach in case you have any suggestions.

Added to `preamble.tex`:
```
\usepackage[nomain,acronym,xindy,toc]{glossaries}
\makeglossaries
\usepackage[xindy]{imakeidx}
\makeindex
\input{glossary}
```

`glossary.tex` contains glossary entries, such as:

```
\newglossaryentry{computer}
{
  name=computer,
  description={is a programmable machine that receives input,
               stores and manipulates data, and provides
               output in a useful format}
}
```

In the rmd files I use `\gls{computer}`, ending with:

```
\printindex
\printglossaries
```

Ideally, these final commands would come after `\bibliography{}`, but I'm not sure how.

**Comment by yihui** [comment]
This is certainly possible for LaTeX output. You can write arbitrary raw LaTeX commands in R Markdown, but you should know that they won't work for other output formats. Regarding `\printindex` and `\printglossaries` after `\bibliography`, you have to customize the LaTeX template. Chapter 4 has covered how to customize LaTeX output: https://bookdown.org/yihui/bookdown/customization.html

**Comment by gtalckmin** [comment]
@ericpgreen :
Hello Eric,

Did you found a solution for this issue? I have the same problem.
Thanks

**Comment by yihui** [comment]
Please see #199.
