### ISSUE TITLE
Any editor with a good bookdown support. 

### ISSUE THREAD

**Issue by ofenerci** [rstudio/bookdown#714]
Bookdown is great but I am wondering which editor supplies the best integration of bookdown markup language.

**Comment by yihui** [comment]
So you are asking which editor has the best support for an R package created from RStudio, and RStudio happens to be an editor (in case you are not aware of it), it is hard for me not to be biased: https://bookdown.org/yihui/bookdown/rstudio-ide.html 😂

**Comment by N0rbert** [comment]
> Bookdown is great but I am wondering which editor supplies the best integration of bookdown markup language.

I use the following pipe-line:
1. Pre-editing in universal Markdown editor with WYSIWYG support:
    
    From my comprehensive analysis I can recommend [ReText](https://github.com/retext-project/retext).
If you have document with many tables - you can use proprietary [Typora](http://typora.io/) to prepare them.
     Whichever editor you will, use need to know special bookdown syntax elements for labeling and referencing.

1. Compilation of the book.

   Here I use RStudio to build book in all formats.

**Comment by znmeb** [comment]
I use RStudio - the one thing I'd love as an enhancement would be real-time or near-real-time knitting / rendering like some other Markdown editors have. Maybe a "knit on save" option would be a good compromise.

**Comment by yihui** [comment]
@znmeb Yes, we do have "knit on save" from Day One: https://bookdown.org/yihui/bookdown/serve-the-book.html
