### ISSUE TITLE
links in blocks don't have footnotes in pdf

### ISSUE THREAD

**Issue by xvazquezc** [rstudio/bookdown#716]
Hi there,

I recently started with `bookdown` and it looks great!

I have been using a few custom blocks and it works well in general. However, I found out that in linked text within the blocks doesn't get properly converted into footnotes when building the pdf. The linked text gets the proper numbered superscript, but the footnote is not printed anywhere. This happens with both `block` and `block2`.

The footnotes are created without problem outside the custom blocks.

So, this generates the appropriate footnote
```rmarkdown
This is an [link](https://github.com/rstudio/bookdown)
```
But this doesn't
```rmarkdown
    ```{block2 type="rmdnote"}
    This is an [link](https://github.com/rstudio/bookdown)
    ```
```

I guess this has something to do with the `preamble.tex` code or the way the custom blocks are implemented. I tried fiddling with the `preamble.tex`, but after few attempts I got nothing (I'm not very familiar with Latex).

Initial test was with bookdown 0.8 but the issue persists in 0.10.

R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Cheers,
Xabi

**Comment by cderv** [comment]
For this to work you need to use the custom blocks syntax with Fenced Div
See https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

````markdown
::: rmdnote
This is an [link](https://github.com/rstudio/bookdown)
:::
```

This allows to use any Markdown markup whereas the block and block2 engine does not allow that.
