### ISSUE TITLE
playing videos inside html book

### ISSUE THREAD

**Issue by ericpgreen** [rstudio/bookdown#72]
I don't know if it's helpful or annoying to get these types of issues, but I experimented with adding a video to a chapter without success, and I thought it would be a neat feature to add.

[This RPubs example](http://rstudio-pubs-static.s3.amazonaws.com/143741_5deb29ac847846a9835a426b4c499400.html) shows how to embed a YouTube video in an HTML report.

```
 ```{r, eval=FALSE}
<iframe width="560" height="315" src="http://www.youtube.com/embed/9bZkp7q19f0?rel=0" frameborder="0" allowfullscreen></iframe>
```

This does not seem to work in a bookdown chapter. I also tried `include_url()`, but no luck. I do see how to embed a screenshot that opens the video in YouTube on a new tab, but I'm looking to embed the actual video in the chapter.

**Comment by yihui** [comment]
This works fine for me: `knitr::include_url("http://www.youtube.com/embed/9bZkp7q19f0?rel=0")` Note https resources do not work in the RStudio viewer at the moment (cc @jjallaire), and you have to open the book in your web browser.

**Comment by patilv** [comment]
I am trying to display this page within the book but am unable to using either iframe or include_url. Any thoughts will be appreciated. http://bl.ocks.org/patilv/raw/c2d199103dfd346380c4/

**Comment by yihui** [comment]
@patilv I think the restriction comes from ocks.org. You can see the error message in your web browser console:

> Refused to display 'http://bl.ocks.org/patilv/raw/c2d199103dfd346380c4/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.ocks.org".

So such URLs cannot be embedded as iframes on other web pages.

**Comment by patilv** [comment]
@yihui, that is strange. I have used that in iframes on html pages generated using regular rmds. I will have to check back on this.

**Comment by yihui** [comment]
I tested the `html_document` output and it does not work, either. Same error message in the console.

**Comment by patilv** [comment]
Sure. I will check and let you know if my earlier use case have stopped. Thanks.

**Comment by patilv** [comment]
@yihui : That html_document output works if you view it using the Edge browser but not with Chrome. (My earlier iframes of bl.ocks pages are also rendered on Edge but not on chrome.)  Just came across this from Mike Bostock on the d3js google group: https://groups.google.com/forum/#!topic/d3-js/xBC30357zak  

So, it is an intentional change from Mike.

**Comment by yihui** [comment]
Okay, then there is nothing I can do on my side. Thanks for the info!
