### ISSUE TITLE
it would be great to support OpenDocument (odt) file format for output

### ISSUE THREAD

**Issue by N0rbert** [rstudio/bookdown#722]
As you wrote [in the book](https://bookdown.org/yihui/bookdown/r-markdown.html) the  `rmarkdown` already supports `odt_document` output format.

It would be really great if you add support for OpenDocument (odt) file format to `bookdown` and name it `bookdown::odt_document2` for convenience.

**Comment by yihui** [comment]
Do you actually use ODT?

**Comment by N0rbert** [comment]
Yes. I use it. It is mature and open source format. It is native format for LibreOffice which is preinstalled in almost all GNU/Linux distributions.  So why should not use it? :) 

It allows to create comprehensive big documents with figures, tables, headers, equations and so on. But using manual cross-reference mechanism is still a pain as in pure MS Word. So `bookdown` export to `odt` will make life easier for end-users.

**Comment by yihui** [comment]
The implementation should be fairly similar to `bookdown::word_document2`, but I don't have time for this task. If anyone is interested doing the work, I can probably review the PR. Thanks!

**Comment by yihui** [comment]
Done. Many thanks to @atusy for the implementation!
