### ISSUE TITLE
Limited functionality inside custom blocks

### ISSUE THREAD

**Issue by franknarf1** [rstudio/bookdown#73]
It looks like inline code and `\@ref`s do not work inside a custom block. Is there something I could add to the CSS for the block to get its content managed like the rest of the doc? I'm outputting to `html_book`.

Example CSS:

    .rmdcaution {
      padding: 1em 1em 1em 4em;
      margin-bottom: 10px;
      background: #FFFF99 url("images/1459472920_attention.png") left center/3em no-repeat;
    }
    .rmdcaution:before {
      font-style: italic;
      content: "Word of warning";
    }

Example usage:

    ```{block bracket-docs, type='rmdcaution'}
    For documentation on the last two sections, you can type ``?`[[` ``. Paired brackets are just named after their opener. This naming pattern will come up again \@ref[later](lapply) when working with lists of lists. 
    ```

The resulting html is like:

    <div class="rmdcaution">
    <p>
    For documentation on the last two sections, you can type <code>?<code>[[</code></code>. Paired brackets are just named after their opener. This naming pattern will come up again <span class="citation">@ref&lt;a</span> href=“lapply”&gt;later</a> when working with lists of lists.
    </p>
    </div>

And the content displays like:

> `For documentation on the last two sections, you can type ?[[. Paired brackets are just named after their opener. This naming pattern will come up again @ref<a href=“lapply”>later when working with lists of lists.`

The example is currently up on [my gh pages, section 2.1.6](http://franknarf1.github.io/r-tutorial/_book/basics.html#basics), with corresponding [source files on my account](source files on my account).

----

I also just noticed (beyond the example above), that inline code gets pretty-printed inside a custom block, so `"A"` has curly quotes.

**Comment by yihui** [comment]
I thought I mentioned it in the doc but I didn't https://bookdown.org/yihui/bookdown/custom-blocks.html Yes, custom blocks are supposed to work with very simple content. They do not support all types of elements. I may improve this in the future, but it is a little challenging.

**Comment by franknarf1** [comment]
Ok, thanks for the info; and the package too, of course! It's been very easy to use (starting this week without any real Rstudio or github familiarity).

**Comment by yihui** [comment]
Now if you install the development version of **knitr** via

```r
devtools::install_github('yihui/knitr')
```

and change the `block` engine to `block2`. Then everything should just work.
