### ISSUE TITLE
Please develop bookdown::powerpoint_presentation2 output for cross-references

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/bookdown#741]
As `rmarkdown::render()` now officially supports `powerpoint_presentation` output_format, would you mind developing an advanced wrapper that enables cross-references like `bookdown::powerpoint_presentation2` just as in `bookdown::word_document2`?
That would be greatly appreciated.

**Comment by yihui** [comment]
Done. Many thanks to @atusy for the implementation!
