### ISSUE TITLE
Please allow users to define prefix for Appendix section in UI like Chapter

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/bookdown#744]
Currently, it does not seem that users can define prefix used for "Appendix" in UI like chapter prefix.
If you click any appendix link created by bookdown, the title bar starts with an alphabet like A or B (not Appendix A or Appendix B).
For example, open [this link](https://bookdown.org/yihui/bookdown/software-tools.html) and the title bar is not prefixed with "Appendix ".
Would there be any way to achieve this goal?

**Comment by yihui** [comment]
Sounds like a reasonable feature request, but I don't have time for it. I'm hoping someone else could help here...

**Comment by WerthPADOH** [comment]
I'll work on this, if that's alright.

**Comment by WerthPADOH** [comment]
Made a PR: #783.  I also added an option to modify the counters that come before appendix titles.  The default counters are still like A, B.1, B.2, etc.

**Comment by yihui** [comment]
I have merged the PR. Please test with `remotes::install_github('rstudio/bookdown')`. The documentation is at https://bookdown.org/yihui/bookdown/internationalization.html (search for `appendix_name` there). Many thanks to @WerthPADOH for the work and @jooyoungseo for the request!
