### ISSUE TITLE
reticulate with bookdown

### ISSUE THREAD

**Issue by andrewcstewart** [rstudio/bookdown#748]
I'm trying to build a bookdown project consisting of separate Rmd files that each consist of python chunks using [reticulate](https://rstudio.github.io/reticulate/), and it seems that a new reticulate session is being created each time.

Obviously this doesn't qualify in full as a `bookdown` issue, but I was just wondering if you might have any insight from the perspective of the rendering process in `bookdown`.  The R session itself seems to persist across all aggregated Rmd files.  I've tried using the pre- scripts as well to no effect.

Anyway, just curious if you have any insight to offer.  This may ultimately be more of a question about how reticulate manages python sessions.

**Comment by cderv** [comment]
> The R session itself seems to persist across all aggregated Rmd files. I've tried using the pre- scripts as well to no effect.

You are right. By default bookdown use the Merge and Knit approach (M-K) and the Rmd is render in a single session. The other approach is Knit and Merge (K-M) and new session are used for each Rmd.
See the detail in [bookdown book](https://bookdown.org/yihui/bookdown/new-session.html)

I don't know how reticulate behave in the M-K approach. From the [documentation](https://rstudio.github.io/reticulate/articles/r_markdown.html#python-chunks), it should use a single python session 
> Python chunks all execute within a single Python session so have access to all objects created in previous chunks. Chunk options like echo, include, etc. all work as expected. 
As in M-K approach a single Rmd is created before knitting, I believe there should be a single session used. (note that you need knitr > 1.18)

Can you provide an example bookdown repo reproducing the issue you see ? 
That way, it will be easier to look at what you encounter and see if something can be done here or elsewhere.

**Comment by andrewcstewart** [comment]
Thanks @cderv - I went to setup a simple example (with a fresh clean env) in rstudio.cloud to share, and I'm actually having trouble reproducing the original issue.  Multiple bookdown chapters are "inheriting" the `reticulate` spawned python session from the `index.Rmd` just fine!

So at least I understand how bookdown is operating, now I can just isolate the issue on my side to conda environments or something related.

Thanks again.
