### ISSUE TITLE
Would you mind developing word_book() output format?

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/bookdown#756]
I was wondering if there would be any way that someone could develop `bookdown::word_book()` output format just like either `bookdown::pdf_book()` or `bookdown::html_book()`.
Currently, figure and table numbering does not follow chapter hierarchy when output type is `bookdown::word_document2()`, which means a figure inserted under Chapter 3 is numbered Figure 1 (not Figure 3.1) if that figure is the first one throughout all Rmds. This happens to table numbering as well.
It would be so much appreciated if `word_book()` format could be implemented.
Many thanks!

**Comment by yihui** [comment]
The last time I checked Pandoc (long ago), it still didn't support numbering sections in Word. If it does support it now, I can support numbering figures by section numbers, too.

**Comment by cderv** [comment]
I don't think this is supported yet... https://github.com/jgm/pandoc/issues/1413 is still open
However, https://github.com/lierdakil/pandoc-crossref/ could be pandoc filter useful to extend bookdown capabilities. I don't know how it works (yet) regarding docx output but it should. 
This is a long shot but I wanted to dig aroung this pandoc filter and see how it could help improve bookdown (maybe). 
Currently, there is no easy way to get that using bookdown.

**Comment by jooyoungseo** [comment]
Good news! `--number-sections` is now supported for docx output via [pandoc v2.10.1](https://github.com/jgm/pandoc/releases/tag/2.10.1).

**Comment by atusy** [comment]
Yes, this is a good news.
First, we have to add the `number_sections` argument to the `rmarkdown::word_document` function.

**Comment by yihui** [comment]
Great! I'd welcome a PR from anyone. Thanks!

**Comment by jooyoungseo** [comment]
Alright, I will then make a PR for `rmarkdown::word_document()` first.

**Comment by jooyoungseo** [comment]
Now that `rmarkdown::word_document()` has a `number_sections` argument via [rmarkdown#1869](https://github.com/rstudio/rmarkdown/pull/1869), would either of you (@cderv, @atusy) mind taking care of the next step? :)

**Comment by atusy** [comment]
@jooyoungseo 

I made a PR #938 to extend `markdown_document2` and subsequently its family.
It means we do not need `word_book`. We just have to turn on the `number_sections` argument.

**Comment by jooyoungseo** [comment]
Thanks a lot, @atusy, for your hard work! That would be a huge improvement.

**Comment by paulsharpeY** [comment]
Apologies if this I'm hijacking this issue, but I have a related question. I've had some success rendering nicer Word documents using [a pattern that combines .Rmd with a Word template](https://github.com/joelnitta/ms_template/blob/master/code/render.R) (see also [blog post explaining the rationale](https://www.joelnitta.com/post/rmd-to-docx/)).

Do you think it's possible to integrate this approach with bookdown? I had a quick look at [word_document2](https://github.com/rstudio/bookdown/blob/9eb20a83fe303d643cdc1ffca21c2b228be9406a/R/word.R#L60), but it wasn't obvious to me whether this would be possible. Happy to submit a PR if I can get some guidance on how to approach this.

**Comment by cderv** [comment]
@jooyoungseo this is now implemented thanks to @atusy ! Currently it is with `word_document2`. 

@yihui I think we can add an alias `word_book` now, what do you think ? It would be in adequation with `pdf_book` and `epub_book`.

**Comment by jooyoungseo** [comment]
@cderv, shouldn't we make sure whether number_sections works for appendix (e.g., appendix A, etc. for `word_book`?

**Comment by yihui** [comment]
I guess appendix numbering will be tricky...

**Comment by atusy** [comment]
Yes, appendix numbering is quite tricky...
I tried update lua filter, and it works as long as documents are rendered by rmarkdown formats, but not by bookdown formats.
My lua filter looks for the `(APPENDIX)` prefix in headers, however, `bookdown::markdown_document2` removes the prefix before processing by the lua filter...
I think we should document the current limitation open a new issue to solve it in the future.

https://github.com/atusy/rmarkdown/blob/appendix/inst/rmd/lua/number-sections.lua

**Comment by jooyoungseo** [comment]
I have just opened the appendix issue in #946 .
