### ISSUE TITLE
Is it possible to create only .tex file?

### ISSUE THREAD

**Issue by Nowosad** [rstudio/bookdown#76]
`bookdown` has a function `pdf_book` to create pdf file. However, default pdf file is almost always not perfect. Is it possible to create only .tex file?

**Comment by yihui** [comment]
No, there is not such an option at the moment. You can only preserve the .tex output by specifying `keep_tex = TRUE`, and the PDF will always be generated.

**Comment by Nowosad** [comment]
Ok, thanks for the answer.
