### ISSUE TITLE
Caption for images in *.emf format

### ISSUE THREAD

**Issue by wuffi** [rstudio/bookdown#769]
When inserting images in`  .emf` or `.wmf` (vector graphics) format for output in Word (Microsoft), the automatic labeling in the figure caption puts out for example "(ref:myFigureCaption) Caption with **bold** text" instead of resolving it to the expected result "Figure 1: Caption with **bold** text".

I used the following `01-minimal_example.Rmd`:
```
    ---
    title: "Minimal Example"
    output: word_document
    ---
    
    # Including Plots
    
    You can also embed plots, for example:
    
    (ref:myFigureCaption) Caption with **bold** text
    ```{r pressure, fig.cap = '(ref:myFigureCaption)', echo=FALSE}
    plot(pressure)
    ```

Content of `_bookdown.yml` file:

    book_filename: "bookdown-demo"
    rmd_files: ["01-minimal_example.Rmd"]

Content of `index.Rmd` file:
    ---
    output:
      bookdown::word_document2: 
        toc: yes
    ---

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

attached base packages:
character(0)

other attached packages:
[1] bookdown_0.12

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  graphics_3.5.0 
 [3] htmltools_0.3.6 tools_3.5.0    
 [5] utils_3.5.0     yaml_2.1.19    
 [7] grDevices_3.5.0 Rcpp_0.12.17   
 [9] stats_3.5.0     datasets_3.5.0 
[11] rmarkdown_1.14  knitr_1.23     
[13] methods_3.5.0   xfun_0.8       
[15] digest_0.6.15   base_3.5.0     
[17] evaluate_0.14 
```

**Comment by yihui** [comment]
https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references
