### ISSUE TITLE
References within each chapter

### ISSUE THREAD

**Issue by ajbass** [rstudio/bookdown#77]
Awesome package! Is there a way to have a Reference section within each chapter? I was looking through the documentation and could not figure it out.

**Comment by yihui** [comment]
That is not possible for now, but I think it is a good idea, and I'll try to implement it. Thanks!

**Comment by yihui** [comment]
Now references will be displayed on the HTML page where they were actually used. I didn't make any changes for the PDF output, since I believe there must have been mature LaTeX solutions.

**Comment by rensa** [comment]
Was this ever implemented for PDF output? I'm looking at using `bookdown` for a thesis where each chapter was originally a journal paper. So each chapter would have its own reference list. it would be lovely to render it in LaTeX :)

**Comment by yihui** [comment]
@rensa I'm pretty sure there are LaTeX solutions, but I don't have time for further investigation. You may google for something like "latex references by chapter".

**Comment by rensa** [comment]
No worries :) Thanks!

**Comment by rensa** [comment]
Unfortunately not! My supervisors told me that it wasn't a big deal (ie. I could have one big reference list at the end of the thesis, even though some of the chapters are based on published papers), so I left it. I feel like it should be possible, but I'm in my write-up and don't really want to dig around my thesis template too much, sorry 😞

**Comment by danielmcintosh1** [comment]
I continued to do some Googling and found this solution that worked for me. I get a minor warning that I am working on but otherwise exports to pdf as desired.
https://stackoverflow.com/questions/45028623/is-there-a-way-to-add-chapter-bibliographies-using-bookdown

**Comment by rensa** [comment]
Awesome! I'll have a crack at it when I'm doing my last pass in a few months 👍 Thanks, @danielmcintosh1!
