### ISSUE TITLE
How to publish a Bookdown book on GitLab

### ISSUE THREAD

**Issue by dashohoxha** [rstudio/bookdown#795]
I have written a basic example on how to publish a Bookdown book on GitLab:
- https://gitlab.com/dashohoxha/bookdown-example
- https://www.researchgate.net/publication/336983801_How_to_Publish_a_Book_With_Bookdown

Maybe it can be mentioned somehow on the Publishing chapter:
- https://bookdown.org/yihui/bookdown/publishing.html

**Comment by cderv** [comment]
Thank you ! 

We will cover this with https://github.com/rstudio/bookdown/issues/1075 and share your example! 

I'll close to track only in the other issue but that does not mean we ignore this one. It is just to try reduce duplication and centralize in one place.

Thanks !
