### ISSUE TITLE
Unable to compile with nostarch.cls, possibly because of \MakeUppercase

### ISSUE THREAD

**Issue by gvwilson** [rstudio/bookdown#796]
By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - Since my example requires several files, I have put it in a GitHub repo at <https://github.com/gvwilson/bookdown-nostarch/>. The `README.md` file contains detailed information to supplement the bug report below.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

1.  I am attempting to use Bookdown with the style files provided by [No Starch Press](https://nostarch.com/).
2.  After installing TinyTex on my Mac, and then installing packages one by one as LaTeX complains, I am able to compile the example provided by No Starch.
3.  When I attempt to compile a small example using Bookdown, I get an error.
4.  The error appears to be related to the formatting of bibliographic citations: if I remove one line from `index.Rmd` that includes an `@tag` citation, the example compiles, but it fails with that line.
5.  The command-line output from Bookdown shows that compilation is getting as far as `pandoc`, and then `tlmgr` is trying to find a missing file `/tikzlibrarytopaths.code.tex`. It attempts to reinstall `pgf` to resolve the issue, but `pgf` is already present and compilation fails.
6.  The final error message complains about an undefined control sequence `\MakeUppercase ...ppercaseUnsupportedInPdfStrings` (the ellipsis `...` is present in the error message).
7.  `grep` shows that `\MakeUppercase` is used in `nostarch.cls`, but is not defined there; online searches tell me that `\MakeUppercase` is defined by standard LaTeX packages.
8.. If I include a bibliographic citation in the No Starch example `\cite{...}`, it compiles without error.

I therefore believe that something in Bookdown is undefined `\MakeUppercase` or blocking the loading of a file that would define it. Please see <https://github.com/gvwilson/bookdown-nostarch/> for a minimal working example and further documentation.

**Comment by gvwilson** [comment]
1.  Alistair Bailey found a fix for the original problem (described below).
2.  This fix enables the original toy example to compile correctly, but fails when ported back to the book.
3.  The `rmarkdown` branch of the <https://github.com/gvwilson/bookdown-nostarch/> repository includes a minimal working example of the new problem:
    -   Check out the `rmarkdown` branch
    -   Build with `make bookdown`: fails.
    -   Remove one line from `index.Rmd` that includes an unnumbered section heading in a blockquote.
    -    Builds correctly.

**Comment by gvwilson** [comment]
More digging has uncovered a case that seems to trigger the problem: putting a section heading inside a blockquote. I was using H3 headers in blockquotes and styling with CSS for the web version, and that worked with the default Bookdown LaTeX template, but this:

```
> ### Title Inside Blockquote
>
> text of blockquote
```

fails with the obscure error noted above when using the No Starch template, even with the suggested change to `preamble.tex`. I can change most instances to (for example) bold text, but there are two places where I am trying to show literal RMarkdown source that includes headers.

**Comment by cderv** [comment]
Hi @gvwilson, 

Thank you for your patience. 

Is this still an issue ? 
The repo https://github.com/gvwilson/bookdown-nostarch/ no more exist so I can't look into it. 

Thank you
