### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown#8]
For LaTeX output, inserting `\appendix` is basically all we need to do. For HTML, there is no concept of "appendix", so we need some sort of hack to mark certain sections after a certain point to be appendices. (Requested by @aronatkins)

**Comment by yihui** [comment]
@aronatkins It is implemented now. You may search for `appendix` in the doc https://bookdown.org/yihui/bookdown/

**Comment by sammo3182** [comment]
Yihui, thank you for the excellent job on improving the appendix function of `bookdown`. I wounder if it is possible to have options to insert `\usepackage{appendix}` and add 

```latex
\appendixpage
\addappheadtotoc
```
after the `\appendix`?

By doing them, one can move the appendices after the references in the pdf output.

Thanks,

**Comment by yihui** [comment]
@sammo3182 You always have the last weapon if everything else fails to meet your demand: templates (https://bookdown.org/yihui/bookdown/templates.html) That said, I don't see why it is worth killing the time...

**Comment by sammo3182** [comment]
Hi @yihui , thank you for the hint. But could give me a little more help on specifying the Latex template to move the appendix after the reference? I tried adding the following lines in the template:
```latex
\begin{document}
%... settngs about title,  content, etc.
\newpage
$if(bibliography)$
\bibliography{$for(bibliography)$$bibliography$$sep$,$endfor$}
$endif$

\newpage
$if(appendix)$
$appendix$
$endif$

%....some other stuff    
\end{document}
```
But the appendix still appears before the bibliography. Is that because the appendix is not saved in the variable `appendix` or somewhere I did wrong? 

Thank you

**Comment by yihui** [comment]
@sammo3182 Sorry. You are right that the appendix is not actually in the `$appendix$` variable but in `$body$`. That means you cannot easily change the position of the appendix. As I said, I don't see why it is worth killing the time. I feel it makes more sense to put the bibliography after the appendix, because you might cite some references in the appendix as well, in which case it will be weird to have these citation entries to appear before where they are actually referred to.

There is one thing I absolutely love about LaTeX: its PDF output. And there are two things I absolutely hate about it: the syntax (backslashes everywhere and infinite custom environments), and all kinds of _arbitrary_ rules that the victims of the Stockholm Syndrome create (especially for journals).

**Comment by sammo3182** [comment]
Haha, can't agree more on both points, @yihui. The issue is not a fatal one since I can always manually switch the positions of pages in the pdf outputs. As it didn't look easily solved from the file building process, just let it be there. Thank you again for the help.

**Comment by yihui** [comment]
It is definitely a solvable problem. I just don't want to scratch my head thinking about it since the gain seems to be trivial to me. Actually I just added a way to post-process the .tex output, and you can probably use regular expressions to identify the appendix and bibliography, then swap them. See #373 for more info.

**Comment by Warchess21** [comment]
For @yihui many thanks for creating Bookdown package. But i have a problem when I compile my paper. Since I'm using many table in the appendix. Some of these tables appear in the bibliography.
And i think it will be very interesting by a simple command to move Appendix after a bibliography.

[curr_acc_africa_18.pdf](https://github.com/rstudio/bookdown/files/2079201/curr_acc_africa_18.pdf)

See the file uploaded at the bibliography to simply understand what i say

**Comment by sammo3182** [comment]
@Warchess21, I don't know if you have tried to deal with it through `pandoc`. See the second answer in https://stackoverflow.com/questions/16427637/pandoc-insert-appendix-after-bibliography/44294306
Note that this trick cannot be used together with `natbib` as I found in practice.

```
This is some text [@item1]

This is more text [@item2]

# References

<div id="refs"></div>

# appendix
```

**Comment by eeholmes** [comment]
Per comment above, if you are using bookdown, change the contents of your References.Rmd file to
```
`r if (knitr::is_html_output()){ '
# References {-}
<div id="refs"></div>
'}`
```
You can put the References.Rmd file wherever you want the references to appear.  If it doesn't work, make sure you have updated to the latest pandoc.   You don't need to call your header 'References' or the file 'References.Rmd'.  Call it whatever you want.  It's the div id part that is key.  You can put that <div></div> wherever you need it.

**Comment by rdocking** [comment]
Another solution for doing this in Latex/PDF is to define a `bookdown.post.latex` function:

```
options(bookdown.post.latex = function(x) {
  
  # x is the content of the LaTeX output file
  # str_replace can take a named vector of patterns and replacements
  replace_patterns <- c(
    "^\\\\bibliography\\{thesis.bib\\}" = "",         # Remove the default bibliography
    "^BIBLIOGRAPHY" = "\\\\bibliography{thesis.bib}"  # Add it in a new spot
  )
  
  stringr::str_replace_all(x, replace_patterns)
})
```

Calling this function (e.g., in `index.Rmd`) will remove the existing bibliography reference and drop in a new one in the text where a line reading 'BIBLIOGRAPHY' is found.
