### ISSUE TITLE
Markown Issues

### ISSUE THREAD

**Issue by SKLEE98** [rstudio/bookdown#808]
install.packages("Miktex")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/User/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Miktex’ is not available (for R version 3.6.1)

**Comment by SKLEE98** [comment]
Hopefully anyone can help me to solve this issue.

**Comment by cderv** [comment]
Hi, 

For this kind of question, you should ask on http://community.rstudio.com or stackoverflow. Github Issues are more for feature request or bug report. 

I don't know what you are trying to do but MikTex is the name of a Latex distribution and not an R package. That is why 
> package ‘Miktex’ is not available

Do you know about Latex already ? 

To work with Rmarkdown, I advice you to use TinyTex. Look at: 
https://yihui.name/tinytex/

You'll find on this website all the information to install a latex distribution that works well with Rmarkdown. 

Hope you'll manage to make it work ! 

I'll close this issue as it is not bookdown related.
