### ISSUE TITLE
MiKTeX Installation issues

### ISSUE THREAD

**Issue by SKLEE98** [rstudio/bookdown#809]
Can anyone help me to solve the below issues:

MiKTeX  : 
The operation could not be completed for the following reason:
Window API error 5: Access is denied.

I kept trying but did not work.

![IMG_20191108_222247](https://user-images.githubusercontent.com/57544969/68520453-c95b3c80-028f-11ea-92f4-24550accf9e1.jpg)

**Comment by cderv** [comment]
Hello @SKLEE98 , 

You already posted a related question in #808 
please follow the advice I already give in https://github.com/rstudio/bookdown/issues/808#issuecomment-552024622

> For this kind of question, you should ask on http://community.rstudio.com or stackoverflow. Github Issues are more for feature request or bug report.

When you open an issue in this repo, there should be an issue template giving some guidelines to follow. Please take it into account when opening issue. 

I am still closing this one as this is not related to bookdown at all. 
It is an installation issue for MikTex that seems to be related to where you are installing the binary (_Access is denied_). Look at `TinyTex` distribution in my other comment for a lightweight and easy to install distribution to compile PDF.
