### ISSUE TITLE
Error when install the package

### ISSUE THREAD

**Issue by Alex1900** [rstudio/bookdown#82]
I followed the instruction in the demo book and below is the error message I got when I install it using command devtools::install_github("rstudio/bookdown"). What is  object 'latexmk' in this message? Is there any additional packages I need to install as well? I have already installed the latest version of htmltool, httpuv, miniUI, shiny, rmarkdown.

```
* installing *source* package 'bookdown' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in get(x, envir = ns, inherits = FALSE) : 
  object 'latexmk' not found
Error : unable to load R code in package 'bookdown'
ERROR: lazy loading failed for package 'bookdown'
* removing 'D:/Program Files/R/R-3.0.3/library/bookdown'
Error: Command failed (1)
```

**Comment by yihui** [comment]
I don't think you have the latest version of rmarkdown. Show your `sessionInfo()` after `library(rmarkdown)`.

BTW, your R version is 3.0.3, which is more than 2 years old. You probably need to upgrade now.

**Comment by Alex1900** [comment]
I reinstalled R and it is working now. Thanks Yihui.
