### ISSUE TITLE
Bug: Figure caption counting keeps being appended to previous chapter when appendix_name is customized

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/bookdown#827]
This is another bug that I have just found.

When `appendix_name` field has been customized in `bookdown.yml`, any figures included in Appendix section is captioned appended to your previous chapter.

For example, let's say you have three chapters and the last figure before your appendix is captioned as "Figure 3.11:", then the following setup will give you your figure in `Appendix A` as "Figure 3.12:" instead of "Figure A.1:"

``` yaml
language:
  ui:
    appendix_name: "Appendix "
```

Please note that this bug does not occur when you do not customize `appendix_name` field.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by jooyoungseo** [comment]
Now it is perfect! Thank you very much for fixing everything.

**Comment by yihui** [comment]
You are welcome, and thanks for testing! I'm going to make a CRAN release soon.
