### ISSUE TITLE
Footnotes at the end of each chapter (HTML)

### ISSUE THREAD

**Issue by ultinomics** [rstudio/bookdown#84]
Is it possible to have footnotes be placed at the end of each HTML chapter instead of at the end of the document? (I'm guessing the answer here will be the same or similar as #77, but I thought I still ask.)

It makes sense to me that footnotes go at the end of a gitbook if one renders via MK. But I find it odd that the footnotes still go in the `references` chapter when I use `bookdown::html_chapters` with options `split_by: 'rmd'` and then render using KM. I was expecting that each Rmd be knit and coverted to its own html file with footnotes.

Thanks @yihui!

**Comment by yihui** [comment]
You are right that it is a good idea to move both references and footnotes back to each individual HTML page. I'll try. Thanks for the suggestion!

**Comment by yihui** [comment]
Now footnotes will be displayed on the page where they were actually created. Same for references.

**Comment by ultinomics** [comment]
Amazing. Will there be an option to have references placed at the end of a
chapter?

**Comment by yihui** [comment]
There are no options to control the behavior, but references are indeed placed at the end of each page, e.g. see https://bookdown.org/yihui/bookdown/ A full list of references are still placed at the end of the book, though.
