### ISSUE TITLE
equation refs

### ISSUE THREAD

**Issue by deleeuw** [rstudio/bookdown#85]
gitbook format split by chapter. correct that references to formulas in other chapters do not work ?

**Comment by yihui** [comment]
Correct. MathJax does not support references of equations on other pages. I understand sometimes you may want to refer to equations on other pages, but it would require me to parse MathJax equation labels, which is doable but not trivial, so I didn't implement it.

**Comment by deleeuw** [comment]
Thanks — Jan

===
Jan de Leeuw, Professor Emeritus, UCLA Statistics
http://gifi.stat.ucla.edu — https://www.facebook.com/jan.deleeuw1
eval (parse (text = "library(leaflet); x <- addTiles (leaflet ()); 
print (addMarkers (x, lng=-122.6670884, lat=45.5763559, popup = 'Nicole and Jan'))"))

**Comment by yihui** [comment]
You are welcome. Section 2.1.3 documented the syntax: https://bookdown.org/yihui/bookdown/markdown-syntax.html
