### ISSUE TITLE
What blocks are available

### ISSUE THREAD

**Issue by csgillespie** [rstudio/bookdown#86]
The page: https://bookdown.org/yihui/bookdown/custom-blocks.html

doesn't actually mention which blocks have been defined

**Comment by yihui** [comment]
The documentation says

> It is up to the book author how to define the style of the block.

meaning that none are available until you define them. The book source is here https://github.com/rstudio/bookdown/tree/master/inst/examples and you can figure out how the example blocks were defined.

**Comment by csgillespie** [comment]
Sorry, I misread.
