### ISSUE TITLE
How to use rticles::springer_article with R Markdown?

### ISSUE THREAD

**Issue by h56cho** [rstudio/bookdown#862]
Hello,

I am trying to use the ```rticles::springer_article``` with my R Markdown, and the below shows my YAML header:
```R
title: myTitle
bibliography: library.bib
bibstyle: spphys
output: rticles::springer_article
```

and when I try the above, the following error shows up:
```R
This is BibTeX, Version 0.99d (TeX Live 2019)
The top-level auxiliary file: Publication_2_v11.aux
I couldn't open style file spphys.bst
---line 22 of file Publication_2_v11.aux
 : \bibstyle{spphys
 :                 }
I'm skipping whatever remains of this command
I found no style file---while reading file Publication_2_v11.aux
(There were 2 error messages)

Error: Failed to build the bibliography via bibtex
Execution halted
Warning message:
LaTeX Warning: Citation `Galyardt14mmm' on page 3 undefined on input line 178.
LaTeX Warning: Reference `sec:1' on page 3 undefined on input line 184.
Package rerunfilecheck Warning: File `Publication_2_v11.out' has changed.
(rerunfilecheck)                Rerun to get outlines right
(rerunfilecheck)                or use package `bookmark'.
LaTeX Warning: There were undefined references.
LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right. 
```
my .bib file does compile when I try to use it on the regular R markdown template (i.e. without articles::springer_article)

How can I solve this issue? Thank you,

**Comment by cderv** [comment]
Hi, 

It is not clear for me how you are trying to use `rticles::springer_article` inside bookdown ?
Is this an issue with bookdown, rmarkdown or even rticles ? 

Maybe asking this type of question inside RStudio community or Stackoverflow would be a better idea, as adviced in the issue guide. There is a broader community of R user ready to help with questions and help find issues if any. Then, opening a bug in the correct repo is the way to go. 

Thanks.
