### ISSUE TITLE
Is there a way to use LNCS template with book down?   

### ISSUE THREAD

**Issue by h56cho** [rstudio/bookdown#863]
Hello,

I am trying to use the R markdown with LNCS template by springer.
Is there a way to use the LNCS template with R book down?

Thank you,

**Comment by cderv** [comment]
Hi, 

As stated in the issue template, this type of question is best asked on the RStudio community or in SO, than in the issue board in this repo. 
There will be a broader community ready to help, and maybe already some people that use the LNCS template and share experience. 

The bookdown contest posts could also be a source inspiration for you to find examples:
https://community.rstudio.com/tag/bookdown-contest

About template and publisher, the book has some informations. 
https://bookdown.org/yihui/bookdown/publishers.html
I'll guess you need to have already the latex template 
> It will be much easier to publish a book written with bookdown if the publisher you choose supports LaTeX. 

Hope it helps.
