### ISSUE TITLE
Multiple formats at once

### ISSUE THREAD

**Issue by MyKo101** [rstudio/bookdown#873]
Setting `new_session: true` currently starts a new session for each chapter that is rendered. However, I am currently rendering multiple formats and it would be beneficial for me to have a new session between each _format_, but maintain the same session _within_ each format.

Is there a simple solution to this? Or would it just be a case of looping each output. I'm currently using this in the `index.rmd` YAML:
```
knit: (function(...) bookdown::render_book(...,output_format="all"))
```

**Comment by yihui** [comment]
I suggest you use a custom R script to render your book to multiple formats. This is what I do for the bookdown book: https://github.com/rstudio/bookdown/tree/master/inst/examples/_render.R

If you want to render each format in a separate R session, you shouldn't set `new_session: true`. Here is one way:

```r
for (fmt in c('bookdown::pdf_book', 'bookdown::epub_book', 'bookdown::gitbook')) {
  xfun::Rscript_call(bookdown::render_book, list('index.Rmd', fmt))
}
```
