### ISSUE TITLE
Error with krantz class and hyperref package (unnumbered sections)

### ISSUE THREAD

**Issue by jamarav** [rstudio/bookdown#884]
Hi yihui. 
First of all congratulations for your smart package knitr. I'm an R user and I have used this wonderful package in the last two years producing interactive reports. In my opinion this package is a high quality tool for reproducible reseach, as you describe in your book "Dynamic Documents with R and knitr". Now I'm writing my thesis and I have decide to generate the document with knitr and Latex. 
I'm writing you according to report some problems with the krantz class that I have noticed. I'm using the krantz class from this repository that let me to use the hyperref package without compilation problems. I have notice that the hyperref package make the links correct only when I use numbered parts, chapters...
The problem is generated when I use unnumbered commands (\part*{} , \chapter*{}, ...) in the frontmatter and backmatter.
I tryed to fix the problem using \addcontentsline{toc}{chapter}{} together with \chapter*{} and I could show that this works with the standard book class but it doesn't work with krantz class. In this class,  the use of \chapter*{} adds a link in the table of contents that it is not added in the default book class. This behaviour doesn't allow to use the combination of \chapter*{} and \addcontentsline{toc}{chapter}{foo}.
I attached a simple example using your book tamplate in the knitr repository. The links of hyperref are wrong at the first and last sections of table of contents. As you can to show, the preface links in the toc is replicated (one generated by \chapter*{Preface} and the other  generated by \addcontentsline{toc}{chapter}{Author}).
I also attached my actual krantz class. 
I added the following **extra options**:

_-Another page dimensions format (240 x 170)mm.
-Short title option in the headings.
-I commented the definition of cornermarks (I'm not sure if this is the best way to remove the cornermarks)
-I commented \pagestyle{headings} lines (I prefer to set manual the pagestyle in the main document) and I created  \pagestyle{thesisheadings} adding the short title option_ 

Note: I'm not an experienced Latex user. I would appreciate any improvment suggestion

Thanks in advance

[knitr-book.zip](https://github.com/rstudio/bookdown/files/4599949/knitr-book.zip)

**Comment by yihui** [comment]
Sorry, but I don't think I have enough expertise for this particular LaTeX class, either. If you are working with Chapman & Hall/CRC, they have a LaTeX help desk and you can email `Kumar.Shashi@cenveo.com` with your questions about `krantz.cls`.

If you are working on your thesis, you probably should follow the typesetting guidelines of the graduate school (unless they don't have guidelines), otherwise it can be quite painful to switch from `krantz.cls` to another document class in the end...

**Comment by jamarav** [comment]
Thanks you very much Yihui for the advices. I will try to fix the problems or to write to the email above.

**Comment by jamarav** [comment]
Finally I have achieved to fix the problem. I got a good behaviour between hyperref package and unnumbered chapters redefining the lines below from the krantz.cls class file:

```
\def\@schapter#1{\if@twocolumn
                   \@topnewpage[\@makeschapterhead{#1}]%
                 \else
                   \@makeschapterhead{#1}%
                   \addcontentsline{toc}{chapter}{#1}
                   %\addcontentsline{toc}{fm}{#1}
                   \markboth{#1}{#1}
                   \@afterheading
                 \fi}
```
I'm not sure which is the definition of fm in the krantz class but the changes above works fine fixing the error.
I also commented the line  \printindex{} in the main .Rnw file and I added several \cleardoublepage{} commands for a proper work.
I hope these changes are useful.
[knitr-book.zip](https://github.com/rstudio/bookdown/files/4643063/knitr-book.zip)

**Comment by jamarav** [comment]
An additional update. For the correct link reference with hyperref the package toclof is still required in the main document. For remain a correct format with krantz style titles it is necessary to include the option **[titles]**: 
```
\usepackage[titles]{tocloft}
```
