### ISSUE TITLE
pdf_book: documentclass scrbook not possible because of \subtitle

### ISSUE THREAD

**Issue by rnuske** [rstudio/bookdown#89]
The custom title layout introduced by bookdown defines the new command `\subtitle`.
This renders the usage of the documentclass `scrbook` impossible. 

`scrbook` is part of the latex package koma-script. KOMA-Script adapts the standard documentclasses to European paper sizes and is quite popular around here.

Changing documentclass from `book` to `scrbook` in index.Rmd of the bookdown-demo results in the following error messages
```
! LaTeX Error: Command \subtitle already defined.
               Or name \end... illegal, see p.192 of the manual.

Fehler: Failed to compile bookdown-demo.tex. See bookdown-demo.log for more info.
Ausführung angehalten

Exited with status 1.
```
[bookdown-demo.log](https://github.com/rstudio/bookdown/files/220937/bookdown-demo.log.txt)

Is there anything one could do to suppress the custom bookdown title layout?

**Comment by rnuske** [comment]
read now the later chapters of the bookdown book (https://bookdown.org/yihui/bookdown/theming.html). 
`scrbook` works in combination with `template: null`!

**Comment by yihui** [comment]
Glad you found it in the documentation.
