### ISSUE TITLE
HTML output should default to sans-setif section headings and serif text

### ISSUE THREAD

**Issue by krishnakumarg1984** [rstudio/bookdown#904]
In the canonical LaTeX documentclass `book` or `report` for a long-form document (which is `bookdown's` target category), it is desirable to have the body text is typeset using serif version of the font while having the section headings typeset using  sans-serif versions of the font. This appears to be a strong typographical convention for reasons of the comfort of reading.

https://tex.stackexchange.com/questions/64059/sans-serif-headings-serif-body-text
http://www.khirevich.com/latex/font/ 
https://subscription.packtpub.com/book/hardware_and_creative/9781847199867/11/ch11lvl1sec155/time-for-action-designing-chapter-and-section-headings 

Right now, looking at the `gitbook` output of the bookdown book as well as the gitbook output generated by `bookdown-minimal` project template, it is not easy to make such a fine-tuned change. The changes of font type currently get applied throughout the document. Can we fine-tune this somehow?

**Comment by cderv** [comment]
With HTML output, you should be able to customize font using CSS as any other HTML output. You can target specific part of the document using CSS selector. 

Did you try that already ? 

I'll close this as I don't think this is **bookdown** specific. 

You can follow the issue guide and ask such question in Q&A website: https://yihui.org/issue/#got-a-question

Please feel free to reopen if there is something specific I missed. 

Thank you.
