### ISSUE TITLE
R bookdown - pdf_book does not render pdf 

### ISSUE THREAD

**Issue by milenastat** [rstudio/bookdown#907]
I am trying to compile **R Cookbook** bookdown downloaded from the author's [github][1] to **pdf**. 

In `index.Rmd` I specified that I want `output: bookdown::pdf_book` but built all defaulted to an error:

```
! Package inputenc Error: Unicode character ⌘ (U+2318)
(inputenc)                not set up for use with LaTeX.

Try other LaTeX engines instead (e.g., xelatex) if you are using pdflatex. See https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html
Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
Execution halted

Exited with status 1.
```
I followed the steps in ```https://yihui.org/tinytex/r/#debugging``` and currently the errors look the following:

```
pandoc-citeproc: reference ref not found
tlmgr: package repository http://mirror.koddos.net/CTAN/systems/texlive/tlnet (verified)
tlmgr install: package already present: texlive-scripts
! Package fontspec Error: The font "Arial" cannot be found.

! kpathsea: Running mktextfm Arial
! /home/pinkpanther/.TinyTeX/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for Arial.
! /home/pinkpanther/.TinyTeX/texmf-dist/web2c/mktexnam: Need to update ?
! mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input Arial
! This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

! /home/pinkpanther/.TinyTeX/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for Arial.
! /home/pinkpanther/.TinyTeX/texmf-dist/web2c/mktexnam: Need to update ?
! mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input Arial
! This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

! /home/pinkpanther/.TinyTeX/texmf-dist/web2c/mktexnam: Need to update ?
! mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input Arial
! This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

! mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input Arial
! This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

! This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)

! kpathsea: Running mktexmf Arial

! ! I can't find file `Arial'.
! <*> ...=ljfour; mag:=1; ; nonstopmode; input Arial

! <*> ...=ljfour; mag:=1; ; nonstopmode; input Arial

! Please type another input file name
! ! Emergency stop.
! <*> ...=ljfour; mag:=1; ; nonstopmode; input Arial

! ! Emergency stop.
! <*> ...=ljfour; mag:=1; ; nonstopmode; input Arial

! <*> ...=ljfour; mag:=1; ; nonstopmode; input Arial

! Transcript written on mfput.log.

! grep: Arial.log: No such file or directory

! mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input Arial' failed to make Arial.tfm.

! kpathsea: Appending font creation commands to missfont.log.

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
Execution halted

Exited with status 1.
```
[In][3] `_output.yml` I played with ```latex_engine``` and changed from ```xelatex``` to ```pdflatex```and the other way round but it did not help. 

I have two laptops: (1) principal running Fedora 29 and R.3.6.1 (2) spare one with Ubuntu 20.00 and R.4.0 for 'experimenting'. On both I had TexLive installed. 

Having read [this post][4] from my Ubuntu machine I removed TexLive (which installation even after purging, cleaning etc. still seems to live on my Ubuntu - details below) and `install.packages('tinytex')
tinytex::install_tinytex()`. That however did not help solve the problem. 

For [clarity][5] on Ubuntu 

```
R> Sys.which('xelatex')
                xelatex 
     "/usr/bin/xelatex" 
```

and `/home/pinkpanther/bin/xelatex` on Fedora

In Fedora the ```_main.log``` as suggested in this [post][6] can be accessed and [system2][6] renders:

```
R> (system2('pdflatex', '-v', stdout = F))
[1] 0
```
```
R> (system2('pdflatex', '-v'))
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018)
kpathsea version 6.3.0
Copyright 2018 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.67.0
[1] 0
```

Equivalently in Ubuntu `_main.rds` when attempting to extract gives and error and system2 returns:

```
> (system2('pdflatex', '-v', stdout = F))
[1] 0
```

```
> (system2('pdflatex', '-v'))
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.02
[1] 0
```
It is already 2 days I am working on debugging this problem and yes I know I can read it online but it is important to me to render a pdf file. I just want to compile this bookdown file which was made available on github and I do not plan to write a new book. 

    

  [1]: https://github.com/CerebralMastication/R-Cookbook.git
  [2]: https://community.rstudio.com/t/bookdown-pdf-generation/12359/4
  [3]: https://stackoverflow.com/questions/58398191/bookdown-does-not-render-image-in-output-pdf
  [4]: https://github.com/rstudio/rmarkdown/issues/1285
  [5]: https://community.rstudio.com/t/no-pdf-output-in-bookdown-demo/6416/11
  [6]: https://github.com/rstudio/bookdown/issues/394

**Comment by cderv** [comment]
Hi, 

thanks for your patience on this. 

If you really need to build the book from https://github.com/CerebralMastication/R-Cookbook, I would suggest to see with the author of the book directly.

It does not seems like a specific **bookdown** issue, but you need to setup your environment for building a PDF version (LaTeX, CTAN packages, fonts, ...), and specifically to what is required for the specific book you want.
For that I can't help as I don't know this book. 

If you found a specific issue with **bookdown**, please reopen a new one.

Thank you.
