### ISSUE TITLE
Feature suggestion: Improve HTML print layout?

### ISSUE THREAD

**Issue by haozhu233** [rstudio/bookdown#91]
Hi, @yihui, thank you so much for this package which saves me a lot of time from home-brewing a similar website with fewer functionalities. So far both my boss and I love it. :)

Regarding this issue, could we get a better default print layout? Currently, if you try to print out the HTML page directly using browser (ctrl + P or cmd + P), the layout will look kind of bad as it will include the toc by default and you won't be able to print out anything other than Page 1. 

I guess the ultimate goal is that when user hit the print button, all the contents in that chapter will be put on a page in a memo style and the toc is hidden by css by default. Thank you!

**Comment by yihui** [comment]
HTML is simply not for printing purposes. If you want to to print the document, the quality will be much much better if you just compile the book into PDF and print the PDF. I'm not sure if you have noticed `bookdown::pdf_book`.

**Comment by haozhu233** [comment]
I did use `bookdown::pdf_book` and I like the default tex layout that you customized for a book (thanks again for that :+1: ). 

Maybe it is just my personal preference on this but HTML page can also get an elegant printing result if it is well defined in `@media print{ }`. A good example coming to my mind is [stackedit.io](https://stackedit.io/editor). They hided all the editing panels and it left users a very clean page to look at and print. 

![capture](https://cloud.githubusercontent.com/assets/7014590/14613832/3fd25238-056c-11e6-8609-217856934715.PNG)

Of course, I can use `bookdown::pdf_book` every time when I build a website but I just hope users can have a minimum thing to rely on even if a pdf book is not rendered.

**Comment by haozhu233** [comment]
@yihui Sorry, I just recognized that if this is really a problem, it is a problem of `gitbook`. :P 

So I'm going to close this issue. Again, thank you so much for this awesome package!

**Comment by yihui** [comment]
Actually I totally agree it will be helpful if we can tweak the gitbook CSS to make the pages look better when printed. If you have the time to do it, I'd certainly appreciate a pull request (even it is as simple as hiding the sidebar, it will still be much better).

I don't really like the default LaTeX template, though. It just uses the plain `book` class. I have not done much research yet, but at least I tried the LaTeX class from Chapman & Hall, and this is what it looks like: https://dl.dropboxusercontent.com/u/15335397/misc/bookdown-crc.pdf

**Comment by haozhu233** [comment]
Sounds good! I will check it out. 

That Chapman & Hall book looks surprisingly good!! Are we finally reaching a stage where LaTeX becomes as friendly as it can be? I'm impressed!

**Comment by yihui** [comment]
Exactly. LaTeX is powerful, and I wish we could make use of 80% of its power with 20% effort.

**Comment by hadley** [comment]
I'm reopening this issue because I think it should be resolved. The default print appearance from css doesn't need to look amazing, but it needs to do better than currently (in Safari, it only prints a single page, regardless of how long the file actually is)

**Comment by yihui** [comment]
@haozhu233 has solved the issue, and we are just waiting for the CLA before he can send the pull request.
