### ISSUE TITLE
Include md files with shifted heading level

### ISSUE THREAD

**Issue by kmcbest** [rstudio/bookdown#914]
Pandoc has a command " shift-heading-level-by= " which dynamically changes all the heading levels on the fly. You can have your content split into small md files and use a builder script to include them. There's a lua filter script which can parse an index.md file for the restructuring of your book, such as 
``` 
{.include shift-heading-level-by=1}
11.md        (in this case, # heading will become ## heading in the output but the 11.md file itself remains untouched)
12.md
```
Bookdown, however, only has a YAML script to include all or some of the md files as they were. Is there a similar mechanic for dynamically set the heading level of an included file?

**Comment by cderv** [comment]
Hi, 

I may have misunderstood your question and / or issue but here answer from what I understand. 

* You should be able to set pass `--shift-heading-level-by=` pandoc options using the `pandoc_args=` argument in the output format function. This will be pass to pandoc to get the desired effect during the conversion. Would that work in what you described ? 
* You can also use `pandoc_args=` to pass a lua filter of your need so that pandoc uses it during conversion. 

> There's a lua filter script which can parse an index.md file for the restructuring of your book
Do you have an example of that ? I don't know about that and I may have missed something.

**Comment by kmcbest** [comment]
Imagine I have two md.files
1.md goes like
```
# Introduction
There is...
## Background
The author...
```
2.md goes like
```
# Introduction
Before...
## Background
In fact...
```

Supposed I'm writing another paper where I need the content of 1.md and 2.md but I want them on a lower heading level. I want to have a third "index.md" to include them, which goes like (pseudo code)
```
# Method 1
{include 1.md  shift-heading-level-by=1}

# Method 2
{include 2.md  shift-heading-level-by=1}
```

And the Combined.md looks like
```
# Method 1
## Introduction
There is...

### Background
The author...

# Method 2
## Introduction
Before...

### Background
In fact...

```

Therefore, my 1.md and 2.md remain intact and can be reused elsewhere.

Example files are here: [rmd-example.zip](https://github.com/rstudio/bookdown/files/4925074/rmd-example.zip)

**Comment by mschilli87** [comment]
@kmcbest: Ca you provide and *actual* (minimal) example (incl. YAML headers and the how you render the document)?

What features do you loose when combing the files?
AFAICT, you can always render your `1.rmd` and `2.rmd` to `1.md` and `2.md` and then include those into `combined.rmd`.

This should even work with a base R only hack like this:

````Rmd
```{r include-fun, include=FALSE}
include_md <- function(md.file) {
    cat(readLines(md.file, sep = '\n'))
}
```
# Method 1

```{r method1, results="asis"}
include_md("1.md")
```
# Method 2

```{r method2, results="asis"}
include_md("2.md")
```
````

I'd probably use a Makefile to ensure everything is build the way it should but you can do it any way you like.
As long as you pass the appropriate pandoc arguments when converting the `*.rmd` files to `*.md` files, those will already have the extra indentation level without the need to ever touch the `*.rmd` files (so you could still build them your regular way as standalone documents).

Note that this is super hacky and there are probably much cleaner solutions. I just wanted to point out that AFAICT everything you want should already be possible without the need to change anything in any package involved.

**Comment by kmcbest** [comment]
Thank you Marcel. I'm new to R Markdown and didn't know about defining a function like this. Your code is inspiring. What I need to do is extend your include_md function to do these:
1. Add another parameter "nShift", which reflects the extra indentation level that I want.
2. Parse the md.file line by line. If any line starts with a '#', I should append nShift '#'s at the beginning.

That may do the trick. I'll report back with a working example.



2255859@qq.com
 
From: Marcel Schilling
Date: 2020-07-15 20:57
To: rstudio/bookdown
CC: kmcbest; Mention
Subject: Re: [rstudio/bookdown] Include md files with shifted heading level (#914)
@kmcbest: Ca you provide and actual (minimal) example (incl. YAML headers and the how you render the document)?
What features do you loose when combing the files?
AFAICT, you can always render your 1.rmd and 2.rmd to 1.md and 2.md and then include those into combined.rmd.
This should even work with a base R only hack like this:
```{r include-fun, include=FALSE}
include_md <- function(md.file) {
    cat(readLines(md.file, sep = '\n'))
}
```
# Method 1
```{r method1, results="asis"}
include_md("1.md")
```
# Method 2
```{r method2, results="asis"}
include_md("2.md")
```
I'd probably use a Makefile to ensure everything is build the way it should but you can do it any way you like.
As long as you pass the appropriate pandoc arguments when converting the *.rmd files to *.md files, those will already have the extra indentation level without the need to ever touch the *.rmd files (so you could still build them your regular way as standalone documents).
Note that this is super hacky and there are probably much cleaner solutions. I just wanted to point out that AFAICT everything you want should already be possible without the need to change anything in any package involved.

**Comment by kmcbest** [comment]
And change it to 
`readLines(md.file, encoding="UTF-8")  `
to read UTF encoded files.

**Comment by mschilli87** [comment]
@kmcbest: Nice to hear my dirty hack was of use to you. I don't think you need `gsub` though as you want only one replacement exactly. Also note that this might break in cases like this:

````Rmd
# This is a header and should be indented.

```{r, echo = TRUE}
# This is a comment in a code chunk that will end up in the Markdown and should not be indented.
```
````

So I'd rather rely on Pandoc for for shifting the headers in the partial files before including them as-is in the main document.

**Comment by cderv** [comment]
@kmcbest before going any further with ideas I have in mind, I am still trying to understand your use case regarding bookdown (where you open this issue at first). Your example zip is not a bookdown project, so I may have missed a part. 

From my understanding, bookdown allows already to split a long form document in multiple Rmd files instead of writing a very long document. The classical usage is to have one Rmd by section, with several chapters in it. 

How do you want to use bookdown coupled with the feature you found useful from the lua filter ? 
I did not know about this filter but I see it as a way to split a main document in small piece. 

Also, know that with Rmarkdown and knitr, you have the concept of child document. Maybe it could be of interest regarding your usage See https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html
This is another way to do what @mschilli87 describe, but to include child rmd file directly.

**Comment by kmcbest** [comment]
@cderv Bookdown has the trick to treat child files in stock by YAML script, like 'rmd_files: ["index.Rmd", "abstract.Rmd", "intro.Rmd"]'. 
I think the only feature missing in bookdown is to shift heading level when you include the child md files, hence the question. You mentioned the pandoc parameter '--shift-heading-level-by='. While it can be passed to the main file to change its heading level, what I want is to do it to the child files. So if the bookdown package got update to honor this syntax:
`rmd_files: ["index.Rmd", 1, "abstract.Rmd", 1 "intro.Rmd", 0]`
with 1, 1 and 0 the additional heading level indent, we're good.

**Comment by kmcbest** [comment]
> 
> 
> @kmcbest: Nice to hear my dirty hack was of use to you. I don't think you need `gsub` though as you want only one replacement exactly. Also note that this might break in cases like this:
> 
> ```gfm
> # This is a header and should be indented.
> 
> ```{r, echo = TRUE}
> # This is a comment in a code chunk that will end up in the Markdown and should not be indented.
> ```
> ```
> 
> So I'd rather rely on Pandoc for for shifting the headers in the partial files before including them as-is in the main document.

**Comment by cderv** [comment]
> 'rmd_files: ["index.Rmd", "abstract.Rmd", "intro.Rmd"]'

This are not child files, as Rmarkdown child document used in `child=` chunk option. These are just several Rmd used to generate a book-like content from several Rmd files. 
Why do you need to shift the header in the first place ? Why the file can't have the correct header directly ? 

With bookdown, files are not included inside one another like the lua filter suggest to do. The are rendered as one Rmd or merged after rendering. So generally, the header are the correct level in all the Rmd document. In my opinion the kind of feature you suggest could be interested for child document, included inside a main Rmd document. However, a lua filter is a great way to do that as it parses the AST and not modify the text as is (using regex). 

Can you provide a small example using bookdown of what you have in mind, with the result you aim. It would help really understand better the usage and the solution you are suggesting. Thank you.

**Comment by kmcbest** [comment]
> With bookdown, files are not included inside one another like the lua filter suggest to do. The are rendered as one Rmd or merged after rendering.

So I've indeed misunderstood Bookdown's feature. Luckily the R language offers read and shifting on-the-fly.

The reason why I need to shift the header is that I'm breaking a long technical document into smaller, reusable md files. Imaging my product has a lot of features, some belong to the free version, some for the basic, some for advance or VIP etc. From my point of view and for each md file, I always write them starting with heading level 1. Now the company has a customer asking for an offer, with a budget covering the free and basic features. I then have to collaborate with the marketing team to write a document containing the feasibility study, the product design and the pricing info. Since I'm only in charge of the "product design" section, I should combine my md files (free.md, basic.md, for example) and shifted a level so that they are nested into the "product design" section. Then I hand my output Word file to the marketing team so that they can merge it with other parts of the document.

**Comment by cderv** [comment]
I see the need, thank you for the clarification. 

You are talking about md files, and not Rmd files. How to you plan to use bookdown ? generate the word document ? 
Building a small example from what you describe would really help trying possible solutions. I am not sure if your source file are Rmd, or md

>  I'm breaking a long technical document into smaller, reusable md files. Imaging my product has a lot of features, some belong to the free version, some for the basic, some for advance or VIP etc.

Know that you can also use conditional block, code block or text block, so that you can produce a different document based from the same source. (Ex: https://bookdown.org/yihui/rmarkdown-cookbook/eng-asis.html and https://bookdown.org/yihui/rmarkdown-cookbook/chunk-variable.html)
This would allow you to set like an environment variable, and depending on the value, the generated document would differ. It could be of help in such use case.

**Comment by kmcbest** [comment]
In fact I kind of rushed in put on this issue and I should really delve into R markdown, let alone bookdown to have a better idea. Indeed, if there's conditional block, I should reconsider my initial purpose. Maybe I don't need to break down my document at all. I'll put some time into this.

Thanks for the explanation.
