### ISSUE TITLE
Failure to build chapter doesn't immediately stop book from building

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#920]
Instead, it fails later when assembling the entire book. For example, in Mastering Shiny if the `scaling-test.Rmd` chapter has an error, the build process completes but gives a less informative error:

```
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... mapply -> <Anonymous> -> read_utf8 -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file 'scaling-testing.md': No such file or directory
Warning message:
In file.rename(unlist(meta)[move], files_md[move]) :
  cannot rename file 'scaling-testing.md' to '_book/scaling-testing.md', reason 'No such file or directory'
```

And then to find the source of the error I have to scroll up through a very large amount of output to find:

```
label: unnamed-chunk-2
Quitting from lines 11-12 (scaling-testing.Rmd) 
Error in eval(expr, envir, enclos) : !
Calls: local ... handle -> withCallingHandlers -> withVisible -> eval -> eval
```

It would be better to fail earlier.

**Comment by hadley** [comment]
Just to give you a sense of how annoying this is. Here's a link to a ~3,000 line log file I need to scroll through to figure out why the book failed to build: https://gist.github.com/hadley/04f96d091364fdd198031e078cdb1b1e

**Comment by cderv** [comment]
When I try to compile the mastering shiny book, I encounter some errors and it stops the rendering process. See here: https://gist.github.com/cderv/fa5c3a105a90a783a5e4defadfcb3499

If I try with bookdown demo book by introducing an error in _02-literature.Rmd_ for example, it will stop the rendering of the book at this chapter without processing any further. 

So it seems it is not something generic about bookdown, and could be specific to a setup. 

I was wondering if this was interactive vs non-interactive but running 
```cmd
Rscript.exe -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
```
in terminal also throws the error at the chapter, and do not build the all book. 

Did I miss anything ? Is this is happening for you no matter the book ?

**Comment by hadley** [comment]
I normally run the book via RStudio, which generates ` rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8')`. But even if I run `bookdown::render_book("index.Rmd", "bookdown::gitbook")`, it still continues when I introduce an error in an early chapter.

```
[master] > packageVersion("bookdown")
[1] ‘0.21’
[master] > packageVersion("rmarkdown")
[1] ‘2.4.4’
[master] > packageVersion("knitr")
[1] ‘1.30’
```

I have the same problem with R4DS.

**Comment by cderv** [comment]
I can't reproduce this unfortunatly - I tried on Windows and on Ubuntu with the Mastering Shiny book by cloning the repo. Everytime I have an error within one the file, it stops the rendering at that file. I tried with `render_book` and with `render_site`
It does not process the all book. I don't have a Mac to try but I don't see why this would be OS related. 

Steps I did 
* I clone the mastering shiny book
* I installed all the dependencies
* I added a chunk in `introduction.Rmd` under `## What is Shiny ?`
````md
```{r}
stop('Creating an error to test issue #920')
```
````
* I ran `rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8')`

here is the whole result I got in the console
````r
> rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8')


processing file: index.Rmd
  |......................................................................| 100%
   inline R code fragments


output file: index.knit.md



processing file: introduction.Rmd
  |....                                                                  |   6%
  ordinary text without R code

  |........                                                              |  11%
label: unnamed-chunk-1 (with options) 
List of 1
 $ include: logi FALSE

  |............                                                          |  17%
  ordinary text without R code

  |................                                                      |  22%
label: unnamed-chunk-2
Quitting from lines 10-11 (introduction.Rmd) 
Error in eval(expr, envir, enclos) : Creating an error to test issue #920
Calls: local ... handle -> withCallingHandlers -> withVisible -> eval -> eval

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile introduction.Rmd
````

Unfortunatly, without being able to reproduce, I will have a hard time looking further - I wonder why I don't encounter this behavior if you have it in two books.

I have this 
``` r
packageVersion("bookdown")
#> [1] '0.21'
packageVersion("rmarkdown")
#> [1] '2.4.6'
packageVersion("knitr")
#> [1] '1.30'
```

Do you have special config regarding error in a Rprofile or else ? Could we try to reproduce this in an example using the [bookdown-demo](https://github.com/rstudio/bookdown-demo) example that is simple book ? That may be easier to isolate the issue.

**Comment by hadley** [comment]
That was useful, thanks! It also failed for me when run with `R --vanilla`. A bit of experimentation with my `.Rprofile` found that the problem was:

```R
options(error = rlang::entrace)
```

I use this to give better tracebacks for base errors, so it would be nice to figure out why this breaks knitr. I'm happy to look into it if you can point me to the code responsible for generating the "Execution halted" error.

**Comment by hadley** [comment]
I wonder if the root cause is using `system()` for running code in another process — in callr, I think we automatically bubble up the error message into the parent process so you can access the full trace back.

**Comment by cderv** [comment]
Thanks, I'll investigate further with that option activated. I'll get back to you.

**Comment by cderv** [comment]
Regarding the Execution halted, I believe this comes from R here:
https://github.com/wch/r-source/blob/a48c6bea1353ce9b79beee0022a19ceeae822162/src/main/main.c#L342

Bookdown call `Rscript` using `system2()` to run an R script `render_one.R` that will call the `rmarkdown::render()`. Traceback is 
```r
> traceback()
8: stop("Failed to compile ", file)
7: Rscript_render(f, render_args, render_meta, add1, add2)
6: render_new_session(files, main, config, output_format, clean, 
       envir, ...)
5: render_book("index.Rmd", output_format = output_format, envir = envir)
4: render_book_script(output_format, envir, quiet)
3: in_dir(input, render_book_script(output_format, envir, quiet))
2: generator$render(input_file = input_file, output_format = output_format, 
       envir = envir, quiet = quiet)
1: rmarkdown::render_site(output_format = "bookdown::pdf_book", 
       encoding = "UTF-8")
```

That would mean the use of `rlang::entrace` prevent the error to halt the execution of `Rscript` and from bookdown point of view the `Rscript_render` call did not failt. 

Could this be the source of the error ? 
Could this be the cause ?

**Comment by yihui** [comment]
> I wonder if the root cause is using `system()` for running code in another process

It is indeed a `system()` call, and it should thrown an error if the exit status is non-zero. My current guess is that your setting affected the exit status, and it became `0` even if there was an error. I'm not familiar with `rlang::entrace`, so I'm not sure.

**Comment by cderv** [comment]
I can now reproduce by using `options(error = rlang::entrace)` **if I put it in my .Rprofile**. That is because bookdown calls `Rscript` that will load the site files. 

I think we narrowed down the issue now. @hadley you know better `rlang::entrace`, do you see why it happens this way ?

**Comment by cderv** [comment]
And here is the reprex of the underlying issue in bookdown 
``` r
res <- xfun::Rscript(
  shQuote(c("--vanilla", "-e", 'stop("An error")'))
)
res
#> [1] 1
res <- xfun::Rscript(
  shQuote(c("--vanilla", "-e", 'options(error = rlang::entrace); stop("An error")'))
)
res
#> [1] 0
```

<sup>Created on 2020-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

First case throws 1 as a result, hence bookdown knows there is an error. Second throws 0 as a result, so bookdown does not know there is an error.

**Comment by cderv** [comment]
Last precision: this is not an issue with only `system`. Here is what I got if I use `callr::rscript` which uses `processx::run`
``` r
temp_r <- tempfile()
xfun::write_utf8(c('stop("An error")'), temp_r)

# will error
res <- callr::rscript(temp_r, "--vanilla")
#> Error: An error
#> Execution halted
#> Error in (function (command = NULL, args = character(), error_on_status = TRUE, : System command 'Rscript' failed, exit status: 1, stdout & stderr were printed

# res was not created
res
#> Error in eval(expr, envir, enclos): object 'res' not found

temp_r <- tempfile()
xfun::write_utf8(c('options(error = rlang::entrace)', 'stop("An error")'), temp_r)
# will not error on our console
res <- callr::rscript(temp_r, "--vanilla")
#> Error: An error
str(res)
#> List of 5
#>  $ status : int 0
#>  $ stdout : chr ""
#>  $ stderr : chr "Error: An error\n"
#>  $ timeout: logi FALSE
#>  $ command: chr [1:3] "/usr/lib/R/bin/Rscript" "/tmp/RtmpV57zmp/file24f25c9e5c96" "--vanilla"
```

<sup>Created on 2020-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

First case without `rlang`, _rscript_ is correctly throwing an error that callr throws to us. Second case, there is no error thrown in R but Rscript was indeed with an error.

**Comment by cderv** [comment]
Same in terminal also in Ubuntu
```sh
$ /usr/lib/R/bin/Rscript --vanilla  -e "stop('An error')"
Error: An error
Execution halted
$ /usr/lib/R/bin/Rscript --vanilla  -e "options(error = rlang::entrace);stop('An error')"
Error: An error
```

**Comment by hadley** [comment]
Yeah, it's ok with `callr::r()` which is why we haven't noticed this before:

``` r
callr::r(function() {
  options(error = rlang::entrace)
  stop("Hi!")
})
#> Error: callr subprocess failed: Hi!
```

<sup>Created on 2020-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I'll figure out what's going on on the `entrace` side.

**Comment by hadley** [comment]
(If you run `callr::r()` interactively, you'll notice that it allows you to get at the traceback of the failure in the child process)

**Comment by cderv** [comment]
Oh I did not know that. That is insteresting ! It is clearly useful for debugging. Thanks for sharing.

**Comment by lionel-** [comment]
Unlike calling handlers, `options(error = )` handlers do not have a concept of declining to handle an error. So R sets the status to 0 when such a handler is set.

`rlang::entrace()` now removes itself from `options(error = )` to work around this.

**Comment by cderv** [comment]
Thanks @lionel- ! I confirm this is now working from bookdown. 
Thanks for the report @hadley.
