### ISSUE TITLE
Use git commit SHA as `date`

### ISSUE THREAD

**Issue by umarcor** [rstudio/bookdown#926]
According to https://bookdown.org/yihui/rmarkdown-cookbook/update-date.html, it is possible to set `date` dynamically through `Sys.Date()` or `Sys.time()`. However, it seems not possible to use other R features. In the body of the document, I could use `r system("git rev-parse HEAD", intern=TRUE)`, but it seems not to work in the metadata.

**Comment by yihui** [comment]
Could you read and follow [the issue guide](new) exactly to provide all the required information? As requested, please do not ignore or delete the issue guide in your post, otherwise it is usually hard for us to help you. Thanks!

**Comment by umarcor** [comment]
- [x I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

For a reproducible example, add the following the metadata in to https://github.com/LarsAsplund/github-facts/blob/main/01-index.Rmd:

```
date: "`r system("git rev-parse HEAD", intern=TRUE)`"
```

It will produce:

```
Rscript \
  -e "bookdown::render_book('00-index.Rmd', 'bookdown::gitbook')" \
  -e "bookdown::render_book('00-index.Rmd', 'bookdown::pdf_book')" \
  -e "bookdown::render_book('00-index.Rmd', 'bookdown::epub_book')"
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Parser error: while parsing a block mapping at line 1, column 1 did not find expected key at line 4, column 19
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```

However, it works if used in the body: https://github.com/LarsAsplund/github-facts/blob/main/01-index.Rmd#L67.

Hence, I assume it is not supported. I am just asking for confirmation.

**Comment by yihui** [comment]
It's because the YAML syntax is incorrect. Try:

```yaml
date: '`r system("git rev-parse HEAD", intern=TRUE)`'
```

If you are not sure about the single/double quotes in YAML, you may try `yaml::as.yaml` as mentioned on this page: https://bookdown.org/yihui/rmarkdown/output-formats.html

```r
cat(yaml::as.yaml(list(date = '`r system("git rev-parse HEAD", intern=TRUE)`')))
```

**Comment by umarcor** [comment]
Brilliant! Thanks a lot for the quick and effective help!
