### ISSUE TITLE
Error in grep(sprintf(" id=\"%s\"", links[i]), full, fixed = TRUE)

### ISSUE THREAD

**Issue by gingershuying** [rstudio/bookdown#93]
I am not sure whether this is problem of my `settings` or bookdown. I have tried to knit the file  with codes 
```
---
title: "Test Doc"
knit: "bookdown::render_book"
output: 
  bookdown::gitbook:
    split_by: section
---
# Chapter 1

test

## Test2

test2

```
It works fine! However when I change the section title Test2 to "R's package" or "some" Chinese characters, I can't knit the document properly. RMarkdown will complain something like 
```
Error in grep(sprintf(" id=\"%s\"", links[i]), full, fixed = TRUE) : 
  無效的多位元組字串於 '<e2><99>s package</h2>'
Calls: <Anonymous> ... split_chapters -> restore_links -> lapply -> FUN -> grep
停止執行
```

Sorry that my R complains in Mandarine. Is there a way to sort this out?

**Comment by yihui** [comment]
Please post your `sessionInfo()` when reporting issues. I guess you are using Windows, and your locale setting might be English.

BTW, don't worry about Chinese characters. I'm native Chinese.

**Comment by gingershuying** [comment]
Here is my sessionInfo
```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950 
[2] LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950
[4] LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] shiny_0.13.2      R6_2.1.2          bookdown_0.0.65   rsconnect_0.4.2.2
 [5] htmltools_0.3.5   tools_3.2.2       yaml_2.1.13       Rcpp_0.12.4      
 [9] rmarkdown_0.9.5.9 digest_0.6.9      xtable_1.8-2      httpuv_1.3.3     
[13] mime_0.4          miniUI_0.1.1     
```

**Comment by yihui** [comment]
Could you try the latest version of R?

**Comment by gingershuying** [comment]
Thank you Yihui! Bookdown works well with the newest version of R. Sorry for my careless trial.

Also, would it possible to knit rmd file organised in multiple sub folders instead of the root folder?

**Comment by yihui** [comment]
Yes, you can put Rmd files in sub folders, and you have to specify the paths in the `rmd_files` field in `_bookdown.yml`: https://bookdown.org/yihui/bookdown/usage.html Please note the default working directory for all Rmd files is the root directory of the book, though.
