### ISSUE TITLE
serve_book needs to save when there are no changes

### ISSUE THREAD

**Issue by pachamaltese** [rstudio/bookdown#954]
Hi

I keep see seeing this error when I open the project

```
> bookdown::serve_book()
Error in render_book(files, output_format, output_dir = output_dir, preview = preview_,  : 
  No input R Markdown files found from the current directory /home/pacha or in the rmd_files field of _bookdown.yml
```

I have to open any of the rmd files, which are not edited in the session, hit ctrl+s and then `serve_book()`  works

**Comment by cderv** [comment]
Hi, 

we need more information (as asked in the issue template), as an example reproducible if possible. 

It works for me when I did this: 

* Open RStudio
* Create a new bookdown project
* Close any open files
* Run `bookdown::serve_book()` in the console.

I don't have to open and save any Rmd file before that.  

> No input R Markdown files found from the **current directory /home/pacha**

It seems your working directory is your home folder. The `index.Rmd` file and other bookdown related files must be in the working directory where you run `serve_book()` unless you modify the `dir` argument in the function. 

It is just a guess but can you check that ?

**Comment by cderv** [comment]
This is possibly solves with last version of **blogdown**. Please open a new issue if this is not the case.
