### ISSUE TITLE
[Bug] Unnumbered section heading

### ISSUE THREAD

**Issue by csgillespie** [rstudio/bookdown#96]
The following give unnumbered sections:

```
### AB and CD {-}
### `AB` and CD {-}
### AB `and` CD {-}
```

However if the final word is in `computer font`, the title gets numbered.

```
### AB and `CD` {-}
```

**Comment by yihui** [comment]
Thanks for the report, and I think this is a Pandoc bug, so I filed it to https://github.com/jgm/pandoc/issues/2878

**Comment by yihui** [comment]
Turns out it is not. I think you will have to add something before `{-}` to prevent Pandoc from interpreting `{-}` as the attribute of the `code` before it, e.g. you can add a space

```md
### AB and `CD` \ {-}
```
