### ISSUE TITLE
Kindlegen no longer available

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#973]
Kindlegen no longer available: https://www.amazon.com/gp/feature.html?docId=1000765211, so may want to use `bookdown::calibre` as the recommendation at https://bookdown.org/yihui/bookdown/e-books.html#mobi and discuss `kindlegen` was an option

_Originally posted by @muschellij2 in https://github.com/rstudio/bookdown/issues/46#issuecomment-705152388_

**Comment by cderv** [comment]
We need to update the message in `kindlegen()` (maybe deprecate the function ?)

We could stay only with `calibre()` as the tool allow to convert to Mobi

Or we could also provide a new wrapper to the replacement called kindle preview 
https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765261

**Comment by yihui** [comment]
`kindlegen()` issues a warning now, and the book section has been updated accordingly. Thanks!
