### ISSUE TITLE
Correctly place the square of proof env using fenced divs environment in HTML

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown#977]
Following changes in https://github.com/rstudio/bookdown/pull/940#issuecomment-696598277_,  there is display issue in HTML with the square of the proof environment.

it happens because of the css rule currently used. 
https://github.com/rstudio/bookdown/blob/57f1217c20835d538d103244ea46ec65acc374c3/inst/resources/gitbook/css/plugin-bookdown.css#L93-L96

As using pandoc, everything is inserted between a `<p>` tag, this rule creates a floating square that is not placed where we want. Modifying the rule to add to the last `<p>` child should work for the new syntax, but there won't be a square printed in html for the old syntax... Not sure it is bug or loss...

**Comment by yihui** [comment]
I tested both syntaxes and the squares were shown correctly in the output:

![image](https://user-images.githubusercontent.com/163582/95769304-4c91c900-0c7d-11eb-954c-ac615e9c219c.png)

````
```{proof}
The characteristic function of $X\sim\mathrm{Pois}(\lambda)$ is $\varphi _{X}(t)=e^{\lambda (e^{it}-1)}$. Let $P_n=\sum_{i=1}^nX_i$. We know from Theorem \@ref(thm:chf-sum) that

\begin{equation*}
\begin{split}
\varphi _{P_{n}}(t) & =\prod_{i=1}^n\varphi _{X_i}(t) \\
& =\prod_{i=1}^n e^{\lambda_i (e^{it}-1)} \\
& = e^{\sum_{i=1}^n \lambda_i (e^{it}-1)}
\end{split}
\end{equation*}

This is the characteristic function of a Poisson random variable with the parameter $\lambda=\sum_{i=1}^n \lambda_i$. From Lemma \@ref(lem:chf-pdf), we know the distribution of $P_n$ is $\mathrm{Pois}(\sum_{i=1}^n\lambda_i)$.
```

::: {.proof}
The characteristic function of $X\sim\mathrm{Pois}(\lambda)$ is $\varphi _{X}(t)=e^{\lambda (e^{it}-1)}$. Let $P_n=\sum_{i=1}^nX_i$. We know from Theorem \@ref(thm:chf-sum) that

\begin{equation*}
\begin{split}
\varphi _{P_{n}}(t) & =\prod_{i=1}^n\varphi _{X_i}(t) \\
& =\prod_{i=1}^n e^{\lambda_i (e^{it}-1)} \\
& = e^{\sum_{i=1}^n \lambda_i (e^{it}-1)}
\end{split}
\end{equation*}

This is the characteristic function of a Poisson random variable with the parameter $\lambda=\sum_{i=1}^n \lambda_i$. From Lemma \@ref(lem:chf-pdf), we know the distribution of $P_n$ is $\mathrm{Pois}(\sum_{i=1}^n\lambda_i)$.
:::
````

**Comment by cderv** [comment]
OK not sure what happens when I tried that. Seems ok now. 

Thanks you !
